<?php

/* 
**  ========
**  WARQUEST
**  ========
**
**  Creato da wplaat
**
**  Per avere più informazioni visita il seguente indirizzo.
**  Indirizzo : www.plaatsoft.nl 
**
**  Oppure manda una email al seguente indirizzo e-mail.
**  Email   : info@plaatsoft.nl
**
**  All copyrights reserved (c) 2008-2013 PlaatSoft
*/

/*
** Some translation remarks:
** (1) Every line has the following syntax $lang['<KEY>'] = '<DESCRIPTION>';
**     Only change the <DESCRIPTION> part. Leave the rest unchanged.
** (2) The <DESCRIPTION> part contain %s tags. DO NOT REMOVE THEN.
**     The %s are realtime replace with game parameters. 
**     For example: 'Restore for %s dollari' will be on screen 'Restore for 100 dollari'
** (3) The LINK keys contain the menu items of the game. Choose as short as possible words.
** (4) Leave HTML tags unchanged, for example <b>, </b>, etc....
**
** Good luck and have fun!
*/

/*
** ------------------
** Language: Italian
** ------------------
*/
 
/*
** ------------------
** LINK
** ------------------
*/

/* Login */
$lang['LINK_LOGIN']  = 'Login'; 
$lang['LINK_REGISTER'] = 'Registrazione'; 
$lang['LINK_RECOVER'] = 'Recupero'; 
$lang['LINK_MANUAL'] = 'Manuale'; 
$lang['LINK_RSS']  = 'RSS'; 

/* Generale */
$lang['LINK_HOME'] = 'Home';
$lang['LINK_MISSIONS'] = 'Missioni';
$lang['LINK_BATTLE'] = 'Lotta';
$lang['LINK_UNITS']  = 'Unità';
$lang['LINK_BUILDINGS']  = 'Edifici';
$lang['LINK_BANKS'] = 'Banche';
$lang['LINK_ALLIANCE'] = 'Alleanze';
$lang['LINK_PLAYER'] = 'Giocatore';
$lang['LINK_MONEY'] = 'Soldi';
$lang['LINK_HELP'] = 'Aiuto';
$lang['LINK_ADMIN'] = 'Admin';

$lang['LINK_FIRST']  = 'Primo';
$lang['LINK_PREVIOUS'] = 'Precedente';
$lang['LINK_NEXT'] = 'Prossimo';
$lang['LINK_LAST'] = 'Ultimo';

/* Home */
$lang['LINK_RESTORE'] = 'Ricarica';
$lang['LINK_REPAIR'] = 'Ripara';
$lang['LINK_ACTIVATE'] = 'Attiva';

$lang['LINK_EARTH'] = 'Terra';
$lang['LINK_MOON'] = 'Luna';
$lang['LINK_MARS'] = 'Marte';

/* Giocatore */
$lang['LINK_OVERVIEW'] = 'Riepilogo';
$lang['LINK_DELETE'] = 'Cancella';
$lang['LINK_SETTINGS'] = 'Impostazioni';
$lang['LINK_NEWS'] = 'Info';
$lang['LINK_COMMENTS'] = 'Messaggi';
$lang['LINK_STATISTICS'] = 'Statistiche';
$lang['LINK_LOGOUT'] = 'Esci';
$lang['LINK_EDIT'] = 'Edit';
$lang['LINK_SAVE'] = 'Salva';
$lang['LINK_REPLY'] = 'Rispondi';
$lang['LINK_PROFILE'] = 'Profilo';
$lang['LINK_SKILLS'] = 'Skill';
$lang['LINK_RECRUIT']  = 'Invita';
$lang['LINK_INCREASE'] = 'Aumenta';
$lang['LINK_DECREASE'] = 'Diminuisci';
$lang['LINK_RESTORE_NOW']  = 'Ricarica per %s dollari';
$lang['LINK_CHANGE'] = 'Cambia';
$lang['LINK_REPORT'] = 'Segnala';
$lang['LINK_BOUNTY'] = 'Taglia';

/* Missioni */
$lang['LINK_PLAY'] = 'Gioca';
$lang['LINK_BUY_PLAY'] = 'Compra e gioca';
$lang['LINK_DO_AGAIN'] = 'Gioca ancora';

/* Lotta */
$lang['LINK_ATTACK'] = 'Attacca';
$lang['LINK_BATTLES']  = 'Lotte';
$lang['LINK_SP'] = 'Punti skill';

/* Unità */
$lang['LINK_DEPLOY'] = 'Posiziona';
$lang['LINK_DEPLOY_AGAIN'] = 'Posiziona ancora';
$lang['LINK_DISBAND']  = 'Rimuovi';
$lang['LINK_DISBAND_AGAIN']= 'Rimuovi ancora';

/* Edifici */
$lang['LINK_INCOME'] = 'Introito';
$lang['LINK_DEFENSE'] = 'Difesa';
$lang['LINK_ENERGY'] = 'Energia';
$lang['LINK_BUY'] = 'Compra';
$lang['LINK_BUY_AGAIN'] = 'Compra ancora';
$lang['LINK_SELL'] = 'Vendi';
$lang['LINK_SELL_AGAIN'] = 'Vendi ancora';

/* Banca / Borsa / Casinò */
$lang['LINK_BANK'] = 'Banca';
$lang['LINK_STOCKEXCHANGE'] = 'Borsa';
$lang['LINK_CASINO'] = 'Casinò';

$lang['LINK_DEPOSIT']  = 'Deposita';
$lang['LINK_WITHDRAW'] = 'Ritira';
$lang['LINK_BALANCE']  = 'Bilancio';

/* Alleanza */
$lang['LINK_INVITE'] = 'Invita';
$lang['LINK_PENDING'] = 'Attendono';
$lang['LINK_APPROVED'] = 'Accettato';
$lang['LINK_COMMENT']  = 'Messaggio';
$lang['LINK_BEST_PLAYER']  = 'Top-Giocatori';
$lang['LINK_BEST_COUNTRY'] = 'Top-Paesi';
$lang['LINK_DROP'] = 'Annulla';
$lang['LINK_ACCEPT'] = 'Accetta';
$lang['LINK_REJECT'] = 'Rifiuta';
$lang['LINK_SEND'] = 'Manda';
$lang['LINK_RESET']  = 'Resetta';

/* Forum */
$lang['LINK_FORUM']  = 'Forum';
$lang['LINK_POLLS'] = 'Sondaggi';
$lang['LINK_CHATROOM'] = 'Chat';
$lang['LINK_SEARCH']  = 'Cerca';

/* Aiuto */
$lang['LINK_GENERAL']  = 'Istruzioni';
$lang['LINK_NOTES']  = 'Note-rilascio';
$lang['LINK_RANKS']  = 'Gradi';
$lang['LINK_AWARDS'] = 'Premi';
$lang['LINK_LEVELS']  = 'Livelli';
$lang['LINK_STATS']  = 'Statistiche';
$lang['LINK_DONATE']  = 'Dona';
$lang['LINK_ABOUT']  = 'Info';

/*
** ------------------
** GENERALE 
** ------------------
*/

$lang['SYSTEM_HACK_DETECTED'] = 'Per favore, non usare il pulsante di aggiornamento pagina!';

$lang['AGO_DAY']   = ' giorno';	
$lang['AGO_DAYS']  = ' giorni';
$lang['AGO_HOUR']  = ' ora';
$lang['AGO_HOURS'] = ' ore';
$lang['AGO_MIN']   = ' minuto';
$lang['AGO_MINS']  = ' minuti';
$lang['AGO_SEC']   = ' secondo';
$lang['AGO_SECS']  = ' secondi';

$lang['COPYRIGHT'] = 'Copyright © 2008-2013 - Tutti i diritti riservati - <a target="new" href="http://www.plaatsoft.nl">PlaatSoft</a>';	

$lang['STATUS_CASH']  = 'Contante';
$lang['STATUS_EXP']  = 'Esp.';
$lang['STATUS_LEVEL']  = 'Livello';
$lang['STATUS_HEALTH'] = 'Salute';
$lang['STATUS_ENERGY'] = 'Energia';
$lang['STATUS_AMMO'] = 'Munizioni';
$lang['STATUS_ALLIANCE_SIZE'] = 'Grandezza alleanza';

$lang['BOX_INFO'] = 'INFO';
$lang['BOX_WARN'] = 'ATTENZIONE';
$lang['BOX_ERROR'] = 'ERRORE';

$lang['GENERAL_NEXT_LEVEL'] = 'Magnifico! Hai raggiunto il livello successivo! Hai ricevuto %s punti skill e %s dollari. La tua salute, energia e munizioni sono state ricaricate. ';
$lang['GENERAL_BATTLE_LEVEL'] = 'Magnifico! Hai vinto %s battaglie e ricevuto %s punti skill extra e %s dollari.';
$lang['GENERAL_BOUNTY_LEVEL'] = 'Ottimo! Hai messo %s taglie sulla testa e hai ricevuto %s punti skill extra e %s dollari.';
$lang['GENERAL_REBEL_LEVEL'] = 'Ottimo! Hai iniziato %s rivolte e hai ricevuto %s punti skill extra e %s dollari.';
$lang['GENERAL_BATTLE_AWARD_WON'] = 'lotte vinte';
$lang['GENERAL_BOUNTY_AWARD_WON'] = 'taglie messe';
$lang['GENERAL_REBEL_AWARD_WON'] = 'rivolte iniziate';
$lang['GENERAL_UNLOCK'] = 'Sbloccato al livello %s';
$lang['GENERAL_NEW_FEATURES'] = 'Le seguenti novità sono state sbloccate:';
$lang['GENERAL_RECEIVED_AWARD'] = 'Ricevuto premio:';

$lang['GENERAL_ATTACK'] = 'attacco';
$lang['GENERAL_DEFENSE'] = 'difesa';
$lang['GENERAL_INCOME']  = 'introito';
$lang['GENERAL_ENERGY']  = 'energia';
$lang['GENERAL_EXPERIENCE']  = 'esperienza';
$lang['GENERAL_DOLLAR']  = 'dollaro';
$lang['GENERAL_ALLIANCE_SIZE'] = 'grandezza alleanza';
$lang['GENERAL_EXPERIENCE_POINTS'] = 'punti esperienza';
$lang['GENERAL_UPKEEP'] = 'Costo orario';
$lang['GENERAL_BANK']  = 'Banca';
$lang['GENERAL_DEPLOYED']  = 'posizionati';

$lang['GENERAL_PLAYER']  = 'Giocatore';
$lang['GENERAL_LEVEL'] = 'Livello';
$lang['GENERAL_ALLIANCE']  = 'Alleanza';
$lang['GENERAL_WON'] = 'Vinto';
$lang['GENERAL_LOST']  = 'Perso';
$lang['GENERAL_AMOUNT'] = 'Quantità';
$lang['GENERAL_DATE'] = 'Data';
$lang['GENERAL_TRANSACTION'] = 'Transazione';
$lang['GENERAL_BALANCE'] = 'Bilancio';
$lang['GENERAL_APPROVED'] = 'Approvato';
$lang['GENERAL_EMAIL'] = 'Email';
$lang['GENERAL_TOP']	= 'Top';
$lang['GENERAL_EXP'] = 'Esperienza';
$lang['GENERAL_COUNTRY'] = 'Paese';
$lang['GENERAL_PLAYERS'] = 'Giocatori';
$lang['GENERAL_WONS']  = 'Vinto';
$lang['GENERAL_LOSTS'] = 'Perso';
$lang['GENERAL_NO'] = 'No';
$lang['GENERAL_YES'] = 'Sì';
$lang['GENERAL_AGO'] = 'Fa';
$lang['GENERAL_MESSAGE'] = 'Messaggio';
$lang['GENERAL_ACTION'] = 'Azione';
$lang['GENERAL_NUMBER'] = 'Nr.';
$lang['GENERAL_DISCOUNT'] = 'Sconto edificio';
$lang['GENERAL_REQUESTS'] = 'Richieste';
$lang['GENERAL_EP'] = 'Punti skill';
$lang['GENERAL_AWARD'] = 'Premio';
$lang['GENERAL_LANGUAGE'] = 'Lingua';
$lang['GENERAL_RANKING'] = 'Gradi';

$lang['GENERAL_NEW_UNIT'] = 'NUOVA UNITà';
$lang['GENERAL_NEW_BUILDING'] = 'NUOVO EDIFICIO';
$lang['GENERAL_NEW_MISSION'] = 'NUOVA MISSIONE';
$lang['GENERAL_GAIN'] = 'guadagno';

$lang['GENERAL_BOUNTY'] = 'Taglia';
$lang['GENERAL_INTELLIGENCE'] = 'intelligence';
$lang['GENERAL_SPIES'] = 'spie';
$lang['GENERAL_MAINTENANCE'] = 'Manutenzione unità';

$lang['GENERAL_CNTRY'] = 'Paese';
$lang['GENERAL_TOPICS'] = 'argomenti'; 
$lang['GENERAL_FORUM'] = 'Forum';
$lang['GENERAL_MESSAGES'] = 'messaggi';
$lang['GENERAL_LAST_MESSAGE'] = 'Ultimo messaggio';
$lang['GENERAL_FORUM_MODERATED'] = '(Moderato da %s)';
$lang['GENERAL_NOT_MODERATED'] = '(Non moderato)';
$lang['GENERAL_BY'] = 'fa';
$lang['GENERAL_TOPIC'] = 'Topic';
$lang['GENERAL_LOCKED'] = 'Chiuso';
$lang['GENERAL_WORLDMAP'] = 'Cartina mondo';
$lang['GENERAL_PLAATSOFT'] = 'PlaatSoft';
$lang['GENERAL_CONQUER'] = 'Conquista';

$lang['GENERAL_ST'] = '%so';
$lang['GENERAL_ND'] = '%so';
$lang['GENERAL_TH'] = '%so';

$lang['GENERAL_CONTINENT'] = 'Continente';
$lang['GENERAL_CONQUERED'] = 'Conquistato';

$lang['GENERAL_IDLE'] = 'Standby';
$lang['GENERAL_ACTIVE'] = 'Attivo';
$lang['GENERAL_INACTIVE'] = 'Inattivo';

$lang['GENERAL_PLANET'] = 'Pianeta';
$lang['GENERAL_PLANET_1'] = 'Terra';
$lang['GENERAL_PLANET_2'] = 'Luna';
$lang['GENERAL_PLANET_3'] = 'Marte';

/*
** ------------------
** Consigli
** ------------------
*/

$lang['TIP_GENERAL']  = 'CONSIGLI';
$lang['TIP_0'] = 'Gioca la missione d\'allenamento per ricevere punti esperienza e raggiungere il livello successivo.';
$lang['TIP_1'] = 'Compra delle unità e inizia ad allenarti nelle lotte per ricevere punti esperienza.';
$lang['TIP_2'] = 'Usa i punti skill ricevuti (Home -> Skill) per migliorare le abilità del tuo soldato.';
$lang['TIP_3'] = 'Inserisci la tua mail per ricevere notifiche sui messaggi e sulle alleanze!';
$lang['TIP_4'] = 'Compra degli edifici da introito per generare introito ogni ora.';
$lang['TIP_5'] = 'Compra degli edifici da difesa per migliorare la potenza della tua difesa.';
$lang['TIP_6'] = 'Alleati con altri giocatori per migliorare la potenza del tuo attacco o della tua difesa.';
$lang['TIP_7'] = 'Deposita il tuo contante nella Banca Nazionale per tenerlo al sicuro da altri giocatori.';
$lang['TIP_8'] = 'Ricevi punti esperienza extra votando nei sondaggi attivi!';
$lang['TIP_9'] = 'Metti taglie sulla testa di altri giocatori per ricevere premi sulle taglie  messe.';
$lang['TIP_10'] = 'Visita il casinò per giocare alla Ruota della Fortuna e vincere più contante.';
$lang['TIP_11'] = 'Compra edifici energetici per recuperare energia rapidamente.';
$lang['TIP_12'] = 'Compra unità Intel per spiare altri giocatori e per iniziare rivolte nei loro continenti.';
$lang['TIP_13'] = 'Deposita denaro contante nella banca Trasquera per ricevere interessi giornalieri.';
$lang['TIP_14'] = 'Visita il forum. Nuove idee sul gioco sono ben accettate!';
$lang['TIP_15'] = 'Guarda la sezione Aiuto per avere più informazioni.';
$lang['TIP_16'] = 'Compra/vendi azioni per avere più profitto (Soldi -> Borsa)';
$lang['TIP_17'] = 'Deposita denaro contante nella banca Swisscore per ricevere interessi giornalieri.';
$lang['TIP_18'] = 'Completa tutte le missioni del continente per ricevere punti skill extra.';
$lang['TIP_19'] = 'Ripara le unità (Home -> Ricarica) per prevenire la perdita di unità';
$lang['TIP_20'] = 'Visita il casinò per giocare alla Slot Machine e vincere più contante.';
$lang['TIP_21'] = 'Ripara gli edifici (Home -> Ricarica) per prevenire la perdita degli edifici';
$lang['TIP_22'] = 'Continua a giocare il gioco e diventa il miglior giocatore del tuo paese!';

$lang['TIP_90'] = 'Ancora 10 livelli prima di iniziare la tua colonia sulla Luna.';
$lang['TIP_91'] = 'Ancora 9 livelli prima di iniziare la tua colonia sulla Luna.';
$lang['TIP_92'] = 'Ancora 8 livelli prima di iniziare la tua colonia sulla Luna.';
$lang['TIP_93'] = 'Ancora 7 livelli prima di iniziare la tua colonia sulla Luna.';
$lang['TIP_94'] = 'Ancora 6 livelli prima di iniziare la tua colonia sulla Luna.';
$lang['TIP_95'] = 'Ancora 5 livelli prima di iniziare la tua colonia sulla Luna.';
$lang['TIP_96'] = 'Ancora 4 livelli prima di iniziare la tua colonia sulla Luna.';
$lang['TIP_97'] = 'Ancora 3 livelli prima di iniziare la tua colonia sulla Luna.';
$lang['TIP_98'] = 'Ancora 2 livelli prima di iniziare la tua colonia sulla Luna.';
$lang['TIP_99'] = 'Ancora 1 livello prima di iniziare la tua colonia sulla Luna.';
$lang['TIP_100'] = 'Costruisci la tua colonia sulla Luna!';

$lang['TIP_140'] = 'Ancora 10 livelli prima di iniziare la tua colonia su Marte.';
$lang['TIP_141'] = 'Ancora 9 livelli prima di iniziare la tua colonia su Marte.';
$lang['TIP_142'] = 'Ancora 8 livelli prima di iniziare la tua colonia su Marte.';
$lang['TIP_143'] = 'Ancora 7 livelli prima di iniziare la tua colonia su Marte.';
$lang['TIP_144'] = 'Ancora 6 livelli prima di iniziare la tua colonia su Marte.';
$lang['TIP_145'] = 'Ancora 5 livelli prima di iniziare la tua colonia su Marte.';
$lang['TIP_146'] = 'Ancora 4 livelli prima di iniziare la tua colonia su Marte.';
$lang['TIP_147'] = 'Ancora 3 livelli prima di iniziare la tua colonia su Marte.';
$lang['TIP_148'] = 'Ancora 2 livelli prima di iniziare la tua colonia su Marte.';
$lang['TIP_149'] = 'Ancora 1 livello prima di iniziare la tua colonia su Marte.';
$lang['TIP_150'] = 'Costruisci la tua colonia su Marte!';

/*
** ------------------
** PAGINA LOGIN
** ------------------
*/

$lang['LOGIN_MEMBER_TITLE'] = 'Login utente';
$lang['LOGIN_REGISTER_TITLE'] = 'Registrazione gratuita';
$lang['LOGIN_RECOVER_TITLE'] = 'Recupero password';
$lang['LOGIN_MANUAL_TITLE'] = 'Manuale';

$lang['LOGIN_PLAYERS'] = 'giocatore';
$lang['LOGIN_REQUESTS'] = 'richieste';
$lang['LOGIN_COUNTRIES'] = 'paesi';
$lang['LOGIN_ONLINE'] = 'giocatori online';

$lang['LOGIN_PASSWORD'] = 'Password';
$lang['LOGIN_USERNAME'] = 'Nome utente';
$lang['LOGIN_EMAIL'] = 'Email';
$lang['LOGIN_NICKNAME']  = 'Nickname';

$lang['LOGIN_MAINTENANCE_TITLE'] = 'Manutenzione server';
$lang['LOGIN_MAINTENANCE'] = 'Al momento, siamo in fase di manutenzione server. Per favore, torna fra 30 minuti. Grazie!';

$lang['LOGIN_LOGOUT'] = 'Ora sei disconnesso!'; 
$lang['LOGIN_FAILED'] = 'Nome utente e/o password errati!';
$lang['LOGIN_REGISTER_OK'] = 'Account utente %s è stato creato!';
$lang['LOGIN_PASSWORD_TO_SHORT'] = 'La password dev\'essere lunga almeno 6 caratteri!';
$lang['LOGIN_USERNAME_TO_SHORT'] = 'Il nome utente dev\'essere lungo almeno 4 cratteri!';
$lang['LOGIN_USERNAME_EXIST'] = 'Il nome utente %s esiste già!';
$lang['LOGIN_EMAIL_EXIST'] = 'Email già registrata!';
$lang['LOGIN_EMAIL_INVALID'] = 'L\'email è errato! (formato errato)';
$lang['LOGIN_NICKNAME_EXIST'] = 'Nickname %s già in uso!';
$lang['LOGIN_NICKNAME_NEEDED'] = 'Il nickname dev\'essere inserito!';
$lang['LOGIN_NEW_PASSWORD_SEND'] = 'La nuova password è stata mandata all\'indirizzo email specificato!';
$lang['LOGIN_EMAIL_UNKNOWN'] = 'E-mail sconosciuta!';
$lang['LOGIN_BEST_VIEWED'] = 'WarQuest è stato ottimizzato per i seguenti sistemi mobili: "Apple iOS/iPad, Nokia Symbian, BlackBerry OS, Android OS" e i browser internet: "Internet Esploratore, Mozilla Firefox, Apple Safari, Opera, Google Chrome". Questo gioco viene visualizzato meglio con la larghezza del browser settata a 500px. ';

$lang['LOGIN_NEW_CLIENT_TITLE'] = 'Nuovo client WarQuest disponibile!';
$lang['LOGIN_NEW_CLIENT'] = 'Stai usando un vecchio client Windows di WarQuest. Per favore visita www.plaatsoft.nl per scaricare l\'ultima versione.';

$lang['HOME_TRAVEL_TO'] = 'Vai a';

/*
** ------------------
** HOME - OVERVIEW
** ------------------
*/

$lang['HOME_TITLE'] = 'HOME';

$lang['HOME_FLASH_NEWS_TITLE'] = 'Notizie dell\'ultima ora';

$lang['HOME_LASTEST_FORUM_ITEM'] = 'Post più recente nel forum';

$lang['HOME_INTRO_PLAYERS'] = 'Al momento %s giocatori da %s paesi sono attivi, ';
$lang['HOME_INTRO_FIGHTS'] = '%s lotte hanno avuto luogo e ';
$lang['HOME_INTRO_REQUESTS'] = '%s richieste server sono state eseguite. ';
		
$lang['HOME_INTRO_TITLE'] = 'Introduzione';
$lang['HOME_INTRO_MISSIONS'] = 'Inizia il gioco completando %s ';
$lang['HOME_INTRO_BATTLES'] = 'e lottando %s. ';
$lang['HOME_INTRO_UNITS'] = 'Quando guadagni soldi e punti esperienza puoi comprare %s più avanzate ';
$lang['HOME_INTRO_BUILDINGS'] = ' e %s per diventare più forte. ';
$lang['HOME_INTRO_ENEMY'] = 'In ogni momento altri giocatori possono attaccarti, quindi migliora sempre la tua difesa.';

$lang['HOME_NEW_ANDROID_VERSION'] = 'Nuova versione app v%s è disponibile al Market Android.<br/>Per favore aggiornate il client!';
$lang['HOME_NEW_WINDOWS_VERSION'] = 'Nuovo client Windows di WarQuest v%s è disponibile!';
$lang['HOME_CLICK_HERE'] = 'qui';
$lang['HOME_CLICK_TEXT'] = 'Clicca %s per iniziare a scaricarlo.';
$lang['HOME_EMAIL_MISSING'] = 'Per favore inserisci la tua email per ricevere messaggi dai giocatori tramite mail e per il recupero della password.';
$lang['HOME_DAILY_BONUS'] = 'Hai trovato %s dollari nella zona di un nemico!';

$lang['HOME_WELCOME'] = 'Benvenuto';
$lang['HOME_LAST_LOGIN'] = 'L\'ultima visita è stata <b>%s</b> fa.';
$lang['HOME_AWARDS'] = 'Premi';
$lang['HOME_BATTLE_AWARDS_TEXT'] = 'Hai guadagnato i seguenti premi Lotta:';
$lang['HOME_BOUNTY_AWARDS_TEXT'] = 'Hai guadagnato i seguenti premi Taglia:';
$lang['HOME_REBEL_AWARDS_TEXT'] = 'Hai guadagnato i seguenti premi Rivolta:';
$lang['HOME_OVERVIEW_TITLE']= 'Riepilogo';
$lang['HOME_MAP_TITLE'] = 'Continenti conquistati';
$lang['HOME_MAP_NOTE'] = 'Ogni continente consiste in tre regioni che possono essere conquistate attraverso le missioni.';

$lang['HOME_INTRO_PLACE1'] = 'Sei al <b>%so</b> posto nella tabella generale dei giocatori '; 
$lang['HOME_INTRO_PLACE2'] = 'e al <b>%so</b> posto sulla tabella  dell\'<b>%s</b>. '; 
$lang['HOME_PLAYERS_ONLINE'] = 'Nelle ultime 24 ore %s giocatori erano online.';

/*
** ------------------
** HOME - PROFILE
** ------------------
*/

$lang['PLAYER_TITLE'] = 'GIOCATORE';
$lang['PLAYER_WIN_LOST_RATE'] = 'Rateo vinto/perso';
$lang['PLAYER_BUILDINGS'] = 'Edifici';
$lang['PLAYER_CASH_FLOW'] = 'Flusso contante';
$lang['PLAYER_ALLIANCE_SIZE'] = 'Grandezza alleanza';
$lang['PLAYER_EXP_POINTS']  = 'Punti esperienza';
$lang['PLAYER_SERVER_REQUEST']  = 'Richieste server';
$lang['PLAYER_MISSION_COMPLETED'] = 'Missione completata';
$lang['PLAYER_DEFENSE_STRENGTH']  = 'Potenza difesa';
$lang['PLAYER_ATTACK_STRENGTH'] = 'Potenza attacco';
$lang['PLAYER_FIGHTS_LOST'] = 'Lotte perse';
$lang['PLAYER_FIGHTS_WON']  = 'Lotte vinte';
$lang['PLAYER_BUILDING_INCOME'] = 'Introito edifici';
$lang['PLAYER_CONTINENT_INCOME'] = 'Introito continente';
$lang['PLAYER_BOUNTY_SET'] = 'Taglie messe';
$lang['PLAYER_REBELLION_RISE'] = 'Rivolte iniziate';
$lang['PLAYER_UPKEEP']  = 'Costo orario unità';
$lang['PLAYER_NETTO_INCOME']  = 'Introito netto';
$lang['PLAYER_STATISTICS']  = 'Statistiche'; 
$lang['PLAYER_DISCOUNT_MAINTENANCE']  = 'Sconto & Manutenzione';
$lang['PLAYER_NAME']  = 'Nome'; 
$lang['PLAYER_ID']  = 'Identità';
$lang['PLAYER_RANK']  = 'Grado'; 
$lang['PLAYER_OVERVIEW']  = 'Profilo'; 
$lang['PLAYER_DISCOUNT_RATE'] = 'Sconto edifici';
$lang['PLAYER_MAINTENANCE_RATE'] = 'Manutenzione unità';
$lang['PLAYER_LAST_LOGIN'] = 'Ultima volta attivo (fa)';
$lang['PLAYER_CREATED'] = 'Creato (fa)';
$lang['PLAYER_CASINO_PLAYED']  = 'Giocato al casinò';
$lang['PLAYER_ADS_SHOWED']  = 'Pubblicità mostrate';

$lang['PLAYER_ATTACK_FORCE'] = 'Riepilogo (%s Attacco %s)';
$lang['PLAYER_DEFENSE_FORCE'] = 'Riepilogo (%s Difesa %s)';
$lang['PLAYER_ATTACK_TEXT'] = '%s ha al momento <b>%s</b> alleati e può commandare max <b>%s</b> unità. L\'attacco %s ha le seguenti unità:';
$lang['PLAYER_DEFENSE_TEXT'] = '%s ha al momento <b>%s</b> alleati e può comandare max <b>%s</b> unità. La difesa %s ha le seguenti unità:';
$lang['PLAYER_UNIT'] = 'Unità';
$lang['PLAYER_AMOUNT'] = 'Quantità';
$lang['PLAYER_STRENGTH'] = 'Potenza';
$lang['PLAYER_ATTACK_SKILLS'] = 'Skill attacco';
$lang['PLAYER_DEFENSE_SKILLS'] = 'Skill difesa';
$lang['PLAYER_SUB_TOTAL'] = 'Sub totale';
$lang['PLAYER_TOTAL'] = 'Totale';
$lang['PLAYER_FORCE'] = 'Potenza attacco e difesa'; 
$lang['PLAYER_DEPLOYED'] = 'Posizionato';

$lang['PLAYER_BUILDING'] = 'Edificio';
$lang['PLAYER_INCOME'] = 'Introito';
$lang['PLAYER_COST'] = 'Costo';
$lang['PLAYER_BUILDING_OVERVIEW'] = 'Riepilogo introito edifici';
$lang['PLAYER_BUILDING_TEXT'] = 'Al momento, il giocatore %s ha i seguenti edifici da introito %s :';
$lang['PLAYER_UPKEEP_COST'] = 'Riepilogo costo orario';
$lang['PLAYER_UPKEEP_TEXT'] = 'Al momento, il giocatore %s possiede le seguenti unità %s :';
$lang['PLAYER_CONTINENT_OVERVIEW'] = 'Riepilogo introito continente';
$lang['PLAYER_CONTINENT_TEXT'] = 'Il giocatore %s ha conquistato i seguenti continenti %s :';

$lang['PLAYER_SPY_1'] = 'intel';
$lang['PLAYER_SPY_2'] = 'esploratori';
$lang['PLAYER_SPY_3'] = 'esploratori';
$lang['PLAYER_SPY_4'] = 'esploratori';
$lang['PLAYER_SPY_5'] = 'esploratori';

$lang['PLAYER_ESPIONAGE_UNLOCK1'] = 'Sbloccato quando la tua potenza %s è %s% superiore a quella dell\'avversario.';
$lang['PLAYER_ESPIONAGE_UNLOCK2'] = 'Sbloccato quando la potenza del tuo %s è uguale o superiore a quella dell\'avversario.';

$lang['PLAYER_MONEY_STATUS'] = 'Possedimenti attuali';
$lang['PLAYER_CASH_MONEY'] = 'Contante';
$lang['PLAYER_BANK'] = 'Banca';

$lang['PLAYER_PLATFORM_BROWSER'] = 'Piattaforma e browser';
$lang['PLAYER_BROWSER'] = 'Browser';
$lang['PLAYER_BROWSER_VERSION'] = 'Versione';
$lang['PLAYER_PLATFORM'] = 'Piattaforma';

$lang['PLAYER_LAST_TWEET'] = 'Ultimo tweet';

/*
** ------------------
** HOME - NEWS
** ------------------
*/

$lang['HOME_BATTLE_TITLE'] = 'Novità';
$lang['HOME_BATTLE_ATTACK_BY'] = 'Sei stato attaccato da %s di %s.';
$lang['HOME_BATTLE_YOU_WON'] = 'Hai <b>VINTO</b>. ';
$lang['HOME_BATTLE_YOU_LOST'] = 'Hai <b>PERSO</b>. ';
$lang['HOME_BATTLE_YOU_EXP'] = 'Hai guadgnato %s punti esperienza ';
$lang['HOME_BATTLE_TOOK_DAMAGE'] = 'e ricevuto %s danni.';
$lang['HOME_BATTLE_TAKING_DAMAGE'] = 'e ricevendo %s danni.';
$lang['HOME_BATTLE_YOU_MONEY'] = 'Perdendo %s dollari ';
$lang['HOME_BATTLE_NO_NEWS'] = 'Nessuna novità Lotta disponibile al momento!'; 

$lang['HOME_BOUNTY_NEWS'] = '%s ha messo %s dollari sulla tua testa. Se vieni sconfitto perderai %s punti esperienza.';

/*
** ------------------
** HOME - MESSAGE
** ------------------
*/

$lang['HOME_MESSAGES_TITLE']= 'Messaggi';
$lang['HOME_MESSAGE_DELETED'] = 'Messaggi cancellati!';
$lang['HOME_NO_MESSAGES'] = 'Nessun messaggio dai giocatori disponibile!'; 

/*
** ------------------
** HOME - SKILLS
** ------------------
*/

$lang['PLAYER_SKILL_SUBTITLE1']  = 'Punti skill';
$lang['PLAYER_SKILL_SUBTITLE2']  = 'Punti skill [%s disponibili]';
$lang['PLAYER_SKILL_NOTE']  = 'Nota: Usa punti skill per aumentare attacco, difesa, salute, energia o skill munizioni.';
$lang['PLAYER_SKILLS']  = 'Skill'; 
$lang['PLAYER_MAX'] = 'Ora'; 
$lang['PLAYER_ATTACK']  = 'ATTACCO';
$lang['PLAYER_DEFENSE'] = 'DIFESA';
$lang['PLAYER_HEALTH']  = 'SALUTE'; 
$lang['PLAYER_ENERGY']  = 'ENERGIA'; 
$lang['PLAYER_AMMO']  = 'MUNIZIONI';
$lang['PLAYER_ATTACK_TIP']  = 'Aumenta la tua skill d\'attacco per fare più danno e vincere più lotte. Ci vuole 1 punto skill per aumentare la tua potenza d\'attacco di %s. Diminuisci la tua skill d\'attacco di %s per riavere 1 punto skill.';
$lang['PLAYER_DEFENSE_TIP'] = 'Aumenta la tua skill di difesa per resistere a più attacchi. Ci vuole 1 punto skill per aumentare la tua potenza di difesa di %s. Diminuisci la tua skill di difesa di %s per riavere 1 punto skill.';
$lang['PLAYER_HEALTH_TIP']  = 'Aumenta la tua skill di salute massima per sopravvivere a lotte intense. Ci vuole 1 punto skill per aumentare il tuo livello di salute massima di 10. Diminuisci la tua salute di 20 per riavere 1 punto skill.';
$lang['PLAYER_ENERGY_TIP']  = 'Aumenta il tuo livello massimo di energia per giocare più missioni. Ci vuole 1 punto skill per aumentare il tuo livello d\'energia massima di 10. Diminuisci la tua skill d\'energia di 20 per riavere 1 punto skill.';
$lang['PLAYER_AMMO_TIP']  = 'Aumenta il tuo livello massimo di munizioni per aumentare le tue capacità di combattere. Ci vogliono 2 punti skill per aumentare le tue munizioni di 1. Diminuisci la tua skill munizioni di 1 per riavere 1 punto skill.';
$lang['PLAYER_SKILL_ACCEPTED1']  = 'Skill %s aumentata.';
$lang['PLAYER_SKILL_REJECTED1']  = 'Hai bisogno di %s punti skill per modificare questa skill.';
$lang['PLAYER_SKILL_ACCEPTED2']  = 'Skill %s diminuita.';
$lang['PLAYER_SKILL_REJECTED2']  = 'Skill %s ha raggiunto il livello minimo.';


/*
** ------------------
** HOME - RESTORE
** ------------------
*/

$lang['PLAYER_RESTORE_TITLE'] = 'Ricarica & ripara';
$lang['PLAYER_RESTORE_SUBTITLE1'] = 'Ricarica';
$lang['PLAYER_RESTORE_SUBTITLE2'] = 'Ripara';
$lang['PLAYER_RESTORE_UNLOCKED'] = 'Ricarica & ripara vengono sbloccate al livello %s.';
$lang['PLAYER_RESTORE_PRICE'] = 'Prezzo ricarica';
$lang['PLAYER_RESTORE_PRICE_PER_DAY'] = 'Prezzo ricarica giornaliero';
$lang['PLAYER_REPAIR_PRICE'] = 'Prezzo riparazioni';
$lang['PLAYER_RESTORED_FAILED'] = 'Non hai %s dollari per eseguire quest\'azione.';

$lang['PLAYER_HEALTH_TITLE'] = 'Ricarica salute';
$lang['PLAYER_HEALTH_NOTE'] = 'Paga l\'ospedale affinchè ripristini completamente la salute del tuo esercito. La ricarica può essere usata solo una volta ogni 5 minuti. La salute si ricarica anche da sola nel tempo.';	
$lang['PLAYER_HEALTH_CONDITION'] = 'Condizione salute';
$lang['PLAYER_HEALTH_RESTORED'] = 'Salute ricaricata per %s dollari.';
$lang['PLAYER_HEALTH_CONFIRM'] = 'Vuoi davvero ricaricare la salute?';

$lang['PLAYER_ENERGY_TITLE'] = 'Ricarica energia';
$lang['PLAYER_ENERGY_NOTE'] = 'Paga la compagnia petrolifera affinchè ricarichi completamente l\'energia del tuo esercito. La ricarica può essere usata solo una volta ogni 24 ore. L\'energia si ricarica anche da sola nel tempo. ';	
$lang['PLAYER_ENERGY_CONDITION'] = 'Condizione energetica';
$lang['PLAYER_ENERGY_RESTORED'] = 'Energia ricaricata per %s dollari.';
$lang['PLAYER_ENERGY_CONFIRM'] = 'Vuoi davvero ricaricare l\'energia?';

$lang['PLAYER_AMMO_TITLE'] = 'Ricarica munizioni';
$lang['PLAYER_AMMO_NOTE'] = 'Paga la fabbrica di armi per ricaricare completamente le munizioni del tuo esercito. La ricarica può essere usata solo una volta ogni 24 ore. Le munizioni si ricaricano anche da sole nel tempo.';	
$lang['PLAYER_AMMO_CONDITION'] = 'Condizione munizioni';
$lang['PLAYER_AMMO_RESTORED'] = 'Munizioni ricaricate per %s dollari.';
$lang['PLAYER_AMMO_CONFIRM'] = 'Vuoi davvero ricaricare le munizioni?';

$lang['PLAYER_CEASE_FIRE_TITLE'] = 'Armistizio';
$lang['PLAYER_CEASE_FIRE_NOTE'] = 'Paga soldi per attivare un periodo di armistizio. Durante questo periodo, altri giocatori non possono attaccarti, nè tu attaccare loro.';	
$lang['PLAYER_CEASE_FIRE_ACTIVATED'] = 'Periodo di armistizio attivato per %s dollari.';
$lang['PLAYER_CEASE_FIRE_CONFIRM'] = 'Vuoi davvero attivare il periodo d\'armistizio?';
$lang['PLAYER_HOLIDAY_TITLE'] = 'Periodo vacanza';
$lang['PLAYER_HOLIDAY_NOTE'] = 'Rilassati attivando il periodo di vacanza. Durante questo periodo il tuo account viene congelato (Missioni, Lotte, Unità ed Edifici vengono disattivati) e altri giocatori non possono attaccarti e viceversa.';	
$lang['PLAYER_HOLIDAY_ACTIVATED'] = 'Periodo vacanza attivato per %s dollari.';
$lang['PLAYER_HOLIDAY_CONFIRM'] = 'Vuoi davvero attivare il periodo vacanza?';

$lang['PLAYER_UNITS_TITLE'] = 'Ripara unità';
$lang['PLAYER_UNITS_NOTE'] = 'Ripara le unità del tuo esercito. Se la condizione delle unità arriva a 0%, alcune unità verranno distrutte e le rimanenti unità vengono riparate automaticamente.';	
$lang['PLAYER_UNITS_CONDITION'] = 'Condizione unità (CU)';
$lang['PLAYER_UNITS_REPAIRED'] = 'Le tue unità sono state riparate per %s dollari.';
$lang['PLAYER_UNITS_CONFIRM'] = 'Vuoi davvero riparare le tue unità?';

$lang['PLAYER_BUILDINGS_TITLE'] = 'Ripara edifici';
$lang['PLAYER_BUILDINGS_NOTE'] = 'Ripara gli edifici della tua base. Se la condizione degli edifici arriva a 0%, alcuni edifici verranno distrutti e gli edifici rimanenti vengono riparati automaticamente.';	
$lang['PLAYER_BUILDINGS_CONDITION'] = 'Condizione edifici (CE)';
$lang['PLAYER_BUILDINGS_REPAIRED'] = 'I tuoi edifici sono stati riparati per %s dollari.';
$lang['PLAYER_BUILDINGS_CONFIRM'] = 'Vuoi davvero riparare i tuoi edifici?';

$lang['PLAYER_REBELLION_TITLE'] = 'Ripristina la pace';
$lang['PLAYER_REBELLION_NOTE'] = 'Paga l\'intelligence per sedare rivolte imminenti nelle tue regioni conquistate. Se la Condizione Rivolta (CR) arriva al 100%, alcune regioni verranno perse a favore dei ribelli e dovrai riconquistarle.';	
$lang['PLAYER_REBELLION_CONDITION'] = 'Condizione rivolta (CR)';
$lang['PLAYER_REBELLION_RESTORED'] = 'Seda rivolta per %s dollari.';
$lang['PLAYER_REBELLION_CONFIRM'] = 'Vuoi davvero ripristinare la pace?';

/*
** ------------------
** HOME - SETTINGS
** ------------------
*/

$lang['SETTING_TITLE'] = 'Impostazioni';
$lang['SETTING_GENERAL1'] = 'Impostazioni generali 1';
$lang['SETTING_GENERAL2'] = 'Impostazioni generali 2';

$lang['SETTING_NICKNAME'] = 'Nickname WarQuest';
$lang['SETTING_TWITTER'] = 'Account Twitter';
$lang['SETTING_LANGUAGE'] = 'Lingua';
$lang['SETTING_BACKGROUND'] = "Sfondo";
$lang['SETTING_SOUND'] = 'Attiva audio (Sperimentale)';
$lang['SETTING_BOUNTY'] = 'Abilita pop-up conferma taglia.';
$lang['SETTING_RESTORE'] = 'Abilita pop-up conferma ricarica & ripara.';
$lang['SETTING_CONDITION'] = 'Abilita info Unità/Edifici/Condizione rivolta nel banner principale.';
$lang['SETTING_FORUM_SORT'] = 'Abilita post forum più recente nella pagina di riepilogo nella Home.';
$lang['SETTING_SORT1'] = 'Mostra il messaggio più recente in cima al forum.';
$lang['SETTING_SORT2'] = 'Mostra il giocatore più vecchio in cima alla lista delle lotte.';

$lang['PLAYER_LANG_ENGLISH'] = 'Inglese';
$lang['PLAYER_LANG_DUTCH'] = 'Olandese';
$lang['PLAYER_LANG_GERMAN'] = 'Tedesco';

$lang['PLAYER_GENERAL_CHANGED'] = 'Impostazioni generali cambiate!';
$lang['NICKNAME_EXIST'] = 'Nickname già in uso!';
$lang['NICKNAME_TO_SHORT'] = 'Il nickname dev\'essere lungo almeno 4 caratteri!';
$lang['NICKNAME_NO_SPACE'] = 'Space character(s) in nickname is not allowed!';

$lang['PLAYER_CHANGE_EMAIL'] = 'Impostazioni email';
$lang['PLAYER_NEW_EMAIL'] = 'Indirizzo email';
$lang['PLAYER_NOTIFICATION_ALLIANCE'] = 'Notifiche alleanza via mail';
$lang['PLAYER_NOTIFICATION_COMMENT'] = 'Notifiche messaggi via mail';
$lang['PLAYER_EMAIL_CHANGED'] = 'Impostazioni email cambiate';
$lang['PLAYER_EMAIL_EXIST'] = 'Indirizzo email già registrato!';
$lang['PLAYER_EMAIL_INVALID'] = 'Indirizzo email non valido (formato non valido)!';

$lang['PLAYER_LOGIN_SETTINGS'] = 'Impostazioni login';
$lang['PLAYER_USERNAME'] = 'Nome utente';
$lang['PLAYER_USERNAME_TO_SHORT'] = 'Il nome utente dev\'essere lungo almeno 4 caratteri!';
$lang['PLAYER_USERNAME_ALREADY_EXIST'] = 'Nome utente già in uso!';
$lang['PLAYER_USERNAME_CHANGED'] = 'Il nome utente è stato cambiato. Non dimenticare di cambiarlo nell\'app WarQuest di Android,iOS, Symbian e nel client Windows, altrimenti il login automatico non funzionerà più!';
$lang['PLAYER_CURRENT_PASSWORD'] = 'Password attuale';		
$lang['PLAYER_NEW_PASSWORD'] = 'Nuova password';
$lang['PLAYER_PASSWORD_CHANGED'] = 'La password è stata cambiata. Non dimenticare di cambiarla nell\'app WarQuest di Android, iOS, Symbian e nel client Windows, altrimenti il login automatico non funzionerà più!';
$lang['PLAYER_PASSWORD_NO_MATCH'] = 'Password attuale non corrisponde!';
$lang['PLAYER_PASSWORD_TO_SHORT'] = 'La nuova password dev\'essere lunga almeno 6 caratteri!';
$lang['PLAYER_LOGIN_NOTE'] = 'ATTENZIONE: Il login automatico funziona soltanto quando il nome utente e password sono uguali nell\'app WarQuest di Android,iOS, Symbian e nel client Windows!'; 



$lang['BACKGROUND_0'] = 'Nero';
$lang['BACKGROUND_1'] = 'Verde Militare';
$lang['BACKGROUND_2'] = 'Rosso Aurora';
$lang['BACKGROUND_3'] = 'Pietre Grigie';
$lang['BACKGROUND_4'] = 'Cerchi rosa';
$lang['BACKGROUND_5'] = 'Seta Blu';
$lang['BACKGROUND_6'] = 'Marrone';
$lang['BACKGROUND_7'] = 'Pirata';
$lang['BACKGROUND_8'] = 'Moderno';
$lang['BACKGROUND_9'] = 'Classico';
$lang['BACKGROUND_10'] = 'Cioccolato';
$lang['BACKGROUND_11'] = 'Natalizio';
$lang['BACKGROUND_12'] = 'Fuochi d\'artificio';

/*
** ------------------
** DATI MISSIONE
** ------------------
*/

/* Missioni Terra */
$lang['MISSION_GROUP_0'] = 'Allenamento';
$lang['MISSION_GROUP_1'] = 'Europa';
$lang['MISSION_GROUP_2'] = 'N-America';
$lang['MISSION_GROUP_3'] = 'S-America';
$lang['MISSION_GROUP_4'] = 'Africa';
$lang['MISSION_GROUP_5'] = 'N-Asia';
$lang['MISSION_GROUP_6'] = 'S-Asia';
$lang['MISSION_GROUP_7'] = 'E-Asia';
$lang['MISSION_GROUP_8'] = 'Oceania';
$lang['MISSION_GROUP_9'] = 'Medioriente';

/* Missioni Luna */
$lang['MISSION_GROUP_10'] = 'Alpha ';
$lang['MISSION_GROUP_11'] = 'Beta';
$lang['MISSION_GROUP_12'] = 'Charlie';
$lang['MISSION_GROUP_13'] = 'Delta';
$lang['MISSION_GROUP_14'] = 'Echo';
$lang['MISSION_GROUP_15'] = 'Foxtrot';
$lang['MISSION_GROUP_16'] = 'Golf';
$lang['MISSION_GROUP_17'] = 'Hotel';
$lang['MISSION_GROUP_18'] = 'Lima';

/* Missioni Marte */
$lang['MISSION_GROUP_20'] = 'Alpaca';
$lang['MISSION_GROUP_21'] = 'Bison';
$lang['MISSION_GROUP_22'] = 'Coyote';
$lang['MISSION_GROUP_23'] = 'Dinosaur';
$lang['MISSION_GROUP_24'] = 'Emu';
$lang['MISSION_GROUP_25'] = 'Fox';
$lang['MISSION_GROUP_26'] = 'Gnu';
$lang['MISSION_GROUP_27'] = 'Heron';
$lang['MISSION_GROUP_28'] = 'Lion';

/* Mercure */
$lang['MISSION_GROUP_30'] = 'Alfred';
$lang['MISSION_GROUP_31'] = 'Benjamin';
$lang['MISSION_GROUP_32'] = 'Charles';
$lang['MISSION_GROUP_33'] = 'David';
$lang['MISSION_GROUP_34'] = 'Edward';
$lang['MISSION_GROUP_35'] = 'Frederick';
$lang['MISSION_GROUP_36'] = 'George';
$lang['MISSION_GROUP_37'] = 'Harry';
$lang['MISSION_GROUP_38'] = 'Isaac';

/* Terra */
$lang['MISSION_0'] = 'Missione allenamento';
$lang['MISSION_1'] = 'Regione Inghilterra';
$lang['MISSION_2'] = 'Benelux';
$lang['MISSION_3'] = 'Regione Francia ';
$lang['MISSION_4'] = 'Europa Centrale';
$lang['MISSION_5'] = 'Scandinavia';
$lang['MISSION_6'] = 'Europa dell\'Est';
$lang['MISSION_7'] = 'Regione Spagna';
$lang['MISSION_8'] = 'Sud Europa';

$lang['MISSION_10'] = 'Groenlandia';
$lang['MISSION_11'] = 'Canada';
$lang['MISSION_12'] = 'Stati Uniti';
$lang['MISSION_13'] = 'Messico';
$lang['MISSION_14'] = 'Regione Guatemala';
$lang['MISSION_15'] = 'Regione Nicaragua';
$lang['MISSION_16'] = 'Regione Cuba';
$lang['MISSION_17'] = 'Regione Caraibica';

$lang['MISSION_20'] = 'America Centrale';
$lang['MISSION_21'] = 'Regione Ecuador';
$lang['MISSION_22'] = 'Regione Bolivia';
$lang['MISSION_23'] = 'Regione Paraguay';
$lang['MISSION_24'] = 'Regione Cile';
$lang['MISSION_25'] = 'Regione Argentina';
$lang['MISSION_26'] = 'Regione Uruguay';
$lang['MISSION_27'] = 'Regione Brasile';

$lang['MISSION_30'] = 'Regione Algeria';
$lang['MISSION_31'] = 'Regione Egitto';
$lang['MISSION_32'] = 'Regione Africa dell\'Ovest';
$lang['MISSION_33'] = 'Regione Africa Centrale';
$lang['MISSION_34'] = 'Regione Africa dell\'Est';
$lang['MISSION_35'] = 'Regione Mozambico';
$lang['MISSION_36'] = 'Regione Zimbabue';
$lang['MISSION_37'] = 'Regione Sudafrica';

$lang['MISSION_40'] = 'Regione Russia';
$lang['MISSION_41'] = 'Regione Mongolia';
$lang['MISSION_42'] = 'Regione Kazakistan';
$lang['MISSION_43'] = 'Regione Uzbekistan';
$lang['MISSION_44'] = 'Regione Tajikistan';
$lang['MISSION_45'] = 'Regione Turkmenistan';
$lang['MISSION_46'] = 'Regione Giorgia';
$lang['MISSION_47'] = 'Regione Armenia';

$lang['MISSION_50'] = 'Iran';
$lang['MISSION_51'] = 'Afghanistan';
$lang['MISSION_52'] = 'Pakistan';
$lang['MISSION_53'] = 'India';
$lang['MISSION_54'] = 'Nepal';
$lang['MISSION_55'] = 'Regione Bangladesh';
$lang['MISSION_56'] = 'Regione Tailandia';
$lang['MISSION_57'] = 'Regione Laos';

$lang['MISSION_60'] = 'Cina';
$lang['MISSION_61'] = 'Nord Corea';
$lang['MISSION_62'] = 'Sud Corea';
$lang['MISSION_63'] = 'Giappone';
$lang['MISSION_64'] = 'Taiwan';
$lang['MISSION_65'] = 'Regione Cambodia';
$lang['MISSION_66'] = 'Regione Vietnam';
$lang['MISSION_67'] = 'Malesia';

$lang['MISSION_70'] = 'Indonesia dell\'Ovest';
$lang['MISSION_71'] = 'Indonesia dell\'Est';
$lang['MISSION_72'] = 'Regione Filippine';
$lang['MISSION_73'] = 'Papua Nuova Guinea';
$lang['MISSION_74'] = 'Timor';
$lang['MISSION_75'] = 'Nord Australia';
$lang['MISSION_76'] = 'Sud Australia';
$lang['MISSION_77'] = 'Nuova Zeelanda';

$lang['MISSION_80'] = 'Siria';
$lang['MISSION_81'] = 'Iraq';
$lang['MISSION_82'] = 'Arabia Saudita';
$lang['MISSION_83'] = 'Kuweit';
$lang['MISSION_84'] = 'Yemen Regione Yemen';
$lang['MISSION_85'] = 'Regione Oman ';
$lang['MISSION_86'] = 'Giordania';
$lang['MISSION_87'] = 'Israele';

/* Luna */
$lang['MISSION_100'] = 'Cratere Endymion';
$lang['MISSION_101'] = 'Cratere Franklin';
$lang['MISSION_102'] = 'Sinus Honoris';
$lang['MISSION_103'] = 'Mons Fidei';
$lang['MISSION_104'] = 'Cratere Blanc';
$lang['MISSION_105'] = 'Cratere Fesenkov';
$lang['MISSION_106'] = 'Montes Temporis';
$lang['MISSION_107'] = 'Cratere Darwin';

$lang['MISSION_110'] = 'Cratere Agnes';
$lang['MISSION_111'] = 'Mons Andre';
$lang['MISSION_112'] = 'Vallis Ardeshir';
$lang['MISSION_113'] = 'Cratere Aristoteles';
$lang['MISSION_114'] = 'Mare Blanc';
$lang['MISSION_115'] = 'Mons Bradley';
$lang['MISSION_116'] = 'Vallis Delisle';
$lang['MISSION_117'] = 'Sinus Dieter';

$lang['MISSION_120'] = 'Mons Dilip';
$lang['MISSION_121'] = 'Mons Esam';
$lang['MISSION_122'] = 'Cratere Albategnius';
$lang['MISSION_123'] = 'Mons Gruithuisen Delta';
$lang['MISSION_124'] = 'Mare Gruithuisen Gamma';
$lang['MISSION_125'] = 'Cratere Hansteen';
$lang['MISSION_126'] = 'Vallis Herodotus';
$lang['MISSION_127'] = 'Mons Huygens';

$lang['MISSION_130'] = 'Sinus La Hire';
$lang['MISSION_131'] = 'Mons Maraldi';
$lang['MISSION_132'] = 'Mons Moro';
$lang['MISSION_133'] = 'Cratere Aristarchus';
$lang['MISSION_134'] = 'Mons Pico';
$lang['MISSION_135'] = 'Vallis Piton';
$lang['MISSION_136'] = 'Sinus Rumker';
$lang['MISSION_137'] = 'Mons Usov';

$lang['MISSION_140'] = 'Mons Vinogradov';
$lang['MISSION_141'] = 'Mons Vitruvius';
$lang['MISSION_142'] = 'Mons Wolff';
$lang['MISSION_143'] = 'Montes Agricola';
$lang['MISSION_144'] = 'Montes Alpes';
$lang['MISSION_145'] = 'Cratere Apenninus';
$lang['MISSION_146'] = 'Montes Archimedes';
$lang['MISSION_147'] = 'Montes Carpatus';

$lang['MISSION_150'] = 'Montes Caucasus';
$lang['MISSION_151'] = 'Mare Cordillera';
$lang['MISSION_152'] = 'Montes Haemus';
$lang['MISSION_153'] = 'Cratere Harbinger';
$lang['MISSION_154'] = 'Sinus Pyrenaeus';
$lang['MISSION_155'] = 'Montes Riphaeus';
$lang['MISSION_156'] = 'Montes Rook';
$lang['MISSION_157'] = 'Mare Secchi';

$lang['MISSION_160'] = 'Montes Spitzbergen';
$lang['MISSION_161'] = 'Mare Taurus';
$lang['MISSION_162'] = 'Sinus Teneriffe';
$lang['MISSION_163'] = 'Montes Harbinger';
$lang['MISSION_164'] = 'Vallis Rheita';
$lang['MISSION_165'] = 'Vallis Baade';
$lang['MISSION_166'] = 'Cratere Bohr';
$lang['MISSION_167'] = 'Vallis Palitzsch';

$lang['MISSION_170'] = 'Cratere Fecunditatis';
$lang['MISSION_171'] = 'Mare Australe';
$lang['MISSION_172'] = 'Montes Orientale';
$lang['MISSION_173'] = 'Sinus Cognitum';
$lang['MISSION_174'] = 'Mare Crisium';
$lang['MISSION_175'] = 'Mons Spumans';
$lang['MISSION_176'] = 'Montes Tranquillitatis';
$lang['MISSION_177'] = 'Mare Vaporum';

$lang['MISSION_180'] = 'Cratere Aestatis';
$lang['MISSION_181'] = 'Lacus Bonitatis';
$lang['MISSION_182'] = 'Montes Felicitatis';
$lang['MISSION_183'] = 'Sinus Luxuriae';
$lang['MISSION_184'] = 'Lacus Oblivionis';
$lang['MISSION_185'] = 'Mons Solitudinis';
$lang['MISSION_186'] = 'Montes Temporis';
$lang['MISSION_187'] = 'Cratere Timoris';

/* Mars */
$lang['MISSION_200'] = 'Cratere Al-Qahira';
$lang['MISSION_201'] = 'Sinus Ares';
$lang['MISSION_202'] = 'Vallis Auqakuh';
$lang['MISSION_203'] = 'Cratere Bahram';
$lang['MISSION_204'] = 'Mare Harmakhis';
$lang['MISSION_205'] = 'Mons Her Desher';
$lang['MISSION_206'] = 'Sinus Hrad';
$lang['MISSION_207'] = 'Vallis Huo Hsing';

$lang['MISSION_210'] = 'Mons Kasei';
$lang['MISSION_211'] = 'Mare Labou';
$lang['MISSION_212'] = 'Vallis Maadim';
$lang['MISSION_213'] = 'Cratere Maja';
$lang['MISSION_214'] = 'Sinus Mamers';
$lang['MISSION_215'] = 'Vallis Mangala';
$lang['MISSION_216'] = 'Cratere Marte';
$lang['MISSION_217'] = 'Mare Mawrth';

$lang['MISSION_220'] = 'Cratere Nirgal';
$lang['MISSION_221'] = 'Vallis Shalbatana';
$lang['MISSION_222'] = 'Cratere Simud';
$lang['MISSION_223'] = 'Sinus Tiu';
$lang['MISSION_224'] = 'Vallis Aloysius';
$lang['MISSION_225'] = 'Cratere Ambrosius';
$lang['MISSION_226'] = 'Mare Barnabas';
$lang['MISSION_227'] = 'Mare Constantia';

$lang['MISSION_230'] = 'Vallis Edmondus';
$lang['MISSION_231'] = 'Mare Eustachius';
$lang['MISSION_232'] = 'Cratere Georgius';
$lang['MISSION_233'] = 'Sinus Griselda';
$lang['MISSION_234'] = 'Vallis Gualterius';
$lang['MISSION_235'] = 'Cratere Homfridus';
$lang['MISSION_236'] = 'Mare Henricus';
$lang['MISSION_237'] = 'Guglielmus';

$lang['MISSION_240'] = 'Mare Janetta';
$lang['MISSION_241'] = 'Vallis Jerominus';
$lang['MISSION_242'] = 'Cratere Josephus';
$lang['MISSION_243'] = 'Mare Leonardus';
$lang['MISSION_244'] = 'Sinus Mauritius';
$lang['MISSION_245'] = 'Cratere Nicholaus';
$lang['MISSION_246'] = 'Vallis Laurentius';
$lang['MISSION_247'] = 'Mons Octavius';

$lang['MISSION_250'] = 'Cratere Misericordia';
$lang['MISSION_251'] = 'Vallis Petronella';
$lang['MISSION_252'] = 'Sinus Sylvanus';
$lang['MISSION_253'] = 'Cratere Reginaldus';
$lang['MISSION_254'] = 'Vallis Adeipho';
$lang['MISSION_255'] = 'Sinus Randulphus';
$lang['MISSION_256'] = 'Cratere Xpofer';
$lang['MISSION_257'] = 'Mare Aegidius';

$lang['MISSION_260'] = 'Sinus Aeneas';
$lang['MISSION_261'] = 'Cratere Philipus';
$lang['MISSION_262'] = 'Sinus Beniaminus';
$lang['MISSION_263'] = 'Vallis Rosamundi';
$lang['MISSION_264'] = 'Mons Peregrinus';
$lang['MISSION_265'] = 'Mare Xtianus';
$lang['MISSION_266'] = 'Vallis Crispianus';
$lang['MISSION_267'] = 'Cratere Clementia';

$lang['MISSION_270'] = 'Vallis Elizabeta';
$lang['MISSION_271'] = 'Cratere Xtopher';
$lang['MISSION_272'] = 'Mare Placentia';
$lang['MISSION_273'] = 'Sinus Gaufridus';
$lang['MISSION_274'] = 'Cratere Stephanus';
$lang['MISSION_275'] = 'Vallis Xpianus	';
$lang['MISSION_276'] = 'Mare Girardus';
$lang['MISSION_277'] = 'Cratere Radulphus';

$lang['MISSION_280'] = 'Cratere Xtopherus';
$lang['MISSION_281'] = 'Vallis Terentius';
$lang['MISSION_282'] = 'Mons Eamnonn';
$lang['MISSION_283'] = 'Cratere Kadisha';
$lang['MISSION_284'] = 'Mare Kachine';
$lang['MISSION_285'] = 'Vallis Oddvar';
$lang['MISSION_286'] = 'Sinus Radborne';
$lang['MISSION_287'] = 'Cratere Ebenezer';

/* Mercure */
$lang['MISSION_300'] = 'Cratere Albococcinea';
$lang['MISSION_301'] = 'Sinus argentea';
$lang['MISSION_302'] = 'Vallis Atrococcinea';
$lang['MISSION_303'] = 'Crater Colorans';
$lang['MISSION_304'] = 'Mare Cardinalis';
$lang['MISSION_305'] = 'Mons Brunnea';
$lang['MISSION_306'] = 'Sinus Chlorantha';
$lang['MISSION_307'] = 'Vallis Erythrocarpa';

$lang['MISSION_310'] = 'Mons Ferruginea';
$lang['MISSION_311'] = 'Mare Colorans';
$lang['MISSION_312'] = 'Vallis Aurea';
$lang['MISSION_313'] = 'Cratere Atrovirens';
$lang['MISSION_314'] = 'Sinus lutescens';
$lang['MISSION_315'] = 'Vallis Maculata';
$lang['MISSION_316'] = 'Cratere Nigrescens';
$lang['MISSION_317'] = 'Mare Punicea';

$lang['MISSION_320'] = 'Cratere Rosea';
$lang['MISSION_321'] = 'Vallis Rubiginosa';
$lang['MISSION_322'] = 'Cratere Tinctoria';
$lang['MISSION_323'] = 'Sinus Sulphurea';
$lang['MISSION_324'] = 'Vallis Sempervirens';
$lang['MISSION_325'] = 'Cratere Rubicunda';
$lang['MISSION_326'] = 'Mare Variegata';
$lang['MISSION_327'] = 'Mare Versicolor';

$lang['MISSION_330'] = 'Vallis Vinosa';
$lang['MISSION_331'] = 'Mare Viridescens';
$lang['MISSION_332'] = 'Cratere Citrodora';
$lang['MISSION_333'] = 'Sinus Foetidissima';
$lang['MISSION_334'] = 'Vallis Gravaeolens';
$lang['MISSION_335'] = 'Cratere Odorata';
$lang['MISSION_336'] = 'Mare Suaveolens';
$lang['MISSION_337'] = 'Cratere Ursina';

$lang['MISSION_340'] = 'Mare Amabile';
$lang['MISSION_341'] = 'Vallis Praecox ';
$lang['MISSION_342'] = 'Cratere Bella';
$lang['MISSION_343'] = 'Mare Amoena';
$lang['MISSION_344'] = 'Sinus Gracilis';
$lang['MISSION_345'] = 'Cratere Formosa';
$lang['MISSION_346'] = 'Vallis Fragilis';
$lang['MISSION_347'] = 'Mons Foeniculaceus';

$lang['MISSION_350'] = 'Cratere Blanda';
$lang['MISSION_351'] = 'Vallis Elegantissima';
$lang['MISSION_352'] = 'Sinus Imperialis';
$lang['MISSION_353'] = 'Cratere Splendens';
$lang['MISSION_354'] = 'Vallis Superba';
$lang['MISSION_355'] = 'Sinus Magnifica';
$lang['MISSION_356'] = 'Cratere Campestris';
$lang['MISSION_357'] = 'Mare Collina';

$lang['MISSION_360'] = 'Sinus Insignis';
$lang['MISSION_361'] = 'Cratere Peregrina';
$lang['MISSION_362'] = 'Sinus Mutabilis';
$lang['MISSION_363'] = 'Vallis Spectabilis';
$lang['MISSION_364'] = 'Mons Thermalis';
$lang['MISSION_365'] = 'Mare Gracilis';
$lang['MISSION_366'] = 'Vallis Sinensis';
$lang['MISSION_367'] = 'Cratere Pratensis';

$lang['MISSION_370'] = 'Vallis Mirabilis';
$lang['MISSION_371'] = 'Cratere Umbrosa ';
$lang['MISSION_372'] = 'Mare Paradoxas';
$lang['MISSION_373'] = 'Sinus Pulchella';
$lang['MISSION_374'] = 'Crater Floribunda';
$lang['MISSION_375'] = 'Vallis Microphylla';
$lang['MISSION_376'] = 'Mare Parviflora';
$lang['MISSION_377'] = 'Cratere Venusta';

$lang['MISSION_380'] = 'Cratere Monstrosus';
$lang['MISSION_381'] = 'Vallis Septentrionalis';
$lang['MISSION_382'] = 'Mons Occidentalis';
$lang['MISSION_383'] = 'Cratere Pulcherrima';
$lang['MISSION_384'] = 'Mare Spectabilis';
$lang['MISSION_385'] = 'Vallis Regia';
$lang['MISSION_386'] = 'Sinus Macrantha';
$lang['MISSION_387'] = 'Cratere Caespitosa';

/*
** ------------------
** PAGINA MISSIONI
** ------------------
*/

$lang['MISSION_TITLE'] = 'MISSIONI';
$lang['MISSION_NOTE'] = 'Nota: Gioca missioni per guadagnare soldi e punti esperienza per raggiungere il livello successivo. Quando una missione è completa al 100% riceverai il doppio dei soldi. Se hai conquistato il 100% del continente %s il tuo introito orario incrementerà di %s dollari.';

$lang['MISSION_ALLIANCE_SIZE'] = 'grandezza alleanza';
$lang['MISSION_GAIN'] = 'Guadagno';
$lang['MISSION_PART'] = 'Parte';
$lang['MISSION_REQUIRED'] = 'Richiede';
$lang['MISSION_UNLOCK'] = 'Sbloccato al livello %s';
$lang['MISSION_CHANCE_LOOT'] = 'Possibilità di drop';

$lang['MISSION_YOU_USED'] = 'Hai usato';
$lang['MISSION_YOU_GAIN'] = 'Hai guadagnato';
$lang['MISSION_DOLLAR_AND'] = ' dollari e ';
$lang['MISSION_ABORTED'] = 'Missione annullata!';
$lang['MISSION_NO_ENERGY'] = 'Non hai abbastanza energia per completare la missione. Aspetta qualche minuto affinchè l\'energia si ricarichi.';
$lang['MISSION_LOW_ALLIANCE'] = 'La grandezza della tua alleanza è troppo piccola per giocare questa missione.';
$lang['MISSION_MISSING_UNITS'] = 'Non hai la giusta quantità di unità per completare la missione. Unità mancanti: ';
$lang['MISSION_MISSING_UNITS_PRICE'] = 'Prezzo totale delle unità è %s dollari. Il costo orario aumenterà di %s dollari.';
$lang['MISSION_UNITS_LOST'] = 'Durante la missione hai perso le seguenti unità:';
$lang['MISSION_LOOT_WON'] = 'Hai guadagnato il seguente drop :';
$lang['MISSION_UNLOCKED'] = 'Ora, continua con l\'allenamento nelle lotte.';

$lang['MISSION_CONTINTENT_READY1'] = 'Magnifico! Hai completato la parte %s di %s del continente %s! ';
$lang['MISSION_CONTINTENT_READY2'] = 'Hai ricevuto %s punti skill extra. ';
$lang['MISSION_CONTINTENT_READY3'] = 'Hai finito tutte le parti. Continua col prossimo continente!';
$lang['MISSION_CONTINTENT_READY4'] = 'Procedi con la parte %s di questo continente!';
$lang['MISSION_COMPLETE_TEXT'] = 'Hai conquistato i seguenti continenti finora!';

$lang['MISSION_REBEL'] = 'Rivolta';

/*
** ------------------
** PAGINA LOTTA
** ------------------
*/

$lang['BATTLE_TITLE'] = 'LOTTA';
$lang['BATTLE_GENERAL_TITLE'] = 'Lotta';
$lang['BATTLE_BOUNTY_TITLE'] = 'Caccia alle taglie';

$lang['BATTLE_LOST'] = 'Il tuo %s ha attaccato %s. Hai perso la lotta, ricevendo %s danni, mentre hai inflitto %s danni a %s.';
$lang['BATTLE_WON'] = 'Il tuo %s ha attaccato %s. Hai vinto la lotta, ricevendo %s danni mentre hai inflitto %s danni a %s. Hai preso %s dollari e guadagnato %s punti esperienza.';
$lang['BATTLE_DEFENDER_HEALTH_LOW'] = '%s si arrende temporaneamente perchè la sua salute è troppo bassa!';
$lang['BATTLE_ATTACKER_HEALTH_LOW'] = 'La tua salute è troppo bassa per lottare!. Visita l\'ospedale per il recupero istantaneo o aspetta il recupero automatico.';
$lang['BATTLE_AMMO_LOW'] = 'Hai finito le munizioni! Aspetta qualche minuto per recuperare le munizioni o usa i punti skill per migliorare l\'abilità munizioni oppure paga la fabbrica per recuperarle instantaneamente.';
$lang['BATTLE_UNITS_LOST'] = 'Durante la lotta hai perso le seguenti unità:';
$lang['BATTLE_BUILDINGS_LOST'] = 'Durante la lotta hai perso i seguenti edifici:';
$lang['BATTLE_DEFENSE_FORCE'] = '%s %s difesa %s (potenza difesa %s):'; 
$lang['BATTLE_DEFENSE_BASE'] = 'Difesa base %s:'; 
$lang['BATTLE_ATTACK_FORCE'] = 'La potenza d\'attacco del tuo %s %s (potenza attacco %s)';
$lang['BATTLE_MORE'] = 'più';
$lang['BATTLE_NO_PLAYER_AVAILABLE'] = 'Al momento non c\'è nessun giocatore disponibile per le lotte.';
$lang['BATTLE_UNLOCKED'] = '%s la lotta viene sbloccata al livello %s.';
$lang['BATTLE_FIRST_MISSION'] = 'Completa la missione d\'allenamento prima.';
$lang['BATTLE_BOUNTY_UNLOCKED'] = '%s la caccia alle taglie viene sbloccata al livello %s.';
$lang['BATTLE_ALLY_NO_ATTACK'] = '<b>%s</b> è un alleato. Non puoi attaccare gli alleati.';
$lang['BATTLE_SURRENDER'] = 'Arreso temporaneamente';

$lang['BATTLE_NOTE1'] = 'Nota: Lotta contro altri giocatori per guadagnare soldi e punti esperienza per raggiungere il livello successivo.';
$lang['BATTLE_NOTE2'] = 'Nota: Dai la caccia ad altri giocatori per vincere i soldi della loro taglia e guadagnare punti esperienza per raggiungere il livello successivo.';

$lang['BATTLE_FORCE_TYPE'] = 'Forza:';
$lang['BATTLE_ENEMIES'] = 'Nemici';
$lang['BATTLE_BOUNTY'] = 'Caccia-Taglia';
$lang['BATTLE_NO_BOUNTY_PLAYERS'] = 'Al momento non ci sono giocatori disponibili con la taglia sulla testa.';
$lang['BATTLE_BOUNTY_BONUS'] = 'Ricevuto bonus extra per la taglia di %s dollari.'; 
$lang['BATTLE_HOSPITAL_BONUS'] = '%s si è arreso temporaneamente. Hai ricevuto un bonus di %s dollari!'; 
$lang['BATTLE_BOUNTY_LOST'] = 'Sei stato attaccato dall\'(a) %s di %s.Hai PERSO, ricevendo %s dollari %s danni e perdendo e %s punti esperienza.';
$lang['BATTLE_BOUNTY_CONFIRM'] = 'Vuoi mettere una taglia di %s dollari?';

$lang['BATTLE_CEASE_FIRE_PERIOD'] = 'Periodo armistizio è attivo! Non è possibile lottare. %s';
$lang['BATTLE_AND'] = 'e';
$lang['BATTLE_REBEL_UPDATE1'] = 'Ben fatto, hai iniziato una rivolta contro %s nella regione di %s. Sotto puoi vedere la sua situazione attuale.';
$lang['BATTLE_REBEL_UPDATE2'] = 'Ben fatto, hai aumentato le possibilità di rivolta di %s al %s%.';
$lang['BATTLE_REBEL_UPDATE3'] = 'Peccato, nessuna regione disponibile per la rivolta!';

$lang['BATTLE_NO_BOUNTY_MONEY'] = 'Non hai %s dollari per mettere una taglia sulla testa di %s.';
$lang['BATTLE_BOUNTY_SET'] = 'Hai messo %s dollari sulla testa di %s. Quando %s viene sconfitto, perderà %s punti esperienza.'; 

$lang['BATTLE_RANGE'] = 'I giocatori dal livello %s fino al %s sono adatti per lottare contro di te.';
/*
** ------------------
** DATI UNITà
** ------------------
*/

/* Terra */
$lang['UNIT_GROUP_0']  = 'Esercito';
$lang['UNIT_GROUP_2']  = 'Cavalleria';
$lang['UNIT_GROUP_3']  = 'Marina';
$lang['UNIT_GROUP_4']  = 'Avviazione';
$lang['UNIT_GROUP_5']  = 'Cittadini';
$lang['UNIT_GROUP_6']  = 'Intel';

/* Luna */
$lang['UNIT_GROUP_7']  = 'Guerrieri';
$lang['UNIT_GROUP_8']  = 'Droni';
$lang['UNIT_GROUP_9']  = 'NaviSpaziali';
$lang['UNIT_GROUP_10'] = 'Cittadini';
$lang['UNIT_GROUP_11'] = 'Esercito';
$lang['UNIT_GROUP_12'] = 'Esploratori';

/* Marte */
$lang['UNIT_GROUP_13']  = 'Droni';
$lang['UNIT_GROUP_14']  = 'Guerrieri';
$lang['UNIT_GROUP_15']  = 'NaviSpaziali';
$lang['UNIT_GROUP_16']  = 'Esploratori';
$lang['UNIT_GROUP_17'] 	= 'Cittadini';
$lang['UNIT_GROUP_18'] 	= 'Esercito';

/* mercure */
$lang['UNIT_GROUP_19']  = 'Droni';
$lang['UNIT_GROUP_20']  = 'Guerrieri';
$lang['UNIT_GROUP_21']  = 'NaviSpaziali';
$lang['UNIT_GROUP_22']  = 'Esploratori';
$lang['UNIT_GROUP_23'] 	= 'Cittadini';
$lang['UNIT_GROUP_24'] 	= 'Esercito';


/* Cavalleria (Terra) - Gruppo 2 */
$lang['UNIT_1'] = 'Minimitragliatore';
$lang['UNIT_101'] = 'Auto militare';
$lang['UNIT_102'] = 'Hummer';
$lang['UNIT_103'] = 'Camion';
$lang['UNIT_104'] = 'Artiglieria leggera';
$lang['UNIT_105'] = 'Trasportatore cavalleria';
$lang['UNIT_106'] = 'MGM-51 Shillelagh';
$lang['UNIT_107'] = 'Trasportatore cavalleria avanzato';
$lang['UNIT_108'] = 'Veicolo assalto';
$lang['UNIT_109'] = 'Lanciatore SSM';
$lang['UNIT_110'] = 'Aereo leggero';
$lang['UNIT_111'] = 'Carro M1 Abrahms';
$lang['UNIT_112'] = 'Veicolo cavalleria';
$lang['UNIT_113'] = 'Veicolo antimboscata';
$lang['UNIT_114'] = 'Carro pesante';
$lang['UNIT_115'] = '1A1 Leopardo';
$lang['UNIT_116'] = 'Veicolo HG-544';
$lang['UNIT_117'] = 'Trasportatore Tracker';
$lang['UNIT_118'] = 'Veicolo di combattimento';
$lang['UNIT_119'] = 'Carro Hellfire';
$lang['UNIT_120'] = 'Carro combattimento';
$lang['UNIT_121'] = 'Sistema Montato di Combattimento';
$lang['UNIT_122'] = 'Artiglieria ad auto-propulsione';
$lang['UNIT_123'] = 'Carro Chaparral';
$lang['UNIT_124'] = 'M198 Howitzer';
$lang['UNIT_125'] = 'Artiglieria pesante';
$lang['UNIT_126'] = 'Lancia Missili';
$lang['UNIT_127'] = 'Antiaerea mobile';

/* Marina (Terra) - Gruppo 3 */
$lang['UNIT_201'] = 'Gommone';
$lang['UNIT_202'] = 'Trasporto';
$lang['UNIT_203'] = 'Fregata';
$lang['UNIT_204'] = 'Carro navale';
$lang['UNIT_205'] = 'Distruttore navale';
$lang['UNIT_206'] = 'M80 Stiletto';
$lang['UNIT_207'] = 'Sottomarino';
$lang['UNIT_208'] = 'Trasportatore elicotteri';
$lang['UNIT_209'] = 'Nave da combattimento';
$lang['UNIT_210'] = 'Nave missilistica Houbei';
$lang['UNIT_211'] = 'Fregata Horizon';
$lang['UNIT_212'] = 'Fregata Tipo 13';
$lang['UNIT_213'] = 'Distruttore';
$lang['UNIT_214'] = 'Sottomarino Scorpion';
$lang['UNIT_215'] = 'Distruttore DDG 1000';
$lang['UNIT_216'] = 'Sottomarino classe Elite';
$lang['UNIT_217'] = 'Distruttore SPY-1D';
$lang['UNIT_218'] = 'Combattente del Mare';
$lang['UNIT_219'] = 'Ultrarapido HSV-2';
$lang['UNIT_220'] = 'Cruiser missilistico';
$lang['UNIT_221'] = 'Combattente UXV';
$lang['UNIT_222'] = 'Nave anti-sottomarini';
$lang['UNIT_223'] = 'Nave Kanimbla AT';
$lang['UNIT_224'] = 'Trasportatore avviazione';
$lang['UNIT_225'] = 'Piattaforma d\'atteraggio';
$lang['UNIT_226'] = 'Fregata tipo 23';
$lang['UNIT_227'] = 'Sottomarino classe Ohio';
$lang['UNIT_228'] = 'Cruiser nucleare';

/* Avviazione (Terra) - Gruppo 4 */
$lang['UNIT_301'] = 'Cessna 172';
$lang['UNIT_302'] = 'Aereo cargo C-17';
$lang['UNIT_303'] = 'Aereo V-22A Osprey';
$lang['UNIT_304'] = 'Jet AV-8B Harrier';
$lang['UNIT_305'] = 'Elicottero Comanche';
$lang['UNIT_306'] = 'Elicottero Havoc';
$lang['UNIT_307'] = 'Saab JA37 Viggen';
$lang['UNIT_308'] = 'SR-71 Blackbird';
$lang['UNIT_309'] = 'Elicottero Apache';
$lang['UNIT_310'] = 'Bombardiere B-2 Spirit';
$lang['UNIT_311'] = 'F-18 Super Hornet';
$lang['UNIT_313'] = 'F-15 Silent Eagle';
$lang['UNIT_314'] = 'B-1 Lancer';
$lang['UNIT_316'] = 'Intercettore F3';
$lang['UNIT_318'] = 'F-16 Falcon';
$lang['UNIT_319'] = 'PAK-FA Fighter';
$lang['UNIT_320'] = 'F-117 Nighthawk';
$lang['UNIT_321'] = 'Bombardiere Boeing NGB';
$lang['UNIT_322'] = 'Jet F-14 Tomcat';
$lang['UNIT_323'] = 'Jet F-35 Lightning II';
$lang['UNIT_324'] = 'Bombardiere B-52 Stratofortress';
$lang['UNIT_325'] = 'Jet F-22 Raptor';
$lang['UNIT_326'] = 'Trident II Missile';

/* Cittadini (Terra) - Gruppo 5 */
$lang['UNIT_401'] = 'Ingegnere edile';
$lang['UNIT_402'] = 'Ingegnere meccanico';
$lang['UNIT_403'] = 'Ingegnere laboratorio';
$lang['UNIT_404'] = 'Manager';
$lang['UNIT_405'] = 'Dottore';
$lang['UNIT_406'] = 'Cuoco';
$lang['UNIT_407'] = 'Guardia di sicurezza';

/* Intel (Terra) - Gruppo 6 */
$lang['UNIT_501'] = 'Telecamera di sorveglianza';
$lang['UNIT_502'] = 'Intelligence dei 	Marines';
$lang['UNIT_503'] = 'Minidrone aereo';
$lang['UNIT_504'] = 'Robot Spia G34';
$lang['UNIT_505'] = 'Incrociatore Intelligence A3';
$lang['UNIT_506'] = 'Nave spia cammuffata';
$lang['UNIT_507'] = 'Hawk Eye';
$lang['UNIT_508'] = 'UK-80 AWACS';
$lang['UNIT_509'] = 'Nave anti-radar AS-102';
$lang['UNIT_510'] = 'US-101 Predator';
$lang['UNIT_511'] = 'Drone Heron';
$lang['UNIT_512'] = 'Satellite spia  HG101';


/* Warriors (Moon) - Group 7 */
$lang['UNIT_700'] = 'Ahiga I';
$lang['UNIT_701'] = 'Aindrias II';
$lang['UNIT_702'] = 'Aloisius III';
$lang['UNIT_703'] = 'Aloysius IV';
$lang['UNIT_704'] = 'Alvar V';
$lang['UNIT_705'] = 'Aindrias VI';
$lang['UNIT_706'] = 'Cadomedo VII';
$lang['UNIT_707'] = 'Catigernus VIII';
$lang['UNIT_708'] = 'Catutigernos IX';
$lang['UNIT_709'] = 'Cedric X';
$lang['UNIT_710'] = 'Cheveyo XI';

/* Drones (Moon) - Group 8 */
$lang['UNIT_800'] = 'Basic Rover I';
$lang['UNIT_801'] = 'Lunar Transporter II';
$lang['UNIT_802'] = 'Moon Explorer III';
$lang['UNIT_803'] = 'Moon Havostar IV';
$lang['UNIT_804'] = 'Mobile Lab V';
$lang['UNIT_805'] = 'Transporter VI';
$lang['UNIT_805'] = 'Space Crane VII';
$lang['UNIT_806'] = 'Moon Buggy VIII';
$lang['UNIT_807'] = 'Fuel Transporter IX';
$lang['UNIT_808'] = 'Fuel Explorer X';
$lang['UNIT_809'] = 'Moon Explorer XI';
$lang['UNIT_810'] = 'Transporter XII';

/* Spacecrafts (Moon) - Group 9 */
$lang['UNIT_900'] = 'Moon Cruiser';
$lang['UNIT_901'] = 'Millennium Falcon';
$lang['UNIT_902'] = 'Ebon Hawk';
$lang['UNIT_903'] = 'Transport Robot';
$lang['UNIT_904'] = 'Slave I';
$lang['UNIT_905'] = 'Assault ship';
$lang['UNIT_906'] = 'Corellian corvette';
$lang['UNIT_907'] = 'War Hawk Shadow';
$lang['UNIT_908'] = 'Solar Spacecraft';
$lang['UNIT_909'] = 'Royal starship';
$lang['UNIT_910'] = 'Theta-Class Shuttle';
$lang['UNIT_911'] = 'Trade Cruiser';
$lang['UNIT_912'] = 'Sith Infiltrator';
$lang['UNIT_913'] = 'Imperial landing craft';
$lang['UNIT_914'] = 'Star Skiff II';
$lang['UNIT_915'] = 'Star Destroyer';
$lang['UNIT_916'] = 'Flag Ship';

/* Citizens (Moon) - Group 10 */
$lang['UNIT_1000'] = 'Astronaut';
$lang['UNIT_1001'] = 'Female';
$lang['UNIT_1002'] = 'Male';

/* Explorers (Moon) - Group 12 */
$lang['UNIT_1200'] = 'Explorer Satellite';
$lang['UNIT_1201'] = 'Explorer Ship';
$lang['UNIT_1202'] = 'Short Range Radar';
$lang['UNIT_1203'] = 'Deepspace Explorer';
$lang['UNIT_1204'] = 'Planet Explorer';
$lang['UNIT_1205'] = 'Space Elevator';
$lang['UNIT_1206'] = 'Astronaut Explorer';
$lang['UNIT_1207'] = 'Long Range Rader';
$lang['UNIT_1208'] = 'Deepspace Relay Station';
$lang['UNIT_1209'] = 'Lightspeed Explorer';
$lang['UNIT_1210'] = 'Planet Destroyer';
$lang['UNIT_1211'] = 'Galaxy Explorer';


/* Drones (Mars) - Group 13 */
$lang['UNIT_1300'] = 'Loyce I';
$lang['UNIT_1301'] = 'Labhaoise II';
$lang['UNIT_1302'] = 'Kondo III';
$lang['UNIT_1303'] = 'Kiaskari VI';
$lang['UNIT_1304'] = 'Khalon V';
$lang['UNIT_1305'] = 'Hida VI';
$lang['UNIT_1306'] = 'Irapeke VII';
$lang['UNIT_1307'] = 'Heriberto VIII';
$lang['UNIT_1308'] = 'Kerbasi IX';
$lang['UNIT_1309'] = 'Karna X';

/* Warriors (Mars) - Group 14 */
$lang['UNIT_1400'] = 'Gervaso I';
$lang['UNIT_1401'] = 'Galtero II';
$lang['UNIT_1402'] = 'Gunther III';
$lang['UNIT_1403'] = 'Donnachadh VI';
$lang['UNIT_1404'] = 'Duncan V';
$lang['UNIT_1405'] = 'Eskiminzin VI';
$lang['UNIT_1406'] = 'Fenyang VII';
$lang['UNIT_1407'] = 'Finnegan VIII';
$lang['UNIT_1408'] = 'Clodovea IX';
$lang['UNIT_1409'] = 'Eferhilda X';

/* Spacecrafts (Moon) - Group 15 */
$lang['UNIT_1500'] = 'Mars Cruiser I';
$lang['UNIT_1501'] = 'Cocon II';
$lang['UNIT_1502'] = 'Hawk Eye III';
$lang['UNIT_1503'] = 'Ariane IV';
$lang['UNIT_1504'] = 'Gyro V';
$lang['UNIT_1505'] = 'Miner VI';
$lang['UNIT_1506'] = 'Jannus VII';
$lang['UNIT_1507'] = 'Tango VIII';
$lang['UNIT_1508'] = 'Rader IX';
$lang['UNIT_1509'] = 'Eloy  X';

/* Explorers (Mars) - Group 16 */
$lang['UNIT_1600'] = 'Cadabyr I';
$lang['UNIT_1601'] = 'Chadwick II';
$lang['UNIT_1602'] = 'Calhoun III';
$lang['UNIT_1603'] = 'Cheveyo IV';
$lang['UNIT_1604'] = 'Clancy V';
$lang['UNIT_1605'] = 'Clodovea VI';
$lang['UNIT_1606'] = 'Cochise VII';
$lang['UNIT_1607'] = 'Czarine VIII';
$lang['UNIT_1608'] = 'Caddawyc IX';
$lang['UNIT_1609'] = 'Chlodwig X';

/* Citizens (Mars) - Group 17 */
$lang['UNIT_1700'] = 'Astronauta';
$lang['UNIT_1701'] = 'Fmmina';
$lang['UNIT_1702'] = 'Maschio';

/* Guerrieri (Mercure) - Group 19 */
$lang['UNIT_1900'] = 'Swify I';
$lang['UNIT_1901'] = 'Euhm II';
$lang['UNIT_1902'] = 'Mirageman III';
$lang['UNIT_1903'] = 'Vereldor IV';
$lang['UNIT_1904'] = 'Maelsius V';
$lang['UNIT_1905'] = 'Suldan VI';
$lang['UNIT_1906'] = 'Jonesy VII';
$lang['UNIT_1907'] = 'Pendejo VIII';
$lang['UNIT_1908'] = 'Vorpal IX';
$lang['UNIT_1909'] = 'Iyona X';

/* Guerrieri (Mercure) - Group 20 */
$lang['UNIT_2000'] = 'Grandmaster I';
$lang['UNIT_2001'] = 'Courage II';
$lang['UNIT_2002'] = 'Hero III';
$lang['UNIT_2003'] = 'Pious IV';
$lang['UNIT_2004'] = 'Stalwart V';
$lang['UNIT_2005'] = 'Bombadil VI';
$lang['UNIT_2006'] = 'Happyelf VII';
$lang['UNIT_2007'] = 'Rainbow VIII';
$lang['UNIT_2008'] = 'MerryLad IX';
$lang['UNIT_2009'] = 'Drenar X';

/* Navicelle (Mercure) - Group 21 */
$lang['UNIT_2100'] = 'Halvilion I';
$lang['UNIT_2101'] = 'Menelaus II';
$lang['UNIT_2102'] = 'Ultimatum III';
$lang['UNIT_2103'] = 'Erudur IV';
$lang['UNIT_2104'] = 'Banbelion V';
$lang['UNIT_2105'] = 'Nimtharadon VI';
$lang['UNIT_2106'] = 'Voronthil VII';
$lang['UNIT_2107'] = 'Anion VIII';
$lang['UNIT_2108'] = 'Partharaon IX';
$lang['UNIT_2109'] = 'Erudil X';

/* Esploratori (Mercure) - Group 22 */
$lang['UNIT_2200'] = 'Girlyman I';
$lang['UNIT_2201'] = 'Wuss II';
$lang['UNIT_2202'] = 'Sissy III';
$lang['UNIT_2203'] = 'Tauren IV';
$lang['UNIT_2204'] = 'Hykon V';
$lang['UNIT_2205'] = 'Talenx VI';
$lang['UNIT_2206'] = 'DDazra VII';
$lang['UNIT_2207'] = 'Hexa VIII';
$lang['UNIT_2208'] = 'Marest IX';
$lang['UNIT_2209'] = 'Rawrgrable X';

/* Cittadini (Mercure) - Group 23 */
$lang['UNIT_2300'] = 'Astronauta';
$lang['UNIT_2301'] = 'Femmina';
$lang['UNIT_2302'] = 'Maschio';

/*
** ------------------
** PAGINA UNITà
** ------------------
*/
$lang['UNIT_TITLE'] = 'UNITà';
$lang['UNIT_NOTE_1'] = 'Nota: Compra unità soldati per abilitare le missioni.';
$lang['UNIT_NOTE_2'] = 'Nota: Compra unità Cavalleria per migliorare la potenza della tua Cavalleria. Lotta, vinci e ruba soldi dal conto del tuo avversario.';
$lang['UNIT_NOTE_3'] = 'Nota: Compra unità della Marina per migliorare la tua potenza navale. Lotta, vinci e ruba soldi dal conto del tuo avversario.';
$lang['UNIT_NOTE_4'] = 'Nota: Compra unità dell\'avviazione per migliorare la tua potenza aerea. Lotta, vinci e ruba soldi dal conto del tuo avversario.';
$lang['UNIT_NOTE_6'] = 'Nota: Compra unità Intel units per migliorare la potenza del tuo Intelligence. Lotta, vinci per iniziare una rivolta nelle regioni terrestri e ruba soldi dal conto Trasquera o SwissCore del tuo avversario.';

$lang['UNIT_NOTE_8'] = 'Nota: Compra Droni Lunari per migliorare la potenza dei tuoi Droni. Lotta, vinci e ruba soldi dal conto del tuo avversario.';
$lang['UNIT_NOTE_7'] = 'Nota: Compra  Guerrieri Lunari per migliorare la potenza dei tuoi Guerrieri. Lotta, vinci e ruba soldi dal conto del tuo avversario.';
$lang['UNIT_NOTE_9'] = 'Nota: Compra Navicelle Lunari per migliorare la potenza dele tue Navicelle. Lotta, vinci e ruba soldi dal conto del tuo avversario.';
$lang['UNIT_NOTE_12'] = 'Nota: Compra Esploratori Lunari per migliorare la potenza dei tuoi Esploratori. Lotta, vinci per iniziare una rivolta nelle regioni lunari e ruba soldi dal conto Trasquera o SwissCore del tuo avversario.';

$lang['UNIT_NOTE_13'] = 'Nota: Compra Droni Marziani per migliorare la potenza dei tuoi Droni. Lotta, vinci e ruba soldi dal conto del tuo avversario.';
$lang['UNIT_NOTE_14'] = 'Nota: Compra Guerrieri Marziani per migliorare la potenza dei tuoi Guerrieri. Lotta, vinci e ruba soldi dal conto del tuo avversario.';
$lang['UNIT_NOTE_15'] = 'Nota: Compra Navicelle Marziane per migliorare la potenza dele tue Navicelle. Lotta, vinci e ruba soldi dal conto del tuo avversario.';
$lang['UNIT_NOTE_16'] = 'Nota: Compra Esploratori Marziani per migliorare la potenza dei tuoi Esploratori. Lotta, vinci per iniziare una rivolta nelle regioni marziani e ruba soldi dal conto Trasquera o SwissCore del tuo avversario.';

$lang['UNIT_NOTE_19'] = 'Nota: Compra Droni Mercure per migliorare la potenza dei tuoi Droni. Lotta, vinci e ruba soldi dal conto del tuo avversario.';
$lang['UNIT_NOTE_20'] = 'Nota: Compra Guerrieri Mercure per migliorare la potenza dei tuoi Guerrieri. Lotta, vinci e ruba soldi dal conto del tuo avversario.';
$lang['UNIT_NOTE_21'] = 'Nota: Compra Navicelle Mercure per migliorare la potenza dele tue Navicelle. Lotta, vinci e ruba soldi dal conto del tuo avversario.';
$lang['UNIT_NOTE_22'] = 'Nota: Compra Esploratori Mercure per migliorare la potenza dei tuoi Esploratori. Lotta, vinci per iniziare una rivolta nelle regioni marziani e ruba soldi dal conto Trasquera o SwissCore del tuo avversario.';

$lang['UNIT_DISBAND'] = 'Hai rimosso %s %s per %s. Ancora %s posizionati.';
$lang['UNIT_DISBAND_FAILED'] = 'Non hai %s %s. Ancora %s posizionati.';

$lang['UNIT_DEPLOY'] = 'Hai posizionato %s %s per %s. Ora %s posizionati.';
$lang['UNIT_NO_UPKEEP'] = 'Non hai abbastanza introito orario per sostenere %s %s.';
$lang['UNIT_NO_FUNDS'] = 'Non hai abbastanza soldi per comprare %s %s per %s.';
$lang['UNIT_MAX'] = 'Non più di %s %s(s) permessi!';

/*
** ------------------
** DATI EDIFICI
** ------------------
*/

/* Edifici Terra */
$lang['BUILDING_GROUP_1']  = 'Introito';
$lang['BUILDING_GROUP_2']  = 'Difesa';
$lang['BUILDING_GROUP_3']  = 'Energia';
$lang['BUILDING_GROUP_4']  = 'Sconto';
$lang['BUILDING_GROUP_5']  = 'Manutenzione';

/* Edifici Luna */
$lang['BUILDING_GROUP_6']  = 'Introito';
$lang['BUILDING_GROUP_7']  = 'Difesa';
$lang['BUILDING_GROUP_8']  = 'Energia';
$lang['BUILDING_GROUP_9']  = 'Sconto';
$lang['BUILDING_GROUP_10'] = 'Manutenzione';

/* Edifici Marte */
$lang['BUILDING_GROUP_11'] = 'Introito';
$lang['BUILDING_GROUP_12'] = 'Difesa';
$lang['BUILDING_GROUP_13'] = 'Energia';
$lang['BUILDING_GROUP_14'] = 'Sconto';
$lang['BUILDING_GROUP_15'] = 'Manutenzione';

/* Edifici Mercure */
$lang['BUILDING_GROUP_16'] = 'Introito';
$lang['BUILDING_GROUP_17'] = 'Difesa';
$lang['BUILDING_GROUP_18'] = 'Energia';
$lang['BUILDING_GROUP_19'] = 'Sconto';
$lang['BUILDING_GROUP_20'] = 'Manutenzione';

/* Introito (Terra) - Gruppo 1 */
$lang['BUILDING_1']  = 'Deposito merci';
$lang['BUILDING_3']  = 'Raffineria';
$lang['BUILDING_6']  = 'Fabbrica armi';
$lang['BUILDING_8']  = 'Centro communicazioni';
$lang['BUILDING_24'] = 'Fabbrica Bioscientifica';
$lang['BUILDING_12'] = 'Pozzo petrolifero';
$lang['BUILDING_14'] = 'Laboratorio ricerca militare';
$lang['BUILDING_16'] = 'Sito test nucleari';
$lang['BUILDING_25'] = 'Fabbrica trattamento acqua';
$lang['BUILDING_17'] = 'Rete satellitare solare';

/* Difesa (Terra) - Gruppo 2 */
$lang['BUILDING_2']  = 'Bunker';
$lang['BUILDING_21'] = 'Campo minato marino';
$lang['BUILDING_51'] = 'Ambasciata';
$lang['BUILDING_22'] = 'Lanciatorpedo';
$lang['BUILDING_11'] = 'Campo minato terrestre';
$lang['BUILDING_52'] = 'Centro commando Intelligence';
$lang['BUILDING_23'] = 'Fabbrica sottomarini';
$lang['BUILDING_53'] = 'Centro controllo droni';
$lang['BUILDING_54'] = 'Centro strategico cyberspazio';

/* Energia (Terra) - Group 3 */
$lang['BUILDING_4']  = 'Unità energia solare';
$lang['BUILDING_10'] = 'Generatore mobile';
$lang['BUILDING_13'] = 'Fabbrica energia gas';
$lang['BUILDING_18'] = 'Fattoria energia eolica';
$lang['BUILDING_19'] = 'Estrattori petrolio';
$lang['BUILDING_26'] = 'Fabbrica energia solare';
$lang['BUILDING_27'] = 'Fattoria energia eolica offshore';
$lang['BUILDING_28'] = 'Fabbrica energia geotermale';
$lang['BUILDING_35'] = 'Diga idroelettrica';
$lang['BUILDING_39'] = 'Centrale nucleare';

/* Sconto (Terra) - Gruppo 4 */
$lang['BUILDING_29'] = 'Deposito mobile militare';
$lang['BUILDING_40'] = 'Deposito merci militare';
$lang['BUILDING_37'] = 'Ospedale mobile';
$lang['BUILDING_38'] = 'Centro comando';
$lang['BUILDING_30'] = 'Campo addestramento militare';
$lang['BUILDING_31'] = 'Accademia militare';
$lang['BUILDING_32'] = 'Zona attività ricreative';
$lang['BUILDING_33'] = 'Statua militare';
$lang['BUILDING_34'] = 'Alloggi militari';
$lang['BUILDING_36'] = 'Ufficio del Presidente';

/* Manutenzione (Terra) - Gruppo 5 */
$lang['BUILDING_41'] = 'Manutenzione stradale';
$lang['BUILDING_42'] = 'Manutenzione ponti';
$lang['BUILDING_43'] = 'Garage trasporti militari';
$lang['BUILDING_44'] = 'Hangar elicotteri';
$lang['BUILDING_45'] = 'Garage autovetture';
$lang['BUILDING_46'] = 'Porto della Marina';
$lang['BUILDING_47'] = 'Manutenzione edifici';
$lang['BUILDING_48'] = 'Porto sottomarini';
$lang['BUILDING_49'] = 'Manutenzione edifici energetici';
$lang['BUILDING_50'] = 'Hangar aerei';

/* Introito (Luna) - Gruppo 6 */
$lang['BUILDING_600'] = 'Base generale';
$lang['BUILDING_601'] = 'Centro esplora e ricerca';
$lang['BUILDING_602'] = 'Alloggi personale';
$lang['BUILDING_603'] = 'Fabbrica ossigeno';
$lang['BUILDING_604'] = 'Fabbrica acqua';
$lang['BUILDING_605'] = 'Centro communicazioni';
$lang['BUILDING_606'] = 'Serra';
$lang['BUILDING_607'] = 'Fabbrica edile';
$lang['BUILDING_608'] = 'Centro estrazioni minerarie';
$lang['BUILDING_609'] = 'Centro lanci Navicelle';
$lang['BUILDING_610'] = 'Ospedale lunare';
$lang['BUILDING_611'] = 'Centro terraforming';

/* Difesa (Luna) - Gruppo 7 */
$lang['BUILDING_700'] = 'Centro ricerca difesa';
$lang['BUILDING_701'] = 'Fabbrica droni';
$lang['BUILDING_702'] = 'Missili a corto raggio';
$lang['BUILDING_703'] = 'Fabbrica guerrieri';
$lang['BUILDING_704'] = 'Sistema allarme';
$lang['BUILDING_705'] = 'Laser a lungo raggio';
$lang['BUILDING_706'] = 'Fabbrica Navicelle';
$lang['BUILDING_707'] = 'Scudo d\'energia';
$lang['BUILDING_708'] = 'Lanciamissili nucleari';
$lang['BUILDING_709'] = 'Fabbrica armi Taser';
$lang['BUILDING_710'] = 'Fabbrica armi fotoniche';
$lang['BUILDING_711'] = 'Difensore mobile androidi';
$lang['BUILDING_712'] = 'Scudo difesa colonia';
$lang['BUILDING_713'] = 'Fabbrica sotteranea';
$lang['BUILDING_714'] = 'Lancia Navicelle';

/* Energia (Luna) - Gruppo 8 */
$lang['BUILDING_800'] = 'Centro ricerca gas';
$lang['BUILDING_801'] = 'Centro ricerca petrolio';
$lang['BUILDING_802'] = 'Estrattori gas';
$lang['BUILDING_803'] = 'Estrattori petrolio';
$lang['BUILDING_804'] = 'Fabbrica energia solare';
$lang['BUILDING_805'] = 'Fabbrica energia gas';
$lang['BUILDING_806'] = 'Minifabbrica energia solare';
$lang['BUILDING_807'] = 'Centrale nucleare';
$lang['BUILDING_808'] = 'Grande fabbrica energia solare';
$lang['BUILDING_809'] = 'Mini colonia spaziale';
$lang['BUILDING_810'] = 'Sistema griglia solare';
$lang['BUILDING_811'] = 'Colonia grande spaziale';

/* Sconto (Luna) - Gruppo 9 */
$lang['BUILDING_900'] = 'Grattacielo lunare';
$lang['BUILDING_901'] = 'Ponte lunare';
$lang['BUILDING_902'] = 'Villaggio Moonrock';
$lang['BUILDING_903'] = 'Alloggi militari';
$lang['BUILDING_904'] = 'Base vulcanica lunare';
$lang['BUILDING_905'] = 'Villaggio lunare';
$lang['BUILDING_906'] = 'Campo d\'addestramento lunare';
$lang['BUILDING_907'] = 'Lanciamissili lunari';
$lang['BUILDING_908'] = 'Ufficio del Presidente lunare';
$lang['BUILDING_909'] = 'Accademia militare lunare';
$lang['BUILDING_910'] = 'Zona attività ricreative lunare';
$lang['BUILDING_911'] = 'Centro comando lunare';

/* Manutenzione (Luna) - Gruppo 10 */
$lang['BUILDING_1000'] = 'Centro riparazioni unità';
$lang['BUILDING_1001'] = 'Centro riparazioni Droni';
$lang['BUILDING_1002'] = 'Centro riparazioni Missili';
$lang['BUILDING_1003'] = 'Centro riparazioni Esploratori';
$lang['BUILDING_1004'] = 'Centro riparazioni Veicoli';
$lang['BUILDING_1005'] = 'Centro riparazioni Guerrieri';
$lang['BUILDING_1006'] = 'Centro riparazioni Infrastrutture';
$lang['BUILDING_1007'] = 'Centro Architetti lunari';
$lang['BUILDING_1008'] = 'Centro Compagnia Elettrica';
$lang['BUILDING_1009'] = 'Centro riparazioni Robot';

/* Introito (Marte) - Gruppo 11 */
$lang['BUILDING_1100'] = 'Base generale';
$lang['BUILDING_1101'] = 'Centro esplora e ricerca';
$lang['BUILDING_1102'] = 'Fabbrica ossigeno';
$lang['BUILDING_1103'] = 'Alloggi personale';
$lang['BUILDING_1104'] = 'Fabbrica acqua';
$lang['BUILDING_1105'] = 'Centro estrazioni minerarie';
$lang['BUILDING_1106'] = 'Centro communicazioni';
$lang['BUILDING_1107'] = 'Centro copertura';
$lang['BUILDING_1108'] = 'Serra';
$lang['BUILDING_1109'] = 'Hotel Marte';

/* Difesa (Marte) - Gruppo 12 */
$lang['BUILDING_1200'] = 'Centro ricerca';
$lang['BUILDING_1201'] = 'Fabbrica armi';
$lang['BUILDING_1202'] = 'Missile a corto raggio';
$lang['BUILDING_1203'] = 'Fabbrica guerrieri';
$lang['BUILDING_1204'] = 'Sitema allarme';
$lang['BUILDING_1205'] = 'Fabbrica Navicelle';
$lang['BUILDING_1206'] = 'Lanciamissili a lungo raggio';
$lang['BUILDING_1207'] = 'Fabbrica Esploratori';
$lang['BUILDING_1208'] = 'Fabbrica Droni';
$lang['BUILDING_1209'] = 'Fabbrica avanzata guerrieri';

/* Energia (Marte) - Gruppo 13 */
$lang['BUILDING_1300'] = 'Centro ricerca energia';
$lang['BUILDING_1301'] = 'Fabbrica energia gas';
$lang['BUILDING_1302'] = 'Centro ricerca petrolio';
$lang['BUILDING_1303'] = 'Estrattori petrolio';
$lang['BUILDING_1304'] = 'Fabbrica energia solare';
$lang['BUILDING_1305'] = 'Estrattori gas';
$lang['BUILDING_1306'] = 'Centro minerario';
$lang['BUILDING_1307'] = 'Centrale nucleare';
$lang['BUILDING_1308'] = 'Fabbrica grande orbita solare';
$lang['BUILDING_1309'] = 'Grande colonia marziana';

/* Sconto (Marte) - Gruppo 14 */
$lang['BUILDING_1400'] = 'Centro addestramento';
$lang['BUILDING_1401'] = 'Centro terraforming';
$lang['BUILDING_1402'] = 'Alloggi personale militare';
$lang['BUILDING_1403'] = 'Alloggi militari';
$lang['BUILDING_1404'] = 'Deposito merci';
$lang['BUILDING_1405'] = 'Compagnia edile';
$lang['BUILDING_1406'] = 'Campo addestramento';
$lang['BUILDING_1407'] = 'Ufficio del Presidente';
$lang['BUILDING_1408'] = 'Villaggio';

/* Manutenzione (Marte) - Gruppo 15 */
$lang['BUILDING_1500'] = 'Centro riparazione unità';
$lang['BUILDING_1501'] = 'Centro riparazione droni';
$lang['BUILDING_1502'] = 'Centro riparazione Missili';
$lang['BUILDING_1503'] = 'Centro riparazione Esploratori';
$lang['BUILDING_1504'] = 'Centro riparazione Veicoli';
$lang['BUILDING_1505'] = 'Centro riparazione Guerrieri';
$lang['BUILDING_1506'] = 'Centro riparazione Infrastrutture';
$lang['BUILDING_1507'] = 'Centro Architetti';
$lang['BUILDING_1508'] = 'Compagnia Elettrica';
$lang['BUILDING_1509'] = 'Centro riparazione Robot';

/* Introito (Mercure) - Group 16 */
$lang['BUILDING_1600'] = 'Base generale';
$lang['BUILDING_1601'] = 'Centro esplora e ricerca';
$lang['BUILDING_1602'] = 'Fabbrica ossigeno';
$lang['BUILDING_1603'] = 'Alloggi personale';
$lang['BUILDING_1604'] = 'Fabbrica acqua';
$lang['BUILDING_1605'] = 'Centro estrazioni minerarie';
$lang['BUILDING_1606'] = 'Centro communicazioni';
$lang['BUILDING_1607'] = 'Centro copertura';
$lang['BUILDING_1608'] = 'Serra';
$lang['BUILDING_1609'] = 'Hotel Mercure';

/* Difesa (Mercure) - Group 17 */
$lang['BUILDING_1700'] = 'Centro ricerca';
$lang['BUILDING_1701'] = 'Fabbrica armi';
$lang['BUILDING_1702'] = 'Missile a corto raggio';
$lang['BUILDING_1703'] = 'Fabbrica guerrieri';
$lang['BUILDING_1704'] = 'Sitema allarme';
$lang['BUILDING_1705'] = 'Fabbrica Navicelle';
$lang['BUILDING_1706'] = 'Lanciamissili a lungo raggio';
$lang['BUILDING_1707'] = 'Fabbrica Esploratori';
$lang['BUILDING_1708'] = 'Fabbrica Droni';
$lang['BUILDING_1709'] = 'Fabbrica avanzata guerrieri';

/* Energia (Mercure) - Group 18 */
$lang['BUILDING_1800'] = 'Centro ricerca energia';
$lang['BUILDING_1801'] = 'Fabbrica energia gas';
$lang['BUILDING_1802'] = 'Centro ricerca petrolio';
$lang['BUILDING_1803'] = 'Estrattori petrolio';
$lang['BUILDING_1804'] = 'Fabbrica energia solare';
$lang['BUILDING_1805'] = 'Estrattori gas';
$lang['BUILDING_1806'] = 'Centro minerario';
$lang['BUILDING_1807'] = 'Centrale nucleare';
$lang['BUILDING_1808'] = 'Fabbrica grande orbita solare';
$lang['BUILDING_1809'] = 'Grande colonia Mercure';

/* Sconto (Mercure) - Group 19 */
$lang['BUILDING_1900'] = 'Centro addestramento';
$lang['BUILDING_1901'] = 'Centro terraforming';
$lang['BUILDING_1902'] = 'Alloggi personale militare';
$lang['BUILDING_1903'] = 'Alloggi militari';
$lang['BUILDING_1904'] = 'Deposito merci';
$lang['BUILDING_1905'] = 'Compagnia edile';
$lang['BUILDING_1906'] = 'Campo addestramento';
$lang['BUILDING_1907'] = 'Ufficio del Presidente';
$lang['BUILDING_1908'] = 'Villaggio';
$lang['BUILDING_1909'] = 'Zona ricreazione';

/* Manutenzione (Mercure) - Group 20 */
$lang['BUILDING_1200'] = 'Centro riparazione unità';
$lang['BUILDING_1201'] = 'Centro riparazione droni';
$lang['BUILDING_1202'] = 'Centro riparazione Missili';
$lang['BUILDING_1203'] = 'Centro riparazione Esploratori';
$lang['BUILDING_1204'] = 'Centro riparazione Veicoli';
$lang['BUILDING_1205'] = 'Centro riparazione Guerrieri';
$lang['BUILDING_1206'] = 'Centro riparazione Infrastrutture';
$lang['BUILDING_1207'] = 'Centro Architetti';
$lang['BUILDING_1208'] = 'Compagnia Elettrica';
$lang['BUILDING_1209'] = 'Centro riparazione Robot';

/*
** ------------------
** PAGINA EDIFICI
** ------------------
*/

$lang['BUILDING_TITLE'] = 'EDIFICI';
$lang['BUILDING_NOTE1'] = 'Nota: Gli edifici da introito terrestri producono introiti orari più alti. Ogni edificio contiene cittadini che aumentano il costo orario.';
$lang['BUILDING_NOTE2'] = 'Nota: Gli edifici da difesa terrestri aumentano la difesa contro gli attacchi. Ogni edificio contiene cittadini che aumentano il costo orario.';
$lang['BUILDING_NOTE3'] = 'Nota: Gli edifici energetici terrestri accelerano il recupero dell\'energia. Ogni edificio contiene cittadini che aumentano il costo orario.';
$lang['BUILDING_NOTE4'] = 'Nota: Gli edifici sconto offrono prezzi scontanti sull\'acquisto degli edifici. Ogni edificio contiene cittadini che aumentano il costo orario.';
$lang['BUILDING_NOTE5'] = 'Nota: Gli edifici da manutenzione accelerano le riparazioni delle unità che equivale a meno unità perse durante le lotte. Ogni edificio contiene cittadini che aumentano il costo orario.';

$lang['BUILDING_NOTE6'] = 'Nota: Gli edifici da introito lunari producono introiti più alti per la tua base lunare.';
$lang['BUILDING_NOTE7'] = 'Nota: Gli edifici da difesa lunari aumentano la difesa contro gli attacchi alla tua base lunare';
$lang['BUILDING_NOTE8'] = 'Nota: Gli edifici energetici lunari accelerano il recupero dell\'energia per la tua base lunare.';
$lang['BUILDING_NOTE9'] = 'Nota: Gli edifici sconto lunari offrono prezzi scontanti sull\'acquisto degli edifici.';
$lang['BUILDING_NOTE10'] = 'Nota: Gli edifici da manutenzione lunari accelerano le riparazioni delle unità che equivale a meno unità perse durante le lotte.';

$lang['BUILDING_NOTE11'] = 'Nota: Gli edifici da introito marziani producono introiti più alti per la tua base.';
$lang['BUILDING_NOTE12'] = 'Nota: Gli edifici da difesa marziani aumentano la difesa contro gli attacchi alla tua base.';
$lang['BUILDING_NOTE13'] = 'Nota: Gli edifici energetici marziani accelerano il recupero dell\'energia per la tua base.';
$lang['BUILDING_NOTE14'] = 'Nota: Gli edifici sconto marziani offrono prezzi scontanti sull\'acquisto degli edifici.';
$lang['BUILDING_NOTE15'] = 'Nota: Gli edifici da manutenzione marziani accelerano le riparazioni delle unità che equivale a meno unità perse durante le lotte.';

$lang['BUILDING_NOTE16'] = 'Nota: Gli edifici da introito marziani producono introiti più alti per la tua base Mercure.';
$lang['BUILDING_NOTE17'] = 'Nota: Gli edifici da difesa marziani aumentano la difesa contro gli attacchi alla tua base Mercure.';
$lang['BUILDING_NOTE18'] = 'Nota: Gli edifici energetici marziani accelerano il recupero dell\'energia per la tua base Mercure.';
$lang['BUILDING_NOTE19'] = 'Nota: Gli edifici sconto Mercure offrono prezzi scontanti sull\'acquisto degli edifici.';
$lang['BUILDING_NOTE20'] = 'Nota: Gli edifici da manutenzione Mercure accelerano le riparazioni delle unità che equivale a meno unità perse durante le lotte.';

$lang['BUILDING_SELL'] = 'Hai venduto %s %s per %s. Ancora %s posizionati.';
$lang['BUILDING_LOW_UPKEEP'] = 'Non hai abbastanza introito orario per vendere %s %s per %s.';
$lang['BUILDING_NOT_OWNED'] = 'Non hai %s %s.';

$lang['BUILDING_BUY'] = 'Hai comprato %s %s per %s. Ora %s posizionati.';
$lang['BUILDING_MAX'] = 'Non più di %s %s permessi!';
$lang['BUILDING_NO_FUNDS'] = 'Non hai abbastanza soldi per comprare %s %s per %s.'; 
$lang['BUILDING_LOW_UPKEEP2'] = 'Non hai abbastanza introito orario per comprare %s %s per %s.';

$lang['BUILDING_UPKEEP'] = 'Costo orario';
$lang['BUILDING_PRICE'] = 'Prezzo';
$lang['BUILDING_DEPLOYED'] = 'Posizionato';
$lang['BUILDING_GAIN'] = 'Guadagno';
$lang['BUILDING_ENERGY'] = 'Energia';
$lang['BUILDING_INCOME'] = 'Introito';
$lang['BUILDING_REQUIRED'] = 'Richiesto';

/*
** ------------------
** SOLDI 
** ------------------
*/

$lang['MONEY_TITLE'] = 'SOLDI';

/*
** ------------------
** BANCHE
** ------------------
*/

$lang['BANK_GROUP_1'] = 'Nazionale';
$lang['BANK_GROUP_2'] = 'Trasquera';
$lang['BANK_GROUP_3'] = 'SwissCore';

$lang['BANK_TITLE'] = 'BANCHE';
$lang['BANK_NOTE'] = 'Nota: C\'è una percentuale di %s% per qualunque deposito. La banca paga %s% di interessi giornalieri. ';
$lang['BANK_WARNING'] = 'Attenzione: Unità Intel o Esploratori di altri giocatori possono rubare soldi da questa banca.';

$lang['BANK_TRANSACTION_TYPE_0'] = 'Hai ritirato';
$lang['BANK_TRANSACTION_TYPE_1'] = 'Hai depositato';
$lang['BANK_TRANSACTION_TYPE_2'] = 'Percentuale banca';
$lang['BANK_TRANSACTION_TYPE_3'] = 'Fattura ricarica';		
$lang['BANK_TRANSACTION_TYPE_4'] = 'Interessi';	
$lang['BANK_TRANSACTION_TYPE_5'] = 'le spie rubano';
$lang['BANK_TRANSACTION_TYPE_6'] = 'Bonus ';

$lang['BANK_TRANSACTION_LOG'] = 'Fattura transazione';

$lang['BANK_WITHDRAW']= 'Ritirato %s dollari dalla banca';
$lang['BANK_WITHDRAW_FAILED'] = '%s dollari non sono disponibili sul conto bancario!';

$lang['BANK_DEPOSIT'] = 'Depositato %s dollari in banca.';
$lang['BANK_DEPOSIT_FAILED'] = 'Non hai %s dollari.';

/*
** ------------------
** BORSA
** ------------------
*/

$lang['STOCK_GROUP_1'] = 'Nasdaq';
$lang['STOCK_GROUP_2'] = 'DowJones';
$lang['STOCK_GROUP_3'] = 'AEX';
$lang['STOCK_GROUP_4'] = 'Personale';

$lang['STOCK_TITLE'] = 'BORSA';
$lang['STOCK_BROKER_ERROR'] = 'Connessione col broker fallita. Il trading non è disponibile al momento. Per favore, riprova più tardi.';
$lang['STOCK_BUY'] = 'Hai comprato %s %s azioni per %s dollari. Ora, %s possedute.';
$lang['STOCK_NO_MONEY'] = 'Non hai abbastanza soldi per comprare %s azioni %s per %s dollari.';
$lang['STOCK_PRICE'] = 'Prezzo azioni %s [%s]';
$lang['STOCK_PROFIT'] = 'Profitto azioni %s [%s]';
$lang['STOCK_NOT_OWNED'] = 'Non possiedi %s azioni %s.';
$lang['STOCK_SELL'] = 'Hai venduto %s azioni %s per %s dollari. Hai pagato %s dollari di percentuale per la transazione. Ancora %s possedute.';
$lang['STOCK_NOTE'] = 'Nota: Puoi comprare o vendere azioni per generare profitto. I prezzi delle azioni sono basate su info in tempo reale da Yahoo! Finanza. C\'è una percentuale di %s% da pagare su ogni transazione di vendita.';
$lang['STOCK_PRICE_TO_LOW'] = 'Prezzo azione troppo basso. Trading bloccato!';

$lang['STOCK_SYMBOL'] = 'Simbolo azione'; 
$lang['STOCK_SYMBOL_INFO'] = 'Nota: Inserisci un simbolo finaziario Yahoo! Finanza per personalizzare questa lista.'; 

$lang['STOCK_ADD'] = 'Aggiungi azione';
$lang['STOCK_SYMBOL_ADDED'] = 'Hai aggiunto (%s) alla tua lista personale di azioni.';
$lang['STOCK_NO_SYMBOLS' ] = 'Non hai ancora aggiunto azioni personali!';
$lang['STOCK_SYMBOL_NOT_FOUND'] = 'Simbolo azione (%s) non esiste!';
$lang['STOCK_SYMBOL_AVAILABLE'] = 'Simbolo azione (%s) già disponibile nella lista personale.';

$lang['STOCK_REMOVE'] = 'Rimuovi azione';
$lang['STOCK_SYMBOL_REMOVED'] = 'Simbolo azione rimosso!';

$lang['GENERAL_STOCKS'] = 'Azioni';

/*
** ------------------
** CASINò
** ------------------
*/

$lang['CASINO_TITLE'] = 'CASINò' ;

$lang['CASINO_1'] = 'Ruota-della-fortuna';
$lang['CASINO_2'] = 'Slot-Machine';

$lang['CASINO_MONEY'] = 'Soldi';
$lang['CASINO_NUMBER'] = 'Numero fortunato';
$lang['CASINO_BET'] = 'Scommetti';
$lang['CASINO_PLAY'] = 'Gioca';
$lang['CASINO_ROLL'] = 'Ruota';

$lang['CASINO_NO_BET'] = 'Inserisci somma scommessa!';
$lang['CASINO_NO_LUCKY_NUMBER'] = 'Inserisci numero fortunato!';
$lang['CASINO_BET_TO_LARGE'] = 'Scommessa troppo grande! Scommessa massima è %s dollari.'; 
$lang['CASINO_NO_MONEY'] = 'Non hai abbastanza soldi!'; 

$lang['CASINO_WIN'] = 'Il numero vincitore era %s. Hai vinto %s dollari.';
$lang['CASINO_LOST'] = 'Il numero vincitore era %s. Hai perso %s dollari.';

$lang['CASINO_NOTE1'] = 'Nota: Inserisci la tua scommessa e il tuo numero fortunato e premi il pulsante Gioca. Se sei fortunato, vinci 10 volte la tua scommessa.';
$lang['CASINO_NOTE2'] = 'Nota: Inserisci la tua scommessa e premi il pulsante Gioca. Forse la tua scommessa pagherà.';

$lang['CASINO_UNLOCK'] = '%s è sbloccato al livello %s';

$lang['CASINO_SLOTMACHINE_WIN'] = 'Hai vinto %s volte la tua scommessa. Hai vinto %s dollari.';
$lang['CASINO_SLOTMACHINE_LOST'] = 'Hai perso %s dollari.';
$lang['CASINO_SLOTMACHINE_HELP'] = 'Le seguenti combinazioni slot-machine pagheranno.';

/*
** ------------------
** ALLEANZA
** ------------------
*/

$lang['ALLIANCE_TITLE'] = 'ALLEANZA';

$lang['ALLIANCE_PENDING_TITLE1'] = 'Attendono';
$lang['ALLIANCE_PENDING_TITLE2'] = 'Attendono [%s accettati - %s alleati invitati]';

$lang['ALLIANCE_ACCEPT_TITLE1'] = 'Accettato';
$lang['ALLIANCE_ACCEPT_TITLE2'] = 'Accettato [%s accettati - %s alleati invitati]';

$lang['ALLIANCE_INVITE_TITLE1'] = 'Invita';
$lang['ALLIANCE_INVITE_TITLE2'] = 'Invita [%s accettati - %s alleati invitati]';

$lang['ALLIANCE_NO_PENDING'] = 'Nessun invito in attesa!'; 
$lang['ALLIANCE_INVITATION'] = 'Invito mandato a %s!'; 
$lang['ALLIANCE_REJECT'] = 'Rifiuta %s come alleato!';
$lang['ALLIANCE_DROP'] = 'Rinuncia a %s come alleato!';
$lang['ALLIANCE_ACCEPT'] = 'Accetta %s come alleato!';
$lang['ALLIANCE_ALLY'] = 'Alleato';
$lang['ALLIANCE_MAXIMUM'] = 'Massima somma di %s alleati raggiunta per questo livello.'; 
$lang['ALLIANCE_LOCKED'] = 'Invito alleanza è sbloccato al livello 1';
$lang['ALLIANCE_NOTE'] = 'Nota: Con ogni alleato approvato puoi comandare 6 unità in più durante le lotte. Tieni a mente che non puoi attaccare gli alleati.';

$lang['ALLIANCE_INVITE_FRIENDS'] = 'Invita amico via email';
$lang['ALLIANCE_INVITE_NOTE'] = 'Nota: Invita un giocatore per un alleanza. Se l\'altro giocatore accetta o rifiuta you riceverai una notifica tramite mail (opzione in impostazioni). Massima somma di alleati per questo livello è %s.';
$lang['ALLIANCE_EMAIL_INVALID']= 'Indirizzo email non valido!';
$lang['ALLIANCE_ALREADY_INVITED'] = 'Indirizzo email già invitato!';
$lang['ALLIANCE_INVITE_SENT'] = 'Invito via mail mandato.';

$lang['ALLIANCE_COMMENT_TITLE'] = 'Messaggio';
$lang['ALLIANCE_COMMENT_TEXT1'] = 'Crea messaggio (max. 400 caratteri) per tutti i giocatori';
$lang['ALLIANCE_COMMENT_TEXT2'] = 'Crea messaggio (max. 400 caratteri) per %s';
$lang['ALLIANCE_PLAYER_NEWS'] = 'Messaggi';
$lang['ALLIANCE_COMMENT_ALL'] = 'Messaggio salvato e disponbile per tutti i giocatori.';
$lang['ALLIANCE_COMMENT_PLAYER'] = 'Mesaggio mandato a %s';

$lang['LEADERBORD_BEST_PLAYER'] = 'Tabella leader (Migliori Giocatori)';
$lang['LEADERBORD_BEST_PLAYER_NOTE'] = 'Nota: La tabella mostra i migliori giocatori umani. I robot di WarQuest (cyberspazio) non vengono mostrati!';

$lang['LEADERBORD_BEST_COUNTRY'] = 'Tabella leader (Migliori Paesi)';
$lang['LEADERBORD_BEST_COUNTRY_NOTE'] = 'Nota: Nota: La tabella mostra i migliori paesi reali.';

$lang['LEADERBORD_PLAYER_COUNTRY'] = 'Tabella leader (Migliori Giocatori di %s)';
$lang['LEADERBORD_PLAYER_COUNTRY_NOTE'] = 'Nota: La tabella mostra i migliori giocatori umani del paese selezionato.';

/*
** ------------------
** FORUM 
** ------------------
*/

$lang['FORUM_TITLE'] = 'FORUM'; 
$lang['FORUM_TITLE2'] = 'Forum';
$lang['FORUM_NOTE'] = 'Nota: Seleziona un forum per vedere tutti i topic postati.';

$lang['FORUM_1'] = 'Annunci ufficiali'; 
$lang['FORUM_NOTE_1'] = 'Annunci generali';
$lang['FORUM_2'] = 'Segnalazioni bug'; 
$lang['FORUM_NOTE_2'] = 'Cosa non va in questa versione?';
$lang['FORUM_3'] = 'Richieste novità'; 
$lang['FORUM_NOTE_3'] = 'Cosa vorresti nella prossima versione?';
$lang['FORUM_4'] = 'Aiuto'; 
$lang['FORUM_NOTE_4'] = 'Cosa non è chiaro in WarQuest?';
$lang['FORUM_5'] = 'Altro'; 
$lang['FORUM_NOTE_5'] = 'Qualunque altra discussione?';
$lang['FORUM_6'] = 'Community paesi'; 
$lang['FORUM_NOTE_6'] = 'Discussioni in lingua locale?';

$lang['FORUM_SEARCH_TOKEN'] = 'Elemento ricerca deve essere lungo almeno 3 caratteri.';

$lang['TOPIC_TITLE'] = 'Topic'; 
$lang['TOPIC_CREATED_INPUT'] = 'Crea nuovo topic (max. 80 caratteri)';
$lang['TOPIC_CREATED'] = 'Topic creato';
$lang['TOPIC_UPDATED'] = 'Topic aggiornato';
$lang['TOPIC_DELETED'] = 'Topic cancellato';
$lang['TOPIC_NO_TOPICS'] = 'Al momento nessun topic trovato.';
$lang['TOPIC_NOTE'] = 'Nota: Seleziona un topic per leggere/scrivere messaggi postati o creare un nuovo topic.'; 
$lang['TOPIC_CREATED_BY'] = '(Creato da %s)';

/*
** ------------------
** FORUM - POLL
** ------------------
*/

$lang['POLL_TITLE'] = 'Sondaggi';
$lang['POLL_RESULT_TITLE'] = 'Risultati sondaggi';
$lang['POLL_TEASER_TITLE'] = 'Nuovo sondaggio';
$lang['POLL_RESULTS'] = 'Risultati';
$lang['POLL_ClOSED'] = '(Sondaggio chiuso)';
$lang['POLL_VOTE_ADD'] = 'Grazie per il tuo voto! Hai ricevuto 10 punti esperienza bonus come premio.';
$lang['POLL_VOTE_REMOVE'] = 'Il tuo voto è stato annullato!';
$lang['POLL_VOTE'] = 'Vota';
$lang['POLL_VOTES'] = 'Voti';
$lang['POLL_CANCEL'] = 'Annulla';
$lang['POLL_SUMMARY'] = 'Totale votanti: %s';
$lang['POLL_WARNING'] = 'Seleziona una delle possibili opzioni di voto!';

/*
** ------------------
** FORUM - CHAT
** ------------------
*/

$lang['CHATROOM_TITLE'] = 'Chatroom';
$lang['CHATROOM_NOTE'] = 'Nota: Inizia una sessione di chat selezionando un giocatore online!';
$lang['CHATROOM_LAST_ACTIVE'] = 'Ultimo attivo';
$lang['CHATROOM_CHAT'] = 'Chat';
$lang['CHAT_NOTE'] = 'Nota: Inserisci un messaggio per iniziare la chat!';

$lang['CHAT_TITLE'] = 'Chat';

/*
** ------------------
** PAGINA AIUTO
** ------------------
*/

$lang['HELP_TITLE'] = 'AIUTO';

$lang['HELP_GENERAL_SUBTITLE'] = 'Istruzioni';

$lang['HELP_INTRO_TITLE'] = 'Introduzione';
$lang['HELP_INTRO'] =	'WarQuest è un gioco multiplayer online gratuito con una zona di guerra popolata da migliaia di giocatori reali. WarQuest ti porta nell\'anno 2020. Il mondo è in guerra. Lo scopo del gioco è di difendere il tuo paese e conquistare altri paesi. Compra armi e unità produttive, gioca missioni, lotta, fatti degli alleati e diventa il miglior giocatore del tuo paese.';

$lang['HELP_EXP_TITLE'] = 'Esperienza / Livello';
$lang['HELP_EXP'] = 'Gioca missioni e lotta per guadagnare punti esperienza. Quando hai abbastanza punti esperienza sarai in grado di passared al livello successivo. Una volta passato al livello successivo, la tua energia, salute e munizioni verranno ricaricate all\'istante.';

$lang['HELP_HEALTH_TITLE'] = 'Salute';
$lang['HELP_HEALTH'] = 'La tua salute diminuisce ad ogni lotta ma si ricarica automaticamente nel tempo. Puoi anche visitare l\'ospedale (Home -> Ricarica) e pagare per il recupero istantaneo.';

$lang['HELP_ENERGY_TITLE'] = 'Energia'; 
$lang['HELP_ENERGY'] = 'Il tuo livello di energia diminuisce ogni volta che giochi una missione ma si ricarica automaticamente nel tempo. Comprare edifici energetici ricaricherà la tua energia più in fretta. Puoi ricaricarla allo stesso modo della salute.';

$lang['HELP_AMMO_TITLE'] = 'Munizioni'; 
$lang['HELP_AMMO'] =	'Ogni lotta costa 1 munizione. Le munizioni vengono ricaricate automaticamente nel tempo. Puoi ricaricarla allo stesso modo dell\'energia e della salute.';

$lang['HELP_MISSION_TITLE'] = 'Missioni';
$lang['HELP_MISSION'] = 'Gioca missioni per guadagnare soldi e punti esperienza per raggiungere il livello successivo. 
Se una missione viene completata al 100%, guadagnerai il doppio dei soldi. Se un continente viene conquistato, 
riceverai un bonus all\'introito orario.';

$lang['HELP_BATTLE_TITLE'] = 'Lotta';
$lang['HELP_BATTLE'] =	'Lotta contro altri giocatori per guadagnare soldi e punti esperienza per raggiungere il livello successivo. Durante le lotte, unità ed edifici della tua base possono essere danneggiati o perfino persi.';

$lang['HELP_UNITS_TITLE'] = 'Unità';
$lang['HELP_UNITS'] =  'Durante gli attacchi, le tue unità migliori vengono selezionate automaticamente. La grandezza (somma di unità operative) del tuo esercito è decretata dalla grandezza della tua alleanza. Parti con un alleato che ti permette di commandare 6 unità. Ogni alleato approvato ti permette di commandare 6 unità in più. Puoi comprarne di più, ma solo le unità 6 volte la grandezza della tua alleanza verranno usate.';

$lang['HELP_BUILDINGS_TITLE'] = 'Edifici';
$lang['HELP_BUILDINGS'] = 'Durante il gioco gli edifici producono introito, difesa migliore, faster energia più rapida, 
sconti e/o manutenzione migliore delle unità. Ogni aquisto di edifici incrementerà il prezzo per gli aquisti futuri. Ogni edificio contiene cittadini che costano introito orario.';

$lang['HELP_BANKS_TITLE'] = 'Banche';
$lang['HELP_BANKS'] = 'Ogni banca addebiterà una parcentuale sui depositi. I soldi depositati nella Banca Nazionale 
sono al sicuro da altri giocatori ma dà degli interessi bassi. I soldi depositati nelle banche Trasquera o SwissCore 
danno interessi giornalieri migliori ma, unità Intel (Terra) o Esploratori (Luna/Marte) da altri giocatori possono rubarti dei soldi.';

$lang['HELP_ALLIANCE_TITLE'] = 'Alleanza'; 
$lang['HELP_ALLIANCE'] = 'Ogni alleato approvato ti permette di commandare 6 unità in più (che possiedi) 
durante le lotte. Aumenta la grandezza della tua alleanza per diventare più forte! Tieni a mente che tu non puoi attaccare gli alleati.';

$lang['HELP_SKILL_POINTS_TITLE'] = 'Punti skill';
$lang['HELP_SKILL_POINTS'] = 'Durante il gioco, i punti skill possono essere ricevuti. Usa i punti skill per 
aumentare le abilità attacco, difesa, salute, energia e/o munizioni. L\'aumento della skill Munizioni costa 2 punti skill, 
gli altri costeranno solo 1 punto skill. Puoi anche scambiare 2:1 punti skill per cambiare le tue abilità.';

$lang['HELP_TACTICS_TITLE'] = 'Tattiche';
$lang['HELP_TACTICS'] = 'Una cosa da tenere a mente, è che le unità usate in missioni sono soggette a perdite e feriti. Questo è importante da considerare quando il costo di rimpiazzo di alcune unità più costose usate in una missione può eccedere i soldi guadgnati dalla missione. In generale, se il tuo scopo e di massimizzare i soldi dalle missioni, allora concentrati sul valore Soldi / Energia delle missioni. 
Se il tuo scopo è quello di massimizzare punti esperienza, allora concentrati sul valore Esp / Energia delle missioni.<br/><br/>

Una volta che arrivi ai livelli superiori, il gioco aumenta automaticamente il numero di avversari che possono attaccarti. Quando questo accade, dovresti aumentare la grandezza della alleanza o massimizzare il numero dei tuoi alleati.<br/><br/>

Gli edifici da difesa sono l\'aquisto ideale perchè aumentano il punteggio della tua difesaa ogni qualvolta tu venga attaccato. 
Raccomando l\'aquisto di tutti quelli che puoi permetterti perchè ti permetterà di spendere più soldi per unità di attacco senza preoccuparti dei loro punti difesa.<br/><br/>

In WarQuest, gli edifici da difesa fanno alcuni avversari estremamente difficili da attaccare con successo. 
Anche se, è ancora raccomandabile mettere punti in difesa, io raccomando di mettere più punti possibile in attacco. Puoi compensare la bassa difesa delle abilità con edifici da difesa.<br/><br/>

Quando decidi che unità comprare, devi considerare con cura il costo orario delle unità e la potenza di Attacco e 
Difesa. Assumendo che puoi permetterti di comprare l\'unità, il costo non dovrebbe essere un fattore nella tua decisione perchè è un costo una tantum. Per il fatto della riduzione dell\'introito per colpa del costo orario delle unità, non sempre ha senso comprare le migliori unità disponibili. Se vinci la maggior parte delle tue lotte con le tue unità attuali, allora avrebbe più senso strategico non aumentare il tuo costo orario e permettere al tuo introito di aumentare in modo esponenziale.';

$lang['HELP_GRAVATAR_TITLE'] = 'Gravatar';
$lang['HELP_GRAVATAR'] = 'WarQuest supporta il servizio immagini di Gravatar (www.gravatar.com). Gravatar è un immagine che ti segue da sito a sito, apparendo accanto al tuo (nick)name.';

$lang['HELP_BOUNTY_TITLE'] = 'Caccia alla taglia';
$lang['HELP_BOUNTY'] = 'Puoi mettere una taglia sulla testa del tuo avversario. Il prezzo della taglia è relazionato al livello dell\'avversario. Dopo che hai messo la taglia, altri giocatori possono attaccare l\'avversario (Lotta -> Taglia).
Se l\'avversario viene sconfitto, perderà alcuni punti esperienza e i soldi della taglia vengono trasferiti al vincitore.';

$lang['HELP_UNITS_CONDITION_TITLE'] = 'Condizione Unità (CU)';
$lang['HELP_UNITS_CONDITION'] = 'Questo valore dà informazioni sulla condizione attuale delle tue unità. 
Se la condizione arriva a 0%, perderai alcune unità. Per prevenire la perdità di unità, puoi visitare 
(Home -> Ricarica) e riparare le unità operative.'; 

$lang['HELP_BUILDINGS_CONDITION_TITLE'] = 'Condizione Edifici (CE)';
$lang['HELP_BUILDINGS_CONDITION'] = 'Questo valore dà informazioni sulla condizione attuale dei tuoi edifici. Se la condizione arriva a 0%, perderai alcuni edifici. Per prevenire la perdita di edifici, 
puoi visitare (Home -> Ricarica) per riparare la tua base.'; 

$lang['HELP_FORUM_TITLE'] = 'Forum';
$lang['HELP_FORUM'] = 'Pwer avere più informazioni e chattare con altri giocatori, per favore visita il Forum di Warquest.';

$lang['HELP_WORLDMAP_TITLE'] = 'Cartina';
$lang['HELP_WORLDMAP'] = 'Ogni cartina del pianeta (Terra / Luna / Marte) contiene 72 regioni che possono essere conquistate attraverso le missioni. Le regioni possono avere uno dei seguenti colori: <br/>
- "Verde" Regione conquistata al 0%.<br/>
- "Giallo" Regione conquistata al 33%.<br/>
- "Viola" Regione conquistata al 66%.<br/>
- "Arancio" Regione conquistata al 100%.<br/>
- "Rosso" Rivolta nella regione. La regione va riconquistata.';

$lang['HELP_SHORTCUTS_TITLE'] = 'Scorciatoie menu';
$lang['HELP_SHORTCUTS'] = 'Le seguenti scorciatoie menù nascoste sono disponibili nel banner principale per una navigazione più veloce:<br/>
- Clicca "Contante" per andare nella pagina dei giocatori migliori.<br/>
- Clicca "Esp." per andare nella pagina dei paesi migliori.<br/>
- Clicca "Livello" per andare alla pagina dei sondaggi.<br/>
- Clicca "Salute" per andare alla pagina della Ricarica.<br/>
- Clicca "Energia" per andare alla pagina del profilo giocatore.<br/>
- Clicca "Munizioni" per andare alla pagina delle abilità.';

$lang['HELP_ATTACK_FORCE_TITLE'] = 'Forza attacco';
$lang['HELP_ATTACK_FORCE'] = 'Prima della lotta, puoi selezionare una delle seguenti forze di attacco:<br/><br/>
TERRA<br/>
- "Esercito" Migliori unità di Cavalleria, Marina e Avviazione terrestri.<br/>
- "Cavalleria" Solo unità terrestri di Cavalleria.<br/>
- "Marina" Solo unità terrestri della Marina.<br/>
- "Avviazione" Solo unità terrestri dell\'Avviazione.<br/>
- "Intel" Solo unità terrestri dell\'Intel.<br/><br/>
LUNA<br/>
- "Esercito" Migliori unità lunari di Droni, Guerrieri e Navicelle.<br/>
- "Droni" Solo unità lunari di Droni.<br/>
- "Guerrieri" Solo unità lunari di Guerrieri.<br/>
- "Navicelle" Solo unità lunari di Navicelle.<br/>
- "Esploratori " Solo unità lunari di Esploratori.<br/><br/>
MARTE<br/>
- "Esercito" Migliori unità marziane di Droni, Guerrieri e Navicelle.<br/>
- "Droni" Solo unità marziane di Droni.<br/>
- "Guerrieri" Solo unità marziane di Guerrieri.<br/>
- "Navicelle" Solo unità marziane di Navicelle.<br/>
- "Esploratori" Solo unità marziane di Esploratori.<br/>';

$lang['HELP_REBELLION_CONDITION_TITLE'] = 'Condizione Rivolta (CR)';
$lang['HELP_REBELLION_CONDITION'] = 'Questo valore dà informazioni sulla condizione di rivolta attuale. 
La rivolta delle regioni è azionata dagli attacchi dell\'Intel (Terra) o degli Esploratori (Luna/Marte) del 
tuo avversario. Se la condizione arriva al 100%, alcune delle tue regioni conquistate saranno in rivolta. 
Per prevenire le rivolte, visita (Home -> Ricarica) per sedarle. Ogni regione in rivolta ha come risultato 
introito orario posticipato. Ripristina il controllo nella regione in rivolta giocando la missione in questione.';

/*
** ------------------
** HELP - RELEASE NOTES
** ------------------
*/

$lang['HELP_NOTES_SUBTITLE1'] = 'Note di rilascio';
$lang['HELP_NOTES_SUBTITLE2'] = 'Note di rilascio (Solo in inglese)';

/*
** ------------------
** HELP - RANKS
** ------------------
*/

$lang['HELP_RANKS_SUBTITLE'] = 'Ranghi';
$lang['HELP_RANKS'] = 'I seguenti ranghi sono disponibili:';

/*
** ------------------
** HELP - AWARDS
** ------------------
*/

$lang['HELP_AWARDS_SUBTITLE'] = 'Premi';
$lang['HELP_BATTLE_AWARDS'] = 'I seguenti premi per la vittoria nelle lotte possono essere guadagnati:';
$lang['HELP_BOUNTY_AWARDS'] = 'I seguenti premi per le taglie messe possono essere guadagnati:';
$lang['HELP_REBEL_AWARDS'] = 'I seguenti premi per inizio rivolta possono essere guadgnati:';

/*
** ------------------
** HELP - LEVELS
** ------------------
*/

$lang['HELP_LEVEL_SUBTITLE'] = 'Livelli';
$lang['HELP_LEVEL'] = 'I seguenti livelli sono disponibili:';
$lang['HELP_LEVEL_UNIT_LOST'] = 'Unità perse';
$lang['HELP_LEVEL_EXPERIENCE'] = 'Esperienza';
$lang['HELP_LEVEL_FEATURES'] = 'Schema sblocco novità';

/*
** ------------------
** HELP - STATS
** ------------------
*/

$lang['HELP_STATS_TITLE'] = 'Statistiche';
$lang['HELP_STATS_NOTE'] = 'Nota: In questa pagina vengono mostrate le statistiche in tempo reale di WarQuest.';
$lang['HELP_STATS_PLAYERS'] = 'Nuovi giocatori';
$lang['HELP_STATS_ONLINE'] = 'Giocatori online';
$lang['HELP_STATS_FIGHTS'] = 'Lotte tra giocatori';
$lang['HELP_STATS_MISSIONS'] = 'Missioni giocate';
$lang['HELP_STATS_CASINO'] = 'Partite Casinò giocate';
$lang['HELP_STATS_REQUESTS'] = 'Richieste server';

/*
** ------------------
** HELP - DONATE
** ------------------
*/

$lang['HELP_DONATE_TITLE1'] = 'Dona';
$lang['HELP_DONATE_TITLE2'] = 'Dona';

$lang['HELP_SUBTITLE_DONATE1'] = 'Generale';
$lang['HELP_DONATE1'] = 'Il software di WarQuest può essere usato senza costi, ma se desideri esprimere 
il tuo apprezzamento per il tempo e le risorse che l\'autore ha speso svillupandolo e sostenendolo nel tempo, 
e anche per aiutare alla riduzione del costo per far andare il webserver, accettiamo e apprezziamo le donazioni.';

$lang['HELP_SUBTITLE_DONATE3'] = 'PayPal';
$lang['HELP_DONATE3'] = 'Per fare una donazione online usando la tua carta di credito o conto PayPal, clicca 
sotto e inserisci la somma con cui desideri contribuire. La tua carta di credito verrà processata da PayPal, un nome
fidato nelle transazioni online sicure. Grazie per il tuo contributo!';

/*
** ------------------
** HELP - ABOUT
** ------------------
*/

$lang['HELP_ABOUT_SUBTITLE'] = 'Info';
$lang['HELP_BACKGROUND_TITLE'] = 'Sfondo';
$lang['HELP_BACKGROUND'] = 'WarQuest è stato creato da <a target="new" href="http://www.plaatsoft.nl">PlaatSoft</a>. Idea original del gioco è basata su alcuni altri giochi disponibili nell\'appstore di Apple. Il motivo principale per ricreare questo tipo di di gioco è di creare un game play migliore e un interfaccia utente controllabili sui seguenti terminali: smartphone (Apple, Android, Nokia e BlackBerry), tablet(Samsung e Apple), Console (Nintendo) e tutti i tipi di notebook (Intel / AMD ecc...).';
$lang['HELP_CREDITS_TITLE'] = 'Crediti';
$lang['HELP_BROWSERS_TITLE'] = 'Browser supportati'; 
$lang['HELP_HARDWARE_TITLE'] = 'Hardware supportato'; 
$lang['HELP_DISCLAIMER_TITLE'] = 'Disclaimer'; 
$lang['HELP_DISCLAIMER'] = 'Il programma viene prodotto COSì COM\'è  e SENZA ALCUNA GARANZIA, INCLUSA LA GARANZIA DELLA VENDIBILITà DEL DESIGN E FORMA PER UN MOTIVO PARTICOLARE.<br/>';

$lang['HELP_CREDITS_TITLE'] = 'Crediti';
$lang['HELP_CREDITS'] = 'Grazie mille alle seguenti persone e organizzazioni che hanno aiutato a creare questo gioco:';
$lang['HELP_CREDITS_ARCHITECT'] = 'Architetto';
$lang['HELP_CREDITS_DEVELOPERS'] = 'Sviluppatore';
$lang['HELP_CREDITS_GRAPHICS'] = 'Grafica e Informazione';
$lang['HELP_CREDITS_TRANSLATORS'] = 'Traduttori';
$lang['HELP_CREDITS_TESTERS'] = 'Tester';
$lang['HELP_CREDITS_OTHER'] = 'Altri';
$lang['HELP_CREDITS_OTHER_NOTE'] = 'E ovviamente tutti i giocatori di WarQuest che hanno mandato ottimo feedback per migliorare il gioco. Gustati il gioco e divertiamoci!';

/*
** ------------------
** DATI RANGHI
** ------------------
*/

$lang['RANK_1'] = "Soldato semplice";
$lang['RANK_2'] = "Soldato di prima classe";
$lang['RANK_3'] = "Specialista";
$lang['RANK_4'] = "Caporale";
$lang['RANK_5'] = "Sergente";
$lang['RANK_6'] = "Sergente di truppa";
$lang['RANK_7'] = "Sergente di prima classe";
$lang['RANK_8'] = "Sergente capo";
$lang['RANK_9'] = "Primo sergente";
$lang['RANK_10'] = "Sergente maggiore";
$lang['RANK_11'] = "Sergente maggiore di commando";
$lang['RANK_12'] = "Sergente maggiore dell'Esercito";
$lang['RANK_13'] = "Secondo luogotenente";
$lang['RANK_14'] = "Primo luogotenente";
$lang['RANK_15'] = "Capitano";
$lang['RANK_16'] = "Maggiore";
$lang['RANK_17'] = "Colonello luogotenente";
$lang['RANK_18'] = "Colonello";
$lang['RANK_19'] = "Generale brigadiere";
$lang['RANK_20'] = "Generale maggiore";
$lang['RANK_21'] = "Generale luogotenente";
$lang['RANK_22'] = "Generale";
$lang['RANK_23'] = "Generale dell\'Esercito";

/*
** ------------------
** NOMI PAESI
** ------------------
*/

$landcode = array();

$landcode['ad'] = "Andorra";
$landcode['ae'] = "Emirati Arabi";
$landcode['af'] = "Afghanistan";
$landcode['ag'] = "Antigua e Barbuda";
$landcode['ai'] = "Anguilla";
$landcode['al'] = "Albania";
$landcode['am'] = "Armenia";
$landcode['an'] = "Antille Olandesi";
$landcode['ao'] = "Angola";
$landcode['aq'] = "Antarctica";
$landcode['ar'] = "Argentina";
$landcode['as'] = "Samoa Americana";
$landcode['at'] = "Austria";
$landcode['au'] = "Australia";
$landcode['aw'] = "Aruba";
$landcode['ax'] = "Isole Aland";
$landcode['az'] = "Azerbaijan";
		
$landcode['ba'] = "Bosnia e Herzegovina";
$landcode['bb'] = "Barbados";
$landcode['bd'] = "Bangladesh";
$landcode['be'] = "Belgio";
$landcode['bf'] = "Burkina Faso";
$landcode['bg'] = "Bulgaria";
$landcode['bh'] = "Bahrain";
$landcode['bi'] = "Burundi";
$landcode['bj'] = "Benin";
$landcode['bm'] = "Bermuda";
$landcode['bn'] = "Brunei Darussalam";	
$landcode['bl'] = "San Bartolomeo";
$landcode['bn'] = "Brunei";
$landcode['bo'] = "Bolivia";
$landcode['br'] = "Brasile";
$landcode['bs'] = "Bahamas";
$landcode['bt'] = "Bhutan";
$landcode['bv'] = "Isola Bouvet";
$landcode['bw'] = "Botswana";
$landcode['by'] = "Belarus";
$landcode['bz'] = "Belize";
	
$landcode['ca'] = "Canada";
$landcode['cc'] = "Isole Coco";
$landcode['cf'] = "Repubblica Centrale Africana";
$landcode['cg'] = "Congo";
$landcode['ch'] = "Svizzera";
$landcode['ci'] = "Costa d\'Avorio";
$landcode['ck'] = "Isole Cook";
$landcode['cl'] = "Chili";
$landcode['cm'] = "Camerun";
$landcode['cn'] = "Cina";
$landcode['co'] = "Colombia";
$landcode['cr'] = "Costa Rica";
$landcode['cs'] = "Serbia e Montenegro";
$landcode['cu'] = "Cuba";
$landcode['cv'] = "Capo Verde";
$landcode['cx'] = "Isola Natale";
$landcode['cy'] = "Cipro";
$landcode['cz'] = "Republica Ceca";
	
$landcode['de'] = "Germania";
$landcode['dj'] = "Djibouti";
$landcode['dk'] = "Danimarca";
$landcode['dm'] = "Dominica";
$landcode['do'] = "Repubblica Dominicana";
$landcode['dz'] = "Algeria";
	
$landcode['ec'] = "Ecuador";
$landcode['ee'] = "Estonia";
$landcode['eg'] = "Egitto";
$landcode['eh'] = "Sahara Ovest";
$landcode['er'] = "Eritrea";
$landcode['es'] = "Spagna";
$landcode['et'] = "Etiopia";
$landcode['eu'] = "Cyberspazio";
	
$landcode['fi'] = "Finlandia";
$landcode['fj'] = "Fiji";
$landcode['fk'] = "Isole Falkland";
$landcode['fm'] = "Micronesia";
$landcode['fo'] = "Isola Faroe";
$landcode['fr'] = "Francia";
	
$landcode['ga'] = "Gabon";
$landcode['gb'] = "Regno Unito";
$landcode['gd'] = "Grenada";
$landcode['ge'] = "Georgia";
$landcode['gf'] = "Guiana Francese";
$landcode['gh'] = "Ghana";
$landcode['gi'] = "Gibraltar";
$landcode['gl'] = "Groenlandia";
$landcode['gm'] = "Gambia";
$landcode['gn'] = "Guinea";
$landcode['gp'] = "Guadalupe";
$landcode['gq'] = "Guinea ecuatoriale";
$landcode['gr'] = "Grecia";
$landcode['gs'] = "Georgia Sud ";
$landcode['gt'] = "Guatemala";
$landcode['gu'] = "Guam";
$landcode['gw'] = "Guinea-Bissau";
$landcode['gy'] = "Guyana";
	
$landcode['hk'] = "Hong Kong";
$landcode['hm'] = "Isole Heard e McDonald";
$landcode['hn'] = "Honduras";
$landcode['hr'] = "Croazia";
$landcode['ht'] = "Haiti";
$landcode['hu'] = "Ungheria";
	
$landcode['id'] = "Indonesia";
$landcode['ie'] = "Irlanda";
$landcode['il'] = "Israele";
$landcode['in'] = "India";
$landcode['im'] = "Isola di Man";
$landcode['io'] = "Territorio Oceano BI";
$landcode['iq'] = "Iraq";
$landcode['ir'] = "Iran";
$landcode['is'] = "Islanda";
$landcode['it'] = "Italia";
	
$landcode['jm'] = "Giamaica";
$landcode['jo'] = "Giordania";
$landcode['jp'] = "Giappone";
	
$landcode['ke'] = "Kenya";
$landcode['kg'] = "Kyrgyzstan";
$landcode['kh'] = "Cambodia";
$landcode['ki'] = "Kiribati";
$landcode['km'] = "Comores";
$landcode['kn'] = "Saint Kitts en Nevis";
$landcode['kp'] = "Nord Corea";
$landcode['kr'] = "Sud Corea";
$landcode['kw'] = "Kuwait";
$landcode['ky'] = "Isole Cayman";
$landcode['kz'] = "Kazachstan";
	
$landcode['la'] = "Laos";
$landcode['lb'] = "Libia";
$landcode['lc'] = "San Lucia";
$landcode['li'] = "Liechtenstein";
$landcode['lk'] = "Sri Lanka";
$landcode['lr'] = "Liberia";
$landcode['ls'] = "Lesotho";
$landcode['lt'] = "Lituania";
$landcode['lu'] = "Luxemburg";
$landcode['lv'] = "Latvia";
$landcode['ly'] = "Libiana";
	
$landcode['ma'] = "Marocco";
$landcode['mc'] = "Monaco";
$landcode['md'] = "Moldavia";
$landcode['mg'] = "Madagascar";
$landcode['mh'] = "Isole Marshall";
$landcode['mk'] = "Macedonia";
$landcode['ml'] = "Mali";
$landcode['mm'] = "Myanmar";
$landcode['mn'] = "Mongolia";
$landcode['mo'] = "Macao";
$landcode['mp'] = "Isole Nordiche Mariana";
$landcode['mq'] = "Martinica";
$landcode['mr'] = "Mauritania";
$landcode['ms'] = "Montserrat";
$landcode['mt'] = "Malta";
$landcode['mu'] = "Mauritius";
$landcode['mv'] = "Maldive";
$landcode['mw'] = "Malawi";
$landcode['mx'] = "Messico";
$landcode['my'] = "Malaesia";
$landcode['mz'] = "Mozambico";
	
$landcode['na'] = "Namibia";
$landcode['nc'] = "Nuova Caledonia";
$landcode['ne'] = "Nigeria";
$landcode['nf'] = "Isole Norfolk";
$landcode['ng'] = "Nigeria";
$landcode['ni'] = "Nicaragua";
$landcode['nl'] = "Olanda";
$landcode['no'] = "Norvegia";
$landcode['np'] = "Nepal";
$landcode['nr'] = "Nauru";
$landcode['nu'] = "Niue";
$landcode['nz'] = "Nuova Zeelanda";
	
$landcode['om'] = "Oman";
	
$landcode['pa'] = "Panama";
$landcode['pe'] = "Perù";
$landcode['pf'] = "Polinesia Francese";
$landcode['pg'] = "Papua Nuova Guinea";
$landcode['ph'] = "Filippine";
$landcode['pk'] = "Pakistan";
$landcode['pl'] = "Polonia";
$landcode['pm'] = "Saint Pierre e Miquelon";
$landcode['pn'] = "Pitcairn";
$landcode['pr'] = "Porto Rico";
$landcode['ps'] = "Palestina";
$landcode['pt'] = "Portogallo";
$landcode['pw'] = "Palau";
$landcode['py'] = "Paraguay";
	
$landcode['qa'] = "Qatar";
	
$landcode['re'] = "Reunion";
$landcode['ro'] = "Romania";
$landcode['ru'] = "Federazione Russa";
$landcode['rs'] = "Serbia";
$landcode['rw'] = "Ruanda";
	
$landcode['sa'] = "Arabia Saudita";
$landcode['sb'] = "Isole Solomon";
$landcode['sc'] = "Seychelles";
$landcode['sd'] = "Sudan";
$landcode['se'] = "Svezia";
$landcode['sg'] = "Singapore";
$landcode['sh'] = "Saint-Helena";
$landcode['si'] = "Slovenia";
$landcode['sj'] = "Svalbard e Jan Mayen";
$landcode['sk'] = "Slovacchia";
$landcode['sl'] = "Sierra Leone";
$landcode['sm'] = "San Marino";
$landcode['sn'] = "Senegal";
$landcode['so'] = "Somalia";
$landcode['sr'] = "Suriname";
$landcode['st'] = "Sao Tome en Principe";
$landcode['sv'] = "El Salvador";
$landcode['sy'] = "Siria";
$landcode['sz'] = "Swaziland";
	
$landcode['tc'] = "Turks e Isole Caicos";
$landcode['td'] = "Ciad";
$landcode['tg'] = "Togo";
$landcode['th'] = "Tailandia";
$landcode['tj'] = "Tajikistan";
$landcode['tk'] = "Tokelau";
$landcode['tl'] = "Timor";
$landcode['tm'] = "Turkmenistan";
$landcode['tn'] = "Tunisia";
$landcode['to'] = "Tonga";
$landcode['tr'] = "Turchia";
$landcode['tt'] = "Trinidad e Tobago";
$landcode['tv'] = "Tuvalu";
$landcode['tw'] = "Taiwan";
$landcode['tz'] = "Tanzania";
	
$landcode['ua'] = "Ucraina";
$landcode['ug'] = "Uganda";
$landcode['um'] = "Isole Stati Uniti Minori Outlying";
$landcode['us'] = "Stati Uniti";
$landcode['uy'] = "Uruguay";	
$landcode['uz'] = "Uzbekistan";
	
$landcode['va'] = "Città del Vaticano";
$landcode['vc'] = "Saint Vincent e le Grenadines";
$landcode['ve'] = "Venezuela";
$landcode['vg'] = "Isole Vergini; Britanniche";
$landcode['vi'] = "Isole Vergini; SUA";
$landcode['vn'] = "Vietnam";
$landcode['vu'] = "Vanuatu";
	
$landcode['wf'] = "Wallis e Futuna";
$landcode['ws'] = "Samoa";
	
$landcode['ye'] = "Yemen";
$landcode['yt'] = "Mayotte";
	
$landcode['za'] = "Sud Africa";
$landcode['zm'] = "Zambia";
$landcode['zw'] = "Zimbabue";
	
/*
** ------------------
** LA FINE
** ------------------
*/

?>