<?php

/* 
**  ========
**  WARQUEST
**  ========
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  All copyrights reserved (c) 2008-2013 PlaatSoft
*/

/*
** Some translation remarks:
** (1) Every line has the following syntax $lang['<KEY>'] = '<DESCRIPTION>';
**     Only change the <DESCRIPTION> part. Leave the rest unchanged.
** (2) The <DESCRIPTION> part contain %s tags. DO NOT REMOVE THEN.
**     The %s are realtime replace with game parameters. 
**     For example: 'Restore for %s dollar' will be on screen 'Restore for 100 dollar'
** (3) The LINK keys contain the menu items of the game. Choose as short as possible words.
** (4) Leave HTML tags unchanged, for example <b>, </b>, etc....
**
** Good luck and have fun!
*/

/* 
** ------------------
** Language: Nederlands
** ------------------
*/

/*
** ------------------
** LINKS
** ------------------
*/

/* Login */
$lang['LINK_LOGIN']  = 'Inloggen'; 
$lang['LINK_REGISTER'] = 'Registeer'; 
$lang['LINK_RECOVER'] = 'Herstel'; 
$lang['LINK_MANUAL'] = 'Handleiding'; 
$lang['LINK_FACEBOOK'] = 'Facebook';
$lang['LINK_RSS']  = 'RSS'; 

/* General */
$lang['LINK_HOME'] = 'Start';
$lang['LINK_MISSIONS'] = 'Missies';
$lang['LINK_BATTLE'] = 'Strijd';
$lang['LINK_UNITS']  = 'Eenheden';
$lang['LINK_BUILDINGS']  = 'Gebouwen';
$lang['LINK_BANKS'] = 'Banken';
$lang['LINK_ALLIANCE'] = 'Alliantie';
$lang['LINK_PLAYER'] = 'Speler';
$lang['LINK_MONEY'] = 'Geld';
$lang['LINK_HELP'] = 'Help';
$lang['LINK_ADMIN'] = 'Admin';

$lang['LINK_FIRST'] = 'Eerste';
$lang['LINK_PREVIOUS'] = 'Vorige';
$lang['LINK_NEXT'] = 'Volgende';
$lang['LINK_LAST'] = 'Laatste';

/* Home */
$lang['LINK_RESTORE'] = 'Herstel';
$lang['LINK_REPAIR'] = 'Reparen';
$lang['LINK_TRADE'] = 'Handel';
$lang['LINK_ACTIVATE'] = 'Activeer';

/* Player */
$lang['LINK_OVERVIEW'] = 'Overzicht';
$lang['LINK_DELETE'] = 'Verwijder';
$lang['LINK_SETTINGS'] = 'Instellingen';
$lang['LINK_NEWS'] = 'Nieuws';
$lang['LINK_COMMENTS'] = 'Bericht';
$lang['LINK_STATISTICS'] = 'Statistieken';
$lang['LINK_LOGOUT'] = 'Logout';
$lang['LINK_EDIT']  = 'Aanpassen';
$lang['LINK_SAVE'] = 'Versturen';
$lang['LINK_REPLY'] = 'Beantwoorden';
$lang['LINK_PROFILE'] = 'Profiel';
$lang['LINK_SKILLS'] = 'Vaardigheid';
$lang['LINK_RECRUIT']  = 'Werven';
$lang['LINK_INCREASE'] = 'Verhoog';
$lang['LINK_DECREASE'] = 'Verlaag';
$lang['LINK_RESTORE_NOW']  = 'Herstel voor %s dollar';
$lang['LINK_CHANGE'] = 'Wijzig';
$lang['LINK_REPORT'] = 'Rapport';
$lang['LINK_BOUNTY'] = 'Premie';

/* Mission */
$lang['LINK_PLAY'] = 'Speel';
$lang['LINK_BUY_PLAY'] = 'Koop en Speel';
$lang['LINK_DO_AGAIN'] = 'Speel nogeens';

/* Battle */
$lang['LINK_ATTACK'] = 'Aanval';
$lang['LINK_BATTLES']  = 'Gevechten';
$lang['LINK_SP'] = 'Vaardigheden';

/* Unit */
$lang['LINK_DEPLOY'] = 'Koop';
$lang['LINK_DEPLOY_AGAIN'] = 'Koop weer';
$lang['LINK_DISBAND']  = 'Verkoop';
$lang['LINK_DISBAND_AGAIN']= 'Verkoop weer';

/* Building */
$lang['LINK_INCOME'] = 'Inkomen';
$lang['LINK_DEFENSE'] = 'Verdediging';
$lang['LINK_ENERGY'] = 'Energie';
$lang['LINK_BUY'] = 'Koop';
$lang['LINK_BUY_AGAIN'] = 'Koop weer';
$lang['LINK_SELL'] = 'Verkoop';
$lang['LINK_SELL_AGAIN'] = 'Verkoop weer';

/* Bank */
$lang['LINK_BANK'] = 'Bank';
$lang['LINK_STOCKEXCHANGE'] = 'Beurs';
$lang['LINK_CASINO'] = 'Casino';

$lang['LINK_DEPOSIT'] = 'Storten';
$lang['LINK_WITHDRAW'] = 'Opnemen';
$lang['LINK_BALANCE']  = 'Saldo';

/* Alliance */
$lang['LINK_INVITE'] = 'Uitnodigen';
$lang['LINK_PENDING'] = 'Gaande';
$lang['LINK_APPROVED'] = 'Geaccepteerd';
$lang['LINK_COMMENT']  = 'Bericht';
$lang['LINK_FORUM']  = 'Forum';
$lang['LINK_BEST_PLAYER']  = 'Beste-Spelers';
$lang['LINK_BEST_COUNTRY'] = 'Beste-Landen';
$lang['LINK_DROP'] = 'Afwijzen';
$lang['LINK_ACCEPT'] = 'Accepteren';
$lang['LINK_REJECT'] = 'Afwijzen';
$lang['LINK_SEND'] = 'Zend';
$lang['LINK_RESET']  = 'Reset';

/* Forum */
$lang['LINK_FORUM']  = 'Forum';
$lang['LINK_POLLS'] = 'Onderzoek';
$lang['LINK_CHATROOM'] = 'Chatroom';
$lang['LINK_SEARCH']  = 'Zoek';

/* Help */
$lang['LINK_GENERAL']  = 'Instructies';
$lang['LINK_NOTES']  = 'Versies';
$lang['LINK_RANKS']  = 'Rangen';
$lang['LINK_AWARDS'] = 'Onderscheidingen';
$lang['LINK_LEVELS']  = 'Nivo\'s';
$lang['LINK_STATS']  = 'Stats';
$lang['LINK_ABOUT']  = 'Over';
$lang['LINK_DONATE']  = 'Donatie';

/*
** ------------------
** GENERAL 
** ------------------
*/

$lang['SYSTEM_HACK_DETECTED'] = 'A.u.b. reload, terug en vooruit knop niet gebruiken!';

$lang['AGO_DAY']   = ' dag';
$lang['AGO_DAYS']  = ' dagen';
$lang['AGO_HOUR']  = ' uur';
$lang['AGO_HOURS'] = ' uren';
$lang['AGO_MIN']   = ' min';
$lang['AGO_MINS']  = ' min';
$lang['AGO_SEC']   = ' sec';
$lang['AGO_SECS']  = ' sec';

$lang['COPYRIGHT'] = 'Copyright © 2008-2013 - Alle rechten voorbehouden - <a target="new" href="http://www.plaatsoft.nl">PlaatSoft</a>';

$lang['STATUS_CASH']  = 'Geld';
$lang['STATUS_EXP']  = 'Erv.';
$lang['STATUS_LEVEL']  = 'Nivo';
$lang['STATUS_HEALTH'] = 'Gezondheid';
$lang['STATUS_ENERGY'] = 'Energie';
$lang['STATUS_AMMO'] = 'Munitie';
$lang['STATUS_ALLIANCE_SIZE'] = 'Alliantie';

$lang['BOX_INFO'] = 'INFORMATIE';
$lang['BOX_WARN'] = 'WAARSCHUWING';
$lang['BOX_ERROR'] = 'ERROR';

$lang['GENERAL_NEXT_LEVEL'] = 'Geweldig! Je hebt het volgende nivo bereikt! Je ontvangt %s ervaringspunten en %s dollar. Je gezondheid, energie en munitie is hersteld.';
$lang['GENERAL_BATTLE_LEVEL'] = 'Briljant! Je hebt %s gevechten gewonnen. Je hebt %s ervaringspunt(en) en %s dollar verdiend.';
$lang['GENERAL_BOUNTY_LEVEL'] = 'Great! You have set %s bounties and received %s extra skill point(s) and %s dollars.';
$lang['GENERAL_REBEL_LEVEL'] = 'Great! You started %s rebellions and received %s extra skill point(s) and %s dollars.';
$lang['GENERAL_BATTLE_AWARD_WON'] = 'gevechten gewonnen';
$lang['GENERAL_BOUNTY_AWARD_WON'] = 'premie uitgedeeld';
$lang['GENERAL_REBEL_AWARD_WON'] = 'rebellie gestart';
$lang['GENERAL_UNLOCK'] = 'Ontgrendeld in nivo %s';
$lang['GENERAL_NEW_FEATURES'] = 'De volgende onderdelen zijn ontgrendeld:';
$lang['GENERAL_RECEIVED_AWARD'] = 'Ontvangen onderscheiding:';

$lang['GENERAL_ATTACK'] = 'aanval';
$lang['GENERAL_DEFENSE'] = 'verdediging';
$lang['GENERAL_INCOME'] = 'inkomen';
$lang['GENERAL_ENERGY'] = 'energie';
$lang['GENERAL_EXPERIENCE']  = 'ervaringspunten';
$lang['GENERAL_DOLLAR'] = 'dollar';
$lang['GENERAL_ALLIANCE_SIZE'] = 'alliantie grootte';
$lang['GENERAL_EXPERIENCE_POINTS'] = 'ervaringspunten';
$lang['GENERAL_UPKEEP'] = 'Uur prijs';
$lang['GENERAL_BANK']  = 'bank';
$lang['GENERAL_DEPLOYED']  = 'actief';

$lang['GENERAL_PLAYER']  = 'Speler';
$lang['GENERAL_LEVEL'] = 'Nivo';
$lang['GENERAL_ALLIANCE']  = 'Alliantie';
$lang['GENERAL_WON'] = 'Gewonnen';
$lang['GENERAL_LOST']  = 'Verloren';
$lang['GENERAL_AMOUNT'] = 'Aantal';
$lang['GENERAL_DATE'] = 'Datum';
$lang['GENERAL_TRANSACTION'] = 'Transactie';
$lang['GENERAL_BALANCE'] = 'Saldo';
$lang['GENERAL_APPROVED'] = 'Akkoord';
$lang['GENERAL_EMAIL'] = 'Email';
$lang['GENERAL_TOP'] = 'Top';
$lang['GENERAL_EXP'] = 'Ervaring';
$lang['GENERAL_COUNTRY'] = 'Land';
$lang['GENERAL_PLAYERS'] = 'Spelers';
$lang['GENERAL_WONS']  = 'Gewonnen';
$lang['GENERAL_LOSTS'] = 'Verloren';
$lang['GENERAL_NO'] = 'Nee';
$lang['GENERAL_YES'] = 'Ja';
$lang['GENERAL_AGO'] = 'Geleden';
$lang['GENERAL_MESSAGE'] = 'Bericht';
$lang['GENERAL_ACTION']  = 'Actie';
$lang['GENERAL_NUMBER'] = 'Nr.';
$lang['GENERAL_DISCOUNT'] = 'Gebouw korting';
$lang['GENERAL_REQUESTS'] = 'Verzoeken';
$lang['GENERAL_EP'] = 'Vaardigheidpunt';
$lang['GENERAL_AWARD'] = 'Onderscheiding';
$lang['GENERAL_LANGUAGE'] = 'Taal';
$lang['GENERAL_RANKING'] = 'Lijst';

$lang['GENERAL_NEW_UNIT'] = 'NIEUWE EENHEID';
$lang['GENERAL_NEW_BUILDING']	= 'NIEUW GEBOUW';
$lang['GENERAL_NEW_MISSION'] = 'NIEUWE MISSIE';
$lang['GENERAL_GAIN'] = 'win';

$lang['GENERAL_BOUNTY'] = 'Premie';
$lang['GENERAL_INTELLIGENCE'] = 'intelligentie';
$lang['GENERAL_SPIES'] = 'spionen';
$lang['GENERAL_MAINTENANCE'] = 'Onderhoud';

$lang['GENERAL_CNTRY'] = 'Land';
$lang['GENERAL_TOPICS'] = 'onderwerpen'; 
$lang['GENERAL_FORUM'] = 'Forum';
$lang['GENERAL_MESSAGES'] = 'berichten';
$lang['GENERAL_LAST_MESSAGE'] = 'Laatste bericht';
$lang['GENERAL_FORUM_MODERATED'] = '(Beheerder is %s)';
$lang['GENERAL_NOT_MODERATED'] = '(Geen Beheerder)';
$lang['GENERAL_BY'] = 'geleden';
$lang['GENERAL_TOPIC'] = 'Onderwerp';
$lang['GENERAL_LOCKED'] = 'Geblokkeerd';
$lang['GENERAL_WORLDMAP'] = 'Wereldkaart';
$lang['GENERAL_PLAATSOFT'] = 'PlaatSoft';
$lang['GENERAL_CONQUER'] = 'Overwin';

$lang['GENERAL_ST'] = '%sste';
$lang['GENERAL_ND'] = '%sde';
$lang['GENERAL_TH'] = '%sde';

$lang['GENERAL_IDLE'] = 'Rust';
$lang['GENERAL_ACTIVE'] = 'Actief';
$lang['GENERAL_INACTIVE'] = 'Inactief';

$lang['GENERAL_PLANET'] = 'Planet';
$lang['GENERAL_PLANET_0'] = 'Aarde';
$lang['GENERAL_PLANET_1'] = 'Maan';
$lang['GENERAL_PLANET_2'] = 'Mars';
$lang['GENERAL_PLANET_3'] = 'Asteroid';
$lang['GENERAL_PLANET_4'] = 'Zon';

/*
** ------------------
** TIP
** ------------------
*/

$lang['TIP_GENERAL']  = 'TIP';
$lang['TIP_0'] = 'Play the training mission to collect experience points and reach the next level.';
$lang['TIP_1'] = 'Buy some units and start battle training to collect experience points.';
$lang['TIP_2'] = 'Trade in received skill points (Home -> Skills) to improve your soldier skills.';
$lang['TIP_3'] = 'Enter your email address to receive message and alliance notifications!';
$lang['TIP_4'] = 'Buy some income buildings to generate hourly income.';
$lang['TIP_5'] = 'Buy some defense buildings to improve your defense strength.';
$lang['TIP_6'] = 'Make alliance with ohter players to improve your attack/defense strenght.';
$lang['TIP_7'] = 'Store cash money on the National bank to keep it safe for other players.';
$lang['TIP_8'] = 'Collect extra experience points by voting on the available polls!';
$lang['TIP_9'] = 'Set bounty on other players to collect bounty awards.';
$lang['TIP_10'] = 'Visit the casino to try out the Wheel of Fortune and win more cash.';
$lang['TIP_11'] = 'Buy energy buildings for faster energy restore.';
$lang['TIP_12'] = 'Buy exspionage units to spy other players and start rebellion on there side.';
$lang['TIP_13'] = 'Store cash money on the Trasquera bank to receive daily interest.';
$lang['TIP_14'] = 'Visit the forum. New game ideas are welcome!';
$lang['TIP_15'] = 'Check out the Help section for more information.';
$lang['TIP_16'] = 'Buy/Sell stocks to make more profit (Money -> StockExchange)';
$lang['TIP_17'] = 'Store cash money on the SwissCore bank to receive daily interest.';
$lang['TIP_18'] = 'Complete all continent missions to receive extra bonus skill points.';
$lang['TIP_19'] = 'Repair units (Home -> Restore) to prevent unit loss';
$lang['TIP_20'] = 'Visit the casino to try out the Slot Machine and win more cash.';
$lang['TIP_21'] = 'Repair buildings (Home -> Restore) to prevent building loss';
$lang['TIP_22'] = 'Continue with the game and become the best player of your country!';

$lang['TIP_90'] = 'Only 10 levels away from starting your own moon colony.';
$lang['TIP_91'] = 'Only 9 levels away from starting your own moon colony.';
$lang['TIP_92'] = 'Only 8 levels away from starting your own moon colony.';
$lang['TIP_93'] = 'Only 7 levels away from starting your own moon colony.';
$lang['TIP_94'] = 'Only 6 levels away from starting your own moon colony.';
$lang['TIP_95'] = 'Only 5 levels away from starting your own moon colony.';
$lang['TIP_96'] = 'Only 4 levels away from starting your own moon colony.';
$lang['TIP_97'] = 'Only 3 levels away from starting your own moon colony.';
$lang['TIP_98'] = 'Only 2 levels away from starting your own moon colony.';
$lang['TIP_99'] = 'Only 1 level away from starting your own moon colony.';
$lang['TIP_100'] = 'Start your own moon colony!';

$lang['TIP_141'] = 'Only 10 levels away from starting your own mars colony.';
$lang['TIP_142'] = 'Only 9 levels away from starting your own mars colony.';
$lang['TIP_143'] = 'Only 8 levels away from starting your own mars colony.';
$lang['TIP_144'] = 'Only 7 levels away from starting your own mars colony.';
$lang['TIP_144'] = 'Only 6 levels away from starting your own mars colony.';
$lang['TIP_145'] = 'Only 5 levels away from starting your own mars colony.';
$lang['TIP_146'] = 'Only 4 levels away from starting your own mars colony.';
$lang['TIP_147'] = 'Only 3 levels away from starting your own mars colony.';
$lang['TIP_148'] = 'Only 2 levels away from starting your own mars colony.';
$lang['TIP_149'] = 'Only 1 level away from starting your own mars colony.';
$lang['TIP_150'] = 'Start your own mars colony!';

$lang['TIP_190'] = 'Only 10 levels away from starting your own asteroid colony.';
$lang['TIP_191'] = 'Only 9 levels away from starting your own asteroid colony.';
$lang['TIP_192'] = 'Only 8 levels away from starting your own asteroid colony.';
$lang['TIP_193'] = 'Only 7 levels away from starting your own asteroid colony.';
$lang['TIP_194'] = 'Only 6 levels away from starting your own asteroid colony.';
$lang['TIP_195'] = 'Only 5 levels away from starting your own asteroid colony.';
$lang['TIP_196'] = 'Only 4 levels away from starting your own asteroid colony.';
$lang['TIP_197'] = 'Only 3 levels away from starting your own asteroid colony.';
$lang['TIP_198'] = 'Only 2 levels away from starting your own asteroid colony.';
$lang['TIP_199'] = 'Only 1 level away from starting your own asteroid colony.';
$lang['TIP_200'] = 'Start your own asteroid colony!';

/*
** ------------------
** LOGIN PAGE
** ------------------
*/

$lang['LOGIN_MEMBER_TITLE'] = 'Inloggen';
$lang['LOGIN_REGISTER_TITLE'] = 'Registratie';
$lang['LOGIN_RECOVER_TITLE'] = 'Wachtwoord herstellen';
$lang['LOGIN_MANUAL_TITLE'] = 'Handmatig';

$lang['LOGIN_PLAYERS'] = 'spelers';
$lang['LOGIN_REQUESTS'] = 'verzoeken';
$lang['LOGIN_COUNTRIES'] = 'landen';
$lang['LOGIN_ONLINE'] = 'spelers online';

$lang['LOGIN_PASSWORD'] = 'Wachtwoord';
$lang['LOGIN_USERNAME'] = 'Gebruikersnaam';
$lang['LOGIN_EMAIL'] = 'Email';
$lang['LOGIN_NICKNAME']  = 'Alias';

$lang['LOGIN_MAINTENANCE_TITLE'] = 'Server Onderhoud';
$lang['LOGIN_MAINTENANCE'] = 'Op dit moment vindt er onderhoud plaats. Probeer het over 5 minuten nog eens.';

$lang['LOGIN_LOGOUT'] = 'Je bent nu afgemeld!'; 
$lang['LOGIN_FAILED'] = 'Ongeldige Gebruikersnaam en/of Wachtwoord!';
$lang['LOGIN_BANN'] = 'Dit account is geblokkeerd vanwege vals spelen!';
$lang['LOGIN_REGISTER_OK'] = 'Gebruikers account %s is aangemaakt!';
$lang['LOGIN_PASSWORD_TO_SHORT'] = 'Wachtwoord dient minimaal 4 tekens lang te zijn!';
$lang['LOGIN_USERNAME_TO_SHORT'] = 'Gebruikersnaam dient minimaal 4 tekens lang te zijn!';
$lang['LOGIN_USERNAME_EXIST'] = 'Gebruikersnaam %s bestaat reeds!';
$lang['LOGIN_EMAIL_EXIST'] = 'Email adres is reeds geregisteerd!';
$lang['LOGIN_EMAIL_INVALID'] = 'Email adres is ongeldig! (Verkeerd formaat)';
$lang['LOGIN_NICKNAME_EXIST'] = 'Alias %s reeds in gebruik!';
$lang['LOGIN_NICKNAME_NEEDED'] = 'Alias moet worden ingevoerd!';
$lang['LOGIN_NEW_PASSWORD_SEND'] = 'Nieuw wachtwoord is verstuurd per email!';
$lang['LOGIN_EMAIL_UNKNOWN'] = 'Email adres is onbekend!';
$lang['LOGIN_BEST_VIEWED'] = 'WarQuest is geoptimaliseerd voor de volgende mobiele hardware: "Apple iPhone / iPad / iPod, Nokia, 
BlackBerry, Android" en internet browsers: "Microsoft Internet Explorer, Mozilla Firefox, Apple Safari, Opera, Google Chrome". 
De weergave van dit spel is optimaal bij 500 pixels browser venster breedte';

$lang['LOGIN_NEW_CLIENT_TITLE'] = 'Nieuwe WarQuest client beschikbaar!';
$lang['LOGIN_NEW_CLIENT'] = 'Op dit moment gebruik je een oude WarQuest Windows client.<br/>Bezoek www.plaatsoft.nl om de nieuwste versie te downloaden.';

$lang['LOGIN_PASSWORD_RESET_NOTE'] = 'If you have forgotten your password, enter your email address and we\'ll send you a new password by email.';

/*
** ------------------
** HOME - OVERVIEW
** ------------------
*/

$lang['HOME_TITLE'] = 'START';

$lang['HOME_FLASH_NEWS_TITLE'] = 'Laatste Nieuws';

$lang['HOME_LASTEST_FORUM_ITEM'] = 'Laatste forum bericht';

$lang['HOME_INTRO_PLAYERS'] = 'Op dit moment zijn er %s spelers uit %s landen actief, ';
$lang['HOME_INTRO_FIGHTS'] = '%s gevechten hebben plaats gevonden en ';
$lang['HOME_INTRO_REQUESTS'] = '%s server verzoeken zijn afgehandeld. ';

$lang['HOME_INTRO_TITLE'] = 'Introductie';
$lang['HOME_INTRO_MISSIONS'] = 'Start het spel door %s te spelen. Hierdoor worden automatisch eenheden aangekocht. ';
$lang['HOME_INTRO_BATTLES'] = 'Met deze eenheden kan je gaan %s tegen andere spelers. ';
$lang['HOME_INTRO_UNITS'] = 'Met het gewonnen geld kan je betere %s ';
$lang['HOME_INTRO_BUILDINGS'] = ' en %s kopen zodat je aanval sterkte verhoogt wordt. ';
$lang['HOME_INTRO_ENEMY'] = 'Op ieder moment kunnen andere spelers je aanvallen dus houd ook je verdedigings sterkte op niveau.';

$lang['HOME_NEW_ANDROID_VERSION'] = 'Nieuwe app versie v%s is beschikbaar op de Android Market!';
$lang['HOME_NEW_WINDOWS_VERSION'] = 'Nieuwe WarQuest client v%s is beschikbaar!';
$lang['HOME_CLICK_HERE'] = 'hier';
$lang['HOME_CLICK_TEXT'] = 'Klik %s om de download te starten.';

$lang['HOME_EMAIL_MISSING'] = 'Je email adres ontbreekt!';
$lang['HOME_DAILY_BONUS'] = 'Je hebt %s dollar gevonden op een vijandelijke locatie!';

$lang['HOME_WELCOME'] = 'Welkom';
$lang['HOME_LAST_LOGIN'] = 'Laatste bezoek was <b>%s</b> geleden.';
$lang['HOME_AWARDS'] = 'Ontvangen Onderscheidingen:';
$lang['HOME_MAP_TITLE'] = 'Continenten';
$lang['HOME_MAP_NOTE'] = 'Door het spelen van missies kun je alle continenten veroveren.';

$lang['HOME_TRAVEL_TO'] = 'Reis naar';

$lang['HOME_OVERVIEW_TITLE'] = 'Overzicht';

$lang['HOME_INTRO_PLACE1'] = 'Je staat op de <b>%s</b> plaats van alle spelers '; 
$lang['HOME_INTRO_PLACE2'] = 'en op de <b>%s</b> plaats van <b>%s</b>.'; 
$lang['HOME_PLAYERS_ONLINE'] = '%s speler zijn de laatste 24 uur actie geweest.';

/*
** ------------------
** HOME - PROFILE
** ------------------
*/

$lang['PLAYER_TITLE'] = 'SPELER';
$lang['PLAYER_WIN_LOST_RATE'] = 'Win/Verlies ratio';
$lang['PLAYER_BUILDINGS'] = 'Gebouwen';
$lang['PLAYER_CASH_FLOW'] = 'Geldstroom';
$lang['PLAYER_ALLIANCE_SIZE'] = 'Alliantie grootte';
$lang['PLAYER_EXP_POINTS']  = 'Ervaringspunten';
$lang['PLAYER_SERVER_REQUEST']  = 'Server verzoeken';
$lang['PLAYER_MISSION_COMPLETED'] = 'Missies uitgevoerd';
$lang['PLAYER_DEFENSE_STRENGTH']  = 'Verdediging';
$lang['PLAYER_ATTACK_STRENGTH'] = 'Aanval';
$lang['PLAYER_FIGHTS_LOST'] = 'Gevechten verloren';
$lang['PLAYER_FIGHTS_WON']  = 'Gevechten gewonnen';
$lang['PLAYER_BUILDING_INCOME'] = 'Vastgoed inkomen';
$lang['PLAYER_BOUNTY_SET'] = 'Premie uitgedeeld';

$lang['PLAYER_UPKEEP']  = 'Uur prijs';
$lang['PLAYER_NETTO_INCOME']  = 'Netto inkomen';
$lang['PLAYER_STATISTICS']  = 'Statistieken'; 
$lang['PLAYER_NAME']  = 'Naam'; 
$lang['PLAYER_ID']  = 'Id';
$lang['PLAYER_DISCOUNT_RATE'] = 'Gebouw korting';
$lang['PLAYER_MAINTENANCE_RATE'] = 'Eenheden onderhoud';
$lang['PLAYER_LAST_LOGIN'] = 'Laatst actief';
$lang['PLAYER_CREATED'] = 'Eerste inlog';
$lang['PLAYER_CASINO_PLAYED']  = 'Casino gespeeld';
$lang['PLAYER_ADS_SHOWED']  = 'Advertenties getoond';

$lang['PLAYER_RANK']  = 'Rang'; 
$lang['PLAYER_OVERVIEW']  = 'Profiel'; 
$lang['PLAYER_FORCE'] = 'Aanvals- & verdedigingskracht';

$lang['PLAYER_ATTACK_FORCE'] = 'Overzicht (%s Aanvals %s)';
$lang['PLAYER_DEFENSE_FORCE'] = 'Overzicht (%s Verdedigings %s)';
$lang['PLAYER_ATTACK_TEXT'] = '%s heeft momenteel <b>%s</b> allianties en kan maximaal <b>%s</b> eenheden aansturen. Je aanvals %s bevat de volgende eenheden:';
$lang['PLAYER_DEFENSE_TEXT'] = '%s heeft momenteel <b>%s</b> allianties en kan maximaal <b>%s</b> eenheden aansturen. Je verdedigings %s bevat de volgende eenheden:';
$lang['PLAYER_UNIT'] = 'Eenheid/Gebouw';
$lang['PLAYER_AMOUNT'] = 'Aantal';
$lang['PLAYER_STRENGTH'] = 'Kracht';
$lang['PLAYER_ATTACK_SKILLS'] = 'Aanvalsvaardigheden';
$lang['PLAYER_DEFENSE_SKILLS'] = 'Verdedigingsvaardigheden';
$lang['PLAYER_SUB_TOTAL'] = 'Sub totaal';
$lang['PLAYER_TOTAL'] = 'Totaal';
$lang['PLAYER_DEPLOYED'] = 'Actief';

$lang['PLAYER_BUILDING'] = 'Gebouwen';
$lang['PLAYER_INCOME'] = 'Inkomen';
$lang['PLAYER_COST'] = 'Uitgaven';
$lang['PLAYER_BUILDING_OVERVIEW'] = 'Overzicht (Vastgoed inkomen)';
$lang['PLAYER_BUILDING_TEXT'] = '%s heeft momenteel de volgende %s inkomen gebouwen:';
$lang['PLAYER_UPKEEP_COST'] = 'Overzicht (Uur kosten)';
$lang['PLAYER_UPKEEP_TEXT'] = '%s bezit op dit moment de volgende %s eenheden:';
$lang['PLAYER_CONTINENT_OVERVIEW'] = 'Continent inkomen overzicht';
$lang['PLAYER_CONTINENT_TEXT'] = '%s heeft de volgende %s continent(en) verroverd:';

$lang['PLAYER_SPY_1'] = 'spionage';
$lang['PLAYER_SPY_2'] = 'explorers';
$lang['PLAYER_ESPIONAGE_UNLOCK1'] = 'Ontgrendeld als jouw %s sterkte %s% hoger is tegenstander.';
$lang['PLAYER_ESPIONAGE_UNLOCK2'] = 'Ontgrendeld als jouw %s sterkte gelijk of hoger is tegenstander.';

$lang['PLAYER_MONEY_STATUS'] = 'Huidige vermogen';
$lang['PLAYER_CASH_MONEY'] = 'Contant';
$lang['PLAYER_BANK'] = 'Bank';

$lang['PLAYER_PLATFORM_BROWSER'] = 'Platform & Browser';
$lang['PLAYER_BROWSER'] = 'Browser';
$lang['PLAYER_BROWSER_VERSION'] = 'Versie';
$lang['PLAYER_PLATFORM'] = 'Platform';

/*
** ------------------
** HOME - NEWS
** ------------------
*/

$lang['HOME_BATTLE_TITLE'] = 'Nieuws';
$lang['HOME_BATTLE_ATTACK_BY'] = 'Je werd aangevallen door de %s van %s. ';
$lang['HOME_BATTLE_YOU_WON'] = 'Je <b>won</b>! ';
$lang['HOME_BATTLE_YOU_LOST'] = 'Je <b>verloor</b>! ';
$lang['HOME_BATTLE_YOU_EXP'] = 'Je ervaring steeg met %s  ';
$lang['HOME_BATTLE_TOOK_DAMAGE'] = 'en liep %s schade op.';
$lang['HOME_BATTLE_TAKING_DAMAGE'] = 'en liep %s schade op.';
$lang['HOME_BATTLE_YOU_MONEY'] = 'Je verloor %s dollar ';
$lang['HOME_BATTLE_NO_NEWS'] = 'Geen nieuws beschikbaar op dit moment!';

$lang['HOME_BOUNTY_NEWS'] = '%s heeft %s dollar op jouw hoofd gezet. Als je verslagen wordt verlies je %s ervaringspunten.';

/*
** ------------------
** HOME - MESSAGE
** ------------------
*/

$lang['HOME_MESSAGES_TITLE']= 'Berichten';
$lang['HOME_MESSAGE_DELETED'] = 'Bericht verwijderd!';
$lang['HOME_NO_MESSAGES'] = 'Geen berichten beschikbaar op dit moment!'; 

/*
** ------------------
** HOME - SKILLS
** ------------------
*/

$lang['PLAYER_SKILL_SUBTITLE1']  = 'Vaardigheden';
$lang['PLAYER_SKILL_SUBTITLE2']  = 'Vaardigheden [%s beschikbaar]';
$lang['PLAYER_SKILL_NOTE']  = 'Opmerking: Gebruik vaardigheidspunten om Aanval, Verdediging, Gezondheid, Energie en/of Munitie vaardigheden te vergroten.';
$lang['PLAYER_SKILLS']  = 'Vaardigheden'; 
$lang['PLAYER_MAX'] = 'Huidig'; 
$lang['PLAYER_ATTACK']  = 'AANVAL';
$lang['PLAYER_DEFENSE'] = 'VERDEDIGING';
$lang['PLAYER_HEALTH']  = 'GEZONDHEID'; 
$lang['PLAYER_ENERGY']  = 'ENERGIE'; 
$lang['PLAYER_AMMO']  = 'MUNITIE'; 
$lang['PLAYER_ATTACK_TIP']  = 'Verhoog je aanvalskracht zodat je vaker wint tijdens een gevecht. Kost 1 ervaringspunt om je aanvalskracht met %s te verhogen. Verlaag je aanvalskracht met %s om 1 ervaringspunt beschikbaar te krijgen.';
$lang['PLAYER_DEFENSE_TIP'] = 'Verhoog je verdedingskracht zodat je aanvallen beter kunt afslaan. Kost 1 ervaringspunt om je verdedigingsskracht met %s te verhogen. Verlaag je verdedingskracht met %s om 1 ervaringspunt beschikbaar te krijgen.';
$lang['PLAYER_HEALTH_TIP']  = 'Verhoog je gezondheid zodat je langer kunt vechten. Kost 1 ervaringspunt om je gezondheid met 10 te verhogen. Verlaag je gezondheid met 20 om 1 ervaringspunt beschikbaar te krijgen.';
$lang['PLAYER_ENERGY_TIP']  = 'Verhoog je energie zodat je meer missies kan spelen. Kost 1 ervaringspunt om je energie met 10 te verhogen. Verlaag je energie met 20 om 1 ervaringspunt beschikbaar te krijgen.';
$lang['PLAYER_AMMO_TIP']  = 'Verhoog je munitie zodat je langer kan aanvallen. Kost 2 ervaringspunten om je munitie met 1 te verhogen. Verlaag je munitie met 1 om 1 ervaringspunt beschikbaar te krijgen.';
$lang['PLAYER_SKILL_ACCEPTED1']  = '%s vaardigheid verhoogd.';
$lang['PLAYER_SKILL_REJECTED1']  = 'Je hebt geen %s vaardigheidspunt(en) beschikbaar.';
$lang['PLAYER_SKILL_ACCEPTED2']  = '%s vaardigheid verlaagd.';
$lang['PLAYER_SKILL_REJECTED2']  = 'Vaardigheid %s heeft laagste punt bereikt.';


/*
** ------------------
** HOME - RESTORE
** ------------------
*/

$lang['PLAYER_RESTORE_TITLE'] = 'Herstel & Reparatie';
$lang['PLAYER_RESTORE_SUBTITLE1'] = 'Herstel';
$lang['PLAYER_RESTORE_SUBTITLE2'] = 'Reparatie';
$lang['PLAYER_RESTORE_UNLOCKED'] = 'Herstel & Reparatie is ontgrendeld in nivo %s.';
$lang['PLAYER_RESTORE_PRICE'] = 'Herstel prijs';
$lang['PLAYER_REPAIR_PRICE'] = 'Repareer prijs';
$lang['PLAYER_RESTORED_FAILED'] = 'Je bezit geen %s dollar om deze actie uit te voeren!';

$lang['PLAYER_HEALTH_TITLE'] = 'Herstel gezondheid';
$lang['PLAYER_HEALTH_NOTE'] = 'Betaal het ziekenhuis om je gezondheid meteen te herstellen. Herstel kan maar een keer per 10 minuten gebruikt worden. Gezondheid hersteld ook automatisch.';		
$lang['PLAYER_HEALTH_CONDITION'] = 'Gezondheid conditie';
$lang['PLAYER_HEALTH_RESTORED'] = 'Gezondheid is hersteld voor %s dollar.';
$lang['PLAYER_HEALTH_CONFIRM'] = 'Wil je echt je gezondheid herstellen?';

$lang['PLAYER_ENERGY_TITLE'] = 'Herstel energie';
$lang['PLAYER_ENERGY_NOTE'] = 'Betaal de oliemaatschappij om je energie meteen te herstellen. Herstel kan maar een keer per 24 uur gebruikt worden. Energie hersteld ook automatisch.';	
$lang['PLAYER_ENERGY_CONDITION'] = 'Energie conditie';
$lang['PLAYER_ENERGY_RESTORED'] = 'Energie is hersteld voor %s dollar.';
$lang['PLAYER_ENERGY_CONFIRM'] = 'Wil je echt je energie herstellen?';

$lang['PLAYER_AMMO_TITLE'] = 'Herstel munitie';
$lang['PLAYER_AMMO_NOTE'] = 'Betaal de wapenleverancier om je munitie meteen te herstellen. Herstel kan maar een keer per 24 uur gebruikt worden. Munitie hersteld ook automatisch.';	
$lang['PLAYER_AMMO_CONDITION'] = 'Munitie conditie';
$lang['PLAYER_AMMO_RESTORED'] = 'Munitie is hersteld voor %s dollar.';
$lang['PLAYER_AMMO_CONFIRM'] = 'Wil je echt je munitie herstellen?';

$lang['PLAYER_CEASE_FIRE_TITLE'] = 'Wapenstilstand';
$lang['PLAYER_CEASE_FIRE_NOTE'] = 'Herstel door een wapenstilstand te activeren. Tijdens de wapenstilstand kan niemand je aanvallen, maar jij kan ook niemand aanvallen.';	
$lang['PLAYER_CEASE_FIRE_ACTIVATED'] = 'Wapenstilstand geactiveerd voor %s dollar.';
$lang['PLAYER_CEASE_FIRE_CONFIRM'] = 'Wil je echt een wapenstilstand periode activeren?';

$lang['PLAYER_UNITS_TITLE'] = 'Repareer eenheden';
$lang['PLAYER_UNITS_NOTE'] = 'Repareer je eenheden van je leger. Als eenheden conditie 0% wordt verlies je een aantal eenheden en de overige eenheden worden automatisch gerepareerd.';	
$lang['PLAYER_UNITS_CONDITION'] = 'Eenheden conditie';
$lang['PLAYER_UNITS_REPAIRED'] = 'Je eenheden zijn gerepareert voor %s dollar.';
$lang['PLAYER_UNITS_CONFIRM'] = 'Wil je echt je eenheden repareren?';

$lang['PLAYER_BUILDINGS_TITLE'] = 'Repareer gebouwen';
$lang['PLAYER_BUILDINGS_NOTE'] = 'Repareer je gebouwen van je basis. Als de conditie 0% wordt verlies je een aantal gebouwen en de overige gebouwen worden automatisch gerepareerd.';	
$lang['PLAYER_BUILDINGS_CONDITION'] = 'Gebouwen conditie';
$lang['PLAYER_BUILDINGS_REPAIRED'] = 'Je gebouwen zijn gerepareert voor %s dollar.';
$lang['PLAYER_BUILDINGS_CONFIRM'] = 'Wil je echt je gebouwen repareren?';

/*
** ------------------
** HOME - SETTINGS
** ------------------
*/

$lang['SETTING_TITLE'] = 'Instellingen';
$lang['SETTING_GENERAL1'] = 'Algemene instellingen 1';
$lang['SETTING_GENERAL2'] = 'Algemene instellingen 2';

$lang['SETTING_NICKNAME'] = 'Naam';
$lang['SETTING_LANGUAGE'] = 'Taal';
$lang['SETTING_BACKGROUND'] = "Achtergrond";
$lang['SETTING_SOUND'] = 'Geluid aanzetten (Experiment)';
$lang['SETTING_BOUNTY'] = 'Activeer premie bevestigingspopup';
$lang['SETTING_RESTORE'] = 'Activeer herstel / repareer bevestigingspopup';
$lang['SETTING_CONDITION'] = 'Activeer eenheden/gebouwen conditie informatie in header';
$lang['SETTING_FORUM_SORT'] = 'Activeer laatste forum post op home pagina';
$lang['SETTING_SORT1'] = 'Activeer laatste forum bericht on thuis scherm.';
$lang['SETTING_SORT2'] = ' Enable oldest battle player on top at battle list.';
$lang['SETTING_NO_BOT_NEWS'] = 'Deactiveer robot vecht nieuws.';

$lang['PLAYER_LANG_ENGLISH'] = 'Engels';
$lang['PLAYER_LANG_DUTCH'] = 'Nederlands';
$lang['PLAYER_LANG_GERMAN'] = 'Duits';

$lang['PLAYER_GENERAL_CHANGED'] = 'Algemene instellingen aangepast!';
$lang['NICKNAME_EXIST'] = 'Naam bestaat al!';
$lang['NICKNAME_TO_SHORT'] = 'Naam moet minmaal 4 karakters lang zijn!';
$lang['NICKNAME_NO_SPACE'] = 'Er mogen geen spatie in de naam voorkomen!';

$lang['PLAYER_CHANGE_EMAIL'] = 'Email instellingen';
$lang['PLAYER_NEW_EMAIL'] = 'Email adres';
$lang['PLAYER_NOTIFICATION_ALLIANCE'] = 'Alliantie notificatie per email';
$lang['PLAYER_NOTIFICATION_COMMENT'] = 'Bericht notificatie per email';
$lang['PLAYER_EMAIL_CHANGED'] = 'Email instellingen zijn aangepast';
$lang['PLAYER_EMAIL_EXIST'] = 'Email adres is al ingebruik bij andere speler!';
$lang['PLAYER_EMAIL_INVALID'] = 'Email adres is niet correct!';

$lang['PLAYER_LOGIN_SETTINGS'] = 'Login Instellingen';
$lang['PLAYER_USERNAME'] = 'Gebruikersnaam';
$lang['PLAYER_USERNAME_TO_SHORT'] = 'Gebruikersnaam moet minimaal 4 karakters lang zijn!';
$lang['PLAYER_USERNAME_ALREADY_EXIST'] = 'Gebruikersnaam bestaat al!';
$lang['PLAYER_USERNAME_CHANGED'] = 'Gebruikersnaam aangepast.';
$lang['PLAYER_CURRENT_PASSWORD'] = 'Huidige wachtwoord';		
$lang['PLAYER_NEW_PASSWORD'] = 'Nieuw wachtwoord';
$lang['PLAYER_PASSWORD_CHANGED'] = 'Wachtwoord aangepast!';
$lang['PLAYER_PASSWORD_NO_MATCH'] = 'Huidige wachtwoord komt niet overeen!';
$lang['PLAYER_PASSWORD_TO_SHORT'] = 'Het nieuwe wachtwoord moet minimaal 6 karakters lang zijn!';
$lang['PLAYER_LOGIN_NOTE'] = 'BELANGRIJK: Automatische inlog werkt alleen als de zelfde gebruikersnaam en wachtwoord wordt ingesteld in de WarQuest Android en/of Windows client!'; 

$lang['BACKGROUND_0'] = 'Zwart';
$lang['BACKGROUND_1'] = 'Legergroen';
$lang['BACKGROUND_2'] = 'Rode aurora';
$lang['BACKGROUND_3'] = 'Grijze stenen';
$lang['BACKGROUND_4'] = 'Paarse cirkels';
$lang['BACKGROUND_5'] = 'Zijde blauw';
$lang['BACKGROUND_6'] = 'Bruin';
$lang['BACKGROUND_7'] = 'Piraat';
$lang['BACKGROUND_8'] = 'Modern';
$lang['BACKGROUND_9'] = 'Klassiek';
$lang['BACKGROUND_10'] = 'Chocolade';
$lang['BACKGROUND_11'] = 'Kerst';
$lang['BACKGROUND_12'] = 'Vuurwerk';

/*
** ------------------
** MISSION DATA
** ------------------
*/

/* Earth */
$lang['MISSION_GROUP_0'] = 'Training';
$lang['MISSION_GROUP_1'] = 'Europa';
$lang['MISSION_GROUP_2'] = 'N-Amerika';
$lang['MISSION_GROUP_3'] = 'S-Amerika';
$lang['MISSION_GROUP_4'] = 'Afrika';
$lang['MISSION_GROUP_5'] = 'N-Azia';
$lang['MISSION_GROUP_6'] = 'S-Azia';
$lang['MISSION_GROUP_7'] = 'E-Azia';
$lang['MISSION_GROUP_8'] = 'Oceania';
$lang['MISSION_GROUP_9'] = 'M-Oosten';

/* Moon */
$lang['MISSION_GROUP_10'] = 'Alpha ';
$lang['MISSION_GROUP_11'] = 'Beta';
$lang['MISSION_GROUP_12'] = 'Charlie';
$lang['MISSION_GROUP_13'] = 'Delta';
$lang['MISSION_GROUP_14'] = 'Echo';
$lang['MISSION_GROUP_15'] = 'Foxtrot';
$lang['MISSION_GROUP_16'] = 'Golf';
$lang['MISSION_GROUP_17'] = 'Hotel';
$lang['MISSION_GROUP_18'] = 'Lima';

/* Mars */
$lang['MISSION_GROUP_20'] = 'Alpaca';
$lang['MISSION_GROUP_21'] = 'Bison';
$lang['MISSION_GROUP_22'] = 'Coyote';
$lang['MISSION_GROUP_23'] = 'Dinosaur';
$lang['MISSION_GROUP_24'] = 'Emu';
$lang['MISSION_GROUP_25'] = 'Fox';
$lang['MISSION_GROUP_26'] = 'Gnu';
$lang['MISSION_GROUP_27'] = 'Heron';
$lang['MISSION_GROUP_28'] = 'Lion';

/* ---------------------------------------------- */

/* Earth */
$lang['MISSION_0'] = 'Training missie';
$lang['MISSION_1'] = 'Engeland regio';
$lang['MISSION_2'] = 'Benelux';
$lang['MISSION_3'] = 'Frankrijk regio';
$lang['MISSION_4'] = 'Central Europa ';
$lang['MISSION_5'] = 'Scandinavie';
$lang['MISSION_6'] = 'Oost Europa';
$lang['MISSION_7'] = 'Spanje regie';
$lang['MISSION_8'] = 'Zuid Europe';

$lang['MISSION_10'] = 'Groenland';
$lang['MISSION_11'] = 'Canada';
$lang['MISSION_12'] = 'Verenigde Staten';
$lang['MISSION_13'] = 'Mexico';
$lang['MISSION_14'] = 'Guatemala regio';
$lang['MISSION_15'] = 'Nicaragua regio';
$lang['MISSION_16'] = 'Cuba regio';
$lang['MISSION_17'] = 'Caribbean regio';

$lang['MISSION_20'] = 'Midden Amerika';
$lang['MISSION_21'] = 'Ecuador regio';
$lang['MISSION_22'] = 'Bolivia regio';
$lang['MISSION_23'] = 'Paraguay regio';
$lang['MISSION_24'] = 'Chile regio';
$lang['MISSION_25'] = 'Argentina regio';
$lang['MISSION_26'] = 'Uruguay regio';
$lang['MISSION_27'] = 'Brazil regio';

$lang['MISSION_30'] = 'Algeria regio';
$lang['MISSION_31'] = 'Egypte regio';
$lang['MISSION_32'] = 'West Afrika regio';
$lang['MISSION_33'] = 'Central Afrika regio';
$lang['MISSION_34'] = 'Oost Afrika regio';
$lang['MISSION_35'] = 'Mozambique regio';
$lang['MISSION_36'] = 'Zimbabwe regio';
$lang['MISSION_37'] = 'Zuid Afrika regio';

$lang['MISSION_40'] = 'Rusland';
$lang['MISSION_41'] = 'Mongolie regio';
$lang['MISSION_42'] = 'Kazakhstan regio';
$lang['MISSION_43'] = 'Uzbekihstan regio';
$lang['MISSION_44'] = 'Takikistan regio';
$lang['MISSION_45'] = 'Turkmenistan regio';
$lang['MISSION_46'] = 'Georgia regio';
$lang['MISSION_47'] = 'Armenia regio';

$lang['MISSION_50'] = 'Iran';
$lang['MISSION_51'] = 'Afghanistan';
$lang['MISSION_52'] = 'Pakistan';
$lang['MISSION_53'] = 'India';
$lang['MISSION_54'] = 'Nepal';
$lang['MISSION_55'] = 'Bangladesh regio';
$lang['MISSION_56'] = 'Thailand regio';
$lang['MISSION_57'] = 'Laos regio';

$lang['MISSION_60'] = 'China';
$lang['MISSION_61'] = 'Noord Korea';
$lang['MISSION_62'] = 'Zuid Korea';
$lang['MISSION_63'] = 'Japan';
$lang['MISSION_64'] = 'Taiwan';
$lang['MISSION_65'] = 'Cambodia regio';
$lang['MISSION_66'] = 'VietNam regio';
$lang['MISSION_67'] = 'Malaysia';

$lang['MISSION_70'] = 'West Indonesia';
$lang['MISSION_71'] = 'Oost Indonesia';
$lang['MISSION_72'] = 'Filippijnen regio';
$lang['MISSION_73'] = 'Papua Nieuw Guinea';
$lang['MISSION_74'] = 'Timor';
$lang['MISSION_75'] = 'Noord Australia';
$lang['MISSION_76'] = 'Zuid Australia';
$lang['MISSION_77'] = 'Nieuw Zeeland';

$lang['MISSION_80'] = 'Syri&euml';
$lang['MISSION_81'] = 'Irak';
$lang['MISSION_82'] = 'Saoedi-Arabi&euml;';
$lang['MISSION_83'] = 'Koeweit';
$lang['MISSION_84'] = 'Jemen regio';
$lang['MISSION_85'] = 'Oman regio ';
$lang['MISSION_86'] = 'Jordani&euml;';
$lang['MISSION_87'] = 'Isra&euml;l';

/* ---------------------------------------------- */

/* Moon */
$lang['MISSION_100'] = 'Crater Endymion';
$lang['MISSION_101'] = 'Crater Franklin';
$lang['MISSION_102'] = 'Sinus Honoris';
$lang['MISSION_103'] = 'Mons Fidei';
$lang['MISSION_104'] = 'Crater Blanc';
$lang['MISSION_105'] = 'Crater Fesenkov';
$lang['MISSION_106'] = 'Montes Temporis';
$lang['MISSION_107'] = 'Crater Darwin';

$lang['MISSION_110'] = 'Crater Agnes';
$lang['MISSION_111'] = 'Mons Andre';
$lang['MISSION_112'] = 'Vallis Ardeshir';
$lang['MISSION_113'] = 'Crater Aristoteles';
$lang['MISSION_114'] = 'Mare Blanc';
$lang['MISSION_115'] = 'Mons Bradley';
$lang['MISSION_116'] = 'Vallis Delisle';
$lang['MISSION_117'] = 'Sinus Dieter';

$lang['MISSION_120'] = 'Mons Dilip';
$lang['MISSION_121'] = 'Mons Esam';
$lang['MISSION_122'] = 'Crater Albategnius';
$lang['MISSION_123'] = 'Mons Gruithuisen Delta';
$lang['MISSION_124'] = 'Mare Gruithuisen Gamma';
$lang['MISSION_125'] = 'Crater Hansteen';
$lang['MISSION_126'] = 'Vallis Herodotus';
$lang['MISSION_127'] = 'Mons Huygens';

$lang['MISSION_130'] = 'Sinus La Hire';
$lang['MISSION_131'] = 'Mons Maraldi';
$lang['MISSION_132'] = 'Mons Moro';
$lang['MISSION_133'] = 'Crater Aristarchus';
$lang['MISSION_134'] = 'Mons Pico';
$lang['MISSION_135'] = 'Vallis Piton';
$lang['MISSION_136'] = 'Sinus Rumker';
$lang['MISSION_137'] = 'Mons Usov';

$lang['MISSION_140'] = 'Mons Vinogradov';
$lang['MISSION_141'] = 'Mons Vitruvius';
$lang['MISSION_142'] = 'Mons Wolff';
$lang['MISSION_143'] = 'Montes Agricola';
$lang['MISSION_144'] = 'Montes Alpes';
$lang['MISSION_145'] = 'Crater Apenninus';
$lang['MISSION_146'] = 'Montes Archimedes';
$lang['MISSION_147'] = 'Montes Carpatus';

$lang['MISSION_150'] = 'Montes Caucasus';
$lang['MISSION_151'] = 'Mare Cordillera';
$lang['MISSION_152'] = 'Montes Haemus';
$lang['MISSION_153'] = 'Crater Harbinger';
$lang['MISSION_154'] = 'Sinus Pyrenaeus';
$lang['MISSION_155'] = 'Montes Riphaeus';
$lang['MISSION_156'] = 'Montes Rook';
$lang['MISSION_157'] = 'Mare Secchi';

$lang['MISSION_160'] = 'Montes Spitzbergen';
$lang['MISSION_161'] = 'Mare Taurus';
$lang['MISSION_162'] = 'Sinus Teneriffe';
$lang['MISSION_163'] = 'Montes Harbinger';
$lang['MISSION_164'] = 'Vallis Rheita';
$lang['MISSION_165'] = 'Vallis Baade';
$lang['MISSION_166'] = 'Crater Bohr';
$lang['MISSION_167'] = 'Vallis Palitzsch';

$lang['MISSION_170'] = 'Crater Fecunditatis';
$lang['MISSION_171'] = 'Mare Australe';
$lang['MISSION_172'] = 'Montes Orientale';
$lang['MISSION_173'] = 'Sinus Cognitum';
$lang['MISSION_174'] = 'Mare Crisium';
$lang['MISSION_175'] = 'Mons Spumans';
$lang['MISSION_176'] = 'Montes Tranquillitatis';
$lang['MISSION_177'] = 'Mare Vaporum';

$lang['MISSION_180'] = 'Crater Aestatis';
$lang['MISSION_181'] = 'Lacus Bonitatis';
$lang['MISSION_182'] = 'Montes Felicitatis';
$lang['MISSION_183'] = 'Sinus Luxuriae';
$lang['MISSION_184'] = 'Lacus Oblivionis';
$lang['MISSION_185'] = 'Mons Solitudinis';
$lang['MISSION_186'] = 'Montes Temporis';
$lang['MISSION_187'] = 'Crater Timoris';

/* ---------------------------------------------- */

/* Mars */
$lang['MISSION_200'] = 'Crater Al-Qahira';
$lang['MISSION_201'] = 'Sinus Ares';
$lang['MISSION_202'] = 'Vallis Auqakuh';
$lang['MISSION_203'] = 'Crater Bahram';
$lang['MISSION_204'] = 'Mare Harmakhis';
$lang['MISSION_205'] = 'Mons Her Desher';
$lang['MISSION_206'] = 'Sinus Hrad';
$lang['MISSION_207'] = 'Vallis Huo Hsing';

$lang['MISSION_210'] = 'Mons Kasei';
$lang['MISSION_211'] = 'Mare Labou';
$lang['MISSION_212'] = 'Vallis Maadim';
$lang['MISSION_213'] = 'Crater Maja';
$lang['MISSION_214'] = 'Sinus Mamers';
$lang['MISSION_215'] = 'Vallis Mangala';
$lang['MISSION_216'] = 'Crater Marte';
$lang['MISSION_217'] = 'Mare Mawrth';

$lang['MISSION_220'] = 'Crater Nirgal';
$lang['MISSION_221'] = 'Vallis Shalbatana';
$lang['MISSION_222'] = 'Crater Simud';
$lang['MISSION_223'] = 'Sinus Tiu';
$lang['MISSION_224'] = 'Vallis Aloysius';
$lang['MISSION_225'] = 'Crater Ambrosius';
$lang['MISSION_226'] = 'Mare Barnabas';
$lang['MISSION_227'] = 'Mare Constantia';

$lang['MISSION_230'] = 'Vallis Edmondus';
$lang['MISSION_231'] = 'Mare Eustachius';
$lang['MISSION_232'] = 'Crater Georgius';
$lang['MISSION_233'] = 'Sinus Griselda';
$lang['MISSION_234'] = 'Vallis Gualterius';
$lang['MISSION_235'] = 'Crater Homfridus';
$lang['MISSION_236'] = 'Mare Henricus';
$lang['MISSION_237'] = 'Guglielmus';

$lang['MISSION_240'] = 'Mare Janetta';
$lang['MISSION_241'] = 'Vallis Jerominus';
$lang['MISSION_242'] = 'Crater Josephus';
$lang['MISSION_243'] = 'Mare Leonardus';
$lang['MISSION_244'] = 'Sinus Mauritius';
$lang['MISSION_245'] = 'Crater Nicholaus';
$lang['MISSION_246'] = 'Vallis Laurentius';
$lang['MISSION_247'] = 'Mons Octavius';

$lang['MISSION_250'] = 'Crater Misericordia';
$lang['MISSION_251'] = 'Vallis Petronella';
$lang['MISSION_252'] = 'Sinus Sylvanus';
$lang['MISSION_253'] = 'Crater Reginaldus';
$lang['MISSION_254'] = 'Vallis Adeipho';
$lang['MISSION_255'] = 'Sinus Randulphus';
$lang['MISSION_256'] = 'Crater Xpofer';
$lang['MISSION_257'] = 'Mare Aegidius';

$lang['MISSION_260'] = 'Sinus Aeneas';
$lang['MISSION_261'] = 'Crater Philipus';
$lang['MISSION_262'] = 'Sinus Beniaminus';
$lang['MISSION_263'] = 'Vallis Rosamundi';
$lang['MISSION_264'] = 'Mons Peregrinus';
$lang['MISSION_265'] = 'Mare Xtianus';
$lang['MISSION_266'] = 'Vallis Crispianus';
$lang['MISSION_267'] = 'Crater Clementia';

$lang['MISSION_270'] = 'Vallis Elizabeta';
$lang['MISSION_271'] = 'Crater Xtopher';
$lang['MISSION_272'] = 'Mare Placentia';
$lang['MISSION_273'] = 'Sinus Gaufridus';
$lang['MISSION_274'] = 'Crater Stephanus';
$lang['MISSION_275'] = 'Vallis Xpianus	';
$lang['MISSION_276'] = 'Mare Girardus';
$lang['MISSION_277'] = 'Crater Radulphus';

$lang['MISSION_280'] = 'Crater Xtopherus';
$lang['MISSION_281'] = 'Vallis Terentius';
$lang['MISSION_282'] = 'Mons Eamnonn';
$lang['MISSION_283'] = 'Crater Kadisha';
$lang['MISSION_284'] = 'Mare Kachine';
$lang['MISSION_285'] = 'Vallis Oddvar';
$lang['MISSION_286'] = 'Sinus Radborne';
$lang['MISSION_287'] = 'Crater Ebenezer';

/* 
** ------------------
** MISSION PAGE
** ------------------
*/
 
$lang['MISSION_TITLE'] = 'MISSIES';
$lang['MISSION_NOTE'] = 'Opmerking: Speel missies om geld en ervaringspunten te krijgen en zo het volgende nivo te bereiken. Als een missie 100% voltooid is krijg je 2x zoveel geld. Als je %s 100% veroverd hebt wordt je uur inkomen met %s dollar verhoogd.';

$lang['MISSION_ALLIANCE_SIZE'] = 'alliantie grote';
$lang['MISSION_GAIN'] = 'Win';
$lang['MISSION_PART'] = 'Deel';
$lang['MISSION_REQUIRED'] = 'Nodig';
$lang['MISSION_UNLOCK'] = 'Ontgrendeld bij nivo %s';
$lang['MISSION_CHANCE_LOOT'] = 'Kans op buit';

$lang['MISSION_YOU_USED'] = 'Je gebruikte';
$lang['MISSION_YOU_GAIN'] = 'Je krijgt';
$lang['MISSION_DOLLAR_AND'] = ' dollar en ';
$lang['MISSION_ABORTED'] = 'Missie afgebroken!';
$lang['MISSION_NO_ENERGY'] = 'Je hebt niet genoeg energie om de missie te voltooien. Wacht een paar minuten om je energie op te laden.';
$lang['MISSION_LOW_ALLIANCE'] = 'Je Alliantie grootte is te klein om deze missie te spelen.';
$lang['MISSION_MISSING_UNITS'] = 'Je beschikt niet over de juiste hoeveelheid eenheden om de missie te voltooien. Ontbrekende eenheden: ';
$lang['MISSION_MISSING_UNITS_PRICE'] = 'Totale prijs om de eenheden te kopen is %s dollar. Onderhoudskosten zullen stijgen met %s dollar.';
$lang['MISSION_UNITS_LOST'] = 'Tijdens de missie verloor je de volgende eenheden';
$lang['MISSION_LOOT_WON'] = 'Je won de volgende buit tijdens de missie';
$lang['MISSION_UNLOCKED'] = 'Ga nu verder met de vecht training.';

$lang['MISSION_CONTINTENT_READY1'] = 'Geweldig! Je hebt deel %s van %s van het %s continent voltooid! ';
$lang['MISSION_CONTINTENT_READY2'] = 'Je hebt %s extra ervaringspunten ontvangen. ';
$lang['MISSION_CONTINTENT_READY3'] = 'Je bent klaar met alle delen. Ga verder met het volgende continent!';
$lang['MISSION_CONTINTENT_READY4'] = 'Ga verder met deel %s van dit continent!';
$lang['MISSION_COMPLETE_TEXT'] = 'Op dit moment heb je de volgende continenten verroverd!';

$lang['MISSION_REBEL'] = 'Rebellion';

/*
** ------------------
** BATTLE PAGE
** ------------------
*/

$lang['BATTLE_TITLE'] = 'STRIJD';
$lang['BATTLE_GENERAL_TITLE'] = 'Strijd';
$lang['BATTLE_BOUNTY_TITLE'] = 'Premie jagen';

$lang['BATTLE_LOST'] =  'Je %s viel %s aan. Gevecht verloren! %s schade opgelopen, %s schade toegebracht aan %s';
$lang['BATTLE_WON'] = 'Je %s viel %s aan. Gevecht gewonnen, je liep %s schade op en bracht %s schade toe aan %s. Je nam %s dollar in beslag en kreeg %s ervaringspunten.';
$lang['BATTLE_DEFENDER_HEALTH_LOW'] = '%s gezondheid is te laag om te vechten!';
$lang['BATTLE_ATTACKER_HEALTH_LOW'] = 'Je gezondheid is te laag om te vechten!. Bezoek het ziekenhuis voor een snel herstel of wacht op automatische herstel van je gezondheid.';
$lang['BATTLE_AMMO_LOW'] = 'Je hebt geen munitie meer! Wacht een paar minuten op het herladen of wissel vaardigheidspunten in voor meer munitie.';
$lang['BATTLE_UNITS_LOST'] = 'Tijdens de missie verloor je de volgenden eenheden:';
$lang['BATTLE_BUILDINGS_LOST'] = 'Tijdens de missie verloor je de volgenden gebouwen:';
$lang['BATTLE_DEFENSE_FORCE'] = '%s %s verdedigings %s (%s verdedigingskracht):'; 
$lang['BATTLE_DEFENSE_BASE'] = '%s verdedigings basis:'; 
$lang['BATTLE_ATTACK_FORCE'] = 'Je %s aanvals %s (%s aanvalskracht):';
$lang['BATTLE_MORE'] = 'meer';
$lang['BATTLE_NO_PLAYER_AVAILABLE'] = 'In dit nivo zijn er geen spelers beschikbaar om tegen te vechten.';
$lang['BATTLE_UNLOCKED'] = 'Vechten is ontgrendeld in nivo 1.<br/>Je moet eerst de training missie afronden.';
$lang['BATTLE_BOUNTY_UNLOCKED'] = 'Premiejagen is ontgrendeld in nivo %s.';
$lang['BATTLE_SURRENDER'] = 'Tijdelijk opgegeven';

$lang['BATTLE_ALLY_NO_ATTACK'] = 'Je hebt met <b>%s</b> een alliantie. Je kan spelers niet aanvallen waar je een alliantie mee hebt.';

$lang['BATTLE_NOTE1'] = 'Info: Vecht met andere spelers, om geld en ervaringspunten te verdienen en zo het volgende nivo te bereiken.';
$lang['BATTLE_NOTE2'] = 'Info: Vecht met andere spelers, win om de premie op te strijken en ervaringspunten te verdienen zodat je het volgende nivo kan bereiken.';

$lang['BATTLE_FORCE_TYPE'] = '';
$lang['BATTLE_ENEMIES'] = 'Vijanden';
$lang['BATTLE_BOUNTY'] = 'Premiejagen';
$lang['BATTLE_NO_BOUNTY_PLAYERS'] = 'Op dit moment zijn er geen speler(s) met een premie beschikbaar.';
$lang['BATTLE_BOUNTY_BONUS'] = 'Extra premie van %s dollar ontvangen!'; 
$lang['BATTLE_HOSPITAL_BONUS'] = '%s geeft tijdelijk op. Je ontvangt %s dollar bonus!';
$lang['BATTLE_BOUNTY_LOST'] = 'Je werd aangevallen door de %s van %s. Je <b>verloor</b>. Je verloor %s dollar, %s gezondheid en %s ervaringspunten.';
$lang['BATTLE_BOUNTY_CONFIRM'] = 'Wil je een premie van %s dollar zetten?';

$lang['BATTLE_CEASE_FIRE_PERIOD'] = 'Wapenstilstand periode geactiveerd! %s';
$lang['BATTLE_AND'] = 'en';

$lang['BATTLE_NO_BOUNTY_MONEY'] = 'Je bezit geen %s dollar om als premie op %s hoofd te zetten.';
$lang['BATTLE_BOUNTY_SET'] = 'Je hebt %s dollar op het hoofd van %s gezet. Als %s wordt verslagen verlies hij %s vaardigheidspunten.'; 

$lang['BATTLE_MOON_UNLOCKED'] = 'Maan gevechten kunnen vanaf nivo 100.';
$lang['BATTLE_MARS_UNLOCKED'] = 'Mars gevechten kunnen vanaf nivo 150.';
$lang['BATTLE_ASTERIOD_UNLOCKED'] = 'Asteriod gevechten kunnen vanaf nivo 200.';

$lang['BATTLE_RANGE'] = 'Spelers van nivo %s to %s kunnen worden aangevallen.';

/*
** ------------------
** UNIT DATA
** ------------------
*/

/* Earth */
$lang['UNIT_GROUP_0'] = 'Leger';
$lang['UNIT_GROUP_2'] = 'Cavalerie';
$lang['UNIT_GROUP_3'] = 'Marine';
$lang['UNIT_GROUP_4'] = 'Luchtmacht';
$lang['UNIT_GROUP_5'] = 'Burgers';
$lang['UNIT_GROUP_6'] = 'Spionage';

/* Moon */
$lang['UNIT_GROUP_7']  = 'Warriors';
$lang['UNIT_GROUP_8']  = 'Drones';
$lang['UNIT_GROUP_9']  = 'Ruimteschepen';
$lang['UNIT_GROUP_10'] = 'Burgers';
$lang['UNIT_GROUP_11'] = 'Leger';
$lang['UNIT_GROUP_12'] = 'Ontdekkers';

/* Mars */
$lang['UNIT_GROUP_13']  = 'Drones';
$lang['UNIT_GROUP_14']  = 'Warriors';
$lang['UNIT_GROUP_15']  = 'Ruimteschepen';
$lang['UNIT_GROUP_16']  = 'Ontdekkers';
$lang['UNIT_GROUP_17'] 	= 'Burgers';
$lang['UNIT_GROUP_18'] 	= 'Leger';

/* ---------------------------------------------- */

/* Calvary (Earth) - Group 2 */
$lang['UNIT_1'] = 'Zandhaas';
$lang['UNIT_101'] = 'Militair Ziekenauto';
$lang['UNIT_102'] = 'Hum-Vee Jeep';
$lang['UNIT_103'] = 'Vrachtwagen';
$lang['UNIT_104'] = 'Lichte Artillerie';
$lang['UNIT_105'] = 'Infanterie Transport';
$lang['UNIT_106'] = 'MGM-51 Shillelagh';
$lang['UNIT_107'] = 'Gepanserd Transport';
$lang['UNIT_108'] = 'Aanvals Voertuig';
$lang['UNIT_109'] = 'Gronddoel Lanceersysteem';
$lang['UNIT_110'] = 'Lichte Hovercraft';
$lang['UNIT_111'] = 'M1 Abrams Tank';
$lang['UNIT_112'] = 'Gepanserd Voertuig';
$lang['UNIT_113'] = 'Bushhmaster Voertuig';
$lang['UNIT_114'] = 'Langeafstands Lanceersysteem';
$lang['UNIT_115'] = 'Leopard 1A1';
$lang['UNIT_116'] = 'Land Rover';
$lang['UNIT_117'] = 'Rubs-Transporter';
$lang['UNIT_118'] = 'Aanvals Voertuig';
$lang['UNIT_119'] = 'Hellfire Tank';
$lang['UNIT_120'] = 'Gevechts Tank';
$lang['UNIT_121'] = 'MCS Gevechtseenheid';
$lang['UNIT_122'] = 'Artillery Tank';
$lang['UNIT_123'] = 'Charparrai Tank';
$lang['UNIT_124'] = 'M198 Howitzer';
$lang['UNIT_125'] = 'Zwaar Artillery Geschut';
$lang['UNIT_126'] = 'Missile Lanceereenheid';
$lang['UNIT_127'] = 'Anti-Luchtdoel Geschut';

/* Navy (Earth) - Group 3 */
$lang['UNIT_201'] = 'Zodiak';
$lang['UNIT_202'] = 'Bevoorradingschip';
$lang['UNIT_203'] = 'Fregat';
$lang['UNIT_204'] = 'Marine Tanker';
$lang['UNIT_205'] = 'Mijnenveger';
$lang['UNIT_206'] = 'M80 Stiletto';
$lang['UNIT_207'] = 'Onderzee&euml;r';
$lang['UNIT_208'] = 'Helikopter Carrier';
$lang['UNIT_209'] = 'Fregat';
$lang['UNIT_210'] = 'Anti-schipraket schip';
$lang['UNIT_211'] = 'Horizon Fregat';
$lang['UNIT_212'] = 'Torpedojager';
$lang['UNIT_213'] = 'Vlaggenschip';
$lang['UNIT_214'] = 'Scorpene Onderzee&euml;r';
$lang['UNIT_215'] = 'DDG 1000 Torpedojager';
$lang['UNIT_216'] = 'Elite Dreadnought';
$lang['UNIT_217'] = 'Ohio Onderzee&euml;r';
$lang['UNIT_218'] = 'Sea Fighter';
$lang['UNIT_219'] = 'HSV-2 Swift';
$lang['UNIT_220'] = 'Raket Kruiser';
$lang['UNIT_221'] = 'UXV Combatant';
$lang['UNIT_222'] = 'Anti-Onderzee&euml;r schip';
$lang['UNIT_223'] = 'Amfibie Transporter';
$lang['UNIT_224'] = 'Vliegdekschip';
$lang['UNIT_225'] = 'Landing Platform Dock';
$lang['UNIT_226'] = 'Type 23 Fregat';
$lang['UNIT_227'] = 'Commandofregat';
$lang['UNIT_228'] = 'Nucleaire Kruiser';

/* Airforce (Earth) - Group 4 */
$lang['UNIT_301'] = 'Cessna 172';
$lang['UNIT_302'] = 'C-17 Transport vliegtuig';
$lang['UNIT_303'] = 'V-22A Osprey Gunship';
$lang['UNIT_304'] = 'AV-8B Harrier Jager';
$lang['UNIT_305'] = 'Comanche Helikopter';
$lang['UNIT_306'] = 'Havoc Helicopter';
$lang['UNIT_307'] = 'Saab JA37 Viggen';
$lang['UNIT_308'] = 'SR-71 Blackbird';
$lang['UNIT_309'] = 'Apache Helikopter';
$lang['UNIT_310'] = 'B-2 Bommenwerper';
$lang['UNIT_311'] = 'F-18 Super Hornet';
$lang['UNIT_313'] = 'F-15 Silent Eagle';
$lang['UNIT_314'] = 'B-1 Lancer';
$lang['UNIT_316'] = 'F3 Interceptor';
$lang['UNIT_318'] = 'F-16 Falcon';
$lang['UNIT_319'] = 'PAK-FA Jager';
$lang['UNIT_320'] = 'F-117 Nighthawk';
$lang['UNIT_321'] = 'NGB Bommenwerper';
$lang['UNIT_322'] = 'F-14 Tomcat';
$lang['UNIT_323'] = 'F-35 Lightning II';
$lang['UNIT_324'] = 'B-52 Stratofortress';
$lang['UNIT_325'] = 'F-22 Raptor';
$lang['UNIT_326'] = 'Trident II Raket';

$lang['UNIT_401'] = 'Bouwvakker';
$lang['UNIT_402'] = 'Techneut';
$lang['UNIT_403'] = 'Laborant';
$lang['UNIT_404'] = 'Manager';
$lang['UNIT_405'] = 'Dokter';
$lang['UNIT_406'] = 'Kok';
$lang['UNIT_407'] = 'Beveiliger';

$lang['UNIT_501'] = 'Beveiligings Camera';
$lang['UNIT_502'] = 'Marine Intelligence';
$lang['UNIT_503'] = 'Mini lucht robot';
$lang['UNIT_504'] = 'G343 spionage robot';
$lang['UNIT_505'] = 'Informatie A3 Crusador';
$lang['UNIT_506'] = 'Spionage vissersboot';
$lang['UNIT_507'] = 'Hawk Eye';
$lang['UNIT_508'] = 'UK-80 Awacs';
$lang['UNIT_509'] = 'AS-102 stealth boot';
$lang['UNIT_510'] = 'US-101 Pretator';
$lang['UNIT_511'] = 'Heron Drone';
$lang['UNIT_512'] = 'HG101 Sateliet';

/* ---------------------------------------------- */

/* Warriors (Moon) - Group 7 */
$lang['UNIT_700'] = 'Warrior 1';
$lang['UNIT_701'] = 'Warrior 2';
$lang['UNIT_702'] = 'Warrior 3';
$lang['UNIT_703'] = 'Warrior 4';
$lang['UNIT_704'] = 'Warrior 5';
$lang['UNIT_705'] = 'Warrior 6';
$lang['UNIT_706'] = 'Warrior 7';
$lang['UNIT_707'] = 'Warrior 8';
$lang['UNIT_708'] = 'Warrior 9';
$lang['UNIT_709'] = 'Warrior 10';
$lang['UNIT_710'] = 'Warrior 11';

/* Drones (Moon) - Group 8 */
$lang['UNIT_800'] = 'Basic Rover';
$lang['UNIT_801'] = 'Lunar Transporter';
$lang['UNIT_802'] = 'Moon Explorer I';
$lang['UNIT_803'] = 'Moon Havostar';
$lang['UNIT_804'] = 'Mobile Lab';
$lang['UNIT_805'] = 'Transporter';
$lang['UNIT_805'] = 'Space Crane';
$lang['UNIT_806'] = 'Moon Buggy';
$lang['UNIT_807'] = 'Fuel Transporter';
$lang['UNIT_808'] = 'Fuel Explorer';
$lang['UNIT_809'] = 'Moon Explorer II';
$lang['UNIT_810'] = 'Gas Transporter';

/* Spacecrafts (Moon) - Group 9 */
$lang['UNIT_900'] = 'Moon Cruiser';
$lang['UNIT_901'] = 'Millennium Falcon';
$lang['UNIT_902'] = 'Ebon Hawk';
$lang['UNIT_903'] = 'Transport Robot';
$lang['UNIT_904'] = 'Slave I';
$lang['UNIT_905'] = 'Assault ship';
$lang['UNIT_906'] = 'Corellian corvette';
$lang['UNIT_907'] = 'War Hawk Shadow';
$lang['UNIT_908'] = 'Solar Spacecraft';
$lang['UNIT_909'] = 'Royal starship';
$lang['UNIT_910'] = 'Theta-Class Shuttle';
$lang['UNIT_911'] = 'Trade Cruiser';
$lang['UNIT_912'] = 'Sith Infiltrator';
$lang['UNIT_913'] = 'Imperial landing craft';
$lang['UNIT_914'] = 'Star Skiff II';
$lang['UNIT_915'] = 'Star Destroyer';
$lang['UNIT_916'] = 'Flag Ship';

/* Citizens (Moon) - Group 10 */
$lang['UNIT_1000'] = 'Astronaut';
$lang['UNIT_1001'] = 'Female Citizen';
$lang['UNIT_1002'] = 'Male Citizen';

/* Explorers (Moon) - Group 12 */
$lang['UNIT_1200'] = 'Explorer Satellite';
$lang['UNIT_1201'] = 'Explorer Ship';
$lang['UNIT_1202'] = 'Short Range Radar';
$lang['UNIT_1203'] = 'Deepspace Explorer';
$lang['UNIT_1204'] = 'Planet Explorer';
$lang['UNIT_1205'] = 'Space Elevator';
$lang['UNIT_1206'] = 'Astronaut Explorer';
$lang['UNIT_1207'] = 'Long Range Rader';
$lang['UNIT_1208'] = 'Deepspace Relay Station';
$lang['UNIT_1209'] = 'Lightspeed Explorer';
$lang['UNIT_1210'] = 'Planet Destroyer';
$lang['UNIT_1211'] = 'Galaxy Explorer II';

/* ---------------------------------------------- */

/* Drones (Mars) - Group 13 */
$lang['UNIT_1300'] = 'Drone M1';
$lang['UNIT_1301'] = 'Drone M0';
$lang['UNIT_1302'] = 'Drone M2';
$lang['UNIT_1303'] = 'Drone M3';
$lang['UNIT_1304'] = 'Drone M4';
$lang['UNIT_1305'] = 'Drone M5';
$lang['UNIT_1306'] = 'Drone M6';
$lang['UNIT_1307'] = 'Drone M7';
$lang['UNIT_1308'] = 'Drone M8';
$lang['UNIT_1309'] = 'Drone M9';

/* Warriors (Mars) - Group 14 */
$lang['UNIT_1400'] = 'Warrior M0';
$lang['UNIT_1401'] = 'Warrior M1';
$lang['UNIT_1402'] = 'Warrior M2';
$lang['UNIT_1403'] = 'Warrior M3';
$lang['UNIT_1404'] = 'Warrior M4';
$lang['UNIT_1405'] = 'Warrior M5';
$lang['UNIT_1406'] = 'Warrior M6';
$lang['UNIT_1407'] = 'Warrior M7';
$lang['UNIT_1408'] = 'Warrior M8';
$lang['UNIT_1409'] = 'Warrior M9';

/* Spacecrafts (Mars) - Group 15 */
$lang['UNIT_1500'] = 'Mars Cruiser I';
$lang['UNIT_1501'] = 'Cocon IV';
$lang['UNIT_1502'] = 'Hawk Eye V';
$lang['UNIT_1503'] = 'Ariane VI';
$lang['UNIT_1504'] = 'Gyro II';
$lang['UNIT_1505'] = 'Miner III';
$lang['UNIT_1506'] = 'Jannus VI';
$lang['UNIT_1507'] = 'Tango II';
$lang['UNIT_1508'] = 'Rader II';
$lang['UNIT_1509'] = 'Andrew III';

/* Explorers (Mars) - Group 16 */
$lang['UNIT_1600'] = 'Explorer M0';
$lang['UNIT_1601'] = 'Explorer M1';
$lang['UNIT_1602'] = 'Explorer M2';
$lang['UNIT_1603'] = 'Explorer M3';
$lang['UNIT_1604'] = 'Explorer M4';
$lang['UNIT_1605'] = 'Explorer M5';
$lang['UNIT_1606'] = 'Explorer M6';
$lang['UNIT_1607'] = 'Explorer M7';
$lang['UNIT_1608'] = 'Explorer M8';
$lang['UNIT_1609'] = 'Explorer M9';

/* Citizens (Mars) - Group 17 */
$lang['UNIT_1700'] = 'Astronaut';
$lang['UNIT_1701'] = 'Female Citizen';
$lang['UNIT_1702'] = 'Male Citizen';

/* ---------------------------------------------- */

/*
** ------------------
** UNIT PAGE
** ------------------
*/

$lang['UNIT_TITLE'] = 'EENHEDEN';

$lang['UNIT_NOTE_1'] = 'Note: Buy soldier units to enabled missions.';
$lang['UNIT_NOTE_2'] = 'Note: Buy Cavalry units to improve your Cavalry Force strenght. Battle, win and steal some money from your opponent cash account.';
$lang['UNIT_NOTE_3'] = 'Note: Buy Navy units to improve your Navy Force strenght. Battle, win and steal some money from your opponent cash account.';
$lang['UNIT_NOTE_4'] = 'Note: Buy Airfoce units to improve your Airforce strenght. Battle, win and steal some money from your opponent cash account.';
$lang['UNIT_NOTE_6'] = 'Note: Buy Espionage units to improve  your Espionage force strenght. Batlle, win to initialize rebellion on earth and steal some money from your opponent Traquara or SwissCore bank account.';

$lang['UNIT_NOTE_8'] = 'Note: Buy Moon Drone units to improve your Drone Force strenght. Battle, win and steal some money from your opponent cash account.';
$lang['UNIT_NOTE_7'] = 'Note: Buy Moon Warrior units to improve your Warrior Force strenght. Battle, win and steal some money from your opponent cash account.';
$lang['UNIT_NOTE_9'] = 'Note: Buy Moon Spacecraft units to improve your Spacecraft Force strenght. Battle, win and steal some money from your opponent cash account.';
$lang['UNIT_NOTE_12'] = 'Note: Buy Moon Expore units to improve  your Explorers force strenght. Batlle, win to initialize rebellion on the moon and steal some money from your opponent Traquara or SwissCore bank account.';

$lang['UNIT_NOTE_13'] = 'Note: Buy Mars Drone units to improve your Drone Force strenght. Battle, win and steal some money from your opponent cash account.';
$lang['UNIT_NOTE_14'] = 'Note: Buy Mars Warrior units to improve your Warrior Force strenght. Battle, win and steal some money from your opponent cash account.';
$lang['UNIT_NOTE_15'] = 'Note: Buy Mars Spacecraft units to improve your Spacecraft Force strenght. Battle, win and steal some money from your opponent cash account.';
$lang['UNIT_NOTE_16'] = 'Note: Buy Mars Expore units to improve  your Explorers force strenght. Batlle, win to initialize rebellion on the moon and steal some money from your opponent Traquara or SwissCore bank account.';


$lang['UNIT_DISBAND'] = 'Je verkocht %s %s voor %s. Er zijn er nog %s actief.';
$lang['UNIT_DISBAND_FAILED'] = 'Je bezit geen %s %s. Er zijn er nog %s actief.';

$lang['UNIT_DEPLOY'] = 'Je kocht %s %s voor %s. Er zijn er nu %s actief.';
$lang['UNIT_NO_UPKEEP'] = 'Niet genoeg netto inkomen om %s %s te bekostigen';
$lang['UNIT_NO_FONDS'] = 'Niet genoeg gemiddelen om %s %s voor %s aan te kopen.';
$lang['UNIT_MAX'] = 'Niet meer dan %s %s zijn toegestaan!';

/*
** ------------------
** BUILDING DATA
** ------------------
*/

/* Earth Buildings */
$lang['BUILDING_GROUP_1'] = 'Inkomsten';
$lang['BUILDING_GROUP_2'] = 'Verdediging';
$lang['BUILDING_GROUP_3'] = 'Energie';
$lang['BUILDING_GROUP_4'] = 'Korting';
$lang['BUILDING_GROUP_5'] = 'Onderhoud';

/* Moon Buildings */
$lang['BUILDING_GROUP_6'] = 'Inkomsten';
$lang['BUILDING_GROUP_7'] = 'Verdediging';
$lang['BUILDING_GROUP_8'] = 'Energie';
$lang['BUILDING_GROUP_9']  = 'Korting';
$lang['BUILDING_GROUP_10'] = 'Onderhoud';

/* Mars Buildings */
$lang['BUILDING_GROUP_11'] = 'Inkomsten';
$lang['BUILDING_GROUP_12'] = 'Verdediging';
$lang['BUILDING_GROUP_13'] = 'Energie';
$lang['BUILDING_GROUP_14'] = 'Korting';
$lang['BUILDING_GROUP_15'] = 'Onderhoud';

/* ---------------------------------------------- */

/* Earth Buildings */
$lang['BUILDING_1'] = 'Militaire opslagplaats';
$lang['BUILDING_2'] = 'Bunker';
$lang['BUILDING_3'] = 'Raffinaderij';
$lang['BUILDING_4'] = 'Zonne energie unit';
$lang['BUILDING_5'] = 'Tankwal';
$lang['BUILDING_6'] = 'Wapen fabriek';
$lang['BUILDING_7'] = 'Luchtafweer geschut';
$lang['BUILDING_8'] = 'Communicatie Centrum';
$lang['BUILDING_9'] = 'Korte afstand luchtafweer';
$lang['BUILDING_10'] = 'Mobiele Aggregaat';
$lang['BUILDING_11'] = 'Wachttoren';
$lang['BUILDING_12'] = 'Olie Booreiland';
$lang['BUILDING_13'] = 'Kolen energie centrale';
$lang['BUILDING_14'] = 'Militair ontwikkel lab';
$lang['BUILDING_15'] = 'Mijnenveld';
$lang['BUILDING_16'] = 'Nucleair test lab';
$lang['BUILDING_17'] = 'Satelliet netwerk';
$lang['BUILDING_18'] = 'Windmolenpark';
$lang['BUILDING_19'] = 'Olie bron';
$lang['BUILDING_20'] = 'Lange afstand luchtafweer';
$lang['BUILDING_21'] = 'Kust bunker';
$lang['BUILDING_22'] = 'Torpedo launcher';
$lang['BUILDING_23'] = 'Zeemijnenveld';
$lang['BUILDING_24'] = 'Bio science lab';
$lang['BUILDING_25'] = 'Water behandelingsunit';
$lang['BUILDING_26'] = 'Zonne energie centrale';
$lang['BUILDING_27'] = 'Zee Windmolenpark';
$lang['BUILDING_28'] = 'Geothermal energie centrale';
$lang['BUILDING_29'] = 'Leger veldkeuken';
$lang['BUILDING_30'] = 'Militair Training kamp';
$lang['BUILDING_31'] = 'Militair Academie';
$lang['BUILDING_32'] = 'Recreatie Faciliteit';
$lang['BUILDING_33'] = 'Militair Monument';
$lang['BUILDING_34'] = 'Militair Hoofdkwartier';
$lang['BUILDING_35'] = 'Hydro Centrale';
$lang['BUILDING_36'] = 'Politiek Centrum';
$lang['BUILDING_37'] = 'Mobiel Ziekenhuis';
$lang['BUILDING_38'] = 'Commando Centrum';
$lang['BUILDING_39'] = 'Nucleair energie centrale';
$lang['BUILDING_40'] = 'Militair winkelcentrum';
$lang['BUILDING_41'] = 'Weg onderhoud';
$lang['BUILDING_42'] = 'Brug onderhoud';
$lang['BUILDING_43'] = 'Transport onderhoud';
$lang['BUILDING_44'] = 'Helicopter onderhoud';
$lang['BUILDING_45'] = 'Voertuig onderhoud';
$lang['BUILDING_46'] = 'Schip onderhoud';
$lang['BUILDING_47'] = 'Gebouw onderhoud';
$lang['BUILDING_48'] = 'Onderzeeboot onderhoud';
$lang['BUILDING_49'] = 'Energie centrale onderhoud';
$lang['BUILDING_50'] = 'Vliegtuig onderhoud';
$lang['BUILDING_51'] = 'Ambassade';
$lang['BUILDING_52'] = 'Spion Commando Centrum';
$lang['BUILDING_53'] = 'Drone bedieningscentrum';
$lang['BUILDING_54'] = 'Cyberspace Centrum';

/*
** ------------------
** BUILDING PAGE
** ------------------
*/

$lang['BUILDING_TITLE'] = 'GEBOUWEN';

$lang['BUILDING_NOTE1'] = 'Opmerking: Door middel van het aankopen van inkomsten gebouwen genereer je extra inkomsten.';
$lang['BUILDING_NOTE2'] = 'Opmerking: Door middel van het aankopen van verdeging gebouwen verbetert je algemene verdediging.';
$lang['BUILDING_NOTE3'] = 'Opmerking: Door middel van het aankopen van energie gebouwen bouw je sneller energie op.';
$lang['BUILDING_NOTE4'] = 'Opmerking: Door middel van het aankopen van korting gebouwen krijg je meer korting op de gebouw prijzen.';
$lang['BUILDING_NOTE5'] = 'Opmerking: Door middel van het aankopen van onderhoudsgebouwen worden eenheden beter gerepareerd zodat je minder eenheden verlies tijdens gevechten.';

$lang['BUILDING_NOTE6'] = 'Opmerking: Door middel van het aankopen van inkomsten gebouwen genereer je extra inkomsten.';
$lang['BUILDING_NOTE7'] = 'Opmerking: Door middel van het aankopen van verdeging gebouwen verbetert je algemene verdediging.';
$lang['BUILDING_NOTE8'] = 'Opmerking: Door middel van het aankopen van energie gebouwen bouw je sneller energie op.';
$lang['BUILDING_NOTE9'] = 'Opmerking: Door middel van het aankopen van korting gebouwen krijg je meer korting op de gebouw prijzen.';
$lang['BUILDING_NOTE10'] = 'Opmerking: Door middel van het aankopen van onderhoudsgebouwen worden eenheden beter gerepareerd zodat je minder eenheden verlies tijdens gevechten.';

$lang['BUILDING_NOTE11'] = 'Opmerking: Door middel van het aankopen van inkomsten gebouwen genereer je extra inkomsten.';
$lang['BUILDING_NOTE12'] = 'Opmerking: Door middel van het aankopen van verdeging gebouwen verbetert je algemene verdediging.';
$lang['BUILDING_NOTE13'] = 'Opmerking: Door middel van het aankopen van energie gebouwen bouw je sneller energie op.';
$lang['BUILDING_NOTE14'] = 'Opmerking: Door middel van het aankopen van korting gebouwen krijg je meer korting op de gebouw prijzen.';
$lang['BUILDING_NOTE15'] = 'Opmerking: Door middel van het aankopen van onderhoudsgebouwen worden eenheden beter gerepareerd zodat je minder eenheden verlies tijdens gevechten.';

$lang['BUILDING_SELL'] = 'Je verkocht %s %s voor %s. Er zijn er nog %s actief.';
$lang['BUILDING_LOW_UPKEEP'] = 'Niet genoeg netto inkomen om %s %s te verkopen voor %.';
$lang['BUILDING_NOT_OWNED'] = 'Je bezit geen %s %s.';

$lang['BUILDING_BUY'] = 'Je kocht %s %s voor %s. Er zijn er nu %s actief.';
$lang['BUILDING_MAX'] = 'Niet meer dan %s(s) zijn toegestaan.';
$lang['BUILDING_NO_FUNDS'] = 'Niet genoeg middelen om %s %s voor %s aan te kopen.'; 
$lang['BUILDING_LOW_UPKEEP2'] = 'Niet genoeg netto inkomen om %s %s te kopen voor %.';

$lang['BUILDING_UPKEEP'] = 'Uur prijs';
$lang['BUILDING_PRICE'] = 'Prijs';
$lang['BUILDING_DEPLOYED'] = 'Actief';
$lang['BUILDING_GAIN'] = 'Win';
$lang['BUILDING_ENERGY'] = 'Energie';
$lang['BUILDING_INCOME'] = 'Inkomen';
$lang['BUILDING_REQUIRED'] = 'Nodig';

/*
** ------------------
** MONEY 
** ------------------
*/

$lang['MONEY_TITLE'] = 'GELD';

/*
** ------------------
** BANKS PAGE
** ------------------
*/

$lang['BANK_GROUP_1'] = 'National';
$lang['BANK_GROUP_2'] = 'Trasquera';
$lang['BANK_GROUP_3'] = 'SwissCore';

$lang['BANK_TITLE'] = 'BANKEN';
$lang['BANK_NOTE'] = 'Opmerkingen: Elke inleg kost %s% transactie kosten. De bank betaald %s% rente elke dag.';
$lang['BANK_WARNING'] = 'Waarschuwing: Spionage eenheden kunnen geld stelen van deze bank.';

$lang['BANK_TRANSACTION_TYPE_0'] = 'Opname';
$lang['BANK_TRANSACTION_TYPE_1'] = 'Inleg';
$lang['BANK_TRANSACTION_TYPE_2'] = 'Transactie kosten';
$lang['BANK_TRANSACTION_TYPE_3'] = 'Herstel rekening';		
$lang['BANK_TRANSACTION_TYPE_4'] = 'Rente';	
$lang['BANK_TRANSACTION_TYPE_5'] = 'spion stal';
$lang['BANK_TRANSACTION_TYPE_6'] = 'Bonus';

$lang['BANK_TRANSACTION_LOG'] = 'Transacties';

$lang['BANK_WITHDRAW']= '%s dollar opgenomen van bank';
$lang['BANK_WITHDRAW_FAILED'] = 'Geen %s dollar op de bank!';

$lang['BANK_DEPOSIT'] = '%s dollar gestort op bank.';
$lang['BANK_DEPOSIT_FAILED'] = 'Je bezit geen %s dollar.';

/* 
** ------------------
** STOCK PAGE
** ------------------
*/

$lang['STOCK_GROUP_1'] = 'Nasdaq';
$lang['STOCK_GROUP_2'] = 'DowJones';
$lang['STOCK_GROUP_3'] = 'AEX';
$lang['STOCK_GROUP_4'] = 'Personelijk';

$lang['STOCK_BROKER_ERROR'] = 'Beurs connectie ligt er uit. Hierdoor kan nu niet gehandeld worden. Probeer het later opnieuw.';
$lang['STOCK_BUY'] = 'Je kocht %s %s aandelen voor %s dollar. %s aandelen in bezit.';
$lang['STOCK_NO_MONEY'] = 'Niet genoeg geld om %s %s aandelen voor %s dollar te kopen.';
$lang['STOCK_PRICE'] = 'Aandeel prijs %s [%s]';
$lang['STOCK_PROFIT'] = 'Aandeel winst %s [%s]';
$lang['STOCK_NOT_OWNED'] = 'Je bezit niet %s %s aandelen.';
$lang['STOCK_SELL'] = 'Je verkocht %s %s aandelen voor %s dollar. Bank transactie kosten zijn %s dollar. %s aandelen nog in bezit.';
$lang['STOCK_NOTE'] = 'Opmerking: Je kan aandelen kopen en verkopen zodat je winst kan maken. De aandelen koers wordt realtime gesynchoniseerd met de geselecteerd aandelenbeurs. Elke verkoop transactie kosten %s%.';
$lang['STOCK_PRICE_TO_LOW'] = 'Stock price to low. Trading blocked!';

$lang['STOCK_SYMBOL'] = 'Stock Symbol'; 
$lang['STOCK_SYMBOL_INFO'] = 'Note: Enter yahoo financial stock symbol to customize this list.'; 

$lang['STOCK_ADD'] = 'Add Stock';
$lang['STOCK_SYMBOL_ADDED'] = 'You added (%s) to your personal stock list.';
$lang['STOCK_NO_SYMBOLS' ] = 'You did not add any personal stocks yet!';
$lang['STOCK_SYMBOL_NOT_FOUND'] = 'Stock symbol (%s) does not exist!';
$lang['STOCK_SYMBOL_AVAILABLE'] = 'Stock symbol (%s) all ready available in personal list.';

$lang['STOCK_REMOVE'] = 'Remove Stock';
$lang['STOCK_SYMBOL_REMOVED'] = 'Stock symbol removed!';

$lang['GENERAL_STOCKS'] = 'Stocks';

/*
** ------------------
** CASINO
** ------------------
*/

$lang['CASINO_TITLE'] = 'CASINO' ;

$lang['CASINO_1'] = 'WielVanGeluk';
$lang['CASINO_2'] = 'SlotMachine';

$lang['CASINO_COMING_SOON'] = 'wordt aan gebouwd';

$lang['CASINO_MONEY'] = 'Geld';
$lang['CASINO_NUMBER'] = 'Geluksgetal';
$lang['CASINO_BET'] = 'Inzet';
$lang['CASINO_PLAY'] = 'Speel';
$lang['CASINO_ROLL'] = 'Draai';

$lang['CASINO_NO_BET'] = 'Voer een inzet in!';
$lang['CASINO_NO_LUCKY_NUMBER'] = 'Voer een geluksgetal in!';
$lang['CASINO_BET_TO_LARGE'] = 'Inzet te hoog! Maximaal mag je %s dollar inzetten.'; 
$lang['CASINO_NO_MONEY'] = 'Niet genoeg geld!'; 

$lang['CASINO_WIN'] = 'Winnende getal was %s. Je won %s dollar.';
$lang['CASINO_LOST'] = 'Winnende getal was %s. Je verloor %s dollar.';

$lang['CASINO_NOTE1'] = 'Tip: Wiel van Geluk. Selecteer je geluksnummer en spel. Als je wint krijg je 10 keer de inzet.';
$lang['CASINO_NOTE2'] = 'Tip: Slot Machine. Doe een inzet en spel. Als je wint krijg je X keer de inzet.';

$lang['CASINO_UNLOCK'] = '%s is ontgrendeld in nivo %s';

$lang['CASINO_SLOTMACHINE_WIN'] = 'Je won %s keer je inzet. Je won %s dollar.';
$lang['CASINO_SLOTMACHINE_LOST'] = 'Je verloor %s dollar.';
$lang['CASINO_SLOTMACHINE_HELP'] = 'Met de volgende combinaties win je X keer je inzet';

/*
** ------------------
** ALLIANCE PAGE
** ------------------
*/

$lang['ALLIANCE_TITLE'] = 'ALLIANTIE';

$lang['ALLIANCE_PENDING_TITLE1'] = 'Lopende';
$lang['ALLIANCE_PENDING_TITLE2'] = 'Lopende [%s geaccepteerd - %s uitgenodigd allianties]';

$lang['ALLIANCE_ACCEPT_TITLE1'] = 'Geaccepteerd';
$lang['ALLIANCE_ACCEPT_TITLE2'] = 'Geaccepteerd [%s geaccepteerd - %s uitgenodigd allianties]';

$lang['ALLIANCE_INVITE_TITLE1'] = 'Uitnodiging';
$lang['ALLIANCE_INVITE_TITLE2'] = 'Uitnodiging [%s geaccepteerd - %s uitgenodigd allianties]';

$lang['ALLIANCE_NO_PENDING'] = 'Op dit moment zijn er geen lopende alliantie uitnodigingen!'; 
$lang['ALLIANCE_INVITATION'] = 'Alliantie uitnodiging naar %s verstuurd!'; 
$lang['ALLIANCE_REJECT'] = 'Alliantie met %s afgewezen!';
$lang['ALLIANCE_DROP'] = 'Allianctie met %s verbroken!';
$lang['ALLIANCE_ACCEPT'] = 'Alliantie met %s geaccepteerd!';
$lang['ALLIANCE_ALLY'] = 'Alliantie';
$lang['ALLIANCE_MAXIMUM'] = 'Maximum van %s allianties bereikt voor dit level.'; 
$lang['ALLIANCE_LOCKED'] = 'Allianties zijn mogelijk vanaf level 1';
$lang['ALLIANCE_NOTE'] = 'Opmerking: Voor elke goedgekeurde alliantie kan je 6 extra eenheden inzetten tijdens een gevecht.';

$lang['ALLIANCE_INVITE_FRIENDS'] = 'Vriend uitnodigen per email:';
$lang['ALLIANCE_INVITE_NOTE'] = 'Opmerking: Nodig andere spelers uit voor een alliantie. Als de andere speler jouw uitnodiging accepteerd of weigerd ontvang je een email bericht. Maximum aantal toegestaande allianties voor dit level is %s';
$lang['ALLIANCE_EMAIL_INVALID']= 'Email adres is niet correct!';
$lang['ALLIANCE_ALREADY_INVITED'] = 'Email adres is al vaker uitgenodigd!';
$lang['ALLIANCE_INVITE_SENT'] = 'Uitnodigings email is verzonden.';

$lang['ALLIANCE_COMMENT_TITLE'] = 'Berichten';
$lang['ALLIANCE_COMMENT_TEXT1'] = 'Maak bericht (max. 400 karakters) voor alle spelers';
$lang['ALLIANCE_COMMENT_TEXT2'] = 'Maak bericht (max. 400 karakters) voor %s';
$lang['ALLIANCE_PLAYER_NEWS'] = 'Berichten';
$lang['ALLIANCE_COMMENT_ALL'] = 'Bericht is opgeslagen en beschikbaar voor alle spelers!';
$lang['ALLIANCE_COMMENT_PLAYER'] = 'Bericht verzonden naar %s';

$lang['LEADERBORD_BEST_PLAYER'] = 'Overzicht (Beste Spelers)';
$lang['LEADERBORD_BEST_PLAYER_NOTE'] = 'Opmerking: Dit overzicht laat de beste spelers zien. WarQuest robot (cyberspace) spelers worden niet weergegeven.';

$lang['LEADERBORD_BEST_COUNTRY'] = 'Overzicht (Beste Land)';
$lang['LEADERBORD_BEST_COUNTRY_NOTE'] = 'Opmerking: Dit overzicht laat de beste landen zien.';

$lang['LEADERBORD_PLAYER_COUNTRY'] = 'Overzicht (Beste speler van %s)';
$lang['LEADERBORD_PLAYER_COUNTRY_NOTE'] = 'Opmerking: Dit overzicht laat de beste spelers van het geselecteerde land zien.';

$lang['TOPIC_TITLE'] = 'Onderwerpen'; 
$lang['TOPIC_CREATED_INPUT'] = 'Maak een nieuwe onderwerp (max. 80 karakters)';
$lang['TOPIC_CREATED'] = 'Onderwerp aangemaakt';
$lang['TOPIC_UPDATED'] = 'Onderwerp bijgewerkt';
$lang['TOPIC_DELETED'] = 'Onderwerp verwijderd';
$lang['TOPIC_NO_TOPICS'] = 'Op dit moment zijn er geen onderwerpen beschikbaar op dit forum.';
$lang['TOPIC_NOTE'] = 'Tip: Selecteer een onderwerp om opgeslagen berichten te lezen of te schrijven.'; 
$lang['TOPIC_CREATED_BY'] = '(Aangemaakt door %s)';

/*
** ------------------
** FORUM 
** ------------------
*/

$lang['FORUM_TITLE'] = 'Forums'; 
$lang['FORUM_NOTE'] = 'Note: Selecteer een forum om onderliggende onderwerpen te zien.';

$lang['FORUM_1'] = 'Mededelingen'; 
$lang['FORUM_NOTE_1'] = 'Algemene mededelingen';
$lang['FORUM_2'] = 'Foutrapporten'; 
$lang['FORUM_NOTE_2'] = 'Wat gaat fout in deze versie?';
$lang['FORUM_3'] = 'Wijzigingsverzoeken'; 
$lang['FORUM_NOTE_3'] = 'Wat is gewenst in de volgende versie?';
$lang['FORUM_4'] = 'Help'; 
$lang['FORUM_NOTE_4'] = 'Wat is niet duidelijk in WarQuest?';
$lang['FORUM_5'] = 'Overige'; 
$lang['FORUM_NOTE_5'] = 'Overige onderwerpen?';
$lang['FORUM_6'] = 'Landen Platform'; 
$lang['FORUM_NOTE_6'] = 'Nationale taal discussies?';

$lang['FORUM_SEARCH_TOKEN'] = 'Search token must be atleast 3 character long.';

$lang['TOPIC_TITLE'] = 'Topics'; 
$lang['TOPIC_CREATED_INPUT'] = 'Create new topic (max. 80 characters)';
$lang['TOPIC_CREATED'] = 'Topic is created';
$lang['TOPIC_UPDATED'] = 'Topic is updated';
$lang['TOPIC_DELETED'] = 'Topic is deleted';
$lang['TOPIC_NO_TOPICS'] = 'On this moment no topic(s) found.';
$lang['TOPIC_NOTE'] = 'Note: Select a topic to read/write posted messages or create a new topic.'; 
$lang['TOPIC_CREATED_BY'] = '(Created by %s)';

/*
** ------------------
** FORUM - POLL
** ------------------
*/

$lang['POLL_TITLE'] = 'Polls';
$lang['POLL_RESULT_TITLE'] = 'Poll Results';
$lang['POLL_TEASER_TITLE'] = 'New Poll';
$lang['POLL_RESULTS'] = 'Results';
$lang['POLL_ClOSED'] = '(Poll closed)';
$lang['POLL_VOTE_ADD'] = 'Thanks you for your vote! You received 10 bonus experience points as reward.';
$lang['POLL_VOTE_REMOVE'] = 'Your vote is canceled!';
$lang['POLL_VOTE'] = 'Vote';
$lang['POLL_VOTES'] = 'Votes';
$lang['POLL_CANCEL'] = 'Cancel';
$lang['POLL_SUMMARY'] = 'Total Voters: %s';
$lang['POLL_WARNING'] = 'Select one of the possible vote options!';

/*
** ------------------
** FORUM  - CHAT
** ------------------
*/

$lang['CHATROOM_TITLE'] = 'Chatroom';
$lang['CHATROOM_NOTE'] = 'Note: Start a chat session by selecting an online player!';
$lang['CHATROOM_LAST_ACTIVE'] = 'Last Active';
$lang['CHATROOM_CHAT'] = 'Chat';
$lang['CHAT_NOTE'] = 'Note: Enter a message to start the chat!';

$lang['CHAT_TITLE'] = 'Chat';

/* 
** ------------------
** HELP - INSTRUCTIONS
** ------------------
*/

$lang['HELP_TITLE'] = 'HELP';

$lang['HELP_GENERAL_SUBTITLE'] = 'Instructies';
$lang['HELP_INTRO_TITLE'] = 'Introductie';
$lang['HELP_INTRO'] =	'Welkom bij WarQuest. Deze Realtime Multi Player Game (RMPG) neemt je mee naar het jaar 2020. De wereld is in oorlog. Het doel van het spel is om je land te verdedigen en andere te veroveren. Koop wapens en productie-faciliteiten, Speel missies, vecht, maak bondgenoten en word de beste speler van je land.';
$lang['HELP_EXP_TITLE'] = 'Ervaring / Nivo';
$lang['HELP_EXP'] = 'Speel missies en strijd om ervaringspunten te verkrijgen. Als er genoeg ervaringspunten zijn verzameld behaal je het volgende nivo. Wanneer een nivo is voltooid, worden energie, gezondheid en munitie direct volledig hersteld.';
$lang['HELP_HEALTH_TITLE'] = 'Gezondheid';
$lang['HELP_HEALTH'] = 'Je gezondheid vermindert bij elk gevecht, maar herstelt automatisch na verloop van tijd. Je kunt ook naar het ziekenhuis om direct te herstellen.';
$lang['HELP_ENERGY_TITLE'] = 'Energie'; 
$lang['HELP_ENERGY'] = 'Je energie vermindert na elke gespeelde missie, maar herstelt automatisch na verloop van tijd. Koop energie gebouwen om sneller energie te herstellen.';
$lang['HELP_AMMO_TITLE'] = 'Munitie'; 
$lang['HELP_AMMO'] =	'Elk gevecht kost een munitie. Munitie wordt automatisch hersteld na verloop van tijd.';
$lang['HELP_MISSION_TITLE'] = 'Missies';
$lang['HELP_MISSION'] = 'Speel missies om geld en ervaringspunten te krijgen en het volgende nivo te bereiken. Als een missie 100% voltooid is krijg je dubbel zoveel geld.';
$lang['HELP_BATTLE_TITLE'] = 'Gevechten';
$lang['HELP_BATTLE'] =	'Vecht met andere spelers om geld en ervaringspunten te krijgen en het volgende nivo te bereiken. Tijdens de strijd kunnen units worden beschadigd of verloren gaan.';
$lang['HELP_UNITS_TITLE'] = 'Eenheden';
$lang['HELP_UNITS'] =  'Tijdens de aanvallen, zullen je bondgenoten automatisch je beste eenheden gebruiken. Elke bondgenoot kan maximaal tot zes eenheden commanderen.';
$lang['HELP_BUILDINGS_TITLE'] = 'Gebouwen';
$lang['HELP_BUILDINGS'] = 'Tijdens het spel zorgen gebouwen voor inkomsten, meer verdedigingen / of snellere energie opbouw. Elke aankoop van een gebouw zal de prijs verhogen.';
$lang['HELP_BANKS_TITLE'] = 'Banken';
$lang['HELP_BANKS'] = 'Iedere bank berekent stortingskosten. Geld in bewaring bij de National bank is veilig tegen diefstal door andere spelers maar deze bank geeft maar een lage dagelijkse rente. De overige banken geven een zeer hoge dagelijkse rente maar spionen van andere spelers kunnen wel geld stelen.';
$lang['HELP_ALLIANCE_TITLE'] = 'Alliantie'; 
$lang['HELP_ALLIANCE'] = 'Met elke goedgekeurd bondgenoot kunt u 6 extra eenheden commanderen tijdens gevechten. Maak dus vrienden om sterker te worden!';
$lang['HELP_SKILL_POINTS_TITLE'] = 'Vaardigheidspunten';
$lang['HELP_SKILL_POINTS'] = 'Tijdens het spel kunnen worden vaardigheidspunten verzamelen. Gebruik vaardigheidspunten om aanval, verdediging, gezondheid, energie en/of munitie vaardigheden te verbeteren. Munitie vaardigheid verbeteren kost twee vaardigheidspunten, de overige een vaardigheidspunt.';
$lang['HELP_TACTICS_TITLE'] = 'Tactiek';
$lang['HELP_TACTICS'] = 'Op dit moment is geen informatie over dit onderwerp beschikbaar.';
$lang['HELP_GRAVATAR_TITLE'] = 'Gravatar';
$lang['HELP_GRAVATAR'] = 'WarQuest ondersteund gravatar (www.gravatar.com) foto service. Als je een pasfoto upload wordt deze getoond op je speler overzicht pagina.';

/*
** ------------------
** FORUM  - RANKS
** ------------------
*/

$lang['HELP_RANKS_SUBTITLE'] = 'Rangen';
$lang['HELP_RANKS'] = 'De volgende rangen zijn beschikbaar:';

/*
** ------------------
** FORUM  - LEVELS
** ------------------
*/

$lang['HELP_LEVEL_SUBTITLE'] = 'Nivo`s';
$lang['HELP_LEVEL'] = 'De volgende nivo`s zijn beschikbaar:';
$lang['HELP_LEVEL_UNIT_LOST'] = 'Unit Lost';
$lang['HELP_LEVEL_EXPERIENCE'] = 'Experciece';
$lang['HELP_LEVEL_FEATURES'] = 'Feature unlock schema';

/*
** ------------------
** FORUM  - AWARDS
** ------------------
*/

$lang['HELP_AWARDS_SUBTITLE'] = 'Onderscheidingen';
$lang['HELP_BATTLE_AWARDS'] = 'De volgende gevechten onderscheidingen kunnen worden verdiend:';
$lang['HELP_BOUNTY_AWARDS'] = 'De volgende premie onderscheidingen kunnen worden verdiend:';

/*
** ------------------
** FORUM  - STATS
** ------------------
*/

$lang['HELP_STATS_TITLE'] = 'Statistieken';
$lang['HELP_STATS_NOTE'] = 'Tip: Op deze pagina worden alle realtime WarQuest statistieken getoond.';
$lang['HELP_STATS_PLAYERS'] = 'Nieuwe spelers (laatste 31 dagen)';
$lang['HELP_STATS_ONLINE'] = 'Spelers online (laatste 31 dagen)';
$lang['HELP_STATS_FIGHTS'] = 'Gevechten (laatste 31 dagen)';
$lang['HELP_STATS_MISSIONS'] = 'Missies gespeelt (laatste 31 dagen)';
$lang['HELP_STATS_CASINO'] = 'Casino spelen gespeeld (laatste 31 dagen)';
$lang['HELP_STATS_GOLD'] = 'Goud gebruik (laatste 31 dagen)';
$lang['HELP_STATS_REQUESTS'] = 'Server aanvragen (laatste 13 dagen)';

/*
** ------------------
** HELP - DONATE
** ------------------
*/


/*
** ------------------
** FORUM  - ABOUT
** ------------------
*/

$lang['HELP_ABOUT_SUBTITLE'] = 'Over';
$lang['HELP_BACKGROUND_TITLE'] = 'Achtergrond';
$lang['HELP_BACKGROUND'] = 'WarQuest is gemaakt door <a target="new" href="http://www.plaatsoft.nl">PlaatSoft</a>. Het origenele spel idee is gebaseerd op enkele andere spellen welke beschikbaar zijn in de Apple appstore. De belangrijkste reden om opnieuw dit type spel te bouwen is een betere gebruikersinterface te ontwikkelen zodat het spel gespeeld kan worden op de een volgende typen apparaten: Smart phones (Apple, Nokia en Black Berry), tables (Apple), Spel computer (Nintendo) en notebooks (Intel en AMD base).';
$lang['HELP_CREDITS_TITLE'] = 'Dankbetuigingen';
$lang['HELP_BROWSERS_TITLE'] = 'Ondersteunde browsers'; 
$lang['HELP_HARDWARE_TITLE'] = 'Ondersteunde hardware'; 
$lang['HELP_DISCLAIMER_TITLE'] = 'Disclaimer'; 
$lang['HELP_DISCLAIMER'] = 'Dit spel wordt zonder enige garantie geleverd. De autheur kan nergens aansprakelijk worden voor gesteld.<br/>';

$lang['HELP_CREDITS_TITLE'] = 'Dankbetuiging';
$lang['HELP_CREDITS'] = 'De volgende mensen en organisatie hebben WarQuest mogelijk gemaakt.';
$lang['HELP_CREDITS_ARCHITECT'] = 'Architect';
$lang['HELP_CREDITS_DEVELOPERS'] = 'Ontwikkelaar';
$lang['HELP_CREDITS_GRAPHICS'] = 'Graphics & Informatie';
$lang['HELP_CREDITS_TRANSLATORS'] = 'Vertalers';
$lang['HELP_CREDITS_TESTERS'] = 'Testers';
$lang['HELP_CREDITS_OTHER'] = 'Overige';
$lang['HELP_CREDITS_OTHER_NOTE'] = 'en natuurlijk de WarQuest spelers voor hun opbouwende reacties zodat het spel verbeterd kon worden. Veel plezier met WarQuest toegewenst!';


/* 
** ------------------
** RANK DATA
** ------------------
*/

$lang['RANK_1']  = "Rekruut";
$lang['RANK_2']  = "Soldaat";
$lang['RANK_3']  = "Specialist";
$lang['RANK_4']  = "Korporaal";
$lang['RANK_5']  = "Sergeant";
$lang['RANK_6']  = "Staf Sergeant";
$lang['RANK_7']  = "Sergeant Eerste Klas";
$lang['RANK_8']  = "4e Sergeant";
$lang['RANK_9']  = "3e Sergeant";
$lang['RANK_10'] = "2e Sergeant";
$lang['RANK_11'] = "1e Sergeant";
$lang['RANK_12'] = "2e Sergeant Majoor";
$lang['RANK_13'] = "Majoor";
$lang['RANK_14'] = "2e Leutenant";
$lang['RANK_15'] = "1e Leutenant";
$lang['RANK_16'] = "Kapitein";
$lang['RANK_17'] = "Leutenant Kolonel";
$lang['RANK_18'] = "Kolonel";
$lang['RANK_19'] = "Brigade Generaal";
$lang['RANK_20'] = "Majoor Generaal";
$lang['RANK_21'] = "Leutenant Generaal";
$lang['RANK_22'] = "Generaal";
$lang['RANK_23'] = "Admiraal";

/*
** ------------------
** COUNTRY NAMES
** ------------------
*/

$landcode = array();

$landcode['ad'] = "Andorra";
$landcode['ae'] = "Arabische Emiraten";
$landcode['af'] = "Afghanistan";
$landcode['ag'] = "Antigua and Barbuda";
$landcode['ai'] = "Anguilla";
$landcode['al'] = "Albani&euml;";
$landcode['am'] = "Armeni&euml;";
$landcode['an'] = "Nederlandse Antillen";
$landcode['ao'] = "Angola";
$landcode['aq'] = "Antarctica";
$landcode['ar'] = "Argentini&euml;";
$landcode['as'] = "Amerikaans Samoa";
$landcode['at'] = "Oostenrijk";
$landcode['au'] = "Australi&euml;";
$landcode['aw'] = "Aruba";
$landcode['az'] = "Azerbeidzjan";

$landcode['ba'] = "Bosni&euml; en Herzegovina";
$landcode['bb'] = "Barbados";
$landcode['bd'] = "Bangladesh";
$landcode['be'] = "Belgi&euml;";
$landcode['bf'] = "Burkina Faso";
$landcode['bg'] = "Bulgarije";
$landcode['bh'] = "Bahrein";
$landcode['bi'] = "Burundi";
$landcode['bj'] = "Benin";
$landcode['bm'] = "Bermuda";
$landcode['bn'] = "Brunei";
$landcode['bo'] = "Bolivia";
$landcode['br'] = "Brazili&euml;";
$landcode['bs'] = "Bahamas";
$landcode['bt'] = "Bhutan";
$landcode['bv'] = "Bouvet";
$landcode['bw'] = "Botswana";
$landcode['by'] = "Wit-Rusland";
$landcode['bz'] = "Belize";

$landcode['ca'] = "Canada";
$landcode['cc'] = "Cocoseilanden";
$landcode['cf'] = "Centraal-Afrikaanse Republiek";
$landcode['cg'] = "Congo";
$landcode['ch'] = "Zwitserland";
$landcode['ci'] = "Ivoorkust";
$landcode['ck'] = "Cookeilanden";
$landcode['cl'] = "Chili";
$landcode['cm'] = "Kameroen";
$landcode['cn'] = "China";
$landcode['co'] = "Columbia";
$landcode['cr'] = "Costa Rica";
$landcode['cs'] = "Servi en Montenegro";
$landcode['cu'] = "Cuba";
$landcode['cv'] = "Kaapverdi&euml;";
$landcode['cx'] = "Christmaseiland";
$landcode['cy'] = "Cyprus";
$landcode['cz'] = "Tsjechi&euml;";

$landcode['de'] = "Duitsland";
$landcode['dj'] = "Djibouti";
$landcode['dk'] = "Denemarken";
$landcode['dm'] = "Dominica";
$landcode['do'] = "Dominicaanse Republiek";
$landcode['dz'] = "Algerij&euml;";

$landcode['ec'] = "Ecuador";
$landcode['ee'] = "Estland";
$landcode['eg'] = "Egypte";
$landcode['eh'] = "Westelijke Sahara";
$landcode['er'] = "Eritrea";
$landcode['es'] = "Spanje";
$landcode['et'] = "Etiopi&euml;";
$landcode['eu'] = "Cyberspace";

$landcode['fi'] = "Finland";
$landcode['fj'] = "Fiji";
$landcode['fk'] = "Falklandeilanden";
$landcode['fm'] = "Micronesia";
$landcode['fo'] = "Faer&ouml;er";
$landcode['fr'] = "Frankrijk";

$landcode['ga'] = "Gabon";
$landcode['gb'] = "Verenigd Koninkrijk";
$landcode['gd'] = "Grenada";
$landcode['ge'] = "Georgi&euml;";
$landcode['gf'] = "Frans-Guyana";
$landcode['gh'] = "Ghana";
$landcode['gi'] = "Gibraltar";
$landcode['gl'] = "Groenland";
$landcode['gm'] = "Gambia";
$landcode['gn'] = "Guinee";
$landcode['gp'] = "Guadeloupe";
$landcode['gq'] = "Equatoriaal-Guinee";
$landcode['gr'] = "Griekenland";
$landcode['gs'] = "Sandwicheilanden";
$landcode['gt'] = "Guatemala";
$landcode['gu'] = "Guam";
$landcode['gw'] = "Guinee-Bissau";
$landcode['gy'] = "Guyana";

$landcode['hk'] = "Hong Kong";
$landcode['hm'] = "McDonaldeilanden";
$landcode['hn'] = "Honduras";
$landcode['hr'] = "Kroati&euml;";
$landcode['ht'] = "Ha&iuml;ti";
$landcode['hu'] = "Hongarije";

$landcode['id'] = "Indonesi&euml;";
$landcode['ie'] = "Ierland";
$landcode['il'] = "Isra&euml;l";
$landcode['in'] = "India";
$landcode['io'] = "Brits Territorium";
$landcode['iq'] = "Irak";
$landcode['ir'] = "Iran";
$landcode['is'] = "IJsland";
$landcode['it'] = "Itali&euml;";
$landcode['jm'] = "Jamaica";
$landcode['jo'] = "Jordani&euml;";
$landcode['jp'] = "Japan";

$landcode['ke'] = "Kenia";
$landcode['kg'] = "Kirgizi&euml;";
$landcode['kh'] = "Cambodja";
$landcode['ki'] = "Kiribati";
$landcode['km'] = "Comoren";
$landcode['kn'] = "Saint Kitts en Nevis";
$landcode['kp'] = "Noord Korea";
$landcode['kr'] = "Zuid Korea";
$landcode['kw'] = "Koeweit";
$landcode['ky'] = "Caymaneilanden";
$landcode['kz'] = "Kazachstan";

$landcode['la'] = "Laos";
$landcode['lb'] = "Libanon";
$landcode['lc'] = "Saint Lucia";
$landcode['li'] = "Liechtenstein";
$landcode['lk'] = "Sri Lanka";
$landcode['lr'] = "Liberia";
$landcode['ls'] = "Lesotho";
$landcode['lt'] = "Litouwen";
$landcode['lu'] = "Luxemburg";
$landcode['lv'] = "Letland";
$landcode['ly'] = "Libi&euml;";

$landcode['ma'] = "Marocco";
$landcode['mc'] = "Monaco";
$landcode['md'] = "Moldavi&euml;";
$landcode['mg'] = "Madagascar";
$landcode['mh'] = "Marshalleilanden";
$landcode['mk'] = "Macedoni&euml;";
$landcode['ml'] = "Mali";
$landcode['mm'] = "Myanmar";
$landcode['mn'] = "Mongoli&euml;";
$landcode['mo'] = "Macau";
$landcode['mp'] = "Noordelijke Marianen";
$landcode['mq'] = "Martinique";
$landcode['mr'] = "Mauritani&euml;";
$landcode['ms'] = "Montserrat";
$landcode['mt'] = "Malta";
$landcode['mu'] = "Mauritius";
$landcode['mv'] = "Maldiven";
$landcode['mw'] = "Malawi";
$landcode['mx'] = "Mexico";
$landcode['my'] = "Maleisi&euml;";
$landcode['mz'] = "Mozambique";

$landcode['na'] = "Namibi&euml;";
$landcode['nc'] = "Nieuw-Caledoni&euml;";
$landcode['ne'] = "Niger";
$landcode['nf'] = "Norfolkeiland";
$landcode['ng'] = "Nigeria";
$landcode['ni'] = "Nicaragua";
$landcode['nl'] = "Nederland";
$landcode['no'] = "Noorwegen";
$landcode['np'] = "Nepal";
$landcode['nr'] = "Nauru";
$landcode['nu'] = "Niue";
$landcode['nz'] = "Nieuw-Zeeland";

$landcode['om'] = "Oman";

$landcode['pa'] = "Panama";
$landcode['pe'] = "Peru";
$landcode['pf'] = "Frans-Polynesi&euml;";
$landcode['pg'] = "Papua Nieuw Guinea";
$landcode['ph'] = "Filippijnen";
$landcode['pk'] = "Pakistan";
$landcode['pl'] = "Polen";
$landcode['pm'] = "Saint-Pierre en Miquelon";
$landcode['pn'] = "Pitcairn";
$landcode['pr'] = "Puerto Rico";
$landcode['ps'] = "Palestijnsgebied";
$landcode['pt'] = "Portugal";
$landcode['pw'] = "Palau";
$landcode['py'] = "Paraguay";

$landcode['qa'] = "Qatar";

$landcode['re'] = "R&eacute;union";
$landcode['ro'] = "Roemeni&euml;";
$landcode['ru'] = "Russische Federatie";
$landcode['rs'] = "Servie";
$landcode['rw'] = "Rwanda";

$landcode['sa'] = "Saoedi-Arabi&euml;";
$landcode['sb'] = "Salomonseilanden";
$landcode['sc'] = "Seychellen";
$landcode['sd'] = "Sudan";
$landcode['se'] = "Zweden";
$landcode['sg'] = "Singapore";
$landcode['sh'] = "Sint-Helena";
$landcode['si'] = "Sloveni&euml;";
$landcode['sj'] = "Jan Mayeneilanden";
$landcode['sk'] = "Slovakije";
$landcode['sl'] = "Sierra Leone";
$landcode['sm'] = "San Marino";
$landcode['sn'] = "Senegal";
$landcode['so'] = "Somali&euml;";
$landcode['sr'] = "Suriname";
$landcode['st'] = "Sao Tome en Principe";
$landcode['sv'] = "El Salvador";
$landcode['sy'] = "Syri&euml;";
$landcode['sz'] = "Swaziland";

$landcode['tc'] = "Turks- en Caicoseilanden";
$landcode['td'] = "Tsjaad";
$landcode['tg'] = "Togo";
$landcode['th'] = "Thailand";
$landcode['tj'] = "Tadzjikistan";
$landcode['tk'] = "Tokelau";
$landcode['tl'] = "Oost-Timor";
$landcode['tm'] = "Turkmenistan";
$landcode['tn'] = "Tunesi&euml;";
$landcode['to'] = "Tonga";
$landcode['tr'] = "Turkije";
$landcode['tt'] = "Trinidad en Tobago";
$landcode['tv'] = "Tuvalu";
$landcode['tw'] = "Taiwan";
$landcode['tz'] = "Tanzania";

$landcode['ua'] = "Oekra&iuml;";
$landcode['ug'] = "Uganda";
$landcode['um'] = "Kleine Pacifische eilanden";
$landcode['us'] = "Verenigde Staten";
$landcode['uy'] = "Uruguay";
$landcode['uz'] = "Oezbekistan";

$landcode['va'] = "Vaticaanstad";
$landcode['vc'] = "Saint Vincent";
$landcode['ve'] = "Venezuela";
$landcode['vg'] = "Britse Maagdeneilanden";
$landcode['vi'] = "Amerikaanse Maagdeneilanden";
$landcode['vn'] = "Vietnam";
$landcode['vu'] = "Vanuatu";

$landcode['wf'] = "Wallis en Futuna";
$landcode['ws'] = "Samoa";

$landcode['ye'] = "Jemen";
$landcode['yt'] = "Mayotte";

$landcode['za'] = "Zuid Afrika";
$landcode['zm'] = "Zambia";
$landcode['zw'] = "Zimbabwe";

/*
** ------------------
** GOLD FEATURES
** ------------------
*/

$lang['GENERAL_GOLD'] = 'goud';
$lang['PLAYER_GOLD'] = 'Goud'; 

/*
** ------------------
** THE END
** ------------------
*/

?>
