package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Bonus generated by hbm2java
 */
@Entity
@Table(name="bonus"
    ,catalog="warquest"
)
public class Bonus  implements java.io.Serializable {


     private BonusId id;

    public Bonus() {
    }

    public Bonus(BonusId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="bonusId", column=@Column(name="bonus_id", nullable=false) ), 
        @AttributeOverride(name="pid", column=@Column(name="pid", nullable=false) ), 
        @AttributeOverride(name="date", column=@Column(name="date", nullable=false, length=19) ) } )
    public BonusId getId() {
        return this.id;
    }
    
    public void setId(BonusId id) {
        this.id = id;
    }




}


