package nl.warquest.database.entity;
// Generated 18-mrt-2014 21:03:36 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BuildingUnitId generated by hbm2java
 */
@Embeddable
public class BuildingUnitId  implements java.io.Serializable {


     private int bid;
     private int uid;

    public BuildingUnitId() {
    }

    public BuildingUnitId(int bid, int uid) {
       this.bid = bid;
       this.uid = uid;
    }
   

    @Column(name="bid", nullable=false)
    public int getBid() {
        return this.bid;
    }
    
    public void setBid(int bid) {
        this.bid = bid;
    }

    @Column(name="uid", nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }




}


