package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clan generated by hbm2java
 */
@Entity
@Table(name="clan"
    ,catalog="warquest"
)
public class Clan  implements java.io.Serializable {


     private Integer cid;
     private String name;
     private Date created;
     private Date lastActivity;
     private int pid;
     private int won;
     private int lost;
     private long money;
     private int attack;
     private int defense;
     private String slogan;
     private int mission;

    public Clan() {
    }

    public Clan(String name, Date created, Date lastActivity, int pid, int won, int lost, long money, int attack, int defense, String slogan, int mission) {
       this.name = name;
       this.created = created;
       this.lastActivity = lastActivity;
       this.pid = pid;
       this.won = won;
       this.lost = lost;
       this.money = money;
       this.attack = attack;
       this.defense = defense;
       this.slogan = slogan;
       this.mission = mission;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="cid", nullable=false)
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    
    @Column(name="name", nullable=false, length=6)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_activity", nullable=false, length=19)
    public Date getLastActivity() {
        return this.lastActivity;
    }
    
    public void setLastActivity(Date lastActivity) {
        this.lastActivity = lastActivity;
    }
    
    @Column(name="pid", nullable=false)
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    
    @Column(name="won", nullable=false)
    public int getWon() {
        return this.won;
    }
    
    public void setWon(int won) {
        this.won = won;
    }
    
    @Column(name="lost", nullable=false)
    public int getLost() {
        return this.lost;
    }
    
    public void setLost(int lost) {
        this.lost = lost;
    }
    
    @Column(name="money", nullable=false)
    public long getMoney() {
        return this.money;
    }
    
    public void setMoney(long money) {
        this.money = money;
    }
    
    @Column(name="attack", nullable=false)
    public int getAttack() {
        return this.attack;
    }
    
    public void setAttack(int attack) {
        this.attack = attack;
    }
    
    @Column(name="defense", nullable=false)
    public int getDefense() {
        return this.defense;
    }
    
    public void setDefense(int defense) {
        this.defense = defense;
    }
    
    @Column(name="slogan", nullable=false, length=200)
    public String getSlogan() {
        return this.slogan;
    }
    
    public void setSlogan(String slogan) {
        this.slogan = slogan;
    }
    
    @Column(name="mission", nullable=false)
    public int getMission() {
        return this.mission;
    }
    
    public void setMission(int mission) {
        this.mission = mission;
    }




}


