package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClanMissionId generated by hbm2java
 */
@Embeddable
public class ClanMissionId  implements java.io.Serializable {


     private int cid;
     private int mid;

    public ClanMissionId() {
    }

    public ClanMissionId(int cid, int mid) {
       this.cid = cid;
       this.mid = mid;
    }
   

    @Column(name="cid", nullable=false)
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }

    @Column(name="mid", nullable=false)
    public int getMid() {
        return this.mid;
    }
    
    public void setMid(int mid) {
        this.mid = mid;
    }




}


