package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name="member"
    ,catalog="warquest"
)
public class Member  implements java.io.Serializable {


     private Integer pid;
     private String username;
     private String password;
     private String email;
     private int emailValid;
     private int notificationComment;
     private int notificationAlliance;
     private Date created;
     private Date lastLogin;
     private Date prevLogin;
     private String ip;
     private String browser;
     private String versie;
     private String platform;
     private int autoLogin;

    public Member() {
    }

    public Member(String username, String password, String email, int emailValid, int notificationComment, int notificationAlliance, Date created, Date lastLogin, Date prevLogin, String ip, String browser, String versie, String platform, int autoLogin) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.emailValid = emailValid;
       this.notificationComment = notificationComment;
       this.notificationAlliance = notificationAlliance;
       this.created = created;
       this.lastLogin = lastLogin;
       this.prevLogin = prevLogin;
       this.ip = ip;
       this.browser = browser;
       this.versie = versie;
       this.platform = platform;
       this.autoLogin = autoLogin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="pid", nullable=false)
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    
    @Column(name="username", nullable=false, length=40)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password", nullable=false, length=65)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="email", nullable=false, length=120)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="email_valid", nullable=false)
    public int getEmailValid() {
        return this.emailValid;
    }
    
    public void setEmailValid(int emailValid) {
        this.emailValid = emailValid;
    }
    
    @Column(name="notification_comment", nullable=false)
    public int getNotificationComment() {
        return this.notificationComment;
    }
    
    public void setNotificationComment(int notificationComment) {
        this.notificationComment = notificationComment;
    }
    
    @Column(name="notification_alliance", nullable=false)
    public int getNotificationAlliance() {
        return this.notificationAlliance;
    }
    
    public void setNotificationAlliance(int notificationAlliance) {
        this.notificationAlliance = notificationAlliance;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_login", nullable=false, length=19)
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="prev_login", nullable=false, length=19)
    public Date getPrevLogin() {
        return this.prevLogin;
    }
    
    public void setPrevLogin(Date prevLogin) {
        this.prevLogin = prevLogin;
    }
    
    @Column(name="ip", nullable=false, length=16)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    
    @Column(name="browser", nullable=false, length=128)
    public String getBrowser() {
        return this.browser;
    }
    
    public void setBrowser(String browser) {
        this.browser = browser;
    }
    
    @Column(name="versie", nullable=false, length=20)
    public String getVersie() {
        return this.versie;
    }
    
    public void setVersie(String versie) {
        this.versie = versie;
    }
    
    @Column(name="platform", nullable=false, length=128)
    public String getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(String platform) {
        this.platform = platform;
    }
    
    @Column(name="auto_login", nullable=false)
    public int getAutoLogin() {
        return this.autoLogin;
    }
    
    public void setAutoLogin(int autoLogin) {
        this.autoLogin = autoLogin;
    }




}


