package nl.warquest.database.entity;
// Generated 18-mrt-2014 21:03:36 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MissionAward generated by hbm2java
 */
@Entity
@Table(name="mission_award"
    ,catalog="warquest"
)
public class MissionAward  implements java.io.Serializable {


     private int id;
     private int won;
     private int ep;

    public MissionAward() {
    }

    public MissionAward(int id, int won, int ep) {
       this.id = id;
       this.won = won;
       this.ep = ep;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="won", nullable=false)
    public int getWon() {
        return this.won;
    }
    
    public void setWon(int won) {
        this.won = won;
    }
    
    @Column(name="ep", nullable=false)
    public int getEp() {
        return this.ep;
    }
    
    public void setEp(int ep) {
        this.ep = ep;
    }




}


