package nl.warquest.database.entity;
// Generated 18-mrt-2014 21:03:36 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlayerUnitId generated by hbm2java
 */
@Embeddable
public class PlayerUnitId  implements java.io.Serializable {


     private int pid;
     private int uid;

    public PlayerUnitId() {
    }

    public PlayerUnitId(int pid, int uid) {
       this.pid = pid;
       this.uid = uid;
    }
   

    @Column(name="pid", nullable=false)
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }

    @Column(name="uid", nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }




}


