package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlayerPlayer generated by hbm2java
 */
@Entity
@Table(name="player_player"
    ,catalog="warquest"
)
public class PlayerPlayer  implements java.io.Serializable {


     private PlayerPlayerId id;
     private int approved;
     private Date inviteDate;

    public PlayerPlayer() {
    }

    public PlayerPlayer(PlayerPlayerId id, int approved, Date inviteDate) {
       this.id = id;
       this.approved = approved;
       this.inviteDate = inviteDate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="pid1", column=@Column(name="pid1", nullable=false) ), 
        @AttributeOverride(name="pid2", column=@Column(name="pid2", nullable=false) ) } )
    public PlayerPlayerId getId() {
        return this.id;
    }
    
    public void setId(PlayerPlayerId id) {
        this.id = id;
    }
    
    @Column(name="approved", nullable=false)
    public int getApproved() {
        return this.approved;
    }
    
    public void setApproved(int approved) {
        this.approved = approved;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="invite_date", nullable=false, length=19)
    public Date getInviteDate() {
        return this.inviteDate;
    }
    
    public void setInviteDate(Date inviteDate) {
        this.inviteDate = inviteDate;
    }




}


