package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PlayerClan generated by hbm2java
 */
@Entity
@Table(name="player_clan"
    ,catalog="warquest"
)
public class PlayerClan  implements java.io.Serializable {


     private PlayerClanId id;

    public PlayerClan() {
    }

    public PlayerClan(PlayerClanId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="pid", column=@Column(name="pid", nullable=false) ), 
        @AttributeOverride(name="cid", column=@Column(name="cid", nullable=false) ), 
        @AttributeOverride(name="joined", column=@Column(name="joined", nullable=false, length=19) ), 
        @AttributeOverride(name="approved", column=@Column(name="approved", nullable=false) ) } )
    public PlayerClanId getId() {
        return this.id;
    }
    
    public void setId(PlayerClanId id) {
        this.id = id;
    }




}


