package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PollAnswer generated by hbm2java
 */
@Entity
@Table(name="poll_answer"
    ,catalog="warquest"
)
public class PollAnswer  implements java.io.Serializable {


     private int answerId;
     private int pollId;
     private String answer;

    public PollAnswer() {
    }

    public PollAnswer(int answerId, int pollId, String answer) {
       this.answerId = answerId;
       this.pollId = pollId;
       this.answer = answer;
    }
   
     @Id 
    
    @Column(name="answer_id", nullable=false)
    public int getAnswerId() {
        return this.answerId;
    }
    
    public void setAnswerId(int answerId) {
        this.answerId = answerId;
    }
    
    @Column(name="poll_id", nullable=false)
    public int getPollId() {
        return this.pollId;
    }
    
    public void setPollId(int pollId) {
        this.pollId = pollId;
    }
    
    @Column(name="answer", nullable=false, length=128)
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


