package nl.warquest.database.entity;
// Generated 18-mrt-2014 21:03:36 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Unit generated by hbm2java
 */
@Entity
@Table(name="unit"
    ,catalog="warquest"
)
public class Unit  implements java.io.Serializable {


     private int uid;
     private int lid;
     private int price;
     private int gold;
     private int attack;
     private int defense;
     private int max;
     private int ugid;
     private int upkeep;

    public Unit() {
    }

    public Unit(int uid, int lid, int price, int gold, int attack, int defense, int max, int ugid, int upkeep) {
       this.uid = uid;
       this.lid = lid;
       this.price = price;
       this.gold = gold;
       this.attack = attack;
       this.defense = defense;
       this.max = max;
       this.ugid = ugid;
       this.upkeep = upkeep;
    }
   
     @Id 
    
    @Column(name="uid", nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    
    @Column(name="lid", nullable=false)
    public int getLid() {
        return this.lid;
    }
    
    public void setLid(int lid) {
        this.lid = lid;
    }
    
    @Column(name="price", nullable=false)
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    
    @Column(name="gold", nullable=false)
    public int getGold() {
        return this.gold;
    }
    
    public void setGold(int gold) {
        this.gold = gold;
    }
    
    @Column(name="attack", nullable=false)
    public int getAttack() {
        return this.attack;
    }
    
    public void setAttack(int attack) {
        this.attack = attack;
    }
    
    @Column(name="defense", nullable=false)
    public int getDefense() {
        return this.defense;
    }
    
    public void setDefense(int defense) {
        this.defense = defense;
    }
    
    @Column(name="max", nullable=false)
    public int getMax() {
        return this.max;
    }
    
    public void setMax(int max) {
        this.max = max;
    }
    
    @Column(name="ugid", nullable=false)
    public int getUgid() {
        return this.ugid;
    }
    
    public void setUgid(int ugid) {
        this.ugid = ugid;
    }
    
    @Column(name="upkeep", nullable=false)
    public int getUpkeep() {
        return this.upkeep;
    }
    
    public void setUpkeep(int upkeep) {
        this.upkeep = upkeep;
    }




}


