package nl.warquest.database;
// Generated 17-mrt-2014 21:30:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Battle generated by hbm2java
 */
@Entity
@Table(name="battle"
    ,catalog="warquest"
)
public class Battle  implements java.io.Serializable {


     private Integer id;
     private int pid1;
     private int pid2;
     private Date date;
     private long money;
     private int health;
     private int experience;
     private int win;
     private int ugid;
     private int bounty;

    public Battle() {
    }

    public Battle(int pid1, int pid2, Date date, long money, int health, int experience, int win, int ugid, int bounty) {
       this.pid1 = pid1;
       this.pid2 = pid2;
       this.date = date;
       this.money = money;
       this.health = health;
       this.experience = experience;
       this.win = win;
       this.ugid = ugid;
       this.bounty = bounty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="pid1", nullable=false)
    public int getPid1() {
        return this.pid1;
    }
    
    public void setPid1(int pid1) {
        this.pid1 = pid1;
    }
    
    @Column(name="pid2", nullable=false)
    public int getPid2() {
        return this.pid2;
    }
    
    public void setPid2(int pid2) {
        this.pid2 = pid2;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="money", nullable=false)
    public long getMoney() {
        return this.money;
    }
    
    public void setMoney(long money) {
        this.money = money;
    }
    
    @Column(name="health", nullable=false)
    public int getHealth() {
        return this.health;
    }
    
    public void setHealth(int health) {
        this.health = health;
    }
    
    @Column(name="experience", nullable=false)
    public int getExperience() {
        return this.experience;
    }
    
    public void setExperience(int experience) {
        this.experience = experience;
    }
    
    @Column(name="win", nullable=false)
    public int getWin() {
        return this.win;
    }
    
    public void setWin(int win) {
        this.win = win;
    }
    
    @Column(name="ugid", nullable=false)
    public int getUgid() {
        return this.ugid;
    }
    
    public void setUgid(int ugid) {
        this.ugid = ugid;
    }
    
    @Column(name="bounty", nullable=false)
    public int getBounty() {
        return this.bounty;
    }
    
    public void setBounty(int bounty) {
        this.bounty = bounty;
    }




}


