package nl.warquest.database;
// Generated 17-mrt-2014 21:30:25 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BuildingGroup generated by hbm2java
 */
@Entity
@Table(name="building_group"
    ,catalog="warquest"
)
public class BuildingGroup  implements java.io.Serializable {


     private int bgid;
     private int planet;
     private int sell;
     private int type;

    public BuildingGroup() {
    }

    public BuildingGroup(int bgid, int planet, int sell, int type) {
       this.bgid = bgid;
       this.planet = planet;
       this.sell = sell;
       this.type = type;
    }
   
     @Id 
    
    @Column(name="bgid", nullable=false)
    public int getBgid() {
        return this.bgid;
    }
    
    public void setBgid(int bgid) {
        this.bgid = bgid;
    }
    
    @Column(name="planet", nullable=false)
    public int getPlanet() {
        return this.planet;
    }
    
    public void setPlanet(int planet) {
        this.planet = planet;
    }
    
    @Column(name="sell", nullable=false)
    public int getSell() {
        return this.sell;
    }
    
    public void setSell(int sell) {
        this.sell = sell;
    }
    
    @Column(name="type", nullable=false)
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }




}


