package nl.warquest.database;
// Generated 17-mrt-2014 21:30:25 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Building generated by hbm2java
 */
@Entity
@Table(name="building"
    ,catalog="warquest"
)
public class Building  implements java.io.Serializable {


     private int bid;
     private long price;
     private int gold;
     private int lid;
     private int income;
     private int defense;
     private int energy;
     private int discount;
     private int maintenance;
     private int max;
     private int bgid;
     private int ugid;

    public Building() {
    }

    public Building(int bid, long price, int gold, int lid, int income, int defense, int energy, int discount, int maintenance, int max, int bgid, int ugid) {
       this.bid = bid;
       this.price = price;
       this.gold = gold;
       this.lid = lid;
       this.income = income;
       this.defense = defense;
       this.energy = energy;
       this.discount = discount;
       this.maintenance = maintenance;
       this.max = max;
       this.bgid = bgid;
       this.ugid = ugid;
    }
   
     @Id 
    
    @Column(name="bid", nullable=false)
    public int getBid() {
        return this.bid;
    }
    
    public void setBid(int bid) {
        this.bid = bid;
    }
    
    @Column(name="price", nullable=false)
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }
    
    @Column(name="gold", nullable=false)
    public int getGold() {
        return this.gold;
    }
    
    public void setGold(int gold) {
        this.gold = gold;
    }
    
    @Column(name="lid", nullable=false)
    public int getLid() {
        return this.lid;
    }
    
    public void setLid(int lid) {
        this.lid = lid;
    }
    
    @Column(name="income", nullable=false)
    public int getIncome() {
        return this.income;
    }
    
    public void setIncome(int income) {
        this.income = income;
    }
    
    @Column(name="defense", nullable=false)
    public int getDefense() {
        return this.defense;
    }
    
    public void setDefense(int defense) {
        this.defense = defense;
    }
    
    @Column(name="energy", nullable=false)
    public int getEnergy() {
        return this.energy;
    }
    
    public void setEnergy(int energy) {
        this.energy = energy;
    }
    
    @Column(name="discount", nullable=false)
    public int getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(int discount) {
        this.discount = discount;
    }
    
    @Column(name="maintenance", nullable=false)
    public int getMaintenance() {
        return this.maintenance;
    }
    
    public void setMaintenance(int maintenance) {
        this.maintenance = maintenance;
    }
    
    @Column(name="max", nullable=false)
    public int getMax() {
        return this.max;
    }
    
    public void setMax(int max) {
        this.max = max;
    }
    
    @Column(name="bgid", nullable=false)
    public int getBgid() {
        return this.bgid;
    }
    
    public void setBgid(int bgid) {
        this.bgid = bgid;
    }
    
    @Column(name="ugid", nullable=false)
    public int getUgid() {
        return this.ugid;
    }
    
    public void setUgid(int ugid) {
        this.ugid = ugid;
    }




}


