package nl.warquest.database;
// Generated 17-mrt-2014 21:30:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Player generated by hbm2java
 */
@Entity
@Table(name="player"
    ,catalog="warquest"
)
public class Player  implements java.io.Serializable {


     private int pid;
     private String name;
     private String twitter;
     private String country;
     private int ammo;
     private Date ammoDate;
     private int ammoStep;
     private int energy;
     private int energyStep;
     private Date energyDate;
     private int health;
     private int healthStep;
     private Date healthDate;
     private long money;
     private long moneyStep;
     private Date moneyDate;
     private int gold;
     private int upkeep;
     private int lid;
     private int wonLevel;
     private int experience;
     private int won;
     private int lost;
     private int mission;
     private int missionLevel;
     private int alliance;
     private int invite;
     private long bank1;
     private long bank2;
     private long bank3;
     private int damageUnits;
     private int damageBuildings;
     private int maintenance;
     private Date lastBattle;
     private int newsNotification;
     private int chatNotification;
     private int commentNotification;
     private int clanNotification;
     private String language;
     private int background;
     private String defaultForce;
     private String defaultMission;
     private int defaultAmount;
     private Date bonusDate;
     private int request;
     private Date requestDate;
     private int ads;
     private int casino;
     private Date restoreHealth;
     private Date restoreEnergy;
     private Date restoreAmmo;
     private Date ceaseFireDate;
     private Date holidayDate;
     private int rebelStatus;
     private int bounty;
     private int bountyLevel;
     private int planet;
     private int rebel;
     private int rebelLevel;
     private String pattern;
     private Date premiumDate;

    public Player() {
    }

    public Player(int pid, String name, String twitter, String country, int ammo, Date ammoDate, int ammoStep, int energy, int energyStep, Date energyDate, int health, int healthStep, Date healthDate, long money, long moneyStep, Date moneyDate, int gold, int upkeep, int lid, int wonLevel, int experience, int won, int lost, int mission, int missionLevel, int alliance, int invite, long bank1, long bank2, long bank3, int damageUnits, int damageBuildings, int maintenance, Date lastBattle, int newsNotification, int chatNotification, int commentNotification, int clanNotification, String language, int background, String defaultForce, String defaultMission, int defaultAmount, Date bonusDate, int request, Date requestDate, int ads, int casino, Date restoreHealth, Date restoreEnergy, Date restoreAmmo, Date ceaseFireDate, Date holidayDate, int rebelStatus, int bounty, int bountyLevel, int planet, int rebel, int rebelLevel, String pattern, Date premiumDate) {
       this.pid = pid;
       this.name = name;
       this.twitter = twitter;
       this.country = country;
       this.ammo = ammo;
       this.ammoDate = ammoDate;
       this.ammoStep = ammoStep;
       this.energy = energy;
       this.energyStep = energyStep;
       this.energyDate = energyDate;
       this.health = health;
       this.healthStep = healthStep;
       this.healthDate = healthDate;
       this.money = money;
       this.moneyStep = moneyStep;
       this.moneyDate = moneyDate;
       this.gold = gold;
       this.upkeep = upkeep;
       this.lid = lid;
       this.wonLevel = wonLevel;
       this.experience = experience;
       this.won = won;
       this.lost = lost;
       this.mission = mission;
       this.missionLevel = missionLevel;
       this.alliance = alliance;
       this.invite = invite;
       this.bank1 = bank1;
       this.bank2 = bank2;
       this.bank3 = bank3;
       this.damageUnits = damageUnits;
       this.damageBuildings = damageBuildings;
       this.maintenance = maintenance;
       this.lastBattle = lastBattle;
       this.newsNotification = newsNotification;
       this.chatNotification = chatNotification;
       this.commentNotification = commentNotification;
       this.clanNotification = clanNotification;
       this.language = language;
       this.background = background;
       this.defaultForce = defaultForce;
       this.defaultMission = defaultMission;
       this.defaultAmount = defaultAmount;
       this.bonusDate = bonusDate;
       this.request = request;
       this.requestDate = requestDate;
       this.ads = ads;
       this.casino = casino;
       this.restoreHealth = restoreHealth;
       this.restoreEnergy = restoreEnergy;
       this.restoreAmmo = restoreAmmo;
       this.ceaseFireDate = ceaseFireDate;
       this.holidayDate = holidayDate;
       this.rebelStatus = rebelStatus;
       this.bounty = bounty;
       this.bountyLevel = bountyLevel;
       this.planet = planet;
       this.rebel = rebel;
       this.rebelLevel = rebelLevel;
       this.pattern = pattern;
       this.premiumDate = premiumDate;
    }
   
     @Id 
    
    @Column(name="pid", nullable=false)
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    
    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="twitter", nullable=false, length=20)
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    
    @Column(name="country", nullable=false, length=5)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="ammo", nullable=false)
    public int getAmmo() {
        return this.ammo;
    }
    
    public void setAmmo(int ammo) {
        this.ammo = ammo;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ammo_date", nullable=false, length=19)
    public Date getAmmoDate() {
        return this.ammoDate;
    }
    
    public void setAmmoDate(Date ammoDate) {
        this.ammoDate = ammoDate;
    }
    
    @Column(name="ammo_step", nullable=false)
    public int getAmmoStep() {
        return this.ammoStep;
    }
    
    public void setAmmoStep(int ammoStep) {
        this.ammoStep = ammoStep;
    }
    
    @Column(name="energy", nullable=false)
    public int getEnergy() {
        return this.energy;
    }
    
    public void setEnergy(int energy) {
        this.energy = energy;
    }
    
    @Column(name="energy_step", nullable=false)
    public int getEnergyStep() {
        return this.energyStep;
    }
    
    public void setEnergyStep(int energyStep) {
        this.energyStep = energyStep;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="energy_date", nullable=false, length=19)
    public Date getEnergyDate() {
        return this.energyDate;
    }
    
    public void setEnergyDate(Date energyDate) {
        this.energyDate = energyDate;
    }
    
    @Column(name="health", nullable=false)
    public int getHealth() {
        return this.health;
    }
    
    public void setHealth(int health) {
        this.health = health;
    }
    
    @Column(name="health_step", nullable=false)
    public int getHealthStep() {
        return this.healthStep;
    }
    
    public void setHealthStep(int healthStep) {
        this.healthStep = healthStep;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="health_date", nullable=false, length=19)
    public Date getHealthDate() {
        return this.healthDate;
    }
    
    public void setHealthDate(Date healthDate) {
        this.healthDate = healthDate;
    }
    
    @Column(name="money", nullable=false)
    public long getMoney() {
        return this.money;
    }
    
    public void setMoney(long money) {
        this.money = money;
    }
    
    @Column(name="money_step", nullable=false)
    public long getMoneyStep() {
        return this.moneyStep;
    }
    
    public void setMoneyStep(long moneyStep) {
        this.moneyStep = moneyStep;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="money_date", nullable=false, length=19)
    public Date getMoneyDate() {
        return this.moneyDate;
    }
    
    public void setMoneyDate(Date moneyDate) {
        this.moneyDate = moneyDate;
    }
    
    @Column(name="gold", nullable=false)
    public int getGold() {
        return this.gold;
    }
    
    public void setGold(int gold) {
        this.gold = gold;
    }
    
    @Column(name="upkeep", nullable=false)
    public int getUpkeep() {
        return this.upkeep;
    }
    
    public void setUpkeep(int upkeep) {
        this.upkeep = upkeep;
    }
    
    @Column(name="lid", nullable=false)
    public int getLid() {
        return this.lid;
    }
    
    public void setLid(int lid) {
        this.lid = lid;
    }
    
    @Column(name="won_level", nullable=false)
    public int getWonLevel() {
        return this.wonLevel;
    }
    
    public void setWonLevel(int wonLevel) {
        this.wonLevel = wonLevel;
    }
    
    @Column(name="experience", nullable=false)
    public int getExperience() {
        return this.experience;
    }
    
    public void setExperience(int experience) {
        this.experience = experience;
    }
    
    @Column(name="won", nullable=false)
    public int getWon() {
        return this.won;
    }
    
    public void setWon(int won) {
        this.won = won;
    }
    
    @Column(name="lost", nullable=false)
    public int getLost() {
        return this.lost;
    }
    
    public void setLost(int lost) {
        this.lost = lost;
    }
    
    @Column(name="mission", nullable=false)
    public int getMission() {
        return this.mission;
    }
    
    public void setMission(int mission) {
        this.mission = mission;
    }
    
    @Column(name="mission_level", nullable=false)
    public int getMissionLevel() {
        return this.missionLevel;
    }
    
    public void setMissionLevel(int missionLevel) {
        this.missionLevel = missionLevel;
    }
    
    @Column(name="alliance", nullable=false)
    public int getAlliance() {
        return this.alliance;
    }
    
    public void setAlliance(int alliance) {
        this.alliance = alliance;
    }
    
    @Column(name="invite", nullable=false)
    public int getInvite() {
        return this.invite;
    }
    
    public void setInvite(int invite) {
        this.invite = invite;
    }
    
    @Column(name="bank1", nullable=false)
    public long getBank1() {
        return this.bank1;
    }
    
    public void setBank1(long bank1) {
        this.bank1 = bank1;
    }
    
    @Column(name="bank2", nullable=false)
    public long getBank2() {
        return this.bank2;
    }
    
    public void setBank2(long bank2) {
        this.bank2 = bank2;
    }
    
    @Column(name="bank3", nullable=false)
    public long getBank3() {
        return this.bank3;
    }
    
    public void setBank3(long bank3) {
        this.bank3 = bank3;
    }
    
    @Column(name="damage_units", nullable=false)
    public int getDamageUnits() {
        return this.damageUnits;
    }
    
    public void setDamageUnits(int damageUnits) {
        this.damageUnits = damageUnits;
    }
    
    @Column(name="damage_buildings", nullable=false)
    public int getDamageBuildings() {
        return this.damageBuildings;
    }
    
    public void setDamageBuildings(int damageBuildings) {
        this.damageBuildings = damageBuildings;
    }
    
    @Column(name="maintenance", nullable=false)
    public int getMaintenance() {
        return this.maintenance;
    }
    
    public void setMaintenance(int maintenance) {
        this.maintenance = maintenance;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_battle", nullable=false, length=19)
    public Date getLastBattle() {
        return this.lastBattle;
    }
    
    public void setLastBattle(Date lastBattle) {
        this.lastBattle = lastBattle;
    }
    
    @Column(name="news_notification", nullable=false)
    public int getNewsNotification() {
        return this.newsNotification;
    }
    
    public void setNewsNotification(int newsNotification) {
        this.newsNotification = newsNotification;
    }
    
    @Column(name="chat_notification", nullable=false)
    public int getChatNotification() {
        return this.chatNotification;
    }
    
    public void setChatNotification(int chatNotification) {
        this.chatNotification = chatNotification;
    }
    
    @Column(name="comment_notification", nullable=false)
    public int getCommentNotification() {
        return this.commentNotification;
    }
    
    public void setCommentNotification(int commentNotification) {
        this.commentNotification = commentNotification;
    }
    
    @Column(name="clan_notification", nullable=false)
    public int getClanNotification() {
        return this.clanNotification;
    }
    
    public void setClanNotification(int clanNotification) {
        this.clanNotification = clanNotification;
    }
    
    @Column(name="language", nullable=false, length=10)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    
    @Column(name="background", nullable=false)
    public int getBackground() {
        return this.background;
    }
    
    public void setBackground(int background) {
        this.background = background;
    }
    
    @Column(name="default_force", nullable=false, length=40)
    public String getDefaultForce() {
        return this.defaultForce;
    }
    
    public void setDefaultForce(String defaultForce) {
        this.defaultForce = defaultForce;
    }
    
    @Column(name="default_mission", nullable=false, length=40)
    public String getDefaultMission() {
        return this.defaultMission;
    }
    
    public void setDefaultMission(String defaultMission) {
        this.defaultMission = defaultMission;
    }
    
    @Column(name="default_amount", nullable=false)
    public int getDefaultAmount() {
        return this.defaultAmount;
    }
    
    public void setDefaultAmount(int defaultAmount) {
        this.defaultAmount = defaultAmount;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="bonus_date", nullable=false, length=19)
    public Date getBonusDate() {
        return this.bonusDate;
    }
    
    public void setBonusDate(Date bonusDate) {
        this.bonusDate = bonusDate;
    }
    
    @Column(name="request", nullable=false)
    public int getRequest() {
        return this.request;
    }
    
    public void setRequest(int request) {
        this.request = request;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="request_date", nullable=false, length=19)
    public Date getRequestDate() {
        return this.requestDate;
    }
    
    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }
    
    @Column(name="ads", nullable=false)
    public int getAds() {
        return this.ads;
    }
    
    public void setAds(int ads) {
        this.ads = ads;
    }
    
    @Column(name="casino", nullable=false)
    public int getCasino() {
        return this.casino;
    }
    
    public void setCasino(int casino) {
        this.casino = casino;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="restore_health", nullable=false, length=19)
    public Date getRestoreHealth() {
        return this.restoreHealth;
    }
    
    public void setRestoreHealth(Date restoreHealth) {
        this.restoreHealth = restoreHealth;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="restore_energy", nullable=false, length=19)
    public Date getRestoreEnergy() {
        return this.restoreEnergy;
    }
    
    public void setRestoreEnergy(Date restoreEnergy) {
        this.restoreEnergy = restoreEnergy;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="restore_ammo", nullable=false, length=19)
    public Date getRestoreAmmo() {
        return this.restoreAmmo;
    }
    
    public void setRestoreAmmo(Date restoreAmmo) {
        this.restoreAmmo = restoreAmmo;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cease_fire_date", nullable=false, length=19)
    public Date getCeaseFireDate() {
        return this.ceaseFireDate;
    }
    
    public void setCeaseFireDate(Date ceaseFireDate) {
        this.ceaseFireDate = ceaseFireDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="holiday_date", nullable=false, length=19)
    public Date getHolidayDate() {
        return this.holidayDate;
    }
    
    public void setHolidayDate(Date holidayDate) {
        this.holidayDate = holidayDate;
    }
    
    @Column(name="rebel_status", nullable=false)
    public int getRebelStatus() {
        return this.rebelStatus;
    }
    
    public void setRebelStatus(int rebelStatus) {
        this.rebelStatus = rebelStatus;
    }
    
    @Column(name="bounty", nullable=false)
    public int getBounty() {
        return this.bounty;
    }
    
    public void setBounty(int bounty) {
        this.bounty = bounty;
    }
    
    @Column(name="bounty_level", nullable=false)
    public int getBountyLevel() {
        return this.bountyLevel;
    }
    
    public void setBountyLevel(int bountyLevel) {
        this.bountyLevel = bountyLevel;
    }
    
    @Column(name="planet", nullable=false)
    public int getPlanet() {
        return this.planet;
    }
    
    public void setPlanet(int planet) {
        this.planet = planet;
    }
    
    @Column(name="rebel", nullable=false)
    public int getRebel() {
        return this.rebel;
    }
    
    public void setRebel(int rebel) {
        this.rebel = rebel;
    }
    
    @Column(name="rebel_level", nullable=false)
    public int getRebelLevel() {
        return this.rebelLevel;
    }
    
    public void setRebelLevel(int rebelLevel) {
        this.rebelLevel = rebelLevel;
    }
    
    @Column(name="pattern", nullable=false, length=16)
    public String getPattern() {
        return this.pattern;
    }
    
    public void setPattern(String pattern) {
        this.pattern = pattern;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="premium_date", nullable=false, length=19)
    public Date getPremiumDate() {
        return this.premiumDate;
    }
    
    public void setPremiumDate(Date premiumDate) {
        this.premiumDate = premiumDate;
    }




}


