package nl.warquest.database;
// Generated 17-mrt-2014 21:30:25 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PlayerBuilding generated by hbm2java
 */
@Entity
@Table(name="player_building"
    ,catalog="warquest"
)
public class PlayerBuilding  implements java.io.Serializable {


     private PlayerBuildingId id;
     private int amount;

    public PlayerBuilding() {
    }

    public PlayerBuilding(PlayerBuildingId id, int amount) {
       this.id = id;
       this.amount = amount;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="pid", column=@Column(name="pid", nullable=false) ), 
        @AttributeOverride(name="bid", column=@Column(name="bid", nullable=false) ) } )
    public PlayerBuildingId getId() {
        return this.id;
    }
    
    public void setId(PlayerBuildingId id) {
        this.id = id;
    }
    
    @Column(name="amount", nullable=false)
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }




}


