package nl.warquest.database;
// Generated 17-mrt-2014 21:30:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlayerClanId generated by hbm2java
 */
@Embeddable
public class PlayerClanId  implements java.io.Serializable {


     private int pid;
     private int cid;
     private Date joined;
     private int approved;

    public PlayerClanId() {
    }

    public PlayerClanId(int pid, int cid, Date joined, int approved) {
       this.pid = pid;
       this.cid = cid;
       this.joined = joined;
       this.approved = approved;
    }
   

    @Column(name="pid", nullable=false)
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }

    @Column(name="cid", nullable=false)
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }

    @Column(name="joined", nullable=false, length=19)
    public Date getJoined() {
        return this.joined;
    }
    
    public void setJoined(Date joined) {
        this.joined = joined;
    }

    @Column(name="approved", nullable=false)
    public int getApproved() {
        return this.approved;
    }
    
    public void setApproved(int approved) {
        this.approved = approved;
    }




}


