package nl.warquest.database;
// Generated 17-mrt-2014 21:30:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Topic generated by hbm2java
 */
@Entity
@Table(name="topic"
    ,catalog="warquest"
)
public class Topic  implements java.io.Serializable {


     private Integer tid;
     private int fid;
     private int pid;
     private String description;
     private Date date;
     private int deleted;

    public Topic() {
    }

    public Topic(int fid, int pid, String description, Date date, int deleted) {
       this.fid = fid;
       this.pid = pid;
       this.description = description;
       this.date = date;
       this.deleted = deleted;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="tid", nullable=false)
    public Integer getTid() {
        return this.tid;
    }
    
    public void setTid(Integer tid) {
        this.tid = tid;
    }
    
    @Column(name="fid", nullable=false)
    public int getFid() {
        return this.fid;
    }
    
    public void setFid(int fid) {
        this.fid = fid;
    }
    
    @Column(name="pid", nullable=false)
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    
    @Column(name="description", nullable=false, length=128)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="deleted", nullable=false)
    public int getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(int deleted) {
        this.deleted = deleted;
    }




}


