<?php

/* 
**  ========
**  WARQUEST
**  ========
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  All copyrights reserved (c) 2008-2014 PlaatSoft
*/

/*
** Some translation remarks:
** (1) Every line has the following syntax $lang['<KEY>'] = '<DESCRIPTION>';
**     Only change the <DESCRIPTION> part. Leave the rest unchanged.
** (2) The <DESCRIPTION> part contain %s tags. DO NOT REMOVE THEN.
**     The %s are realtime replace with game parameters. 
**     For example: 'Restore for %s dollar' will be on screen 'Restore for 100 dollar'
** (3) The LINK keys contain the menu items of the game. Choose as short as possible words.
** (4) Leave HTML tags unchanged, for example <b>, </b>, etc....
**
** Good luck and have fun!
*/

/*
** ------------------
** Language: DEUTSCH
** ------------------
*/
 
/*
** ------------------
** LINKS
** ------------------
*/

/* Login */
$lang['LINK_LOGIN']  = 'Login'; 
$lang['LINK_REGISTER'] = 'Registration'; 
$lang['LINK_RECOVER'] = 'Erholung'; 
$lang['LINK_MANUAL'] = 'Handbuch'; 
$lang['LINK_RSS']  = 'RSS'; 

/* General */
$lang['LINK_HOME'] = 'Home';
$lang['LINK_MISSIONS'] = 'Mission';
$lang['LINK_BATTLE'] = 'Kampf';
$lang['LINK_UNITS']  = 'Einheiten';
$lang['LINK_BUILDINGS']  = 'Gebäude';
$lang['LINK_BANKS'] = 'Bank';
$lang['LINK_PLAYER'] = 'Spieler';
$lang['LINK_MONEY'] = 'Geld';
$lang['LINK_HELP'] = 'Hilfe';
$lang['LINK_ADMIN'] = 'Admin';

$lang['LINK_FIRST']  = 'Anfang';
$lang['LINK_PREVIOUS'] = 'Zurück';
$lang['LINK_NEXT'] = 'Weiter';
$lang['LINK_LAST'] = 'Ende';

/* Home */
$lang['LINK_RESTORE'] = 'Restore';
$lang['LINK_REPAIR'] = 'Reparatur';
$lang['LINK_TRADE'] = 'Trade';
$lang['LINK_ACTIVATE'] = 'Activate';

/* Player */
$lang['LINK_OVERVIEW'] = 'Übersicht';
$lang['LINK_DELETE'] = 'Löschen';
$lang['LINK_SETTINGS'] = 'Einstellung';
$lang['LINK_NEWS'] = 'News';
$lang['LINK_COMMENTS'] = 'Nachrichten';
$lang['LINK_STATISTICS'] = 'Statistik';
$lang['LINK_LOGOUT'] = 'Logout';
$lang['LINK_EDIT'] = 'Edit';
$lang['LINK_SAVE'] = 'Speichern';
$lang['LINK_REPLY'] = 'Reply';
$lang['LINK_PROFILE'] = 'Profil';
$lang['LINK_SKILLS'] = 'Skills';
$lang['LINK_RECRUIT']  = 'Einladen';
$lang['LINK_INCREASE'] = 'Erhöhen';
$lang['LINK_DECREASE'] = 'Erniedrigen';
$lang['LINK_RESTORE_NOW']  = 'Restore for %s dollar';
$lang['LINK_CHANGE'] = 'Ändern';
$lang['LINK_REPORT'] = 'Melden';
$lang['LINK_BOUNTY'] = 'Belohnung';

/* Mission */
$lang['LINK_PLAY'] = 'Angriff';
$lang['LINK_BUY_PLAY'] = 'Kaufen und Angriff';
$lang['LINK_DO_AGAIN'] = 'wieder Angriff';

/* Battle */
$lang['LINK_ATTACK'] = 'Angriff';
$lang['LINK_BATTLES']  = 'Kampf';
$lang['LINK_SP'] = 'Skill Punkte';

/* Unit */
$lang['LINK_DEPLOY'] = 'Entlassen';
$lang['LINK_DEPLOY_AGAIN'] = 'weiter Entlassen';
$lang['LINK_DISBAND']  = 'Disband';
$lang['LINK_DISBAND_AGAIN']= 'Disband Again';

/* Building */
$lang['LINK_INCOME'] = 'Einkommen';
$lang['LINK_DEFENSE'] = 'Verteidigung';
$lang['LINK_ENERGY'] = 'Energie';
$lang['LINK_BUY'] = 'Erwerben';
$lang['LINK_BUY_AGAIN'] = 'Mehr Erwerben';
$lang['LINK_SELL'] = 'Verkaufen';
$lang['LINK_SELL_AGAIN'] = 'Mehr Verkaufen';

/* Bank / Exchange / Casino */
$lang['LINK_BANK'] = 'Bank';
$lang['LINK_STOCKEXCHANGE'] = 'Börse';
$lang['LINK_CASINO'] = 'Kasino';

$lang['LINK_DEPOSIT']  = 'Einzahlen';
$lang['LINK_WITHDRAW'] = 'Abheben';
$lang['LINK_BALANCE']  = 'Kontostand';

/* Alliance */
$lang['LINK_INVITE'] = 'Einladen';
$lang['LINK_PENDING'] = 'Pending';
$lang['LINK_APPROVED'] = 'Akzeptieren';
$lang['LINK_COMMENT']  = 'Nachricht';
$lang['LINK_BEST_PLAYER']  = 'Spieler';
$lang['LINK_BEST_COUNTRY'] = 'Land';
$lang['LINK_DROP'] = 'Ablehnen';
$lang['LINK_ACCEPT'] = 'Akzeptieren';
$lang['LINK_REJECT'] = 'Reject';
$lang['LINK_SEND'] = 'Senden';
$lang['LINK_RESET']  = 'Reset';

/* Forum */
$lang['LINK_FORUM']  = 'Forum';
$lang['LINK_POLLS'] = 'Wahlen';
$lang['LINK_CHATROOM'] = 'Chatroom';
$lang['LINK_SEARCH']  = 'Suchen';

/* Help */
$lang['LINK_GENERAL']  = 'Anleitung';
$lang['LINK_RANKS']  = 'Rank';
$lang['LINK_AWARDS'] = 'Auszeichnung';
$lang['LINK_NOTES']  = 'Release-Notes';
$lang['LINK_STATS']  = 'Statistik';
$lang['LINK_ABOUT']  = 'Über';
$lang['LINK_DONATE']  = 'Spende';

/*
** ------------------
** GENERAL 
** ------------------
*/

$lang['AGO_DAY']   = ' Tag';	
$lang['AGO_DAYS']  = ' Tage';
$lang['AGO_HOUR']  = ' Stunde';
$lang['AGO_HOURS'] = ' Stunden';
$lang['AGO_MIN']   = ' Min';
$lang['AGO_MINS']  = ' Min';
$lang['AGO_SEC']   = ' Sek';
$lang['AGO_SECS']  = ' Sek';
	
$lang['STATUS_CASH']  = 'Geld';
$lang['STATUS_EXP']  = 'Exp.';
$lang['STATUS_LEVEL']  = 'Rang';
$lang['STATUS_HEALTH'] = 'Gesundheit';
$lang['STATUS_ENERGY'] = 'Energie';
$lang['STATUS_AMMO'] = 'Muni';
$lang['STATUS_ALLIANCE_SIZE'] = 'Größe';

$lang['BOX_INFO'] = 'INFO';
$lang['BOX_WARN'] = 'ACHTUNG';
$lang['BOX_ERROR'] = 'ERROR';

$lang['GENERAL_NEXT_LEVEL'] = 'Brilliant! Du erhälst einen neuen Rang! Du erhälst %s skill Punkte und %s Dollar. Deine Gesundheit, Energie und Muni ist vollständig. ';
$lang['GENERAL_BATTLE_LEVEL'] = 'Brilliant! Du warst %s siegreich im Kampf und erhälst dafür %s Extra skill Punkt(e) und %s Dollar.';
$lang['GENERAL_BOUNTY_LEVEL'] = 'Großartig! Du hast %s Belohnung(en) ausgesetzt and erhälst dafür %s Extra Skill Punkte(e) und %s Dollar.';
$lang['GENERAL_REBEL_LEVEL'] = 'Großartig! Du hast die Chance einen Aufstand auszulösen um %s erhöht und erhälst %s Extra Skill Punkte(e) und %s Dollar.';
$lang['GENERAL_BATTLE_AWARD_WON'] = 'gewonnene Kriege';
$lang['GENERAL_BOUNTY_AWARD_WON'] = 'Belohnungen ausgesetzt';
$lang['GENERAL_REBEL_AWARD_WON'] = 'Aufstände ausgelöst';
$lang['GENERAL_UNLOCK'] = 'Freigeschaltet bei Rang %s';
$lang['GENERAL_NEW_FEATURES'] = 'Die folgenden Features sind nun verfügbar:';
$lang['GENERAL_RECEIVED_AWARD'] = 'Auszeichnung erhalten:';

$lang['GENERAL_ATTACK'] = 'Angriff';
$lang['GENERAL_DEFENSE'] = 'Verteidigung';
$lang['GENERAL_INCOME']  = 'Einkommen';
$lang['GENERAL_ENERGY']  = 'Energie';
$lang['GENERAL_EXPERIENCE']  = 'Erfahrung';
$lang['GENERAL_DOLLAR']  = 'Dollar';
$lang['GENERAL_ALLIANCE_SIZE'] = 'Bündnis Größe';
$lang['GENERAL_EXPERIENCE_POINTS'] = 'Erfahrungspunkte';
$lang['GENERAL_UPKEEP'] = 'Stündliche Kosten';
$lang['GENERAL_BANK']  = 'Bank';
$lang['GENERAL_STOCKEXCHANGE']  = 'Stock Exchange';
$lang['GENERAL_DEPLOYED']  = 'Angestellt';

$lang['GENERAL_PLAYER']  = 'Spieler';
$lang['GENERAL_LEVEL'] = 'Rang';
$lang['GENERAL_ALLIANCE']  = 'Bündnis';
$lang['GENERAL_WON'] = 'Sieg';
$lang['GENERAL_LOST']  = 'Niederlage';
$lang['GENERAL_AMOUNT'] = 'Stück';
$lang['GENERAL_DATE'] = 'Datum';
$lang['GENERAL_TRANSACTION'] = 'Transaktion';
$lang['GENERAL_BALANCE'] = 'Kontostand';
$lang['GENERAL_APPROVED'] = 'Approved';
$lang['GENERAL_EMAIL'] = 'Email';
$lang['GENERAL_TOP']	= 'Top';
$lang['GENERAL_EXP'] = 'Erfahrung';
$lang['GENERAL_COUNTRY'] = 'Land';
$lang['GENERAL_PLAYERS'] = 'Spieler';
$lang['GENERAL_WONS']  = 'Siege';
$lang['GENERAL_LOSTS'] = 'Niederlage';
$lang['GENERAL_NO'] = 'Nein';
$lang['GENERAL_YES'] = 'Ja';
$lang['GENERAL_AGO'] = 'Ago';
$lang['GENERAL_MESSAGE'] = 'Nachricht';
$lang['GENERAL_ACTION'] = 'Aktion';
$lang['GENERAL_NUMBER'] = 'Nr.';
$lang['GENERAL_DISCOUNT'] = 'Building discount';
$lang['GENERAL_REQUESTS'] = 'Anfrage';
$lang['GENERAL_EP'] = 'Erfahrungspunkte';
$lang['GENERAL_AWARD'] = 'Belohnung';
$lang['GENERAL_LANGUAGE'] = 'Sprache';

$lang['GENERAL_NEW_UNIT'] = 'NEUE EINHEIT';
$lang['GENERAL_NEW_BUILDING'] = 'NEUES GEBÄUDE';
$lang['GENERAL_NEW_MISSION'] = 'NEUE MISSION';
$lang['GENERAL_GAIN'] = 'verdienen';

$lang['GENERAL_BOUNTY'] = 'Belohnung';
$lang['GENERAL_INTELLIGENCE'] = 'Intelligenz';
$lang['GENERAL_SPIES'] = 'spionieren';
$lang['GENERAL_MAINTENANCE'] = 'Einheiten Zustand';

$lang['GENERAL_CNTRY'] = 'Land';
$lang['GENERAL_TOPICS'] = 'Übersicht'; 
$lang['GENERAL_FORUM'] = 'Forum';
$lang['GENERAL_MESSAGES'] = 'Nachrichten';
$lang['GENERAL_LAST_MESSAGE'] = 'Letzte Nachricht';
$lang['GENERAL_FORUM_MODERATED'] = '(Moderated by %s)';
$lang['GENERAL_NOT_MODERATED'] = '(Not Moderated)';
$lang['GENERAL_BY'] = 'VOR';
$lang['GENERAL_TOPIC'] = 'Übersicht';
$lang['GENERAL_LOCKED'] = 'Verschlossen';
$lang['GENERAL_WORLDMAP'] = 'Welt-Karte';
$lang['GENERAL_PLAATSOFT'] = 'PlaatSoft';
$lang['GENERAL_CONQUER'] = 'Erobere';

$lang['GENERAL_ST'] = '%sst';
$lang['GENERAL_ND'] = '%snd';
$lang['GENERAL_TH'] = '%sth';

$lang['GENERAL_CONTINENT'] = 'Kontinent';
$lang['GENERAL_CONQUERED'] = 'Erobert';

$lang['GENERAL_IDLE'] = 'Idle';
$lang['GENERAL_ACTIVE'] = 'Aktiv';
$lang['GENERAL_INACTIVE'] = 'Inaktiv';

$lang['GENERAL_PLANET_1'] = 'Erde';
$lang['GENERAL_PLANET_2'] = 'Mond';

/*
** ------------------
** LOGIN PAGE
** ------------------
*/

$lang['LOGIN_MEMBER_TITLE'] = 'Member Login';
$lang['LOGIN_REGISTER_TITLE'] = 'Kostenlose Registrierung';
$lang['LOGIN_RECOVER_TITLE'] = 'Passwort vergessen?';
$lang['LOGIN_MANUAL_TITLE'] = 'Handbuch';

$lang['LOGIN_PLAYERS'] = 'Spieler';
$lang['LOGIN_REQUESTS'] = 'Anfragen';
$lang['LOGIN_COUNTRIES'] = 'Länder';
$lang['LOGIN_ONLINE'] = 'Spieler online';

$lang['LOGIN_PASSWORD'] = 'Passwort';
$lang['LOGIN_USERNAME'] = 'Username';
$lang['LOGIN_EMAIL'] = 'Email';
$lang['LOGIN_NICKNAME']  = 'Nickname';

$lang['LOGIN_MAINTENANCE_TITLE'] = 'Server Maintenance';
$lang['LOGIN_MAINTENANCE'] = 'Im Moment ist der Server abgeschaltet. Bitte versuchen Sie es in 5 Minuten nocheinmal.';

$lang['LOGIN_LOGOUT'] = 'Du bist ausgeloggt!'; 
$lang['LOGIN_FAILED'] = 'Falscher Username und/oder Passwort!';
$lang['LOGIN_REGISTER_OK'] = 'User Account %s ist erstellt!';
$lang['LOGIN_PASSWORD_TO_SHORT'] = 'Passwort muss mindestens 6 Zeichen lang sein!';
$lang['LOGIN_USERNAME_TO_SHORT'] = 'Username muss mindestens 4 Zeichen lang sein!';
$lang['LOGIN_USERNAME_EXIST'] = 'Username %s existiert bereits!';
$lang['LOGIN_EMAIL_EXIST'] = 'Email ist schon registriert!';
$lang['LOGIN_NICKNAME_EXIST'] = 'Nickname %s wird schon benutzt!';
$lang['LOGIN_NICKNAME_NEEDED'] = 'Nickname muss eingegeben werden!';
$lang['LOGIN_NEW_PASSWORD_SEND'] = 'Das neue Passwort wurde dir per Mail geschickt!';
$lang['LOGIN_EMAIL_UNKNOWN'] = 'Email ist unbekannt!';
$lang['LOGIN_BEST_VIEWED'] = 'WarQuest ist optimiert für folgende Handys: "Apple iPhone / iPad / iPod, Nokia Smartphones, BlackBerry Smartphones, Android Smartphones" und Internet Browsers: "Microsoft Internet Explorer, Mozilla Firefox, Apple Safari, Opera, Google Chrome". This game is best viewed with browser width set to 500px. ';

$lang['LOGIN_NEW_CLIENT_TITLE'] = 'New WarQuest Client ist verfügbar!';
$lang['LOGIN_NEW_CLIENT'] = 'Sie verwenden einen alten WarQuest Windows client. Bitte besuchen Sie www.plaatsoft.nl um die neueste Version zu erhalten.';

/*
** ------------------
** HOME - OVERVIEW
** ------------------
*/

$lang['HOME_TITLE'] = 'HOME';

$lang['HOME_LASTEST_FORUM_ITEM'] = 'Letzter Forum Post';

$lang['HOME_INTRO_PLAYERS'] = 'Im Moment sind %s Spieler aus %s Ländern aktiv, ';
$lang['HOME_INTRO_FIGHTS'] = '%s Kämpfe wurden ausgetragen und ';
$lang['HOME_INTRO_REQUESTS'] = '%s Serveranfragen wurden beantwortet. ';
		
$lang['HOME_INTRO_TITLE'] = 'Anleitung';
$lang['HOME_INTRO_MISSIONS'] = 'Beginne das Spiel indem du %s ';
$lang['HOME_INTRO_BATTLES'] = 'und kämpfe %s. ';
$lang['HOME_INTRO_UNITS'] = 'Wenn du ausreichend Erfahrung und Geld gesammelt, hast kannst du bessere %s ';
$lang['HOME_INTRO_BUILDINGS'] = ' und %s um mächtiger zu werden. ';

$lang['HOME_NEW_ANDROID_VERSION'] = 'Neue App Version v%s ist im Android Market verfügbar.<br/>Bitte Upgraden!';
$lang['HOME_NEW_WINDOWS_VERSION'] = 'Neuer WarQuest client v%s ist verfügbar!';
$lang['HOME_CLICK_HERE'] = 'hier';
$lang['HOME_CLICK_TEXT'] = 'Klick %s um den Download zu starten.';
$lang['HOME_DAILY_BONUS'] = 'Du hast %s Dollar bei einem feindlichen Stützpunkt gefunden!';

$lang['HOME_WELCOME'] = 'Willkommen %s %s.';
$lang['HOME_LAST_LOGIN'] = 'Letzter Besuch  ist <b>%s</b> her.';
$lang['HOME_AWARDS'] = 'Auszeichnungen';
$lang['HOME_BATTLE_AWARDS_TEXT'] = 'Folgende Auszeichnungen hast du im Kampf verdient:';
$lang['HOME_BOUNTY_AWARDS_TEXT'] = 'Folgende Auszeichnungen hast du für Kopfgelder verdient:';
$lang['HOME_REBEL_AWARDS_TEXT'] = 'Folgende Auszeichnungen hast du für Aufstände verdient:';
$lang['HOME_OVERVIEW_TITLE']= 'Übersicht';
$lang['HOME_MAP_TITLE'] = 'eroberte Kontinente';
$lang['HOME_MAP_NOTE'] = 'Jede Mission muss dreimal absolviert, werden um den Kontinent erfolgreich einzunehmen.';

$lang['HOME_TRAVEL_TO'] = 'Reise zu';

$lang['HOME_INTRO_PLACE1'] = 'Du bist auf dem %s Platz in der allgemeinen Rangliste '; 
$lang['HOME_INTRO_PLACE2'] = 'und auf dem %s Platz auf der <b>%s</b> Rangliste. '; 
$lang['HOME_PLAYERS_ONLINE'] = 'In den letzten 24 Stunden waren %s Spieler online.';


/*
** ------------------
** HOME - PROFILE
** ------------------
*/

$lang['PLAYER_TITLE'] = 'Spieler';
$lang['PLAYER_WIN_LOST_RATE'] = 'Sieg/Niederlage Ratio';
$lang['PLAYER_BUILDINGS'] = 'Gebäude';
$lang['PLAYER_CASH_FLOW'] = 'Cash Flow';
$lang['PLAYER_ALLIANCE_SIZE'] = 'Bündnis Größe';
$lang['PLAYER_EXP_POINTS']  = 'Erfahrungspunkte';
$lang['PLAYER_SERVER_REQUEST']  = 'Server Anfragen';
$lang['PLAYER_MISSION_COMPLETED'] = 'Missionen abgeschlossen';
$lang['PLAYER_DEFENSE_STRENGTH']  = 'Verteidigungswert';
$lang['PLAYER_ATTACK_STRENGTH'] = 'Angriffswert';
$lang['PLAYER_FIGHTS_LOST'] = 'Niederlagen';
$lang['PLAYER_FIGHTS_WON']  = 'Siege';
$lang['PLAYER_BUILDING_INCOME'] = 'Gebäude Einkommen';
$lang['PLAYER_CONTINENT_INCOME'] = 'Kontinent Einkommen';
$lang['PLAYER_BOUNTY_SET'] = 'Belohnungen ausgesetzt';
$lang['PLAYER_REBELLION_RISE'] = 'Aufstände ausgelöst';
$lang['PLAYER_UNIT_COST']  = 'Unit Kosten';
$lang['PLAYER_NETTO_INCOME']  = 'Netto Einkommen';
$lang['PLAYER_STATISTICS']  = 'Statistik'; 
$lang['PLAYER_DISCOUNT_MAINTENANCE']  = 'Rabatt & Zustand';
$lang['PLAYER_NAME']  = 'Name'; 
$lang['PLAYER_ID']  = 'Id';
$lang['PLAYER_RANK']  = 'Rang'; 
$lang['PLAYER_OVERVIEW']  = 'Profil'; 
$lang['PLAYER_DISCOUNT_RATE'] = 'Gebäude Rabatt';
$lang['PLAYER_MAINTENANCE_RATE'] = 'Einheiten Zustand';
$lang['PLAYER_LAST_LOGIN'] = 'Zuletzt aktiv (Vor)';
$lang['PLAYER_CREATED'] = 'Erstellt (Vor)';
$lang['PLAYER_CASINO_PLAYED']  = 'Kasino besucht';
$lang['PLAYER_ADS_SHOWED']  = 'Werbung erhalten';


$lang['PLAYER_ATTACK_FORCE'] = 'Übersicht (Angriff %s)';
$lang['PLAYER_DEFENSE_FORCE'] = 'Übersicht (Verteidigung %s)';
$lang['PLAYER_ATTACK_TEXT'] = '%s hat momentan <b>%s</b> Verbündete und kann eine maximale Armeegröße von <b>%s</b> Einheiten befehligen. Der Angriffswert von %s errechnet sich aus folgenden Einheiten:';
$lang['PLAYER_DEFENSE_TEXT'] = '%s hat mometan <b>%s</b> Verbündete und kann eine maximale Armeegröße von <b>%s</b> Einheiten befehligen. Der Verteidigungswert von %s errechnet sich aus folgenden Einheiten:';
$lang['PLAYER_UNIT'] = 'Einheit';
$lang['PLAYER_AMOUNT'] = 'Anzahl';
$lang['PLAYER_STRENGTH'] = 'Stärke';
$lang['PLAYER_ATTACK_SKILLS'] = 'Spieler Angriffswert';
$lang['PLAYER_DEFENSE_SKILLS'] = 'Spieler Verteidigungswert';
$lang['PLAYER_SUB_TOTAL'] = 'Sub total';
$lang['PLAYER_TOTAL'] = 'Total';
$lang['PLAYER_FORCE'] = 'Angriffs & Verteidigungsstärke'; 
$lang['PLAYER_DEPLOYED'] = 'Beschäftigt';

$lang['PLAYER_BUILDING'] = 'Gebäude';
$lang['PLAYER_INCOME'] = 'Einkommen';
$lang['PLAYER_COST'] = 'Kosten';
$lang['PLAYER_BUILDING_OVERVIEW'] = 'Gebäude Einkommen Übersicht';
$lang['PLAYER_BUILDING_TEXT'] = 'SPieler %s hat ein momentaniges Einkommen durch Gebäude in Höhe von %s:';
$lang['PLAYER_UNIT_COST_OVERVIEW'] = 'Stündliche Kosten Übersicht';
$lang['PLAYER_UNIT_COST_TEXT'] = 'Spieler %s besitzt im Moment folgende %s Einheit(en):';
$lang['PLAYER_CONTINENT_OVERVIEW'] = 'Kontinent Einkommen Übersicht';
$lang['PLAYER_CONTINENT_TEXT'] = 'Spieler %s eroberte folgende %s Kontinent(e):';

$lang['PLAYER_SPY_1'] = 'Spionage';
$lang['PLAYER_SPY_2'] = 'Kundschafter';
$lang['PLAYER_SPY_3'] = 'Kundschafter';
$lang['PLAYER_ESPIONAGE_UNLOCK1'] = 'Freigeschaltet wenn deine %s Stärke um %s% höher ist als beim Gegner.';
$lang['PLAYER_ESPIONAGE_UNLOCK2'] = 'Freigeschaltet wenn deine %s Stärke gleich oder höher als beim Gegner.';

$lang['PLAYER_MONEY_STATUS'] = 'Current Assets';
$lang['PLAYER_CASH_MONEY'] = 'Geld';
$lang['PLAYER_BANK'] = 'Bank';

$lang['PLAYER_PLATFORM_BROWSER'] = 'Platform & Browser';
$lang['PLAYER_BROWSER'] = 'Browser';
$lang['PLAYER_BROWSER_VERSION'] = 'Version';
$lang['PLAYER_PLATFORM'] = 'Platform';

$lang['PLAYER_LAST_TWEET'] = 'Letzte Meldung';

/*
** ------------------
** HOME - NEWS
** ------------------
*/

$lang['HOME_BATTLE_TITLE'] = 'Neuigkeiten';
$lang['HOME_BATTLE_ATTACK_BY'] = 'You were attacked by the %s of %s.';
$lang['HOME_BATTLE_YOU_WON'] = 'Du hast <b>GEWONNEN</b>. ';
$lang['HOME_BATTLE_YOU_LOST'] = 'Du hast <b>VERLOREN</b>. ';
$lang['HOME_BATTLE_YOU_EXP'] = 'Du erhälst %s Erfahrung ';
$lang['HOME_BATTLE_TOOK_DAMAGE'] = 'und teilst %s Schaden aus.';
$lang['HOME_BATTLE_TAKING_DAMAGE'] = 'und erleidest %s Punkte Schaden.';
$lang['HOME_BATTLE_YOU_MONEY'] = 'Verlierst %s dollar ';
$lang['HOME_BATTLE_NO_NEWS'] = 'No battle news available on this moment!'; 

$lang['HOME_BOUNTY_NEWS'] = '%s hat ein Kopfgeld von %s Dollar auf dich gesetzt . Wenn du besiegt wirst, verlierst du %s Erfahrungspunkte.';

/*
** ------------------
** HOME - MESSAGE
** ------------------
*/

$lang['HOME_COMMENTS_TITLE']= 'Nachricht';
$lang['HOME_COMMENT_DELETED'] = 'Nachricht gelöscht!';
$lang['HOME_NO_COMMENTS'] = 'Keine Nachrichten von Spielern verfügbar!'; 

/*
** ------------------
** HOME - SKILLS
** ------------------
*/

$lang['PLAYER_SKILL_SUBTITLE1']  = 'Skill Punkte';
$lang['PLAYER_SKILL_SUBTITLE2']  = 'Skill Punkte [%s verfügbar]';
$lang['PLAYER_SKILL_NOTE']  = 'Tipp : Verteile Skillpunkte um deinen Angriffs-, verteidigungs-, Gesunheits- und Energiewert zusteigern oder dein Munitionsdepot zu erhöhen.';
$lang['PLAYER_SKILLS']  = 'Skills'; 
$lang['PLAYER_CURRENT'] = 'Current'; 
$lang['PLAYER_ATTACK']  = 'ANGRIFF';
$lang['PLAYER_DEFENSE'] = 'VERTEIDIGUNG';
$lang['PLAYER_HEALTH']  = 'GESUNDHEIT'; 
$lang['PLAYER_ENERGY']  = 'ENERGIE'; 
$lang['PLAYER_AMMO']  = 'MUNITION'; 
$lang['PLAYER_ATTACK_TIP']  = 'Erhöhe deinen Angriffswert um mehr Schaden und mehr Kriege zu gewinnen. Es koste 1 Skillpunkt um deinen Angriffswert um  %s zu erhöhen. Deinen Angriffswert wird auf %s reduziert um einen 1 Skillpunkt wiederzuerlangen.';
$lang['PLAYER_DEFENSE_TIP'] = 'Erhöhe deinen Verteidigungswert um größeren Angriffen standzuhalten. Es kostet 1 Skillpunkt um deinen Verteidigungswert um %s zu erhöhen. Deinen Verteidigungswert wird auf %s reduziert um einen 1 Skillpunkt wiederzuerlangen.';
$lang['PLAYER_HEALTH_TIP']  = 'Erhöhe deine Gesundheit um länger bei intensive Gefechten am Leben zu bleiben. Es kostet 1 Skillpunkt um deine maximale Gesundheit um 10 zu erhöhen. Dein Gesundheitswert wird um 20 reduziert um 1 Skillpunkt wiederzuerlangen.';
$lang['PLAYER_ENERGY_TIP']  = 'Erhöhe deinen maximale Energie um mehr Missionen zu auszuführen. Es kostet 1 Skillpunkt um deine maximale Energie um 10 zu erhöhen. Reduziere dein Energie-Niveau um 20 um 1 Skillpunkt wiederzuerlangen.';
$lang['PLAYER_AMMO_TIP']  = 'Erhöhe dein Munitionsdepot um mehr Angriffe gegen Spieler auszüben. Es kostet 2 Skillpunkte um dein Munitionsdepot um 1 zu erhöhen. Reduziere dein Munitionsdepot um 1 um 1 Skillpunkt wiederzuerlangen.';
$lang['PLAYER_SKILL_ACCEPTED1']  = '%s s Wert erhöht.';
$lang['PLAYER_SKILL_REJECTED1']  = 'Du benötigst %s Skillpunkt(e) um den Wert zu ändern.';
$lang['PLAYER_SKILL_ACCEPTED2']  = '%s s Wert reduziert.';
$lang['PLAYER_SKILL_REJECTED2']  = '%s s Wert ist auf der kleinsten Stufe.';

/*
** ------------------
** HOME - RESTORE
** ------------------
*/

$lang['RESTORE_TITLE'] = 'Wiederherstellen & Reparieren';
$lang['RESTORE_LOCKED'] = 'Wiederherstellen & Reparieren ist freigeschaltet ab Level %s.';
$lang['PLAYER_RESTORE_PRICE'] = 'Wiederherstellungspreis';
$lang['PLAYER_REPAIR_PRICE'] = 'Reperaturkosten';
$lang['PLAYER_RESTORED_FAILED'] = 'Nicht genug Geld!';

$lang['PLAYER_HEALTH_TITLE'] = 'Gesundheit wiederherstellen';
$lang['PLAYER_HEALTH_NOTE'] = 'Bezahle den Krankenhausaufenthalt für deine Soldaten damit ihre Gesundheit zurückkehrt. Eine Behandlung kann nur jede 5 Minuten erfolgen. Der Heilungsprozess findet auch unabhängig vom Krankenhaus statt.';	
$lang['PLAYER_HEALTH_CONDITION'] = 'Gesundheitszustand';
$lang['PLAYER_HEALTH_RESTORED'] = 'Gesundheit wiederherstellen für %s Dollar.';
$lang['PLAYER_HEALTH_CONFIRM'] = 'Möchtest du wirklich das Krankenhaus aufsuchen?';

$lang['PLAYER_ENERGY_TITLE'] = 'Restore Energy';
$lang['PLAYER_ENERGY_NOTE'] = 'Kaufe Benzin um die Energievorräte deiner Amee aufzufüllen. Die Wiederherstellung kann nur alle 24-Stunden erfolgen. Die Energieleiste füllt sich auch selbstständig mit der Zeit. ';	
$lang['PLAYER_ENERGY_CONDITION'] = 'Energiezustand';
$lang['PLAYER_ENERGY_RESTORED'] = 'Energie wieder herstellen f+r %s Dollar.';
$lang['PLAYER_ENERGY_CONFIRM'] = 'Möchtest du wirklich Benzin kaufen?';

$lang['PLAYER_AMMO_TITLE'] = 'Munitions auffüllen';
$lang['PLAYER_AMMO_NOTE'] = 'Bezahle einen großen Waffenhändler um sofort Munition zu erhalten. Der Waffenhändler kann nur alle 24 Stunden ausliefern. Deine Fabriken fertigen auch unabhängig vom Händler.';	
$lang['PLAYER_AMMO_CONDITION'] = 'Munition';
$lang['PLAYER_AMMO_RESTORED'] = 'Munition auffüllen für %s Dollar.';
$lang['PLAYER_AMMO_CONFIRM'] = 'Möchtest du wirklich dein Depot auffüllen lassen?';

$lang['PLAYER_CEASE_FIRE_TITLE'] = 'Waffenruhe';
$lang['PLAYER_CEASE_FIRE_NOTE'] = 'Bezahle Schutzgeld für 8 Stündige Feuerpause. Während dieser Zeit ist es anderen Spielern nicht möglich dich anzugreifen, jedoch gilt dieses Abkommen auch für dich.';	
$lang['PLAYER_CEASE_FIRE_ACTIVATED'] = 'Abkommen für Waffenruhe kaufen für %s Dollar.';
$lang['PLAYER_CEASE_FIRE_CONFIRM'] = 'Möchtest du wirklich das Abkommen abzeichnen?';

$lang['PLAYER_UNITS_TITLE'] = 'Werkstatt';
$lang['PLAYER_UNITS_NOTE'] = 'Lass deine Einheiten reparieren. Wenn der Zustand bei 0% ist werden manche Einheiten zerstört and the remaining units are automaticly repaired.';	
$lang['PLAYER_UNITS_CONDITION'] = 'Einheiten Zustand(UC)';
$lang['PLAYER_UNITS_REPAIRED'] = 'Einheiten reparieren für %s Dollar.';
$lang['PLAYER_UNITS_CONFIRM'] = 'Möchtest du wirklich deine Einheiten reparieren lassen?';

$lang['PLAYER_BUILDINGS_TITLE'] = 'Gebäude Restauration';
$lang['PLAYER_BUILDINGS_NOTE'] = 'Restauriere deine Gebäude um sie vor dem Verfall zu retten. Wenn der Wert auf 0% sinkt werden einige Gebäude zerstört und die übrigen Gebäude renoviert.';	
$lang['PLAYER_BUILDINGS_CONDITION'] = 'Gebäude Zustand (BC)';
$lang['PLAYER_BUILDINGS_REPAIRED'] = 'Gebäude restaurieren für %s Dollar.';
$lang['PLAYER_BUILDINGS_CONFIRM'] = 'Möchtest du wirklich deine Gebäude restaurieren?';

$lang['PLAYER_REBELLION_TITLE'] = 'Aufstand vermeiden';
$lang['PLAYER_REBELLION_NOTE'] = 'Besteche die Anführer der Rebellen um sie zu besänftigen. Sollte der Wert bei 100% liegen ist ein Aufstand unausweichlich und einige Regionen müssen erneut erobert werden.';	
$lang['PLAYER_REBELLION_CONDITION'] = 'Rebellen im Volk (RC)';
$lang['PLAYER_REBELLION_RESTORED'] = 'Rebellen bestechen für %s Dollar.';
$lang['PLAYER_REBELLION_CONFIRM'] = 'Möchtest du wirklich die Rebellen bestechen?';

/*
** ------------------
** HOME - SETTINGS
** ------------------
*/

$lang['SETTING_TITLE'] = 'Einstellung';
$lang['SETTING_GENERAL1'] = 'Grundeinstellungen 1';
$lang['SETTING_GENERAL2'] = 'Grundeinstelungen 2';

$lang['SETTING_NICKNAME'] = 'WarQuest Nickname';
$lang['SETTING_TWITTER'] = 'Twitter Account';
$lang['SETTING_LANGUAGE'] = 'Sprache';
$lang['SETTING_BACKGROUND'] = "Hintergrund";
$lang['SETTING_SOUND'] = 'Sound aktivieren (Experimental)';
$lang['SETTING_BOUNTY'] = 'Kopfgeld Bestätigung aktivieren';
$lang['SETTING_RESTORE'] = 'Wiederherstellen & Reparatur Bestätigung aktivieren';
$lang['SETTING_CONDITION'] = 'Zustand von Einheiten/Gebäuden/Aufstand in einem Banner aktivieren';
$lang['SETTING_FORUM_SORT'] = 'Letzten Eintrag vom Forum auf der Start-Seite aktivieren';
$lang['SETTING_SORT1'] = 'Die neuesten Nachrichten oben im forum';
$lang['SETTING_SORT2'] = 'Älteste Spieler nach oben in der Kampf-Liste';

$lang['PLAYER_LANG_ENGLISH'] = 'Englisch';
$lang['PLAYER_LANG_DUTCH'] = 'Holländisch';
$lang['PLAYER_LANG_GERMAN'] = 'German';
$lang['PLAYER_LANG_ITALIAN'] = 'Italian';

$lang['BACKGROUND_0'] = 'schwarz';
$lang['BACKGROUND_1'] = 'Armee Grün';
$lang['BACKGROUND_2'] = 'Tranparent';
$lang['BACKGROUND_3'] = 'Rote Aura';
$lang['BACKGROUND_4'] = 'Blaue Seide';
$lang['BACKGROUND_5'] = 'Pirat';
$lang['BACKGROUND_6'] = 'Klassich';
$lang['BACKGROUND_7'] = 'Weihnachten';
$lang['BACKGROUND_8'] = 'Feuerwerk';

$lang['PLAYER_GENERAL_CHANGED'] = 'Grundeinstellungen geändert!';
$lang['NICKNAME_EXIST'] = 'Nickname ist schon gewählt!';
$lang['NICKNAME_TO_SHORT'] = 'Nickname muss mindestens 4 Zeichen lang sein!';
$lang['NICKNAME_NO_SPACE'] = 'Space character(s) in nickname is not allowed!';

$lang['PLAYER_CHANGE_EMAIL'] = 'Email Einstellungen';
$lang['PLAYER_NEW_EMAIL'] = 'Email Addresse';
$lang['PLAYER_NOTIFICATION_ALLIANCE'] = 'Bündnisanfragen per mail';
$lang['PLAYER_NOTIFICATION_COMMENT'] = 'Nachrichteneingang per mail';
$lang['PLAYER_EMAIL_CHANGED'] = 'Email Einstellung geändert';
$lang['PLAYER_EMAIL_EXIST'] = 'Email Adresse ist bereits registriert!';
$lang['EMAIL_INVALID'] = 'Email Adresse ist nicht gültig (Falsche Schreibweise)!';

$lang['PLAYER_LOGIN_SETTINGS'] = 'Login Einstellungen';
$lang['PLAYER_USERNAME'] = 'Username';
$lang['PLAYER_USERNAME_TO_SHORT'] = 'Username muss mindestens 4 Zeichen lang sein!';
$lang['PLAYER_USERNAME_ALREADY_EXIST'] = 'Username existiert bereits!';
$lang['PLAYER_USERNAME_CHANGED'] = 'Username ist geändert. Vergiß nicht deinen Username in der WarQuest Android und/oder Windows app zu ändern, ansonsten funktioniert der automatische LogIn nicht mehr!';
$lang['PLAYER_CURRENT_PASSWORD'] = 'Bisheriges Passwort';		
$lang['PLAYER_NEW_PASSWORD'] = 'Neues Passwort';
$lang['PLAYER_PASSWORD_CHANGED'] = 'Passwort geändert. Vergiß nicht dein Passwort in der WarQuest Android und/oder Windows app zu ändern, ansonsten funktioniert der automatische LogIn nicht mehr!';
$lang['PLAYER_PASSWORD_NO_MATCH'] = 'Das jetztige Passwort stimmt nicht überein!';
$lang['PLAYER_PASSWORD_TO_SHORT'] = 'Das neue Passwort muss mindestens 6 Zeichen lang sein!';
$lang['PLAYER_LOGIN_NOTE'] = 'ACHTUNG: Der automatische Login während des Starts funktioniert nur wenn der Username und das Passwort eingestellt ist in der WarQuest Android und/oder Windows app!'; 

/*
** ------------------
** MISSION DATA
** ------------------
*/

$lang['MISSION_0'] = 'Trainings Mission';

$lang['MISSION_1'] = 'Groß-Britannien';
$lang['MISSION_2'] = 'Luxemburg';
$lang['MISSION_3'] = 'Frankreich';
$lang['MISSION_4'] = 'Zentral Europa';
$lang['MISSION_5'] = 'Skandinavien';
$lang['MISSION_6'] = 'Ost Europa';
$lang['MISSION_7'] = 'Spanien';
$lang['MISSION_8'] = 'Süd Europa';

$lang['MISSION_10'] = 'Grönland';
$lang['MISSION_11'] = 'Kanada';
$lang['MISSION_12'] = 'USA';
$lang['MISSION_13'] = 'Mexiko';
$lang['MISSION_14'] = 'Guatemala Region';
$lang['MISSION_15'] = 'Nicaragua Region';
$lang['MISSION_16'] = 'Kuba Region';
$lang['MISSION_17'] = 'Karibik Region';

$lang['MISSION_20'] = 'Mittel Amerika';
$lang['MISSION_21'] = 'Equador';
$lang['MISSION_22'] = 'Bolivien';
$lang['MISSION_23'] = 'Paraguay';
$lang['MISSION_24'] = 'Chile Region';
$lang['MISSION_25'] = 'Argentinien';
$lang['MISSION_26'] = 'Uruguay';
$lang['MISSION_27'] = 'Brasilien';

$lang['MISSION_30'] = 'Algerien';
$lang['MISSION_31'] = 'Ägypten';
$lang['MISSION_32'] = 'West Afrika';
$lang['MISSION_33'] = 'Zentral Africa';
$lang['MISSION_34'] = 'Ost Afrika';
$lang['MISSION_35'] = 'Mozambique Region';
$lang['MISSION_36'] = 'Zimbabwe Region';
$lang['MISSION_37'] = 'Süd Afrika';

$lang['MISSION_40'] = 'Russland';
$lang['MISSION_41'] = 'Mongolei';
$lang['MISSION_42'] = 'Kasachstan';
$lang['MISSION_43'] = 'Uzbekistan';
$lang['MISSION_44'] = 'Tajikistan';
$lang['MISSION_45'] = 'Turkmenistan';
$lang['MISSION_46'] = 'Georgien';
$lang['MISSION_47'] = 'Armenien';

$lang['MISSION_50'] = 'Iran';
$lang['MISSION_51'] = 'Afghanistan';
$lang['MISSION_52'] = 'Pakistan';
$lang['MISSION_53'] = 'Indien';
$lang['MISSION_54'] = 'Nepal';
$lang['MISSION_55'] = 'Bangladesh';
$lang['MISSION_56'] = 'Thailand';
$lang['MISSION_57'] = 'Laos';

$lang['MISSION_60'] = 'China';
$lang['MISSION_61'] = 'Nord Korea';
$lang['MISSION_62'] = 'Süd Korea';
$lang['MISSION_63'] = 'Japan';
$lang['MISSION_64'] = 'Taiwan';
$lang['MISSION_65'] = 'Kambotscha';
$lang['MISSION_66'] = 'Vietnam';
$lang['MISSION_67'] = 'Malaysia';

$lang['MISSION_70'] = 'West Indonesien';
$lang['MISSION_71'] = 'Ost Indonesien';
$lang['MISSION_72'] = 'Philippin';
$lang['MISSION_73'] = 'Papua New Guinea';
$lang['MISSION_74'] = 'Timor';
$lang['MISSION_75'] = 'Nord Australien';
$lang['MISSION_76'] = 'Süd Australien';
$lang['MISSION_77'] = 'Neuseeland';

$lang['MISSION_80'] = 'Syria';
$lang['MISSION_81'] = 'Irak';
$lang['MISSION_82'] = 'Saudi Arabien';
$lang['MISSION_83'] = 'Kuwait';
$lang['MISSION_84'] = 'Yemen';
$lang['MISSION_85'] = 'Oman';
$lang['MISSION_86'] = 'Jordan';
$lang['MISSION_87'] = 'Israel';

/*
** ------------------
** MISSION PAGE
** ------------------
*/

$lang['MISSION_TITLE'] = 'MISSIONS';
$lang['MISSION_NOTE'] = 'Tipp: Spiele Missionen um Erfahrungspunkte und Geld zu erhalten. Bei Abschluß einer Mission mit 100% bekommst du doppelt soviel Geld. Wenn du alles zu 100% erobert hast gehört dir der Kontinent %s und dein stündliches Einkommen wird um %s Dollar gesteigert.';

$lang['MISSION_ALLIANCE_SIZE'] = 'Verbündete';
$lang['MISSION_GAIN'] = 'Verdien';
$lang['MISSION_PART'] = 'Part';
$lang['MISSION_REQUIRED'] = 'Benötigt';
$lang['MISSION_UNLOCK'] = 'Freigeschaltet ab dem Level %s';
$lang['MISSION_CHANCE_LOOT'] = 'Chance Gegenstand zu erhalten';

$lang['MISSION_YOU_USED'] = 'Du benutztest';
$lang['MISSION_YOU_GAIN'] = 'Du verdientest';
$lang['MISSION_DOLLAR_AND'] = ' Dollar und ';
$lang['MISSION_ABORTED'] = 'Mission abgebrochen!';
$lang['MISSION_NO_ENERGY'] = 'Du hast nicht ausreichend Energie um die Mission abzuschließen. Warte einige Minuten damit sich deine Energie sich wieder füllt.';
$lang['MISSION_LOW_ALLIANCE'] = 'Deine Bündnis Größe ist nicht ausreichend um diese Mission zu beginnen.';
$lang['MISSION_MISSING_UNITS'] = 'Du besitzt nicht die nötige Anzahl an Einheiten um diese Mission zu schaffen. Fehlende Einheit(en): ';
$lang['MISSION_MISSING_UNITS_PRICE'] = 'Gesamtsumme um die EInheit(en) zu kaufen liegt bei %s Dollar. Die stündlichen Kosten betragen %s Dollars.';
$lang['MISSION_UNITS_LOST'] = 'Während der Mission sind folgende Einheit(en) gefallen';
$lang['MISSION_LOOT_WON'] = 'Du hast folgenden Einheit gewonnen';
$lang['MISSION_UNLOCKED'] = 'Nun setze dein Kampf-Training weiter fort.';

$lang['MISSION_CONTINTENT_READY1'] = 'Brilliant! Du hast erfolgreich den Teil %s von %s in dem Kontinent %s! ';
$lang['MISSION_CONTINTENT_READY2'] = 'Du erhälst %s Extra Skillpunkte. ';
$lang['MISSION_CONTINTENT_READY3'] = 'Du hast alle Teile absolviert und erfolgreich erobert. Bereite dich auf den nächsten Kontinent vor!';
$lang['MISSION_CONTINTENT_READY4'] = 'Mache weiter mit dem Teil %s auf dem Kontinent!';
$lang['MISSION_COMPLETE_TEXT'] = 'Du hast folgende Kontinente bis jetzt erobert!';

$lang['MISSION_REBEL'] = 'Rebellion';

/*
** ------------------
** BATTLE PAGE
** ------------------
*/

$lang['BATTLE_TITLE'] = 'Kampf';
$lang['BATTLE_GENERAL_TITLE'] = 'Kampf';
$lang['BATTLE_BOUNTY_TITLE'] = 'Kopfgeld';

$lang['BATTLE_LOST'] =  'Your %s attacked %s. You lost the Battle, taking %s damage, while dealing %s to %s.';
$lang['BATTLE_WON'] = 'Your %s attacked %s. You won the battle, taking %s damage while dealing %s to %s. You took %s dollar and gain %s experience point.';
$lang['BATTLE_DEFENDER_HEALTH_LOW'] = '%s ist vorrübergehend außer Gefecht gesetzt weil seine Lebenspunkte zu niedrig sind für einen weiteren Kampf!';
$lang['BATTLE_ATTACKER_HEALTH_LOW'] = 'Deine Gesundheit ist zu niedrig für den Kampf!. Besuche ein Krankenhaus um deine Reserven wieder aufzufüllen oder warte einen Augenblick.';
$lang['BATTLE_AMMO_LOW'] = 'You are out of ammo! Wait a few minutes for your ammo to recharge or deploy skill points to improve ammo skill.';
$lang['BATTLE_UNITS_LOST'] = 'Während des Kampfes ist/sind folgende Einheit/en gefallen:';
$lang['BATTLE_BUILDINGS_LOST'] = 'Während des Kampfes wurde folgende(s) Gebäude zerstört:';

$lang['BATTLE_NOTE1'] = 'Tipp: Kämpfe gegen andere Spieler, um Erfahrungspunkte und Geld zu verdienen. Du kannst nur gegen Spieler aus anderen Ländern kämpfen.';
$lang['BATTLE_NOTE2'] = 'Tipp: Jage andere Spieler um ein Kopfgeld zu kassieren und um Erfahrungspunkte zu sammeln für einen Stufenaufstieg. Du kannst nur gegen Spieler aus anderen Ländern kämpfen.';

$lang['BATTLE_FORCE_TYPE'] = 'Einheiten:';
$lang['BATTLE_ENEMIES'] = 'Feinde';
$lang['BATTLE_BOUNTY'] = 'Kopfgeld';
$lang['BATTLE_NO_BOUNTY_PLAYERS'] = 'Im Moment ist kein Kopfgeld auf einen Spieler ausgesetzt worden.';
$lang['BATTLE_BOUNTY_BONUS'] = 'Extra: Kopfgeld-Bonus von %s Dollar erhalten.'; 
$lang['BATTLE_HOSPITAL_BONUS'] = '%s ist vorübergehend ausser Gefecht. Du erhälst einen Bonus von %s Dollar!'; 
$lang['BATTLE_BOUNTY_LOST'] = 'You were attacked by the %s of %s.You LOST. Losing %s dollar, taking %s damage and losing %s experience points.';
$lang['BATTLE_BOUNTY_CONFIRM'] = 'Möchtest du eine Belohnung in Höhe von %s Dollar setzen?';

$lang['BATTLE_CEASE_FIRE_PERIOD'] = 'Waffenruhe ist aktiv! %s';

/*
** ------------------
** UNIT DATA
** ------------------
*/

/* Earth */
$lang['UNIT_GROUP_1']  = 'Armee';
$lang['UNIT_GROUP_2']  = 'Kavalarie';
$lang['UNIT_GROUP_3']  = 'Marine';
$lang['UNIT_GROUP_4']  = 'Luftwaffe';
$lang['UNIT_GROUP_5']  = 'Zivilisten';
$lang['UNIT_GROUP_6']  = 'Nachrichtendienst';

/* Moon */
$lang['UNIT_GROUP_7']  = 'Warriors';
$lang['UNIT_GROUP_8']  = 'Drohnen';
$lang['UNIT_GROUP_9']  = 'Spacecrafts';
$lang['UNIT_GROUP_10'] = 'Zivilisten';
$lang['UNIT_GROUP_11'] = 'Armee';
$lang['UNIT_GROUP_12'] = 'Kundschafter';

/* Mars */
$lang['UNIT_GROUP_13']  = 'Drohnen';
$lang['UNIT_GROUP_14']  = 'Warriors';
$lang['UNIT_GROUP_15']  = 'Spacecrafts';
$lang['UNIT_GROUP_16']  = 'Explorers';
$lang['UNIT_GROUP_17'] 	= 'Zivilisten';
$lang['UNIT_GROUP_18'] 	= 'Armee';

/* MERCURY */
$lang['UNIT_GROUP_19']  = 'Drones';
$lang['UNIT_GROUP_20']  = 'Warriors';
$lang['UNIT_GROUP_21']  = 'Spacecrafts';
$lang['UNIT_GROUP_22']  = 'Explorers';
$lang['UNIT_GROUP_23'] 	= 'Citizens';
$lang['UNIT_GROUP_24'] 	= 'Army';


/*
** ------------------
** UNIT PAGE
** ------------------
*/

/*
** ------------------
** BUILDING DATA
** ------------------
*/

/* Earth Buildings */
$lang['BUILDING_GROUP_1'] = 'Einkommen';
$lang['BUILDING_GROUP_2'] = 'Verteidigung';
$lang['BUILDING_GROUP_3'] = 'Energie';
$lang['BUILDING_GROUP_4'] = 'Discount';
$lang['BUILDING_GROUP_5'] = 'Maintenance';

/* Moon Buildings */
$lang['BUILDING_GROUP_6'] = 'Einkommen';
$lang['BUILDING_GROUP_7'] = 'Verteidigung';
$lang['BUILDING_GROUP_8'] = 'Energie';
$lang['BUILDING_GROUP_9'] = 'Discount';
$lang['BUILDING_GROUP_10'] = 'Maintenance';

/* Mars Buildings */
$lang['BUILDING_GROUP_11'] = 'Einkommen';
$lang['BUILDING_GROUP_12'] = 'Verteidigung';
$lang['BUILDING_GROUP_13'] = 'Energie';
$lang['BUILDING_GROUP_14'] = 'Discount';
$lang['BUILDING_GROUP_15'] = 'Maintenance';

/*
** ------------------
** BUILDING PAGE
** ------------------
*/

$lang['BUILDING_UPKEEP'] = 'Stündliche Kosten';
$lang['BUILDING_PRICE'] = 'Preis';
$lang['BUILDING_DEPLOYED'] = 'Beschäftigt';
$lang['BUILDING_GAIN'] = 'Verdienst';
$lang['BUILDING_ENERGY'] = 'Energie';
$lang['BUILDING_INCOME'] = 'Einkommen';
$lang['BUILDING_REQUIRED'] = 'Benötigt';

/*
** ------------------
** MONEY 
** ------------------
*/

$lang['MONEY_TITLE'] = 'MONEY';

/*
** ------------------
** BANKS 
** ------------------
*/

$lang['BANK_TITLE'] = 'BANKS';
$lang['BANK_NOTE'] = 'Tipp: There is a %s% Gebühr für jede Einzahlung. Die Bank zahlt dir %s% tägliche Zinsen. ';
$lang['BANK_WARNING'] = 'Achtung: Nachrichtendienst und Kundschafter von anderen Spielern können Geld stehlen von dieser Bank.';

$lang['BANK_TRANSACTION_TYPE_0'] = 'Abgehoben:';
$lang['BANK_TRANSACTION_TYPE_1'] = 'Eingezahlt:';
$lang['BANK_TRANSACTION_TYPE_2'] = 'Bankgebühr';
$lang['BANK_TRANSACTION_TYPE_3'] = 'Restore bill';		
$lang['BANK_TRANSACTION_TYPE_4'] = 'Zinsen:';	
$lang['BANK_TRANSACTION_TYPE_5'] = 'Gestohlen:';
$lang['BANK_TRANSACTION_TYPE_6'] = 'Bonus ';

$lang['BANK_TRANSACTION_LOG'] = 'Kontoauszug';

/*
** ------------------
** CASINO
** ------------------
*/

$lang['CASINO_TITLE'] = 'KASINO' ;

$lang['CASINO_WHEEL'] = 'Glücksrad';
$lang['CASINO_SLOTMACHINE'] = 'Einarmiger Bandit';

$lang['CASINO_COMING_SOON'] = 'ist noch in der Versuchsphase!';

$lang['CASINO_MONEY'] = 'Geld';
$lang['CASINO_NUMBER'] = 'Glücksnummer';
$lang['CASINO_BET'] = 'wetten';
$lang['CASINO_PLAY'] = 'Spielen';
$lang['CASINO_ROLL'] = 'Drehen';

$lang['CASINO_NO_BET'] = 'Gib deinen Wetteinsatz!';
$lang['CASINO_NO_LUCKY_NUMBER'] = 'Wähle deine Glücksnummer!';
$lang['CASINO_BET_TO_LARGE'] = 'Wetteinsatz zu hoch! Das Limit liegt bei %s Dollar.'; 
$lang['CASINO_NO_MONEY'] = 'Nicht genug Geld!'; 

$lang['CASINO_WIN'] = 'Glücksnummer war %s. Du gewinnst %s  Dollar.';
$lang['CASINO_LOST'] = 'Glücksnummer war %s. Du verlierst %s Dollar.';

$lang['CASINO_SLOTMACHINE_WIN'] = 'Du gewinnst das %sfache deines Wetteinsatzes. Du erhälst %s Dollar.';
$lang['CASINO_SLOTMACHINE_LOST'] = 'Du verlierst %s Dollar.';
$lang['CASINO_SLOTMACHINE_HELP'] = 'The following slot machine combinations will pay out';

/*
** ------------------
** ALLIANCE
** ------------------
*/

$lang['ALLIANCE_ACCEPT_TITLE1'] = 'Akzeptieren';
$lang['ALLIANCE_ACCEPT_TITLE2'] = 'Akzeptiert [%s allies]';

$lang['ALLIANCE_INVITE_TITLE'] = 'Einladen';

$lang['ALLIANCE_INVITATION'] = 'Bündnisanfrage gesendet an %s!'; 
$lang['ALLIANCE_REJECT'] = 'Reject %s as ally!';
$lang['ALLIANCE_DROP'] = 'Drop %s as ally!';
$lang['ALLIANCE_ACCEPT'] = '%s als Verbündeten akzeptiert!';
$lang['ALLIANCE_ALLY'] = 'Ally';
$lang['ALLIANCE_MAXIMUM'] = 'Maximume Anzahl von %s Verbündeten ist für das Level erreicht.'; 
$lang['ALLIANCE_LOCKED'] = 'Bündnisanfragen sind ab level 1 verfügbar';
$lang['ALLIANCE_NOTE'] = 'Tipp: Mit jedem bestätigtem Verbündeten, kannst du sechs weitere Einheiten in den Kampf schicken. Denke immer daran, Verbündete können nicht angegriffen werden.';

/*
** ------------------
** FORUM 
** ------------------
*/

$lang['TOPIC_CREATED'] = 'Topic ist erstellt';
$lang['TOPIC_UPDATED'] = 'Topic ist upgedatet';
$lang['TOPIC_DELETED'] = 'Topic ist gelöscht';
$lang['TOPIC_NO_TOPICS'] = 'Im Moment sind keine Topic(s) gegründet.';
$lang['TOPIC_NOTE'] = 'Tipp: Select a topic to read/write posted messages or create a new topic.'; 
$lang['TOPIC_CREATED_BY'] = '(Erstellt von %s)';

/*
** ------------------
** FORUM - POLL
** ------------------
*/

$lang['POLL_TITLE'] = 'Wahlen';
$lang['POLL_RESULT_TITLE'] = 'Wahl Resultate';
$lang['POLL_TEASER_TITLE'] = 'Neue Wahl';
$lang['POLL_RESULTS'] = 'Resultat';
$lang['POLL_ClOSED'] = '(Wahl geschlossen)';
$lang['POLL_VOTE_ADD'] = 'Danke für die Unterstützung!';
$lang['POLL_VOTE_REMOVE'] = 'Deine Wahl wurde abgebrochen!';
$lang['POLL_VOTE'] = 'Wahl';
$lang['POLL_VOTES'] = 'Abstimmen';
$lang['POLL_CANCEL'] = 'Abbrechen';

/*
** ------------------
** FORUM - CHAT
** ------------------
*/

$lang['CHATROOM_TITLE'] = 'Chatroom';
$lang['CHATROOM_NOTE'] = 'Tipp: Klicke einen Online Spieler an um den Chat zu starten!';
$lang['CHATROOM_LAST_ACTIVE'] = 'Zuletzt aktiv';
$lang['CHATROOM_CHAT'] = 'Chat';
$lang['CHAT_NOTE'] = 'Tipp: Schreibe eine Nachricht um den Chat zu beginnen!';

$lang['CHAT_TITLE'] = 'Chat';

/*
** ------------------
** HELP - INSTRUCTIONS
** ------------------
*/

$lang['HELP_TITLE'] = 'Hilfe';

$lang['HELP_GENERAL_SUBTITLE'] = 'Einführung';

$lang['HELP_INTRO_TITLE'] = 'Einführung';
$lang['HELP_INTRO'] =	'WarQuest ist ein kostenloses Multiplayer Online Game featuring a war zone mit tausenden von realen Spielern. WarQuest nimmt dich mit ins 
Jahr 2020. Der Weltkrieg ist ausgebrochen. Das Ziel des Spiels ist es dein Land zu verteidigen und andere Länder zu erobern. Rüste dich mit schwerem Kriegsgerät,
 produziere Einheiten, spiele Missionen, kämpfe, schließe Bündisse und werde der beste Spieler aller Zeiten.';

$lang['HELP_EXP_TITLE'] = 'Erfahrungspunkte / Level';
$lang['HELP_EXP'] = 'Spiele Missionen und trage Kämpfe gegen Spieler aus um Erfahrungspunkte zu sammeln. Wenn du genügend Punkte für einen Levelaufstieg gesammelt hast, 
kannst du wertvolle Skillpunkte verteilen. Wenn du eine Stufe aufsteigst, füllt sich deine Energie-, Lebens- und Munitionsbar automatisch vollständig auf.';

$lang['HELP_HEALTH_TITLE'] = 'Gesundheit';
$lang['HELP_HEALTH'] = 'Deine Gesundheit nimmt mit jedem Kampf drastisch ab, wird jedoch automatisch mit der Zeit wieder aufgefüllt. Du kannst auch das Krankenhaus aufsuchen (Home -> Restore) um sofortige Heilung zu erhalten.';

$lang['HELP_ENERGY_TITLE'] = 'Energie'; 
$lang['HELP_ENERGY'] = 'Deine Energie nimmt mit jeder Mission ab, füllt sich jedoch automatisch mit der Zeit wieder. Kaufe Energie Gebäude um eine größere Menge wieder zu erlangen und somit schneller Mission zu spielen.
 Auf dem gleiche Weg wie du deine Gesundheit sofort auffrischen kannst, gibt es eine Möglichkeit für dein Energie.';

$lang['HELP_AMMO_TITLE'] = 'Munition'; 
$lang['HELP_AMMO'] =	'In jedem Kampf gegen einen Spieler benötigst du Eine Munitionspunkt. Die Munition füllt sich ebenfalls mit der Zeit vollkommen automatisch. Ein Waffenhändler füllt dein Depot vollständig
 wieder auf, auf dem gleichen weg zu finde wie das Krankenhaus.';

$lang['HELP_MISSION_TITLE'] = 'Missionen';
$lang['HELP_MISSION'] = 'Spiele Missionen um Geld und Erfahrungspunkte zu erhalten für einen Stufenaufstieg. 
Wenn eine Mission zu 100% abgeschlossen ist, erhälst du beim wiederholten Angriff die doppelte Menge Geld. Wenn der Kontinent vollständig 
erobert wurde, erhälst du einen Bonus auf dein Stündliches Einkommen.';

$lang['HELP_BATTLE_TITLE'] = 'Kampf';
$lang['HELP_BATTLE'] =	'Kämpfe gegen andere Spieler, um Erfahrungspunkte und Geld zu verdienen, für einen Stufenaufstieg.
 Während des Kampfes werden deine Gebäude und Truppen beschädigt und können sogar fallen. Du kannst nur gegen Spieler aus anderen Ländern kämpfen.';

$lang['HELP_UNITS_TITLE'] = 'Einheiten';
$lang['HELP_UNITS'] =  'Während eines Angriffs werden deine besten Truppen automatisch gewählt. Die Größe der Truppe (Anzahl) deiner Armee bezieht sich auf die Anzahl deiner Verbündeten. Zu Anfang 
 besitzt du nur einen Verbündeten (Dich selbst) und kannst daher nur sechs Einheiten befehligen. Jeder Verbündeter hilft dir sechs weitere Einheiten zu führen. Denke daran es werden immer nur die besten in den Kampf geschickt und die Anzahl der Truppen entspricht dem 6fachen deiner Verbündeten.';

$lang['HELP_BUILDINGS_TITLE'] = 'Gebäude';
$lang['HELP_BUILDINGS'] = 'Während des Spielens ermöglichen dir deine Gebäude eine bestimmtes Einkommen, eine Verteidigung, mehr Energie, 
Rabatte und/oder besseren Schutz gegen Verlust von Einheiten während eines Kampfes. Jedes gekaufte Gebäude steigert den Preis beim Neuerwerb. Jedes Gebäude hat natürlich auch Zivilisten, die Kosten verursachen.';

$lang['HELP_BANKS_TITLE'] = 'Bank';
$lang['HELP_BANKS'] = 'Jede Bank hat eine Einzahlungsgebühr, dafür erhälst du aber auch Zinsen. Die National Bank ist die sicherste aller Banken, jedoch ist der Zinssatz auch dementsprechend der niedrigste. 
.Andere Banken haben einen höheren Zinssatz, jedoch ist es anderen Spielern möglich, mithilfe vom Nachrichtendienst (Erde) bzw. Kundschaftern (Mond) diese auszurauben.';

$lang['HELP_ALLIANCE_TITLE'] = 'Bündnis'; 
$lang['HELP_ALLIANCE'] = 'Jeder bestätigte Verbündetet erlaubt dir sechs weitere Einheiten zu kommandieren(welche du natürlich besitzen musst) 
während eines Angriffs auf einen Spieler. Gehe Bündnise ein um stärker zu werden! Selbstverständliche ist es nicht möglich Verbündete anzugreifen.';

$lang['HELP_SKILL_POINTS_TITLE'] = 'Skill Punkte';
$lang['HELP_SKILL_POINTS'] = 'During the game skill points can be collected. Deploy skill points to 
increase attack, defense, health, energy and/or ammo skills. Ammo skill upgrade costs two skill points, 
others will cost you only one skill points. You can also trade-in 2:1 skillpoints to reallocate your skills.';


$lang['HELP_UNITS_CONDITION_TITLE'] = 'Einheiten Zustand (EZ)';
$lang['HELP_UNITS_CONDITION'] = 'Dieser Wert gibt dir aufschlussreiche Inforamtion über den momentanigen Zustand deiner Streitkraft. 
Sollte der Wert auf 0% sinken, wirst du einige Einheiten verlieren. Um dies zu verhinderen solltest du regelmäßig die Werkstatt aufsuchen und deine Truppen pflegen, gehe dazu (Home -> Restore).'; 

$lang['HELP_BUILDINGS_CONDITION_TITLE'] = 'Gebäude Zustand (GZ)';
$lang['HELP_BUILDINGS_CONDITION'] = 'This value gives information about your current base buildings 
condition. If the condition goes below 0% you will lose some buildings. To prevent building loss 
you can visit (Home -> Restore) to repair your base.'; 

$lang['HELP_FORUM_TITLE'] = 'Forum';
$lang['HELP_FORUM'] = 'To get more information and chat with other players please visit the Warquest 
Forum under (Alliance -> Forum).';

/*
** ------------------
** HELP - RELEASE NOTES
** ------------------
*/

/*
** ------------------
** HELP - RANKS
** ------------------
*/

/*
** ------------------
** HELP - AWARDS
** ------------------
*/

/*
** ------------------
** HELP - DONATE
** ------------------
*/

/*
** ------------------
** HELP - STATS
** ------------------
*/

/*
** ------------------
** COUNTRY NAMES
** ------------------
*/

$landcode = array();

$landcode['ad'] = "Andorra";
$landcode['ae'] = "Arab Emirates";
$landcode['af'] = "Afghanistan";
$landcode['ag'] = "Antigua and Barbuda";
$landcode['ai'] = "Anguilla";
$landcode['al'] = "Albania";
$landcode['am'] = "Armenia";
$landcode['an'] = "Netherlands Antilles";
$landcode['ao'] = "Angola";
$landcode['aq'] = "Antarctica";
$landcode['ar'] = "Argentina";
$landcode['as'] = "American Samoa";
$landcode['at'] = "Österreich";
$landcode['au'] = "Australien";
$landcode['aw'] = "Aruba";
$landcode['ax'] = "Aland Islands";
$landcode['az'] = "Azerbaijan";
		
$landcode['ba'] = "Bosnia and Herzegovina";
$landcode['bb'] = "Barbados";
$landcode['bd'] = "Bangladesch";
$landcode['be'] = "Belgien";
$landcode['bf'] = "Burkina Faso";
$landcode['bg'] = "Bulgaria";
$landcode['bh'] = "Bahrain";
$landcode['bi'] = "Burundi";
$landcode['bj'] = "Benin";
$landcode['bm'] = "Bermuda";
$landcode['bn'] = "Brunei Darussalam";	
$landcode['bl'] = "Saint Barthelemy";
$landcode['bn'] = "Brunei";
$landcode['bo'] = "Bolivia";
$landcode['br'] = "Brazil";
$landcode['bs'] = "Bahamas";
$landcode['bt'] = "Bhutan";
$landcode['bv'] = "Bouvet island";
$landcode['bw'] = "Botswana";
$landcode['by'] = "Belarus";
$landcode['bz'] = "Belize";
	
$landcode['ca'] = "Canada";
$landcode['cc'] = "Cocos Islands";
$landcode['cf'] = "Central African Republic";
$landcode['cg'] = "Kongo";
$landcode['ch'] = "Schweiz";
$landcode['ci'] = "Cote d lvoire";
$landcode['ck'] = "Cook Islands";
$landcode['cl'] = "Chili";
$landcode['cm'] = "Kameroon";
$landcode['cn'] = "China";
$landcode['co'] = "Columbien";
$landcode['cr'] = "Costa Rica";
$landcode['cs'] = "Serbia en Montenegro";
$landcode['cu'] = "Kuba";
$landcode['cv'] = "Cape Verde";
$landcode['cx'] = "Christmas Island";
$landcode['cy'] = "Cyprus";
$landcode['cz'] = "Czech Republic";
	
$landcode['de'] = "Deutschland";
$landcode['dj'] = "Djibouti";
$landcode['dk'] = "Denmark";
$landcode['dm'] = "Dominica";
$landcode['do'] = "Dominican Republic";
$landcode['dz'] = "Algeria";
	
$landcode['ec'] = "Equador";
$landcode['ee'] = "Estonia";
$landcode['eg'] = "Ägypten";
$landcode['eh'] = "Western Sahara";
$landcode['er'] = "Eritrea";
$landcode['es'] = "Spain";
$landcode['et'] = "Ethiopia";
$landcode['eu'] = "Cyberspace";
	
$landcode['fi'] = "Finnland";
$landcode['fj'] = "Fiji";
$landcode['fk'] = "Falkland Islands";
$landcode['fm'] = "Micronesia";
$landcode['fo'] = "Faroe Islands";
$landcode['fr'] = "France";
	
$landcode['ga'] = "Gabon";
$landcode['gb'] = "United Kingdom";
$landcode['gd'] = "Grenada";
$landcode['ge'] = "Georgia";
$landcode['gf'] = "French Guiana";
$landcode['gh'] = "Ghana";
$landcode['gi'] = "Gibraltar";
$landcode['gl'] = "Grönland";
$landcode['gm'] = "Gambia";
$landcode['gn'] = "Guinea";
$landcode['gp'] = "Guadeloupe";
$landcode['gq'] = "Equatorial Guinea";
$landcode['gr'] = "Greece";
$landcode['gs'] = "Zuid-Georgia";
$landcode['gt'] = "Guatemala";
$landcode['gu'] = "Guam";
$landcode['gw'] = "Guinee-Bissau";
$landcode['gy'] = "Guyana";
	
$landcode['hk'] = "Hong Kong";
$landcode['hm'] = "Heard- en McDonald Islands";
$landcode['hn'] = "Honduras";
$landcode['hr'] = "Kroatien";
$landcode['ht'] = "Haiti";
$landcode['hu'] = "Hungary";
	
$landcode['id'] = "Indonesien";
$landcode['ie'] = "Irland";
$landcode['il'] = "Israel";
$landcode['in'] = "India";
$landcode['im'] = "Isle of Man";
$landcode['io'] = "BI Ocean Territory";
$landcode['iq'] = "Irak";
$landcode['ir'] = "Iran";
$landcode['is'] = "Iceland";
$landcode['it'] = "Italien";
	
$landcode['jm'] = "Jamaika";
$landcode['jo'] = "Jordan";
$landcode['jp'] = "Japan";
	
$landcode['ke'] = "Kenia";
$landcode['kg'] = "Kyrgyzstan";
$landcode['kh'] = "Cambodia";
$landcode['ki'] = "Kiribati";
$landcode['km'] = "Comores";
$landcode['kn'] = "Saint Kitts en Nevis";
$landcode['kp'] = "North Korea";
$landcode['kr'] = "South Korea";
$landcode['kw'] = "Kuwait";
$landcode['ky'] = "Cayman Islands";
$landcode['kz'] = "Kazachstan";
	
$landcode['la'] = "Laos";
$landcode['lb'] = "Libanon";
$landcode['lc'] = "Saint Lucia";
$landcode['li'] = "Liechtenstein";
$landcode['lk'] = "Sri Lanka";
$landcode['lr'] = "Liberia";
$landcode['ls'] = "Lesotho";
$landcode['lt'] = "Lithuania";
$landcode['lu'] = "Luxemburg";
$landcode['lv'] = "Latvia";
$landcode['ly'] = "Libyen";
	
$landcode['ma'] = "Marokko";
$landcode['mc'] = "Monako";
$landcode['md'] = "Moldova";
$landcode['mg'] = "Madagascar";
$landcode['mh'] = "Marshall Islands";
$landcode['mk'] = "Macedonia";
$landcode['ml'] = "Mali";
$landcode['mm'] = "Myanmar";
$landcode['mn'] = "Mongolia";
$landcode['mo'] = "Macao";
$landcode['mp'] = "Northern Mariana Islands";
$landcode['mq'] = "Martinique";
$landcode['mr'] = "Mauritania";
$landcode['ms'] = "Montserrat";
$landcode['mt'] = "Malta";
$landcode['mu'] = "Mauritius";
$landcode['mv'] = "Maldives";
$landcode['mw'] = "Malawi";
$landcode['mx'] = "Mexico";
$landcode['my'] = "Malaysia";
$landcode['mz'] = "Mozambique";
	
$landcode['na'] = "Namibia";
$landcode['nc'] = "New Caledonia";
$landcode['ne'] = "Niger";
$landcode['nf'] = "Norfolk Islands";
$landcode['ng'] = "Niger";
$landcode['ni'] = "Nicaragua";
$landcode['nl'] = "Netherlands";
$landcode['no'] = "Norway";
$landcode['np'] = "Nepal";
$landcode['nr'] = "Nauru";
$landcode['nu'] = "Niue";
$landcode['nz'] = "New Zealand";
	
$landcode['om'] = "Oman";
	
$landcode['pa'] = "Panama";
$landcode['pe'] = "Peru";
$landcode['pf'] = "French Polynesia";
$landcode['pg'] = "Papua New Guinea";
$landcode['ph'] = "Philippines";
$landcode['pk'] = "Pakistan";
$landcode['pl'] = "Poland";
$landcode['pm'] = "Saint Pierre and Miquelon";
$landcode['pn'] = "Pitcairn";
$landcode['pr'] = "Puerto Rico";
$landcode['ps'] = "Palestinian";
$landcode['pt'] = "Portugal";
$landcode['pw'] = "Palau";
$landcode['py'] = "Paraguay";
	
$landcode['qa'] = "Qatar";
	
$landcode['re'] = "Reunion";
$landcode['ro'] = "Romania";
$landcode['ru'] = "Russian Federation";
$landcode['rs'] = "Serbia";
$landcode['rw'] = "Rwanda";
	
$landcode['sa'] = "Saudi Arabia";
$landcode['sb'] = "Solomon Islands";
$landcode['sc'] = "Seychelles";
$landcode['sd'] = "Sudan";
$landcode['se'] = "Sweden";
$landcode['sg'] = "Singapore";
$landcode['sh'] = "Saint-Helena";
$landcode['si'] = "Slovenia";
$landcode['sj'] = "Svalbard and Jan Mayen";
$landcode['sk'] = "Slovakia";
$landcode['sl'] = "Sierra Leone";
$landcode['sm'] = "San Marino";
$landcode['sn'] = "Senegal";
$landcode['so'] = "Somalia";
$landcode['sr'] = "Suriname";
$landcode['st'] = "Sao Tome en Principe";
$landcode['sv'] = "El Salvador";
$landcode['sy'] = "Syrien";
$landcode['sz'] = "Swaziland";
	
$landcode['tc'] = "Turks and Caicos Islands";
$landcode['td'] = "Chad";
$landcode['tg'] = "Togo";
$landcode['th'] = "Thailand";
$landcode['tj'] = "Tajikistan";
$landcode['tk'] = "Tokelau";
$landcode['tl'] = "Timor";
$landcode['tm'] = "Turkmenistan";
$landcode['tn'] = "Tunisien";
$landcode['to'] = "Tonga";
$landcode['tr'] = "Turkei";
$landcode['tt'] = "Trinidad and Tobago";
$landcode['tv'] = "Tuvalu";
$landcode['tw'] = "Taiwan";
$landcode['tz'] = "Tanzania";
	
$landcode['ua'] = "Ukraine";
$landcode['ug'] = "Uganda";
$landcode['um'] = "United States Minor Outlying Islands";
$landcode['us'] = "USA";
$landcode['uy'] = "Uruguay";	
$landcode['uz'] = "Uzbekistan";
	
$landcode['va'] = "Vatikan";
$landcode['vc'] = "Saint Vincent and the Grenadines";
$landcode['ve'] = "Venezuela";
$landcode['vg'] = "Virgin Islands; British";
$landcode['vi'] = "Virgin islands; US";
$landcode['vn'] = "Vietnam";
$landcode['vu'] = "Vanuatu";
	
$landcode['wf'] = "Wallis and Futuna";
$landcode['ws'] = "Samoa";
	
$landcode['ye'] = "Yemen";
$landcode['yt'] = "Mayotte";
	
$landcode['za'] = "Süd Afrika";
$landcode['zm'] = "Zambia";
$landcode['zw'] = "Zimbabwe";
	
/*
** ------------------
** THE END
** ------------------
*/

?>