<?php

/* 
**  ========
**  WARQUEST
**  ========
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  All copyrights reserved (c) 2008-2014 PlaatSoft
*/

/*
** Some translation remarks:
** (1) Every line has the following syntax $lang['<KEY>'] = '<DESCRIPTION>';
**     Only change the <DESCRIPTION> part. Leave the rest unchanged.
** (2) The <DESCRIPTION> part contain %s tags. DO NOT REMOVE THEN.
**     The %s are realtime replace with game parameters. 
**     For example: 'Restore for %s dollars' will be on screen 'Restore for 100 dollars'
** (3) The LINK keys contain the menu items of the game. Choose as short as possible words.
** (4) Leave HTML tags unchanged, for example <b>, </b>, etc....
**
** Good luck and have fun!
*/

/*
** ------------------
** Language: English
** ------------------
*/
 
/*
** ------------------
** LINKS
** ------------------
*/

/* Login */
$lang['LINK_LOGIN']  = 'Login'; 
$lang['LINK_REGISTER'] = 'Registration'; 
$lang['LINK_RECOVER'] = 'Recovery'; 
$lang['LINK_MANUAL'] = 'Manual'; 
$lang['LINK_FACEBOOK'] = 'Facebook';
$lang['LINK_RSS']  = 'RSS'; 

/* General */
$lang['LINK_HOME'] = 'Home';
$lang['LINK_MISSIONS'] = 'Missions';
$lang['LINK_BATTLE'] = 'Battle';
$lang['LINK_UNITS']  = 'Units';
$lang['LINK_BUILDINGS']  = 'Buildings';
$lang['LINK_BANKS'] = 'Banks';
$lang['LINK_ALLIANCE'] = 'Alliance';
$lang['LINK_PLAYER'] = 'Player';
$lang['LINK_MONEY'] = 'Money';
$lang['LINK_HELP'] = 'Help';
$lang['LINK_ADMIN'] = 'Admin';

$lang['LINK_FIRST']  = 'First';
$lang['LINK_PREVIOUS'] = 'Previous';
$lang['LINK_NEXT'] = 'Next';
$lang['LINK_LAST'] = 'Last';

/* Home */
$lang['LINK_RESTORE'] = 'Restore';
$lang['LINK_REPAIR'] = 'Repair';
$lang['LINK_TRADE'] = 'Trade';
$lang['LINK_ACTIVATE'] = 'Activate';

/* Player */
$lang['LINK_OVERVIEW'] = 'Overview';
$lang['LINK_DELETE'] = 'Delete';
$lang['LINK_SETTINGS'] = 'Settings';
$lang['LINK_NEWS'] = 'News';
$lang['LINK_COMMENTS'] = 'Messages';
$lang['LINK_STATISTICS'] = 'Statistics';
$lang['LINK_LOGOUT'] = 'Logout';
$lang['LINK_EDIT'] = 'Edit';
$lang['LINK_SAVE'] = 'Save';
$lang['LINK_REPLY'] = 'Reply';
$lang['LINK_PROFILE'] = 'Profile';
$lang['LINK_SKILLS'] = 'Skills';
$lang['LINK_RECRUIT']  = 'Invite';
$lang['LINK_INCREASE'] = 'Increase';
$lang['LINK_DECREASE'] = 'Decrease';
$lang['LINK_RESTORE_NOW']  = 'Restore for %s dollars';
$lang['LINK_CHANGE'] = 'Change';
$lang['LINK_REPORT'] = 'Report';
$lang['LINK_BOUNTY'] = 'Bounty';

/* Mission */
$lang['LINK_PLAY'] = 'Play';
$lang['LINK_BUY_PLAY'] = 'Buy and play';
$lang['LINK_DO_AGAIN'] = 'Play again';

/* Battle */
$lang['LINK_ATTACK'] = 'Attack';
$lang['LINK_BATTLES']  = 'Battles';
$lang['LINK_SP'] = 'Skill points';

/* Unit */
$lang['LINK_DEPLOY'] = 'Deploy';
$lang['LINK_DEPLOY_AGAIN'] = 'Deploy again';
$lang['LINK_DISBAND']  = 'Disband';
$lang['LINK_DISBAND_AGAIN']= 'Disband Again';

/* Building */
$lang['LINK_INCOME'] = 'Income';
$lang['LINK_DEFENSE'] = 'Defense';
$lang['LINK_ENERGY'] = 'Energy';
$lang['LINK_BUY'] = 'Buy';
$lang['LINK_BUY_AGAIN'] = 'Buy again';
$lang['LINK_SELL'] = 'Sell';
$lang['LINK_SELL_AGAIN'] = 'Sell again';

/* Money */
$lang['LINK_BANK'] = 'Bank';
$lang['LINK_STOCKEXCHANGE'] = 'Stock-Exchange';
$lang['LINK_CASINO'] = 'Casino';

$lang['LINK_DEPOSIT']  = 'Deposit';
$lang['LINK_WITHDRAW'] = 'Withdraw';
$lang['LINK_BALANCE']  = 'Balance';

/* Alliance */
$lang['LINK_INVITE'] = 'Invite';
$lang['LINK_PENDING'] = 'Pending';
$lang['LINK_APPROVED'] = 'Accepted';
$lang['LINK_COMMENT']  = 'Message';
$lang['LINK_FORUM']  = 'Forum';
$lang['LINK_BEST_PLAYER']  = 'Best-Players';
$lang['LINK_BEST_COUNTRY'] = 'Best-Countries';
$lang['LINK_DROP'] = 'Drop';
$lang['LINK_ACCEPT'] = 'Accept';
$lang['LINK_REJECT'] = 'Reject';
$lang['LINK_SEND'] = 'Send';
$lang['LINK_RESET']  = 'Reset';

/* Forum */
$lang['LINK_FORUM']  = 'Forums';
$lang['LINK_POLLS'] = 'Polls';
$lang['LINK_CHATROOM'] = 'Chatroom';
$lang['LINK_SEARCH']  = 'Search';

/* Help */
$lang['LINK_GENERAL']  = 'Instructions';
$lang['LINK_NOTES']  = 'Release-Notes';
$lang['LINK_RANKS']  = 'Ranks';
$lang['LINK_AWARDS'] = 'Awards';
$lang['LINK_LEVELS']  = 'Levels';
$lang['LINK_STATS']  = 'Stats';
$lang['LINK_DONATE']  = 'Donate';
$lang['LINK_ABOUT']  = 'About';

/* Admin */

/*
** ------------------
** GENERAL 
** ------------------
*/

$lang['SYSTEM_HACK_DETECTED'] = 'Please do not use the reload, prev or next button!';

$lang['AGO_DAY']   = ' day';	
$lang['AGO_DAYS']  = ' days';
$lang['AGO_HOUR']  = ' hour';
$lang['AGO_HOURS'] = ' hours';
$lang['AGO_MIN']   = ' min';
$lang['AGO_MINS']  = ' mins';
$lang['AGO_SEC']   = ' sec';
$lang['AGO_SECS']  = ' secs';
	
$lang['COPYRIGHT'] = 'Copyright © 2008-2014 - All Rights Reserved - <a target="new" href="http://www.plaatsoft.nl">PlaatSoft</a>';
$lang['STATUS_CASH']  = 'Cash';
$lang['STATUS_EXP']  = 'Exp.';
$lang['STATUS_LEVEL']  = 'Level';
$lang['STATUS_HEALTH'] = 'Health';
$lang['STATUS_ENERGY'] = 'Energy';
$lang['STATUS_AMMO'] = 'Ammo';
$lang['STATUS_ALLIANCE_SIZE'] = 'Alliance size';

$lang['BOX_INFO'] = 'INFO';
$lang['BOX_WARN'] = 'WARNING';
$lang['BOX_ERROR'] = 'ERROR';

$lang['GENERAL_NEXT_LEVEL'] = 'Brilliant! You have reached the next level! You received %s skill points and %s dollars. Your health, energy and ammo are restored. ';
$lang['GENERAL_BATTLE_LEVEL'] = 'Brilliant! You have won %s battles and received %s extra skill point(s) and %s dollars.';
$lang['GENERAL_BOUNTY_LEVEL'] = 'Great! You have set %s bounties and received %s extra skill point(s) and %s dollars.';
$lang['GENERAL_REBEL_LEVEL'] = 'Great! You started %s rebellions and received %s extra skill point(s) and %s dollars.';
$lang['GENERAL_BATTLE_AWARD_WON'] = 'fights won';
$lang['GENERAL_BOUNTY_AWARD_WON'] = 'bounties set';
$lang['GENERAL_REBEL_AWARD_WON'] = 'rebellions started';
$lang['GENERAL_UNLOCK'] = 'Unlocked at level %s';
$lang['GENERAL_NEW_FEATURES'] = 'The following features are now unlocked:';
$lang['GENERAL_RECEIVED_AWARD'] = 'Received award:';

$lang['GENERAL_ATTACK'] = 'attack';
$lang['GENERAL_DEFENSE'] = 'defense';
$lang['GENERAL_INCOME']  = 'income';
$lang['GENERAL_ENERGY']  = 'energy';
$lang['GENERAL_EXPERIENCE']  = 'experience';
$lang['GENERAL_DOLLAR']  = 'dollar';
$lang['GENERAL_ALLIANCE_SIZE'] = 'alliance size';
$lang['GENERAL_EXPERIENCE_POINTS'] = 'experience points';
$lang['GENERAL_UPKEEP'] = 'Hourly cost';
$lang['GENERAL_BANK']  = 'Bank';
$lang['GENERAL_DEPLOYED']  = 'deployed';

$lang['GENERAL_PLAYER']  = 'Player';
$lang['GENERAL_LEVEL'] = 'Level';
$lang['GENERAL_ALLIANCE']  = 'Alliance';
$lang['GENERAL_WON'] = 'Won';
$lang['GENERAL_LOST']  = 'Lost';
$lang['GENERAL_AMOUNT'] = 'Amount';
$lang['GENERAL_DATE'] = 'Date';
$lang['GENERAL_TRANSACTION'] = 'Transaction';
$lang['GENERAL_BALANCE'] = 'Balance';
$lang['GENERAL_APPROVED'] = 'Approved';
$lang['GENERAL_EMAIL'] = 'Email';
$lang['GENERAL_TOP']	= 'Top';
$lang['GENERAL_EXP'] = 'Experience';
$lang['GENERAL_COUNTRY'] = 'Country';
$lang['GENERAL_PLAYERS'] = 'Players';
$lang['GENERAL_WONS']  = 'Won';
$lang['GENERAL_LOSTS'] = 'Lost';
$lang['GENERAL_NO'] = 'No';
$lang['GENERAL_YES'] = 'Yes';
$lang['GENERAL_AGO'] = 'Ago';
$lang['GENERAL_MESSAGE'] = 'Message';
$lang['GENERAL_ACTION'] = 'Action';
$lang['GENERAL_NUMBER'] = 'Nr.';
$lang['GENERAL_DISCOUNT'] = 'Building discount';
$lang['GENERAL_REQUESTS'] = 'Requests';
$lang['GENERAL_EP'] = 'Skill Point';
$lang['GENERAL_AWARD'] = 'Award';
$lang['GENERAL_LANGUAGE'] = 'Language';
$lang['GENERAL_RANKING'] = 'Ranking';

$lang['GENERAL_NEW_UNIT'] = 'NEW UNIT';
$lang['GENERAL_NEW_BUILDING'] = 'NEW BUILDING';
$lang['GENERAL_NEW_MISSION'] = 'NEW MISSION';
$lang['GENERAL_GAIN'] = 'gain';

$lang['GENERAL_BOUNTY'] = 'Bounty';
$lang['GENERAL_INTELLIGENCE'] = 'intelligence';
$lang['GENERAL_SPIES'] = 'spies';
$lang['GENERAL_MAINTENANCE'] = 'Unit maintenance';

$lang['GENERAL_CNTRY'] = 'Country';
$lang['GENERAL_TOPICS'] = 'topics'; 
$lang['GENERAL_FORUM'] = 'Forum';
$lang['GENERAL_MESSAGES'] = 'messages';
$lang['GENERAL_LAST_MESSAGE'] = 'Last Message';
$lang['GENERAL_FORUM_MODERATED'] = '(Moderated by %s)';
$lang['GENERAL_NOT_MODERATED'] = '(Not Moderated)';
$lang['GENERAL_BY'] = 'ago';
$lang['GENERAL_TOPIC'] = 'Topic';
$lang['GENERAL_LOCKED'] = 'Locked';
$lang['GENERAL_WORLDMAP'] = 'World Map';
$lang['GENERAL_PLAATSOFT'] = 'PlaatSoft';
$lang['GENERAL_CONQUER'] = 'Conquer';

$lang['GENERAL_ST'] = '%sst';
$lang['GENERAL_ND'] = '%snd';
$lang['GENERAL_TH'] = '%sth';

$lang['GENERAL_CONTINENT'] = 'Continent';
$lang['GENERAL_CONQUERED'] = 'Conquered';

$lang['GENERAL_IDLE'] = 'Idle';
$lang['GENERAL_ACTIVE'] = 'Active';
$lang['GENERAL_INACTIVE'] = 'Inactive';

$lang['GENERAL_PLANET'] = 'Planet';
$lang['GENERAL_PLANET_1'] = 'Earth';
$lang['GENERAL_PLANET_2'] = 'Moon';
$lang['GENERAL_PLANET_3'] = 'Mars';
$lang['GENERAL_PLANET_4'] = 'Mercure';
$lang['GENERAL_PLANET_5'] = 'Neptune';

/*
** ------------------
** TIP
** ------------------
*/

$lang['TIP_GENERAL']  = 'TIP';
$lang['TIP_0'] = 'Play the training mission to collect experience points and reach the next level.';
$lang['TIP_1'] = 'Buy some units and start battle training to collect experience points.';
$lang['TIP_2'] = 'Trade in received skill points (Home -> Skills) to improve your soldier abilities.';
$lang['TIP_3'] = 'Enter your email address to receive message and alliance notifications!';
$lang['TIP_4'] = 'Buy some income buildings to generate hourly income.';
$lang['TIP_5'] = 'Buy some defense buildings to improve your defense strength.';
$lang['TIP_6'] = 'Make alliance with ohter players to improve your attack/defense strength.';
$lang['TIP_7'] = 'Store cash money in the National bank to keep them safe from other players.';
$lang['TIP_8'] = 'Collect extra experience points by voting on the available polls!';
$lang['TIP_9'] = 'Set bounty on other players to receive bounty awards.';
$lang['TIP_10'] = 'Visit the casino to play the Wheel of Fortune and win more cash.';
$lang['TIP_11'] = 'Buy energy buildings for faster energy recovery.';
$lang['TIP_12'] = 'Buy Intel units to spy other players and start rebellion on their continent.';
$lang['TIP_13'] = 'Store cash money in the Trasquera bank to receive daily interest.';
$lang['TIP_14'] = 'Visit the forum. New game ideas are welcome!';
$lang['TIP_15'] = 'Check out the Help section for more information.';
$lang['TIP_16'] = 'Buy/Sell stocks to make more profit (Money -> StockExchange)';
$lang['TIP_17'] = 'Store cash money in the SwissCore bank to receive daily interest.';
$lang['TIP_18'] = 'Complete all continent missions to receive extra skill points.';
$lang['TIP_19'] = 'Repair units (Home -> Restore) to prevent unit loss';
$lang['TIP_20'] = 'Visit the casino to play the Slot Machine and win more cash.';
$lang['TIP_21'] = 'Repair buildings (Home -> Restore) to prevent building loss';
$lang['TIP_22'] = 'Keep playing the game and become the best player of your country!';

$lang['TIP_90'] = 'Only 10 levels away from starting your own moon colony.';
$lang['TIP_91'] = 'Only 9 levels away from starting your own moon colony.';
$lang['TIP_92'] = 'Only 8 levels away from starting your own moon colony.';
$lang['TIP_93'] = 'Only 7 levels away from starting your own moon colony.';
$lang['TIP_94'] = 'Only 6 levels away from starting your own moon colony.';
$lang['TIP_95'] = 'Only 5 levels away from starting your own moon colony.';
$lang['TIP_96'] = 'Only 4 levels away from starting your own moon colony.';
$lang['TIP_97'] = 'Only 3 levels away from starting your own moon colony.';
$lang['TIP_98'] = 'Only 2 levels away from starting your own moon colony.';
$lang['TIP_99'] = 'Only 1 level away from starting your own moon colony.';
$lang['TIP_100'] = 'Start your own moon colony!';

$lang['TIP_140'] = 'Only 10 levels away from starting your own mars colony.';
$lang['TIP_141'] = 'Only 9 levels away from starting your own mars colony.';
$lang['TIP_142'] = 'Only 8 levels away from starting your own mars colony.';
$lang['TIP_143'] = 'Only 7 levels away from starting your own mars colony.';
$lang['TIP_144'] = 'Only 6 levels away from starting your own mars colony.';
$lang['TIP_145'] = 'Only 5 levels away from starting your own mars colony.';
$lang['TIP_146'] = 'Only 4 levels away from starting your own mars colony.';
$lang['TIP_147'] = 'Only 3 levels away from starting your own mars colony.';
$lang['TIP_148'] = 'Only 2 levels away from starting your own mars colony.';
$lang['TIP_149'] = 'Only 1 level away from starting your own mars colony.';
$lang['TIP_150'] = 'Start your own Mars colony!';

$lang['TIP_190'] = 'Only 10 levels away from starting your own mercure colony.';
$lang['TIP_191'] = 'Only 9 levels away from starting your own mercure colony.';
$lang['TIP_192'] = 'Only 8 levels away from starting your own mercure colony.';
$lang['TIP_193'] = 'Only 7 levels away from starting your own mercure colony.';
$lang['TIP_194'] = 'Only 6 levels away from starting your own mercure colony.';
$lang['TIP_195'] = 'Only 5 levels away from starting your own mercure colony.';
$lang['TIP_196'] = 'Only 4 levels away from starting your own mercure colony.';
$lang['TIP_197'] = 'Only 3 levels away from starting your own mercure colony.';
$lang['TIP_198'] = 'Only 2 levels away from starting your own mercure colony.';
$lang['TIP_199'] = 'Only 1 level away from starting your own mercure colony.';
$lang['TIP_200'] = 'Start your own mercure colony!';

$lang['TIP_240'] = 'Only 10 levels away from starting your own neptune colony.';
$lang['TIP_241'] = 'Only 9 levels away from starting your own neptune colony.';
$lang['TIP_242'] = 'Only 8 levels away from starting your own neptune colony.';
$lang['TIP_243'] = 'Only 7 levels away from starting your own neptune colony.';
$lang['TIP_244'] = 'Only 6 levels away from starting your own neptune colony.';
$lang['TIP_245'] = 'Only 5 levels away from starting your own neptune colony.';
$lang['TIP_246'] = 'Only 4 levels away from starting your own neptune colony.';
$lang['TIP_247'] = 'Only 3 levels away from starting your own neptune colony.';
$lang['TIP_248'] = 'Only 2 levels away from starting your own neptune colony.';
$lang['TIP_249'] = 'Only 1 level away from starting your own neptune colony.';
$lang['TIP_250'] = 'Start your own neptune colony!';

/*
** ------------------
** LOGIN PAGE
** ------------------
*/

$lang['LOGIN_MEMBER_TITLE'] = 'Member login';
$lang['LOGIN_REGISTER_TITLE'] = 'Free registration';
$lang['LOGIN_RECOVER_TITLE'] = 'Password recovery';
$lang['LOGIN_FACEBOOK_TITLE'] = 'Facebook';
$lang['LOGIN_MANUAL_TITLE'] = 'Manual';

$lang['LOGIN_PLAYERS'] = 'players';
$lang['LOGIN_REQUESTS'] = 'requests';
$lang['LOGIN_COUNTRIES'] = 'countries';
$lang['LOGIN_ONLINE'] = 'players online';

$lang['LOGIN_PASSWORD'] = 'Password';
$lang['LOGIN_USERNAME'] = 'Username';
$lang['LOGIN_EMAIL'] = 'Email';
$lang['LOGIN_NICKNAME']  = 'Nickname';

$lang['LOGIN_MAINTENANCE_TITLE'] = 'Server maintenance';
$lang['LOGIN_MAINTENANCE'] = 'At the moment, we are undergoing server maintenance. Please come back in 30 minutes. Thank you!';

$lang['LOGIN_LOGOUT'] = 'You are now logged off!'; 
$lang['LOGIN_FAILED'] = 'Wrong username and/or password!';
$lang['LOGIN_BANN'] = 'This user account is locked because of cheating!';
$lang['LOGIN_REGISTER_OK'] = 'User account %s is created!';
$lang['LOGIN_PASSWORD_TO_SHORT'] = 'Password must be at least 6 characters long!';
$lang['LOGIN_USERNAME_TO_SHORT'] = 'Username must be at least 4 characters long!';
$lang['LOGIN_USERNAME_EXIST'] = 'Username %s already exist!';
$lang['LOGIN_EMAIL_EXIST'] = 'Email already registered!';
$lang['LOGIN_EMAIL_INVALID'] = 'Email is invalid! (invalid format)';
$lang['LOGIN_NICKNAME_EXIST'] = 'Nickname %s already in use!';
$lang['LOGIN_NICKNAME_NEEDED'] = 'Nickname must be entered!';
$lang['LOGIN_NEW_PASSWORD_SEND'] = 'New password was sent to your email!';
$lang['LOGIN_EMAIL_UNKNOWN'] = 'Unknown e-mail!';
$lang['LOGIN_BEST_VIEWED'] = 'WarQuest is optimized for the following mobile systems: "Apple iOS, BlackBerry OS, Android OS, Symbian OS, Firefox OS" and internet browsers: "Internet Explorer, Mozilla Firefox, Apple Safari, Opera, Google Chrome". 
This game is best viewed with browser width set to 500px. ';

$lang['LOGIN_NEW_CLIENT_TITLE'] = 'New WarQuest client available!';
$lang['LOGIN_NEW_CLIENT'] = 'You are using an old WarQuest Windows client. Please visit www.plaatsoft.nl to get the newest version.';

$lang['LOGIN_PASSWORD_RESET_NOTE'] = 'If you have forgotten your password, enter your email address and we\'ll send you a new password by email.';

/*
** ------------------
** HOME - OVERVIEW
** ------------------
*/

$lang['HOME_TITLE'] = 'HOME';

$lang['HOME_FLASH_NEWS_TITLE'] = 'Breaking news';

$lang['HOME_LASTEST_FORUM_ITEM'] = 'Latest forum post';

$lang['HOME_INTRO_PLAYERS'] = 'At the moment %s players from %s countries are active, ';
$lang['HOME_INTRO_FIGHTS'] = '%s fights took place and ';
$lang['HOME_INTRO_REQUESTS'] = '%s server requests were handled. ';
		
$lang['HOME_INTRO_TITLE'] = 'Introduction';
$lang['HOME_INTRO_MISSIONS'] = 'Start the game by playing %s ';
$lang['HOME_INTRO_BATTLES'] = 'and fight %s. ';
$lang['HOME_INTRO_UNITS'] = 'When you gain money and experience points you can buy more advanced %s ';
$lang['HOME_INTRO_BUILDINGS'] = ' and %s to get stronger. ';
$lang['HOME_INTRO_ENEMY'] = ' At anytime other players can attack you, so keep your defence updated.';

$lang['HOME_NEW_ANDROID_VERSION'] = 'New app version v%s is available at the Android Market.<br/>Please upgrade!';
$lang['HOME_NEW_WINDOWS_VERSION'] = 'New WarQuest client v%s is available!';
$lang['HOME_CLICK_HERE'] = 'here';
$lang['HOME_CLICK_TEXT'] = 'Click %s to start download.';
$lang['HOME_EMAIL_MISSING'] = 'Please confirm your email address to enable password recovery and to receive important WarQuest notifications.';
$lang['HOME_DAILY_BONUS'] = 'You found %s dollar at an enemy location!';

$lang['HOME_WELCOME'] = 'Welcome';
$lang['HOME_LAST_LOGIN'] = 'Last visit was <b>%s</b> ago.';
$lang['HOME_AWARDS'] = 'Awards';
$lang['HOME_BATTLE_AWARDS_TEXT'] = 'You\'ve earned the following battle awards:';
$lang['HOME_BOUNTY_AWARDS_TEXT'] = 'You\'ve earned the following bounty awards:';
$lang['HOME_REBEL_AWARDS_TEXT'] = 'You\'ve earned the following rebellion award:';
$lang['HOME_OVERVIEW_TITLE']= 'Overview';
$lang['HOME_MAP_TITLE'] = 'continents conquered';
$lang['HOME_MAP_NOTE'] = 'Each continent consist out of three regions which can be conquered through missions.';

$lang['HOME_TRAVEL_TO'] = 'Travel to';

$lang['HOME_INTRO_PLACE1'] = 'You are on <b>%s</b> place on the overall leaderboard '; 
$lang['HOME_INTRO_PLACE2'] = 'and <b>%s</b> place on the <b>%s</b> leaderboard. '; 
$lang['HOME_PLAYERS_ONLINE'] = 'Last 24hs %s players were online.';

$lang['HOME_HOLIDAY'] = 'Holiday';
$lang['HOME_HOLIDAY_PERIOD_ACTIVE'] = 'Holiday period active for %s. Missions, battles, units, buildings and money features are locked during this period!';

/*
** ------------------
** HOME - PROFILE
** ------------------
*/

$lang['PLAYER_TITLE'] = 'PLAYER';
$lang['PLAYER_WIN_LOST_RATE'] = 'Won/Lost ratio';
$lang['PLAYER_BUILDINGS'] = 'Buildings';
$lang['PLAYER_CASH_FLOW'] = 'Cash flow';
$lang['PLAYER_ALLIANCE_SIZE'] = 'Alliance size';
$lang['PLAYER_EXP_POINTS']  = 'Experience points';
$lang['PLAYER_SERVER_REQUEST']  = 'Server requests';
$lang['PLAYER_MISSION_COMPLETED'] = 'Mission completed';
$lang['PLAYER_DEFENSE_STRENGTH']  = 'Defense strength';
$lang['PLAYER_ATTACK_STRENGTH'] = 'Attack strength';
$lang['PLAYER_FIGHTS_LOST'] = 'Fights lost';
$lang['PLAYER_FIGHTS_WON']  = 'Fights won';
$lang['PLAYER_BUILDING_INCOME'] = 'Building income';
$lang['PLAYER_CONTINENT_INCOME'] = 'Continent income';
$lang['PLAYER_BOUNTY_SET'] = 'Bounties set';
$lang['PLAYER_REBELLION_RISE'] = 'Rebellions started';
$lang['PLAYER_UPKEEP']  = 'Unit hourly cost';
$lang['PLAYER_NETTO_INCOME']  = 'Net income';
$lang['PLAYER_STATISTICS']  = 'Statistics'; 
$lang['PLAYER_DISCOUNT_MAINTENANCE']  = 'Discount & Maintenance';
$lang['PLAYER_NAME']  = 'Name'; 
$lang['PLAYER_ID']  = 'Id';
$lang['PLAYER_RANK']  = 'Rank'; 
$lang['PLAYER_OVERVIEW']  = 'Profile'; 
$lang['PLAYER_DISCOUNT_RATE'] = 'Building discount';
$lang['PLAYER_MAINTENANCE_RATE'] = 'Unit maintenance';
$lang['PLAYER_LAST_LOGIN'] = 'Last active (ago)';
$lang['PLAYER_CREATED'] = 'Created (ago)';
$lang['PLAYER_CASINO_PLAYED']  = 'Casino played';
$lang['PLAYER_ADS_SHOWED']  = 'Ads showed';
$lang['PLAYER_TOTAL_HOURLY_INCOME'] = 'Total Hourly Income';

$lang['PLAYER_MONEY_STATUS'] = 'Current assets';
$lang['PLAYER_CASH_MONEY'] = 'Cash';
$lang['PLAYER_BANK'] = 'Bank';

$lang['PLAYER_PLATFORM_BROWSER'] = 'Platform & Browser';
$lang['PLAYER_BROWSER'] = 'Browser';
$lang['PLAYER_BROWSER_VERSION'] = 'Version';
$lang['PLAYER_PLATFORM'] = 'Platform';

$lang['PLAYER_LAST_TWEET'] = 'Last Tweet';

$lang['PLAYER_ATTACK_FORCE'] = 'Overview (%s Attack %s)';
$lang['PLAYER_DEFENSE_FORCE'] = 'Overview (%s Defence %s)';
$lang['PLAYER_ATTACK_TEXT'] = '%s has currently <b>%s</b> allies and can command max <b>%s</b> units. The attack %s has the following units:';
$lang['PLAYER_DEFENSE_TEXT'] = '%s has currently <b>%s</b> allies and can command max <b>%s</b> units. The defence %s has the following units:';
$lang['PLAYER_UNIT'] = 'Unit';
$lang['PLAYER_AMOUNT'] = 'Amount';
$lang['PLAYER_STRENGTH'] = 'Strength';
$lang['PLAYER_ATTACK_SKILLS'] = 'Attack skills';
$lang['PLAYER_DEFENSE_SKILLS'] = 'Defence skills';
$lang['PLAYER_SUB_TOTAL'] = 'Sub total';
$lang['PLAYER_TOTAL'] = 'Total';
$lang['PLAYER_FORCE'] = 'Attack & Defence Strength'; 
$lang['PLAYER_DEPLOYED'] = 'Deployed';

$lang['PLAYER_BUILDING'] = 'Building';
$lang['PLAYER_INCOME'] = 'Income';
$lang['PLAYER_COST'] = 'Cost';
$lang['PLAYER_BUILDING_OVERVIEW'] = 'Building Income Overview';
$lang['PLAYER_BUILDING_TEXT'] = 'Currently, player %s has the following %s income buildings:';
$lang['PLAYER_UPKEEP_COST'] = 'Hourly cost overview';
$lang['PLAYER_UPKEEP_TEXT'] = 'Currently, player %s owns the following %s unit(s):';
$lang['PLAYER_CONTINENT_OVERVIEW'] = 'Continent income overview';
$lang['PLAYER_CONTINENT_TEXT'] = 'Player %s conquered the following %s continent(s):';

$lang['PLAYER_DISCOUNT_OVERVIEW'] = 'Building discount overview';
$lang['PLAYER_BUILDING_TEXT'] = 'Currently, player %s has the following %s discount buildings:';

$lang['PLAYER_MAINTENANCE_OVERVIEW'] = 'Building maintenance overview';
$lang['PLAYER_MAINTENANCE_TEXT'] = 'Currently, player %s has the following %s maintenance buildings:';

$lang['PLAYER_SPY_1'] = 'intel';
$lang['PLAYER_SPY_2'] = 'explorers';
$lang['PLAYER_SPY_3'] = 'explorers';
$lang['PLAYER_SPY_4'] = 'explorers';
$lang['PLAYER_SPY_5'] = 'explorers';
$lang['PLAYER_ESPIONAGE_UNLOCK1'] = 'Unlocked when your %s strength is %s% higher then opponent.';
$lang['PLAYER_ESPIONAGE_UNLOCK2'] = 'Unlocked when your %s strength is equal or higher then opponent.';

/*
** ------------------
** HOME - NEWS
** ------------------
*/

$lang['HOME_BATTLE_TITLE'] = 'News';
$lang['HOME_BATTLE_ATTACK_BY'] = 'You were attacked by the %s of %s.';
$lang['HOME_BATTLE_YOU_WON'] = 'You <b>WON</b>. ';
$lang['HOME_BATTLE_YOU_LOST'] = 'You <b>LOST</b>. ';
$lang['HOME_BATTLE_YOU_EXP'] = 'You gained %s experience ';
$lang['HOME_BATTLE_TOOK_DAMAGE'] = 'and took %s damage.';
$lang['HOME_BATTLE_TAKING_DAMAGE'] = 'and taking %s damage.';
$lang['HOME_BATTLE_YOU_MONEY'] = 'Losing %s dollars ';
$lang['HOME_BATTLE_NO_NEWS'] = 'No battle news available at the moment!'; 

$lang['HOME_BOUNTY_NEWS'] = '%s has set %s dollars on your head. If you get defeated you will lose %s experience points.';

/*
** ------------------
** HOME - MESSAGE
** ------------------
*/

$lang['HOME_MESSAGES_TITLE']= 'Messages';
$lang['HOME_MESSAGE_DELETED'] = 'Message deleted!';
$lang['HOME_NO_MESSAGES'] = 'No player messages available at the moment!'; 

/*
** ------------------
** HOME - SKILLS
** ------------------
*/

$lang['PLAYER_SKILL_SUBTITLE1']  = 'Skill points';
$lang['PLAYER_SKILL_SUBTITLE2']  = 'Skill points [%s available]';
$lang['PLAYER_SKILL_NOTE']  = 'Note: Use skill points to increase attack, defence, health, energy or ammo skills.';
$lang['PLAYER_SKILLS']  = 'Skills'; 
$lang['PLAYER_MAX'] = 'Current'; 
$lang['PLAYER_ATTACK']  = 'ATTACK';
$lang['PLAYER_DEFENSE'] = 'DEFENCE';
$lang['PLAYER_HEALTH']  = 'HEALTH'; 
$lang['PLAYER_ENERGY']  = 'ENERGY'; 
$lang['PLAYER_AMMO']  = 'AMMO'; 

$lang['PLAYER_ATTACK_TIP']  = 'Increase your attack skill to do more damage and win more fights. It takes 1 skill point to increase your attack strength with %s. Decrease your attack skill with %s to get 1 skill point in return.';
$lang['PLAYER_DEFENSE_TIP'] = 'Increase your defence skill to resist against more attacks. It takes 1 skill point to increase your defense strength with %s. Decrease your defence skill with %s to get 1 skill point in return.';
$lang['PLAYER_HEALTH_TIP']  = 'Increase your max health skill to survive long fights. It takes 1 skill point to increase your maximum health level with 10. Decrease your health with 20 to get 1 skill point in return.';
$lang['PLAYER_ENERGY_TIP']  = 'Increase your max energy skill to play more missions. It takes 1 skill point to increase your maximum energy level with 10. Decrease your energy skill with 20 to get 1 skill point in return.';
$lang['PLAYER_AMMO_TIP']  = 'Increase your max ammo skill to increase your fight capacity. It takes 2 skill points to increase your ammo with 1. Decrease your ammo skill with 1 to get 1 skill point in return.';

$lang['PLAYER_SKILL_ACCEPTED1']  = '%s skill increased.';
$lang['PLAYER_SKILL_REJECTED1']  = 'You need %s skill point(s) to change this skill.';
$lang['PLAYER_SKILL_ACCEPTED2']  = '%s skill decreased.';
$lang['PLAYER_SKILL_REJECTED2']  = '%s skill have reach minimal level.';

/*
** ------------------
** HOME - TRADE
** ------------------
*/

$lang['HOME_TRADE_TITLE1'] = 'Trade';

$lang['HOME_TRADE_NOTE']  = 'Note: Purchased gold (see help - donate page) can be exchanged in to skill points, cash money or can be used to improve your health, energy or ammo restore timer.';

$lang['HOME_TRADE_CONDITION'] = 'Current';
$lang['HOME_TRADE_MINIMAL'] = 'Minimal';

$lang['HOME_TRADE1'] = 'Health Timer';
$lang['HOME_TRADE1_NOTE'] = 'Decrease health timer so your health restores faster. It takes %s to decrease your health timer with 5 seconds.';

$lang['HOME_TRADE2'] = 'Energy Timer';
$lang['HOME_TRADE2_NOTE'] = 'Decrease energy timer so your energy restores faster. It takes %s to decrease your energy timer with 5 seconds.';

$lang['HOME_TRADE3'] = 'Ammo Timer';
$lang['HOME_TRADE3_NOTE'] = 'Decrease ammo timer so your ammo restores faster. It takes %s to decrease your ammo timer with 5 seconds.';

$lang['HOME_TRADE4'] = 'Cash';
$lang['HOME_TRADE4_NOTE'] = 'Get cash to buy new units, buildings, etc.. It takes %s to increase your cash with %s dollar.';

$lang['HOME_TRADE5'] = 'Skill Point';
$lang['HOME_TRADE5_NOTE'] = 'Get skill points to improve your attack, defence, health, energy or ammo skill. It takes %s to get 1 skill point.';

$lang['HOME_TRADE_SKILL_POINTS'] = 'skill point(s)';
$lang['HOME_TRADE_IN'] = 'Trade-In';
$lang['HOME_MAX_REACHED'] = 'Max Reached';

$lang['HOME_TRADE_HEALTH_TIMER_TO_LARGE'] = 'Health timer has reached minimum value.';
$lang['HOME_TRADE_ENERGY_TIMER_TO_LARGE'] = 'Energy timer has reached minimum value.';
$lang['HOME_TRADE_AMMO_TIMER_TO_LARGE'] = 'Ammo timer has reached minimum value.';
$lang['HOME_TRADE_SUCCESFULL'] = 'The trade is succesfully processed! ';

$lang['HOME_TRADE_NO_GOLD'] = 'You do not own %s.';

/*
** ------------------
** HOME - RESTORE
** ------------------
*/

$lang['PLAYER_RESTORE_TITLE'] = 'Restore & Repair';
$lang['PLAYER_RESTORE_SUBTITLE1'] = 'Restore';
$lang['PLAYER_RESTORE_SUBTITLE2'] = 'Repair';
$lang['PLAYER_RESTORE_UNLOCKED'] = 'Restore & Repair gets unlocked at level %s.';
$lang['PLAYER_RESTORE_PRICE'] = 'Restore Price';
$lang['PLAYER_RESTORE_PRICE_PER_DAY'] = 'Restore price per day';
$lang['PLAYER_REPAIR_PRICE'] = 'Repair Price';
$lang['PLAYER_RESTORED_FAILED'] = 'You do not have %s dollars to execute this action.';

$lang['PLAYER_HEALTH_TITLE'] = 'Restore Health';
$lang['PLAYER_HEALTH_NOTE'] = 'Pay the hospital to restore your army\'s health completely. Restore can only be used once every 5 minutes. Health also restores by itself over time.';	
$lang['PLAYER_HEALTH_CONDITION'] = 'Health condition';
$lang['PLAYER_HEALTH_RESTORED'] = 'Health restored for %s dollars.';
$lang['PLAYER_HEALTH_CONFIRM'] = 'Do you really want to restore health?';

$lang['PLAYER_ENERGY_TITLE'] = 'Restore energy';
$lang['PLAYER_ENERGY_NOTE'] = 'Pay the oil company to restore your army\'s energy completely. Restore can only be used once every 24 hours. Energy also restores by itself over time. ';	
$lang['PLAYER_ENERGY_CONDITION'] = 'Energy condition';
$lang['PLAYER_ENERGY_RESTORED'] = 'Energy restored for %s dollars.';
$lang['PLAYER_ENERGY_CONFIRM'] = 'Do you really want to restore energy?';

$lang['PLAYER_AMMO_TITLE'] = 'Restore ammo';
$lang['PLAYER_AMMO_NOTE'] = 'Pay the weapon factory to restore your army\'s ammo completely. Restore can only be used once every 24 hours. Ammo also restores by itself over time.';	
$lang['PLAYER_AMMO_CONDITION'] = 'Ammo condition';
$lang['PLAYER_AMMO_RESTORED'] = 'Ammo restored for %s dollars.';
$lang['PLAYER_AMMO_CONFIRM'] = 'Do you really want to restore ammo?';

$lang['PLAYER_CEASE_FIRE_TITLE'] = 'Cease Fire Period';
$lang['PLAYER_CEASE_FIRE_NOTE'] = 'Pay money to start a cease fire period. During this period other players can\'t attack you, nor you can attack others.';	
$lang['PLAYER_CEASE_FIRE_ACTIVATED'] = 'Cease fire period activated for %s dollars.';
$lang['PLAYER_CEASE_FIRE_CONFIRM'] = 'Do you really want to activate cease fire period?';
$lang['PLAYER_HOLIDAY_TITLE'] = 'Holiday Period';
$lang['PLAYER_HOLIDAY_NOTE'] = 'Relax by activating a holiday period. During this period your account is frozen (Missions, Battle, Units and Buildings features are locked) and other players can not attack you.';	
$lang['PLAYER_HOLIDAY_ACTIVATED'] = 'Holiday period activated for %s dollar.';
$lang['PLAYER_HOLIDAY_CONFIRM'] = 'Do you really want to activate a holiday period?';

$lang['PLAYER_UNITS_TITLE'] = 'Repair units';
$lang['PLAYER_UNITS_NOTE'] = 'Repair units of your army. If units condition gets 0% some units will be destroyed and the remaining units are automatically repaired.';	
$lang['PLAYER_UNITS_CONDITION'] = 'Units Condition (UC)';
$lang['PLAYER_UNITS_REPAIRED'] = 'Your units are repaired for %s dollars.';
$lang['PLAYER_UNITS_CONFIRM'] = 'Do you really want to repair your units?';

$lang['PLAYER_BUILDINGS_TITLE'] = 'Repair buildings';
$lang['PLAYER_BUILDINGS_NOTE'] = 'Repair buildings of your base. If buildings condition gets 0%, some buildings will be destroyed and the remaining buildings are automatically repaired.';	
$lang['PLAYER_BUILDINGS_CONDITION'] = 'Buildings Condition (BC)';
$lang['PLAYER_BUILDINGS_REPAIRED'] = 'Your buildings are repaired for %s dollar.';
$lang['PLAYER_BUILDINGS_CONFIRM'] = 'Do you really want to repair your buildings?';

$lang['PLAYER_REBELLION_TITLE'] = 'Restore peace';
$lang['PLAYER_REBELLION_NOTE'] = 'Pay intelligence to end upcoming rebellions in your conquered regions. If Rebellion Condition gets 100% some regions will be lost to rebels and must be reconquered.';	
$lang['PLAYER_REBELLION_CONDITION'] = 'Rebellion Condition (RC)';
$lang['PLAYER_REBELLION_RESTORED'] = 'End rebellion for %s dollars.';
$lang['PLAYER_REBELLION_CONFIRM'] = 'Do you really want to restore peace?';

/*
** ------------------
** HOME - SETTINGS
** ------------------
*/

$lang['SETTING_TITLE'] = 'Settings';
$lang['SETTING_GENERAL1'] = 'General settings 1';
$lang['SETTING_GENERAL2'] = 'General settings 2';

$lang['SETTING_NICKNAME'] = 'WarQuest nickname';
$lang['SETTING_TWITTER'] = 'Twitter account';
$lang['SETTING_LANGUAGE'] = 'Language';
$lang['SETTING_BACKGROUND'] = "Background";
$lang['SETTING_SOUND'] = 'Enable sound (Experimental)';
$lang['SETTING_BOUNTY'] = 'Enable bounty confirmation popup.';
$lang['SETTING_RESTORE'] = 'Enable restore & repair confirmation popup.';
$lang['SETTING_CONDITION'] = 'Enable Unit/Building/Rebel condition information in banner.';
$lang['SETTING_FORUM_SORT'] = 'Enable latest forum post on home overview page.';
$lang['SETTING_SORT1'] = 'Enable newest message on top at forum.';
$lang['SETTING_SORT2'] = 'Enable oldest battle player on top at battle list.';
$lang['SETTING_NO_BOT_NEWS'] = 'Disable robot battle news and notifcations.';
$lang['SETTING_ALLIES_IN_BATTLE_LIST'] = 'Enable allies in battle enemies / bount hunting list.';

$lang['PLAYER_LANG_DUTCH'] = 'Dutch';
$lang['PLAYER_LANG_ENGLISH'] = 'English';
$lang['PLAYER_LANG_GERMAN'] = 'German';
$lang['PLAYER_LANG_ITALIAN'] = 'Italian';
$lang['PLAYER_LANG_ROMANIAN'] = 'Romanian';
$lang['PLAYER_LANG_SPANISH'] = 'Spanish';

$lang['BACKGROUND_0'] = 'Black';
$lang['BACKGROUND_1'] = 'Army Green';
$lang['BACKGROUND_2'] = 'Red Aurora';
$lang['BACKGROUND_3'] = 'Gray Stones';
$lang['BACKGROUND_4'] = 'Pink Circles';
$lang['BACKGROUND_5'] = 'Blue Silk';
$lang['BACKGROUND_6'] = 'Brown';
$lang['BACKGROUND_7'] = 'Pirate';
$lang['BACKGROUND_8'] = 'Modern';
$lang['BACKGROUND_9'] = 'Classic';
$lang['BACKGROUND_10'] = 'Chocolate';
$lang['BACKGROUND_11'] = 'Christmas';
$lang['BACKGROUND_12'] = 'Fireworks';

$lang['PLAYER_GENERAL_CHANGED'] = 'General settings changed!';
$lang['NICKNAME_EXIST'] = 'Nickname already taken!';
$lang['NICKNAME_TO_SHORT'] = 'Nickname must be at least 4 characters long!';
$lang['NICKNAME_NO_SPACE'] = 'Space character(s) in nickname is not allowed!';

$lang['PLAYER_CHANGE_EMAIL'] = 'Email settings';
$lang['PLAYER_NEW_EMAIL'] = 'Email Address';
$lang['PLAYER_NOTIFICATION_ALLIANCE'] = 'Alliance notification by mail';
$lang['PLAYER_NOTIFICATION_COMMENT'] = 'Message notification by mail';
$lang['PLAYER_EMAIL_CHANGED'] = 'Email settings changed';
$lang['PLAYER_EMAIL_EXIST'] = 'Email address is already registered!';
$lang['PLAYER_EMAIL_INVALID'] = 'Email address is not valid (invalid format)!';

$lang['PLAYER_LOGIN_SETTINGS'] = 'Login settings';
$lang['PLAYER_USERNAME'] = 'Username';
$lang['PLAYER_USERNAME_TO_SHORT'] = 'Username must be at least 4 characters long!';
$lang['PLAYER_USERNAME_ALREADY_EXIST'] = 'Username already exist!';
$lang['PLAYER_USERNAME_CHANGED'] = 'Username is changed. Do not forget to change it in the WarQuest Android app and Windows client, otherwise automatic login will not work anymore!';
$lang['PLAYER_CURRENT_PASSWORD'] = 'Current password';		
$lang['PLAYER_NEW_PASSWORD'] = 'New password';
$lang['PLAYER_PASSWORD_CHANGED'] = 'Password is changed. Do not forget to change it in the WarQuest Android app and Windows client, otherwise automatic login will not work anymore!';
$lang['PLAYER_PASSWORD_NO_MATCH'] = 'Current password doesn\'t match!';
$lang['PLAYER_PASSWORD_TO_SHORT'] = 'The new password must be at least 6 characters long!';
$lang['PLAYER_LOGIN_NOTE'] = 'WARNING: Automatic login only works when the same username and password are set in the WarQuest Android app and Windows client!'; 

$lang['SETTING_ACCOUNT_RESET_TITLE'] = 'Account reset';
$lang['SETTING_YES'] = 'Yes';
$lang['SETTING_SURE'] = 'Account reset! Are your really sure?';
$lang['SETTING_ACCOUNT_RESET'] = 'Activate an account reset? ';
$lang['SETTING_NO_REVERSE'] = '(This reset action can not be reversed!)';
$lang['SETTING_ACCOUNT_RESET_NOTE'] = 'WARNING: When your account is resetted all data of your account is put back to the begin state. This means that everything is removed (units, buildings, alliances, missions, etc..)'; 
$lang['SETTING_ACCOUNT_RESETTED'] = 'Player %s account is resetted!';

/*
** ------------------
** MISSION DATA
** ------------------
*/

/* Earth Missions */
$lang['MISSION_GROUP_0'] = 'Training';
$lang['MISSION_GROUP_1'] = 'Europe';
$lang['MISSION_GROUP_2'] = 'N-America';
$lang['MISSION_GROUP_3'] = 'S-America';
$lang['MISSION_GROUP_4'] = 'Africa';
$lang['MISSION_GROUP_5'] = 'N-Asia';
$lang['MISSION_GROUP_6'] = 'S-Asia';
$lang['MISSION_GROUP_7'] = 'E-Asia';
$lang['MISSION_GROUP_8'] = 'Oceania';
$lang['MISSION_GROUP_9'] = 'Mideast';

/* Moon Missions */
$lang['MISSION_GROUP_10'] = 'Alpha ';
$lang['MISSION_GROUP_11'] = 'Beta';
$lang['MISSION_GROUP_12'] = 'Charlie';
$lang['MISSION_GROUP_13'] = 'Delta';
$lang['MISSION_GROUP_14'] = 'Echo';
$lang['MISSION_GROUP_15'] = 'Foxtrot';
$lang['MISSION_GROUP_16'] = 'Golf';
$lang['MISSION_GROUP_17'] = 'Hotel';
$lang['MISSION_GROUP_18'] = 'India';

/* Mars Missions */
$lang['MISSION_GROUP_20'] = 'Alpaca';
$lang['MISSION_GROUP_21'] = 'Bison';
$lang['MISSION_GROUP_22'] = 'Coyote';
$lang['MISSION_GROUP_23'] = 'Dolphin';
$lang['MISSION_GROUP_24'] = 'Emu';
$lang['MISSION_GROUP_25'] = 'Fox';
$lang['MISSION_GROUP_26'] = 'Giraffe';
$lang['MISSION_GROUP_27'] = 'Heron';
$lang['MISSION_GROUP_28'] = 'Iguana';

/* Mercure Missions */
$lang['MISSION_GROUP_30'] = 'Alfred';
$lang['MISSION_GROUP_31'] = 'Benjamin';
$lang['MISSION_GROUP_32'] = 'Charles';
$lang['MISSION_GROUP_33'] = 'David';
$lang['MISSION_GROUP_34'] = 'Edward';
$lang['MISSION_GROUP_35'] = 'Frederick';
$lang['MISSION_GROUP_36'] = 'George';
$lang['MISSION_GROUP_37'] = 'Harry';
$lang['MISSION_GROUP_38'] = 'Isaac';

/* Neptune Missions */
$lang['MISSION_GROUP_40'] = 'Addison';
$lang['MISSION_GROUP_41'] = 'Bella';
$lang['MISSION_GROUP_42'] = 'Caroline';
$lang['MISSION_GROUP_43'] = 'Daniel';
$lang['MISSION_GROUP_44'] = 'Eva';
$lang['MISSION_GROUP_45'] = 'Frederick';
$lang['MISSION_GROUP_46'] = 'Genesis';
$lang['MISSION_GROUP_47'] = 'Hailey';
$lang['MISSION_GROUP_48'] = 'Ian';


/* Earth */
$lang['MISSION_0'] = 'Training mission';
$lang['MISSION_1'] = 'Great Britain Region';
$lang['MISSION_2'] = 'Benelux';
$lang['MISSION_3'] = 'France Region ';
$lang['MISSION_4'] = 'Central Europe';
$lang['MISSION_5'] = 'Scandinavia';
$lang['MISSION_6'] = 'East Europe';
$lang['MISSION_7'] = 'Spain Region';
$lang['MISSION_8'] = 'South Europe';

$lang['MISSION_10'] = 'Greenland';
$lang['MISSION_11'] = 'Canada';
$lang['MISSION_12'] = 'United States';
$lang['MISSION_13'] = 'Mexico';
$lang['MISSION_14'] = 'Guatemala Region';
$lang['MISSION_15'] = 'Nicaragua Region';
$lang['MISSION_16'] = 'Cuba Region';
$lang['MISSION_17'] = 'Caribbean Region';

$lang['MISSION_20'] = 'Middle America';
$lang['MISSION_21'] = 'Ecuador Region';
$lang['MISSION_22'] = 'Bolivia Region';
$lang['MISSION_23'] = 'Paraguay Region';
$lang['MISSION_24'] = 'Chile Region';
$lang['MISSION_25'] = 'Argentina Region';
$lang['MISSION_26'] = 'Uruguay Region';
$lang['MISSION_27'] = 'Brazil Region';

$lang['MISSION_30'] = 'Algeria Region';
$lang['MISSION_31'] = 'Egypt Region';
$lang['MISSION_32'] = 'West Africa Region';
$lang['MISSION_33'] = 'Central Africa Region';
$lang['MISSION_34'] = 'East Africa Region';
$lang['MISSION_35'] = 'Mozambique Region';
$lang['MISSION_36'] = 'Zimbabwe Region';
$lang['MISSION_37'] = 'South Africa Region';

$lang['MISSION_40'] = 'Russia Region';
$lang['MISSION_41'] = 'Mongolia Region';
$lang['MISSION_42'] = 'Kazakhstan Region';
$lang['MISSION_43'] = 'Uzbekistan Region';
$lang['MISSION_44'] = 'Tajikistan Region';
$lang['MISSION_45'] = 'Turkmenistan Region';
$lang['MISSION_46'] = 'Georgia Region';
$lang['MISSION_47'] = 'Armenia Region';

$lang['MISSION_50'] = 'Iran';
$lang['MISSION_51'] = 'Afghanistan';
$lang['MISSION_52'] = 'Pakistan';
$lang['MISSION_53'] = 'India';
$lang['MISSION_54'] = 'Nepal';
$lang['MISSION_55'] = 'Bangladesh Region';
$lang['MISSION_56'] = 'Thailand Region';
$lang['MISSION_57'] = 'Laos Region';

$lang['MISSION_60'] = 'China';
$lang['MISSION_61'] = 'North Korea';
$lang['MISSION_62'] = 'South Korea';
$lang['MISSION_63'] = 'Japan';
$lang['MISSION_64'] = 'Taiwan';
$lang['MISSION_65'] = 'Cambodia Region';
$lang['MISSION_66'] = 'Vietnam Region';
$lang['MISSION_67'] = 'Malaysia';

$lang['MISSION_70'] = 'West Indonesia';
$lang['MISSION_71'] = 'East Indonesia';
$lang['MISSION_72'] = 'Philippines Region';
$lang['MISSION_73'] = 'Papua New Guinea';
$lang['MISSION_74'] = 'Timor';
$lang['MISSION_75'] = 'North Australia';
$lang['MISSION_76'] = 'South Australia';
$lang['MISSION_77'] = 'New Zealand';

$lang['MISSION_80'] = 'Syria';
$lang['MISSION_81'] = 'Iraq';
$lang['MISSION_82'] = 'Saudi Arabia';
$lang['MISSION_83'] = 'Kuwait';
$lang['MISSION_84'] = 'Yemen Region';
$lang['MISSION_85'] = 'Oman Region ';
$lang['MISSION_86'] = 'Jordan';
$lang['MISSION_87'] = 'Israel';

/* Moon */
$lang['MISSION_100'] = 'Crater Endymion';
$lang['MISSION_101'] = 'Crater Franklin';
$lang['MISSION_102'] = 'Sinus Honoris';
$lang['MISSION_103'] = 'Mons Fidei';
$lang['MISSION_104'] = 'Crater Blanc';
$lang['MISSION_105'] = 'Crater Fesenkov';
$lang['MISSION_106'] = 'Montes Temporis';
$lang['MISSION_107'] = 'Crater Darwin';

$lang['MISSION_110'] = 'Crater Agnes';
$lang['MISSION_111'] = 'Mons Andre';
$lang['MISSION_112'] = 'Vallis Ardeshir';
$lang['MISSION_113'] = 'Crater Aristoteles';
$lang['MISSION_114'] = 'Mare Blanc';
$lang['MISSION_115'] = 'Mons Bradley';
$lang['MISSION_116'] = 'Vallis Delisle';
$lang['MISSION_117'] = 'Sinus Dieter';

$lang['MISSION_120'] = 'Mons Dilip';
$lang['MISSION_121'] = 'Mons Esam';
$lang['MISSION_122'] = 'Crater Albategnius';
$lang['MISSION_123'] = 'Mons Gruithuisen Delta';
$lang['MISSION_124'] = 'Mare Gruithuisen Gamma';
$lang['MISSION_125'] = 'Crater Hansteen';
$lang['MISSION_126'] = 'Vallis Herodotus';
$lang['MISSION_127'] = 'Mons Huygens';

$lang['MISSION_130'] = 'Sinus La Hire';
$lang['MISSION_131'] = 'Mons Maraldi';
$lang['MISSION_132'] = 'Mons Moro';
$lang['MISSION_133'] = 'Crater Aristarchus';
$lang['MISSION_134'] = 'Mons Pico';
$lang['MISSION_135'] = 'Vallis Piton';
$lang['MISSION_136'] = 'Sinus Rumker';
$lang['MISSION_137'] = 'Mons Usov';

$lang['MISSION_140'] = 'Mons Vinogradov';
$lang['MISSION_141'] = 'Mons Vitruvius';
$lang['MISSION_142'] = 'Mons Wolff';
$lang['MISSION_143'] = 'Montes Agricola';
$lang['MISSION_144'] = 'Montes Alpes';
$lang['MISSION_145'] = 'Crater Apenninus';
$lang['MISSION_146'] = 'Montes Archimedes';
$lang['MISSION_147'] = 'Montes Carpatus';

$lang['MISSION_150'] = 'Montes Caucasus';
$lang['MISSION_151'] = 'Mare Cordillera';
$lang['MISSION_152'] = 'Montes Haemus';
$lang['MISSION_153'] = 'Crater Harbinger';
$lang['MISSION_154'] = 'Sinus Pyrenaeus';
$lang['MISSION_155'] = 'Montes Riphaeus';
$lang['MISSION_156'] = 'Montes Rook';
$lang['MISSION_157'] = 'Mare Secchi';

$lang['MISSION_160'] = 'Montes Spitzbergen';
$lang['MISSION_161'] = 'Mare Taurus';
$lang['MISSION_162'] = 'Sinus Teneriffe';
$lang['MISSION_163'] = 'Montes Harbinger';
$lang['MISSION_164'] = 'Vallis Rheita';
$lang['MISSION_165'] = 'Vallis Baade';
$lang['MISSION_166'] = 'Crater Bohr';
$lang['MISSION_167'] = 'Vallis Palitzsch';

$lang['MISSION_170'] = 'Crater Fecunditatis';
$lang['MISSION_171'] = 'Mare Australe';
$lang['MISSION_172'] = 'Montes Orientale';
$lang['MISSION_173'] = 'Sinus Cognitum';
$lang['MISSION_174'] = 'Mare Crisium';
$lang['MISSION_175'] = 'Mons Spumans';
$lang['MISSION_176'] = 'Montes Tranquillitatis';
$lang['MISSION_177'] = 'Mare Vaporum';

$lang['MISSION_180'] = 'Crater Aestatis';
$lang['MISSION_181'] = 'Lacus Bonitatis';
$lang['MISSION_182'] = 'Montes Felicitatis';
$lang['MISSION_183'] = 'Sinus Luxuriae';
$lang['MISSION_184'] = 'Lacus Oblivionis';
$lang['MISSION_185'] = 'Mons Solitudinis';
$lang['MISSION_186'] = 'Montes Temporis';
$lang['MISSION_187'] = 'Crater Timoris';

/* Mars */
$lang['MISSION_200'] = 'Crater Al-Qahira';
$lang['MISSION_201'] = 'Sinus Ares';
$lang['MISSION_202'] = 'Vallis Auqakuh';
$lang['MISSION_203'] = 'Crater Bahram';
$lang['MISSION_204'] = 'Mare Harmakhis';
$lang['MISSION_205'] = 'Mons Her Desher';
$lang['MISSION_206'] = 'Sinus Hrad';
$lang['MISSION_207'] = 'Vallis Huo Hsing';

$lang['MISSION_210'] = 'Mons Kasei';
$lang['MISSION_211'] = 'Mare Labou';
$lang['MISSION_212'] = 'Vallis Maadim';
$lang['MISSION_213'] = 'Crater Maja';
$lang['MISSION_214'] = 'Sinus Mamers';
$lang['MISSION_215'] = 'Vallis Mangala';
$lang['MISSION_216'] = 'Crater Marte';
$lang['MISSION_217'] = 'Mare Mawrth';

$lang['MISSION_220'] = 'Crater Nirgal';
$lang['MISSION_221'] = 'Vallis Shalbatana';
$lang['MISSION_222'] = 'Crater Simud';
$lang['MISSION_223'] = 'Sinus Tiu';
$lang['MISSION_224'] = 'Vallis Aloysius';
$lang['MISSION_225'] = 'Crater Ambrosius';
$lang['MISSION_226'] = 'Mare Barnabas';
$lang['MISSION_227'] = 'Mare Constantia';

$lang['MISSION_230'] = 'Vallis Edmondus';
$lang['MISSION_231'] = 'Mare Eustachius';
$lang['MISSION_232'] = 'Crater Georgius';
$lang['MISSION_233'] = 'Sinus Griselda';
$lang['MISSION_234'] = 'Vallis Gualterius';
$lang['MISSION_235'] = 'Crater Homfridus';
$lang['MISSION_236'] = 'Mare Henricus';
$lang['MISSION_237'] = 'Crater Guglielmus';

$lang['MISSION_240'] = 'Mare Janetta';
$lang['MISSION_241'] = 'Vallis Jerominus';
$lang['MISSION_242'] = 'Crater Josephus';
$lang['MISSION_243'] = 'Mare Leonardus';
$lang['MISSION_244'] = 'Sinus Mauritius';
$lang['MISSION_245'] = 'Crater Nicholaus';
$lang['MISSION_246'] = 'Vallis Laurentius';
$lang['MISSION_247'] = 'Mons Octavius';

$lang['MISSION_250'] = 'Crater Misericordia';
$lang['MISSION_251'] = 'Vallis Petronella';
$lang['MISSION_252'] = 'Sinus Sylvanus';
$lang['MISSION_253'] = 'Crater Reginaldus';
$lang['MISSION_254'] = 'Vallis Adeipho';
$lang['MISSION_255'] = 'Sinus Randulphus';
$lang['MISSION_256'] = 'Crater Xpofer';
$lang['MISSION_257'] = 'Mare Aegidius';

$lang['MISSION_260'] = 'Sinus Aeneas';
$lang['MISSION_261'] = 'Crater Philipus';
$lang['MISSION_262'] = 'Sinus Beniaminus';
$lang['MISSION_263'] = 'Vallis Rosamundi';
$lang['MISSION_264'] = 'Mons Peregrinus';
$lang['MISSION_265'] = 'Mare Xtianus';
$lang['MISSION_266'] = 'Vallis Crispianus';
$lang['MISSION_267'] = 'Crater Clementia';

$lang['MISSION_270'] = 'Vallis Elizabeta';
$lang['MISSION_271'] = 'Crater Xtopher';
$lang['MISSION_272'] = 'Mare Placentia';
$lang['MISSION_273'] = 'Sinus Gaufridus';
$lang['MISSION_274'] = 'Crater Stephanus';
$lang['MISSION_275'] = 'Vallis Xpianus	';
$lang['MISSION_276'] = 'Mare Girardus';
$lang['MISSION_277'] = 'Crater Radulphus';

$lang['MISSION_280'] = 'Crater Xtopherus';
$lang['MISSION_281'] = 'Vallis Terentius';
$lang['MISSION_282'] = 'Mons Eamnonn';
$lang['MISSION_283'] = 'Crater Kadisha';
$lang['MISSION_284'] = 'Mare Kachine';
$lang['MISSION_285'] = 'Vallis Oddvar';
$lang['MISSION_286'] = 'Sinus Radborne';
$lang['MISSION_287'] = 'Crater Ebenezer';

/* Mercure */
$lang['MISSION_300'] = 'Crater Albococcinea';
$lang['MISSION_301'] = 'Sinus argentea';
$lang['MISSION_302'] = 'Vallis Atrococcinea';
$lang['MISSION_303'] = 'Crater Colorans';
$lang['MISSION_304'] = 'Mare Cardinalis';
$lang['MISSION_305'] = 'Mons Brunnea';
$lang['MISSION_306'] = 'Sinus Chlorantha';
$lang['MISSION_307'] = 'Vallis Erythrocarpa';

$lang['MISSION_310'] = 'Mons Ferruginea';
$lang['MISSION_311'] = 'Mare Colorans';
$lang['MISSION_312'] = 'Vallis Aurea';
$lang['MISSION_313'] = 'Crater Atrovirens';
$lang['MISSION_314'] = 'Sinus lutescens';
$lang['MISSION_315'] = 'Vallis Maculata';
$lang['MISSION_316'] = 'Crater Nigrescens';
$lang['MISSION_317'] = 'Mare Punicea';

$lang['MISSION_320'] = 'Crater Rosea';
$lang['MISSION_321'] = 'Vallis Rubiginosa';
$lang['MISSION_322'] = 'Crater Tinctoria';
$lang['MISSION_323'] = 'Sinus Sulphurea';
$lang['MISSION_324'] = 'Vallis Sempervirens';
$lang['MISSION_325'] = 'Crater Rubicunda';
$lang['MISSION_326'] = 'Mare Variegata';
$lang['MISSION_327'] = 'Mare Versicolor';

$lang['MISSION_330'] = 'Vallis Vinosa';
$lang['MISSION_331'] = 'Mare Viridescens';
$lang['MISSION_332'] = 'Crater Citrodora';
$lang['MISSION_333'] = 'Sinus Foetidissima';
$lang['MISSION_334'] = 'Vallis Gravaeolens';
$lang['MISSION_335'] = 'Crater Odorata';
$lang['MISSION_336'] = 'Mare Suaveolens';
$lang['MISSION_337'] = 'Crater Ursina';

$lang['MISSION_340'] = 'Mare Amabile';
$lang['MISSION_341'] = 'Vallis Praecox ';
$lang['MISSION_342'] = 'Crater Bella';
$lang['MISSION_343'] = 'Mare Amoena';
$lang['MISSION_344'] = 'Sinus Gracilis';
$lang['MISSION_345'] = 'Crater Formosa';
$lang['MISSION_346'] = 'Vallis Fragilis';
$lang['MISSION_347'] = 'Mons Foeniculaceus';

$lang['MISSION_350'] = 'Crater Blanda';
$lang['MISSION_351'] = 'Vallis Elegantissima';
$lang['MISSION_352'] = 'Sinus Imperialis';
$lang['MISSION_353'] = 'Crater Splendens';
$lang['MISSION_354'] = 'Vallis Superba';
$lang['MISSION_355'] = 'Sinus Magnifica';
$lang['MISSION_356'] = 'Crater Campestris';
$lang['MISSION_357'] = 'Mare Collina';

$lang['MISSION_360'] = 'Sinus Insignis';
$lang['MISSION_361'] = 'Crater Peregrina';
$lang['MISSION_362'] = 'Sinus Mutabilis';
$lang['MISSION_363'] = 'Vallis Spectabilis';
$lang['MISSION_364'] = 'Mons Thermalis';
$lang['MISSION_365'] = 'Mare Gracilis';
$lang['MISSION_366'] = 'Vallis Sinensis';
$lang['MISSION_367'] = 'Crater Pratensis';

$lang['MISSION_370'] = 'Vallis Mirabilis';
$lang['MISSION_371'] = 'Crater Umbrosa ';
$lang['MISSION_372'] = 'Mare Paradoxas';
$lang['MISSION_373'] = 'Sinus Pulchella';
$lang['MISSION_374'] = 'Crater Floribunda';
$lang['MISSION_375'] = 'Vallis Microphylla';
$lang['MISSION_376'] = 'Mare Parviflora';
$lang['MISSION_377'] = 'Crater Venusta';

$lang['MISSION_380'] = 'Crater Monstrosus';
$lang['MISSION_381'] = 'Vallis Septentrionalis';
$lang['MISSION_382'] = 'Mons Occidentalis';
$lang['MISSION_383'] = 'Crater Pulcherrima';
$lang['MISSION_384'] = 'Mare Spectabilis';
$lang['MISSION_385'] = 'Vallis Regia';
$lang['MISSION_386'] = 'Sinus Macrantha';
$lang['MISSION_387'] = 'Crater Caespitosa';

/* Neptune */
$lang['MISSION_400'] = 'Crater Melissa';
$lang['MISSION_401'] = 'Sinus Melitta';
$lang['MISSION_402'] = 'Vallis Methodios';
$lang['MISSION_403'] = 'Crater Metrodora';
$lang['MISSION_404'] = 'Mare Miltiades';
$lang['MISSION_405'] = 'Mons Myron';
$lang['MISSION_406'] = 'Sinus Mnason';
$lang['MISSION_407'] = 'Vallis Myrrine';

$lang['MISSION_410'] = 'Mons Neophytos';
$lang['MISSION_411'] = 'Mare Nereus';
$lang['MISSION_412'] = 'Vallis Nicanor';
$lang['MISSION_413'] = 'Crater Nicolaus';
$lang['MISSION_414'] = 'Sinus Nicomedes';
$lang['MISSION_415'] = 'Vallis Nicostratus';
$lang['MISSION_416'] = 'Crater Nikanor';
$lang['MISSION_417'] = 'Mare Nikephoros';

$lang['MISSION_420'] = 'Crater Olympias';
$lang['MISSION_421'] = 'Vallis Olympiodoros';
$lang['MISSION_422'] = 'Crater Olympos';
$lang['MISSION_423'] = 'Sinus Onesimos';
$lang['MISSION_424'] = 'Vallis Origenes';
$lang['MISSION_425'] = 'Crater Onesiphoros';
$lang['MISSION_426'] = 'Mare Pamphilos';
$lang['MISSION_427'] = 'Mare Pancratius';

$lang['MISSION_430'] = 'Vallis Pantaleon';
$lang['MISSION_431'] = 'Mare Panther';
$lang['MISSION_432'] = 'Crater Pantheras';
$lang['MISSION_433'] = 'Sinus Paramonos';
$lang['MISSION_434'] = 'Vallis Pelagia';
$lang['MISSION_435'] = 'Crater Phaedrus';
$lang['MISSION_436'] = 'Mare Philandros';
$lang['MISSION_437'] = 'Crater Phile';

$lang['MISSION_440'] = 'Mare Sappho';
$lang['MISSION_441'] = 'Vallis Seleucus';
$lang['MISSION_442'] = 'Crater Seleukos';
$lang['MISSION_443'] = 'Mare Socrates';
$lang['MISSION_444'] = 'Sinus Solon';
$lang['MISSION_445'] = 'Crater Sophia';
$lang['MISSION_446'] = 'Vallis Sophocles';
$lang['MISSION_447'] = 'Mons Sosigenes';

$lang['MISSION_450'] = 'Crater Telesphoros';
$lang['MISSION_451'] = 'Vallis Thais';
$lang['MISSION_452'] = 'Sinus Thales';
$lang['MISSION_453'] = 'Crater Themistocles';
$lang['MISSION_454'] = 'Vallis Theocritus';
$lang['MISSION_455'] = 'Sinus Theodora';
$lang['MISSION_456'] = 'Crater Thedotos';
$lang['MISSION_457'] = 'Mare Theokritos';

$lang['MISSION_460'] = 'Sinus Xenia';
$lang['MISSION_461'] = 'Crater Xeno';
$lang['MISSION_462'] = 'Sinus Xenocrarws';
$lang['MISSION_463'] = 'Vallis Xenon';
$lang['MISSION_464'] = 'Mons Xenophon';
$lang['MISSION_465'] = 'Mare Zenais';
$lang['MISSION_466'] = 'Vallis Zeno';
$lang['MISSION_467'] = 'Crater Zenobia';

$lang['MISSION_470'] = 'Vallis Zenon';
$lang['MISSION_471'] = 'Crater Zephyros';
$lang['MISSION_472'] = 'Mare Zoe';
$lang['MISSION_473'] = 'Sinus Zopyros';
$lang['MISSION_474'] = 'Crater Zosime';
$lang['MISSION_475'] = 'Vallis Zosimos';
$lang['MISSION_476'] = 'Mare Zoticus';
$lang['MISSION_477'] = 'Crater Zotikos';

$lang['MISSION_480'] = 'Crater Athanansius';
$lang['MISSION_481'] = 'Vallis Athanasia';
$lang['MISSION_482'] = 'Mons Askleiades';
$lang['MISSION_483'] = 'Crater Artemisois';
$lang['MISSION_484'] = 'Mare Artemisia';
$lang['MISSION_485'] = 'Vallis Arsenius';
$lang['MISSION_486'] = 'Sinus Arkadios';
$lang['MISSION_487'] = 'Crater Aristoteles';

/*
** ------------------
** MISSION PAGE
** ------------------
*/

$lang['MISSION_TITLE'] = 'MISSIONS';

$lang['MISSION_NOTE'] = 'Note: Play missions to gain money and experience points to reach the next level. When a mission is 100% completed you will gain double money. If you conquered 100% the %s continent your hourly income will increase with %s dollars.';

$lang['MISSION_ALLIANCE_SIZE'] = 'alliance size';
$lang['MISSION_GAIN'] = 'Gain';
$lang['MISSION_PART'] = 'Part';
$lang['MISSION_REQUIRED'] = 'Required';
$lang['MISSION_UNLOCK'] = 'Unlocked at level %s';
$lang['MISSION_CHANCE_LOOT'] = 'Chance of loot';

$lang['MISSION_YOU_USED'] = 'You used';
$lang['MISSION_YOU_GAIN'] = 'You gained';
$lang['MISSION_DOLLAR_AND'] = ' dollar and ';
$lang['MISSION_ABORTED'] = 'Mission aborted!';
$lang['MISSION_NO_ENERGY'] = 'You do not have enough energy to complete the mission. Wait a few minutes for your energy to recharge.';
$lang['MISSION_LOW_ALLIANCE'] = 'Your alliance size is too small to play this mission.';
$lang['MISSION_MISSING_UNITS'] = 'You do not have the right amount of units to complete the mission. Missing unit(s): ';
$lang['MISSION_MISSING_UNITS_PRICE'] = 'Total price to buy unit(s) is %s dollar. Hourly cost will increase by %s dollars.';
$lang['MISSION_UNITS_LOST'] = 'During the mission you lost the following unit(s)';
$lang['MISSION_LOOT_WON'] = 'You won the following loot';
$lang['MISSION_UNLOCKED'] = 'Now continue with the battle training.';

$lang['MISSION_CONTINTENT_READY1'] = 'Brilliant! You have completed part %s of %s of the %s continent! ';
$lang['MISSION_CONTINTENT_READY2'] = 'You have received %s extra skill points. ';
$lang['MISSION_CONTINTENT_READY3'] = 'You have finished all parts. Continue with the next continent!';
$lang['MISSION_CONTINTENT_READY4'] = 'Proceed with part %s of this continent!';
$lang['MISSION_COMPLETE_TEXT'] = 'You conquered the following continents so far!';

$lang['MISSION_REBEL'] = 'Rebellion';

$lang['MISSION_COMPLETE_PLANET_1'] = 'Excellent! You completed all Earth missions. You received 100 million dollar bonus.';
$lang['MISSION_COMPLETE_PLANET_2'] = 'Excellent! You completed all moon missions. You received 500 million dollar bonus.';
$lang['MISSION_COMPLETE_PLANET_3'] = 'Excellent! You completed all mars missions. You received 999 billion dollar bonus.';
$lang['MISSION_COMPLETE_PLANET_4'] = 'Excellent! You completed all mercure missions. You received 2500 gold bonus.';
$lang['MISSION_COMPLETE_PLANET_5'] = 'Excellent! You completed all neptune missions. You received 5000 gold bonus.';

$lang['MISSION_NO_MISSIONS'] = 'No missions available yet!';

/*
** ------------------
** BATTLE PAGE
** ------------------
*/

$lang['BATTLE_TITLE'] = 'BATTLE';
$lang['BATTLE_GENERAL_TITLE'] = 'Battle';
$lang['BATTLE_BOUNTY_TITLE'] = 'Bounty Hunting';

$lang['BATTLE_LOST'] = 'Your %s attacked %s. You lost the battle, taking %s damage, while dealing %s to %s.';
$lang['BATTLE_WON'] = 'Your %s attacked %s. You won the battle, taking %s damage while dealing %s to %s. You took %s dollars and gain %s experience points.';
$lang['BATTLE_DEFENDER_HEALTH_LOW'] = '%s surrenders temporarely because health is too low!';
$lang['BATTLE_ATTACKER_HEALTH_LOW'] = 'Your health is too low to battle!. Visit the hospital for instant recovery or wait for automatic health recovery.';
$lang['BATTLE_AMMO_LOW'] = 'You are out of ammo! Wait a few minutes for your ammo to recharge or use skill points to improve ammo skill.';
$lang['BATTLE_UNITS_LOST'] = 'During the battle you lost the following unit(s):';
$lang['BATTLE_BUILDINGS_LOST'] = 'During the battle you lost the following building(s):';
$lang['BATTLE_DEFENSE_FORCE'] = '%s %s defense %s (%s defense strength):'; 
$lang['BATTLE_DEFENSE_BASE'] = '%s defence base:'; 
$lang['BATTLE_ATTACK_FORCE'] = 'Your %s attack %s (%s attack strength):';
$lang['BATTLE_MORE'] = 'more';
$lang['BATTLE_NO_PLAYER_AVAILABLE'] = 'At the moment no player(s) are available for battles.';
$lang['BATTLE_UNLOCKED'] = '%s battle is unlocked at level %s.';
$lang['BATTLE_FIRST_MISSION'] = 'Complete the training mission first.';
$lang['BATTLE_BOUNTY_UNLOCKED'] = '%s bounty hunting is unlocked at level %s.';
$lang['BATTLE_ALLY_NO_ATTACK'] = '<b>%s</b> is an ally. You cannot attack allies.';
$lang['BATTLE_SURRENDER'] = 'Temporarely surrender';

$lang['BATTLE_NOTE1'] = 'Note: Fight other players to gain money and experience points to reach the next level.';
$lang['BATTLE_NOTE2'] = 'Note: Hunt other players to collect their bounty and gain experience points to reach the next level.';

$lang['BATTLE_FORCE_TYPE'] = 'Force:';
$lang['BATTLE_ENEMIES'] = 'Enemies';
$lang['BATTLE_BOUNTY'] = 'Bounty-Hunting';

$lang['BATTLE_NO_BOUNTY_PLAYERS'] = 'At the moment no player(s) with bounty are available for battles.';
$lang['BATTLE_BOUNTY_BONUS'] = 'Extra bounty bonus of %s dollars received.'; 
$lang['BATTLE_HOSPITAL_BONUS'] = '%s surrendered temporarely. You receive %s bonus dollars!'; 
$lang['BATTLE_BOUNTY_LOST'] = 'You were attacked by the %s of %s.You LOST. Losing %s dollar, taking %s damage and losing %s experience points.';
$lang['BATTLE_BOUNTY_CONFIRM'] = 'Do you want to set a bounty for %s dollars?';

$lang['BATTLE_CEASE_FIRE_PERIOD'] = 'Cease fire period is active! No fighting possible. %s';
$lang['BATTLE_AND'] = 'and';
$lang['BATTLE_REBEL_UPDATE1'] = 'Well done, you initiated rebellion for %s in the %s region(s). Below you can see his current situation.';
$lang['BATTLE_REBEL_UPDATE2'] = 'Well done, you increased their rebellion chance for %s to %s%.';
$lang['BATTLE_REBEL_UPDATE3'] = 'Too bad, no region available for rebellion!';

$lang['BATTLE_NO_BOUNTY_MONEY'] = 'You do not have %s dollars to set a bounty on %s head.';
$lang['BATTLE_BOUNTY_SET'] = 'You set %s dollar on %s head and gain 1 experience point. When %s gets defeated, he will lose %s expercience points.'; 

$lang['BATTLE_RANGE'] = 'Players from level %s up to %s are in battle range.';

/*
** ------------------
** UNIT DATA
** ------------------
*/

/* Earth */
$lang['UNIT_GROUP_0']  = 'Army';
$lang['UNIT_GROUP_2']  = 'Cavalry';
$lang['UNIT_GROUP_3']  = 'Navy';
$lang['UNIT_GROUP_4']  = 'Airforce';
$lang['UNIT_GROUP_5']  = 'Citizens';
$lang['UNIT_GROUP_6']  = 'Intel';

/* Moon */
$lang['UNIT_GROUP_7']  = 'Warriors';
$lang['UNIT_GROUP_8']  = 'Drones';
$lang['UNIT_GROUP_9']  = 'Spacecrafts';
$lang['UNIT_GROUP_10'] = 'Citizens';
$lang['UNIT_GROUP_11'] = 'Army';
$lang['UNIT_GROUP_12'] = 'Explorers';

/* Mars */
$lang['UNIT_GROUP_13']  = 'Drones';
$lang['UNIT_GROUP_14']  = 'Warriors';
$lang['UNIT_GROUP_15']  = 'Spacecrafts';
$lang['UNIT_GROUP_16']  = 'Explorers';
$lang['UNIT_GROUP_17'] 	= 'Citizens';
$lang['UNIT_GROUP_18'] 	= 'Army';

/* Mercure*/
$lang['UNIT_GROUP_19']  = 'Drones';
$lang['UNIT_GROUP_20']  = 'Warriors';
$lang['UNIT_GROUP_21']  = 'Spacecrafts';
$lang['UNIT_GROUP_22']  = 'Explorers';
$lang['UNIT_GROUP_23'] 	= 'Citizens';
$lang['UNIT_GROUP_24'] 	= 'Army';

/* Neptune */
$lang['UNIT_GROUP_25']  = 'Drones';
$lang['UNIT_GROUP_26']  = 'Warriors';
$lang['UNIT_GROUP_27']  = 'Spacecrafts';
$lang['UNIT_GROUP_28']  = 'Explorers';
$lang['UNIT_GROUP_29'] 	= 'Citizens';
$lang['UNIT_GROUP_30'] 	= 'Army';

/* ---------------------------------------------------- */

/* Calvary (Earth) - Group 2 */
$lang['UNIT_1'] = 'Minigunner';
$lang['UNIT_101'] = 'Military Car';
$lang['UNIT_102'] = 'Humvee';
$lang['UNIT_103'] = 'Truck';
$lang['UNIT_104'] = 'Light Artillery';
$lang['UNIT_105'] = 'Calvary Carrier';
$lang['UNIT_106'] = 'MGM-51 Shillelagh';
$lang['UNIT_107'] = 'Calvary Transporter';
$lang['UNIT_108'] = 'Assault Vehicle';
$lang['UNIT_109'] = 'SSM Launcher';
$lang['UNIT_110'] = 'Light Hovercraft';
$lang['UNIT_111'] = 'M1 Abrams Tank';
$lang['UNIT_112'] = 'Calvary Vehicle';
$lang['UNIT_113'] = 'Anti-ambush Vehicle';
$lang['UNIT_114'] = 'Heavy Tank';
$lang['UNIT_115'] = 'Leopard 1A1';
$lang['UNIT_116'] = 'HG-544 Vehicle';
$lang['UNIT_117'] = 'Tracked Carrier';
$lang['UNIT_118'] = 'Combat Vehicle';
$lang['UNIT_119'] = 'Hellfire Tank';
$lang['UNIT_120'] = 'Battle Tank';
$lang['UNIT_121'] = 'Mounted Combat System';
$lang['UNIT_122'] = 'Self Propelled Artillery';
$lang['UNIT_123'] = 'Chaparral Tank';
$lang['UNIT_124'] = 'M198 Howitzer';
$lang['UNIT_125'] = 'Heavy Artillery';
$lang['UNIT_126'] = 'Missile Launcher';
$lang['UNIT_127'] = 'Mobile Anti Aircraft';
$lang['UNIT_128'] = 'ICBM Launcher';

/* Navy (Earth) - Group 3 */
$lang['UNIT_201'] = 'Rubber boat';
$lang['UNIT_202'] = 'Transport';
$lang['UNIT_203'] = 'Frigate';
$lang['UNIT_204'] = 'Naval Tanker';
$lang['UNIT_205'] = 'Naval Destroyer';
$lang['UNIT_206'] = 'M80 Stiletto';
$lang['UNIT_207'] = 'Submarine';
$lang['UNIT_208'] = 'Helicopter Carrier';
$lang['UNIT_209'] = 'Battleship';
$lang['UNIT_210'] = 'Houbei Missile ship';
$lang['UNIT_211'] = 'Horizon Frigate';
$lang['UNIT_212'] = 'Type 13 Frigate';
$lang['UNIT_213'] = 'Destroyer';
$lang['UNIT_214'] = 'Scorpene Submarine';
$lang['UNIT_215'] = 'DDG 1000 Destroyer';
$lang['UNIT_216'] = 'Elite Dreadnought';
$lang['UNIT_217'] = 'SPY-1D Destroyer';
$lang['UNIT_218'] = 'Sea Fighter';
$lang['UNIT_219'] = 'HSV-2 Swift';
$lang['UNIT_220'] = 'Missile Cruiser';
$lang['UNIT_221'] = 'UXV Combatant';
$lang['UNIT_222'] = 'Anti Submarine Ship';
$lang['UNIT_223'] = 'Kanimbla AT ship';
$lang['UNIT_224'] = 'Aircraft Carrier';
$lang['UNIT_225'] = 'Landing Platform Dock';
$lang['UNIT_226'] = 'Type 23 Frigate';
$lang['UNIT_227'] = 'Type 28 Frigate';
$lang['UNIT_228'] = 'Nuclear Cruiser';
$lang['UNIT_229'] = 'Ohio ICBM Submarine';

/* Airforce (Earth) - Group 4 */
$lang['UNIT_301'] = 'Cessna 172';
$lang['UNIT_302'] = 'C-17 Cargo plane';
$lang['UNIT_303'] = 'V-22A Osprey Gunship';
$lang['UNIT_304'] = 'AV-8B Harrier Jet';
$lang['UNIT_305'] = 'Comanche Helicopter';
$lang['UNIT_306'] = 'Havoc Helicopter';
$lang['UNIT_307'] = 'Saab JA37 Viggen';
$lang['UNIT_308'] = 'SR-71 Blackbird';
$lang['UNIT_309'] = 'Apache Helicopter';
$lang['UNIT_310'] = 'B-2 Spirit Bomber';
$lang['UNIT_311'] = 'F-18 Super Hornet';
$lang['UNIT_313'] = 'F-15 Silent Eagle';
$lang['UNIT_314'] = 'B-1 Lancer';
$lang['UNIT_316'] = 'F3 Interceptor';
$lang['UNIT_318'] = 'F-16 Falcon';
$lang['UNIT_319'] = 'PAK-FA Fighter';
$lang['UNIT_320'] = 'F-117 Nighthawk';
$lang['UNIT_321'] = 'Boeing NGB Bomber';
$lang['UNIT_322'] = 'F-14 Tomcat';
$lang['UNIT_323'] = 'F-35 Lightning II';
$lang['UNIT_324'] = 'B-52 Stratofortress';
$lang['UNIT_325'] = 'F-22 Raptor';
$lang['UNIT_326'] = 'Trident II Missile';
$lang['UNIT_327'] = 'Titan ICBM Missile';

/* Citizens (Earth) - Group 5 */
$lang['UNIT_401'] = 'Construction Engineer';
$lang['UNIT_402'] = 'Mechanic Engineer';
$lang['UNIT_403'] = 'Lab Engineer';
$lang['UNIT_404'] = 'Manager';
$lang['UNIT_405'] = 'Doctor';
$lang['UNIT_406'] = 'Cook';
$lang['UNIT_407'] = 'Security Guard';

/* Intel (Earth) - Group 6 */
$lang['UNIT_501'] = 'Surveillance Camera';
$lang['UNIT_502'] = 'Marine Intelligence';
$lang['UNIT_503'] = 'Mini Air Drone';
$lang['UNIT_504'] = 'G343 Spy Robot';
$lang['UNIT_505'] = 'Intelligence A3 Crusader';
$lang['UNIT_506'] = 'Spy Fishing Ship';
$lang['UNIT_507'] = 'Hawk Eye';
$lang['UNIT_508'] = 'UK-80 AWACS';
$lang['UNIT_509'] = 'AS-102 Stealth Ship';
$lang['UNIT_510'] = 'US-101 Predator';
$lang['UNIT_511'] = 'Heron Drone';
$lang['UNIT_512'] = 'HG101 Satellite';
$lang['UNIT_513'] = 'Aurora Hypersonic Spy';

/* ---------------------------------------------------- */

/* Warriors (Moon) - Group 7 */
$lang['UNIT_700'] = 'Ahiga I';
$lang['UNIT_701'] = 'Aindrias II';
$lang['UNIT_702'] = 'Aloisius III';
$lang['UNIT_703'] = 'Aloysius IV';
$lang['UNIT_704'] = 'Alvar V';
$lang['UNIT_705'] = 'Aindrias VI';
$lang['UNIT_706'] = 'Cadomedo VII';
$lang['UNIT_707'] = 'Catigernus VIII';
$lang['UNIT_708'] = 'Catutigernos IX';
$lang['UNIT_709'] = 'Cedric X';
$lang['UNIT_710'] = 'Cheveyo XI';
$lang['UNIT_711'] = 'Acis I';

/* Drones (Moon) - Group 8 */
$lang['UNIT_800'] = 'Basic Rover I';
$lang['UNIT_801'] = 'Lunar Transporter II';
$lang['UNIT_802'] = 'Moon Explorer III';
$lang['UNIT_803'] = 'Moon Havostar IV';
$lang['UNIT_804'] = 'Mobile Lab V';
$lang['UNIT_805'] = 'Transporter VI';
$lang['UNIT_805'] = 'Space Crane VII';
$lang['UNIT_806'] = 'Moon Buggy VIII';
$lang['UNIT_807'] = 'Fuel Transporter IX';
$lang['UNIT_808'] = 'Fuel Explorer X';
$lang['UNIT_809'] = 'Moon Explorer XI';
$lang['UNIT_810'] = 'Transporter XII';
$lang['UNIT_811'] = 'Abderus V';

/* Spacecrafts (Moon) - Group 9 */
$lang['UNIT_900'] = 'Moon Cruiser';
$lang['UNIT_901'] = 'Millennium Falcon';
$lang['UNIT_902'] = 'Ebon Hawk';
$lang['UNIT_903'] = 'Transport Robot';
$lang['UNIT_904'] = 'Slave I';
$lang['UNIT_905'] = 'Assault ship';
$lang['UNIT_906'] = 'Corellian corvette';
$lang['UNIT_907'] = 'War Hawk Shadow';
$lang['UNIT_908'] = 'Solar Spacecraft';
$lang['UNIT_909'] = 'Royal starship';
$lang['UNIT_910'] = 'Theta-Class Shuttle';
$lang['UNIT_911'] = 'Trade Cruiser';
$lang['UNIT_912'] = 'Sith Infiltrator';
$lang['UNIT_913'] = 'Imperial landing craft';
$lang['UNIT_914'] = 'Star Skiff II';
$lang['UNIT_915'] = 'Star Destroyer';
$lang['UNIT_916'] = 'Flag Ship';
$lang['UNIT_917'] = 'Adapa III';

/* Citizens (Moon) - Group 10 */
$lang['UNIT_1000'] = 'Astronaut';
$lang['UNIT_1001'] = 'Female';
$lang['UNIT_1002'] = 'Male';

/* Explorers (Moon) - Group 12 */
$lang['UNIT_1200'] = 'Explorer Satellite';
$lang['UNIT_1201'] = 'Explorer Ship';
$lang['UNIT_1202'] = 'Short Range Radar';
$lang['UNIT_1203'] = 'Deepspace Explorer';
$lang['UNIT_1204'] = 'Planet Explorer';
$lang['UNIT_1205'] = 'Space Elevator';
$lang['UNIT_1206'] = 'Astronaut Explorer';
$lang['UNIT_1207'] = 'Long Range Rader';
$lang['UNIT_1208'] = 'Deepspace Relay Station';
$lang['UNIT_1209'] = 'Lightspeed Explorer';
$lang['UNIT_1210'] = 'Planet Destroyer';
$lang['UNIT_1211'] = 'Galaxy Explorer';
$lang['UNIT_1212'] = 'Adonis II';

/* ---------------------------------------------------- */

/* Drones (Mars) - Group 13 */
$lang['UNIT_1300'] = 'Loyce I';
$lang['UNIT_1301'] = 'Labhaoise II';
$lang['UNIT_1302'] = 'Kondo III';
$lang['UNIT_1303'] = 'Kiaskari VI';
$lang['UNIT_1304'] = 'Khalon V';
$lang['UNIT_1305'] = 'Hida VI';
$lang['UNIT_1306'] = 'Irapeke VII';
$lang['UNIT_1307'] = 'Heriberto VIII';
$lang['UNIT_1308'] = 'Kerbasi IX';
$lang['UNIT_1309'] = 'Karna X';
$lang['UNIT_1310'] = 'Bedros XI';

/* Warriors (Mars) - Group 14 */
$lang['UNIT_1400'] = 'Gervaso I';
$lang['UNIT_1401'] = 'Galtero II';
$lang['UNIT_1402'] = 'Gunther III';
$lang['UNIT_1403'] = 'Donnachadh VI';
$lang['UNIT_1404'] = 'Duncan V';
$lang['UNIT_1405'] = 'Eskiminzin VI';
$lang['UNIT_1406'] = 'Fenyang VII';
$lang['UNIT_1407'] = 'Finnegan VIII';
$lang['UNIT_1408'] = 'Clodovea IX';
$lang['UNIT_1409'] = 'Eferhilda X';
$lang['UNIT_1410'] = 'Boreas XI';

/* Spacecrafts (Mars) - Group 15 */
$lang['UNIT_1500'] = 'Caesar I';
$lang['UNIT_1501'] = 'Cocon II';
$lang['UNIT_1502'] = 'Hawk Eye III';
$lang['UNIT_1503'] = 'Ariane IV';
$lang['UNIT_1504'] = 'Gyro V';
$lang['UNIT_1505'] = 'Miner VI';
$lang['UNIT_1506'] = 'Jannus VII';
$lang['UNIT_1507'] = 'Tango VIII';
$lang['UNIT_1508'] = 'Rader IX';
$lang['UNIT_1509'] = 'Eloy  X';
$lang['UNIT_1510'] = 'Basta XI';

/* Explorers (Mars) - Group 16 */
$lang['UNIT_1600'] = 'Cadabyr I';
$lang['UNIT_1601'] = 'Chadwick II';
$lang['UNIT_1602'] = 'Calhoun III';
$lang['UNIT_1603'] = 'Cheveyo IV';
$lang['UNIT_1604'] = 'Clancy V';
$lang['UNIT_1605'] = 'Clodovea VI';
$lang['UNIT_1606'] = 'Cochise VII';
$lang['UNIT_1607'] = 'Czarine VIII';
$lang['UNIT_1608'] = 'Caddawyc IX';
$lang['UNIT_1609'] = 'Chlodwig X';
$lang['UNIT_1610'] = 'Calida XI';

/* Citizens (Mars) - Group 17 */
$lang['UNIT_1700'] = 'Astronaut';
$lang['UNIT_1701'] = 'Female';
$lang['UNIT_1702'] = 'Male';

/* ---------------------------------------------------- */

/* Drones (Mercure) - Group 19 */
$lang['UNIT_1900'] = 'Swify I';
$lang['UNIT_1901'] = 'Euhm II';
$lang['UNIT_1902'] = 'Mirageman III';
$lang['UNIT_1903'] = 'Vereldor IV';
$lang['UNIT_1904'] = 'Maelsius V';
$lang['UNIT_1905'] = 'Suldan VI';
$lang['UNIT_1906'] = 'Jonesy VII';
$lang['UNIT_1907'] = 'Pendejo VIII';
$lang['UNIT_1908'] = 'Vorpal IX';
$lang['UNIT_1909'] = 'Iyona X';
$lang['UNIT_1910'] = 'Castor XI';

/* Warriors (Mercure) - Group 20 */
$lang['UNIT_2000'] = 'Grandmaster I';
$lang['UNIT_2001'] = 'Courage II';
$lang['UNIT_2002'] = 'Hero III';
$lang['UNIT_2003'] = 'Pious IV';
$lang['UNIT_2004'] = 'Stalwart V';
$lang['UNIT_2005'] = 'Bombadil VI';
$lang['UNIT_2006'] = 'Happyelf VII';
$lang['UNIT_2007'] = 'Rainbow VIII';
$lang['UNIT_2008'] = 'MerryLad IX';
$lang['UNIT_2009'] = 'Drenar X';
$lang['UNIT_2010'] = 'Demetrius XI';

/* Spacecrafts (Mercure) - Group 21 */
$lang['UNIT_2100'] = 'Halvilion I';
$lang['UNIT_2101'] = 'Menelaus II';
$lang['UNIT_2102'] = 'Ultimatum III';
$lang['UNIT_2103'] = 'Erudur IV';
$lang['UNIT_2104'] = 'Banbelion V';
$lang['UNIT_2105'] = 'Nimtharadon VI';
$lang['UNIT_2106'] = 'Voronthil VII';
$lang['UNIT_2107'] = 'Anion VIII';
$lang['UNIT_2108'] = 'Partharaon IX';
$lang['UNIT_2109'] = 'Erudil X';
$lang['UNIT_2110'] = 'Dice XI';

/* Explorers (Mercure) - Group 22 */
$lang['UNIT_2200'] = 'Girlyman I';
$lang['UNIT_2201'] = 'Wuss II';
$lang['UNIT_2202'] = 'Sissy III';
$lang['UNIT_2203'] = 'Tauren IV';
$lang['UNIT_2204'] = 'Hykon V';
$lang['UNIT_2205'] = 'Talenx VI';
$lang['UNIT_2206'] = 'Dazra VII';
$lang['UNIT_2207'] = 'Hexa VIII';
$lang['UNIT_2208'] = 'Marest IX';
$lang['UNIT_2209'] = 'Rawrgrable X';
$lang['UNIT_2210'] = 'Dinos XI';

/* Citizens (Mercure) - Group 23 */
$lang['UNIT_2300'] = 'Astronaut';
$lang['UNIT_2301'] = 'Female';
$lang['UNIT_2302'] = 'Male';

/* ---------------------------------------------------- */

/* Drones (Neptune) - Group 24 */
$lang['UNIT_2400'] = 'Acacius I';
$lang['UNIT_2401'] = 'Basilius II';
$lang['UNIT_2402'] = 'Callias III';
$lang['UNIT_2403'] = 'Diodotus IV';
$lang['UNIT_2404'] = 'Eirenaios V';
$lang['UNIT_2405'] = 'Gaiana VI';
$lang['UNIT_2406'] = 'Helena VII';
$lang['UNIT_2407'] = 'Iason VIII';
$lang['UNIT_2408'] = 'Kallias IX';
$lang['UNIT_2409'] = 'Leontius X';

/* Warriors (Mercure) - Group 25 */
$lang['UNIT_2500'] = 'Achaikos I';
$lang['UNIT_2501'] = 'Berenice II';
$lang['UNIT_2502'] = 'Cassander III';
$lang['UNIT_2503'] = 'Diogenes IV';
$lang['UNIT_2504'] = 'Eirene V';
$lang['UNIT_2505'] = 'Galenos VI';
$lang['UNIT_2506'] = 'Heliodoros VII';
$lang['UNIT_2507'] = 'Irenaeus VIII';
$lang['UNIT_2508'] = 'Kallikrates IX';
$lang['UNIT_2509'] = 'Linos X';

/* Spacecrafts (Neptune) - Group 26 */
$lang['UNIT_2600'] = 'Aeschylus I';
$lang['UNIT_2601'] = 'Berenike II';
$lang['UNIT_2602'] = 'Charis III';
$lang['UNIT_2603'] = 'Diokles IV';
$lang['UNIT_2604'] = 'Epaphras V';
$lang['UNIT_2605'] = 'Gennadius VI';
$lang['UNIT_2606'] = 'Heracleitus VII';
$lang['UNIT_2607'] = 'Isocrates VIII';
$lang['UNIT_2608'] = 'Kallistos IX';
$lang['UNIT_2609'] = 'Loukianos X';

/* Explorers (Neptune) - Group 27 */
$lang['UNIT_2700'] = 'Aesop I';
$lang['UNIT_2701'] = 'Beerlos II';
$lang['UNIT_2702'] = 'Charmion III';
$lang['UNIT_2703'] = 'Dion IV';
$lang['UNIT_2704'] = 'Erasmos V';
$lang['UNIT_2705'] = 'Georgius VI';
$lang['UNIT_2706'] = 'Heraclius VII';
$lang['UNIT_2707'] = 'Isidoros VIII';
$lang['UNIT_2708'] = 'Karpos IX';
$lang['UNIT_2709'] = 'Lykourgos X';

/* Citizens (Neptune) - Group 28 */
$lang['UNIT_2800'] = 'Astronaut';
$lang['UNIT_2801'] = 'Female';
$lang['UNIT_2802'] = 'Male';

/*
** ------------------
** UNIT PAGE
** ------------------
*/

$lang['UNIT_TITLE'] = 'UNITS';

$lang['UNIT_NOTE_1'] = 'Note: Buy soldier units to enable missions.';
$lang['UNIT_NOTE_2'] = 'Note: Buy calvary units to improve your calvary force strength. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_3'] = 'Note: Buy navy units to improve your naval force strength. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_4'] = 'Note: Buy airfoce units to improve your airforce strength. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_6'] = 'Note: Buy intel units to improve  your intel force strength. Battle, win to start rebellions on Earth regions and steal money from your opponent\'s Trasquera or SwissCore bank account.';

$lang['UNIT_NOTE_8'] = 'Note: Buy moon drone units to improve your drone force strength. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_7'] = 'Note: Buy moon warrior units to improve your warrior force strength. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_9'] = 'Note: Buy moon spacecraft units to improve your spacecraft force strength. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_12'] = 'Note: Buy moon explore units to improve your explorer force strength. Battle, win to start rebellions and steal money from your opponent\'s Trasquera or SwissCore bank account.';

$lang['UNIT_NOTE_13'] = 'Note: Buy mars drone units to improve your drone force strength. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_14'] = 'Note: Buy mars warrior units to improve your warrior force strenght. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_15'] = 'Note: Buy mars spacecraft units to improve your spacecraft force strength. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_16'] = 'Note: Buy mars explore units to improve your explorers force strength. Battle, win to start rebellions and steal some money from your opponent\'s Trasquera or SwissCore bank account.';

$lang['UNIT_NOTE_19'] = 'Note: Buy mercure drone units to improve your drone force strength. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_20'] = 'Note: Buy mercure warrior units to improve your warrior force strenght. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_21'] = 'Note: Buy mercure spacecraft units to improve your spacecraft force strength. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_22'] = 'Note: Buy mercure explore units to improve your explorers force strength. Batlle, win to start rebellions and steal some money from your opponent\'s Trasquera or SwissCore bank account.';

$lang['UNIT_NOTE_25'] = 'Note: Buy neptune drone units to improve your drone force strength. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_26'] = 'Note: Buy neptune warrior units to improve your warrior force strenght. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_27'] = 'Note: Buy neptune spacecraft units to improve your spacecraft force strength. Battle, win and steal money from your opponent\'s cash account.';
$lang['UNIT_NOTE_28'] = 'Note: Buy neptune explore units to improve your explorers force strength. Batlle, win to start rebellions and steal some money from your opponent\'s Trasquera or SwissCore bank account.';


$lang['UNIT_DISBAND'] = 'You disbanded %s %s for %s. Still %s deployed.';
$lang['UNIT_DISBAND_FAILED'] = 'You do not own %s %s. Still %s deployed.';

$lang['UNIT_DEPLOY'] = 'You deploy %s %s for %s. Now %s deployed.';
$lang['UNIT_NO_UPKEEP'] = 'Not enough hourly income to fund %s %s.';
$lang['UNIT_NO_FUNDS'] = 'Not enough funds to buy %s %s for %s.';
$lang['UNIT_MAX'] = 'No more then %s %s(s) allowed!';

$lang['UNITS_NO_UNITS'] = 'No units available yet!';

/*
** ------------------
** BUILDING DATA
** ------------------
*/

/* Earth Buildings */
$lang['BUILDING_GROUP_1']  = 'Income';
$lang['BUILDING_GROUP_2']  = 'Defence';
$lang['BUILDING_GROUP_3']  = 'Energy';
$lang['BUILDING_GROUP_4']  = 'Discount';
$lang['BUILDING_GROUP_5']  = 'Maintenance';

/* Moon Buildings */
$lang['BUILDING_GROUP_6']  = 'Income';
$lang['BUILDING_GROUP_7']  = 'Defence';
$lang['BUILDING_GROUP_8']  = 'Energy';
$lang['BUILDING_GROUP_9']  = 'Discount';
$lang['BUILDING_GROUP_10'] = 'Maintenance';

/* Mars Buildings */
$lang['BUILDING_GROUP_11'] = 'Income';
$lang['BUILDING_GROUP_12'] = 'Defence';
$lang['BUILDING_GROUP_13'] = 'Energy';
$lang['BUILDING_GROUP_14'] = 'Discount';
$lang['BUILDING_GROUP_15'] = 'Maintenance';

/* Mercure Buildings */
$lang['BUILDING_GROUP_16'] = 'Income';
$lang['BUILDING_GROUP_17'] = 'Defence';
$lang['BUILDING_GROUP_18'] = 'Energy';
$lang['BUILDING_GROUP_19'] = 'Discount';
$lang['BUILDING_GROUP_20'] = 'Maintenance';

/* Neptune Buildings */
$lang['BUILDING_GROUP_21'] = 'Income';
$lang['BUILDING_GROUP_22'] = 'Defence';
$lang['BUILDING_GROUP_23'] = 'Energy';
$lang['BUILDING_GROUP_24'] = 'Discount';
$lang['BUILDING_GROUP_25'] = 'Maintenance';

/* ------------------------------------------------------ */

/* Income (Earth) - Group 1 */
$lang['BUILDING_1']  = 'Supply Depot';
$lang['BUILDING_3']  = 'Refinery';
$lang['BUILDING_6']  = 'Weapons Factory';
$lang['BUILDING_8']  = 'Communications Center';
$lang['BUILDING_24'] = 'Bio Science Factory';
$lang['BUILDING_12'] = 'Oil Rig';
$lang['BUILDING_14'] = 'Military Research Lab';
$lang['BUILDING_16'] = 'Nuclear Testing Facility';
$lang['BUILDING_25'] = 'Water Treatment Facility';
$lang['BUILDING_17'] = 'Solar Satellite Network';

/* Defence (Earth) - Group 2 - Calvary */
$lang['BUILDING_2']  = 'Bunker';
$lang['BUILDING_5']  = 'Tank wall';
$lang['BUILDING_11'] = 'Guard tower';
$lang['BUILDING_15'] = 'Land minefield';
$lang['BUILDING_56'] = 'Nuclear bomb bunker';

/* Defence (Earth) - Group 2 - Navy */
$lang['BUILDING_21'] = 'Coast Bunker';
$lang['BUILDING_22'] = 'Torpedo launcher';
$lang['BUILDING_23'] = 'Sea minefield';
$lang['BUILDING_57'] = 'Navy shipyard';

/* Defence (Earth) - Group 2 - Airforce */
$lang['BUILDING_7']  = 'Anti Aircraft gun';
$lang['BUILDING_9']  = 'Short range launcher';
$lang['BUILDING_20'] = 'Long range launcher';
$lang['BUILDING_58'] = 'Military airfield';

/* Defence (Earth) - Group 2 - Intel */
$lang['BUILDING_51'] = 'Embassy';
$lang['BUILDING_52'] = 'Intel command center';
$lang['BUILDING_53'] = 'Drone control center';
$lang['BUILDING_54'] = 'Cyberspace warfare';
$lang['BUILDING_59'] = 'Spy Radar';

/* Energy (Earth) - Group 3 */
$lang['BUILDING_4']  = 'Solar power unit';
$lang['BUILDING_10'] = 'Mobile generator';
$lang['BUILDING_13'] = 'Gas power facility';
$lang['BUILDING_18'] = 'Eolic power farm';
$lang['BUILDING_19'] = 'Oil extractors';
$lang['BUILDING_26'] = 'Solar power facility';
$lang['BUILDING_27'] = 'Offshore eolic power farm';
$lang['BUILDING_28'] = 'Geothermal energy facility';
$lang['BUILDING_35'] = 'Hydro power dam';
$lang['BUILDING_39'] = 'Nuclear power facility';

/* Discount (Earth) - Group 4 */
$lang['BUILDING_29'] = 'Army field mess';
$lang['BUILDING_40'] = 'Military supply depot';
$lang['BUILDING_37'] = 'Mobile hospital';
$lang['BUILDING_38'] = 'Command center';
$lang['BUILDING_30'] = 'Military bootcamp';
$lang['BUILDING_31'] = 'Military academy';
$lang['BUILDING_32'] = 'Recreation facility';
$lang['BUILDING_33'] = 'Military Statue';
$lang['BUILDING_34'] = 'Military headquarters';
$lang['BUILDING_36'] = 'President\'s office';

/* Maintenance (Earth) - Group 5 */
$lang['BUILDING_41'] = 'Road maintenance';
$lang['BUILDING_42'] = 'Bridge maintenance';
$lang['BUILDING_43'] = 'Transport vehicle garage';
$lang['BUILDING_44'] = 'Helicopter hangar';
$lang['BUILDING_45'] = 'Vehicle garage';
$lang['BUILDING_46'] = 'Navy ship dock';
$lang['BUILDING_47'] = 'Building maintenance';
$lang['BUILDING_48'] = 'Submarine dock';
$lang['BUILDING_49'] = 'Power facility maintenance';
$lang['BUILDING_50'] = 'Airplane hangar';

/* ------------------------------------------------------ */

/* Income (Moon) - Group 6 */
$lang['BUILDING_600'] = 'General base';
$lang['BUILDING_601'] = 'Explore & Research center';
$lang['BUILDING_602'] = 'Personel quarters';
$lang['BUILDING_603'] = 'Oxygen factory';
$lang['BUILDING_604'] = 'Water factory';
$lang['BUILDING_605'] = 'Communication center';
$lang['BUILDING_606'] = 'Greenhouse';
$lang['BUILDING_607'] = 'Construction factory';
$lang['BUILDING_608'] = 'Metal extraction center';
$lang['BUILDING_609'] = 'Spacecraft launch center';
$lang['BUILDING_610'] = 'Lunar hospital';
$lang['BUILDING_611'] = 'Terraforming centre';

/* Defence (Moon) - Group 7 */
$lang['BUILDING_700'] = 'Defence research center';
$lang['BUILDING_701'] = 'Drone factory';
$lang['BUILDING_702'] = 'Short range missile';
$lang['BUILDING_703'] = 'Warrior factory';
$lang['BUILDING_704'] = 'Early Warning system';
$lang['BUILDING_705'] = 'Long range laser';
$lang['BUILDING_706'] = 'Spacecraft factory';
$lang['BUILDING_707'] = 'Energy shield';
$lang['BUILDING_708'] = 'Nuclear missile launcher';
$lang['BUILDING_709'] = 'Tasers weapon factory';
$lang['BUILDING_710'] = 'Photonic weapon factory';
$lang['BUILDING_711'] = 'Mobile android defender';
$lang['BUILDING_712'] = 'Colony defence shield';
$lang['BUILDING_713'] = 'Underground factory';
$lang['BUILDING_714'] = 'Spacecraft launcher';

$lang['BUILDING_716'] = 'Research Lab';
$lang['BUILDING_717'] = 'Mine explorer unit';
$lang['BUILDING_718'] = 'Photon research lab';
$lang['BUILDING_719'] = 'Explorer Village';

/* Energy (Moon) - Group 8 */
$lang['BUILDING_800'] = 'Gas research center';
$lang['BUILDING_801'] = 'Petroleum research center';
$lang['BUILDING_802'] = 'Gas extractors';
$lang['BUILDING_803'] = 'Petroleum extractors';
$lang['BUILDING_804'] = 'Solar power facility';
$lang['BUILDING_805'] = 'Gas power facility';
$lang['BUILDING_806'] = 'Mini orbit solar facility';
$lang['BUILDING_807'] = 'Nuclear power facility';
$lang['BUILDING_808'] = 'Large orbit solar facility';
$lang['BUILDING_809'] = 'Mini space colony';
$lang['BUILDING_810'] = 'Solar grid system';
$lang['BUILDING_811'] = 'Large space colony';

/* Discount (Moon) - Group 9 */
$lang['BUILDING_900'] = 'Skyscraper';
$lang['BUILDING_901'] = 'Bridge';
$lang['BUILDING_902'] = 'Village';
$lang['BUILDING_903'] = 'Headquarters';
$lang['BUILDING_904'] = 'Volcano base';
$lang['BUILDING_905'] = 'City';
$lang['BUILDING_906'] = 'Bootcamp';
$lang['BUILDING_907'] = 'Missile launchers';
$lang['BUILDING_908'] = 'President\'s Office';
$lang['BUILDING_909'] = 'Military academy';
$lang['BUILDING_910'] = 'Recreation facility';
$lang['BUILDING_911'] = 'Command center';

/* Maintenance (Moon) - Group 10 */
$lang['BUILDING_1000'] = 'Architect design center';
$lang['BUILDING_1001'] = 'Drone repair center';
$lang['BUILDING_1002'] = 'Missile repair center';
$lang['BUILDING_1003'] = 'Explore repair center';
$lang['BUILDING_1004'] = 'Vehicle repair center';
$lang['BUILDING_1005'] = 'Warrior repair center';
$lang['BUILDING_1006'] = 'Infra repair center';
$lang['BUILDING_1007'] = 'Unit repair center';
$lang['BUILDING_1008'] = 'Power repair center';
$lang['BUILDING_1009'] = 'Robot repair center';

/* ------------------------------------------------------ */

/* Income (Mars) - Group 11 */
$lang['BUILDING_1100'] = 'General base';
$lang['BUILDING_1101'] = 'Research center';
$lang['BUILDING_1102'] = 'Oxygen factory';
$lang['BUILDING_1103'] = 'Personel quarters';
$lang['BUILDING_1104'] = 'Water factory';
$lang['BUILDING_1105'] = 'Metal extration center';
$lang['BUILDING_1106'] = 'Communication center';
$lang['BUILDING_1107'] = 'Converance center';
$lang['BUILDING_1108'] = 'Greenhouse';
$lang['BUILDING_1109'] = 'Hotel';

/* Defense (Mars) - Group 12 */
$lang['BUILDING_1200'] = 'Research center';
$lang['BUILDING_1201'] = 'Weapon factory';
$lang['BUILDING_1202'] = 'Short range missile';
$lang['BUILDING_1203'] = 'Drones factory';
$lang['BUILDING_1204'] = 'Early Warning system';
$lang['BUILDING_1205'] = 'Spacecraft factory';
$lang['BUILDING_1206'] = 'Alien Detect unit';
$lang['BUILDING_1207'] = 'Photonic weapon factory';
$lang['BUILDING_1208'] = 'Long range launcher';
$lang['BUILDING_1209'] = 'Tasers weapon factory';
$lang['BUILDING_1210'] = 'Explorer factory';

$lang['BUILDING_1211'] = 'Drone upgrade lab';
$lang['BUILDING_1212'] = 'Warrior upgrade lab';
$lang['BUILDING_1213'] = 'Greenhouse Lab';
$lang['BUILDING_1214'] = 'Explorer training center';

/* Energy (Mars) - Group 13 */
$lang['BUILDING_1300'] = 'Energy research center';
$lang['BUILDING_1301'] = 'Gas power facility';
$lang['BUILDING_1302'] = 'Petroleum research center';
$lang['BUILDING_1303'] = 'Petroleum extractors';
$lang['BUILDING_1304'] = 'Solar power facility';
$lang['BUILDING_1305'] = 'Gas extractors';
$lang['BUILDING_1306'] = 'Mining center';
$lang['BUILDING_1307'] = 'Nuclear power facility';
$lang['BUILDING_1308'] = 'Large orbit solar facility';
$lang['BUILDING_1309'] = 'Large mars colony';

/* Discount (Mars) - Group 14 */
$lang['BUILDING_1400'] = 'Training center';
$lang['BUILDING_1401'] = 'Terraforming center';
$lang['BUILDING_1402'] = 'Village';
$lang['BUILDING_1403'] = 'Headquarters';
$lang['BUILDING_1404'] = 'Supply depot';
$lang['BUILDING_1405'] = 'Construction unit';
$lang['BUILDING_1406'] = 'Bootcamp';
$lang['BUILDING_1407'] = 'President\'s office';
$lang['BUILDING_1408'] = 'Command center';

/* Maintenance (Mars) - Group 15 */
$lang['BUILDING_1500'] = 'Architect design center';
$lang['BUILDING_1501'] = 'Drone repair center';
$lang['BUILDING_1502'] = 'Missile repair center';
$lang['BUILDING_1503'] = 'Explore repair center';
$lang['BUILDING_1504'] = 'Vehicle repair center';
$lang['BUILDING_1505'] = 'Warrior repair center';
$lang['BUILDING_1506'] = 'Infra repair center';
$lang['BUILDING_1507'] = 'Unit repair center';
$lang['BUILDING_1508'] = 'Power repair center';
$lang['BUILDING_1509'] = 'Robot repair center';

/* ------------------------------------------------------ */

/* Income (Mercure) - Group 16 */
$lang['BUILDING_1600'] = 'General base';
$lang['BUILDING_1601'] = 'Research center';
$lang['BUILDING_1602'] = 'Oxygen factory';
$lang['BUILDING_1603'] = 'Personel quarters';
$lang['BUILDING_1604'] = 'Water factory';
$lang['BUILDING_1605'] = 'Metal extration center';
$lang['BUILDING_1606'] = 'Communication center';
$lang['BUILDING_1607'] = 'Converance center';
$lang['BUILDING_1608'] = 'Greenhouse';
$lang['BUILDING_1609'] = 'Hotel';

/* Defense (Mercure) - Group 17 */
$lang['BUILDING_1700'] = 'Research center';
$lang['BUILDING_1701'] = 'Weapon factory';
$lang['BUILDING_1702'] = 'Short range missile';
$lang['BUILDING_1703'] = 'Explorer factory';
$lang['BUILDING_1704'] = 'Early Warning system';
$lang['BUILDING_1705'] = 'Warrior factory';
$lang['BUILDING_1706'] = 'Alien Detect unit';
$lang['BUILDING_1707'] = 'Long range launcher';
$lang['BUILDING_1708'] = 'Photonic weapon factory';
$lang['BUILDING_1709'] = 'Tasers weapon factory';
$lang['BUILDING_1710'] = 'Drone factory';
$lang['BUILDING_1711'] = 'Warrior Upgrade lab';
$lang['BUILDING_1712'] = 'Solar attack unit';
$lang['BUILDING_1713'] = 'Planet Destroyer';

/* Energy (Mercure) - Group 18 */
$lang['BUILDING_1800'] = 'Gas power facility';
$lang['BUILDING_1801'] = 'Energy research center';
$lang['BUILDING_1802'] = 'Petroleum extractors';
$lang['BUILDING_1803'] = 'Petroleum research center';
$lang['BUILDING_1804'] = 'Solar power facility';
$lang['BUILDING_1805'] = 'Mining center';
$lang['BUILDING_1806'] = 'Gas extractors';
$lang['BUILDING_1807'] = 'Nuclear power facility';
$lang['BUILDING_1808'] = 'Large orbit solar facility';
$lang['BUILDING_1809'] = 'Large colony';

/* Discount (Mercure) - Group 19 */
$lang['BUILDING_1900'] = 'Training center';
$lang['BUILDING_1901'] = 'Terraforming center';
$lang['BUILDING_1902'] = 'Military personel quarters';
$lang['BUILDING_1903'] = 'Military headquarters';
$lang['BUILDING_1904'] = 'Supply depot';

/* Maintenance (Mercure) - Group 20 */
$lang['BUILDING_2000'] = 'Architect design center';
$lang['BUILDING_2001'] = 'Drone repair center';
$lang['BUILDING_2002'] = 'Warrior repair center';
$lang['BUILDING_2003'] = 'Spacecraft repair center';
$lang['BUILDING_2004'] = 'Explorer repair center';

/* ------------------------------------------------------ */

/* Income (Neptune) - Group 21 */
$lang['BUILDING_2100'] = 'Personel quarters';
$lang['BUILDING_2101'] = 'Oxygen factory';
$lang['BUILDING_2102'] = 'Water factory';
$lang['BUILDING_2103'] = 'General base';
$lang['BUILDING_2104'] = 'Research center';
$lang['BUILDING_2105'] = 'Metal extration center';

/* Defense (Neptune) - Group 22 */
$lang['BUILDING_2200'] = 'Drone research center';
$lang['BUILDING_2201'] = 'Drone factory';
$lang['BUILDING_2202'] = 'Drone control center';
$lang['BUILDING_2203'] = 'Warrior Research center';
$lang['BUILDING_2204'] = 'Warrior factory';
$lang['BUILDING_2205'] = 'Warrior control center';
$lang['BUILDING_2206'] = 'Spacecraft research center';
$lang['BUILDING_2207'] = 'Spacecraft factory';
$lang['BUILDING_2208'] = 'Spacecraft control center';
$lang['BUILDING_2209'] = 'Explorer research center';
$lang['BUILDING_2210'] = 'Explorer factory';
$lang['BUILDING_2211'] = 'Explorer control center';

/* Energy (Neptune) - Group 23 */
$lang['BUILDING_2300'] = 'Water power plant';
$lang['BUILDING_2301'] = 'Gas power facility';
$lang['BUILDING_2302'] = 'Petroleum research center';
$lang['BUILDING_2303'] = 'Petroleum extractors';
$lang['BUILDING_2304'] = 'Solar power facility';
$lang['BUILDING_2305'] = 'Gas extractors';
$lang['BUILDING_2306'] = 'Mining center';
$lang['BUILDING_2307'] = 'Nuclear power facility';
$lang['BUILDING_2308'] = 'Orbit solar facility';
$lang['BUILDING_2309'] = 'Ice energy converter';

/* Discount (Neptune) - Group 24 */
$lang['BUILDING_2400'] = 'Military center';
$lang['BUILDING_2401'] = 'Military headquarters';
$lang['BUILDING_2402'] = 'Training center';
$lang['BUILDING_2403'] = 'Research lab';
$lang['BUILDING_2404'] = 'Resource center';

/* Maintenance (Neptune) - Group 25 */
$lang['BUILDING_2500'] = 'Drone repair center';
$lang['BUILDING_2501'] = 'Warrior repair center';
$lang['BUILDING_2502'] = 'Spacecraft repair center';
$lang['BUILDING_2503'] = 'Architect design center';
$lang['BUILDING_2504'] = 'Explorer repair center';

/*
** ------------------
** BUILDING PAGE
** ------------------
*/

$lang['BUILDING_TITLE'] = 'BUILDINGS';
$lang['BUILDING_NOTE1'] = 'Note: Income buildings provide higher hourly income. Each building contains citizens which increase hourly cost.';
$lang['BUILDING_NOTE2'] = 'Note: Defence buildings provide higher defence against attacks. Each building contains citizens which increase hourly cost.';
$lang['BUILDING_NOTE3'] = 'Note: Energy buildings provide faster energy recovery. Each building contains citizens which increase hourly cost.';
$lang['BUILDING_NOTE4'] = 'Note: Discount buildings provide price discount on building purchase. Each building contains citizens which increase hourly cost.';
$lang['BUILDING_NOTE5'] = 'Note: Maintenance buildings provide faster unit repair wich results in less unit loss during battles. Each building contains citizens which increase hourly cost.';

$lang['BUILDING_NOTE6'] = 'Note: Income buildings provide higher income for your moon base.';
$lang['BUILDING_NOTE7'] = 'Note: Defence buildings provide higher defence against attacks on your moon base.';
$lang['BUILDING_NOTE8'] = 'Note: Energy buildings provide faster energy recovery for your moon base.';
$lang['BUILDING_NOTE9'] = 'Note: Discount buildings provide price discount on moon building purchase.';
$lang['BUILDING_NOTE10'] = 'Note: Maintenance buildings provide faster moon unit repair wich results in less unit loss during battles.';

$lang['BUILDING_NOTE11'] = 'Note: Income buildings provide higher income for your mars base.';
$lang['BUILDING_NOTE12'] = 'Note: Defence buildings provide higher defence against attacks on your mars base.';
$lang['BUILDING_NOTE13'] = 'Note: Energy buildings provide faster energy recovery for your mars base.';
$lang['BUILDING_NOTE14'] = 'Note: Discount buildings provide price discount on mars building purchase.';
$lang['BUILDING_NOTE15'] = 'Note: Maintenance buildings provide faster mars unit repair wich results in less unit loss during battles.';

$lang['BUILDING_NOTE16'] = 'Note: Income buildings provide higher income for your mercure base.';
$lang['BUILDING_NOTE17'] = 'Note: Defence buildings provide higher defence against attacks on your mercure base.';
$lang['BUILDING_NOTE18'] = 'Note: Energy buildings provide faster energy recovery for your mercure base.';
$lang['BUILDING_NOTE19'] = 'Note: Discount buildings provide price discount on your mercure building purchase.';
$lang['BUILDING_NOTE20'] = 'Note: Maintenance buildings provide faster mercure unit repair wich results in less unit loss during battles.';

$lang['BUILDING_NOTE21'] = 'Note: Income buildings provide higher income for your neptune base.';
$lang['BUILDING_NOTE22'] = 'Note: Defence buildings provide higher defence against attacks on your neptune base.';
$lang['BUILDING_NOTE23'] = 'Note: Energy buildings provide faster energy recovery for your neptune base.';
$lang['BUILDING_NOTE24'] = 'Note: Discount buildings provide price discount on your neptune building purchase.';
$lang['BUILDING_NOTE25'] = 'Note: Maintenance buildings provide faster neptune unit repair wich results in less unit loss during battles.';

$lang['BUILDING_SELL'] = 'You sold %s %s for %s. Still %s deployed.';
$lang['BUILDING_LOW_UPKEEP'] = 'Not enough hourly income to sell %s %s for %s.';
$lang['BUILDING_NOT_OWNED'] = 'You do not have %s %s.';

$lang['BUILDING_BUY'] = 'You bought %s %s for %s. Now %s deployed.';
$lang['BUILDING_MAX'] = 'No more then %s %s(s) allowed!';
$lang['BUILDING_NO_FUNDS'] = 'Not enough funds to buy %s %s for %s.'; 
$lang['BUILDING_LOW_UPKEEP2'] = 'Not enough hourly income to buy %s %s for %s.';

$lang['BUILDING_UPKEEP'] = 'Hourly Cost';
$lang['BUILDING_PRICE'] = 'Price';
$lang['BUILDING_DEPLOYED'] = 'Deployed';
$lang['BUILDING_GAIN'] = 'Gain';
$lang['BUILDING_ENERGY'] = 'Energy';
$lang['BUILDING_INCOME'] = 'Income';
$lang['BUILDING_REQUIRED'] = 'Required';

$lang['BUILDINGS_NO_BUILDINGS'] = 'No buildings available yet!';

/*
** ------------------
** MONEY - BANKS 
** ------------------
*/

$lang['MONEY_TITLE'] = 'MONEY';

$lang['BANK_GROUP_1'] = 'National';
$lang['BANK_GROUP_2'] = 'Trasquera';
$lang['BANK_GROUP_3'] = 'SwissCore';

$lang['BANK_TITLE'] = 'BANKS';
$lang['BANK_NOTE'] = 'Note: There is a %s% fee for any deposit. The bank pays %s% daily interest. ';
$lang['BANK_WARNING'] = 'Warning: Intel or Explorer units from other players can steal money from this bank.';

$lang['BANK_TRANSACTION_TYPE_0'] = 'You withdrew';
$lang['BANK_TRANSACTION_TYPE_1'] = 'You deposited';
$lang['BANK_TRANSACTION_TYPE_2'] = 'Bank handle fee';
$lang['BANK_TRANSACTION_TYPE_3'] = 'Restore bill';		
$lang['BANK_TRANSACTION_TYPE_4'] = 'Interest';	
$lang['BANK_TRANSACTION_TYPE_5'] = 'spies steal';
$lang['BANK_TRANSACTION_TYPE_6'] = 'Bonus ';

$lang['BANK_TRANSACTION_LOG'] = 'Transaction log';

$lang['BANK_WITHDRAW']= 'Withdrawn %s dollars from bank';
$lang['BANK_WITHDRAW_FAILED'] = '%s dollars not available on bank account!';

$lang['BANK_DEPOSIT'] = 'Deposited %s dollar in the bank.';
$lang['BANK_DEPOSIT_FAILED'] = 'You do not have %s dollars.';

/*
** ------------------
** MONEY - STOCK EXCHANGES
** ------------------
*/

$lang['STOCK_GROUP_1'] = 'Nasdaq';
$lang['STOCK_GROUP_2'] = 'DowJones';
$lang['STOCK_GROUP_3'] = 'AEX';
$lang['STOCK_GROUP_4'] = 'Personal';

$lang['STOCK_TITLE'] = 'STOCK EXCHANGES';
$lang['STOCK_BROKER_ERROR'] = 'Broker connection failed. Trading not possible at the moment. Please try again later.';
$lang['STOCK_BUY'] = 'You bought %s %s stocks for %s dollars. Now %s owned.';
$lang['STOCK_NO_MONEY'] = 'Not enough money to buy %s %s stocks for %s dollars.';
$lang['STOCK_PRICE'] = 'Stock price %s [%s]';
$lang['STOCK_PROFIT'] = 'Stock profit %s [%s]';
$lang['STOCK_NOT_OWNED'] = 'You do not own %s %s stocks.';
$lang['STOCK_SELL'] = 'You sold %s %s stocks for %s dollars. You paid %s dollar transaction fee. Still %s owned.';
$lang['STOCK_NOTE'] = 'Note: You can buy or sell stocks to make profit. Stock prices are based on realtime information from Yahoo! financial service. There is a %s% handle fee on each sale transaction.';
$lang['STOCK_PRICE_TO_LOW'] = 'Stock price to low. Trading blocked!';

$lang['STOCK_SYMBOL'] = 'Stock symbol'; 
$lang['STOCK_SYMBOL_INFO'] = 'Note: Enter Yahoo! financial stock symbol to customize this list.'; 

$lang['STOCK_ADD'] = 'Add stock';
$lang['STOCK_SYMBOL_ADDED'] = 'You added (%s) to your personal stock list.';
$lang['STOCK_NO_SYMBOLS' ] = 'You did not add any personal stocks yet!';
$lang['STOCK_SYMBOL_NOT_FOUND'] = 'Stock symbol (%s) does not exist!';
$lang['STOCK_SYMBOL_AVAILABLE'] = 'Stock symbol (%s) all ready available in personal list.';

$lang['STOCK_REMOVE'] = 'Remove stock';
$lang['STOCK_SYMBOL_REMOVED'] = 'Stock symbol removed!';

$lang['GENERAL_STOCKS'] = 'Stocks';

/*
** ------------------
** MONEY - CASINO
** ------------------
*/

$lang['CASINO_TITLE'] = 'CASINO' ;

$lang['CASINO_1'] = 'WheelOfFortune';
$lang['CASINO_2'] = 'SlotMachine';
$lang['CASINO_3'] = 'TicTacToe';

$lang['CASINO_MONEY'] = 'Money';
$lang['CASINO_NUMBER'] = 'Lucky number';
$lang['CASINO_BET'] = 'Bet';
$lang['CASINO_PLAY'] = 'Play';
$lang['CASINO_ROLL'] = 'Roll';

$lang['CASINO_NO_BET'] = 'Enter bet amount!';
$lang['CASINO_NO_LUCKY_NUMBER'] = 'Enter lucky number!';
$lang['CASINO_BET_TO_LARGE'] = 'Bet too large! Maximum bet is %s dollars.'; 
$lang['CASINO_NO_MONEY'] = 'Not enough money!'; 

$lang['CASINO_WIN'] = 'Winning number was %s. You won %s  dollars.';
$lang['CASINO_LOST'] = 'Winning number was %s. You lost %s dollars.';

$lang['CASINO_NOTE1'] = 'Note: Enter your bet and lucky number and press the play button. If you are lucky you win 10 times your bet.';
$lang['CASINO_NOTE2'] = 'Note: Enter your bet and press the play button. Maybe your bet will pay out.';
$lang['CASINO_NOTE3'] = 'Note: Enter your bet and play tic-tac-toe. If you win, you win 2 times your bet.';

$lang['CASINO_UNLOCK'] = '%s is unlocked at level %s';

$lang['CASINO_SLOTMACHINE_WIN'] = 'You won %s times your bet, %s dollars.';
$lang['CASINO_SLOTMACHINE_LOST'] = 'You lost %s dollars.';
$lang['CASINO_SLOTMACHINE_HELP'] = 'The following slot machine combinations will pay out';

$lang['CASINO_TICTACTOE_WIN'] = 'You won %s times your bet, %s dollars.';
$lang['CASINO_TICTACTOE_DRAW'] = 'Draw. You won %s time your bet, %s dollars.';
$lang['CASINO_TICTACTOE_LOST'] = 'You lost %s dollars.';

/*
** ------------------
** ALLIANCE
** ------------------
*/

$lang['ALLIANCE_TITLE'] = 'ALLIANCE';

$lang['ALLIANCE_PENDING_TITLE1'] = 'Pending';
$lang['ALLIANCE_PENDING_TITLE2'] = 'Pending [%s accepted - %s invited allies]';

$lang['ALLIANCE_ACCEPT_TITLE1'] = 'Accepted';
$lang['ALLIANCE_ACCEPT_TITLE2'] = 'Accepted [%s accepted - %s invited allies]';

$lang['ALLIANCE_INVITE_TITLE1'] = 'Invite';
$lang['ALLIANCE_INVITE_TITLE2'] = 'Invite [%s accepted - %s invited allies]';

$lang['ALLIANCE_NO_PENDING'] = 'No pending invitations waiting!'; 
$lang['ALLIANCE_INVITATION'] = 'Ally invitation sent to %s!'; 
$lang['ALLIANCE_REJECT'] = 'Reject %s as ally!';
$lang['ALLIANCE_DROP'] = 'Drop %s as ally!';
$lang['ALLIANCE_ACCEPT'] = 'Accept %s as ally!';
$lang['ALLIANCE_ALLY'] = 'Ally';
$lang['ALLIANCE_MAXIMUM'] = 'Maximum amount of %s allies reached for this level.'; 
$lang['ALLIANCE_LOCKED'] = 'Alliance invitation is unlocked at level 1';
$lang['ALLIANCE_NOTE'] = 'Note: With every approved ally you can command 6 more units during fights. Keep in mind that you cannot attack allies.';

$lang['ALLIANCE_INVITE_FRIENDS'] = 'Invite friend by email';
$lang['ALLIANCE_INVITE_NOTE'] = 'Note: Invite a player for an alliance. If the other player accepts or rejects the alliance you will receive a notification by email (option in settings). Maximum amount of accepted + invited allies for this level is %s.';
$lang['ALLIANCE_EMAIL_INVALID']= 'Email address is not valid!';
$lang['ALLIANCE_ALREADY_INVITED'] = 'Email address is already invited!';
$lang['ALLIANCE_INVITE_SENT'] = 'Invite email is sent.';

$lang['ALLIANCE_COMMENT_TITLE'] = 'Message';
$lang['ALLIANCE_COMMENT_TEXT1'] = 'Create message (max. 400 characters) for all players';
$lang['ALLIANCE_COMMENT_TEXT2'] = 'Create message (max. 400 characters) for %s';
$lang['ALLIANCE_PLAYER_NEWS'] = 'Messages';
$lang['ALLIANCE_COMMENT_ALL'] = 'Message is stored and available for all players.';
$lang['ALLIANCE_COMMENT_PLAYER'] = 'Message is sent to %s';

$lang['LEADERBORD_BEST_PLAYER'] = 'Leaderboard (Best Players)';
$lang['LEADERBORD_BEST_PLAYER_NOTE'] = 'Note: Leaderboard shows the best human players. WarQuest robot (cyberspace) players are not shown!';

$lang['LEADERBORD_BEST_COUNTRY'] = 'Leaderboard (Best Countries)';
$lang['LEADERBORD_BEST_COUNTRY_NOTE'] = 'Note: Leaderboard shows the best real countries.';

$lang['LEADERBORD_PLAYER_COUNTRY'] = 'Leaderboard (Best Players of %s)';
$lang['LEADERBORD_PLAYER_COUNTRY_NOTE'] = 'Note: Leaderboard shows the best players of the selected country.';

/*
** ------------------
** FORUM 
** ------------------
*/

$lang['FORUM_TITLE'] = 'FORUMS'; 
$lang['FORUM_TITLE2'] = 'Forums';
$lang['FORUM_NOTE'] = 'Note: Select a forum to see all posted topics. I\'ve seen some people cursing or use other bad words in the forums. I doesn\'t want that kind of language on here! Thanks. And remember, no bad words! ';

$lang['FORUM_1'] = 'Announcements'; 
$lang['FORUM_NOTE_1'] = 'General announcements';
$lang['FORUM_2'] = 'Bug Reports'; 
$lang['FORUM_NOTE_2'] = 'What goes wrong in this release?';
$lang['FORUM_3'] = 'Feature Requests'; 
$lang['FORUM_NOTE_3'] = 'What do you want in the next release?';
$lang['FORUM_4'] = 'Help'; 
$lang['FORUM_NOTE_4'] = 'What is not clear in WarQuest?';
$lang['FORUM_5'] = 'Other'; 
$lang['FORUM_NOTE_5'] = 'Any other discussion?';
$lang['FORUM_6'] = 'Country Communities'; 
$lang['FORUM_NOTE_6'] = 'Local language discussions?';

$lang['FORUM_SEARCH_TOKEN'] = 'Search token must be atleast 3 character long.';

$lang['TOPIC_TITLE'] = 'Topics'; 
$lang['TOPIC_CREATED_INPUT'] = 'Create new topic (max. 80 characters)';
$lang['TOPIC_CREATED'] = 'Topic is created';
$lang['TOPIC_UPDATED'] = 'Topic is updated';
$lang['TOPIC_DELETED'] = 'Topic is deleted';
$lang['TOPIC_NO_TOPICS'] = 'At the moment no topic(s) found.';
$lang['TOPIC_NOTE'] = 'Note: Select a topic to read/write posted messages or create a new topic.'; 
$lang['TOPIC_CREATED_BY'] = '(Created by %s)';

/*
** ------------------
** FORUM - POLL
** ------------------
*/

$lang['POLL_TITLE'] = 'Polls';
$lang['POLL_RESULT_TITLE'] = 'Poll Results';
$lang['POLL_TEASER_TITLE'] = 'New Poll';
$lang['POLL_RESULTS'] = 'Results';
$lang['POLL_ClOSED'] = '(Poll closed)';
$lang['POLL_VOTE_ADD'] = 'Thank you for your vote! You received 10 bonus experience points as reward.';
$lang['POLL_VOTE_REMOVE'] = 'Your vote is canceled!';
$lang['POLL_VOTE'] = 'Vote';
$lang['POLL_VOTES'] = 'Votes';
$lang['POLL_CANCEL'] = 'Cancel';
$lang['POLL_SUMMARY'] = 'Total Voters: %s';
$lang['POLL_WARNING'] = 'Select one of the possible vote options!';

/*
** ------------------
** FORUM - CHAT
** ------------------
*/

$lang['CHATROOM_TITLE'] = 'Chatroom';
$lang['CHATROOM_NOTE'] = 'Note: Start a chat session by selecting an online player!';
$lang['CHATROOM_LAST_ACTIVE'] = 'Last Active';
$lang['CHATROOM_CHAT'] = 'Chat';
$lang['CHAT_NOTE'] = 'Note: Enter a message to start the chat!';

$lang['CHAT_TITLE'] = 'Chat';

/*
** ------------------
** HELP - INSTRUCTIONS
** ------------------
*/

$lang['HELP_TITLE'] = 'HELP';

$lang['HELP_GENERAL_SUBTITLE'] = 'Instructions';

$lang['HELP_INTRO_TITLE'] = 'Introduction';
$lang['HELP_INTRO'] =	'WarQuest is a Free Multiplayer Online Game featuring a war zone with thousands of real players. WarQuest takes you to 
the year 2020. The world is at war. The goal of the game is to defend your country and conquer other 
countries. Buy weapons and production units, play missions, fight, make allies and become the best 
player of your country.';

$lang['HELP_EXP_TITLE'] = 'Experience / Level';
$lang['HELP_EXP'] = 'Play missions and fight battles to gain experience points. When you collect 
enough experience points you will be able to upgrade onto the next level. When a level is completed your 
energy, health and ammo will be restored istantly.';

$lang['HELP_HEALTH_TITLE'] = 'Health';
$lang['HELP_HEALTH'] = 'Your health decreases each battle but will automatically be restored over 
time. You can also visit the hospital (Home -> Restore) and pay to recover istantly.';

$lang['HELP_ENERGY_TITLE'] = 'Energy'; 
$lang['HELP_ENERGY'] = 'Your energy level decreases each time you play a mission but restores 
automatically over time. Buying energy buildings will restore your energy faster. You also may 
restore it in the same way you can restore health.';

$lang['HELP_AMMO_TITLE'] = 'Ammo'; 
$lang['HELP_AMMO'] =	'Each battle costs one ammo. Ammo is automatically restored over 
time. You may also restore it in the same way you can restore health.';

$lang['HELP_MISSION_TITLE'] = 'Missions';
$lang['HELP_MISSION'] = 'Play missions to gain money and experience points to reach the next level. 
If a mission is 100% completed you will gain twice the amount of money. If a continent is conquered 
you receive a hourly income bonus.<br/><br/>

The following extra bonus is given when all planet missions are completed:<br/>
EARTH: 100 Million dollars<br/>
MOON: 500 Million dollars<br/>
MARS: 999 Billion dollars<br/>
MERCURE: 2500 gold<br/>
NEPTUNE: 5000 gold';

$lang['HELP_BATTLE_TITLE'] = 'Battle';
$lang['HELP_BATTLE'] =	'Fight other players to gain money and experience points to reach the next 
level. During the fight units and buildings of your base can be damaged or even lost.';

$lang['HELP_UNITS_TITLE'] = 'Units';
$lang['HELP_UNITS'] =  'During attacks your best units are automatic selected. The size (amount 
of operational units) of your army is related to your current approved alliance size. You start off 
with one ally which allows you to command 6 units. Each approved ally allows you to command six more 
units. You can purchase more but only the best 6 times your alliances size will be used.';

$lang['HELP_BUILDINGS_TITLE'] = 'Buildings';
$lang['HELP_BUILDINGS'] = 'During the game buildings provide income, higher defence, faster energy, 
discounts and/or better unit maintenance. Every building purchase will increase the price for a next 
purchase. Each buildings contains citizens which cost hourly income.';

$lang['HELP_BANKS_TITLE'] = 'Banks';
$lang['HELP_BANKS'] = 'Each bank will charge a deposit fee. Money which is stored in the National bank 
is safe from other players but gives a low daily interest. Money stored on the Trasquera or SwissCore 
bank give higher daily interest but Intel (Earth) or Explorer (Moon/Mars) units from other players can steal money.';

$lang['HELP_ALLIANCE_TITLE'] = 'Alliance'; 
$lang['HELP_ALLIANCE'] = 'Every approved ally allows you to command 6 additional units (that you own) 
during fights. Increase alliance size to get stronger! Keep in mind that you cannot attack allies.';

$lang['HELP_SKILL_POINTS_TITLE'] = 'Skill Points';
$lang['HELP_SKILL_POINTS'] = 'During the game skill points can be received. Deploy skill points to 
increase attack, defence, health, energy and/or ammo skills. Ammo skill upgrade costs 2 skill points, 
others will cost you only 1 skill point. You can also trade in 2:1 skillpoints to change your skills.';

$lang['HELP_GOLD_TITLE'] = 'Gold';
$lang['HELP_GOLD']  = 'Gold can be purchased by donate some real dollars. See Help -> Donate. 
Purchase gold can be used to buy premium units & buildings or can be exchanged in to skill points, cash money or can be used to improve your health, energy or ammo restore timer.
<br/><br/>
Benefits of gold buildings:<br/>
- Higher defence strength then normal buildings<br/>
- No hourly cost<br/>
- Immortal during fights<br>
<br/>
Benefits of gold units:<br/>
- Higher attack / defence strength the normal units<br/>
- 50% lower hourly cost then normal units<br/>
- Immortal during fights';

$lang['HELP_TACTICS_TITLE'] = 'Tactics';
$lang['HELP_TACTICS'] = 'One thing to keep in mind is that units used in missions are also subject to 
loss as casualties. This is important to consider as the cost of replacing some of the higher priced 
units used in a mission may exceed the money earned from the mission itself. In general, if your goal 
is to maximize money from missions, then focus on the Money / Energy value of the mission. 
If your goal is to maximize experience points, then focus on the Exp / Energy value of the 
missions.<br/><br/>

Once you hit the higher levels, the game automatically increases the range of opponents that can 
attack you. When this occurs, you should increase alliance size or max out the number of members 
in your alliance.<br/><br/>

Defence buildings are an ideal purchase because they add to your defense score whenever you are attacked. 
I recommend purchasing as many as you can afford since it will allow you to allocate more of your money 
toward attack units without having to worry about their defence points.<br/><br/>

In WarQuest, defence buildings make some opponents extremely difficult to successfully attack. 
Although it is still recommended to put points to defence, I recommend putting as many points 
as possible in to Attack. You can compensate for lower defence skill points with defence 
buildings.<br/><br/>

When deciding what units to buy, you need to carefully consider the units hour costs, Attack and 
Defence strength. Assuming you can afford to buy the unit, cost should not be a factor in your 
decision since it is only a one time cost. Because of the reduction in income due to hourly
unit cost, it does not always make sense to buy the best available units. If you are winning most of 
your fights with your current units, then it may make more strategic sense to not increase your 
hourly cost and allow your income to build at a faster rate.';

$lang['HELP_GRAVATAR_TITLE'] = 'Gravatar';
$lang['HELP_GRAVATAR'] = 'WarQuest supports Gravatar (www.gravatar.com) image service. Gravatar is an 
image that follows you from site to site appearing beside your (nick)name.';

$lang['HELP_BOUNTY_TITLE'] = 'Bounty Hunting';
$lang['HELP_BOUNTY'] = 'You can set bounty on your opponents head. The bounty price is related to the 
opponent level. After you set the bounty other players can attack the opponent (Battle -> BountyHunting).
If the opponent is defeated he will lose some experience points and the bounty money is transferred to 
the winner.';

$lang['HELP_UNITS_CONDITION_TITLE'] = 'Units Condition (UC)';
$lang['HELP_UNITS_CONDITION'] = 'This value gives information about your current units condition. 
If the condition gets below 0% you will lose some units. To prevent unit loss you can visit 
(Home -> Restore) to repair your operational units.'; 

$lang['HELP_BUILDINGS_CONDITION_TITLE'] = 'Buildings Condition (BC)';
$lang['HELP_BUILDINGS_CONDITION'] = 'This value gives information about your current base buildings 
condition. If the condition gets below 0% you will lose some buildings. To prevent building loss 
you can visit (Home -> Restore) to repair your base.'; 

$lang['HELP_FORUM_TITLE'] = 'Forum';
$lang['HELP_FORUM'] = 'To get more information and chat with other players please visit the Warquest 
Forum.';

$lang['HELP_WORLDMAP_TITLE'] = 'Map';
$lang['HELP_WORLDMAP'] = 'Each planet map contain 72 regions which can be conquered with playing 
missions. The regions can have one of the following colors: <br/>
- "Green" Region 0% conquered<br/>
- "Yellow" Region 33% conquered.<br/>
- "Purple" Region 66% conquered.<br/>
- "Orange" Region 100% conquered.<br/>
- "Red" Rebellion in region. Region must be reconquered.';

$lang['HELP_SHORTCUTS_TITLE'] = 'Menu shortcuts';
$lang['HELP_SHORTCUTS'] = 'The following hidden menu shortcuts are available in the banner for 
faster navigation:<br/>
- Click "Cash" to go to player leaderboard page.<br/>
- Click "Exp." to go to country leaderboard page.<br/>
- Click "Level" to go to the poll page.<br/>
- Click "Health" to go to restore page.<br/>
- Click "Energy" to go to player profile page.<br/>
- Click "Ammo" to go to skill points page.';

$lang['HELP_ATTACK_FORCE_TITLE'] = 'Attack force';
$lang['HELP_ATTACK_FORCE'] = 'Before battle you can select one of the following attack forces:<br/><br/>
EARTH<br/>
- "Army" Best of calvary, navy and aircrafs earth units.<br/>
- "Calvary" Only calvary earth units.<br/>
- "Navy" Only navy earth units.<br/>
- "Airforce" Only aircraft earth units.<br/>
- "Intel" Only intel earth units.<br/><br/>
MOON / MARS / MERCURE / NEPTUNE<br/>
- "Army" Best of drone, warrior and spacecraft units.<br/>
- "Drones" Only drone units.<br/>
- "Warriors" Only warrior units.<br/>
- "Spacecrafts " Only spacecraft units.<br/>
- "Explorers " Only explorer units.
';

$lang['HELP_REBELLION_CONDITION_TITLE'] = 'Rebellion Condition (RC)';
$lang['HELP_REBELLION_CONDITION'] = 'This value gives information about your current rebellion condition. Region 
rebellion is triggered by intel (Earth) or explorers (Moon/Mars) attacks by your opponents. If the 
condition reaches 100%, some of your conquered regions will be in rebellion. To prevent rebellion, 
visit (Home -> Restore) to end the rebellion. Each rebellion region results in postponed continent 
hourly income. Restore control in the rebel region by playing the related mission.';

/*
** ------------------
** HELP - RELEASE NOTES
** ------------------
*/

$lang['HELP_NOTES_SUBTITLE1'] = 'Release Notes';
$lang['HELP_NOTES_SUBTITLE2'] = 'Release Notes (English only)';

/*
** ------------------
** HELP - RANKS
** ------------------
*/

$lang['HELP_RANKS_SUBTITLE'] = 'Ranks';
$lang['HELP_RANKS'] = 'The following ranks are available:';

/*
** ------------------
** HELP - AWARDS
** ------------------
*/

$lang['HELP_AWARDS_SUBTITLE'] = 'Awards';
$lang['HELP_BATTLE_AWARDS'] = 'The following battle victory awards can be earned:';
$lang['HELP_BOUNTY_AWARDS'] = 'The following bounty set awards can be earned:';
$lang['HELP_REBEL_AWARDS'] = 'The following rebellion start awards can be earned:';


/*
** ------------------
** HELP - LEVELS
** ------------------
*/

$lang['HELP_LEVEL_SUBTITLE'] = 'Levels';
$lang['HELP_LEVEL'] = 'The following levels are available:';
$lang['HELP_LEVEL_UNIT_LOST'] = 'Unit Lost';
$lang['HELP_LEVEL_EXPERIENCE'] = 'Experiece';
$lang['HELP_LEVEL_FEATURES'] = 'Feature unlock scheme';

/*
** ------------------
** HELP - STATS
** ------------------
*/

$lang['HELP_STATS_TITLE'] = 'Statistics';
$lang['HELP_STATS_NOTE'] = 'Note: On this page realtime WarQuest statistics are shown.';
$lang['HELP_STATS_PLAYERS'] = 'New players';
$lang['HELP_STATS_ONLINE'] = 'Players online';
$lang['HELP_STATS_FIGHTS'] = 'Player fights';
$lang['HELP_STATS_MISSIONS'] = 'Missions played';
$lang['HELP_STATS_CASINO'] = 'Casino games played';
$lang['HELP_STATS_GOLD'] = 'Gold used';
$lang['HELP_STATS_REQUESTS'] = 'Server requests ';

/*
** ------------------
** HELP - DONATE
** ------------------
*/

$lang['HELP_DONATE_TITLE1'] = 'Donate';
$lang['HELP_DONATE_TITLE2'] = 'Donate';

$lang['HELP_SUBTITLE_DONATE1'] = 'General';
$lang['HELP_DONATE1'] = 'WarQuest software may be used free of charge, but if you wish to express 
your appreciation for the time and resources the author spent developing and supporting it 
over the years, and also help reduce the costs of running the web server, we do accept and appreciate 
donations.';

$lang['HELP_SUBTITLE_DONATE2'] = 'Reward';
$lang['HELP_DONATE2'] = 'Each dollar donated will be rewarded with %s. 
Gold is an in-game currency that gives access to various additional options.  With gold in your in-game wallet, you can:
<ul>
<li>buy premium units</li>
<li>buy premium buildings</li>
<li>buy extra skill points</li>
<li>buy extra cash</li> 
<li>upgrade your health timer</li>
<li>upgrade your energy timer</li>
<li>upgrade your ammo timers</li>
</ul>
The donation is manually processed so keep in mind that it takes a few hours before the gold is available.';

$lang['HELP_SUBTITLE_DONATE3'] = 'PayPal';
$lang['HELP_DONATE3'] = 'To make a donation online using your credit card, or PayPal account, click 
below and enter the amount you would like to contribute. Your credit card will be processed by PayPal, 
a trusted name in secure online transactions. Many thanks for your support.';

/*
** ------------------
** HELP - ABOUT
** ------------------
*/

$lang['HELP_ABOUT_SUBTITLE'] = 'About';
$lang['HELP_BACKGROUND_TITLE'] = 'Background';
$lang['HELP_BACKGROUND'] = 'WarQuest is created by <a target="new" href="http://www.plaatsoft.nl">PlaatSoft</a>. Original game idea is based on some other games available in the Apple appstore. The main reason to recreate this kind of game is to create a better game play and user interface which can be controlled on the following devices: smart phones (Apple, Android, Nokia and BlackBerry), tablets(Samsung and Apple), Game consoles (Nintendo) and all kinds of notebooks (Intel / AMD base).';
$lang['HELP_CREDITS_TITLE'] = 'Credits';
$lang['HELP_BROWSERS_TITLE'] = 'Supported Browsers'; 
$lang['HELP_HARDWARE_TITLE'] = 'Supported Hardware'; 
$lang['HELP_DISCLAIMER_TITLE'] = 'Disclaimer'; 
$lang['HELP_DISCLAIMER'] = 'The program is provided AS IT IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.<br/>';

$lang['HELP_CREDITS_TITLE'] = 'Credits';
$lang['HELP_CREDITS'] = 'Many thanks to the following people and organisations who helped creating this game.';
$lang['HELP_CREDITS_ARCHITECT'] = 'Architect';
$lang['HELP_CREDITS_DEVELOPERS'] = 'Developer';
$lang['HELP_CREDITS_GRAPHICS'] = 'Graphics & Information';
$lang['HELP_CREDITS_TRANSLATORS'] = 'Translators';
$lang['HELP_CREDITS_TESTERS'] = 'Testers';
$lang['HELP_CREDITS_OTHER'] = 'Other';
$lang['HELP_CREDITS_OTHER_NOTE'] = 'And of course all WarQuest players who sent great feedback to improve the game. Enjoy then game and lets have fun!';

/*
** ------------------
** RANK DATA
** ------------------
*/

$lang['RANK_1'] = "Private";
$lang['RANK_2'] = "Private first class";
$lang['RANK_3'] = "Specialist";
$lang['RANK_4'] = "Corporal";
$lang['RANK_5'] = "Sergeant";
$lang['RANK_6'] = "Staff Sergeant";
$lang['RANK_7'] = "Sergeant First Class";
$lang['RANK_8'] = "Master Sergeant";
$lang['RANK_9'] = "First Sergeant";
$lang['RANK_10'] = "Sergeant Major";
$lang['RANK_11'] = "Command Sergeant Major";
$lang['RANK_12'] = "Sergeant Major of the Army";
$lang['RANK_13'] = "Second Lieutenant";
$lang['RANK_14'] = "First Lieutenant";
$lang['RANK_15'] = "Captain";
$lang['RANK_16'] = "Major";
$lang['RANK_17'] = "Lieutenant Colonel";
$lang['RANK_18'] = "Colonel";
$lang['RANK_19'] = "Brigadier General";
$lang['RANK_20'] = "Major General";
$lang['RANK_21'] = "Lieutenant General";
$lang['RANK_22'] = "General";
$lang['RANK_23'] = "General of the Army";

/*
** ------------------
** COUNTRY NAMES
** ------------------
*/

$landcode = array();

$landcode['ad'] = "Andorra";
$landcode['ae'] = "Arab Emirates";
$landcode['af'] = "Afghanistan";
$landcode['ag'] = "Antigua and Barbuda";
$landcode['ai'] = "Anguilla";
$landcode['al'] = "Albania";
$landcode['am'] = "Armenia";
$landcode['an'] = "Netherlands Antilles";
$landcode['ao'] = "Angola";
$landcode['aq'] = "Antarctica";
$landcode['ar'] = "Argentina";
$landcode['as'] = "American Samoa";
$landcode['at'] = "Austria";
$landcode['au'] = "Australia";
$landcode['aw'] = "Aruba";
$landcode['ax'] = "Aland Islands";
$landcode['az'] = "Azerbaijan";
		
$landcode['ba'] = "Bosnia and Herzegovina";
$landcode['bb'] = "Barbados";
$landcode['bd'] = "Bangladesh";
$landcode['be'] = "Belgium";
$landcode['bf'] = "Burkina Faso";
$landcode['bg'] = "Bulgaria";
$landcode['bh'] = "Bahrain";
$landcode['bi'] = "Burundi";
$landcode['bj'] = "Benin";
$landcode['bm'] = "Bermuda";
$landcode['bn'] = "Brunei Darussalam";	
$landcode['bl'] = "Saint Barthelemy";
$landcode['bn'] = "Brunei";
$landcode['bo'] = "Bolivia";
$landcode['br'] = "Brazil";
$landcode['bs'] = "Bahamas";
$landcode['bt'] = "Bhutan";
$landcode['bv'] = "Bouvet island";
$landcode['bw'] = "Botswana";
$landcode['by'] = "Belarus";
$landcode['bz'] = "Belize";
	
$landcode['ca'] = "Canada";
$landcode['cc'] = "Cocos Islands";
$landcode['cf'] = "Central African Republic";
$landcode['cg'] = "Congo";
$landcode['ch'] = "Switzerland";
$landcode['ci'] = "Cote d lvoire";
$landcode['ck'] = "Cook Islands";
$landcode['cl'] = "Chili";
$landcode['cm'] = "Cameroon";
$landcode['cn'] = "China";
$landcode['co'] = "Columbia";
$landcode['cr'] = "Costa Rica";
$landcode['cs'] = "Serbia en Montenegro";
$landcode['cu'] = "Cuba";
$landcode['cv'] = "Cape Verde";
$landcode['cx'] = "Christmas Island";
$landcode['cy'] = "Cyprus";
$landcode['cz'] = "Czech Republic";
	
$landcode['de'] = "Germany";
$landcode['dj'] = "Djibouti";
$landcode['dk'] = "Denmark";
$landcode['dm'] = "Dominica";
$landcode['do'] = "Dominican Republic";
$landcode['dz'] = "Algeria";
	
$landcode['ec'] = "Ecuador";
$landcode['ee'] = "Estonia";
$landcode['eg'] = "Egypt";
$landcode['eh'] = "Western Sahara";
$landcode['er'] = "Eritrea";
$landcode['es'] = "Spain";
$landcode['et'] = "Ethiopia";
$landcode['eu'] = "Cyberspace";
	
$landcode['fi'] = "Finland";
$landcode['fj'] = "Fiji";
$landcode['fk'] = "Falkland Islands";
$landcode['fm'] = "Micronesia";
$landcode['fo'] = "Faroe Islands";
$landcode['fr'] = "France";
	
$landcode['ga'] = "Gabon";
$landcode['gb'] = "United Kingdom";
$landcode['gd'] = "Grenada";
$landcode['ge'] = "Georgia";
$landcode['gf'] = "French Guiana";
$landcode['gh'] = "Ghana";
$landcode['gi'] = "Gibraltar";
$landcode['gl'] = "Greenland";
$landcode['gm'] = "Gambia";
$landcode['gn'] = "Guinea";
$landcode['gp'] = "Guadeloupe";
$landcode['gq'] = "Equatorial Guinea";
$landcode['gr'] = "Greece";
$landcode['gs'] = "Zuid-Georgia";
$landcode['gt'] = "Guatemala";
$landcode['gu'] = "Guam";
$landcode['gw'] = "Guinee-Bissau";
$landcode['gy'] = "Guyana";
	
$landcode['hk'] = "Hong Kong";
$landcode['hm'] = "Heard- en McDonald Islands";
$landcode['hn'] = "Honduras";
$landcode['hr'] = "Kroatia";
$landcode['ht'] = "Haiti";
$landcode['hu'] = "Hungary";
	
$landcode['id'] = "Indonesia";
$landcode['ie'] = "Ireland";
$landcode['il'] = "Israel";
$landcode['in'] = "India";
$landcode['im'] = "Isle of Man";
$landcode['io'] = "BI Ocean Territory";
$landcode['iq'] = "Iraq";
$landcode['ir'] = "Iran";
$landcode['is'] = "Iceland";
$landcode['it'] = "Italy";
	
$landcode['jm'] = "Jamaica";
$landcode['jo'] = "Jordan";
$landcode['jp'] = "Japan";
	
$landcode['ke'] = "Kenya";
$landcode['kg'] = "Kyrgyzstan";
$landcode['kh'] = "Cambodia";
$landcode['ki'] = "Kiribati";
$landcode['km'] = "Comores";
$landcode['kn'] = "Saint Kitts en Nevis";
$landcode['kp'] = "North Korea";
$landcode['kr'] = "South Korea";
$landcode['kw'] = "Kuwait";
$landcode['ky'] = "Cayman Islands";
$landcode['kz'] = "Kazachstan";
	
$landcode['la'] = "Laos";
$landcode['lb'] = "Lebanon";
$landcode['lc'] = "Saint Lucia";
$landcode['li'] = "Liechtenstein";
$landcode['lk'] = "Sri Lanka";
$landcode['lr'] = "Liberia";
$landcode['ls'] = "Lesotho";
$landcode['lt'] = "Lithuania";
$landcode['lu'] = "Luxembourg";
$landcode['lv'] = "Latvia";
$landcode['ly'] = "Libyan";
	
$landcode['ma'] = "Morocco";
$landcode['mc'] = "Monaco";
$landcode['md'] = "Moldova";
$landcode['mg'] = "Madagascar";
$landcode['mh'] = "Marshall Islands";
$landcode['mk'] = "Macedonia";
$landcode['ml'] = "Mali";
$landcode['mm'] = "Myanmar";
$landcode['mn'] = "Mongolia";
$landcode['mo'] = "Macao";
$landcode['mp'] = "Northern Mariana Islands";
$landcode['mq'] = "Martinique";
$landcode['mr'] = "Mauritania";
$landcode['ms'] = "Montserrat";
$landcode['mt'] = "Malta";
$landcode['mu'] = "Mauritius";
$landcode['mv'] = "Maldives";
$landcode['mw'] = "Malawi";
$landcode['mx'] = "Mexico";
$landcode['my'] = "Malaysia";
$landcode['mz'] = "Mozambique";
	
$landcode['na'] = "Namibia";
$landcode['nc'] = "New Caledonia";
$landcode['ne'] = "Niger";
$landcode['nf'] = "Norfolk Islands";
$landcode['ng'] = "Niger";
$landcode['ni'] = "Nicaragua";
$landcode['nl'] = "Netherlands";
$landcode['no'] = "Norway";
$landcode['np'] = "Nepal";
$landcode['nr'] = "Nauru";
$landcode['nu'] = "Niue";
$landcode['nz'] = "New Zealand";
	
$landcode['om'] = "Oman";
	
$landcode['pa'] = "Panama";
$landcode['pe'] = "Peru";
$landcode['pf'] = "French Polynesia";
$landcode['pg'] = "Papua New Guinea";
$landcode['ph'] = "Philippines";
$landcode['pk'] = "Pakistan";
$landcode['pl'] = "Poland";
$landcode['pm'] = "Saint Pierre and Miquelon";
$landcode['pn'] = "Pitcairn";
$landcode['pr'] = "Puerto Rico";
$landcode['ps'] = "Palestinian";
$landcode['pt'] = "Portugal";
$landcode['pw'] = "Palau";
$landcode['py'] = "Paraguay";
	
$landcode['qa'] = "Qatar";
	
$landcode['re'] = "Reunion";
$landcode['ro'] = "Romania";
$landcode['ru'] = "Russian Federation";
$landcode['rs'] = "Serbia";
$landcode['rw'] = "Rwanda";
	
$landcode['sa'] = "Saudi Arabia";
$landcode['sb'] = "Solomon Islands";
$landcode['sc'] = "Seychelles";
$landcode['sd'] = "Sudan";
$landcode['se'] = "Sweden";
$landcode['sg'] = "Singapore";
$landcode['sh'] = "Saint-Helena";
$landcode['si'] = "Slovenia";
$landcode['sj'] = "Svalbard and Jan Mayen";
$landcode['sk'] = "Slovakia";
$landcode['sl'] = "Sierra Leone";
$landcode['sm'] = "San Marino";
$landcode['sn'] = "Senegal";
$landcode['so'] = "Somalia";
$landcode['sr'] = "Suriname";
$landcode['st'] = "Sao Tome en Principe";
$landcode['sv'] = "El Salvador";
$landcode['sy'] = "Syria";
$landcode['sz'] = "Swaziland";
	
$landcode['tc'] = "Turks and Caicos Islands";
$landcode['td'] = "Chad";
$landcode['tg'] = "Togo";
$landcode['th'] = "Thailand";
$landcode['tj'] = "Tajikistan";
$landcode['tk'] = "Tokelau";
$landcode['tl'] = "Timor";
$landcode['tm'] = "Turkmenistan";
$landcode['tn'] = "Tunisia";
$landcode['to'] = "Tonga";
$landcode['tr'] = "Turkey";
$landcode['tt'] = "Trinidad and Tobago";
$landcode['tv'] = "Tuvalu";
$landcode['tw'] = "Taiwan";
$landcode['tz'] = "Tanzania";
	
$landcode['ua'] = "Ukraine";
$landcode['ug'] = "Uganda";
$landcode['um'] = "United States Minor Outlying Islands";
$landcode['us'] = "United States";
$landcode['uy'] = "Uruguay";	
$landcode['uz'] = "Uzbekistan";
	
$landcode['va'] = "Vatican City";
$landcode['vc'] = "Saint Vincent and the Grenadines";
$landcode['ve'] = "Venezuela";
$landcode['vg'] = "Virgin Islands; British";
$landcode['vi'] = "Virgin islands; US";
$landcode['vn'] = "Vietnam";
$landcode['vu'] = "Vanuatu";
	
$landcode['wf'] = "Wallis and Futuna";
$landcode['ws'] = "Samoa";
	
$landcode['ye'] = "Yemen";
$landcode['yt'] = "Mayotte";
	
$landcode['za'] = "South Africa";
$landcode['zm'] = "Zambia";
$landcode['zw'] = "Zimbabwe";

/*
** ------------------
** Added v5.8
** ------------------
*/

$lang['USER_EMAIL_CONFIRM_SENT'] = 'Confirmation email sent to %s'; 
$lang['USER_EMAIL_CONFIRM_NEEDED'] = 'Please confirm your email address by clicking %s!';
$lang['USER_EMAIL_HERE'] = 'here';
$lang['USER_EMAIL_VALID'] = 'Your email address is validated. Thank you!';

$lang['PLAYER_CLAN_NAME'] = 'Clan';

$lang['GENERAL_NAME'] = 'Name';
$lang['GENERAL_STRENGTH'] = 'Strength';
$lang['GENERAL_SIZE'] = 'Size';
$lang['GENERAL_NR'] = 'Nr';
$lang['GENERAL_JOINED'] = 'Joined';
$lang['GENERAL_POSITION'] = 'Position';
$lang['GENERAL_COMMANDER'] = 'Commander';
$lang['GENERAL_CREATED'] = 'Created';
$lang['GENERAL_RESULT'] = 'Result';
$lang['GENERAL_CLAN'] = 'Clan';
$lang['GENERAL_ALL']  = 'All';

$lang['LINK_JOIN'] = 'Join';
$lang['LINK_LEAVE'] = 'Leave';
$lang['LINK_CLAN'] = 'Clan';

$lang['CLAN_TITLE'] = 'Clan';
$lang['CLAN_NOTE'] = 'Create or join a clan to enter clan wars. Each player can only be part of one clan.';
$lang['CLAN_ADD'] = 'Add Clan';
$lang['CLAN_CREATE'] = 'New clan name';
$lang['CLAN_LEAVE'] = 'You left then %s clan';
$lang['CLAN_JOINED'] = 'You sent a request to join the %s clan. Commander %s has to approve your request so be patient!';
$lang['CLAN_DROP'] = 'You dropped %s from your %s clan!';
$lang['CLAN_NOT_PART'] = 'Player not part of then clan!';
$lang['CLAN_ALL_PART'] = 'You already joined a clan!';
$lang['CLAN_CREATE_NOTE'] = 'Create a new clan by entering an unique name. It takes 1 skill point to create a clan.';
$lang['CLAN_NAME_TOO_SHORT'] = 'The clan name is too short!';
$lang['CLAN_NAME_TOO_LONG'] = 'The clan name is too long!';
$lang['CLAN_NAME_EXIST'] = 'Clan name [%s] already exist!';
$lang['CLAN_NO_CLANS'] = 'No clan available yet';
$lang['CLAN_NO_MEMBERS'] = 'No clan members yet';
$lang['CLAN_CREATED'] = 'Clan [%s] created!';
$lang['CLAN_NO_SKILL_POINT'] = 'You need 1 skill point to create a new clan.';

$lang['CLAN_SLOGAN'] = 'Clan slogan:';
$lang['CLAN_SLOGAN_NOTE'] = 'Enter or update then clan slogan!';
$lang['CLAN_SLOGAN_SAVED'] = 'Clan slogan is saved';
$lang['CLAN_SLOGAN_TOO_SHORT'] = 'Clan slogan is to short';
$lang['CLAN_SLOGAN_TOO_LONG'] = 'Clan slogan is to long. Maximum 200 characters allowed.';

$lang['CLAN_LIST_TITLE'] = 'Clan List [%s]';

$lang['BATTLE_CLAN_WAR_UNLOCKED'] = '%s clan war is unlocked at level %s.';

$lang['BATTLE_CLAN_WAR_TITLE'] = 'Clan War';
$lang['BATTLE_CLAN_WAR'] = 'Clan-War';
$lang['BATTLE_SECTOR_ALL_CONQUERED'] = 'Sector already conquered!';
$lang['BATTLE_NO_CLAN'] = 'You are not part of a clan. Attack aborted!';
$lang['BATTLE_NOTE_CLAN_WAR'] = 'Note: Select a planet sector which you want to conquer. To take over a planet sector your clan must destroy its defence. Sector defence damage percentage is showed on the map.'; 

$lang['BATTLE_CLAN_WON'] = 'Your %s clan %s attacked the %s clan. You won the battle, taking %s damage, gain %s experience points and won %s dollars. ';
$lang['BATTLE_CLAN_SECTOR_DAMAGE'] = 'Sector defence is %s % damaged.';
$lang['BATTLE_CLAN_SECTOR_CONQUER'] = 'Brilliant! You conquered the sector.';
$lang['BATTLE_CLAN_LOST'] = 'Your %s clan %s attacked the %s clan. You lost the battle, taking %s damage. ';

$lang['BATTLE_CLAN_ATTACK_FORCE'] = 'Your clan %s attack %s (%s attack strength):';
$lang['BATTLE_CLAN_DEFENSE_FORCE'] = '%s %s clan defense %s (%s defense strength):'; 
$lang['BATTLE_CLAN_DEFENSE_BASE'] = '%s clan defence base:'; 

$lang['HELP_CLAN_WAR_TITLE'] = 'Clan War';
$lang['HELP_CLAN_WAR'] =	'Fight other clans to conquer all planet sectors. To take over a planet sector your clan must win 10 times. 
Each conquered sector is rewarded with a bonus. The more sectors you own, the higher the bonus. So WarQuest clan players go for world domination!';


/*
** ------------------
** Added v5.9
** ------------------
*/

$lang['GIFT_SHOP_TITLE'] = 'Gift Shop';
$lang['GIFT_SHOP_NOTE'] = 'The gift shop containing on this moment the above packages';
$lang['GENERAL_USD'] = 'USD';

$lang['GENERAL_GOLD'] = 'gold';
$lang['PLAYER_GOLD'] = 'Gold'; 

$lang['HOME_ANNOUNCEMENTS'] = 'Announcements';

/*
** ------------------
** Added v6.0
** ------------------
*/

$lang['GENERAL_SECTORS'] = 'Sector(s)';
$lang['GENERAL_INCOME_SECTOR'] = 'Income per sector';
$lang['GENERAL_TOTAL'] = 'Total';

$lang['PLAYER_CLAN_WAR_INCOME'] = 'Clan War income';

$lang['PLAYER_CLAN_WAR_OVERVIEW'] = 'Clan war income overview';
$lang['PLAYER_CLAN_WAR_TEXT'] = 'Player %s conquered the following %s sector(s):';

/*
** ------------------
** Added v6.2
** ------------------
*/

$lang['BATTLE_NO_UNITS_AVAILABLE'] = 'No units available to fight with!';

/*
** ------------------
** Added v6.3
** ------------------
*/

$lang['CLAN_ACCEPTED'] = 'You accepted %s to your %s clan.';
$lang['HOME_EMAIL_VALID'] = 'Email address is verified';

/*
** ------------------
** THE END
** ------------------
*/

?>