<?php

/* 
**  ========
**  WARQUEST
**  ========
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  All copyrights reserved (c) 2008-2013 PlaatSoft
*/

/*
** Some translation remarks:
** (1) Every line has the following syntax $lang['<KEY>'] = '<DESCRIPTION>';
**     Only change the <DESCRIPTION> part. Leave the rest unchanged.
** (2) The <DESCRIPTION> part contain %s tags. DO NOT REMOVE THEN.
**     The %s are realtime replace with game parameters. 
**     For example: 'Restore for %s dollars' will be on screen 'Restore for 100 dollars'
** (3) The LINK keys contain the menu items of the game. Choose as short as possible words.
** (4) Leave HTML tags unchanged, for example <b>, </b>, etc....
**
** Good luck and have fun!
*/

/*
** ------------------
** Language: Spanish
** ------------------
*/
 
/*
** ------------------
** LINKS
** ------------------
*/

/* Login */
$lang['LINK_LOGIN']  = 'Acceso'; 
$lang['LINK_REGISTER'] = 'Registro'; 
$lang['LINK_RECOVER'] = 'Recuperación'; 
$lang['LINK_MANUAL'] = 'Manual'; 
$lang['LINK_FACEBOOK'] = 'Facebook';
$lang['LINK_RSS']  = 'RSS'; 

/* General */
$lang['LINK_HOME'] = 'Inicio';
$lang['LINK_MISSIONS'] = 'Misiones';
$lang['LINK_BATTLE'] = 'Batalla';
$lang['LINK_UNITS']  = 'Unidades';
$lang['LINK_BUILDINGS']  = 'Edificios';
$lang['LINK_BANKS'] = 'Bancos';
$lang['LINK_ALLIANCE'] = 'Alianzas';
$lang['LINK_PLAYER'] = 'Jugador';
$lang['LINK_MONEY'] = 'Dinero';
$lang['LINK_HELP'] = 'Ayuda';
$lang['LINK_ADMIN'] = 'Admin';

$lang['LINK_FIRST']  = 'Primera';
$lang['LINK_PREVIOUS'] = 'Anterior';
$lang['LINK_NEXT'] = 'Siguiente';
$lang['LINK_LAST'] = 'Última';

/* Home */
$lang['LINK_RESTORE'] = 'Restaurar';
$lang['LINK_REPAIR'] = 'Reparar';
$lang['LINK_TRADE'] = 'Comercio';
$lang['LINK_ACTIVATE'] = 'Activar';

/* Player */
$lang['LINK_OVERVIEW'] = 'Inicio';
$lang['LINK_DELETE'] = 'Borrar';
$lang['LINK_SETTINGS'] = 'Ajustes';
$lang['LINK_NEWS'] = 'Noticias';
$lang['LINK_COMMENTS'] = 'Mensajes';
$lang['LINK_STATISTICS'] = 'Estadísticas';
$lang['LINK_LOGOUT'] = 'Salir';
$lang['LINK_EDIT'] = 'Editar';
$lang['LINK_SAVE'] = 'Guardar';
$lang['LINK_REPLY'] = 'Responder';
$lang['LINK_PROFILE'] = 'Perfil';
$lang['LINK_SKILLS'] = 'Habilidades';
$lang['LINK_RECRUIT']  = 'Invitar';
$lang['LINK_INCREASE'] = 'Aumentar';
$lang['LINK_DECREASE'] = 'Reducir';
$lang['LINK_RESTORE_NOW']  = 'Restaurar por %s dólares';
$lang['LINK_CHANGE'] = 'Cambio';
$lang['LINK_REPORT'] = 'Informe';
$lang['LINK_BOUNTY'] = 'Recompensa';

/* Mission */
$lang['LINK_PLAY'] = 'Jugar';
$lang['LINK_BUY_PLAY'] = 'Comprar y jugar';
$lang['LINK_DO_AGAIN'] = 'Volver a jugar';

/* Battle */
$lang['LINK_ATTACK'] = 'Atacar';
$lang['LINK_BATTLES']  = 'Batallas';
$lang['LINK_SP'] = 'Puntos de Habilidad';

/* Unit */
$lang['LINK_DEPLOY'] = 'Reclutar';
$lang['LINK_DEPLOY_AGAIN'] = 'Volver a reclutar';
$lang['LINK_DISBAND']  = 'Licenciar';
$lang['LINK_DISBAND_AGAIN']= 'Volver a licenciar';

/* Building */
$lang['LINK_INCOME'] = 'Ingresos';
$lang['LINK_DEFENSE'] = 'Defensa';
$lang['LINK_ENERGY'] = 'Energía';
$lang['LINK_BUY'] = 'Comprar';
$lang['LINK_BUY_AGAIN'] = 'Volver a comprar';
$lang['LINK_SELL'] = 'Vender';
$lang['LINK_SELL_AGAIN'] = 'Volver a vender';

/* Bank / Exchange / Casino */
$lang['LINK_BANK'] = 'Banco';
$lang['LINK_STOCKEXCHANGE'] = 'Bolsa';
$lang['LINK_CASINO'] = 'Casino';

$lang['LINK_DEPOSIT']  = 'Depositar';
$lang['LINK_WITHDRAW'] = 'Retirar';
$lang['LINK_BALANCE']  = 'Saldo';

/* Alliance */
$lang['LINK_INVITE'] = 'Invitar';
$lang['LINK_PENDING'] = 'Pendientes';
$lang['LINK_APPROVED'] = 'Aceptados';
$lang['LINK_COMMENT']  = 'Mensaje';
$lang['LINK_BEST_PLAYER']  = 'Mejores-Jugadores';
$lang['LINK_BEST_COUNTRY'] = 'Mejores-Países';
$lang['LINK_DROP'] = 'Descartar';
$lang['LINK_ACCEPT'] = 'Aceptar';
$lang['LINK_REJECT'] = 'Rechazar';
$lang['LINK_SEND'] = 'Enviar';
$lang['LINK_RESET']  = 'Borrar';

/* Forum */
$lang['LINK_FORUM']  = 'Forums';
$lang['LINK_POLLS'] = 'Encuestas';
$lang['LINK_CHATROOM'] = 'Chats';
$lang['LINK_SEARCH']  = 'Buscar';

/* Help */
$lang['LINK_GENERAL']  = 'Instrucciones';
$lang['LINK_NOTES']  = 'Notas de la versión';
$lang['LINK_RANKS']  = 'Rangos';
$lang['LINK_AWARDS'] = 'Condecoraciones';
$lang['LINK_LEVELS']  = 'Niveles';
$lang['LINK_STATS']  = 'Estadísticas';
$lang['LINK_DONATE']  = 'Donaciones';
$lang['LINK_ABOUT']  = 'Credits';

$lang['LINK_DISABLED'] = 'Deshabilitado';

/*
** ------------------
** GENERAL 
** ------------------
*/

$lang['SYSTEM_HACK_DETECTED'] = 'Por favor no utilizar botón de recarga, adelante o antrás!';

$lang['AGO_DAY']   = ' día';	
$lang['AGO_DAYS']  = ' días';
$lang['AGO_HOUR']  = ' hora';
$lang['AGO_HOURS'] = ' horas';
$lang['AGO_MIN']   = ' min';
$lang['AGO_MINS']  = ' mins';
$lang['AGO_SEC']   = ' seg';
$lang['AGO_SECS']  = ' segs';
	
$lang['COPYRIGHT'] = 'Copyright © 2008-2013 - Todos los derechos reservados - <a target="new" href="http://www.plaatsoft.nl">PlaatSoft</a>';

$lang['STATUS_CASH']  = 'Dinero';
$lang['STATUS_EXP']  = 'Exp.';
$lang['STATUS_LEVEL']  = 'Nivel';
$lang['STATUS_HEALTH'] = 'Salud';
$lang['STATUS_ENERGY'] = 'Energía';
$lang['STATUS_AMMO'] = 'Munición';
$lang['STATUS_ALLIANCE_SIZE'] = 'Núm.Aliados';

$lang['BOX_INFO'] = 'INFO';
$lang['BOX_WARN'] = 'ADVERTENCIA';
$lang['BOX_ERROR'] = 'ERROR';

$lang['GENERAL_NEXT_LEVEL'] = 'Brillante! Has alcanzado el siguiente nivel! Has recibido %s puntos de Habilidades y %s dólares. Tu salud, energía y munición se han restaurado. ';
$lang['GENERAL_BATTLE_LEVEL'] = 'Brillante! Has ganado %s batallas y recibes %s punto(s) extra de Habilidades y %s dólares';
$lang['GENERAL_BOUNTY_LEVEL'] = 'Genial! Has ofrecido %s recompensas y recibes %s punto(s) extra de Habilidades y %s dólares.';
$lang['GENERAL_REBEL_LEVEL'] = 'Genial! Has provocado %s rebeliones y recibes %s punto(s) extra de Habilidades y %s dólares.';
$lang['GENERAL_BATTLE_AWARD_WON'] = 'Combates ganados';
$lang['GENERAL_BOUNTY_AWARD_WON'] = 'recompensas ofrecidas';
$lang['GENERAL_REBEL_AWARD_WON'] = 'rebeliones provocadas';
$lang['GENERAL_UNLOCK'] = 'Desbloqueado en nivel %s';
$lang['GENERAL_NEW_FEATURES'] = 'Los siguientes elementos han sido desbloqueados:';
$lang['GENERAL_RECEIVED_AWARD'] = 'Condecoraciones recibidas:';

$lang['GENERAL_ATTACK'] = 'ataque';
$lang['GENERAL_DEFENSE'] = 'defensa';
$lang['GENERAL_INCOME']  = 'ingresos';
$lang['GENERAL_ENERGY']  = 'energía';
$lang['GENERAL_EXPERIENCE']  = 'experiencia';
$lang['GENERAL_DOLLAR']  = 'dólares';
$lang['GENERAL_ALLIANCE_SIZE'] = 'número aliados';
$lang['GENERAL_EXPERIENCE_POINTS'] = 'puntos experiencia';
$lang['GENERAL_UPKEEP'] = 'Coste por hora';
$lang['GENERAL_BANK']  = 'Banco';
$lang['GENERAL_DEPLOYED']  = 'Disponibles';

$lang['GENERAL_PLAYER']  = 'Jugador';
$lang['GENERAL_LEVEL'] = 'Nivel';
$lang['GENERAL_ALLIANCE']  = 'Alianzas';
$lang['GENERAL_WON'] = 'Ganados';
$lang['GENERAL_LOST']  = 'Perdidos';
$lang['GENERAL_AMOUNT'] = 'Cantidad';
$lang['GENERAL_DATE'] = 'Fecha';
$lang['GENERAL_TRANSACTION'] = 'Transacción';
$lang['GENERAL_BALANCE'] = 'Saldo';
$lang['GENERAL_APPROVED'] = 'Aprobado';
$lang['GENERAL_EMAIL'] = 'Email';
$lang['GENERAL_TOP']	= 'Top';
$lang['GENERAL_EXP'] = 'Experiencia';
$lang['GENERAL_COUNTRY'] = 'País';
$lang['GENERAL_PLAYERS'] = 'Jugadores';
$lang['GENERAL_WONS']  = 'Ganados';
$lang['GENERAL_LOSTS'] = 'Perdidos';
$lang['GENERAL_NO'] = 'No';
$lang['GENERAL_YES'] = 'Sí';
$lang['GENERAL_AGO'] = 'Hace';
$lang['GENERAL_MESSAGE'] = 'Mensaje';
$lang['GENERAL_ACTION'] = 'Acción';
$lang['GENERAL_NUMBER'] = 'Núm.';
$lang['GENERAL_DISCOUNT'] = 'Descuento edificios';
$lang['GENERAL_REQUESTS'] = 'Solicitudes';
$lang['GENERAL_EP'] = 'Puntos Habilidad';
$lang['GENERAL_AWARD'] = 'Condecoración';
$lang['GENERAL_LANGUAGE'] = 'Idioma';
$lang['GENERAL_RANKING'] = 'Ranking';

$lang['GENERAL_NEW_UNIT'] = 'NUEVA UNIDAD';
$lang['GENERAL_NEW_BUILDING'] = 'NUEVO EDIFICIO';
$lang['GENERAL_NEW_MISSION'] = 'NUEVA MISIÓN';
$lang['GENERAL_GAIN'] = 'conseguir';

$lang['GENERAL_BOUNTY'] = 'Recompensa';
$lang['GENERAL_INTELLIGENCE'] = 'Inteligencia';
$lang['GENERAL_SPIES'] = 'espías';
$lang['GENERAL_MAINTENANCE'] = 'Mantenimiento unidades';

$lang['GENERAL_CNTRY'] = 'País';
$lang['GENERAL_TOPICS'] = 'temas'; 
$lang['GENERAL_FORUM'] = 'Forum';
$lang['GENERAL_MESSAGES'] = 'mensajes';
$lang['GENERAL_LAST_MESSAGE'] = 'Último Mensaje';
$lang['GENERAL_FORUM_MODERATED'] = '(Moderado por %s)';
$lang['GENERAL_NOT_MODERATED'] = '(Sin Moderador)';
$lang['GENERAL_BY'] = 'atrás';
$lang['GENERAL_TOPIC'] = 'Tema';
$lang['GENERAL_LOCKED'] = 'Bloqueado';
$lang['GENERAL_WORLDMAP'] = 'Mapa Mundial';
$lang['GENERAL_PLAATSOFT'] = 'PlaatSoft';
$lang['GENERAL_CONQUER'] = 'Conquistar';

$lang['GENERAL_ST'] = '%er';
$lang['GENERAL_ND'] = '%º';
$lang['GENERAL_TH'] = '%º';

$lang['GENERAL_CONTINENT'] = 'Continente';
$lang['GENERAL_CONQUERED'] = 'Conquistado';

$lang['GENERAL_IDLE'] = 'Libre';
$lang['GENERAL_ACTIVE'] = 'Activo';
$lang['GENERAL_INACTIVE'] = 'Inactivo';

$lang['GENERAL_PLANET'] = 'Planeta';
$lang['GENERAL_PLANET_0'] = 'Tierra';
$lang['GENERAL_PLANET_1'] = 'Luna';
$lang['GENERAL_PLANET_2'] = 'Marte';
$lang['GENERAL_PLANET_3'] = 'Asteroide';

/*
** ------------------
** TIP
** ------------------
*/

$lang['TIP_GENERAL']  = 'CONSEJOS';
$lang['TIP_0'] = 'Juege la misión de entrenamiento para acumular puntos de experiencia y llegar al siguiente nivel.';
$lang['TIP_1'] = 'Compre algunas unidades de combate y empiece a entrenar para acumular puntos de experiencia.';
$lang['TIP_2'] = 'Comercie con los puntos de Habilidad recibidos (Inicio -> Habilidades) para mejorar sus Habilidades de soldado.';
$lang['TIP_3'] = 'Introduzca su dirección de correo electrónico para recibir notificaciones de mensajes y de alianzas!';
$lang['TIP_4'] = 'Compre algunos edificios de ingresos para obtener ingresos cada hora.';
$lang['TIP_5'] = 'Compre algunos edificios de defensa para mejorar su fuerza defensiva.';
$lang['TIP_6'] = 'Haga alianzas con los jugadores para mejorar su fuerza de ataque / defensa.';
$lang['TIP_7'] = 'Guarde el dinero en efectivo en el Banco Nacional para mantenerlo a salvo de otros jugadores.';
$lang['TIP_8'] = 'Acumule puntos de experiencia adicionales al votar en las encuestas disponibles!';
$lang['TIP_9'] = 'Establezca recompensas sobre otros jugadores para recibir premios por recompensas.';
$lang['TIP_10'] = 'Visite el Casino para jugar a la Rueda de la Fortuna y ganar más dinero.';
$lang['TIP_11'] = 'Compre edificios de energía para recuperar energía con mayor rapidez.';
$lang['TIP_12'] = 'Compre unidades de Inteligencia para espiar a otros jugadores y comenzar la rebelión en sus continentes.';
$lang['TIP_13'] = 'Guarde el dinero en efectivo en el banco Trasquera para percibir intereses diarios.';
$lang['TIP_14'] = 'Visite el foro. Las nuevas ideas para el juego son bienvenidas!';
$lang['TIP_15'] = 'Eche un vistazo a la sección de Ayuda para más información.';
$lang['TIP_16'] = 'Compra / venta de acciones para conseguir más ganancias (Dinero -> Bolsa)';
$lang['TIP_17'] = 'Guarde el dinero en efectivo en el banco SwissCore para percibir intereses diarios.';
$lang['TIP_18'] = 'Complete todas las misiones del continente para recibir puntos extra de habilidad.';
$lang['TIP_19'] = 'Reparación de unidades (Inicio -> Restaurar) para evitar la pérdida de unidades';
$lang['TIP_20'] = 'Visite el Casino para jugar en la máquina tragamonedas y ganar más dinero.';
$lang['TIP_21'] = 'Reparación de los edificios (Inicio -> Restaurar) para evitar la pérdida de edificios';
$lang['TIP_22'] = 'Siga jugando y conviértase en el mejor jugador de su país!';

$lang['TIP_90'] = 'Está a sólo 10 niveles de iniciar su propia colonia lunar.';
$lang['TIP_91'] = 'Está a sólo 9 niveles de iniciar su propia colonia lunar.';
$lang['TIP_92'] = 'Está a sólo 8 niveles de iniciar su propia colonia lunar.';
$lang['TIP_93'] = 'Está a sólo 7 niveles de iniciar su propia colonia lunar.';
$lang['TIP_94'] = 'Está a sólo 6 niveles de iniciar su propia colonia lunar.';
$lang['TIP_95'] = 'Está a sólo 5 niveles de iniciar su propia colonia lunar.';
$lang['TIP_96'] = 'Está a sólo 4 niveles de iniciar su propia colonia lunar.';
$lang['TIP_97'] = 'Está a sólo 3 niveles de iniciar su propia colonia lunar.';
$lang['TIP_98'] = 'Está a sólo 2 niveles de iniciar su propia colonia lunar.';
$lang['TIP_99'] = 'Está a sólo 1 nivel de iniciar su propia colonia lunar.';
$lang['TIP_100'] = 'Comience su propia colonia lunar!';

$lang['TIP_140'] = 'Está a sólo 10 niveles de iniciar su propia colonia en Marte.';
$lang['TIP_141'] = 'Está a sólo 9 niveles de iniciar su propia colonia en Marte.';
$lang['TIP_142'] = 'Está a sólo 8 niveles de iniciar su propia colonia en Marte.';
$lang['TIP_143'] = 'Está a sólo 7 niveles de iniciar su propia colonia en Marte.';
$lang['TIP_144'] = 'Está a sólo 6 niveles de iniciar su propia colonia en Marte.';
$lang['TIP_145'] = 'Está a sólo 5 niveles de iniciar su propia colonia en Marte.';
$lang['TIP_146'] = 'Está a sólo 4 niveles de iniciar su propia colonia en Marte.';
$lang['TIP_147'] = 'Está a sólo 3 niveles de iniciar su propia colonia en Marte.';
$lang['TIP_148'] = 'Está a sólo 2 niveles de iniciar su propia colonia en Marte.';
$lang['TIP_149'] = 'Está a sólo 1 nivel de iniciar su propia colonia en Marte.';
$lang['TIP_150'] = 'Comience su propia colonia en Marte!';

$lang['TIP_190'] = 'Está a sólo 10 niveles de iniciar su propia colonia en el asteroide.';
$lang['TIP_191'] = 'Está a sólo 9 niveles de iniciar su propia colonia en el asteroide.';
$lang['TIP_192'] = 'Está a sólo 8 niveles de iniciar su propia colonia en el asteroide.';
$lang['TIP_193'] = 'Está a sólo 7 niveles de iniciar su propia colonia en el asteroide.';
$lang['TIP_194'] = 'Está a sólo 6 niveles de iniciar su propia colonia en el asteroide.';
$lang['TIP_195'] = 'Está a sólo 5 niveles de iniciar su propia colonia en el asteroide.';
$lang['TIP_196'] = 'Está a sólo 4 niveles de iniciar su propia colonia en el asteroide.';
$lang['TIP_197'] = 'Está a sólo 3 niveles de iniciar su propia colonia en el asteroide.';
$lang['TIP_198'] = 'Está a sólo 2 niveles de iniciar su propia colonia en el asteroide.';
$lang['TIP_199'] = 'Está a sólo 1 nivel de iniciar su propia colonia en el asteroide.';
$lang['TIP_200'] = 'Comience su propia colonia en el Asteroide!';

/*
** ------------------
** LOGIN PAGE
** ------------------
*/

$lang['LOGIN_MEMBER_TITLE'] = 'Registro usuario';
$lang['LOGIN_REGISTER_TITLE'] = 'Registro libre';
$lang['LOGIN_RECOVER_TITLE'] = 'Recuperación de contraseña';
$lang['LOGIN_MANUAL_TITLE'] = 'Manual';

$lang['LOGIN_PLAYERS'] = 'jugadores';
$lang['LOGIN_REQUESTS'] = 'solicitudes';
$lang['LOGIN_COUNTRIES'] = 'países';
$lang['LOGIN_ONLINE'] = 'jugadores online';

$lang['LOGIN_PASSWORD'] = 'Contraseña';
$lang['LOGIN_USERNAME'] = 'Nombre usuario';
$lang['LOGIN_EMAIL'] = 'Email';
$lang['LOGIN_NICKNAME']  = 'Apodo';

$lang['LOGIN_MAINTENANCE_TITLE'] = 'Mantenimiento del servidor';
$lang['LOGIN_MAINTENANCE'] = 'En estos momentos estamos realizando mantenimiento del servidor. Por favor, vuelva a intentarlo en 30 minutos. Gracias!';

$lang['LOGIN_LOGOUT'] = 'Ahora está desconectado!'; 
$lang['LOGIN_FAILED'] = 'Nombre de usuario y / o contraseña incorrecto!';
$lang['LOGIN_REGISTER_OK'] = 'Cuenta de usuario %s esta creada!';
$lang['LOGIN_PASSWORD_TO_SHORT'] = 'La contraseña debe tener como mínimo 6 caracteres!';
$lang['LOGIN_USERNAME_TO_SHORT'] = 'El nombre de usuario debe tener al menos 4 caracteres!';
$lang['LOGIN_USERNAME_EXIST'] = 'El nombre de usuario %s ya existe!';
$lang['LOGIN_EMAIL_EXIST'] = 'El email ya está registrado!';
$lang['LOGIN_EMAIL_INVALID'] = 'El email no válido! (formato invalido)';
$lang['LOGIN_NICKNAME_EXIST'] = 'El apodo %s ya está en uso!';
$lang['LOGIN_NICKNAME_NEEDED'] = 'Debe introducir el Apodo!';
$lang['LOGIN_NEW_PASSWORD_SEND'] = 'La nueva contraseña se ha enviado a su correo electrónico!';
$lang['LOGIN_EMAIL_UNKNOWN'] = 'email desconocido!';
$lang['LOGIN_BEST_VIEWED'] = 'WarQuest está optimizado para los siguientes sistemas de móvil: "Apple iOS/iPad, Nokia Symbian, 
BlackBerry OS, Android OS" y los navegadores de Internet: "Internet Explorer, Mozilla Firefox, Apple Safari, Opera, Google Chrome". 
Este juego se ve mejor con un navegador configurado a un ancho de 500px. ';

$lang['LOGIN_NEW_CLIENT_TITLE'] = 'Nueva versión WarQuest disponible!';
$lang['LOGIN_NEW_CLIENT'] = 'Usted está utilizando una versión Warquest de windows antigua. Por favor, visite www.plaatsoft.nl para obtener la versión más reciente.';

$lang['LOGIN_PASSWORD_RESET_NOTE'] = 'Si ha olvidado su contraseña, introduzca su dirección de correo electrónico y le enviaremos una nueva contraseña por correo electrónico.';

/*
** ------------------
** HOME - OVERVIEW
** ------------------
*/

$lang['HOME_TITLE'] = 'INICIO';

$lang['HOME_FLASH_NEWS_TITLE'] = 'Noticias de última hora';

$lang['HOME_LASTEST_FORUM_POST'] = 'Último mensaje en el foro';

$lang['HOME_INTRO_PLAYERS'] = 'En este momento %s jugadores de %s países están activos, ';
$lang['HOME_INTRO_FIGHTS'] = '%s combates han tenido lugar ';
$lang['HOME_INTRO_REQUESTS'] = '%s conexiones se gestionaron en el servidor. ';
		
$lang['HOME_INTRO_TITLE'] = 'Introducción';
$lang['HOME_INTRO_MISSIONS'] = 'Inicia el juego para jugar %s ';
$lang['HOME_INTRO_BATTLES'] = 'y combate %s. ';
$lang['HOME_INTRO_UNITS'] = 'Cuando usted gana dinero y puntos de experiencia puede comprar mejores %s ';
$lang['HOME_INTRO_BUILDINGS'] = ' y %s para ser mas poderoso. ';
$lang['HOME_INTRO_ENEMY'] = ' En cualquier momento otros jugadores pueden atacarte, así que mantenga actualizada su defensa.';

$lang['HOME_NEW_ANDROID_VERSION'] = 'Nueva versión de aplicación v%s disponible en Android Market.<br/>Actualiza por favor!';
$lang['HOME_NEW_WINDOWS_VERSION'] = 'Nueva versión de windows Warquest v%s disponible!';
$lang['HOME_CLICK_HERE'] = 'aquí';
$lang['HOME_CLICK_TEXT'] = 'Click %s para iniciar descarga.';
$lang['HOME_EMAIL_MISSING'] = 'Por favor, proporcione su dirección de correo electrónico para recibir mensajes de jugadores por correo y para la recuperación de la contraseña.';
$lang['HOME_DAILY_BONUS'] = 'Encontraste %s dólares en una ubicación del enemigo!';

$lang['HOME_WELCOME'] = 'Bienvenido';
$lang['HOME_LAST_LOGIN'] = 'La última visita fue hace <b>%s</b>.';
$lang['HOME_AWARDS'] = 'Condecoraciones';
$lang['HOME_BATTLE_AWARDS_TEXT'] = 'Usted ha ganado las siguientes condecoraciones de batalla:';
$lang['HOME_BOUNTY_AWARDS_TEXT'] = 'Usted ha ganado las siguientes condecoraciones por recompensas:';
$lang['HOME_REBEL_AWARDS_TEXT'] = 'Usted ha ganado las siguientes condecoraciones por rebeliones:';
$lang['HOME_OVERVIEW_TITLE']= 'Resumen';
$lang['HOME_MAP_TITLE'] = 'Continentes conquistados';
$lang['HOME_MAP_NOTE'] = 'Cada continente consiste de tres regiones que pueden ser conquistadas a través de las misiones.';

$lang['HOME_TRAVEL_TO'] = 'Viajar a';

$lang['HOME_INTRO_PLACE1'] = 'Usted ocupa el <b>%s</b> lugar en la clasificación general '; 
$lang['HOME_INTRO_PLACE2'] = 'y el <b>%s</b> lugar de la clasificacion de <b>%s</b>. '; 
$lang['HOME_PLAYERS_ONLINE'] = 'Las ultimas 24 h %s jugadores estuvieron conectados.';

$lang['HOME_HOLIDAY'] = 'Vacaciones';
$lang['HOME_HOLIDAY_PERIOD_ACTIVE'] = 'Periodo de vacaciones activado por %s. Las misiones, batallas, unidades, edificios y opciones del dinero están bloqueadas durante este período!';

/*
** ------------------
** HOME - PROFILE
** ------------------
*/

$lang['PLAYER_TITLE'] = 'JUGADOR';
$lang['PLAYER_WIN_LOST_RATE'] = 'Ratio Victorias/Derrotas';
$lang['PLAYER_BUILDINGS'] = 'Edificios';
$lang['PLAYER_CASH_FLOW'] = 'Flujo de fondos';
$lang['PLAYER_ALLIANCE_SIZE'] = 'Número de aliados';
$lang['PLAYER_EXP_POINTS']  = 'Puntos Experiencia';
$lang['PLAYER_SERVER_REQUEST']  = 'Conexiones servidor';
$lang['PLAYER_MISSION_COMPLETED'] = 'Misiones completadadas';
$lang['PLAYER_DEFENSE_STRENGTH']  = 'Fuerza de defensa';
$lang['PLAYER_ATTACK_STRENGTH'] = 'Fuerza de ataque';
$lang['PLAYER_FIGHTS_LOST'] = 'Derrotas';
$lang['PLAYER_FIGHTS_WON']  = 'Victorias';
$lang['PLAYER_BUILDING_INCOME'] = 'Ingreso por edificios';
$lang['PLAYER_CONTINENT_INCOME'] = 'Ingreso por continentes';
$lang['PLAYER_BOUNTY_SET'] = 'Recompensas ofrecidas';
$lang['PLAYER_REBELLION_RISE'] = 'Rebeliones provocadas';
$lang['PLAYER_UPKEEP']  = 'Coste/hora de unidades';
$lang['PLAYER_NETTO_INCOME']  = 'Ingreso neto';
$lang['PLAYER_STATISTICS']  = 'Estadísticas'; 
$lang['PLAYER_DISCOUNT_MAINTENANCE']  = 'Descuento y Mantenimiento';
$lang['PLAYER_NAME']  = 'Nombre'; 
$lang['PLAYER_ID']  = 'Id';
$lang['PLAYER_RANK']  = 'Rango'; 
$lang['PLAYER_OVERVIEW']  = 'Perfil'; 
$lang['PLAYER_DISCOUNT_RATE'] = 'Descuento edificios';
$lang['PLAYER_MAINTENANCE_RATE'] = 'Mantenimiento unidades';
$lang['PLAYER_LAST_LOGIN'] = 'Última sesión (hace)';
$lang['PLAYER_CREATED'] = 'Creado (hace)';
$lang['PLAYER_CASINO_PLAYED']  = 'Jugadas de Casino';
$lang['PLAYER_ADS_SHOWED']  = 'Anuncios mostrados';
$lang['PLAYER_TOTAL_HOURLY_INCOME'] = 'Ingresos/hora total';

$lang['PLAYER_MONEY_STATUS'] = 'Activos actuales';
$lang['PLAYER_CASH_MONEY'] = 'Dinero';
$lang['PLAYER_BANK'] = 'Banco';

$lang['PLAYER_PLATFORM_BROWSER'] = 'Plataforma & Navegador';
$lang['PLAYER_BROWSER'] = 'Navegador';
$lang['PLAYER_BROWSER_VERSION'] = 'Versión';
$lang['PLAYER_PLATFORM'] = 'Plataforma';

$lang['PLAYER_LAST_TWEET'] = 'Último Tweet';

$lang['PLAYER_ATTACK_FORCE'] = 'Resumen (%s Ataque %s)';
$lang['PLAYER_DEFENSE_FORCE'] = 'Resumen (%s Defensa %s)';
$lang['PLAYER_ATTACK_TEXT'] = '%s tienes actualmente <b>%s</b> aliados y puedes dirigir máx. <b>%s</b> unidades. El ataque de %s dispone de las siguientes unidades:';
$lang['PLAYER_DEFENSE_TEXT'] = '%s tienes actualmente <b>%s</b> aliados y puedes dirigir máx. <b>%s</b> unidades. La defensa de %s dispone de las siguientes unidades:';
$lang['PLAYER_UNIT'] = 'Unidad';
$lang['PLAYER_AMOUNT'] = 'Cantidad';
$lang['PLAYER_STRENGTH'] = 'Fuerza';
$lang['PLAYER_ATTACK_SKILLS'] = 'Habilidades de ataque';
$lang['PLAYER_DEFENSE_SKILLS'] = 'Habilidades de defensa';
$lang['PLAYER_SUB_TOTAL'] = 'Sub. total';
$lang['PLAYER_TOTAL'] = 'Total';
$lang['PLAYER_FORCE'] = 'Fuerza de Ataque & Defensa'; 
$lang['PLAYER_DEPLOYED'] = 'Disponibles';

$lang['PLAYER_BUILDING'] = 'Edificio';
$lang['PLAYER_INCOME'] = 'INGRESO';
$lang['PLAYER_COST'] = 'Gasto';
$lang['PLAYER_BUILDING_OVERVIEW'] = 'Resumen de ingresos de edificios';
$lang['PLAYER_BUILDING_TEXT'] = 'Actualmente, %s tiene los siguientes ingresos por edificios en %s:';
$lang['PLAYER_UPKEEP_COST'] = 'Resumen coste por hora';
$lang['PLAYER_UPKEEP_TEXT'] = 'Actualmente, %s dispone de las siguiente(s) unidad(es) en %s :';
$lang['PLAYER_CONTINENT_OVERVIEW'] = 'Resumen de ingresos por continentes';
$lang['PLAYER_CONTINENT_TEXT'] = 'Jugador %s ha conquistado los siguientes continentes en %s :';

$lang['PLAYER_DISCOUNT_OVERVIEW'] = 'Resumen de descuento en edificios';
$lang['PLAYER_BUILDING_TEXT'] = 'Actualmente, %s tiene los siguientes edificios de descuento en %s:';

$lang['PLAYER_MAINTENANCE_OVERVIEW'] = 'Resumen de mantenimiento de edificios';
$lang['PLAYER_MAINTENANCE_TEXT'] = 'Actualmente, %s tiene los siguientes edificios de mantenimiento en %s:';

$lang['PLAYER_SPY_1'] = 'Inteligencia';
$lang['PLAYER_SPY_2'] = 'Exploradores';
$lang['PLAYER_SPY_3'] = 'Exploradores';
$lang['PLAYER_SPY_4'] = 'Exploradores';
$lang['PLAYER_ESPIONAGE_UNLOCK1'] = 'Desbloqueado cuando tu fuerza de %s sea %s% superior a la de tu oponente.';
$lang['PLAYER_ESPIONAGE_UNLOCK2'] = 'Desbloqueado cuando tu fuerza de %s sea igual o superior a la de tu oponente.';

/*
** ------------------
** HOME - NEWS
** ------------------
*/

$lang['HOME_BATTLE_TITLE'] = 'Noticias';
$lang['HOME_BATTLE_ATTACK_BY'] = 'Fuiste atacado por %s de %s.';
$lang['HOME_BATTLE_YOU_WON'] = 'Tu <b>VENCISTE</b>. ';
$lang['HOME_BATTLE_YOU_LOST'] = 'TU <b>HAS PERDIDO</b>. ';
$lang['HOME_BATTLE_YOU_EXP'] = 'Usted ganÓ %s de experiencia ';
$lang['HOME_BATTLE_TOOK_DAMAGE'] = 'y causo %s de daños.';
$lang['HOME_BATTLE_TAKING_DAMAGE'] = 'y recibiÓ %s de daños.';
$lang['HOME_BATTLE_YOU_MONEY'] = 'Perdiendo %s dolares ';
$lang['HOME_BATTLE_NO_NEWS'] = 'No hay noticias de batalla disponibles en este momento!'; 

$lang['HOME_BOUNTY_NEWS'] = '%s ha ofrecido %s dÓlares por tu cabeza! Si eres derrotado perderás %s puntos de experiencia.';

/*
** ------------------
** HOME - MESSAGE
** ------------------
*/

$lang['HOME_MESSAGES_TITLE']= 'Mensajes';
$lang['HOME_MESSAGE_DELETED'] = 'Mensaje borrado!';
$lang['HOME_NO_MESSAGES'] = 'No hay mensajes de otros jugadores disponibles en este momento!'; 

/*
** ------------------
** HOME - SKILLS
** ------------------
*/

$lang['PLAYER_SKILL_SUBTITLE1']  = 'Puntos de Habilidad';
$lang['PLAYER_SKILL_SUBTITLE2']  = 'Puntos de Habilidad [%s disponibles]';
$lang['PLAYER_SKILL_NOTE']  = 'Nota: Use los puntos de habilidades para aumentar el ataque, defensa, salud, energía o munición.';
$lang['PLAYER_SKILLS']  = 'habilidades'; 
$lang['PLAYER_MAX'] = 'Actual'; 
$lang['PLAYER_ATTACK']  = 'ATAQUE';
$lang['PLAYER_DEFENSE'] = 'DEFENSA';
$lang['PLAYER_HEALTH']  = 'SALUD'; 
$lang['PLAYER_ENERGY']  = 'ENERGÍA'; 
$lang['PLAYER_AMMO']  = 'MUNICIÓN'; 

$lang['PLAYER_ATTACK_TIP']  = 'Aumente su habilidad de ataque para causar más daños y ganar los combates. Se necesita %s para aumentar su fuerza de ataque en %s. Disminuya su habilidad de ataque en %s para conseguir 1 punto de habilidad a cambio.';
$lang['PLAYER_DEFENSE_TIP'] = 'Aumente su habilidad de defensa para resistir contra los ataques. Se necesita %s para aumentar su fuerza de defensa con %s. Disminuya su habilidad de defensa en %s para conseguir 1 punto de habilidad a cambio.';
$lang['PLAYER_HEALTH_TIP']  = 'Aumente su habilidad de salud máx. para sobrevivir a largas luchas. Se necesita %s para aumentar el nivel max de salud en 10. Disminuya su nivel de salud en 20 para conseguir 1 punto de habilidad a cambio.';
$lang['PLAYER_ENERGY_TIP']  = 'Aumente su habilidad de energia máx. para jugar mas misiones. Se necesita %s para aumentar el nivel max de energia en 10. Disminuya su nivel de energia en 20 para conseguir 1 punto de habilidad a cambio.';
$lang['PLAYER_AMMO_TIP']  = 'Aumente su habilidad de munición máx. para aumentar su capacidad de lucha. Se necesitan %s para aumentar tu municion en 1. Disminuya su nivel de municion en 1 para conseguir 1 punto de habilidad a cambio.';

$lang['PLAYER_SKILL_ACCEPTED1']  = '%s habilidad aumentada.';
$lang['PLAYER_SKILL_REJECTED1']  = 'Necesita %s punto(s) de habilidad para cambiar esta habilidad.';
$lang['PLAYER_SKILL_ACCEPTED2']  = '%s habilidad reducida.';
$lang['PLAYER_SKILL_REJECTED2']  = '%s habilidad ha alcanzado el nivel mínimo.';

/*
** ------------------
** HOME - TRADE
** ------------------
*/

$lang['HOME_TRADE_TITLE1'] = 'Puntos de comercio';
$lang['HOME_TRADE_TITLE2'] = 'Puntos de comercio [%s disponibles]';
$lang['HOME_TRADE_NOTE']  = 'Nota: los puntos de comercio adquiridos (ver ayuda - Página de donaciones) se pueden cambiar por puntos de habilidad, dinero en efectivo o se pueden utilizar para mejorar el tiempo de recuperación de su salud, energía o munición.';

$lang['HOME_TRADE_CONDITION'] = 'Actual';
$lang['HOME_TRADE_MINIMAL'] = 'Mínimo';

$lang['HOME_TRADE1'] = 'Temporizador Salud';
$lang['HOME_TRADE1_NOTE'] = 'Disminuya el temporizador de salud para que su salud se restaure más rápido. Se necesita un punto de comercio para disminuir el temporizador de salud en 5 segundos.';

$lang['HOME_TRADE2'] = 'Temporizador Energía';
$lang['HOME_TRADE2_NOTE'] = 'Disminuya el temporizador de energía para que su energía se restaure más rápido. Se necesita punto de comercio para disminuir el temporizador de energía en 5 segundos.';

$lang['HOME_TRADE3'] = 'Temporizador Munición';
$lang['HOME_TRADE3_NOTE'] = 'Disminuya el temporizador de munición para que su munición se restaure más rápido. Se necesita un punto de comercio para disminuir el temporizador de municion en 5 segundos.';

$lang['HOME_TRADE4'] = 'Dinero';
$lang['HOME_TRADE4_NOTE'] = 'Consiga dinero en efectivo para comprar nuevas unidades, edificios, etc. Se necesita un punto de comercio para aumentar su dinero en efectivo con %s dólares.';

$lang['HOME_TRADE5'] = 'Punto Habilidad';
$lang['HOME_TRADE5_NOTE'] = 'Consiga puntos de habilidad para mejorar su ataque, defensa, salud, energía o munición. Se necesita un punto de comercio para obtener 2 puntos de habilidad.';

$lang['HOME_TRADE_SKILL_POINTS'] = 'punto(s) habilidad';
$lang['HOME_TRADE_IN'] = 'Comerciar';
$lang['HOME_MAX_REACHED'] = 'Máximo alcanzado';

$lang['HOME_TRADE_HEALTH_TIMER_TO_LARGE'] = 'El temporizador de Salud ha alcanzado el valor mínimo.';
$lang['HOME_TRADE_ENERGY_TIMER_TO_LARGE'] = 'El temporizador de Energia ha alcanzado el valor mínimo.';
$lang['HOME_TRADE_AMMO_TIMER_TO_LARGE'] = 'El temporizador de Municion ha alcanzado el valor mínimo.';

/*
** ------------------
** HOME - RESTORE
** ------------------
*/

$lang['PLAYER_RESTORE_TITLE'] = 'Restaurar & Reparar';
$lang['PLAYER_RESTORE_SUBTITLE1'] = 'Restaurar';
$lang['PLAYER_RESTORE_SUBTITLE2'] = 'Reparar';
$lang['PLAYER_RESTORE_UNLOCKED'] = 'Restaurar & Reparar se desbloquea en el nivel %s.';
$lang['PLAYER_RESTORE_PRICE'] = 'Precio por Restaurar';
$lang['PLAYER_RESTORE_PRICE_PER_DAY'] = 'Precio de restaurar diario';
$lang['PLAYER_REPAIR_PRICE'] = 'Precio de Reparación';
$lang['PLAYER_RESTORED_FAILED'] = 'No dispones de %s dólares para ejecutar esta acción.';

$lang['PLAYER_HEALTH_TITLE'] = 'Restaurar Salud';
$lang['PLAYER_HEALTH_NOTE'] = 'Pague el hospital para restaurar la salud de su ejército por completo. Restaurar sólo puede utilizarse una vez cada 5 minutos. La Salud también se restaura por sí misma con el paso del tiempo.';	
$lang['PLAYER_HEALTH_CONDITION'] = 'Estado de salud';
$lang['PLAYER_HEALTH_RESTORED'] = 'Salud restaurada por %s dólares.';
$lang['PLAYER_HEALTH_CONFIRM'] = 'Realmente desea restaurar la salud?';

$lang['PLAYER_ENERGY_TITLE'] = 'Restaurar energía';
$lang['PLAYER_ENERGY_NOTE'] = 'Pague a la empresa petrolera para restaurar la energía de su ejército por completo. Restaurar sólo puede utilizarse una vez cada 24 horas. La energía también se restaura por sí misma con el paso del tiempo. ';	
$lang['PLAYER_ENERGY_CONDITION'] = 'Estado de energía';
$lang['PLAYER_ENERGY_RESTORED'] = 'Energía restaurada por %s dólares.';
$lang['PLAYER_ENERGY_CONFIRM'] = 'Realmente desea restaurar la energía?';

$lang['PLAYER_AMMO_TITLE'] = 'Restaurar munición';
$lang['PLAYER_AMMO_NOTE'] = 'Pague a la fábrica de armas para restaurar la munición de su ejército por completo. Restaurar sólo puede utilizarse una vez cada 24 horas. La munición también se restaura por sí misma con el paso del tiempo.';	
$lang['PLAYER_AMMO_CONDITION'] = 'Estado de munición';
$lang['PLAYER_AMMO_RESTORED'] = 'Munición restaurada por %s dólares.';
$lang['PLAYER_AMMO_CONFIRM'] = 'Realmente desea restaurar munición?';

$lang['PLAYER_CEASE_FIRE_TITLE'] = 'Periodo de alto el fuego';
$lang['PLAYER_CEASE_FIRE_NOTE'] = 'Pague dinero para iniciar un período de alto el fuego. Durante este período, otros jugadores no pueden atacarle, ni se puede atacar a otros.';	
$lang['PLAYER_CEASE_FIRE_ACTIVATED'] = 'Periodo de alto el fuego activado por %s dólares.';
$lang['PLAYER_CEASE_FIRE_CONFIRM'] = 'Está seguro que desea activar el período de alto el fuego?';
$lang['PLAYER_HOLIDAY_TITLE'] = 'Vacaciones';
$lang['PLAYER_HOLIDAY_NOTE'] = 'Relájese activando un período de vacaciones. Durante este período, su cuenta está congelada (las opciones de misiones, batalla, unidades y edificios estarán bloqueadas) y los otros jugadores no le pueden atacar.';	
$lang['PLAYER_HOLIDAY_ACTIVATED'] = 'Vacaciones activadas por %s dólares.';
$lang['PLAYER_HOLIDAY_CONFIRM'] = 'Está seguro que desea activar un período de vacaciones?';

$lang['PLAYER_UNITS_TITLE'] = 'Reparar unidades';
$lang['PLAYER_UNITS_NOTE'] = 'Repare las unidades de su ejército. Si el estado de las unidades llega a 0% algunas unidades serán destruidas y las unidades restantes se reparan de forma automática.';	
$lang['PLAYER_UNITS_CONDITION'] = 'Estado unidades (EU)';
$lang['PLAYER_UNITS_REPAIRED'] = 'Sus unidades son reparadas por %s dólares.';
$lang['PLAYER_UNITS_CONFIRM'] = 'Realmente desea reparar sus unidades?';

$lang['PLAYER_BUILDINGS_TITLE'] = 'Reparar edificios';
$lang['PLAYER_BUILDINGS_NOTE'] = 'Repare los edificios de la base. Si el estado de lod edificios llega a 0%, algunos de los edificios serán destruidos y los edificios restantes se reparan de forma automática.';	
$lang['PLAYER_BUILDINGS_CONDITION'] = 'Estado Edificios (EE)';
$lang['PLAYER_BUILDINGS_REPAIRED'] = 'Sus edificios son reparados por %s dólares.';
$lang['PLAYER_BUILDINGS_CONFIRM'] = 'Realmente desea reparar sus edificios?';

$lang['PLAYER_REBELLION_TITLE'] = 'Restaurar la Paz';
$lang['PLAYER_REBELLION_NOTE'] = 'Pague a Inteligencia para terminar con las rebeliones en sus regiones conquistadas recientemente. Si el estado de rebelión alcanza un 100% algunas regiones se perderán debido a los rebeldes y deberán ser reconquistadas.';	
$lang['PLAYER_REBELLION_CONDITION'] = 'Estado de Rebelion (ER)';
$lang['PLAYER_REBELLION_RESTORED'] = 'Termina con la rebelión por %s dólares.';
$lang['PLAYER_REBELLION_CONFIRM'] = 'Realmente desea restaurar la paz?';

/*
** ------------------
** HOME - SETTINGS
** ------------------
*/

$lang['SETTING_TITLE'] = 'Configuración';
$lang['SETTING_GENERAL1'] = 'Configuración general 1';
$lang['SETTING_GENERAL2'] = 'Configuración general 2';

$lang['SETTING_NICKNAME'] = 'Apodo WarQuest';
$lang['SETTING_TWITTER'] = 'Cuenta Twitter';
$lang['SETTING_LANGUAGE'] = 'Idioma';
$lang['SETTING_BACKGROUND'] = "Fondo";
$lang['SETTING_SOUND'] = 'Activar sonido (Experimental)';
$lang['SETTING_BOUNTY'] = 'Activar aviso emergente de recompensa.';
$lang['SETTING_RESTORE'] = 'Activar aviso emergente de restaurar & reparar.';
$lang['SETTING_CONDITION'] = 'Activar cartel de información unidad / edificio / rebeliones.';
$lang['SETTING_FORUM_POST'] = 'Activar el último mensaje del foro en la página principal de visión general.';
$lang['SETTING_SORT1'] = 'Activar ver mensaje más reciente en la parte superior en los foros.';
$lang['SETTING_SORT2'] = 'Activar ver el jugador más antiguo con el que ha combatido en la parte superior de la lista de batallas.';
$lang['SETTING_NO_BOT_NEWS'] = 'Desactivar noticias de batalla y notificaciones de los robots.';
$lang['SETTING_ALLIES_IN_BATTLE_LIST'] = 'Habilitar ver aliados, en las listas de enemigos / caza recompensas.';

$lang['PLAYER_LANG_ENGLISH'] = 'Inglés';
$lang['PLAYER_LANG_DUTCH'] = 'Holandés';
$lang['PLAYER_LANG_GERMAN'] = 'Alemán';
$lang['PLAYER_LANG_ITALIAN'] = 'Italiano';

$lang['BACKGROUND_0'] = 'Negro';
$lang['BACKGROUND_1'] = 'Verde militar';
$lang['BACKGROUND_2'] = 'Aurora roja';
$lang['BACKGROUND_3'] = 'Piedras grises';
$lang['BACKGROUND_4'] = 'Circulos rosa';
$lang['BACKGROUND_5'] = 'Seda azul';
$lang['BACKGROUND_6'] = 'Marrón';
$lang['BACKGROUND_7'] = 'Pirata';
$lang['BACKGROUND_8'] = 'Moderno';
$lang['BACKGROUND_9'] = 'Clásico';
$lang['BACKGROUND_10'] = 'Chocolate';
$lang['BACKGROUND_11'] = 'Navidad';
$lang['BACKGROUND_12'] = 'Fuegos artificiales';

$lang['PLAYER_GENERAL_CHANGED'] = 'Configuración general cambiada!';
$lang['PLAYER_NICKNAME_EXIST'] = 'El Apodo ya está en uso!';
$lang['PLAYER_NICKNAME_TO_SHORT'] = 'El Apodo debe tener al menos 4 caracteres!';

$lang['PLAYER_CHANGE_EMAIL'] = 'Configuración email';
$lang['PLAYER_NEW_EMAIL'] = 'Dirección email';
$lang['PLAYER_NOTIFICATION_ALLIANCE'] = 'Notificación de alianzas por email';
$lang['PLAYER_NOTIFICATION_COMMENT'] = 'Notificación de mensajes por email';
$lang['PLAYER_EMAIL_CHANGED'] = 'Configuración de email cambiada';
$lang['PLAYER_EMAIL_EXIST'] = 'La dirección de correo electrónico ya está registrada!';
$lang['PLAYER_EMAIL_INVALID'] = 'Dirección de correo electrónico no válida (formato inválido)!';

$lang['PLAYER_LOGIN_SETTINGS'] = 'Ajustes de acceso';
$lang['PLAYER_USERNAME'] = 'Nombre usuario';
$lang['PLAYER_USERNAME_TO_SHORT'] = 'El nombre de usuario debe tener al menos 4 caracteres!';
$lang['PLAYER_USERNAME_ALREADY_EXIST'] = 'El nombre de usuario ya existe!';
$lang['PLAYER_USERNAME_CHANGED'] = 'Nombre Usuario cambiado. No te olvides de cambiarlo en la aplicación WarQuest Android y versión de Windows, de otro modo el inicio de sesión automático no funcionará!';
$lang['PLAYER_CURRENT_PASSWORD'] = 'Contraseña actual';		
$lang['PLAYER_NEW_PASSWORD'] = 'Nueva contraseña';
$lang['PLAYER_PASSWORD_CHANGED'] = 'Contraseña cambiada. No te olvides de cambiarla en la aplicación WarQuest Android y versión de Windows, de otro modo el inicio de sesión automático no funcionará!';
$lang['PLAYER_PASSWORD_NO_MATCH'] = 'La contraseña actual no coincide!';
$lang['PLAYER_PASSWORD_TO_SHORT'] = 'La nueva contraseña debe tener al menos 6 caracteres de largo!';
$lang['PLAYER_LOGIN_NOTE'] = 'ADVERTENCIA: El inicio de sesión automático sólo funciona cuando se establece el mismo nombre de usuario y contraseñaen en la aplicación WarQuest Android y versión de Windows!'; 

$lang['SETTING_ACCOUNT_RESET_TITLE'] = 'Reset de la cuenta';
$lang['SETTING_YES'] = 'Sí';
$lang['SETTING_SURE'] = 'Reset de la cuenta, está seguro?';
$lang['SETTING_ACCOUNT_RESET'] = 'Activar un reset de cuenta? ';
$lang['SETTING_NO_REVERSE'] = 'Esta acción de restablecimiento (Reset) no se puede deshacer!)';
$lang['SETTING_ACCOUNT_RESET_NOTE'] = 'ADVERTENCIA: Si su cuenta se resetea todos los datos de su cuenta se vuelven a poner al estado de comenzar. Esto significa que TODO se eliminará (unidades, edificios, alianzas, misiones, etc.)'; 
$lang['SETTING_ACCOUNT_RESETTED'] = 'Cuenta de jugador %s ha sido reseteada!';

/*
** ------------------
** MISSION DATA
** ------------------
*/

/* Earth Missions */
$lang['MISSION_GROUP_0'] = 'Entrenamiento';
$lang['MISSION_GROUP_1'] = 'Europe';
$lang['MISSION_GROUP_2'] = 'N-America';
$lang['MISSION_GROUP_3'] = 'S-America';
$lang['MISSION_GROUP_4'] = 'África';
$lang['MISSION_GROUP_5'] = 'N-Asia';
$lang['MISSION_GROUP_6'] = 'S-Asia';
$lang['MISSION_GROUP_7'] = 'E-Asia';
$lang['MISSION_GROUP_8'] = 'Oceanía';
$lang['MISSION_GROUP_9'] = 'Oriente Medio';

/* Moon Missions */
$lang['MISSION_GROUP_10'] = 'Alpha ';
$lang['MISSION_GROUP_11'] = 'Beta';
$lang['MISSION_GROUP_12'] = 'Charlie';
$lang['MISSION_GROUP_13'] = 'Delta';
$lang['MISSION_GROUP_14'] = 'Echo';
$lang['MISSION_GROUP_15'] = 'Foxtrot';
$lang['MISSION_GROUP_16'] = 'Golf';
$lang['MISSION_GROUP_17'] = 'Hotel';
$lang['MISSION_GROUP_18'] = 'India';

/* Mars Missions */
$lang['MISSION_GROUP_20'] = 'Alpaca';
$lang['MISSION_GROUP_21'] = 'Bison';
$lang['MISSION_GROUP_22'] = 'Coyote';
$lang['MISSION_GROUP_23'] = 'Dolphin';
$lang['MISSION_GROUP_24'] = 'Emu';
$lang['MISSION_GROUP_25'] = 'Fox';
$lang['MISSION_GROUP_26'] = 'Giraffe';
$lang['MISSION_GROUP_27'] = 'Heron';
$lang['MISSION_GROUP_28'] = 'Iguana';

/* Asteroid Missions */
$lang['MISSION_GROUP_30'] = 'Alfred';
$lang['MISSION_GROUP_31'] = 'Benjamin';
$lang['MISSION_GROUP_32'] = 'Charles';
$lang['MISSION_GROUP_33'] = 'David';
$lang['MISSION_GROUP_34'] = 'Edward';
$lang['MISSION_GROUP_35'] = 'Frederick';
$lang['MISSION_GROUP_36'] = 'George';
$lang['MISSION_GROUP_37'] = 'Harry';
$lang['MISSION_GROUP_38'] = 'Isaac';

/* Earth */
$lang['MISSION_0'] = 'Misión entrenamiento';
$lang['MISSION_1'] = 'Región Gran Bretaña';
$lang['MISSION_2'] = 'Benelux';
$lang['MISSION_3'] = 'Región Francia';
$lang['MISSION_4'] = 'Europa Central';
$lang['MISSION_5'] = 'Escandinavia';
$lang['MISSION_6'] = 'Europa del este';
$lang['MISSION_7'] = 'Región España';
$lang['MISSION_8'] = 'Europa del sur';

$lang['MISSION_10'] = 'Groenlandia';
$lang['MISSION_11'] = 'Canadá';
$lang['MISSION_12'] = 'Estados Unidos';
$lang['MISSION_13'] = 'Méjico';
$lang['MISSION_14'] = 'Región Guatemala';
$lang['MISSION_15'] = 'Región Nicaragua';
$lang['MISSION_16'] = 'Región Cuba';
$lang['MISSION_17'] = 'Región Caribe';

$lang['MISSION_20'] = 'América Central';
$lang['MISSION_21'] = 'Región Ecuador';
$lang['MISSION_22'] = 'Región Bolivia';
$lang['MISSION_23'] = 'Región Paraguay';
$lang['MISSION_24'] = 'Región Chile';
$lang['MISSION_25'] = 'Región Argentina';
$lang['MISSION_26'] = 'Región Uruguay';
$lang['MISSION_27'] = 'Región Brasil';

$lang['MISSION_30'] = 'Región Argelia';
$lang['MISSION_31'] = 'Región Egipto';
$lang['MISSION_32'] = 'Región África Oeste';
$lang['MISSION_33'] = 'Región África Central';
$lang['MISSION_34'] = 'Región África Este';
$lang['MISSION_35'] = 'Región Mozambique';
$lang['MISSION_36'] = 'Región Zimbabue';
$lang['MISSION_37'] = 'Región África Sur';

$lang['MISSION_40'] = 'Región Rusia';
$lang['MISSION_41'] = 'Región Mongolia';
$lang['MISSION_42'] = 'Región Kazajstán';
$lang['MISSION_43'] = 'Región Uzbekistán';
$lang['MISSION_44'] = 'Región Tayikistán';
$lang['MISSION_45'] = 'Región Turkmenistán';
$lang['MISSION_46'] = 'Región Georgia';
$lang['MISSION_47'] = 'Región Armenia';

$lang['MISSION_50'] = 'Irán';
$lang['MISSION_51'] = 'Afganistán';
$lang['MISSION_52'] = 'Pakistán';
$lang['MISSION_53'] = 'India';
$lang['MISSION_54'] = 'Nepal';
$lang['MISSION_55'] = 'Región Bangladesh';
$lang['MISSION_56'] = 'Región Tailandia';
$lang['MISSION_57'] = 'Región Laos';

$lang['MISSION_60'] = 'China';
$lang['MISSION_61'] = 'Corea del Norte';
$lang['MISSION_62'] = 'Corea del Sur';
$lang['MISSION_63'] = 'Japón';
$lang['MISSION_64'] = 'Taiwan';
$lang['MISSION_65'] = 'Región Camboya';
$lang['MISSION_66'] = 'Región Vietnam';
$lang['MISSION_67'] = 'Malasia';

$lang['MISSION_70'] = 'Indonesia Oeste';
$lang['MISSION_71'] = 'Indonesia Este';
$lang['MISSION_72'] = 'Región Filipinas';
$lang['MISSION_73'] = 'Papua Nueva Guinea';
$lang['MISSION_74'] = 'Timor';
$lang['MISSION_75'] = 'Australia Norte';
$lang['MISSION_76'] = 'Australia Sur';
$lang['MISSION_77'] = 'Nueva Zelanda';

$lang['MISSION_80'] = 'Siria';
$lang['MISSION_81'] = 'Irak';
$lang['MISSION_82'] = 'Arabia Saudi';
$lang['MISSION_83'] = 'Kuwait';
$lang['MISSION_84'] = 'Región Yemen';
$lang['MISSION_85'] = 'Región Oman';
$lang['MISSION_86'] = 'Jordania';
$lang['MISSION_87'] = 'Israel';

/* Moon */
$lang['MISSION_100'] = 'Crater Endymion';
$lang['MISSION_101'] = 'Crater Franklin';
$lang['MISSION_102'] = 'Sinus Honoris';
$lang['MISSION_103'] = 'Mons Fidei';
$lang['MISSION_104'] = 'Crater Blanc';
$lang['MISSION_105'] = 'Crater Fesenkov';
$lang['MISSION_106'] = 'Montes Temporis';
$lang['MISSION_107'] = 'Crater Sr.Ordo';

$lang['MISSION_110'] = 'Crater Agnes';
$lang['MISSION_111'] = 'Mons Andre';
$lang['MISSION_112'] = 'Vallis Bego';
$lang['MISSION_113'] = 'Crater Aristoteles';
$lang['MISSION_114'] = 'Mare Blanc';
$lang['MISSION_115'] = 'Mons Bradley';
$lang['MISSION_116'] = 'Vallis Delisle';
$lang['MISSION_117'] = 'Sinus Dieter';

$lang['MISSION_120'] = 'Mons Dilip';
$lang['MISSION_121'] = 'Mons Esam';
$lang['MISSION_122'] = 'Crater Albategnius';
$lang['MISSION_123'] = 'Mons Gruithuisen Delta';
$lang['MISSION_124'] = 'Mare Gruithuisen Gamma';
$lang['MISSION_125'] = 'Crater Hansteen';
$lang['MISSION_126'] = 'Vallis Darwin';
$lang['MISSION_127'] = 'Mons Huygens';

$lang['MISSION_130'] = 'Sinus La Hire';
$lang['MISSION_131'] = 'Mons Maraldi';
$lang['MISSION_132'] = 'Mons Moro';
$lang['MISSION_133'] = 'Crater Aristarchus';
$lang['MISSION_134'] = 'Mons Pico';
$lang['MISSION_135'] = 'Vallis Piton';
$lang['MISSION_136'] = 'Sinus Rumker';
$lang['MISSION_137'] = 'Mons Usov';

$lang['MISSION_140'] = 'Mons Vinogradov';
$lang['MISSION_141'] = 'Mons Vitruvius';
$lang['MISSION_142'] = 'Mons Wolff';
$lang['MISSION_143'] = 'Montes Agricola';
$lang['MISSION_144'] = 'Montes Alpes';
$lang['MISSION_145'] = 'Crater Apenninus';
$lang['MISSION_146'] = 'Montes Archimedes';
$lang['MISSION_147'] = 'Montes Carpatus';

$lang['MISSION_150'] = 'Montes Caucasus';
$lang['MISSION_151'] = 'Mare Cordillera';
$lang['MISSION_152'] = 'Montes Haemus';
$lang['MISSION_153'] = 'Crater Harbinger';
$lang['MISSION_154'] = 'Sinus Pyrenaeus';
$lang['MISSION_155'] = 'Montes Riphaeus';
$lang['MISSION_156'] = 'Montes Rook';
$lang['MISSION_157'] = 'Mare Secchi';

$lang['MISSION_160'] = 'Montes Spitzbergen';
$lang['MISSION_161'] = 'Mare Taurus';
$lang['MISSION_162'] = 'Sinus Teneriffe';
$lang['MISSION_163'] = 'Montes Harbinger';
$lang['MISSION_164'] = 'Vallis Rheita';
$lang['MISSION_165'] = 'Vallis Baade';
$lang['MISSION_166'] = 'Crater Bohr';
$lang['MISSION_167'] = 'Vallis Palitzsch';

$lang['MISSION_170'] = 'Crater Fecunditatis';
$lang['MISSION_171'] = 'Mare Australe';
$lang['MISSION_172'] = 'Montes Orientale';
$lang['MISSION_173'] = 'Sinus Cognitum';
$lang['MISSION_174'] = 'Mare Crisium';
$lang['MISSION_175'] = 'Mons Spumans';
$lang['MISSION_176'] = 'Montes Tranquillitatis';
$lang['MISSION_177'] = 'Mare Vaporum';

$lang['MISSION_180'] = 'Crater Aestatis';
$lang['MISSION_181'] = 'Lacus Bonitatis';
$lang['MISSION_182'] = 'Montes Felicitatis';
$lang['MISSION_183'] = 'Sinus Luxuriae';
$lang['MISSION_184'] = 'Lacus Oblivionis';
$lang['MISSION_185'] = 'Mons Solitudinis';
$lang['MISSION_186'] = 'Montes Temporis';
$lang['MISSION_187'] = 'Crater Timoris';

/* Mars */
$lang['MISSION_200'] = 'Crater Al-Qahira';
$lang['MISSION_201'] = 'Sinus Ares';
$lang['MISSION_202'] = 'Vallis Auqakuh';
$lang['MISSION_203'] = 'Crater Bahram';
$lang['MISSION_204'] = 'Mare Begonya';
$lang['MISSION_205'] = 'Mons Her Desher';
$lang['MISSION_206'] = 'Sinus Hrad';
$lang['MISSION_207'] = 'Vallis Ordo';

$lang['MISSION_210'] = 'Mons Kasei';
$lang['MISSION_211'] = 'Mare Labou';
$lang['MISSION_212'] = 'Vallis Maadim';
$lang['MISSION_213'] = 'Crater Maja';
$lang['MISSION_214'] = 'Sinus Mamers';
$lang['MISSION_215'] = 'Vallis Mangala';
$lang['MISSION_216'] = 'Crater Marte';
$lang['MISSION_217'] = 'Mare Mawrth';

$lang['MISSION_220'] = 'Crater Nirgal';
$lang['MISSION_221'] = 'Vallis Shalbatana';
$lang['MISSION_222'] = 'Crater Simud';
$lang['MISSION_223'] = 'Sinus Tiu';
$lang['MISSION_224'] = 'Vallis Aloysius';
$lang['MISSION_225'] = 'Crater Ambrosius';
$lang['MISSION_226'] = 'Mare Barnabas';
$lang['MISSION_227'] = 'Mare Constantia';

$lang['MISSION_230'] = 'Vallis Edmondus';
$lang['MISSION_231'] = 'Mare Eustachius';
$lang['MISSION_232'] = 'Crater Georgius';
$lang['MISSION_233'] = 'Sinus Griselda';
$lang['MISSION_234'] = 'Vallis Gualterius';
$lang['MISSION_235'] = 'Crater Homfridus';
$lang['MISSION_236'] = 'Mare Henricus';
$lang['MISSION_237'] = 'Crater Guglielmus';

$lang['MISSION_240'] = 'Mare Janetta';
$lang['MISSION_241'] = 'Vallis Jerominus';
$lang['MISSION_242'] = 'Crater Josephus';
$lang['MISSION_243'] = 'Mare Leonardus';
$lang['MISSION_244'] = 'Sinus Mauritius';
$lang['MISSION_245'] = 'Crater Nicholaus';
$lang['MISSION_246'] = 'Vallis Laurentius';
$lang['MISSION_247'] = 'Mons Octavius';

$lang['MISSION_250'] = 'Crater Misericordia';
$lang['MISSION_251'] = 'Vallis Petronella';
$lang['MISSION_252'] = 'Sinus Sylvanus';
$lang['MISSION_253'] = 'Crater Reginaldus';
$lang['MISSION_254'] = 'Vallis Adeipho';
$lang['MISSION_255'] = 'Sinus Randulphus';
$lang['MISSION_256'] = 'Crater Xpofer';
$lang['MISSION_257'] = 'Mare Aegidius';

$lang['MISSION_260'] = 'Sinus Aeneas';
$lang['MISSION_261'] = 'Crater Philipus';
$lang['MISSION_262'] = 'Sinus Beniaminus';
$lang['MISSION_263'] = 'Vallis Rosamundi';
$lang['MISSION_264'] = 'Mons Peregrinus';
$lang['MISSION_265'] = 'Mare Xtianus';
$lang['MISSION_266'] = 'Vallis Crispianus';
$lang['MISSION_267'] = 'Crater Clementia';

$lang['MISSION_270'] = 'Vallis Elizabeta';
$lang['MISSION_271'] = 'Crater Xtopher';
$lang['MISSION_272'] = 'Mare Placentia';
$lang['MISSION_273'] = 'Sinus Gaufridus';
$lang['MISSION_274'] = 'Crater Stephanus';
$lang['MISSION_275'] = 'Vallis Xpianus	';
$lang['MISSION_276'] = 'Mare Girardus';
$lang['MISSION_277'] = 'Crater Radulphus';

$lang['MISSION_280'] = 'Crater Xtopherus';
$lang['MISSION_281'] = 'Vallis Terentius';
$lang['MISSION_282'] = 'Mons Eamnonn';
$lang['MISSION_283'] = 'Crater Kadisha';
$lang['MISSION_284'] = 'Mare Kachine';
$lang['MISSION_285'] = 'Vallis Oddvar';
$lang['MISSION_286'] = 'Sinus Radborne';
$lang['MISSION_287'] = 'Crater Ebenezer';

/* Asteroid */
$lang['MISSION_300'] = 'Crater Albococcinea';
$lang['MISSION_301'] = 'Sinus argentea';
$lang['MISSION_302'] = 'Vallis Atrococcinea';
$lang['MISSION_303'] = 'Crater Colorans';
$lang['MISSION_304'] = 'Mare Ordo silent';
$lang['MISSION_305'] = 'Mons Brunnea';
$lang['MISSION_306'] = 'Sinus Chlorantha';
$lang['MISSION_307'] = 'Vallis Erythrocarpa';

$lang['MISSION_310'] = 'Mons Ferruginea';
$lang['MISSION_311'] = 'Mare Colorans';
$lang['MISSION_312'] = 'Vallis Aurea';
$lang['MISSION_313'] = 'Crater Atrovirens';
$lang['MISSION_314'] = 'Sinus lutescens';
$lang['MISSION_315'] = 'Vallis Maculata';
$lang['MISSION_316'] = 'Crater Nigrescens';
$lang['MISSION_317'] = 'Mare Punicea';

$lang['MISSION_320'] = 'Crater Rosea';
$lang['MISSION_321'] = 'Vallis Rubiginosa';
$lang['MISSION_322'] = 'Crater Tinctoria';
$lang['MISSION_323'] = 'Sinus Sulphurea';
$lang['MISSION_324'] = 'Vallis Sempervirens';
$lang['MISSION_325'] = 'Crater Rubicunda';
$lang['MISSION_326'] = 'Mare Variegata';
$lang['MISSION_327'] = 'Mare Versicolor';

$lang['MISSION_330'] = 'Vallis Vinosa';
$lang['MISSION_331'] = 'Mare Viridescens';
$lang['MISSION_332'] = 'Crater Citrodora';
$lang['MISSION_333'] = 'Sinus Foetidissima';
$lang['MISSION_334'] = 'Vallis Gravaeolens';
$lang['MISSION_335'] = 'Crater Odorata';
$lang['MISSION_336'] = 'Mare Suaveolens';
$lang['MISSION_337'] = 'Crater Ursina';

$lang['MISSION_340'] = 'Mare Amabile';
$lang['MISSION_341'] = 'Vallis Praecox ';
$lang['MISSION_342'] = 'Crater Bella';
$lang['MISSION_343'] = 'Mare Amoena';
$lang['MISSION_344'] = 'Sinus Gracilis';
$lang['MISSION_345'] = 'Crater Formosa';
$lang['MISSION_346'] = 'Vallis Fragilis';
$lang['MISSION_347'] = 'Mons Foeniculaceus';

$lang['MISSION_350'] = 'Crater Blanda';
$lang['MISSION_351'] = 'Vallis Elegantissima';
$lang['MISSION_352'] = 'Sinus Imperialis';
$lang['MISSION_353'] = 'Crater Splendens';
$lang['MISSION_354'] = 'Vallis Superba';
$lang['MISSION_355'] = 'Sinus Magnifica';
$lang['MISSION_356'] = 'Crater Campestris';
$lang['MISSION_357'] = 'Mare Collina';

$lang['MISSION_360'] = 'Sinus Insignis';
$lang['MISSION_361'] = 'Crater Peregrina';
$lang['MISSION_362'] = 'Sinus Mutabilis';
$lang['MISSION_363'] = 'Vallis Spectabilis';
$lang['MISSION_364'] = 'Mons Thermalis';
$lang['MISSION_365'] = 'Mare Gracilis';
$lang['MISSION_366'] = 'Vallis Sinensis';
$lang['MISSION_367'] = 'Crater Pratensis';

$lang['MISSION_370'] = 'Vallis Mirabilis';
$lang['MISSION_371'] = 'Crater Umbrosa ';
$lang['MISSION_372'] = 'Mare Paradoxas';
$lang['MISSION_373'] = 'Sinus Pulchella';
$lang['MISSION_374'] = 'Crater Floribunda';
$lang['MISSION_375'] = 'Vallis Microphylla';
$lang['MISSION_376'] = 'Mare Parviflora';
$lang['MISSION_377'] = 'Crater Venusta';

$lang['MISSION_380'] = 'Crater Monstrosus';
$lang['MISSION_381'] = 'Vallis Septentrionalis';
$lang['MISSION_382'] = 'Mons Occidentalis';
$lang['MISSION_383'] = 'Crater Pulcherrima';
$lang['MISSION_384'] = 'Mare Spectabilis';
$lang['MISSION_385'] = 'Vallis Regia';
$lang['MISSION_386'] = 'Sinus Macrantha';
$lang['MISSION_387'] = 'Crater Caespitosa';

/*
** ------------------
** MISSION PAGE
** ------------------
*/

$lang['MISSION_TITLE'] = 'MISIONES';
$lang['MISSION_NOTE'] = 'Nota: Juegue las misiones para ganar dinero, puntos de experiencia y poder alcanzar el siguiente nivel. Cuando una misión está 100% completada usted gana dinero doble. Si ha completado el 100% del continente %s , el ingreso por hora se incrementará con %s dólares.';

$lang['MISSION_ALLIANCE_SIZE'] = 'número aliados';
$lang['MISSION_GAIN'] = 'Ventajas';
$lang['MISSION_PART'] = 'Parte';
$lang['MISSION_REQUIRED'] = 'Requerido';
$lang['MISSION_UNLOCK'] = 'Desbloqueado en nivel %s';
$lang['MISSION_CHANCE_LOOT'] = 'Posibilidad de botín';

$lang['MISSION_YOU_USED'] = 'Utilizaste';
$lang['MISSION_YOU_GAIN'] = 'Conseguiste';
$lang['MISSION_DOLLAR_AND'] = ' dólares y ';
$lang['MISSION_ABORTED'] = 'Misión abortada!';
$lang['MISSION_NO_ENERGY'] = 'Usted no tiene la energía suficiente para completar la misión. Espere unos minutos para que su energía se recupere.';
$lang['MISSION_LOW_ALLIANCE'] = 'Tú número de aliados es demasiado reducido para jugar esta misión.';
$lang['MISSION_MISSING_UNITS'] = 'Usted no tiene la cantidad correcta de unidades para completar la misión. Unidad(es) que necesitas: ';
$lang['MISSION_MISSING_UNITS_PRICE'] = 'El precio total de compra de unidad(es) es %s dólares. El coste por hora se subirá %s dólares.';
$lang['MISSION_UNITS_LOST'] = 'Durante la misión ha perdido la unidad(es) siguiente(s)';
$lang['MISSION_LOOT_WON'] = 'Ha ganado el botín siguiente';
$lang['MISSION_UNLOCKED'] = 'Ahora hay que continuar con la batalla de entrenamiento.';

$lang['MISSION_CONTINTENT_READY1'] = 'Brillante! Usted ha completado la parte %s de %s del continente %s ! ';
$lang['MISSION_CONTINTENT_READY2'] = 'Ha recibido %s puntos extra de Habilidades. ';
$lang['MISSION_CONTINTENT_READY3'] = 'Ha terminado todas las partes. Continúe con el siguiente continente!';
$lang['MISSION_CONTINTENT_READY4'] = 'Continuar con la parte %s del continente!';
$lang['MISSION_COMPLETE_TEXT'] = 'Usted conquistó los siguientes continentes hasta ahora!';

$lang['MISSION_REBEL'] = 'Rebelion';

$lang['MISSION_COMPLETE_PLANET_0'] = 'Excelente! Has completado todas las misiones de la Tierra. Has recibido 100 millones de dólares de bonificación.';
$lang['MISSION_COMPLETE_PLANET_1'] = 'Excelente! Has completado todas las misiones a la Luna. Has recibido 500 millones de dólares de bonificación.';
$lang['MISSION_COMPLETE_PLANET_2'] = 'Excelente! Has completado todas las misiones de Marte. Has recibido 999 mil millones de dólares de bonificación.';
$lang['MISSION_COMPLETE_PLANET_3'] = 'Excelente! Has completado todas las misiones de asteroides. Has recibido 50 puntos de comercio como bonificación.';

/*
** ------------------
** BATTLE PAGE
** ------------------
*/

$lang['BATTLE_TITLE'] = 'BATALLA';
$lang['BATTLE_GENERAL_TITLE'] = 'Batalla';
$lang['BATTLE_BOUNTY_TITLE'] = 'Caza recompensas';

$lang['BATTLE_LOST'] = 'Tu %s atacó %s. Has perdido la batalla, sufriendo %s de daños y causando %s a %s.';
$lang['BATTLE_WON'] = 'Tu %s atacó %s. Ganaste la batalla, sufriendo %s de daños y causando %s a %s. Capturaste %s dólares y acumulaste %s puntos de experiencia.';
$lang['BATTLE_DEFENDER_HEALTH_LOW'] = '%s se rinde temporalmente porque su salud es demasiado baja!';
$lang['BATTLE_ATTACKER_HEALTH_LOW'] = 'Su salud es demasiado baja para combatir!. Visita el hospital para la recuperación inmediata o espera tiempo para la recuperación de salud.';
$lang['BATTLE_AMMO_LOW'] = 'Se ha quedado sin munición! Espere unos minutos para que su munición se recargue o utilice puntos de habilidad para mejorar la habilidad de munición.';
$lang['BATTLE_UNITS_LOST'] = 'Durante la batalla perdió la(s) unidad(es) siguiente(s):';
$lang['BATTLE_BUILDINGS_LOST'] = 'Durante la batalla perdió el edificio(s) siguiente(s):';
$lang['BATTLE_DEFENSE_FORCE'] = '%s %s defensa %s (%s fuerza de defensa):'; 
$lang['BATTLE_DEFENSE_BASE'] = '%s defensas de la base:'; 
$lang['BATTLE_ATTACK_FORCE'] = 'Tu %s ataque %s (%s fuerza de ataque)';
$lang['BATTLE_MORE'] = 'más';
$lang['BATTLE_NO_PLAYER_AVAILABLE'] = 'En estos momentos ningún jugador(es) están disponibles para combatir.';
$lang['BATTLE_UNLOCKED'] = 'Opción Batalla se desbloquea en el nivel 1.<br/>Complete la misión de entrenamiento primero.';
$lang['BATTLE_BOUNTY_UNLOCKED'] = 'La opción Caza Recompensas se desbloquea en el nivel %s.';
$lang['BATTLE_ALLY_NO_ATTACK'] = '<b>%s</b> es un aliado. No puede atacar a sus aliados.';
$lang['BATTLE_SURRENDER'] = 'Rendición temporal';

$lang['BATTLE_NOTE1'] = 'Nota: Luche con otros jugadores para ganar dinero y puntos de experiencia y para alcanzar el siguiente nivel.';
$lang['BATTLE_NOTE2'] = 'Note: Cace recompensas sobre otros jugadores para recoger el botín y ganar puntos de experiencia para alcanzar el siguiente nivel.';

$lang['BATTLE_FORCE_TYPE'] = 'Fuerza:';
$lang['BATTLE_ENEMIES'] = 'Enemigos';
$lang['BATTLE_BOUNTY'] = 'Caza-Recompensas';
$lang['BATTLE_NO_BOUNTY_PLAYERS'] = 'Por el momento no hay ningún jugador(es) con recompensas disponibles para combatir.';
$lang['BATTLE_BOUNTY_BONUS'] = 'Recibida bonificación de recompensa adicional de %s dólares.'; 
$lang['BATTLE_HOSPITAL_BONUS'] = '%s se rinde temporalmente. Usted recibe un bonus de %s dólares!'; 
$lang['BATTLE_BOUNTY_LOST'] = 'Fuiste atacado por %s de %s.PERDISTE. Perdiendo %s dólares, sufriendo %s de daños y perdiendo %s puntos de experiencia.';
$lang['BATTLE_BOUNTY_CONFIRM'] = 'Quiere ofrecer una recompensa de %s dólares?';

$lang['BATTLE_CEASE_FIRE_PERIOD'] = 'El Periodo de Alto el Fuego está activo! No es posible la lucha. %s';
$lang['BATTLE_AND'] = 'and';
$lang['BATTLE_REBEL_UPDATE1'] = 'Bien hecho, ha iniciado la rebelión de %s en la región(es) %s. Debajo puede ver la situación actual.';
$lang['BATTLE_REBEL_UPDATE2'] = 'Bien hecho, ha aumentado las posibilidades de rebelión para %s al %s%.';
$lang['BATTLE_REBEL_UPDATE3'] = 'Es una pena, ninguna región está disponible para iniciar una rebelión!';

$lang['BATTLE_NO_BOUNTY_MONEY'] = 'No dispone de %s de dólares para establecer una recompensa por la cabeza de %s .';
$lang['BATTLE_BOUNTY_SET'] = 'Has ofrecido %s dólares por la cabeza de %s . Cuando %s sea derrotado, perderá %s puntos de experiencia.'; 

$lang['BATTLE_MOON_UNLOCKED'] = 'Las batallas en la Luna se desbloquean en el nivel 100.';
$lang['BATTLE_MARS_UNLOCKED'] = 'Las batallas en Marte se desbloquean en el nivel 150.';
$lang['BATTLE_ASTERIOD_UNLOCKED'] = 'Las batallas en el Asteroide se desbloquean en el nivel 200.';

$lang['BATTLE_RANGE'] = 'Los jugadores desde el nivel %s hasta el %s están a tu alcance en Batalla.';
/*
** ------------------
** UNIT DATA
** ------------------
*/

/* Earth */
$lang['UNIT_GROUP_0']  = 'Ejército';
$lang['UNIT_GROUP_2']  = 'Caballería';
$lang['UNIT_GROUP_3']  = 'Armada';
$lang['UNIT_GROUP_4']  = 'Fuerza aérea';
$lang['UNIT_GROUP_5']  = 'Ciudadanos';
$lang['UNIT_GROUP_6']  = 'Inteligencia';

/* Moon */
$lang['UNIT_GROUP_7']  = 'Guerreros';
$lang['UNIT_GROUP_8']  = 'Robots';
$lang['UNIT_GROUP_9']  = 'Naves';
$lang['UNIT_GROUP_10'] = 'Ciudadanos';
$lang['UNIT_GROUP_11'] = 'Ejército';
$lang['UNIT_GROUP_12'] = 'Exploradores';

/* Mars */
$lang['UNIT_GROUP_13']  = 'Robots';
$lang['UNIT_GROUP_14']  = 'Guerreros';
$lang['UNIT_GROUP_15']  = 'Naves';
$lang['UNIT_GROUP_16']  = 'Explorers';
$lang['UNIT_GROUP_17'] 	= 'Ciudadanos';
$lang['UNIT_GROUP_18'] 	= 'Ejército';

/* Asteroid */
$lang['UNIT_GROUP_19']  = 'Robots';
$lang['UNIT_GROUP_20']  = 'Guerreros';
$lang['UNIT_GROUP_21']  = 'Naves-espaciales';
$lang['UNIT_GROUP_22']  = 'Exploradores';
$lang['UNIT_GROUP_23'] 	= 'Ciudadanos';
$lang['UNIT_GROUP_24'] 	= 'Ejército';

/* Calvary (Earth) - Group 2 */
$lang['UNIT_1'] = 'Mini-artillero';
$lang['UNIT_101'] = 'Vehículo militar';
$lang['UNIT_102'] = 'Humvee';
$lang['UNIT_103'] = 'Camión';
$lang['UNIT_104'] = 'Artillería ligera';
$lang['UNIT_105'] = 'Transporte de caballería ligero';
$lang['UNIT_106'] = 'MGM-51 Shillelagh';
$lang['UNIT_107'] = 'Transporte de caballería';
$lang['UNIT_108'] = 'Vehículo de asalto';
$lang['UNIT_109'] = 'Lanzacohetes SSM';
$lang['UNIT_110'] = 'Aerodeslizador ligero';
$lang['UNIT_111'] = 'Tanque M1 Abrams';
$lang['UNIT_112'] = 'Transporte blindado';
$lang['UNIT_113'] = 'Vehículo Antiemboscadas';
$lang['UNIT_114'] = 'Lanzacohetes Pesado';
$lang['UNIT_115'] = 'Tanque Leopard 1A1';
$lang['UNIT_116'] = 'Vehículo HG-544';
$lang['UNIT_117'] = 'Transporte de orugas';
$lang['UNIT_118'] = 'Tanque ligero';
$lang['UNIT_119'] = 'Tanque Hellfire';
$lang['UNIT_120'] = 'Tanque Pesado';
$lang['UNIT_121'] = 'Artillería autotransportada';
$lang['UNIT_122'] = 'Artillería autotransportada pesada';
$lang['UNIT_123'] = 'Tanque Chaparral';
$lang['UNIT_124'] = 'Artillería M198 Howitzer';
$lang['UNIT_125'] = 'Artillería Pesada';
$lang['UNIT_126'] = 'Lanza misiles';
$lang['UNIT_127'] = 'Antiaéreo móvil';

/* Navy (Earth) - Group 3 */
$lang['UNIT_201'] = 'Lancha';
$lang['UNIT_202'] = 'Transporte';
$lang['UNIT_203'] = 'Fragata';
$lang['UNIT_204'] = 'Buque cisterna';
$lang['UNIT_205'] = 'Destructor ligero';
$lang['UNIT_206'] = 'M80 Stiletto';
$lang['UNIT_207'] = 'Submarino';
$lang['UNIT_208'] = 'Porta helicópteros';
$lang['UNIT_209'] = 'Acorazado';
$lang['UNIT_210'] = 'Buque Houbei Missile';
$lang['UNIT_211'] = 'Fragata Horizon';
$lang['UNIT_212'] = 'Fragata Type 13';
$lang['UNIT_213'] = 'Destructor';
$lang['UNIT_214'] = 'Submarino Scorpene';
$lang['UNIT_215'] = 'Destructor DDG 1000';
$lang['UNIT_216'] = 'Acorazado Elite';
$lang['UNIT_217'] = 'Destructor SPY-1D';
$lang['UNIT_218'] = 'Sea Fighter';
$lang['UNIT_219'] = 'HSV-2 Swift';
$lang['UNIT_220'] = 'Crucero lanzamisiles';
$lang['UNIT_221'] = 'UXV Combatant';
$lang['UNIT_222'] = 'Buque caza submarinos';
$lang['UNIT_223'] = 'Buque Kanimbla AT';
$lang['UNIT_224'] = 'Portaviones';
$lang['UNIT_225'] = 'Buque de desembarco';
$lang['UNIT_226'] = 'Fragata Type 23';
$lang['UNIT_227'] = 'Submarino Ohio';
$lang['UNIT_228'] = 'Crucero Nuclear';

/* Airforce (Earth) - Group 4 */
$lang['UNIT_301'] = 'Cessna 172';
$lang['UNIT_302'] = 'Avión de transporte C-17';
$lang['UNIT_303'] = 'Cañonero V-22A Osprey';
$lang['UNIT_304'] = 'Harrier AV-8B';
$lang['UNIT_305'] = 'Helicóptero Comanche';
$lang['UNIT_306'] = 'Helicóptero Havoc';
$lang['UNIT_307'] = 'Saab JA37 Viggen';
$lang['UNIT_308'] = 'SR-71 Blackbird';
$lang['UNIT_309'] = 'Helicóptero Apache';
$lang['UNIT_310'] = 'Bombardero B-2 Spirit';
$lang['UNIT_311'] = 'F-18 Super Hornet';
$lang['UNIT_313'] = 'F-15 Silent Eagle';
$lang['UNIT_314'] = 'B-1 Lancer';
$lang['UNIT_316'] = 'F3 Interceptor';
$lang['UNIT_318'] = 'F-16 Falcon';
$lang['UNIT_319'] = 'PAK-FA Fighter';
$lang['UNIT_320'] = 'F-117 Nighthawk';
$lang['UNIT_321'] = 'Bombardero Boeing NGB';
$lang['UNIT_322'] = 'F-14 Tomcat';
$lang['UNIT_323'] = 'F-35 Lightning II';
$lang['UNIT_324'] = 'B-52 Stratofortress';
$lang['UNIT_325'] = 'F-22 Raptor';
$lang['UNIT_326'] = 'Misil Trident II';

/* Citizens (Earth) - Group 5 */
$lang['UNIT_401'] = 'Ingeniero de Construcción';
$lang['UNIT_402'] = 'Ingeniero Mecánico';
$lang['UNIT_403'] = 'Ingeniero de laboratorio';
$lang['UNIT_404'] = 'Gerente';
$lang['UNIT_405'] = 'Doctor';
$lang['UNIT_406'] = 'Cocinero';
$lang['UNIT_407'] = 'Guardia de seguridad';

/* Intel (Earth) - Group 6 */
$lang['UNIT_501'] = 'Cámara de vigilancia';
$lang['UNIT_502'] = 'Inteligencia de la Marina';
$lang['UNIT_503'] = 'Miniavión teledirigido';
$lang['UNIT_504'] = 'Robot espía G343';
$lang['UNIT_505'] = 'Vehículo A3 Crusader';
$lang['UNIT_506'] = 'Barco pesquero espía';
$lang['UNIT_507'] = 'Hawk Eye';
$lang['UNIT_508'] = 'UK-80 AWACS';
$lang['UNIT_509'] = 'Buque AS-102 Stealth';
$lang['UNIT_510'] = 'US-101 Predator';
$lang['UNIT_511'] = 'Avión no tripulado Heron';
$lang['UNIT_512'] = 'Satélite HG101';


/* Warriors (Moon) - Group 7 */
$lang['UNIT_700'] = 'Ahiga I';
$lang['UNIT_701'] = 'Aindrias II';
$lang['UNIT_702'] = 'Aloisius III';
$lang['UNIT_703'] = 'Aloysius IV';
$lang['UNIT_704'] = 'Alvar V';
$lang['UNIT_705'] = 'Aindrias VI';
$lang['UNIT_706'] = 'Ordonez VII';
$lang['UNIT_707'] = 'Catigernus VIII';
$lang['UNIT_708'] = 'Catutigernos IX';
$lang['UNIT_709'] = 'Cedric X';
$lang['UNIT_710'] = 'Cheveyo XI';

/* Drones (Moon) - Group 8 */
$lang['UNIT_800'] = 'Basic Rover I';
$lang['UNIT_801'] = 'Transporte lunar II';
$lang['UNIT_802'] = 'Explorador lunar III';
$lang['UNIT_803'] = 'Moon Havostar IV';
$lang['UNIT_804'] = 'Laboratorio móvil V';
$lang['UNIT_805'] = 'Transporte VI';
$lang['UNIT_805'] = 'Grúa espacial VII';
$lang['UNIT_806'] = 'Buggy lunar VIII';
$lang['UNIT_807'] = 'Transportador de combustible IX';
$lang['UNIT_808'] = 'Explorador de combustible X';
$lang['UNIT_809'] = 'Explorador lunar XI';
$lang['UNIT_810'] = 'Transporte XII';

/* Spacecrafts (Moon) - Group 9 */
$lang['UNIT_900'] = 'Crucero lunar';
$lang['UNIT_901'] = 'Halcón Milenario';
$lang['UNIT_902'] = 'Ebon Hawk';
$lang['UNIT_903'] = 'Transporte Robot';
$lang['UNIT_904'] = 'Slave I';
$lang['UNIT_905'] = 'Nave de asalto';
$lang['UNIT_906'] = 'Corbeta Corellian';
$lang['UNIT_907'] = 'War Hawk Shadow';
$lang['UNIT_908'] = 'Nave solar';
$lang['UNIT_909'] = 'Nave Imperial';
$lang['UNIT_910'] = 'Lanzadera Theta-Class';
$lang['UNIT_911'] = 'Crucero de transporte';
$lang['UNIT_912'] = 'Sith Infiltrator';
$lang['UNIT_913'] = 'Nave de desembarco Imperial';
$lang['UNIT_914'] = 'Star Skiff II';
$lang['UNIT_915'] = 'Destructor estelar';
$lang['UNIT_916'] = 'Buque insignia';

/* Citizens (Moon) - Group 10 */
$lang['UNIT_1000'] = 'Astronauta';
$lang['UNIT_1001'] = 'Mujer';
$lang['UNIT_1002'] = 'Hombre';

/* Explorers (Moon) - Group 12 */
$lang['UNIT_1200'] = 'Satélite de exploración';
$lang['UNIT_1201'] = 'Nave de exploración';
$lang['UNIT_1202'] = 'Radar de corto alcance';
$lang['UNIT_1203'] = 'Explorador de Espacio Profundo';
$lang['UNIT_1204'] = 'Explorador de planetas';
$lang['UNIT_1205'] = 'Elevador Espacial';
$lang['UNIT_1206'] = 'Astronauta explorador';
$lang['UNIT_1207'] = 'Radar de largo alcance';
$lang['UNIT_1208'] = 'Estación del espacio profundo';
$lang['UNIT_1209'] = 'Explorador Velocidad Luz';
$lang['UNIT_1210'] = 'Destructor Planetario';
$lang['UNIT_1211'] = 'Explorador Galáctico';


/* Drones (Mars) - Group 13 */
$lang['UNIT_1300'] = 'Loyce I';
$lang['UNIT_1301'] = 'Labhaoise II';
$lang['UNIT_1302'] = 'Ordonez III';
$lang['UNIT_1303'] = 'Kiaskari VI';
$lang['UNIT_1304'] = 'Khalon V';
$lang['UNIT_1305'] = 'Hida VI';
$lang['UNIT_1306'] = 'Irapeke VII';
$lang['UNIT_1307'] = 'Heriberto VIII';
$lang['UNIT_1308'] = 'Kerbasi IX';
$lang['UNIT_1309'] = 'Karna X';

/* Warriors (Mars) - Group 14 */
$lang['UNIT_1400'] = 'Gervaso I';
$lang['UNIT_1401'] = 'Galtero II';
$lang['UNIT_1402'] = 'Gunther III';
$lang['UNIT_1403'] = 'Donnachadh VI';
$lang['UNIT_1404'] = 'Duncan V';
$lang['UNIT_1405'] = 'Eskiminzin VI';
$lang['UNIT_1406'] = 'Fenyang VII';
$lang['UNIT_1407'] = 'Finnegan VIII';
$lang['UNIT_1408'] = 'Clodovea IX';
$lang['UNIT_1409'] = 'Eferhilda X';

/* Spacecrafts (Mars) - Group 15 */
$lang['UNIT_1500'] = 'Mars Cruiser I';
$lang['UNIT_1501'] = 'Cocon II';
$lang['UNIT_1502'] = 'Hawk Eye III';
$lang['UNIT_1503'] = 'Ariane IV';
$lang['UNIT_1504'] = 'Gyro V';
$lang['UNIT_1505'] = 'Miner VI';
$lang['UNIT_1506'] = 'Jannus VII';
$lang['UNIT_1507'] = 'Tango VIII';
$lang['UNIT_1508'] = 'Rader IX';
$lang['UNIT_1509'] = 'Eloy  X';

/* Explorers (Mars) - Group 16 */
$lang['UNIT_1600'] = 'Cadabyr I';
$lang['UNIT_1601'] = 'Chadwick II';
$lang['UNIT_1602'] = 'Calhoun III';
$lang['UNIT_1603'] = 'Cheveyo IV';
$lang['UNIT_1604'] = 'Clancy V';
$lang['UNIT_1605'] = 'Clodovea VI';
$lang['UNIT_1606'] = 'Cochise VII';
$lang['UNIT_1607'] = 'Czarine VIII';
$lang['UNIT_1608'] = 'Caddawyc IX';
$lang['UNIT_1609'] = 'Chlodwig X';

/* Citizens (Mars) - Group 17 */
$lang['UNIT_1700'] = 'Astronauta';
$lang['UNIT_1701'] = 'Mujer';
$lang['UNIT_1702'] = 'Hombre';


/* Warriors (Asteroid) - Group 19 */
$lang['UNIT_1900'] = 'Swify I';
$lang['UNIT_1901'] = 'Euhm II';
$lang['UNIT_1902'] = 'Mirageman III';
$lang['UNIT_1903'] = 'Ordonez IV';
$lang['UNIT_1904'] = 'Maelsius V';
$lang['UNIT_1905'] = 'Suldan VI';
$lang['UNIT_1906'] = 'Jonesy VII';
$lang['UNIT_1907'] = 'Pendejo VIII';
$lang['UNIT_1908'] = 'Vorpal IX';
$lang['UNIT_1909'] = 'Iyona X';

/* Warriors (Asteroid) - Group 20 */
$lang['UNIT_2000'] = 'Grandmaster I';
$lang['UNIT_2001'] = 'Courage II';
$lang['UNIT_2002'] = 'Hero III';
$lang['UNIT_2003'] = 'Pious IV';
$lang['UNIT_2004'] = 'Stalwart V';
$lang['UNIT_2005'] = 'Bombadil VI';
$lang['UNIT_2006'] = 'Happyelf VII';
$lang['UNIT_2007'] = 'Rainbow VIII';
$lang['UNIT_2008'] = 'MerryLad IX';
$lang['UNIT_2009'] = 'Drenar X';

/* Spacecrafts (Asteroid) - Group 21 */
$lang['UNIT_2100'] = 'Halvilion I';
$lang['UNIT_2101'] = 'Menelaus II';
$lang['UNIT_2102'] = 'Ultimatum III';
$lang['UNIT_2103'] = 'Erudur IV';
$lang['UNIT_2104'] = 'Banbelion V';
$lang['UNIT_2105'] = 'Nimtharadon VI';
$lang['UNIT_2106'] = 'Voronthil VII';
$lang['UNIT_2107'] = 'Anion VIII';
$lang['UNIT_2108'] = 'Partharaon IX';
$lang['UNIT_2109'] = 'Erudil X';

/* Explorers (Asteroid) - Group 22 */
$lang['UNIT_2200'] = 'Girlyman I';
$lang['UNIT_2201'] = 'Wuss II';
$lang['UNIT_2202'] = 'Sissy III';
$lang['UNIT_2203'] = 'Tauren IV';
$lang['UNIT_2204'] = 'Hykon V';
$lang['UNIT_2205'] = 'Talenx VI';
$lang['UNIT_2206'] = 'DDazra VII';
$lang['UNIT_2207'] = 'Hexa VIII';
$lang['UNIT_2208'] = 'Marest IX';
$lang['UNIT_2209'] = 'Rawrgrable X';

/* Citizens (Asteroid) - Group 23 */
$lang['UNIT_2300'] = 'Astronauta';
$lang['UNIT_2301'] = 'Mujer';
$lang['UNIT_2302'] = 'Hombre';

/*
** ------------------
** UNIT PAGE
** ------------------
*/

$lang['UNIT_TITLE'] = 'UNIDADES';

$lang['UNIT_NOTE_1'] = 'Nota: Compre unidades de soldados para realizar las misiones.';
$lang['UNIT_NOTE_2'] = 'Nota: Compre unidades de Caballería para mejorar su fuerza terrestre. Combate, vence y roba el dinero de tu oponente en sus cuentas de efectivo.';
$lang['UNIT_NOTE_3'] = 'Nota: Compre unidades de la Armada para mejorar su fuerza naval. Combate, vence y roba el dinero de tu oponente en sus cuentas de efectivo.';
$lang['UNIT_NOTE_4'] = 'Nota: Compre unidades aéreas para mejorar su fuerza aérea. Combate, vence y roba el dinero de tu oponente en sus cuentas de dinero en efectivo.';
$lang['UNIT_NOTE_6'] = 'Nota: Compre unidades de Inteligencia para mejorar su fuerza de espionaje. Combate, vence e inicia rebeliones en las regiones de la Tierra además de robar el dinero de tu oponente en las cuentas bancarias de Trasquera o SwissCore.';

$lang['UNIT_NOTE_8'] = 'Nota: compre unidades Robot de la Luna para mejorar su fuerza robots. Combate, vence y roba el dinero de tu oponente en sus cuentas de efectivo.';
$lang['UNIT_NOTE_7'] = 'Nota: Compre unidades de Guerreros de la Luna para mejorar su fuerza de guerreros. Combate, vence y roba el dinero de tu oponente en sus cuentas de efectivo.';
$lang['UNIT_NOTE_9'] = 'Nota: Compre unidades de Naves espaciales de la Luna para mejorar su fuerza aeroespacial. Combate, vence y roba el dinero de tu oponente en sus cuentas de efectivo.';
$lang['UNIT_NOTE_12'] = 'Nota: Compre unidades de Exploradores para mejorar su fuerza de exploración. Combate, vence e inicia rebeliones en la Luna además de robar el dinero de tu oponente en las cuentas bancarias de Trasquera o SwissCore.';

$lang['UNIT_NOTE_13'] = 'Nota: compre unidades Robot de Marte para mejorar su fuerza robots. Combate, vence y roba el dinero de tu oponente de sus cuentas de efectivo.';
$lang['UNIT_NOTE_14'] = 'Nota: Compre unidades de Guerreros de Marte para mejorar su fuerza de guerreros. Combate, vence y roba el dinero de tu oponente de sus cuentas de efectivo.';
$lang['UNIT_NOTE_15'] = 'Nota: Compre unidades de Naves espaciales de Marte para mejorar su fuerza aeroespacial. Combate, vence y roba el dinero de tu oponente de sus cuentas de efectivo.';
$lang['UNIT_NOTE_16'] = 'Nota: Compre unidades de Exploradores para mejorar su fuerza de exploración. Combate, vence e inicia rebeliones en la Luna además de robar el dinero de tu oponente en las cuentas bancarias de Trasquera o SwissCore.';

$lang['UNIT_NOTE_19'] = 'Nota: compre unidades Robot para el Asteroide y mejore su fuerza robots. Combate, vence y roba el dinero de tu oponente de sus cuentas de efectivo.';
$lang['UNIT_NOTE_20'] = 'Nota: Compre unidades de Guerreros para el Asteroide y mejore su fuerza de guerreros. Combate, vence y roba el dinero de tu oponente de sus cuentas de efectivo.';
$lang['UNIT_NOTE_21'] = 'Nota: Compre unidades de Naves espaciales para el Asteroide y mejore su fuerza aeroespacial. Combate, vence y roba el dinero de tu oponente de sus cuentas de efectivo.';
$lang['UNIT_NOTE_22'] = 'Nota: Compre unidades de Exploradores para el Asteroide y mejore su fuerza de exploración. Combate, vence e inicia rebeliones en la Luna además de robar el dinero de tu oponente en las cuentas bancarias de Trasquera o SwissCore.';

$lang['UNIT_DISBAND'] = 'Ha licenciado %s %s por %s. Actualmente %s alistados.';
$lang['UNIT_DISBAND_FAILED'] = 'No dispone de %s %s. Actualmente %s alistados.';

$lang['UNIT_DEPLOY'] = 'Ha reclutado %s %s por %s. Ahora %s alistados.';
$lang['UNIT_NO_UPKEEP'] = 'No hay suficientes ingresos por hora para financiar %s %s.';
$lang['UNIT_NO_MONEY'] = 'No tiene suficiente dinero para comprar %s %s por %s.';
$lang['UNIT_MAX'] = 'No más de %s %s(s) permitidos!';

/*
** ------------------
** BUILDING DATA
** ------------------
*/

/* Earth Buildings */
$lang['BUILDING_GROUP_1']  = 'Ingreso';
$lang['BUILDING_GROUP_2']  = 'Defensa';
$lang['BUILDING_GROUP_3']  = 'Energía';
$lang['BUILDING_GROUP_4']  = 'Descuento';
$lang['BUILDING_GROUP_5']  = 'Mantenimiento';

/* Moon Buildings */
$lang['BUILDING_GROUP_6']  = 'Ingreso';
$lang['BUILDING_GROUP_7']  = 'Defensa';
$lang['BUILDING_GROUP_8']  = 'Energía';
$lang['BUILDING_GROUP_9']  = 'Descuento';
$lang['BUILDING_GROUP_10'] = 'Mantenimiento';

/* Mars Buildings */
$lang['BUILDING_GROUP_11'] = 'Ingreso';
$lang['BUILDING_GROUP_12'] = 'Defensa';
$lang['BUILDING_GROUP_13'] = 'Energía';
$lang['BUILDING_GROUP_14'] = 'Descuento';
$lang['BUILDING_GROUP_15'] = 'Mantenimiento';

/* Asteroid Buildings */
$lang['BUILDING_GROUP_16'] = 'Ingreso';
$lang['BUILDING_GROUP_17'] = 'Defensa';
$lang['BUILDING_GROUP_18'] = 'Energía';
$lang['BUILDING_GROUP_19'] = 'Descuento';
$lang['BUILDING_GROUP_20'] = 'Mantenimiento';

/* Income (Earth) - Group 1 */
$lang['BUILDING_1']  = 'Almacén de suministros';
$lang['BUILDING_3']  = 'Refinería';
$lang['BUILDING_6']  = 'Fábrica de armas';
$lang['BUILDING_8']  = 'Centro de comunicaciones';
$lang['BUILDING_24'] = 'Factoría Bio-científica';
$lang['BUILDING_12'] = 'Plataforma petrolífera';
$lang['BUILDING_14'] = 'Laboratorio de investigación militar';
$lang['BUILDING_16'] = 'Instalación de pruebas nucleares';
$lang['BUILDING_25'] = 'Planta de tratamiento de agua';
$lang['BUILDING_17'] = 'Red de satélites solares';

/* Defence (Earth) - Group 2 */
$lang['BUILDING_2']  = 'Búnker';
$lang['BUILDING_21'] = 'Minas marinas';
$lang['BUILDING_51'] = 'Embajada';
$lang['BUILDING_22'] = 'Lanza torpedos';
$lang['BUILDING_9']  = 'Misil de largo alcance';
$lang['BUILDING_52'] = 'Centro de mando Inteligencia';
$lang['BUILDING_53'] = 'Centro de control de Drones';
$lang['BUILDING_54'] = 'Guerra ciberespacial';

/* Energy (Earth) - Group 3 */
$lang['BUILDING_4']  = 'Unidad energía solar';
$lang['BUILDING_10'] = 'Generador móvil';
$lang['BUILDING_13'] = 'Instalación de gas';
$lang['BUILDING_18'] = 'Parque eólico';
$lang['BUILDING_19'] = 'Torre petrolífera';
$lang['BUILDING_26'] = 'Parque energía solar';
$lang['BUILDING_27'] = 'Parque eólico offshore';
$lang['BUILDING_28'] = 'Instalación energía geotérmica';
$lang['BUILDING_35'] = 'Represa hidroeléctrica';
$lang['BUILDING_39'] = 'Planta nuclear';

/* Discount (Earth) - Group 4 */
$lang['BUILDING_29'] = 'Equipamiento logístico';
$lang['BUILDING_40'] = 'Depósito de suministros';
$lang['BUILDING_37'] = 'Hospital móvil';
$lang['BUILDING_38'] = 'Centro de mando';
$lang['BUILDING_30'] = 'Campo de entrenamiento';
$lang['BUILDING_31'] = 'Academia militar';
$lang['BUILDING_32'] = 'Instalaciones de ocio';
$lang['BUILDING_33'] = 'Monumento Militar';
$lang['BUILDING_34'] = 'Cuartel militar';
$lang['BUILDING_36'] = 'Oficina presidencial';

/* Maintenance (Earth) - Group 5 */
$lang['BUILDING_41'] = 'Mantenimiento de carreteras';
$lang['BUILDING_42'] = 'Mantenimiento de puentes';
$lang['BUILDING_43'] = 'Taller de vehículos';
$lang['BUILDING_44'] = 'Hangar de helicópteros';
$lang['BUILDING_45'] = 'Garaje de vehículos';
$lang['BUILDING_46'] = 'Muelle de la Marina';
$lang['BUILDING_47'] = 'Mantenimiento de edificios';
$lang['BUILDING_48'] = 'Muelle de submarinos';
$lang['BUILDING_49'] = 'Mantenimiento instalaciones';
$lang['BUILDING_50'] = 'Hangar de aeronaves';

/* Income (Moon) - Group 6 */
$lang['BUILDING_600'] = 'Base Central';
$lang['BUILDING_601'] = 'Centro Investigación & Exploración';
$lang['BUILDING_602'] = 'Alojamientos del personal';
$lang['BUILDING_603'] = 'Factoría de oxígeno';
$lang['BUILDING_604'] = 'Factoría de agua';
$lang['BUILDING_605'] = 'Centro de comunicaciones';
$lang['BUILDING_606'] = 'Invernadero';
$lang['BUILDING_607'] = 'Factoría de construcción';
$lang['BUILDING_608'] = 'Centro de extracción metales';
$lang['BUILDING_609'] = 'Centro de lanzamiento de naves';
$lang['BUILDING_610'] = 'Hospital lunar';
$lang['BUILDING_611'] = 'Centro de terraformación';

/* Defence (Moon) - Group 7 */
$lang['BUILDING_700'] = 'Investigación de defensa';
$lang['BUILDING_701'] = 'Fábrica de robots';
$lang['BUILDING_702'] = 'Misiles de corto alcance';
$lang['BUILDING_703'] = 'Fábrica de Guerreros';
$lang['BUILDING_704'] = 'Sistema de alarma';
$lang['BUILDING_705'] = 'Láser de largo alcance';
$lang['BUILDING_706'] = 'Fábrica de naves espaciales';
$lang['BUILDING_707'] = 'Escudo de energía';
$lang['BUILDING_708'] = 'Lanzador de misiles nucleares';
$lang['BUILDING_709'] = 'Fábrica de armas de electrochoque';
$lang['BUILDING_710'] = 'Fábrica de armas Fotónicas';
$lang['BUILDING_711'] = 'Defensa androide móvil';
$lang['BUILDING_712'] = 'Escudo de defensa de la colonia';
$lang['BUILDING_713'] = 'Fábrica subterránea';
$lang['BUILDING_714'] = 'Nave espacial de lanzamiento';

/* Energy (Moon) - Group 8 */
$lang['BUILDING_800'] = 'Centro de investigación de gases';
$lang['BUILDING_801'] = 'Centro de investigación petrolero';
$lang['BUILDING_802'] = 'Extractores de gas';
$lang['BUILDING_803'] = 'Extractores de petróleo';
$lang['BUILDING_804'] = 'Instalación de energía solar';
$lang['BUILDING_805'] = 'Instalación de gas';
$lang['BUILDING_806'] = 'Centro de órbita solar';
$lang['BUILDING_807'] = 'Instalación energía nuclear';
$lang['BUILDING_808'] = 'Super-instalación energía solar';
$lang['BUILDING_809'] = 'Mini colonia espacial';
$lang['BUILDING_810'] = 'Sistema explotación solar';
$lang['BUILDING_811'] = 'Colonia Espacial';

/* Discount (Moon) - Group 9 */
$lang['BUILDING_900'] = 'Rascacielos';
$lang['BUILDING_901'] = 'Puente';
$lang['BUILDING_902'] = 'Colonia';
$lang['BUILDING_903'] = 'Central';
$lang['BUILDING_904'] = 'Base volcánica';
$lang['BUILDING_905'] = 'Ciudad';
$lang['BUILDING_906'] = 'Campo entrenamiento';
$lang['BUILDING_907'] = 'Lanzadores de misiles';
$lang['BUILDING_908'] = 'Oficina presidencial';
$lang['BUILDING_909'] = 'Academia militar';
$lang['BUILDING_910'] = 'Instalaciones de ocio';
$lang['BUILDING_911'] = 'Centro de mando';

/* Maintenance (Moon) - Group 10 */
$lang['BUILDING_1000'] = 'Centro de diseño';
$lang['BUILDING_1001'] = 'Reparación de robots';
$lang['BUILDING_1002'] = 'Reparación de misiles';
$lang['BUILDING_1003'] = 'Reparación unidades exploración';
$lang['BUILDING_1004'] = 'Reparación de vehículos';
$lang['BUILDING_1005'] = 'Reparación de guerreros';
$lang['BUILDING_1006'] = 'Reparación de infraestructuras';
$lang['BUILDING_1007'] = 'Reparación de unidades';
$lang['BUILDING_1008'] = 'Reparación de energía';
$lang['BUILDING_1009'] = 'Reparación robotizada';

/* Income (Mars) - Group 11 */
$lang['BUILDING_1100'] = 'Base central';
$lang['BUILDING_1101'] = 'Centro de investigación';
$lang['BUILDING_1102'] = 'Factoría de oxígeno';
$lang['BUILDING_1103'] = 'Alojamientos del personal';
$lang['BUILDING_1104'] = 'Factoría de agua';
$lang['BUILDING_1105'] = 'Centro de extracción metales';
$lang['BUILDING_1106'] = 'Centro de comunicación';
$lang['BUILDING_1107'] = 'Centro conversor';
$lang['BUILDING_1108'] = 'Invernadero';
$lang['BUILDING_1109'] = 'Hotel';

/* Defense (Mars) - Group 12 */
$lang['BUILDING_1200'] = 'centro de investigación';
$lang['BUILDING_1201'] = 'Fábrica de armas';
$lang['BUILDING_1202'] = 'Misil de corto alcance';
$lang['BUILDING_1203'] = 'Fábrica de guerreros';
$lang['BUILDING_1204'] = 'Sistema de alarma';
$lang['BUILDING_1205'] = 'Fábrica de naves espaciales';
$lang['BUILDING_1206'] = 'Lanzadera de largo alcance';
$lang['BUILDING_1207'] = 'Fábrica de Exploradores';
$lang['BUILDING_1208'] = 'Fábrica de robots';
$lang['BUILDING_1209'] = 'Fábrica de Guerreros II';
$lang['BUILDING_1210'] = 'Unidad detección alienígenas';

/* Energy (Mars) - Group 13 */
$lang['BUILDING_1300'] = 'Centro Investigación de Energía';
$lang['BUILDING_1301'] = 'Instalación de gas';
$lang['BUILDING_1302'] = 'Centro investigación petrolera';
$lang['BUILDING_1303'] = 'Extractores de petróleo';
$lang['BUILDING_1304'] = 'Instalación energía solar';
$lang['BUILDING_1305'] = 'Extractores de gas';
$lang['BUILDING_1306'] = 'Centro minero';
$lang['BUILDING_1307'] = 'Instalación energía nuclear';
$lang['BUILDING_1308'] = 'Super-centro de órbita solar';
$lang['BUILDING_1309'] = 'Colonia marciana';

/* Discount (Mars) - Group 14 */
$lang['BUILDING_1400'] = 'Centro de formación';
$lang['BUILDING_1401'] = 'Centro de terraformación';
$lang['BUILDING_1402'] = 'Colonia';
$lang['BUILDING_1403'] = 'Central';
$lang['BUILDING_1404'] = 'Depósito de suministros';
$lang['BUILDING_1405'] = 'Unidad de construcción';
$lang['BUILDING_1406'] = 'Campo de entrenamiento';
$lang['BUILDING_1407'] = 'Oficina presidencial';
$lang['BUILDING_1408'] = 'Centro de mando';

/* Maintenance (Mars) - Group 15 */
$lang['BUILDING_1500'] = 'Centro de diseño';
$lang['BUILDING_1501'] = 'Reparación de robots';
$lang['BUILDING_1502'] = 'Reparación de misiles';
$lang['BUILDING_1503'] = 'Reparación de Exploradores';
$lang['BUILDING_1504'] = 'Reparación de vehículos';
$lang['BUILDING_1505'] = 'Reparación de guerreros';
$lang['BUILDING_1506'] = 'Reparación de infraestructuras';
$lang['BUILDING_1507'] = 'Reparación de unidades';
$lang['BUILDING_1508'] = 'Reparación de energía';
$lang['BUILDING_1509'] = 'Reparación robotizada';

/* Income (Asteroid) - Group 16 */
$lang['BUILDING_1600'] = 'Base central';
$lang['BUILDING_1601'] = 'Centor de investigación';
$lang['BUILDING_1602'] = 'Factoría de oxígeno';
$lang['BUILDING_1603'] = 'Alojamientos del personal';
$lang['BUILDING_1604'] = 'Factoría de agua';
$lang['BUILDING_1605'] = 'Centro de extracción metales';
$lang['BUILDING_1606'] = 'Centro de comunicaciones';
$lang['BUILDING_1607'] = 'Centro conversor';
$lang['BUILDING_1608'] = 'Invernadero';
$lang['BUILDING_1609'] = 'Hotel';

/* Defense (Asteroid) - Group 17 */
$lang['BUILDING_1700'] = 'Centro de investigación';
$lang['BUILDING_1701'] = 'Fábrica de armas';
$lang['BUILDING_1702'] = 'Misil de corto alcance';
$lang['BUILDING_1703'] = 'Fábrica de guerreros';
$lang['BUILDING_1704'] = 'Sistema de alarma';
$lang['BUILDING_1705'] = 'Fábrica de naves espaciales';
$lang['BUILDING_1706'] = 'Lanzadera de largo alcance';
$lang['BUILDING_1707'] = 'Fábrica de Exploradores';
$lang['BUILDING_1708'] = 'Fábrica de robots';
$lang['BUILDING_1709'] = 'Fábrica de guerreros II';

/* Energy (Asteroid) - Group 18 */
$lang['BUILDING_1800'] = 'Centro Investigación de Energía';
$lang['BUILDING_1801'] = 'Instalación de gas';
$lang['BUILDING_1802'] = 'Centro de investigación petrolera';
$lang['BUILDING_1803'] = 'Extractores de petróleo';
$lang['BUILDING_1804'] = 'Instalación de energía solar';
$lang['BUILDING_1805'] = 'Extractores de gas';
$lang['BUILDING_1806'] = 'Centro minero';
$lang['BUILDING_1807'] = 'Instalación de energía nuclear';
$lang['BUILDING_1808'] = 'Super-centro de órbita solar';
$lang['BUILDING_1809'] = 'Colonia Asteroide';

/* Discount (Asteroid) - Group 19 */
$lang['BUILDING_1900'] = 'Centro de formación';
$lang['BUILDING_1901'] = 'Centro de terraformación';
$lang['BUILDING_1902'] = 'Alojamientos del personal militar';
$lang['BUILDING_1903'] = 'Cuartel militar';
$lang['BUILDING_1904'] = 'Depósito de suministros';
$lang['BUILDING_1905'] = 'Centro de construcción';
$lang['BUILDING_1906'] = 'Campo de entrenamiento';
$lang['BUILDING_1907'] = 'Oficina presidencial';
$lang['BUILDING_1908'] = 'Colonia';
$lang['BUILDING_1909'] = 'Instalación de ocio';

/* Maintenance (Asteroid) - Group 20 */
$lang['BUILDING_2000'] = 'Centro de diseño';
$lang['BUILDING_2001'] = 'Reparación de robots';
$lang['BUILDING_2002'] = 'Reparación de misiles';
$lang['BUILDING_2003'] = 'Reparación de Exploradores';
$lang['BUILDING_2004'] = 'Reparación de vehículos';
$lang['BUILDING_2005'] = 'Reparación de guerreros';
$lang['BUILDING_2006'] = 'Reparación de infraestructuras';
$lang['BUILDING_2007'] = 'Reparación de unidades';
$lang['BUILDING_2008'] = 'Reparación de energía';
$lang['BUILDING_2009'] = 'Reparación robotizada';

/*
** ------------------
** BUILDING PAGE
** ------------------
*/

$lang['BUILDING_TITLE'] = 'EDIFICIOS';
$lang['BUILDING_NOTE1'] = 'Nota: los edificios de Ingresos proporcionan un mayor ingreso por hora. Cada edificio contiene ciudadanos que aumentan el coste por hora.';
$lang['BUILDING_NOTE2'] = 'Nota: los edificios de Defensa proporcionan mayor defensa contra los ataques. Cada edificio contiene ciudadanos que aumentan el coste por hora.';
$lang['BUILDING_NOTE3'] = 'Nota: los edificios de Energía proporcionan una recuperación más rápida de la energía. Cada edificio contiene ciudadanos que aumentan el coste por hora.';
$lang['BUILDING_NOTE4'] = 'Nota: los edificios de Descuento ofrecen descuento en el precio de compra de los edificios. Cada edificio contiene ciudadanos que aumentan el coste por hora.';
$lang['BUILDING_NOTE5'] = 'Nota: los edificios de Mantenimiento proporcionan reparación más rápida de las unidades resultando en una menor pérdida de unidades durante las batallas. Cada edificio contiene ciudadanos que aumentan el coste por hora.';

$lang['BUILDING_NOTE6'] = 'Nota: Los edificios de Ingresos proporcionan mayores ingresos para su base lunar.';
$lang['BUILDING_NOTE7'] = 'Nota: Los edificios de Defensa proporcionan una mayor defensa para los ataques contra a su base lunar.';
$lang['BUILDING_NOTE8'] = 'Nota: Los edificios de Energía proporcionan una recuperación más rápida de energía para su base lunar.';
$lang['BUILDING_NOTE9'] = 'Nota: los edificios de Descuento ofrecen precio de descuento en la compra de edificios lunares.';
$lang['BUILDING_NOTE10'] = 'Nota: los edificios de Mantenimiento proporcionan reparación más rápida de las unidades resultando en una menor pérdida de unidades durante las batallas.';

$lang['BUILDING_NOTE11'] = 'Nota: los edificios de Ingresos proporcionan mayores ingresos para su base de Marte.';
$lang['BUILDING_NOTE12'] = 'Nota: los edificios de Defensa proporcionan una mayor defensa para los ataques contra su base de Marte.';
$lang['BUILDING_NOTE13'] = 'Nota: los edificios de Energía proporciona una recuperación más rápida de energía para su base de Marte.';
$lang['BUILDING_NOTE14'] = 'Nota: los edificios de Descuento ofrecen descuento en el precio de compra de edificios en Marte.';
$lang['BUILDING_NOTE15'] = 'Nota: los edificios de Mantenimiento proporcionan reparación más rápida de las unidades resultando en una menor pérdida de unidades durante las batallas.';

$lang['BUILDING_NOTE16'] = 'Nota: Los edificios de Ingresos proporcionan mayores ingresos para su base del Asteroide.';
$lang['BUILDING_NOTE17'] = 'Nota: Los edificios de Defensa proporcionan una mayor defensa para los ataques contra su base del Asteroide.';
$lang['BUILDING_NOTE18'] = 'Nota: Los edificios de Energía proporcionan una recuperación más rápida de energía para su base del Asteroide.';
$lang['BUILDING_NOTE19'] = 'Nota: Los edificios de Descuento ofrecen precio de descuento en su compra de edificios en el Asteroide.';
$lang['BUILDING_NOTE20'] = 'Nota: los edificios de Mantenimiento proporcionan reparación más rápida de las unidades resultando en una menor pérdida de unidades durante las batallas.';

$lang['BUILDING_SELL'] = 'Ha vendido %s %s por %s. Todavía %s disponibles.';
$lang['BUILDING_LOW_UPKEEP'] = 'No tiene suficiente ingreso por hora para vender %s %s por %s.';
$lang['BUILDING_NOT_OWNED'] = 'No dispone de %s %s.';

$lang['BUILDING_BUY'] = 'Usted compró %s %s por %s. Ahora %s disponibles.';
$lang['BUILDING_MAX'] = 'No más de %s %s(s) permitidos!';
$lang['BUILDING_NO_FUNDS'] = 'No tiene suficiente dinero para comprar %s %s por %s.'; 
$lang['BUILDING_LOW_UPKEEP2'] = 'No tiene suficiente ingreso por hora para comprar %s %s por %s.';

$lang['BUILDING_UPKEEP'] = 'Coste por hora';
$lang['BUILDING_PRICE'] = 'Precio';
$lang['BUILDING_DEPLOYED'] = 'Disponibles';
$lang['BUILDING_GAIN'] = 'Ventajas';
$lang['BUILDING_ENERGY'] = 'Energía';
$lang['BUILDING_INCOME'] = 'Ingreso';
$lang['BUILDING_REQUIRED'] = 'Requiere';

/*
** ------------------
** MONEY - BANKS 
** ------------------
*/

$lang['MONEY_TITLE'] = 'DINERO';

$lang['BANK_GROUP_1'] = 'Nacional';
$lang['BANK_GROUP_2'] = 'Trasquera';
$lang['BANK_GROUP_3'] = 'SwissCore';

$lang['BANK_TITLE'] = 'BANCOS';
$lang['BANK_NOTE'] = 'Nota: Hay una comisión de %s% por cualquier depósito. El banco paga %s% interés diario. ';
$lang['BANK_WARNING'] = 'Advertencia: Unidades de Inteligencia o Exploradores de otros jugadores pueden robar el dinero de este banco.';

$lang['BANK_TRANSACTION_TYPE_0'] = 'Retiró';
$lang['BANK_TRANSACTION_TYPE_1'] = 'Ingresó';
$lang['BANK_TRANSACTION_TYPE_2'] = 'Comisión de gestión';
$lang['BANK_TRANSACTION_TYPE_3'] = 'Restaurar cuenta';		
$lang['BANK_TRANSACTION_TYPE_4'] = 'Interés';	
$lang['BANK_TRANSACTION_TYPE_5'] = 'Robo de espías';
$lang['BANK_TRANSACTION_TYPE_6'] = 'Bonus ';

$lang['BANK_TRANSACTION_LOG'] = 'Registro de transacciones';

$lang['BANK_WITHDRAW']= 'Retirados %s dólares del banco';
$lang['BANK_WITHDRAW_FAILED'] = '%s dólares no están disponibles en la cuenta bancaria!';

$lang['BANK_DEPOSIT'] = 'Ingresados %s dólares en el banco.';
$lang['BANK_DEPOSIT_FAILED'] = 'No dispone de %s dólares.';

/*
** ------------------
** MONEY - STOCK EXCHANGES
** ------------------
*/

$lang['STOCK_GROUP_1'] = 'Nasdaq';
$lang['STOCK_GROUP_2'] = 'DowJones';
$lang['STOCK_GROUP_3'] = 'AEX';
$lang['STOCK_GROUP_4'] = 'Personal';

$lang['STOCK_TITLE'] = 'BOLSA DE VALORES';
$lang['STOCK_BROKER_ERROR'] = 'La conexión con el broker ha fallado. No es posible operar en este momento. Por favor, inténtelo de nuevo más tarde.';
$lang['STOCK_BUY'] = 'Compró %s %s acciones por %s dólares. Actualmente %s disponibles.';
$lang['STOCK_NO_MONEY'] = 'No tiene suficiente dinero para comprar %s %s acciones por %s dólares.';
$lang['STOCK_PRICE'] = 'Cotización %s [%s]';
$lang['STOCK_PROFIT'] = 'Beneficio de acciones %s [%s]';
$lang['STOCK_NOT_OWNED'] = 'No dispone de %s %s acciones.';
$lang['STOCK_SELL'] = 'Vendió %s %s acciones por %s dólares. Pagó %s dólares de comisión de gestión. Actualmente %s disponibles.';
$lang['STOCK_NOTE'] = 'Nota: Usted puede comprar o vender acciones para obtener beneficios. El precio de las acciones se basan en información en tiempo real del servicio financiero de Yahoo!. Hay %s% de comisión por cada operación de venta.';
$lang['STOCK_PRICE_TO_LOW'] = 'Cotización de las acciones demasiado bajo. Operaciones bloqueadas!';

$lang['STOCK_SYMBOL'] = 'Símbolo del valor'; 
$lang['STOCK_SYMBOL_INFO'] = 'Nota: Entre en símbolos de valores financieros en Yahoo! para personalizar esta lista.'; 

$lang['STOCK_ADD'] = 'Añadir valor';
$lang['STOCK_SYMBOL_ADDED'] = 'Añadió (%s) a su lista personal de valores.';
$lang['STOCK_NO_SYMBOLS' ] = 'Usted no ha añadido valores bursátiles a su lista personal!';
$lang['STOCK_SYMBOL_NOT_FOUND'] = 'Símbolo del valor (%s) no existe!';
$lang['STOCK_SYMBOL_AVAILABLE'] = 'Símbolo del valor (%s) está disponible en la lista personal.';

$lang['STOCK_REMOVE'] = 'Eliminar valor';
$lang['STOCK_SYMBOL_REMOVED'] = 'Símbolo del valor eliminado!';

$lang['GENERAL_STOCKS'] = 'Valores';

/*
** ------------------
** MONEY - CASINO
** ------------------
*/

$lang['CASINO_TITLE'] = 'CASINO' ;

$lang['CASINO_1'] = 'Rueda de la Fortuna';
$lang['CASINO_2'] = 'Máquina tragamonedas';

$lang['CASINO_MONEY'] = 'Dinero';
$lang['CASINO_NUMBER'] = 'Número de la suerte';
$lang['CASINO_BET'] = 'Apuesta';
$lang['CASINO_PLAY'] = 'Jugar';
$lang['CASINO_ROLL'] = 'Rodar';

$lang['CASINO_NO_BET'] = 'Introduzca cantidad de la apuesta!';
$lang['CASINO_NO_LUCKY_NUMBER'] = 'Introducir número de la suerte!';
$lang['CASINO_BET_TO_LARGE'] = 'Apuesta demasiado grande! La apuesta máxima es de %s dólares.'; 
$lang['CASINO_NO_MONEY'] = 'No hay dinero suficiente!'; 

$lang['CASINO_WIN'] = 'El número ganador fue %s. Ganó %s dólares.';
$lang['CASINO_LOST'] = 'El número ganador fue %s. Perdió %s dólares..';

$lang['CASINO_NOTE1'] = 'Nota: Introduzca su apuesta y número de la suerte y pulse el botón de jugar. Si tienes suerte, puede ganar 10 veces su apuesta.';
$lang['CASINO_NOTE2'] = 'Nota: Introduzca su apuesta y pulse el botón de jugar. Tal vez su apuesta gane.';

$lang['CASINO_UNLOCK'] = '%s se desbloquea en el nivel %s';

$lang['CASINO_SLOTMACHINE_WIN'] = 'Ganó %s veces su apuesta. Ha ganado %s dólares.';
$lang['CASINO_SLOTMACHINE_LOST'] = 'Perdió %s dólares.';
$lang['CASINO_SLOTMACHINE_HELP'] = 'Se pagarán las siguientes combinaciones de máquina tragamonedas';

/*
** ------------------
** ALLIANCE
** ------------------
*/

$lang['ALLIANCE_TITLE'] = 'ALIANZAS';

$lang['ALLIANCE_PENDING_TITLE1'] = 'Pendientes';
$lang['ALLIANCE_PENDING_TITLE2'] = 'Pendientes [%s aceptados - %s aliados invitados]';

$lang['ALLIANCE_ACCEPT_TITLE1'] = 'Aceptados';
$lang['ALLIANCE_ACCEPT_TITLE2'] = 'Aceptados [%s aceptados - %s aliados invitados]';

$lang['ALLIANCE_INVITE_TITLE1'] = 'Invitar';
$lang['ALLIANCE_INVITE_TITLE2'] = 'Invitaciones [%s aceptados - %s aliados invitados]';

$lang['ALLIANCE_NO_PENDING'] = 'No hay invitaciones pendientes!'; 
$lang['ALLIANCE_INVITATION'] = 'Invitación de aliado enviada a %s!'; 
$lang['ALLIANCE_REJECT'] = 'Rechazar %s como aliado!';
$lang['ALLIANCE_DROP'] = 'Descartar %s como aliado!';
$lang['ALLIANCE_ACCEPT'] = 'Aceptar %s como aliado!';
$lang['ALLIANCE_ALLY'] = 'Aliado';
$lang['ALLIANCE_MAXIMUM'] = 'Número máximo de %s aliados alcanzado en este nivel.'; 
$lang['ALLIANCE_LOCKED'] = 'Las invitaciones de alianzas se desbloquean en el nivel 1';
$lang['ALLIANCE_NOTE'] = 'Nota: Por cada aliado aceptado puede dirigir 6 unidades más durante los combates. Tenga en cuenta que no se puede atacar a los aliados.';

$lang['ALLIANCE_INVITE_FRIENDS'] = 'Invitar a un amigo por correo electrónico';
$lang['ALLIANCE_INVITE_NOTE'] = 'Nota: Invite a un jugador como aliado. Si el otro jugador acepta o rechaza la alianza, usted recibirá una notificación por correo electrónico (ver opción en configuración). La cantidad máxima de aceptados + aliados invitados para este nivel es %s.';
$lang['ALLIANCE_EMAIL_INVALID']= 'Dirección de correo electrónico no válida!';
$lang['ALLIANCE_ALREADY_INVITED'] = 'Ya se había enviado invitación al email!';
$lang['ALLIANCE_INVITE_SENT'] = 'Invitación enviada.';

$lang['ALLIANCE_COMMENT_TITLE'] = 'Mensaje';
$lang['ALLIANCE_COMMENT_TEXT1'] = 'Crear mensaje (máx. 400 caracteres) para todos los jugadores';
$lang['ALLIANCE_COMMENT_TEXT2'] = 'Crear mensaje (máx. 400 caracteres) para %s';
$lang['ALLIANCE_PLAYER_NEWS'] = 'Mensajes';
$lang['ALLIANCE_COMMENT_ALL'] = 'Mensaje almacenado y disponible para todos los jugadores.';
$lang['ALLIANCE_COMMENT_PLAYER'] = 'Mensaje enviado a %s';

$lang['LEADERBORD_BEST_PLAYER'] = 'Clasificación (Mejores jugadores)';
$lang['LEADERBORD_BEST_PLAYER_NOTE'] = 'Nota: La clasificación muestra los mejores jugadores humanos. Los jugadores WarQuest robot (ciberespacio) no se muestran!';

$lang['LEADERBORD_BEST_COUNTRY'] = 'Clasificación (Mejores países)';
$lang['LEADERBORD_BEST_COUNTRY_NOTE'] = 'Nota: La clasificación muestra los mejores países reales.';

$lang['LEADERBORD_PLAYER_COUNTRY'] = 'Clasificación (Mejor jugador de %s)';
$lang['LEADERBORD_PLAYER_COUNTRY_NOTE'] = 'Nota: La clasificación muestra los mejores jugadores del país seleccionado.';

/*
** ------------------
** FORUM 
** ------------------
*/

$lang['FORUM_TITLE'] = 'FORUMS'; 
$lang['FORUM_TITLE2'] = 'Forums';
$lang['FORUM_NOTE'] = 'Nota: Seleccione un foro para ver todos los temas publicados. He visto a algunas personas insultar o usar un lenguaje malsonante en los foros. No quemos ese tipo de lenguaje aquí! Gracias. Y recuerde, sin palabrotas! ';

$lang['FORUM_1'] = 'Anuncios'; 
$lang['FORUM_NOTE_1'] = 'Anuncios generales';
$lang['FORUM_2'] = 'Informe de errores'; 
$lang['FORUM_NOTE_2'] = 'Qué va mal en esta versión?';
$lang['FORUM_3'] = 'Solicitud de nuevas funciones'; 
$lang['FORUM_NOTE_3'] = 'Qué te gustaría añadir en la próxima versión?';
$lang['FORUM_4'] = 'Ayuda'; 
$lang['FORUM_NOTE_4'] = 'Qué cosas no están claras en WarQuest?';
$lang['FORUM_5'] = 'Otros'; 
$lang['FORUM_NOTE_5'] = 'Cualquier otro debate';
$lang['FORUM_6'] = 'Comunidades por países'; 
$lang['FORUM_NOTE_6'] = 'Debates en idiomas locales';

$lang['FORUM_SEARCH_TOKEN'] = 'La palabra de búsqueda debe tener al menos 3 caracteres de largo.';

$lang['TOPIC_TITLE'] = 'Temas'; 
$lang['TOPIC_CREATED_INPUT'] = 'Crear un nuevo tema (máximo 80 caracteres)';
$lang['TOPIC_CREATED'] = 'Tema creado';
$lang['TOPIC_UPDATED'] = 'Tema actualizado';
$lang['TOPIC_DELETED'] = 'Tema borrado';
$lang['TOPIC_NO_TOPICS'] = 'Por el momento no hay tema(s) encontrado(s).';
$lang['TOPIC_NOTE'] = 'Nota: Seleccione un tema para leer / escribir mensajes o crear un nuevo tema.'; 
$lang['TOPIC_CREATED_BY'] = '(Creado por %s)';

/*
** ------------------
** FORUM - POLL
** ------------------
*/

$lang['POLL_TITLE'] = 'Encuestas';
$lang['POLL_RESULT_TITLE'] = 'Resultados de encuestas';
$lang['POLL_TEASER_TITLE'] = 'Nueva encuesta';
$lang['POLL_RESULTS'] = 'Resultados';
$lang['POLL_ClOSED'] = '(Encuesta cerrada)';
$lang['POLL_VOTE_ADD'] = 'Gracias por su voto! Ha recibido 10 puntos de experiencia extra como recompensa.';
$lang['POLL_VOTE_REMOVE'] = 'Su voto se ha cancelado!';
$lang['POLL_VOTE'] = 'Votar';
$lang['POLL_VOTES'] = 'Votos';
$lang['POLL_CANCEL'] = 'Cancelar';
$lang['POLL_SUMMARY'] = 'Total votantes: %s';
$lang['POLL_WARNING'] = 'Seleccione una de las opciones de voto posibles!';

/*
** ------------------
** FORUM - CHAT
** ------------------
*/

$lang['CHATROOM_TITLE'] = 'Sala de Chat';
$lang['CHATROOM_NOTE'] = 'Nota: Iniciar una sesión de chat seleccionando un jugador en línea!';
$lang['CHATROOM_LAST_ACTIVE'] = 'Última vez activo';
$lang['CHATROOM_CHAT'] = 'Chat';
$lang['CHAT_NOTE'] = 'Nota: Introduzca un mensaje para iniciar el chat!';

$lang['CHAT_TITLE'] = 'Chat';

/*
** ------------------
** HELP - INSTRUCTIONS
** ------------------
*/

$lang['HELP_TITLE'] = 'AYUDA';

$lang['HELP_GENERAL_SUBTITLE'] = 'Instrucciones';

$lang['HELP_INTRO_TITLE'] = 'Introducción';
$lang['HELP_INTRO'] =	'WarQuest es un juego multijugador en línea gratuito que ofrece una zona de guerra con miles de jugadores reales. WarQuest le lleva al 
año 2020. El mundo está en guerra. El objetivo del juego es la defensa de tu país y conquistar otros 
países. Compra armas y unidades de producción, juega las misiones, lucha, haz aliados y conviértete en el mejor 
jugador de tu país.';

$lang['HELP_EXP_TITLE'] = 'Experiencia / Nivel';
$lang['HELP_EXP'] = 'Juega a las misiones y combate para ganar puntos de experiencia. Cuando acumules 
suficientes puntos de experiencia podrás alcanzar el siguiente nivel. Cuando un nivel se ha completado la 
la energía, la salud y la munición se restauran instantáneamente.';

$lang['HELP_HEALTH_TITLE'] = 'Salud';
$lang['HELP_HEALTH'] = 'Su salud se reduce en cada batalla, pero se restaura automáticamente con el tiempo 
También puede visitar el hospital (Inicio -> Restaurar) y pagar para recuperarla al instante.';

$lang['HELP_ENERGY_TITLE'] = 'Energía'; 
$lang['HELP_ENERGY'] = 'Su nivel de energía disminuye cada vez que juega una misión, pero se restituye
automáticamente con el tiempo. Compre edificios de energía para restaurar la energía con mayor rapidez. También puede 
restaurarla de la misma manera que se restaura la salud.';

$lang['HELP_AMMO_TITLE'] = 'Munición'; 
$lang['HELP_AMMO'] =	'Cada batalla cuesta munición. La munición se restablece automáticamente con el 
tiempo. También puede restaurarla de la misma manera que puede restaurar la salud.';

$lang['HELP_MISSION_TITLE'] = 'Misiones';
$lang['HELP_MISSION'] = 'Juega las misiones para ganar dinero y puntos de experiencia para alcanzar el siguiente nivel. 
Si una misión está 100% completada ganará el doble de la cantidad de dinero. Si un continente es conquistado 
usted recibe un bonus de ingreso por hora.<br/><br/>

La prima adicional que se da cuando todas las misiones del planeta se han completado es la siguiente:<br/>
TIERRA: 100 millones de dólares<br/>
LUNA: 500 millones de dólares<br/>
MARTE: 999 miles de millones de dólares<br/>
ASTEROIDE: 50 puntos de comercio';

$lang['HELP_BATTLE_TITLE'] = 'Batalla';
$lang['HELP_BATTLE'] =	'Lucha contra otros jugadores para ganar dinero, puntos de experiencia y llegar al siguiente 
nivel. En los combates las unidades y los edificios de la base pueden ser dañados o incluso destruidos.';

$lang['HELP_UNITS_TITLE'] = 'Unidades';
$lang['HELP_UNITS'] =  'Durante los ataques sus mejores unidades son automáticamente seleccionadas. El tamaño (cantidad 
de unidades operativas) de su ejército está relacionado con el número de aliados aceptados. Comienzas
con un aliado que le permite comandar 6 unidades. Cada aliado aceptado le permite comandar seis unidades más.
Usted puede comprar más, pero sólo se utilizarán las 6 mejores x el número de aliados que tenga.';

$lang['HELP_BUILDINGS_TITLE'] = 'Edificios';
$lang['HELP_BUILDINGS'] = 'Durante el juego los edificios proporcionan ingresos, una mayor defensa, recuperación más rápida de energía, 
descuentos y / o mejor mantenimiento de las unidades. Cada compra de edificios incrementará el precio para la próxima
compra. Cada uno de los edificios contiene ciudadanos que tienen coste por hora.';

$lang['HELP_BANKS_TITLE'] = 'Bancos';
$lang['HELP_BANKS'] = 'Cada banco le cobrará una comisión de depósito. El dinero que se almacena en el banco Nacional 
está a salvo de otros jugadores, pero ofrece un interés mínimo diario. El dinero almacenado en los bancos Trasquera o SwissCore 
dan mayor interés diario, pero las unidades de Inteligencia (en la Tierra) o en de Exploradores (Luna / Marte) de otros jugadores pueden robarle el dinero.';

$lang['HELP_ALLIANCE_TITLE'] = 'Alianzas'; 
$lang['HELP_ALLIANCE'] = 'Cada aliado aceptado le permite comandar 6 unidades adicionales (de las que posea) 
durante las batallas. Aumente el número de aliados para hacerse más fuerte! Tenga en cuenta que no se puede atacar a los aliados.';

$lang['HELP_SKILL_POINTS_TITLE'] = 'Puntos de Habilidades';
$lang['HELP_SKILL_POINTS'] = 'Durante el juego se pueden recibir puntos de Habilidad. Utilice esos puntos para 
aumentar el ataque, defensa, salud, energía y / o habilidades de munición. Mejorar la munición cuesta 2 puntos de habilidad, 
los otros le cuestan sólo 1 punto de habilidad. También puede negociar 2 a 1 sus puntos de habilidad para cambiar sus habilidades.';

$lang['HELP_TRADE_POINTS_TITLE'] = 'Puntos de Comercio';
$lang['HELP_TRADE_POINTS']  = 'Los puntos de comercio pueden ser adquiridos al donar algunos dólares reales. Ayuda -> Donación. 
La compra de puntos de Comercio se pueden cambiar por puntos de habilidad, dinero en efectivo o se pueden utilizar para mejorar su 
temporizador de recuperación de salud, energía o munición.';

$lang['HELP_TACTICS_TITLE'] = 'Tácticas';
$lang['HELP_TACTICS'] = 'Una cosa a tener en cuenta es que las unidades utilizadas en las misiones también son objeto de 
pérdidas como bajas. Es importante tener en cuenta que el coste de reemplazar las unidades más caras
que utiliza en una misión puede exceder del dinero obtenido en la propia misión. En general, si su objetivo
es maximizar el dinero de las misiones, entonces, céntrese en el valor del dinero / energía de las misiones. 
Si su objetivo es maximizar los puntos de experiencia, entonces céntrese en el valor Exp / Energía de las 
misiones.<br/><br/>

Una vez que llegue a los niveles más altos, el juego automáticamente aumenta el rango de los enemigos que pueden
atacarle. Cuando esto ocurre, usted debe aumentar el número máximo de aliados y el número de aliados
aceptados.<br/><br/>

Los edificios de Defensa son una compra ideal, ya que aumentan su puntuación de defensa cuando es atacado.
Yo recomiendo comprar tantos como pueda permitirse, ya que esto le permitirá dedicar el resto de su dinero
a las unidades de ataque sin tener que preocuparse por sus puntos de defensa.<br/><br/>

En WarQuest, los edificios de defensa hacen muy difícil atacar con éxito a algunos oponentes. 
Aunque se recomienda poner puntos a la defensa, yo recomiendo tener la mayor cantidad de puntos 
posible en el ataque. Puede compensar la disminución de puntos de habilidad de defensa con edificios de 
defensa.<br/><br/>

Al decidir qué unidades comprar, es necesario considerar cuidadosamente los costes de las unidades por hora y su fuerza 
de defensa y ataque. Suponiendo que usted puede permitirse el lujo de comprar la unidad, el coste no debería ser un factor en su 
decisión ya que se paga una vez. La reducción de ingresos debida al coste por hora
de las unidades hace que no tenga sentido comprar siempre las mejores unidades disponibles. Si usted está ganando la mayoría de
sus batallas con sus unidades actuales, entonces puede tener más sentido estratégico no aumentar su
coste por hora y permitir ingresos para construir a un ritmo más rápido.';

$lang['HELP_GRAVATAR_TITLE'] = 'Gravatar';
$lang['HELP_GRAVATAR'] = 'WarQuest soporta el servicio de imágenes Gravatar (www.gravatar.com). Gravatar es un
imagen que te acompaña de un sitio a otro y aparece al lado de tu apodo (nickname).';

$lang['HELP_BOUNTY_TITLE'] = 'Caza recompensas';
$lang['HELP_BOUNTY'] = 'Puede ofrecer recompensa por la cabeza de sus enemigos. El precio de la recompensa está relacionado con el 
nivel de su oponente. Después de establecer la recompensa otros jugadores pueden atacar al oponente (Batalla -> Caza recompensas).
Si el oponente es derrotado perderá algunos puntos de experiencia y el dinero de la recompensa se transfiere al 
vencedor.';

$lang['HELP_UNITS_CONDITION_TITLE'] = 'Estado Unidades (EU)';
$lang['HELP_UNITS_CONDITION'] = 'Este valor da información sobre el estado actual de las unidades. 
Si el estado cae por debajo de 0%, perderá algunas unidades. Para evitar la pérdida de unidades se puede visitar 
(Inicio -> Restaurar) para reparar sus unidades operativas.'; 

$lang['HELP_BUILDINGS_CONDITION_TITLE'] = 'Estado Edificios (EE)';
$lang['HELP_BUILDINGS_CONDITION'] = 'Este valor da información acerca del estado de sus edificios en  
la Base. Si el estado cae por debajo de 0%, perderá algunos edificios. Para evitar su pérdida 
se puede visitar (Inicio -> Restaurar) para reparar su Base.'; 

$lang['HELP_FORUM_TITLE'] = 'Forum';
$lang['HELP_FORUM'] = 'Para obtener más información y chatear con otros jugadores por favor visite el Forum
Warquest.';

$lang['HELP_WORLDMAP_TITLE'] = 'Mapa';
$lang['HELP_WORLDMAP'] = 'Cada mapa de planeta (Tierra / Luna / Marte) contiene 72 regiones que pueden ser conquistadas jugando las
misiones. Las regiones puede tener uno de los siguientes colores: <br/>
- "Verde" Region 0% conquistada<br/>
- "Amarillo" Region 33% conquistada.<br/>
- "Purpura" Region 66% conquistada.<br/>
- "Naranja" Region 100% conquistada.<br/>
- "Rojo" Rebelión en la región. La región debe ser reconquistada.';

$lang['HELP_SHORTCUTS_TITLE'] = 'Accesos directos del menú';
$lang['HELP_SHORTCUTS'] = 'Los siguientes accesos directos ocultos están disponibles en la pestaña de
navegación rápida:<br/>
- Click "Dinero" para ir a la página de clasificación del jugador.<br/>
- Click "Exp." para ir a la página de clasificación de países.<br/>
- Click "Nivel" para ir a la página de encuestas.<br/>
- Click "Salud" para ir a la página de Restaurar.<br/>
- Click "Energía" para ir a la página de perfil del jugador.<br/>
- Click "Munición" Para ir a la página de puntos de Habilidades.';

$lang['HELP_ATTACK_FORCE_TITLE'] = 'Fuerza de ataque';
$lang['HELP_ATTACK_FORCE'] = 'Antes de la batalla se puede seleccionar una de las fuerzas de ataque siguientes:<br/><br/>
TIERRA<br/>
- "Ejército" Lo mejor de la Cavallería, la Armada y las unidades aéreas.<br/>
- "Cavallería" Sólo las unidades terrestres de Cavallería.<br/>
- "Armada" Solo las unidades de la Marina.<br/>
- "Fuerza aérea" Sólo las unidades de aviones de la tierra.<br/>
- "Inteligencia" Sólo las unidades de inteligencia de la tierra.<br/><br/>
LUNA<br/>
- "Ejército" Las mejores unidades de Robots, Guerreros y naves espaciales de la Luna.<br/>
- "Robots" Sólo unidades Robot de la Luna.<br/>
- "Guerreros" Sólo unidades Guerreros de la Luna.<br/>
- "Naves Espaciales " Sólo naves espaciales de la Luna.<br/>
- "Exploradores" Sólo unidades de Exploradores de la Luna.<br/><br/>
MARTE<br/>
- "Ejército" Las mejores unidades de Robots, Guerreros y naves espaciales de Marte.<br/>
- "Robots" Sólo unidades Robot de Marte.<br/>
- "Guerreros" Sólo unidades Guerreros de Marte.<br/>
- "Naves Espaciales " Sólo naves espaciales de Marte.<br/>
- "Exploradores" Sólo unidades de Exploradores de Marte.<br/><br/>
ASTEROIDE<br/>
- "Ejército" Las mejores unidades de Robots, Guerreros y naves espaciales del Asteroide.<br/>
- "Robots" Sólo unidades Robot del Asteroide.<br/>
- "Guerreros" Sólo unidades Guerreros del Asteroide.<br/>
- "Naves Espaciales " Sólo naves espaciales del Asteroide.<br/>
- "Exploradores" Sólo unidades de Exploradores del Asteroide.
';

$lang['HELP_REBELLION_CONDITION_TITLE'] = 'Estado de Rebelión (ER)';
$lang['HELP_REBELLION_CONDITION'] = 'Este valor da información sobre su estado actual de rebelión.
La rebelión de una Región se activa por parte de ataques de la Inteligencia (la Tierra) o exploradores (Luna / Marte) de sus enemigos. Si el
estado alcanza el 100%, algunas de sus regiones conquistadas iniciarán una rebelión. Para evitar la rebelión,
visite (Inicio -> Restaurar) para poner fin a la rebelión. Cada rebelión detiene el ingreso por hora del continente donde esté
la región. Restablezca el control en la región rebelde jugando la misión correspondiente.';

/*
** ------------------
** HELP - RELEASE NOTES
** ------------------
*/

$lang['HELP_NOTES_SUBTITLE1'] = 'Notas de la versión';
$lang['HELP_NOTES_SUBTITLE2'] = 'Notas de la versión (English only)';

/*
** ------------------
** HELP - RANKS
** ------------------
*/

$lang['HELP_RANKS_SUBTITLE'] = 'Rangos';
$lang['HELP_RANKS'] = 'Están disponibles los siguientes rangos militares:';

/*
** ------------------
** HELP - AWARDS
** ------------------
*/

$lang['HELP_AWARDS_SUBTITLE'] = 'Condecoraciones';
$lang['HELP_BATTLE_AWARDS'] = 'Se pueden conseguir las siguientes condecoraciones por batallas ganadas:';
$lang['HELP_BOUNTY_AWARDS'] = 'Se pueden conseguir las siguientes condecoraciones por recompensas ofrecidas:';
$lang['HELP_REBEL_AWARDS'] = 'Se pueden conseguir las siguientes condecoraciones por iniciar rebeliones:';


/*
** ------------------
** HELP - LEVELS
** ------------------
*/

$lang['HELP_LEVEL_SUBTITLE'] = 'Niveles';
$lang['HELP_LEVEL'] = 'Los siguientes niveles están disponibles:';
$lang['HELP_LEVEL_UNIT_LOST'] = 'Unidad perdida';
$lang['HELP_LEVEL_EXPERIENCE'] = 'Experiencia';
$lang['HELP_LEVEL_FEATURES'] = 'Esquema de desbloqueo de características';

/*
** ------------------
** HELP - STATS
** ------------------
*/

$lang['HELP_STATS_TITLE'] = 'Estadísticas';
$lang['HELP_STATS_NOTE'] = 'Nota: En esta página se muestran las estaísticas de WarQuest en tiempo real.';
$lang['HELP_STATS_PLAYERS'] = 'Nuevos jugadores (últimos 31 días)';
$lang['HELP_STATS_ONLINE'] = 'Jugadores conectados (últimos 31 días)';
$lang['HELP_STATS_FIGHTS'] = 'Batallas entre jugadores (últimos 31 días)';
$lang['HELP_STATS_MISSIONS'] = 'Misiones jugadas (últimos 13 días)';
$lang['HELP_STATS_CASINO'] = 'Jugadas en el Casino (últimos 31 días)';
$lang['HELP_STATS_REQUESTS'] = 'Conexiones al Servidor (últimos 31 días)';

/*
** ------------------
** HELP - DONATE
** ------------------
*/

$lang['HELP_DONATE_TITLE1'] = 'Donación';
$lang['HELP_DONATE_TITLE2'] = 'Donación (sólo en Inglés)';

$lang['HELP_SUBTITLE_DONATE1'] = 'General';
$lang['HELP_DONATE1'] = 'El software de WarQuest se puede utilizar de forma gratuita, pero si usted desea expresar 
su agradecimiento por el tiempo y los recursos que el autor ha dedicado a desarrollar y mantener la aplicación 
lo largo de los años, y también ayudar a reducir los costes de funcionamiento del servidor web, aceptamos y apreciamos 
sus donaciones.';

$lang['HELP_SUBTITLE_DONATE3'] = 'PayPal';
$lang['HELP_DONATE3'] = 'Para hacer una donación en línea con tarjeta de crédito, o cuenta de PayPal, haga clic 
abajo e introduzca la cantidad que usted desea aportar. Su tarjeta de crédito será procesada por PayPal, 
una entidad de confianza en las transacciones online. Muchas gracias por su apoyo.';

/*
** ------------------
** HELP - ABOUT
** ------------------
*/

$lang['HELP_ABOUT_SUBTITLE'] = 'Acerca de';
$lang['HELP_BACKGROUND_TITLE'] = 'Antecedentes';
$lang['HELP_BACKGROUND'] = 'WarQuest es creado por <a target="new" href="http://www.plaatsoft.nl">PlaatSoft</a>. La idea original del juego se basa en algunos otros juegos disponibles en la AppStore de Apple. La razón principal para volver a crear este tipo de juego es crear un juego mejor y una interfaz de usuario que puede ser controlada en los siguientes dispositivos: teléfonos inteligentes (Apple, Android, Nokia y BlackBerry), tabletas (Samsung y Apple), consolas de juego (Nintendo) y todo tipo de portátiles (Intel / AMD de base).';
$lang['HELP_CREDITS_TITLE'] = 'Créditos';
$lang['HELP_BROWSERS_TITLE'] = 'Navegadores compatibles'; 
$lang['HELP_HARDWARE_TITLE'] = 'Hardware soportado'; 
$lang['HELP_DISCLAIMER_TITLE'] = 'Nota legal'; 
$lang['HELP_DISCLAIMER'] = 'El programa se proporciona TAL CUAL, SIN GARANTÍA DE NINGÚN TIPO, ESTO ES: SIN GARANTÍA DE DISEÑO, COMERCIALIZACIÓN O APTITUD PARA UN PROPÓSITO PARTICULAR.<br/>';

$lang['HELP_CREDITS_TITLE'] = 'Créditos';
$lang['HELP_CREDITS'] = 'Muchas gracias a las siguientes personas y organizaciones que ayudaron a la creación de este juego.';
$lang['HELP_CREDITS_ARCHITECT'] = 'Arquitecto';
$lang['HELP_CREDITS_DEVELOPERS'] = 'Desarrollador';
$lang['HELP_CREDITS_GRAPHICS'] = 'Gráficos & Información';
$lang['HELP_CREDITS_TRANSLATORS'] = 'Traductores';
$lang['HELP_CREDITS_TESTERS'] = 'Testeadores';
$lang['HELP_CREDITS_OTHER'] = 'Otros';
$lang['HELP_CREDITS_OTHER_NOTE'] = 'Y por supuesto a todos los jugadores que enviaron propuestas para mejorar WarQuest. Disfrutad del juego y a divertirse!';

/*
** ------------------
** RANK DATA
** ------------------
*/

$lang['RANK_1'] = "Soldado";
$lang['RANK_2'] = "Soldado de Primera";
$lang['RANK_3'] = "Cabo";
$lang['RANK_4'] = "Cabo Primero";
$lang['RANK_5'] = "Cabo Mayor";
$lang['RANK_6'] = "Sargento";
$lang['RANK_7'] = "Sargento Primero";
$lang['RANK_8'] = "Brigada";
$lang['RANK_9'] = "Subteniente";
$lang['RANK_10'] = "Suboficial Mayor";
$lang['RANK_11'] = "Cadete 1º C.";
$lang['RANK_12'] = "Cadete 2º C.";
$lang['RANK_13'] = "Alférez";
$lang['RANK_14'] = "Teniente";
$lang['RANK_15'] = "Capitán";
$lang['RANK_16'] = "Comandante";
$lang['RANK_17'] = "Teniente Coronel";
$lang['RANK_18'] = "Coronel";
$lang['RANK_19'] = "General de Brigada";
$lang['RANK_20'] = "General de División";
$lang['RANK_21'] = "Teniente General";
$lang['RANK_22'] = "General de Ejército";
$lang['RANK_23'] = "Capitán General";

/*
** ------------------
** COUNTRY NAMES
** ------------------
*/

$landcode = array();

$landcode['ad'] = "Andorra";
$landcode['ae'] = "Emiratos Árabes";
$landcode['af'] = "Afganistán";
$landcode['ag'] = "Antigua y Barbuda";
$landcode['ai'] = "Anguila";
$landcode['al'] = "Albania";
$landcode['am'] = "Armenia";
$landcode['an'] = "Antillas Holandesas";
$landcode['ao'] = "Angola";
$landcode['aq'] = "Antártida";
$landcode['ar'] = "Argentina";
$landcode['as'] = "Samoa Americana";
$landcode['at'] = "Austria";
$landcode['au'] = "Australia";
$landcode['aw'] = "Aruba";
$landcode['ax'] = "Islas Aland";
$landcode['az'] = "Azerbaiyán";
		
$landcode['ba'] = "Bosnia y Herzegovina";
$landcode['bb'] = "Barbados";
$landcode['bd'] = "Bangladesh";
$landcode['be'] = "Bélgica";
$landcode['bf'] = "Burkina Faso";
$landcode['bg'] = "Bulgaria";
$landcode['bh'] = "Bahrein";
$landcode['bi'] = "Burundi";
$landcode['bj'] = "Benin";
$landcode['bm'] = "Bermuda";
$landcode['bn'] = "Brunei Darussalam";	
$landcode['bl'] = "San Bartolomé";
$landcode['bn'] = "Brunei";
$landcode['bo'] = "Bolivia";
$landcode['br'] = "Brasil";
$landcode['bs'] = "Bahamas";
$landcode['bt'] = "Bután";
$landcode['bv'] = "Isla Bouvet";
$landcode['bw'] = "Botswana";
$landcode['by'] = "Belarús";
$landcode['bz'] = "Belice";
	
$landcode['ca'] = "Canadá";
$landcode['cc'] = "Islas Cocos";
$landcode['cf'] = "República Centroafricana";
$landcode['cg'] = "Congo";
$landcode['ch'] = "Suiza";
$landcode['ci'] = "Costa de Marfil";
$landcode['ck'] = "Las Islas Cook";
$landcode['cl'] = "Chile";
$landcode['cm'] = "Cameroon";
$landcode['cn'] = "China";
$landcode['co'] = "Colombia";
$landcode['cr'] = "Costa Rica";
$landcode['cs'] = "Serbia y Montenegro";
$landcode['cu'] = "Cuba";
$landcode['cv'] = "Cavo Verde";
$landcode['cx'] = "Isla de Navidad";
$landcode['cy'] = "Chipre";
$landcode['cz'] = "República Checa";
	
$landcode['de'] = "Alemania";
$landcode['dj'] = "Yibuti";
$landcode['dk'] = "Dinamarca";
$landcode['dm'] = "Dominica";
$landcode['do'] = "República Dominicana";
$landcode['dz'] = "Argelia";
	
$landcode['ec'] = "Ecuador";
$landcode['ee'] = "Estonia";
$landcode['eg'] = "Egipto";
$landcode['eh'] = "Sáhara Occidental";
$landcode['er'] = "Eritrea";
$landcode['es'] = "España";
$landcode['et'] = "Etiopía";
$landcode['eu'] = "Ciberespacio";
	
$landcode['fi'] = "Finlandia";
$landcode['fj'] = "Fiyi";
$landcode['fk'] = "Islas Malvinas";
$landcode['fm'] = "Micronesia";
$landcode['fo'] = "Islas Feroe";
$landcode['fr'] = "Francia";
	
$landcode['ga'] = "Gabón";
$landcode['gb'] = "Reino Unido";
$landcode['gd'] = "Grenada";
$landcode['ge'] = "Georgia";
$landcode['gf'] = "Guayana Francesa";
$landcode['gh'] = "Ghana";
$landcode['gi'] = "Gibraltar";
$landcode['gl'] = "Groenlandia";
$landcode['gm'] = "Gambia";
$landcode['gn'] = "Guinea";
$landcode['gp'] = "Guadalupe";
$landcode['gq'] = "Guinea Ecuatorial";
$landcode['gr'] = "Grecia";
$landcode['gs'] = "Zuid-Georgia";
$landcode['gt'] = "Guatemala";
$landcode['gu'] = "Guam";
$landcode['gw'] = "Guinea-Bissau";
$landcode['gy'] = "Guayana";
	
$landcode['hk'] = "Hong Kong";
$landcode['hm'] = "Islas Heard y McDonald";
$landcode['hn'] = "Honduras";
$landcode['hr'] = "Croacia";
$landcode['ht'] = "Haití";
$landcode['hu'] = "Hungría";
	
$landcode['id'] = "Indonesia";
$landcode['ie'] = "Irlanda";
$landcode['il'] = "Israel";
$landcode['in'] = "India";
$landcode['im'] = "Isla de Man";
$landcode['io'] = "BI Ocean Territory";
$landcode['iq'] = "Irak";
$landcode['ir'] = "Irán";
$landcode['is'] = "Islandia";
$landcode['it'] = "Italia";
	
$landcode['jm'] = "Jamaica";
$landcode['jo'] = "Jordania";
$landcode['jp'] = "Japón";
	
$landcode['ke'] = "Kenia";
$landcode['kg'] = "Kirguistán";
$landcode['kh'] = "Camboya";
$landcode['ki'] = "Kiribati";
$landcode['km'] = "Comores";
$landcode['kn'] = "Saint Kitts en Nevis";
$landcode['kp'] = "Corea del Norte";
$landcode['kr'] = "Corea del Sur";
$landcode['kw'] = "Kuwait";
$landcode['ky'] = "Islas Caimán";
$landcode['kz'] = "Kazajstán";
	
$landcode['la'] = "Laos";
$landcode['lb'] = "Líbano";
$landcode['lc'] = "Santa Lucia";
$landcode['li'] = "Liechtenstein";
$landcode['lk'] = "Sri Lanka";
$landcode['lr'] = "Liberia";
$landcode['ls'] = "Lesoto";
$landcode['lt'] = "Lituania";
$landcode['lu'] = "Luxemburgo";
$landcode['lv'] = "Letonia";
$landcode['ly'] = "Libia";
	
$landcode['ma'] = "Marruecos";
$landcode['mc'] = "Mónaco";
$landcode['md'] = "Moldova";
$landcode['mg'] = "Madagascar";
$landcode['mh'] = "Islas Marshall";
$landcode['mk'] = "Macedonia";
$landcode['ml'] = "Mali";
$landcode['mm'] = "Myanmar";
$landcode['mn'] = "Mongolia";
$landcode['mo'] = "Macao";
$landcode['mp'] = "Islas Marianas del Norte";
$landcode['mq'] = "Martinica";
$landcode['mr'] = "Mauritania";
$landcode['ms'] = "Montserrat";
$landcode['mt'] = "Malta";
$landcode['mu'] = "Mauricio";
$landcode['mv'] = "Maldivas";
$landcode['mw'] = "Malawi";
$landcode['mx'] = "Méjico";
$landcode['my'] = "Malasia";
$landcode['mz'] = "Mozambique";
	
$landcode['na'] = "Namibia";
$landcode['nc'] = "Nueva Caledonia";
$landcode['ne'] = "Nigeria";
$landcode['nf'] = "Islas Norfolk";
$landcode['ng'] = "Níger";
$landcode['ni'] = "Nicaragua";
$landcode['nl'] = "Países Bajos";
$landcode['no'] = "Noruega";
$landcode['np'] = "Nepal";
$landcode['nr'] = "Nauru";
$landcode['nu'] = "Niue";
$landcode['nz'] = "Nueva Zelanda";
	
$landcode['om'] = "Omán";
	
$landcode['pa'] = "Panamá";
$landcode['pe'] = "Perú";
$landcode['pf'] = "Polinesia francesa";
$landcode['pg'] = "Papua Nueva Guinea";
$landcode['ph'] = "Filipinas";
$landcode['pk'] = "Pakistán";
$landcode['pl'] = "Polonia";
$landcode['pm'] = "San Pedro y Miquelón";
$landcode['pn'] = "Pitcairn";
$landcode['pr'] = "Puerto Rico";
$landcode['ps'] = "Palestina";
$landcode['pt'] = "Portugal";
$landcode['pw'] = "Palau";
$landcode['py'] = "Paraguay";
	
$landcode['qa'] = "Qatar";
	
$landcode['re'] = "Reunión";
$landcode['ro'] = "Rumania";
$landcode['ru'] = "Federación de Rusia";
$landcode['rs'] = "Serbia";
$landcode['rw'] = "Ruanda";
	
$landcode['sa'] = "Arabia Saudi";
$landcode['sb'] = "Islas Salomón";
$landcode['sc'] = "Seychelles";
$landcode['sd'] = "Sudán";
$landcode['se'] = "Suecia";
$landcode['sg'] = "Singapur";
$landcode['sh'] = "Santa Helena";
$landcode['si'] = "Eslovenia";
$landcode['sj'] = "Svalbard y Jan Mayen";
$landcode['sk'] = "Eslovaquia";
$landcode['sl'] = "Sierra Leona";
$landcode['sm'] = "San Marino";
$landcode['sn'] = "Senegal";
$landcode['so'] = "Somalia";
$landcode['sr'] = "Suriname";
$landcode['st'] = "Santo Tomé en Príncipe";
$landcode['sv'] = "El Salvador";
$landcode['sy'] = "Siria";
$landcode['sz'] = "Suazilandia";
	
$landcode['tc'] = "Islas Turcas y Caicos";
$landcode['td'] = "Chad";
$landcode['tg'] = "Togo";
$landcode['th'] = "Tailandia";
$landcode['tj'] = "Tayikistán";
$landcode['tk'] = "Tokelau";
$landcode['tl'] = "Timor";
$landcode['tm'] = "Turkmenistán";
$landcode['tn'] = "Túnez";
$landcode['to'] = "Tonga";
$landcode['tr'] = "Turquía";
$landcode['tt'] = "Trinidad y Tobago";
$landcode['tv'] = "Tuvalu";
$landcode['tw'] = "Taiwan";
$landcode['tz'] = "Tanzania";
	
$landcode['ua'] = "Ucrania";
$landcode['ug'] = "Uganda";
$landcode['um'] = "Islas Menores Estados Unidos";
$landcode['us'] = "Estados Unidos";
$landcode['uy'] = "Uruguay";	
$landcode['uz'] = "Uzbekistán";
	
$landcode['va'] = "Ciudad del Vaticano";
$landcode['vc'] = "San Vicente y las Granadinas";
$landcode['ve'] = "Venezuela";
$landcode['vg'] = "Islas Vírgenes, Británicas";
$landcode['vi'] = "Islas Vírgenes, EE.UU.";
$landcode['vn'] = "Vietnam";
$landcode['vu'] = "Vanuatu";
	
$landcode['wf'] = "Wallis and Futuna";
$landcode['ws'] = "Samoa";
	
$landcode['ye'] = "Yemen";
$landcode['yt'] = "Mayotte";
	
$landcode['za'] = "Sudáfrica";
$landcode['zm'] = "Zambia";
$landcode['zw'] = "Zimbabue";
	
/*
** ------------------
** THE END
** ------------------
*/

?>