package nl.warquest.database.entity;
// Generated 18-mrt-2014 21:03:36 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name="bank"
    ,catalog="warquest"
)
public class Bank  implements java.io.Serializable {


     private Integer id;
     private int pid1;
     private int pid2;
     private int bgid;
     private long amount;
     private Date date;
     private long balance;
     private int action;

    public Bank() {
    }

    public Bank(int pid1, int pid2, int bgid, long amount, Date date, long balance, int action) {
       this.pid1 = pid1;
       this.pid2 = pid2;
       this.bgid = bgid;
       this.amount = amount;
       this.date = date;
       this.balance = balance;
       this.action = action;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="pid1", nullable=false)
    public int getPid1() {
        return this.pid1;
    }
    
    public void setPid1(int pid1) {
        this.pid1 = pid1;
    }
    
    @Column(name="pid2", nullable=false)
    public int getPid2() {
        return this.pid2;
    }
    
    public void setPid2(int pid2) {
        this.pid2 = pid2;
    }
    
    @Column(name="bgid", nullable=false)
    public int getBgid() {
        return this.bgid;
    }
    
    public void setBgid(int bgid) {
        this.bgid = bgid;
    }
    
    @Column(name="amount", nullable=false)
    public long getAmount() {
        return this.amount;
    }
    
    public void setAmount(long amount) {
        this.amount = amount;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="balance", nullable=false)
    public long getBalance() {
        return this.balance;
    }
    
    public void setBalance(long balance) {
        this.balance = balance;
    }
    
    @Column(name="action", nullable=false)
    public int getAction() {
        return this.action;
    }
    
    public void setAction(int action) {
        this.action = action;
    }




}


