package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BankGroup generated by hbm2java
 */
@Entity
@Table(name="bank_group"
    ,catalog="warquest"
)
public class BankGroup  implements java.io.Serializable {


     private int bgid;

    public BankGroup() {
    }

    public BankGroup(int bgid) {
       this.bgid = bgid;
    }
   
     @Id 
    
    @Column(name="bgid", nullable=false)
    public int getBgid() {
        return this.bgid;
    }
    
    public void setBgid(int bgid) {
        this.bgid = bgid;
    }




}


