package nl.warquest.database.entity;
// Generated 18-mrt-2014 21:03:36 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BountyAward generated by hbm2java
 */
@Entity
@Table(name="bounty_award"
    ,catalog="warquest"
)
public class BountyAward  implements java.io.Serializable {


     private int id;
     private int amount;
     private int ep;

    public BountyAward() {
    }

    public BountyAward(int id, int amount, int ep) {
       this.id = id;
       this.amount = amount;
       this.ep = ep;
    }
   
     @Id 
    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="amount", nullable=false)
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    
    @Column(name="ep", nullable=false)
    public int getEp() {
        return this.ep;
    }
    
    public void setEp(int ep) {
        this.ep = ep;
    }




}


