package nl.warquest.database.entity;
// Generated 18-mrt-2014 21:03:36 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chat generated by hbm2java
 */
@Entity
@Table(name="chat"
    ,catalog="warquest"
)
public class Chat  implements java.io.Serializable {


     private Integer id;
     private int pid1;
     private int pid2;
     private Date date;
     private String message;

    public Chat() {
    }

    public Chat(int pid1, int pid2, Date date, String message) {
       this.pid1 = pid1;
       this.pid2 = pid2;
       this.date = date;
       this.message = message;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="pid1", nullable=false)
    public int getPid1() {
        return this.pid1;
    }
    
    public void setPid1(int pid1) {
        this.pid1 = pid1;
    }
    
    @Column(name="pid2", nullable=false)
    public int getPid2() {
        return this.pid2;
    }
    
    public void setPid2(int pid2) {
        this.pid2 = pid2;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="message", nullable=false, length=400)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


