package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClanBank generated by hbm2java
 */
@Entity
@Table(name="clan_bank"
    ,catalog="warquest"
)
public class ClanBank  implements java.io.Serializable {


     private Integer cbid;
     private int cid;
     private int pid;
     private long amount;
     private long balance;
     private int action;
     private Date date;

    public ClanBank() {
    }

    public ClanBank(int cid, int pid, long amount, long balance, int action, Date date) {
       this.cid = cid;
       this.pid = pid;
       this.amount = amount;
       this.balance = balance;
       this.action = action;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="cbid", nullable=false)
    public Integer getCbid() {
        return this.cbid;
    }
    
    public void setCbid(Integer cbid) {
        this.cbid = cbid;
    }
    
    @Column(name="cid", nullable=false)
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }
    
    @Column(name="pid", nullable=false)
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    
    @Column(name="amount", nullable=false)
    public long getAmount() {
        return this.amount;
    }
    
    public void setAmount(long amount) {
        this.amount = amount;
    }
    
    @Column(name="balance", nullable=false)
    public long getBalance() {
        return this.balance;
    }
    
    public void setBalance(long balance) {
        this.balance = balance;
    }
    
    @Column(name="action", nullable=false)
    public int getAction() {
        return this.action;
    }
    
    public void setAction(int action) {
        this.action = action;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


