package nl.warquest.database.entity;
// Generated 18-mrt-2014 21:03:36 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Level generated by hbm2java
 */
@Entity
@Table(name="level"
    ,catalog="warquest"
)
public class Level  implements java.io.Serializable {


     private int lid;
     private int experience;
     private int unitLost;
     private int buildingLost;
     private int planet;

    public Level() {
    }

    public Level(int lid, int experience, int unitLost, int buildingLost, int planet) {
       this.lid = lid;
       this.experience = experience;
       this.unitLost = unitLost;
       this.buildingLost = buildingLost;
       this.planet = planet;
    }
   
     @Id 
    
    @Column(name="lid", nullable=false)
    public int getLid() {
        return this.lid;
    }
    
    public void setLid(int lid) {
        this.lid = lid;
    }
    
    @Column(name="experience", nullable=false)
    public int getExperience() {
        return this.experience;
    }
    
    public void setExperience(int experience) {
        this.experience = experience;
    }
    
    @Column(name="unit_lost", nullable=false)
    public int getUnitLost() {
        return this.unitLost;
    }
    
    public void setUnitLost(int unitLost) {
        this.unitLost = unitLost;
    }
    
    @Column(name="building_lost", nullable=false)
    public int getBuildingLost() {
        return this.buildingLost;
    }
    
    public void setBuildingLost(int buildingLost) {
        this.buildingLost = buildingLost;
    }
    
    @Column(name="planet", nullable=false)
    public int getPlanet() {
        return this.planet;
    }
    
    public void setPlanet(int planet) {
        this.planet = planet;
    }




}


