package nl.warquest.database.entity;
// Generated 18-mrt-2014 21:03:36 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MissionUnitId generated by hbm2java
 */
@Embeddable
public class MissionUnitId  implements java.io.Serializable {


     private int mid;
     private int uid;

    public MissionUnitId() {
    }

    public MissionUnitId(int mid, int uid) {
       this.mid = mid;
       this.uid = uid;
    }
   

    @Column(name="mid", nullable=false)
    public int getMid() {
        return this.mid;
    }
    
    public void setMid(int mid) {
        this.mid = mid;
    }

    @Column(name="uid", nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }




}


