package nl.warquest.database.entity;
// Generated 18-mrt-2014 21:03:36 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlayerPlayerId generated by hbm2java
 */
@Embeddable
public class PlayerPlayerId  implements java.io.Serializable {


     private int pid1;
     private int pid2;

    public PlayerPlayerId() {
    }

    public PlayerPlayerId(int pid1, int pid2) {
       this.pid1 = pid1;
       this.pid2 = pid2;
    }
   

    @Column(name="pid1", nullable=false)
    public int getPid1() {
        return this.pid1;
    }
    
    public void setPid1(int pid1) {
        this.pid1 = pid1;
    }

    @Column(name="pid2", nullable=false)
    public int getPid2() {
        return this.pid2;
    }
    
    public void setPid2(int pid2) {
        this.pid2 = pid2;
    }




}


