package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlayerMissionId generated by hbm2java
 */
@Embeddable
public class PlayerMissionId  implements java.io.Serializable {


     private int pid;
     private int mid;

    public PlayerMissionId() {
    }

    public PlayerMissionId(int pid, int mid) {
       this.pid = pid;
       this.mid = mid;
    }
   

    @Column(name="pid", nullable=false)
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }

    @Column(name="mid", nullable=false)
    public int getMid() {
        return this.mid;
    }
    
    public void setMid(int mid) {
        this.mid = mid;
    }




}


