package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlayerPollId generated by hbm2java
 */
@Embeddable
public class PlayerPollId  implements java.io.Serializable {


     private int pid;
     private int pollId;

    public PlayerPollId() {
    }

    public PlayerPollId(int pid, int pollId) {
       this.pid = pid;
       this.pollId = pollId;
    }
   

    @Column(name="pid", nullable=false)
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }

    @Column(name="poll_id", nullable=false)
    public int getPollId() {
        return this.pollId;
    }
    
    public void setPollId(int pollId) {
        this.pollId = pollId;
    }




}


