package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlayerStockId generated by hbm2java
 */
@Embeddable
public class PlayerStockId  implements java.io.Serializable {


     private int pid;
     private int sid;

    public PlayerStockId() {
    }

    public PlayerStockId(int pid, int sid) {
       this.pid = pid;
       this.sid = sid;
    }
   

    @Column(name="pid", nullable=false)
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }

    @Column(name="sid", nullable=false)
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }




}


