package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PlayerUnit generated by hbm2java
 */
@Entity
@Table(name="player_unit"
    ,catalog="warquest"
)
public class PlayerUnit  implements java.io.Serializable {


     private PlayerUnitId id;
     private int amount;

    public PlayerUnit() {
    }

    public PlayerUnit(PlayerUnitId id, int amount) {
       this.id = id;
       this.amount = amount;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="pid", column=@Column(name="pid", nullable=false) ), 
        @AttributeOverride(name="uid", column=@Column(name="uid", nullable=false) ) } )
    public PlayerUnitId getId() {
        return this.id;
    }
    
    public void setId(PlayerUnitId id) {
        this.id = id;
    }
    
    @Column(name="amount", nullable=false)
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }




}


