package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PlayerStock generated by hbm2java
 */
@Entity
@Table(name="player_stock"
    ,catalog="warquest"
)
public class PlayerStock  implements java.io.Serializable {


     private PlayerStockId id;
     private long amount;
     private long cost;

    public PlayerStock() {
    }

    public PlayerStock(PlayerStockId id, long amount, long cost) {
       this.id = id;
       this.amount = amount;
       this.cost = cost;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="pid", column=@Column(name="pid", nullable=false) ), 
        @AttributeOverride(name="sid", column=@Column(name="sid", nullable=false) ) } )
    public PlayerStockId getId() {
        return this.id;
    }
    
    public void setId(PlayerStockId id) {
        this.id = id;
    }
    
    @Column(name="amount", nullable=false)
    public long getAmount() {
        return this.amount;
    }
    
    public void setAmount(long amount) {
        this.amount = amount;
    }
    
    @Column(name="cost", nullable=false)
    public long getCost() {
        return this.cost;
    }
    
    public void setCost(long cost) {
        this.cost = cost;
    }




}


