package nl.warquest.database.entity;
// Generated 18-mrt-2014 21:03:36 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StockGroup generated by hbm2java
 */
@Entity
@Table(name="stock_group"
    ,catalog="warquest"
)
public class StockGroup  implements java.io.Serializable {


     private int sgid;

    public StockGroup() {
    }

    public StockGroup(int sgid) {
       this.sgid = sgid;
    }
   
     @Id 
    
    @Column(name="sgid", nullable=false)
    public int getSgid() {
        return this.sgid;
    }
    
    public void setSgid(int sgid) {
        this.sgid = sgid;
    }




}


