package nl.warquest.database.entity;
// Generated Mar 18, 2014 8:01:37 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewsId generated by hbm2java
 */
@Embeddable
public class ViewsId  implements java.io.Serializable {


     private int mid;
     private int sid;
     private int ssid;
     private int eid;

    public ViewsId() {
    }

    public ViewsId(int mid, int sid, int ssid, int eid) {
       this.mid = mid;
       this.sid = sid;
       this.ssid = ssid;
       this.eid = eid;
    }
   

    @Column(name="mid", nullable=false)
    public int getMid() {
        return this.mid;
    }
    
    public void setMid(int mid) {
        this.mid = mid;
    }

    @Column(name="sid", nullable=false)
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }

    @Column(name="ssid", nullable=false)
    public int getSsid() {
        return this.ssid;
    }
    
    public void setSsid(int ssid) {
        this.ssid = ssid;
    }

    @Column(name="eid", nullable=false)
    public int getEid() {
        return this.eid;
    }
    
    public void setEid(int eid) {
        this.eid = eid;
    }




}


