<?php

/* 
**  ========
**  WARQUEST
**  ========
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  All copyrights reserved (c) 2008-2014 PlaatSoft
*/

/*
** ---------------------------------------------------------------- 
** VARIABLE CONFIG ITEMS
** ---------------------------------------------------------------- 
*/

/* Enable MySQL (else PostgreSQL) */
define('MYSQL', 1);

/* Enable debug mode -> If enabled SQL is logged */
define('DEBUG', 1);

/* Database settings */
$config["dbuser"]							= "warquest";
$config["dbpass"]							= "warquest";
$config["dbname"]							= "warquest";
$config["dbhost"]							= "127.0.0.1";

/*
** ---------------------------------------------------------------- 
** THE END
** ----------------------------------------------------------------
*/

?>
