<?php

/* 
**  ========
**  WARQUEST
**  ========
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  All copyrights reserved (c) 2008-2014 PlaatSoft
*/

/*
** ---------------------------------------------------------------- 
** VARIABLE CONFIG ITEMS
** ---------------------------------------------------------------- 
*/

/* Database settings */
$config["dbuser"]			= "test";
$config["dbpass"]			= "test";
$config["dbname"]			= "test";
$config["dbhost"]			= "127.0.0.1";

/*
** ---------------------------------------------------------------- 
** THE END
** ----------------------------------------------------------------
*/

?>
