<?php

/* 
**  ========
**  WARQUEST
**  ========
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  All copyrights reserved (c) 2008-2013 PlaatSoft
*/

$united = '

friends and fellow players this is just a suggestion which was accepted by many top players and 
admin as well. In case any doubts or better suggestion please comment here after reading the 
entire rules	

How about a team of elite generals (us) who are above level 250 Join together and fight against 
a new alien threat invading our solar sytem It would stop silly and boring fights among top guns 
of the game. Ok let me explain you game scheme 

The battle over the goldilock region (which actually means region with in the asteroid belt 
scientifically ) has been happening for over five years Now in 2025( as per game time ) humans 
began to venture beyond the asteroid belt for their supremacy As they begin to invade they come 
across an alien race which is even more thirsty for war and even more strong	It is upto the
warlords ( generals ) to resist their invasion further into the asteroid belt So they form the
UNION which consist of the best war generals ( top fifty players ) and with their combined 
forces of moon, mars and asteroids, they begin a war against the unkown but deadly alien race 
This forms the base story	

Rules of game : 
Players should be atleast at level 250 to play the new feature Please note that one can 
simultaneously play the asteroid game as well as this feature after reaching the level 200	

1)members in the UNION group doesnot mean they are stictly allies They may or may not be as allies.
WVDP: Compliant!

2) players cannot attack other humans in the UNION play ( which is just another level like earth 
moon mars and asteroids ) 
WVDP: Compliant

3) Players will have missions ( like base capture and rescue of captured human ships) 
Note: the same mission is played mutually by all players	this means that when a player plays a 
mission he gets his xp but the mission is single and all the players play the same mission and 
when a player does a mission once ,1% of it is completed and when 100% is reached the mission 
is completed Example : ecg plays a mission five times and 5% of it is completed and if bizkit 
plays the same mission 5 times another 5% is added	Example:As a result 10% of the mission is completed.
WVDP: Compliant

4)Battles mode is possible as usual but only with aliens and aliens are strong unlike present bots 

5)Players will not get money in UNION mode play. Instead he gets loot of gold and other precious 
metals in both battles and missions.
WVDP: Rejected! Income will be based on money!

6)player can sell this loot of gold and other precious metals in earth for money. They can be sold 
in the earth market and make money to buy more units and buildings
WVDP: Rejected. See rule 5.

7)ANOTHER MAJOR RULE CHANGE in UNION mode play is that new feature called R&D BUILDINGS which makes 
it the only way to create new technology to build units against aliens unlike in other modes where
 new units are unlocked after each level These R&D buildings are just like energy these buildings 
 generate technology steadily and just like xp build up teachnology grows and for each level 
 crossed we can unlock new units 
 
8) we can use moon,mars and asteroid units together in UNION MODE But we cannot use UNION units in 
other modes	

9) level 299 is the last level in UNION MODE and as usual 10000 xp for each level up 
WVDP: Compliant

10) level 299 ends with our recapture of solar system.
WVDP: Compliant

11) player with highest xp and win lost ratio remain on top as usual 	
WVDP: Complaint

Hope these rules are enough for this next mode Admin please reply Ecg ,biz and others please 
respond to this Any doubts will be cleared';

$notes = '

<span class="subparagraph2">06-11-2013</span><br/>
<i>Game Server v5.7</i><br/>
- Increase maximum level to 279.<br/>
- Disable sun features.</br>
- Improve database optimize. (Admin mode).<br/>
- Added backup cron  job.</br>
- Update jquery to 10.2.0.</br>
- Update jquery-ui to 10.3.0.</br>
- update jquery-css smooth to 10.3.0.</br>
- Added server php source code to google code.<br></br>

<i>General</i><br/>
- Please visit www.gravatar.com to upload a player image.<br/><br/>

<span class="subparagraph2">07-02-2013</span><br/>
<i>Game Server v5.6</i><br/>
- Fixed bug in stock exchange buy functionality.<br/>
- Increase maximum level to 275.<br/>
- Updated copyright banner.<br/>
- Added ban user optional. To lock cheater account (Admin mode).<br/><br/>

<span class="subparagraph2">14-07-2012</span><br/>
<i>Game Server v5.5</i><br/>
- Added spanish translation. Thanks Algarobo!<br/>
- Added romanian translation. Thanks Prepa!<br/>
- Added eight extra levels<br/><br/>

<span class="subparagraph2">07-06-2012</span><br/>
<i>Game Server v5.4</i><br/>
- Added country selection box to settings page.<br/>
- Space character(s) in nickname is not allowed anymore!<br/>
- Now setting a bounty is rewarded with one expercience point.<br/>
- Added sun planet (more is coming soon)<br>
- Added two extra levels.<br/>
- Added total hourly income information to player profile page.<br/>
- Added planet mission bonus information to Help page.<br/>
- Added option to switch from MySql to PostGreSQL database.<br/>
- Added query counter information in footer.<br/>
- Added loosely coupled database layer.<br/>
- Added WarQuest for Linux hyperlink on login page.<br/>
- Robots now random sell units / buildings. Make them less strong.<br/>
- Improve Latest forum query on home page. 10 times faster :)<br/>
- Improve two cron jobs for better performance.<br/>
- Bug fix: Citizens are now showed again in player profile.<br/>
- Bug fix: Bots counter attack cash win is limited to max 1.5 billion.<br/>
- Bug fix: Mars bonus is now 999 billion.<br/><br/>

<i>Linux Client v1.0</i><br/>
- First release of WarQuest linux client.<br/>
- Use QT library 4.8.1 for Linux as engine.<br/>
- The app was build with QtCreator v2.4.1<br/>
- Released app on Ubuntu software center.<br/><br/>


<span class="subparagraph2">20-05-2012</span><br/>
<i>Game Server v5.3</i><br/>
- Activated improved holiday mode.<br/>
- Added following option to settinng page:<br/>
&nbsp;&nbsp;- Enable allies in battle and bounty hunting list.<br/>
&nbsp;&nbsp;- Disable battle bot news.<br/>
- Improve unit and building menu</br>
- Disable page reload after battle force selected</br>
- Improve forum performance.<br/>
- Refactor page handler events.<br/>
- Refactor popup messages.<br/>
- Refactor menu item.<br/>
- Refactor post parameter handler.<br/>
- Planet mission complet bonus is now automatic added!<br/>
- Add extra database index for better performance.<br/>
- Improve bad word filter!<br/>
- Limit maximum battle cash win.<br/>
- Bug fix: Increase alliance size above max with back button is fixed!<br/>
- Bug fix: Minor level experience range updated!<br/>
- Bug fix: Army defense profile overview mismatch resolved.<br/>
- Bug fix: Exploit with back button on building / unit page fixed.<br/><br/>


<span class="subparagraph2">22-04-2012</span><br/>
<i>Game Server v5.2</i><br/>
- Now manage warquest wishlist on www.plaatsoft.nl/scrumboard<br/> 
- Bank transaction log is now cleared after 30 days.<br/>
- Added basic bad words filter to forum.<br/>
- Disabled holiday mode because of heavy abuse.<br/>
- Update bounty award scheme.<br/>
- Merge earth soldiers units in to earth Cavalry units.<br/>
- Added surrender flag functionality to Home - News page.<br/>
- German translation update. Thanks TestBoy!<br/>
- Added minimal trade timer information to trade page.<br/>
- Bug fix: Improve bank interest cron job performance with factor 10.<br/>
- Bug fix: PDF report is now working again.<br/>
- Bug fix: Home - News contain now correct information for all sitations.<br/><br/>


<span class="subparagraph2">04-04-2012</span><br/>
<i>Game Server v5.1</i><br/>
- Image directory structure updated.<br/>
- Improve player profile page (Admin mode)<br/>
- Cache data layer added for better database performance.<br/>
- Added account reset (Home - Settings) feature.<br/>
- Added trade points (Home - Trade) functionality.<br/>
&nbsp;&nbsp;- Donations are now rewarded with trade points.<br/>
&nbsp;&nbsp;- Default health, energy, ammo timer value +/- 10% increased.<br/>
- Remove Login - Manual page.<br/>
- Improve restore notifications.<br/>
- Added ten more battle awards.<br/>
- Added amount selection to skill point page.<br/>
- Bug fix: Level 259 battle range corrected!<br/>
- Bug fix: Level 249 now needs 10.000 expercience points.<br/>
- Bug fix: Fix some small graphical issues.<br/>
- Bug fix: Soldier attack force option disabled again in battle area.<br/><br/>

<span class="subparagraph2">24-03-2012</span><br/>
<i>Game Server v5.0</i><br/>
- Resync levels<br/>
&nbsp;&nbsp;- Earth levels are now 0 - 99.<br/>
&nbsp;&nbsp;- Moon levels are now 100 - 149.<br/>
&nbsp;&nbsp;- Mars levels are now 150 - 199.<br/>
&nbsp;&nbsp;- Asteroid levels are now 200 - 249.<br/>
- Added italian translation. Thanks ZennCore.<br/>
- Added 0.75 day cease fire option.<br/>
- Maximun unit amount per type increase to 5.000.<br/>
- Battle news (Home - News) contains now only last two days.<br/>
- Added travel option to alliance and help page.<br/>
- Added player profile building discount and maintenance detail page.<br/>
- Breaking news content is now always english.<br/>
- Default sorting alliance invite is change to last active on top.<br/>
- Bug fix: Cash flow detail pages now support planet switch.<br/>
- Bug fix: Player profile detail page - planet switch is now working correct.<br/><br/>


<span class="subparagraph2">15-03-2012</span><br/>
<i>Game Server v4.9</i><br/>
- Improve planet navigation.<br/>
&nbsp;&nbsp;- Planet icon is now the travel button.<br/>
&nbsp;&nbsp;- Travel option added to mission, battle and units page.<br/>
&nbsp;&nbsp;- Travel option added to buildings and player profile page.<br/>
&nbsp;&nbsp;- Remove travel link on lower part of home page.<br/>
- Added asteroid belt. Conquer the new frontier!<br/>
&nbsp;&nbsp;- Added 72 Asteroid missions.<br/>
&nbsp;&nbsp;- Added 49 Asteroid building types.<br/>
&nbsp;&nbsp;- Added 40 Asteroid weapon unit types.<br/>
&nbsp;&nbsp;- Asteroid features start at level 255.<br/>
&nbsp;&nbsp;- Added level 275 up to 299.<br/>
- Update Mars unit names.<br/>
- Building lost configuration moved to database.<br/>
- Improve english translation. Thanks zenncorE<br/>
- Move building configuration complete to database.<br/>
- Added cease fire period of one day.<br/>
- Added holiday mode (Home -> Restore).<br/>
- Bug fix: Help - Level page. First expercience entry now correct.<br/>
- Bug fix: Cooldown period after cease fire and holiday restored.<br/><br/>


<span class="subparagraph2">10-03-2012</span><br/>
<i>Game Server v4.8</i><br/>
- Added planet Mars. Conquer the new frontier!<br/>
&nbsp;&nbsp;- Added 72 Mars missions.<br/>
&nbsp;&nbsp;- Added 49 Mars building types.<br/>
&nbsp;&nbsp;- Added 40 Mars weapon unit types.<br/>
&nbsp;&nbsp;- Mars features start at level 200.<br/>
&nbsp;&nbsp;- Added level 222 up to 275.<br/>
- Added german translation. Thanks TestBoy<br/>
- Improve dutch translation. Thanks wplaat<br/>
- Added battle range information to lower part of battle page.<br/>
- Updated WarQuest for symbian login banner hyperlink.<br/>
- Moon features start level moved from 150 to 125.<br/>
- Player profile page shows now general and planet specific info.<br/>
- Update moon building and unit images.<br/>
- Improve audit trail.<br/>
- Bug fix: Fix several bugs related to new mars features.<br/><br/>


<span class="subparagraph2">01-03-2012</span><br/>
<i>Game Server v4.7</i><br/>
- Added custom cease fire period.<br/>
- Added level overview page (Help > Levels)<br/>
- Added personal stocklist (Money > StockExchange > Personal)<br/>
- Added stock sell transaction fee.<br/>
- Added more online help for new players.<br>
- Improve Player > Message page layout.<br/>
- Now Player > News contain information up to 15 days old.<br/>
- Added surrender flag feature to Battle > Bounty hunting page.<br/>
- Added bounty action to player profile page.<br/>
- Each vote is rewarded with 10 experience points.<br/>
- Added WarQuest for Symbian banner to login page.<br/>
- Now you can fight players also from your own country.<br/>
- Optimise game engine for Symbian Mobile devices.<br/>
- Bounty hunting skill points loss reduced with 50%<br/>
- Improve forum - Poll sorting.<br/>
- Added symbian platform detection.<br/>
- Improve technical info page (Admin mode)<br/>
- Bug fix: Bounting Hunting range at level 220 is now working fine.<br/><br/>

<i>Windows Client v1.4</i><br/>
- Added intro screen.<br/>
- Use QT library 4.7.4 for Windows as engine.<br/>
- The app was build with QtCreator v2.4.1<br/>
- Released app on freewarefiles.com<br/><br/>

<i>Symbian Client v1.0</i><br/>
- Added intro screen<br/>
- Added automatic sign on<br/>
- Added automatic screen resolution detection.<br/>
- Added game screen based on QtWebKit.<br/>
- Use QT library 4.7.3 for Symbian as engine.<br/>
- The app was build with QtCreator v2.4.1<br/>
- Released app on OviStore.<br/><br/>


<span class="subparagraph2">15-02-2012</span><br/>
<i>Game Server v4.6</i><br/>
- Added twitter account setting to settings page.<br/>
- Show last player tweet on player profile.<br/>
- Stock amount is now a free input field with suggestion box.<br/>
- Improve unit loot functionality.<br/>
- Disable restore / repair notification in main menu.<br/>
- Increase all spacecrafts defense strength.<br/>
- Moon energy building price decrease with factor 10.<br/>
- Warrior hourly cost increase. They were to cheap.<br/>
- Added 12 moon discount buildings.<br/>
- Added 10 moon maintenance buildings.<br/>
- Added "Warrior 11" and "Galaxy Explorer II" moon unit.<br/>
- Added "No region for rebellion available" detection.<br/>
- Remove some english typos.<br/>
- Bounty hunting player list functionality changed:<br/>
&nbsp;&nbsp;- Players under level 150 see only players under level 150.<br/>
&nbsp;&nbsp;- Players from level 150 see only players from level 150.<br/>
- Added setting "Enable oldest battle player on top at battle list"<br/>
- Bug fix: Improve header for players in level 220.<br/>
- Bug fix: Opening chat does not take you back to earth anymore.<br/><br/>


<span class="subparagraph2">09-02-2012</span><br/>
<i>Game Server v4.5</i><br/>
- Battle page contain now random player selection.<br/>
- Added rebellion rise and bounty set awards.<br/>
- Updated home award section and help award page.<br/>
- Added more cyberspace players in higher levels.<br/>
- Added five more battle awards.<br/>
- Improve player search (Admin mode)<br/>
- Integrated Twitter functionality. (Admin mode)<br/>
- Change battle range algoritme. Now more players are in range!<br/>
- Added forum topic search.<br/>
- Cron job functionality:<br/>
&nbsp;&nbsp;- Added "Sell some units of players with negative hourly income".<br/>
&nbsp;&nbsp;- Optimize some queries for better performance.<br/>
- Health restore timer inactive period decreased to 5 minutes.<br/>
- Improve cyberspace robots intelligence:<br/>
&nbsp;&nbsp;- Robot get a live when attacked.<br>
&nbsp;&nbsp;- Robot buy automatic new units and buildings.<br/>
&nbsp;&nbsp;- Robot income period is extended with 24 hours after an attack.<br/>
&nbsp;&nbsp;- Robot trade-in received skill points.<br>
&nbsp;&nbsp;- Robot withdraw automatic money for bank accounts.<br>
&nbsp;&nbsp;- Robot counter attack smart. So be aware! :)<br/>
- Bug fix: Player battle news contain now always correct army type.<br/>
- Bug fix: Rebalance some defense values of moon units.<br/>
- Bug fix: Battle loot is now working correct!<br/>
- Bug fix: Ranking place on home is now always correct.<br/>
- Bug fix: Remove typo from home screen.<br/>
- Bug fix: Remove double player profile on chat page.<br/>
- Bug fix: Rebellion on moon popup information is now right.<br/><br/>



<span class="subparagraph2">03-02-2012</span><br/>

<i>Game Server v4.4</i><br/>
- Improve english translation. Thanks Mongoose.<br/>
- Added 4 moon explorers defense buildings.<br/>
- Improve registration functionality.<br/>
- Added new leaderboard ranking sort ((experience/30)+won-lost)<br/>
- Added loot feature to battle.<br/>
- Added functionality to disabled an old poll.<br/>
- Bounty rules of engagement changed. Old situation restored.<br/>
- Added WarQuest One Year Party functionality.<br/>
- Visit WarQuest on 8 february 2012 to received a present!<br/>
- Bug fix: Skill points counter in submenu is now working fine again.<br/>
- Bug fix: Notification in Main Menu is not working correct.<br/><br/>

<i>Android Client v2.6</i><br/>
- Improve about screen.<br/>
- Released app on Android Market.<br/><br/>


<span class="subparagraph2">25-01-2012</span><br/>

<i>Game Server v4.3</i><br/>
- Added basic chatroom<br/>
- Standardized player name format (name + country flag).<br/>
- Added 12 explorer moon units (same skills as espionage units).</br>
- Bounty hunting is now more restricted. See help instructions.<br/>
- Refactor menu. Now forum is available in main menu.<br/>
- After the earth the moon can be now conquered.<br/>
- Added 37 moon units, 35 moon buildings and 72 moon missions.<br/>
- Added "Travel to Moon" link on home page.<br/>
- Player > Profile shows information about your current location.<br/>
- Force strength is now realtime calculated.<br/>
- Added one to one relation between units and army battle forces.<br/>
- Optimize overall performance.<br/>
- Bank page layout optimized.<br/>
- Disable set bounty on cyberspace players.<br/>
- Moon map is now clickable.<br/>
- Bug fix: Player with only space characters in nickname can now be selected.<br/>
- Bug fix: Now classified opponent profile is working again.<br/>
- Bug fix: Resolve some small graphical issues.<br/><br/>


<span class="subparagraph2">17-01-2012</span><br/>

<i>Game Server v4.2</i><br/>
- Redesign Home > Setting page.<br/>
- Added forum message sort option to setting page.<br/>
- Added 8 hour cooldown period after using cease fire option.<br/>
- Added bounty set and receive counter to player profile.<br/>
- Added Cease Fire information to player profile.<br/>
- Added basic poll (Alliance > Polls) functionality.<br/>
- Added database tables optimize action (Admin mode)<br/>
- Improve member search functionality (Admin mode)<br/>
- Added five extra battle won awards.<br/>
- Added country flag to Forum - Topic - Messages.<br/>
- Increase battle and bounty hunting player list to max. 30 entries.<br/>
- Bug fix: Optimize some queries for better performance.<br/>
- Bug fix: Mission loot is now mission level related.<br/><br/>


<span class="subparagraph2">12-01-2012</span><br/>

<i>Game Server v4.1</i><br/>
- Split bounty / restore & repair popup configuration.<br/>
- Added more cyberspace robots to have more fun!.<br/>
- Added facebook subpage to login page.<br/>
- Created www.facebook.com/WarQuest page.<br/>
- Improve login page.<br/>
- Added rebellion peace restore (Home > Restore) functionality.<br/>
- Added optional Rebel Condition (RC) to banner.<br>
- Added rebellion chance information to espionage battle page.<br/>
- Added breaking news information to login page.<br/>
- Added technical environment settings page. (Admin Mode)<br/>
- Added worldmap to mission complete message.<br/> 
- Espionage rob bank selection improved.<br/>
- Bug fix: Create cyberplayer is now working correct.<br/>
- Bug fix: Reload casino cheating action.<br/>
- Bug fix: New client version detection improved.<br/>
- Bug fix: Remove some typos in unit names.<br/><br/>



<span class="subparagraph2">05-01-2012</span><br/>

<i>Game Server v4.0</i><br/>
- Improve english translation. Thanks Mongoose!<br/>
- Redesign mission functionality:<br/>
&nbsp;&nbsp- Worldmap is now split in 64 regions with can be conquered.<br/>
&nbsp;&nbsp- Each conquered continent will increase your hourly income.<br/>
&nbsp;&nbsp- Added Continent Income Overview page.<br/>
&nbsp;&nbsp- Attack opponents with espionage to invoke rebellion by opponent.<br/>
&nbsp;&nbsp- Region rebellion result in postpone continent income.<br/>
&nbsp;&nbsp- Mission names renamed!<br/>
&nbsp;&nbsp- Added worldmap region color indication:<br/>
&nbsp;&nbsp&nbsp;&nbsp- Green = Region 0% conquered.<br/>
&nbsp;&nbsp&nbsp;&nbsp- Yellow = Region 33% conquered.<br/>
&nbsp;&nbsp&nbsp;&nbsp- Purple = Region 66% conquered.<br/>
&nbsp;&nbsp&nbsp;&nbsp- Orange = Region 100% conquered.<br/>
&nbsp;&nbsp&nbsp;&nbsp- Red = Rebellion in region. Region must be reconquered.<br/>
- Added casino played game statistics.<br/>
- Added optional lastest forum post on home overview page.<br/>
- Added more win chance to slotmachine.<br/>
- Added five extra battle won awards.<br/>
- Bug fix: Mission loot contain now no citizens anymore.<br/>
- Bug fix: Remove some typo\'s in Help > Instructions.<br/>
- Bug fix: Bounty Hunting battle SQL error fixed.<br/>
- Bug fix: Worldmap is now not clickable anymore for level 0.<br/><br/>

<i>Android Client v2.5</i><br/>
- Improve about box.<br/>
- Released app on Android Market.<br/><br/>



<span class="subparagraph2">31-12-2011</span><br/>

<i>Game Server v3.9</i><br/>
- Improve Help > Instructions page content.<br/>
- Battle > BountyHunting list is not level constrained anymore.<br/>
- Added Happy New Year banner<br/>
- Added star background with firework animation.<br/>
- Improve change username and/or password functionality.<br/>
- Added optional units condition (UC) & buildings condition (BC) in banner.<br/>
- Added slotmachine with help page to casino.<br/>
- Disabled christmas banner on Home page.<br/>
- Improve mail notification in banner.<br/>
- Added unit & building repair notification.<br/>
- Bug fix: Fix cheating bug in casino games.<br/>
- Bug fix: Remove typo in home intro text.<br/>
- Bug fix: Prevent negative units/buildings condition value.<br/><br/>



<span class="subparagraph2">24-12-2011</span><br/>

<i>Game Server v3.8</i><br/>
- Added 9 more battle awards.<br/>
- Added confirmation popup functionality:<br/>
&nbsp;&nbsp- Enable popup on the Page > Settings page.<br/>	
&nbsp;&nbsp- Added popup to restore & repair actions.<br/>
&nbsp;&nbsp- Added popup to set bounty action.<br/>
- Added Help > Statistics page.<br>
- Merge Help > About and Credit page.<br>
- Added cease fire functionality. See Home > Restore page.<br>
- Added unit and building speedbar for fast amount selection.<br/>
- Attack & defense skillpoints strength depend now on player level.<br/>
- Added sleeping smiley. Used for feature request on hold.<br/>
- Adapted losing money color in Player > News page.<br/>
- Added cash bonus:<br/>
&nbsp;&nbsp- when battle opponent surrender temporary.<br/>
&nbsp;&nbsp- when battle awards is won.<br/>
&nbsp;&nbsp- when level is cleared.<br/>
- Added pending alliance request is cleared after 2 days.<br/>
- Added more the 350 extra cyber robot players.<br/>
- Added Health, Energy and Ammo countdown timer.<br/>
- Added contact areas on mission Worldmap.<br/>
- Added christmas background with falling snowflakes animation.<br/>
- Bug fix: Army attack & defense strength calculate is now correct.<br/><br/>

<i>Android Client v2.4</i><br/>
- Maintenance release.<br/>
- Released app on Android Market.<br/><br/>



<span class="subparagraph2">16-12-2011</span><br/>

<i>Game Server v3.7</i><br/>
- Added Player > Restore page:<br/>
&nbsp;&nbsp- Energy and Ammo can now be restored directly.<br/>
&nbsp;&nbsp- This option can only be used once every 24 hours.<br/>
&nbsp;&nbsp- Units and buildings are damaged during battles.<br/>
&nbsp;&nbsp- Units and buildings can now be repaired directly.<br/>
- Improve Forum:<br>
&nbsp;&nbsp;- Topic sorting improved. Newest topic/message is now on top.<br/>
&nbsp;&nbsp;- Added National Communities Forum.<br/>
&nbsp;&nbsp;- Added paginating to Topic page.<br/>
&nbsp;&nbsp;- Added topic description in message section.<br/>
&nbsp;&nbsp;- Forum image is now clickable.<br/>
- Adbrite Ads disabled, to poor revenue.<br>
- Now login username/password can be changed.<br/>
- Added extra background "Chocolate".<br/>
- Added four Espionage defense buildings.<br/>
- Added thumbs up and thumbs down smilies.<br/>
- Added column sorting to all leaderbord and alliance pages.<br/>
- Optimize menu structure. Merge Player and Home menu.<br/>
- Bug fix: Remove some typos in the text across the game.<br/>
- Bug fix: Last two awards are now working correct!<br/><br/>

<i>Android Client v2.3</i><br/>
- Improve app text tags.<br/>
- Released app on Android Market.<br/><br/>


<span class="subparagraph2">09-12-2011</span><br/>

<i>Game Server v3.6</i><br/>
- Added Last Active column to Alliance - Invite page.<br/>
- Filter out WarQuest robot (cyberspace) players in leaderboards.<br/>
- Center game page in Ms. Internet Explorer browsers.<br/>
- Improve PayPal Donate button integration.<br/>
- Added white surrender flag to players with low health on battle field.<br/>
- Added lightweight message forum.<br/>
- Added experimental sound effect setting (default disabled)!<br/>
- Added battle sounds to Battle page. Only works with windows browsers.<br/>
- Added hide shortcut links in banner for faster navigation:<br/>
&nbsp;&nbsp;- Click "Money" to navigate to player leaderboard page..<br/>
&nbsp;&nbsp;- Click "Exp." to navigate to country leaderboard page.<br/>
&nbsp;&nbsp;- Click "Level" to navigate to player messages.<br/>
&nbsp;&nbsp;- Click "Health" to navigate to hospital page.<br/>
&nbsp;&nbsp;- Click "Energy" to navigate to player profile page.<br/>
&nbsp;&nbsp;- Click "Ammo" to navigate to skill points page.<br/>
- Added create and last login date to Player > Profile page.<br/>
- Bug fix: Alliance invite table offset is maintain during invite action.<br/>
- Bug fix: Alliance accepted table offset is maintain during drop action.<br/>
- Bug fix: Corrected some small graphical issues in Ms. Internet Explorer.<br/><br/>

<i>Android Client v2.2</i><br/>
- Exit app is now working correct when there is no internet connection.<br/>
- Released app on Android Market.<br/><br/>


<span class="subparagraph2">03-12-2011</span><br/>

<i>Game Server v3.5</i><br/>
- Improve espionage functionality:<br/>
&nbsp;&nbsp;- Split attack and defense strength pre espionage unit type.<br/>
&nbsp;&nbsp;- Espionage strength depends now on alliance size.<br/>
&nbsp;&nbsp;- Added Espionage update action (Admin mode)<br/>
&nbsp;&nbsp;- Espionage unit type amount increase to maximum 4.000.<br/>
- Added best player leaderboard column sorting.<br/>
- Improve mission unit lost.<br/>
- Added black background color.<br/>
- Added Help > Donate page.<br/>
- Improved background image 4.<br/>
- Improve alliance pages. Split accepted and pending allies.<br/>
- Optimise Ads locations.<br/>
- Added Ad count graph (Admin mode)<br/>
- Log admin actions in audit trail (Admin mode)<br/>
- Log database errors in audit trail (Admin mode)<br/>
- Bug fix: Added word wrap to truncate long comments.<br/><br/>

<i>Android Client v2.1</i><br/>
- Added back button functionality.<br/>
- Released app on Android Market.<br/><br/>

<i>Windows Client v1.3</i><br/>
- Added https support.<br/>
- Now PayPal donate button is working.<br/>
- Use QT library 4.7.4 as engine.<br/>
- The app was build with QtCreator v2.3.0<br/>
- Released app on freewarefiles.com<br/><br/>


<span class="subparagraph2">24-11-2011</span><br/>

<i>Game Server v3.4</i><br/>
- Added bonus deposit to National Bank (Admin mode)<br/>
- Added WarQuest client upgrade detection.<br/>
- Added clean battle and bank log cron job.<br/>
- Improve Player > Settings page:<br/>
&nbsp;&nbsp;- You must enable manually alliance email notifications.<br/>
&nbsp;&nbsp;- You must enable manually comment email notifications.<br/>
- Added strong password indicator.<br/>
- Added level 201 until 220.<br/>
- Added background information for some units.<br/>
- Bank interest is now paid every day (cron job).<br/>
- Encrease daily bonus.<br/>
- Resort units to have a more logical build-up.<br/>
- Improve link and source code encryption.<br/>
- Activate AdBrite Ad in footer for non Android players.<br/>
- Ad income is used to fund the web hosting.<br/>
- Bug fix: WheelOfFortune cheating not possible anymore.<br/>
- Bug fix: Player with long session (>24h) receive daily bonus again.<br/>
- Bug fix: Added TCP/IP web service shorter timeout.<br/><br/>

<i>Android Client v2.0</i><br/>
- Added workarround to resolve critical freeze problem.<br/>
- Exit button event cleanups cache and kills app completly.<br/>
- Released app on Android Market.<br/><br/>

<i>Windows Client v1.2</i><br/>
- Added support to visit external urls.<br/>
- Added support for file transfer.<br/>
- Use QT library 4.7.4 as engine.<br/>
- The app was build with QtCreator v2.3.0<br/>
- Released app on freewarefiles.com<br/><br/>


<span class="subparagraph2">19-11-2011</span><br/>
<i>Game Server v3.3</i><br/>
- Improve Player > Profile page:<br/>
&nbsp;&nbsp;- Added Stock Exchange asset information.<br/>
&nbsp;&nbsp;- Split building image type section.<br/>
&nbsp;&nbsp;- Added alliance invite link.<br/>
&nbsp;&nbsp;- Improve PDF report.<br/>
- Added new buildings:<br/>
&nbsp;&nbsp;- 10 maintenance buildings.<br/>
&nbsp;&nbsp;- 2 energy buildings.<br/>
&nbsp;&nbsp;- 3 discount buildings.<br/>
- Buy maintenance buildings to reduce unit damage during battles.<br/>
- Added meta html data to login page.<br/>
- Added alliance size information to banner.<br/>
- Added Help > Credits page.<br/>
- Added Cook and Security Guard citizen.<br/>
- Disable building citizens panel. Less is more!<br/>
- Added Ads to lower part of page. Functionality is still disabled.<br/>
- Added session take over functionality for better debugging (Admin Mode).<br/>
- Bug fix: Espionage battle bonus is now always correct.<br/>
- Bug fix: Battle unit lost contain now only active units.<br/>
- Bug fix: Army fights do not contain citizens units anymore.<br/>
- Bug fix: Robot attack message contain now always correct army type.<br/>
- Bug fix: WarQuest client version detection is now working again.<br/><br/>

<i>Android Client v1.9</i><br/>
- Maintenance release.<br/>
- Released app on Android Market.<br/><br/>

<span class="subparagraph2">10-11-2011</span><br/>
<i>Game Server v3.2</i><br/>
- Created new session handler:<br/>
&nbsp;&nbsp;- When IP address change during session you are not logout anymore.<br/>
&nbsp;&nbsp;- No client cookie needed anymore.<br/>
&nbsp;&nbsp;- Session inactivity timeout set to 351 days.<br/>
&nbsp;&nbsp;- Only one active session per player account allowed.<br/>
- Espionage functionality adapted:<br/>
&nbsp;&nbsp;- Opponent information is unlocked when your intelligence is higher.<br/>
&nbsp;&nbsp;- Protect your own information by buying more espionage units.<br/>
&nbsp;&nbsp;- Added classified dialog box.<br/>
&nbsp;&nbsp;- Espionage units can now steal from the Trasquera and SwissCore bank.<br/>
- Added multi units lost during battle.<br/>
- Added platform & browser information to Player > Profile page.<br/>
- Replace all html buttons with links. Improve uniform look and feel.<br/>
- Added maximum amount per unit type.<br/>
- Improve unit and building buy/sell dialog.<br/>
- Resolve several small graphical issues.<br/>
- Improve home page for new players. Less is More :)<br/>
- Improve debug trace.<br/>
- Improve browser overview (Admin mode)<br/>
- Bank interest rate is now different for each bank.<br/><br/>

<i>Android Client v1.8</i><br/>
- Refactor source code.<br/>
- Released app on Android Market.<br/><br/>

<span class="subparagraph2">06-11-2011</span><br/>
<i>Game Server v3.1</i><br/>
- Added espionage functionality:<br/>
&nbsp;&nbsp;- Added 12 espionage units.<br/>
&nbsp;&nbsp;- Added detail espionage strength calculation page.<br/>
&nbsp;&nbsp;- Player details page info depends now on espionage strength.<br/>
&nbsp;&nbsp;- More is coming soon :)<br/>
- Redesign Home > Messages page:<br/>
&nbsp;&nbsp;- Now you can reply on received messages.<br/>
&nbsp;&nbsp;- You can edit / delete send messages.<br/>
- Improve unit, building and stock buy/sell dialog.<br/>
- Now posted comments can be edit.<br/>
- Added skill point trade-in functionality to Player - Skills page.<br/>
- Updated deployed player skill points values.<br/>
- Added six extra battle awards.<br/>
- Increase building income.<br/>
- Update unit defense values to get better attack/defense balance.<br/>
- Added mission statistics graph (Admin mode).<br/>
- Improve breaking news input form (Admin mode).<br/><br/>

<i>Android Client v1.7</i><br/>
- On exit (submenu button) all cached files are deleted.<br/> 
- This prevents error pages to be reloaded for the cache.<br/>
- Released app on Android Market.<br/><br/>

<span class="subparagraph2">27-10-2011</span><br/>
<i>Game Server v3.0</i><br/>
- Added to home page amount of online players last 24 hours.<br/>
- Rank names updated (Thanks scout702 for the information).<br/>
- Level 1 is now battle training level.<br/>
- Added WarQuest player comment rss feed on login page.<br/>
- Added game statistics graphs (Admin mode)<br/>
- Improve browser overview report (Admin mode)<br/>
- Bug fix: Cron is now running every day.<br/>
- Bug fix: WarQuest clients can not change there password anymore.<br/><br/>

<i>Android Client v1.6</i><br/>
- Improvement stability.<br/>
- Released app on Android Market.<br/><br/>

<span class="subparagraph2">21-10-2011</span><br/>
<i>Game Server v2.9</i><br/>
- Complete redesign of building functionality:<br/>
&nbsp;&nbsp;- Each building contain now citizens.<br/>
&nbsp;&nbsp;- Each citizen has hourly cost (so deploying buildings reduce your income).<br/>
&nbsp;&nbsp;- Added calculate initial player citizen size action (Admin mode)<br/>
&nbsp;&nbsp;- Improve building transaction messages.<br/>
- Refactor some source code for better performance.<br/>
- Added hourly cost information to unit popup.<br/>
- Disable Poker, Roulette and BlackJack casino games.<br/><br/>

<i>Android Client v1.4</i><br/>
- Maintenance release.<br/>
- Released app on Android Market.<br/><br/>

<span class="subparagraph2">16-10-2011</span><br/>
<i>Game Server v2.8</i><br/>
- Added "Attack" button to player detail page.<br/>
- Improve About and Release Notes information.<br/>
- Remove old Windows client detection. Not needed anymore!<br/>
- Improve breaking news javascript.<br/>
- Improve home page for MSIE browsers.<br/>
- Improve part information of mission.<br/>
- Added member browser / platform overview page. (Admin mode)<br/>
- Move css and js files to second content location.<br/>
- Improve php web server response time.<br/>
- Html requests on login page are now counted.<br/>
- Bug fix: Robot does not attack player without ammo anymore.<br/>
- Disabled html redirect on www.warquest.nl domain.<br/>
- Introduce info@warquest.nl email contact address for questions.<br/><br/>

<i>Android Client v1.3</i><br/>
- Added support for Android 2.2 and higher.<br/>
- Added no internet connection warning.<br/>
- Bug fix: if internet fails during auto sign-on, no account is created anymore.<br/>
- App is now using the www.warquest.nl url.<br/>
- Released app on Android Market.<br/><br/>

<i>Windows Client v1.0</i><br/>
- Added internet and new version check.<br/>
- Bug fix: if internet fails during auto sign-on, no account is created anymore.<br/>
- Use QT library 4.7.4 as engine.<br/>
- The app was build with QtCreator v2.3.0<br/>
- Released app on freewarefiles.com<br/><br/>

<span class="subparagraph2">03-10-2011</span><br/>
<i>Game Server v2.7</i><br/>
- Added breaking news section to home page.<br/>
- Battle player list does not show allies anymore.<br/>
- Improve alliance overview - Not approved allies are now on top of the list.<br/>
- Optimised some pages for Android client.<br/>
- Improve release notes layout.<br/><br/>

<i>Android Client v1.1</i><br/>
- WarQuest app released in the Android market place.<br/>
- Added app icon<br/>
- Added exit, setting and about menu.<br/>
- Added about and setting page.<br/>
- Added title bar with load progress bar<br/>
- Added automatic sign-on.<br/>
- Added client version information in first http request.<br/>
- Added background image on setting and about page.<br/><br/>

<span class="subparagraph2">25-09-2011</span><br/>
<i>Game Server v2.6</i><br/>
- Complete redesign of battle functionality:<br/>
&nbsp;&nbsp;- Now you can fight or bounty hunt other players.<br/>
&nbsp;&nbsp;- You can set a bounty on someone head on the battle page.<br/> 
&nbsp;&nbsp;- If the player with bounty is defeated, he will lose some experience points.<br/>
&nbsp;&nbsp;- Bounty hunting feature is enabled at level 5.<br/>
- Battle attack force selection is now stored.<br/>
- Added "President Office" discount building.<br/>
- Added update building discount action (Admin Mode)<br/>
- Added default picture for robot players.<br/>
- Added leaderboard position on home page.<br/>
- Added active country count on login page.<br/>
- Casino games are now unlocked during the game play.<br/>
- Unit and building attack / defense values updated.<br/>
- Player attack / defense strength recalculated.<br/>
- Enlarge maximum amount of buildings from 450 to 600.<br/>
- Added full automatic cron jobs.<br/><br/>

<i>Android Client v0.1</i><br/>
- Start building android WarQuest app<br/>
- www.warquest.nl site is automatic loaded<br/>
- Full control of game possible.<br/><br/>

<span class="subparagraph2">07-09-2011</span><br/>
<i>Game Server v2.5</i><br/>
- Complete redesign of alliance functionality:<br/>
&nbsp;&nbsp;- Player ally size is now limit to maximum 3 times the player level.<br/>
&nbsp;&nbsp;- For example: A player in level 11 can have maximum 33 allies.<br/>
&nbsp;&nbsp;- Remove recruit button on Player > Profile page.<br/>
&nbsp;&nbsp;- Remove invite friend by email functionality. Was not used!<br/>
- Added user audit trail to detect hack attemps.<br/>
- Added "Satellite Solar Plant" energy building.<br/>
- Added "Military Headquarters" discount building.<br/>
- Improve database indexes. Queries average three times faster.<br/>
- Admin player now visible again in leaderboards.<br/>
- Enlarge maximum amount of buildings from 350 to 450.<br/><br/>

<i>Windows Client v0.70</i><br/>
- Added load progress indication in title bar.<br/>
- Added reload button to popup menu.<br/>
- Added icons to popup menu.<br/>
- Added QT version information on about window.<br/>
- Use QT library 4.7.4 as engine.<br/>
- The app was build with QtCreator v2.3.0<br/>
- Released app on freewarefiles.com<br/><br/>

<span class="subparagraph2">02-09-2011</span><br/>
<i>Game Server v2.4</i><br/>
- Added Wheel of Fortune casino game.<br/>
- Added basic casino functionality. More is coming soon!<br/>
- Move Logout button to home submenu.<br/>
- Added more awards with more bonus expercience points.<br/>
- Update all existing player accounts with new award schema.<br/>
- Improve award help and skill point page.<br/>
- Improve worldmap. Sea is now transparant.<br/>
- Corrected total request count. Robots actions are not counted anymore.<br/>
- Improve some database queries. Now faster page response.<br/> 
- Added cleanup battle log action. (Admin mode)<br/><br/>

<span class="subparagraph2">25-08-2011</span><br/>
<i>Game Server v2.3</i><br/>
- Added Nasdaq, DowJones, Aex stock exchange with realtime prices.<br/>
- Enlarge maximum amount of buildings from 300 to 350.<br/>
- Improve best country leaderboard (Added total server requests).<br/>
- Replace robots country name from Europe to Cyberspace.<br/>
- Added discount buildings. Give building price discount.<br/>
- Refactor existing buildings.<br/>
- Added "Nuclair power plant" energy building.<br/>
- Make source code compliant with the PHP 5.3.x standard.<br/>
- Added some missing country names.<br/><br/>

<span class="subparagraph2">14-07-2011</span><br/>
<i>Game Server v2.2</i><br/>
- Added update player level action. (Admin mode)<br/>
- Added robot players up to level 61.<br/>
- Decrease building prices.<br/>
- Improve login page. New unit images reload every 2 second.<br/>
- Enlarge maximum amount of buildings from 200 to 300.<br/>
- Added extra energy building.<br/>
- Improve user event logging.<br/>
- Robot players can now fight back. Be aware!<br/>
- Improve menu notifications<br/><br/>

<span class="subparagraph2">02-07-2011</span><br/>
<i>Game Server v2.1</i><br/>
- Added ally icon to Best-Player leaderbord and Battle page.<br/>
- Improve allies overview page.<br/>
- Allies can not be attack anymore!<br/>
- Change default background. Hope everybody like it! :lol:<br/>
- Increase battle and bank transaction log size to 30 max entries.<br/>
- Enabled ranks and awards help page again.<br/>
- Remove wishlist from release notes. Game is almost full feature!<br/>
- Improve source code encryption file format.<br/>
- Improve login page. Added supported hardware and browsers.<br/>
- Added page navigation above data tables.<br/>
- Improved Attack and Defense skill points functionality.<br/>
- Make game compliant with Android browsers.<br/>
- Added robot players up to level 45.<br/>
- Bug fix: Mission loot was not always working fine in high levels.<br/>
- Bug fix: Money values on apple devices are now correctly displayed.<br/>
- Bug fix: Now all old WarQuest clients are detected correctly.<br/><br/>

<span class="subparagraph2">25-06-2011</span><br/>
<i>Game Server v2.0</i><br/>
- Reassign robot players to europe "country". <br/>
- Added robot players up to level 35.<br/>
- Added semi-automatic robot player alliance acceptance. :lol:<br/>
- Improve robot player control page. (Admin mode)<br/>
- Reorder levels above level 110.<br/>
- Redesign player skills page.<br/>
- Improve information box layout.<br/>
- Added Win/Losts ratio information to player statistics.<br/>
- Added two income and one extra energy building.<br/>
- Encrypted PHP code on web server. Protect my IPR!<br/>
- Added player building income detail page.<br/>
- Added player unit hourly cost detail page.<br/><br/>

<i>Windows Client v0.60</i><br/>
- Canvas window height depends now on real video page size.<br/>
- Use QT library 4.7.2 as engine.<br/>
- The app was build with QtCreator v2.0.1<br/>
- Released app on freewarefiles.com<br/><br/>

<span class="subparagraph2">20-06-2011</span><br/>
<i>Game Server v1.9</i><br/>
- Improve loot. Now multiple units can be won.<br/>
- Improve battle opponent list selection.<br/>
- Added user event logging for better debugging.<br/>
- Added player PDF report.<br/>
- Added counter attack action in Home > Battle News view.<br/>
- Added wishlist to release notes.<br/>
- Improve menu navigation.<br/>
- Improve fight bonus message.<br/>
- Added tooltip to award images.<br/>
- Enlarge player message size from 200 to max. 400 characters.<br/>
- Bug fix: Random strength calculation mismatch resolved.<br/>
- Bug fix: Random battle lost issue resolved.<br/>
- Bug fix: Protect battle agains negative money bonus.<br/>
- Bug fix: Protect missions again negative hourly income.<br/><br/>

<span class="subparagraph2">14-06-2011</span><br/>
<i>Game Server v1.8</i><br/>
- Added last visit message on home page.<br/>
- Added bank interest. Deposit money generate now also income.<br/>
- Improve daily bonus message.<br/>
- Improve mission buy missing units message.<br/>
- Added Antarctica missions.<br/>
- Split attack / defense strength in army, cavalry, navy and airforce.<br/>
- Now you can battle opponents on land, water and/or air.<br/>
- Added three navy defense buildings.<br/>
- Improve battle page.<br/>
- Added custom background image setting.<br/>
- Improve battle news content and layout.<br/>
- Decrease some building, unit and hourly prices.<br/>
- Bug fix: Language setting remains when other setting is change.<br/><br/>

<span class="subparagraph2">07-06-2011</span><br/>
<i>Game Server v1.7</i><br/>
- Added attack / defense strength values to battle page.<br/>
- Added message if no players are available to fight.<br/>
- Improve menu bar alignment.<br/>
- Improve game status bar.<br/>
- Added player > comments page navigation.<br/>
- Split home page in three parts. Added submenu.<br/>
- Added bank images.<br/>
- Added gravatar player image support.<br/>
- Improve some unit pictures.<br/>
- Added level 0. Mission training level.<br/>
- Added multi language support for country names.<br/>
- Recruit button is only showed when player is not an ally.<br/>
- Added render time information in footer.<br/>
- Added message smilies support :D :lol: :roll:<br/>
- Improve page title.<br/>
- Player can now delete message send to all players.<br/><br/>

<span class="subparagraph2">19-05-2011</span><br/>
<i>Game Server v1.6</i><br/>
- Login page language depends on browser language setting now.<br/>
- Added language selection to Player - Settings page.<br/>
- Improve english translation. Thanks suave.<br/>
- Added dutch translation. Thanks SuperT.<br/>
- Update about page.<br/>
- Detect very old WarQuest windows client. Force upgrade!<br/>
- Remove URL GET parameter processing.<br/>
- Remove jquery dependency. Improve performance 5%.<br/>
- Added picture to hospital page.
- Improve award pictures.<br/>
- Receive extra skill point when award is won.<br/>
- Adapted first 10 level transistions.<br/>
- Bug fix: Hourly cost calculation corrected.<br/><br/>

<i>Windows Client v0.50</i><br/>
- Rename proxy window to settings window.<br/>
- Added username and password settings.<br/>
- Added client version information in first request.<br/>
- Use QT library 4.7.2 as engine.<br/>
- The app was build with QtCreator v2.0.1<br/>
- Released app on freewarefiles.com<br/><br/>

<span class="subparagraph2">14-05-2011</span><br/>
<i>Game Server v1.5</i><br/>
- Show unlocked features when next level is reached.<br/>
- Added two extra energy buildings.<br/>
- Added one extra defense building.<br/>
- Added multi language support.<br/>
- Move all database language labels to resource file.<br/>
- Improve performance (5% less database queries needed during game play)<br/>
- Optimize datamodel.<br/>
- Added English translation (100% ready).<br/>
- Improve inline source code documentation.<br/>
- Optimise CSS for Apple Ipad.<br/><br/>

<span class="subparagraph2">04-05-2011</span><br/>
<i>Game Server v1.4</i><br/>
- Improve mission submenu selection.<br/>
- Improve some game text boxes.<br/>
- Disable help rank and award page.<br/>
- Bug fix: Mission bonus money calculated is now working fine.<br/>
- Bug fix: Transaction with more 2.147.483.647 dollar is now working fine.<br/>
- Bug fix: Prevent negative hourly income on mission page.<br/><br/>

<span class="subparagraph2">27-04-2011</span><br/>
<i>Game Server v1.3</i><br/>
- Improve worldmap image.<br/>
- Added worldmap hyperlink to jump directly to mission page.<br/>
- Improve continent complete bonus - energy level is directly restored.<br/>
- Username and Password length increase to maximum 15 digits.<br/>
- Initial money increase to 25.000 dollar.<br/>
- Initial skill points increase to 9.<br/>
- Move comments functionality to alliance menu.<br/>
- Comments send to a player are also mailed!<br/>
- Until level 17 players can only attack other player in the same level.<br/>
- Bug fix: Alliance player detail page did not work always. Solved.<br/>
- Bug fix: Notes page is now showed correct on Nokia devices.<br/><br/>

<span class="subparagraph2">20-04-2011</span><br/>
<i>Game Server v1.2</i><br/>
- Added world map with mission conquer progress information.<br/>
- Decrease chance of losing units during mission with 50%.<br/>
- Show complete mission submenu bar.<br/>
- Added data page control to best player leaderbord.<br/>
- Split every mission continent in three parts.<br/>
- Created upgrade script to patch database mission tables.<br/>
- Improve help - release notes page.<br/>
- Bug fix: Remove some typos on the mission pages.<br/>
- Bug fix: Alliance calculation is optimise.<br/><br/>

<span class="subparagraph2">14-04-2011</span><br/>
<i>Game Server v1.1</i><br/>
- Improve bank page.<br/>
- Payed hospital bill is now recorded in bank transaction log.<br/>
- Added release notes to help section.<br/>
- Leaderbords table size enlarge to maximum 100 entries.<br/>
- Hourly income stops when player is not active last 24 hours.<br/>
- Added google analystics javascript.<br/>
- Added direct sign on and login for WarQuest client.<br/>
- Now only players can be attack with max 3 level difference.<br/>
- Initial skill point amount decreased from 10 to 7.<br/>
- Bug fix: Javascript money calculation corrected!<br/>
- Bug fix: Home page improved for Nokia devices.<br/><br/>

<i>Windows Client v0.40</i><br/>
- Registration and Login information not needed anymore.<br/>
- Added direct sign on and login.<br/>
- Use QT library 4.7.2 as engine.<br/>
- The app was build with QtCreator v2.0.1<br/>
- Released app on freewarefiles.com<br/><br/>

<span class="subparagraph2">08-04-2011</span><br/>
<i>Game Server v1.0</i><br/>
- Exclude admin account from player reports.<br/>
- Optimise level ranges.<br/>
- Added robot players for the first 15 levels. More fun!<br/>
- Added Players per Level report (Admin page)<br/>
- Added copy and/or delete member account (Admin page)<br/>
- Added new member report (Admin page)<br/>
- Added rang image to home page.<br/>
- Added logout page.<br/>
- Adjusted daily bonus.<br/>
- Added Ranks and About help page.<br/>
- iPhone Safari login with GPRS connection is now working.<br/>
- SuperT, thanks for all the usefull comments and bug reports.<br/>
- First stable release. Beta testing phase closed.<br/><br/>

<span class="subparagraph2">01-04-2011</span><br/>
<i>Game Server v0.90</i><br/>
- Added admin comments maintenance page.<br/>
- Refactor function names of game.<br/>
- Added unit amount on battle page.<br/>
- Improve alliance page.<br/>
- Performance improvement. Split php and image service.<br/>
- Added maintenance admin pages.<br/>
- Improve login page layout.<br/>
- Added deploy or disband multiple units with one click.<br/>
- Added buy or sell multiple buildings with one click.<br/>
- Initial (new account) skill points increase to 10.<br/>
- Now only players can be attack with max 2 level difference.<br/>
- Bug fix: Alliance size on leaderboard corrected.<br/>
- Bug fix: Resolve some small GUI layout issues.<br/>
- Bug fix: Nokia ccs stylesheet.<br/>
- Bug fix: Internet Explorer css stylesheet.<br/>
- Bug fix: Leaderboard player attack is now restricted.<br/>
- Retested game with Firefox, Safari, IE, Nokia, Opera browser.<br/><br/>

<span class="subparagraph2">27-03-2011</span><br/>
<i>Game Server v0.80</i><br/>
- Redesign intro page. Better look.<br/>
- Make CSS font size better<br/>
- Ordered www.warquest.nl domain.<br/> 
- Added Nokia css style sheet.<br/>
- Added admin page, to manage easy users and comments.<br/>
- Added ids to html links and buttons for selenium tests.<br/>
- Added send comment to one player.<br/>
- Added third leaderbord.<br/>
- Refactor feedback message box.<br/>
- Improve help text.<br/>
- Bug fix: 100% continent detect is now working fine.<br/>
- Bug fix: Attack player for leaderboard is now working again.<br/>
- Bug fix: Emails contain now correct text.<br/><br/>

<i>Windows Client v0.30</i><br/>
- Update URL to www.warquest.nl<br/>
- Use QT library 4.7.2 as engine.<br/>
- The app was build with QtCreator v2.0.1<br/>
- Released app on freewarefiles.com<br/><br/>

<span class="subparagraph2">20-03-2011</span><br/>
<i>Game Server v0.70</i><br/>
- Added progress bar to mission.<br/>
- Added chance of loot during mission.<br/>
- Added email notification to alliance functionality.<br/>
- Improve unit lost message during mission.<br/>
- Improve battle summary page.<br/>
- Improve email reply address and mail content.<br/>
- Improve setting page - current values are showed.<br/>
- Added functionality to change email on setting page.<br/>
- Adjusted unit lost chance.<br/>
- Improve battle log cleanup.<br/>
- Added invite friends (email) to game and get bonus.<br/>
- Now all players can make alliance with each other.<br/>
- Improve unit and building info box.<br/>
- Added build number to login page.<br/>
- Improve player page layout.<br/>
- Adjust hospital cost.<br/>
- Bug fix: Solve some small GUI mismatches.<br/>
- Bug fix: Show correct continent name on mission page.<br/>
- Bug fix: Battle log is now working correct.<br/>
- Bug fix: Battle report defense buildings amount now right.<br/><br/>

<span class="subparagraph2">13-03-2011</span><br/>
<i>Game Server v0.60</i><br/>
- Improvement leaderbords.<br/>
- Improve building images (All same size now)!<br/>
- Improve help text.<br/>
- Improve game layout.<br/>
- Added continent mission complet skill points bonus.<br/>
- Translate country names to english.<br/>
- Added apple iphone / ipod css.<br/>
- Added missing mission and mission unit dependencies.<br/>
- Bug fix: Mission unit lost is now working correct.<br/>
- First beta release for the world.<br/><br/>

<i>Windows Client v0.20</i><br/>
- Added proxy support.<br/>
- Added about page.<br/>
- Refactor source code.<br/>
- Use QT library 4.7.2 as engine.<br/>
- The app was build with QtCreator v2.0.1<br/><br/>

<span class="subparagraph2">06-03-2011</span><br/>
<i>Game Server v0.50</i><br/>
- Added submenu to building page. No scrolling anymore. :-}<br/>
- Added two extra banks with special features.<br/>
- Added country flags.<br/>
- Added second leaderbord. Best performing country.<br/>
- Added bank transaction log.<br/>
- Added battle and bank table cleanup.<br/>
- Added basic help page.<br/>
- Added flavicon image.<br/>
- Added land names to flags.<br/>
- Added Credits and Donate page.<br/>
- Player can now only battle other country players.<br/>
- Improve Player > Profile page.<br/>
- Increase daily money bonus.<br/>
- Improve home page layout.<br/>
- Show defense buildings during fights.<br/>
- Create unique game name "War Quest"<br/>
- Added battle new flag in main menu.<br/>
- Improve next level message.<br/>
- Added insigne image to home page.<br/>
- Update weapon unit names and images.<br/>
- Update building names and images.<br/>
- Bug fix: Level 200 is maximum to reach.<br/><br/>

<i>Windows Client v0.10</i><br/>
- Start building.<br/>
- Added application icon.<br/>
- First beta release for the world.<br/>
- Use QT library 4.7.2 as engine.<br/>
- The app was build with QtCreator v2.0.1<br/><br/>

<span class="subparagraph2">27-02-2011</span><br/>
<i>Game Server v0.40</i><br/>
- Added tooltip on battle / mission / player page.<br/>
- Background image is now fix.<br/>
- Improve Player > Profile page.<br/>
- Added leaderbord - best player.<br/>
- Added missing units up to level 200.<br/>
- Added more mission - unit connections.<br/>
- Added buy missing units during mission play.<br/>
- Added random mission unit lost.<br/>
- Added unit lost can be enabled/disable per level.<br/>
- Added battle summary show used weapon units.<br/>
- Added dot support in money javascript.<br/>
- Improve battle log text.<br/>
- Improve number format.<br/>
- Added settings page (change nickname and/or password).<br/>
- Performance tuning. Include only php file when needed.<br/>
- Refactor login functionality.<br/>
- Html parameters are now hidden. Nice clean url during game.<br/>
- Added forgot password page.<br/>
- All hyperlinks are now encrypted to prevent hacking.<br/>
- Added alliance size to mission.<br/>
- Improve Health, Energy and Ammo countdown timer.<br/>
- Added configuration settings in array.<br/>
- Send welcome email to new register player.<br/>
- Added Password reset on login page.<br/>
- Added unit damage functionality during fights.<br/>
- Bug fix: Prevent income to become negatief because of unit cost.<br/>
- Bug fix: Java script hourly money did not work.<br/>
- Bug fix: Defense strength was not correct calculated.<br/>
- Bug fix: Prevent negatieve income by selling a building.<br/>
- Bug fix: Several issues solved during battle events.<br/><br/>

<span class="subparagraph2">20-02-2011</span><br/>
<i>Game Server v0.30</i><br/>
- Battle list is order by oldest battle on top.<br/>
- Player parameters are updated before battle.<br/>
- Improve skill page.<br/>
- Increase page width size to 500px.<br/>
- Added weapon hourly cost feature.<br/>
- Added menu indication if new ally request is waiting.<br/>
- Added menu indication if new skill points are available.<br/>
- Optimise data model.<br/>
- Calc. attack & defense strength depending on alliance size.<br/>
- Added hospital page<br/>
- Make SQL and PHP code compliant with unix operating system.<br/>
- Added comments page with ajax partly reload functionality.<br/>
- Added Alliance functionality.<br/>
- Protect input for SQL insertion.<br/>
- Added Daily bonus.<br/>
- Improve building price structure.<br/>
- Added private battle zone (Disable member registration)<br/>
- Add CSS Background.<br/>
- Added page, mission counter.<br/>
- Refactor database source code.<br/>
- Check on dubble nickname during registration.<br/>
- Building price increase 10% every purchase.<br/>
- Added progress detection for missions.<br/>
- Make CSS compliant with Microsoft Internet Explorer.<br/>
- Added unit dependence to missions.<br/>
- Improve battle log (ago vs timestamp)<br/>
- Added more color to energy, health, etc..<br/>
- Added several hyperlinks to attacker info page.<br/>
- Added introduction text to login page.<br/>
- Introduce box layout.<br/>
- Added maximum amount of building per types.<br/>
- Bug fix: Player timers now working fine.<br/><br/>

<span class="subparagraph2">13-02-2011</span><br/>
<i>Game Server v0.20</i><br/>
- page width is now base 450px.<br/>
- Improve player timer calculation.<br/>
- Added release notes information to source code.<br/>
- Added div and span html blocks. Remove p html blocks.<br/>
- Improve mission feedback.<br/><br/>

<span class="subparagraph2">08-02-2011</span><br/>
<i>Game Server v0.10</i><br/>
- Started programming.<br/>
- Added basic login, registration and logout page.<br/>
- Added css sheet.<br/>
- Added unit and building page.<br/>
- Added player pages.<br/>
- Added battle page.<br/>
- Added mission page.<br/>
- Added bank page.<br/>
- Added some unit and building images.<br/>
- Added javascript timers.<br/>
- Added battle log.<br/>
';

/*
** ---------------------------------------------------------------- 
** THE END
** ----------------------------------------------------------------
*/

?>