<?php

/* 
**  ========
**  WARQUEST
**  ========
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  All copyrights reserved (c) 2008-2013 PlaatSoft
*/

/*
** Some translation remarks:
** (1) Every line has the following syntax $lang['<KEY>'] = '<DESCRIPTION>';
**     Only change the <DESCRIPTION> part. Leave the rest unchanged.
** (2) The <DESCRIPTION> part contain %s tags. DO NOT REMOVE THEN.
**     The %s are realtime replace with game parameters. 
**     For example: 'Restore for %s dollars' will be on screen 'Restore for 100 dollars'
** (3) The LINK keys contain the menu items of the game. Choose as short as possible words.
** (4) Leave HTML tags unchanged, for example <b>, </b>, etc....
**
** Good luck and have fun!
*/

 /*
 ** ------------------
 ** Language: Romanian
 ** ------------------
 */

 /*
 ** ------------------
 ** LINKS
 ** ------------------
 */

 /* Login */
 $lang['LINK_LOGIN'] = 'Logare';
 $lang['LINK_REGISTER'] = 'inregistrare';
 $lang['LINK_RECOVER'] = 'recuperare'; 
 $lang['LINK_MANUAL'] = 'Manual'; 
 $lang['LINK_FACEBOOK'] = 'Facebook';
 $lang['LINK_RSS'] = 'RSS'; 

 /* General */
 $lang['LINK_HOME'] = 'Acasa';
 $lang['LINK_MISSIONS'] = 'Misiuni';
 $lang['LINK_BATTLE'] = 'Lupta';
 $lang['LINK_UNITS'] = 'Armata';
 $lang['LINK_BUILDINGS'] = 'Cladiri';
 $lang['LINK_BANKS'] = 'Banca';
 $lang['LINK_ALLIANCE'] = 'Alianta';
 $lang['LINK_PLAYER'] = 'Jucator';
 $lang['LINK_MONEY'] = 'Bani';
 $lang['LINK_HELP'] = 'Ajutor';
 $lang['LINK_ADMIN'] = 'Admin';

 $lang['LINK_FIRST'] = 'primul';
 $lang['LINK_PREVIOUS'] = 'inapoi'; 
 $lang['LINK_NEXT'] = 'urmator';
 $lang['LINK_LAST'] = 'ultimul';

 /* Home */
 $lang['LINK_RESTORE'] = 'recuperare';
 $lang['LINK_REPAIR'] = 'reparatie';
 $lang['LINK_TRADE'] = 'schimb';
 $lang['LINK_ACTIVATE'] = 'activare';

 /* Player */
 $lang['LINK_OVERVIEW'] = 'principal';
 $lang['LINK_DELETE'] = 'stergere';
 $lang['LINK_SETTINGS'] = 'setari';
 $lang['LINK_NEWS'] = 'noutati';
 $lang['LINK_COMMENTS'] = 'mesaje';
 $lang['LINK_STATISTICS'] = 'statistici';
 $lang['LINK_LOGOUT'] = 'iesire';
 $lang['LINK_EDIT'] = 'editare';
 $lang['LINK_SAVE'] = 'salvare';
 $lang['LINK_REPLY'] = 'raspuns';
 $lang['LINK_PROFILE'] = 'profil';
 $lang['LINK_SKILLS'] = 'aptitudini';
 $lang['LINK_RECRUIT'] = 'invita';
 $lang['LINK_INCREASE'] = 'creste';
 $lang['LINK_DECREASE'] = 'descreste';
 $lang['LINK_RESTORE_NOW'] = 'restaureaza pentru %s dolari';
 $lang['LINK_CHANGE'] = 'schimba';
 $lang['LINK_REPORT'] = 'raporteaza';
 $lang['LINK_BOUNTY'] = 'vanat';

 /* Mission */
 $lang['LINK_PLAY'] = 'Joaca';
 $lang['LINK_BUY_PLAY'] = 'Cumpara si joaca';
 $lang['LINK_DO_AGAIN'] = 'Joaca din nou';

 /* Battle */
 $lang['LINK_ATTACK'] = 'Attack';
 $lang['LINK_BATTLES'] = 'lupte';
 $lang['LINK_SP'] = 'Puncte Aptitudini';

 /* Unit */
 $lang['LINK_DEPLOY'] = 'Cumpara';
 $lang['LINK_DEPLOY_AGAIN'] = 'cumpara din nou';
 $lang['LINK_DISBAND'] = 'Vinde';
 $lang['LINK_DISBAND_AGAIN']= 'vinde din nou';

 /* Building */
 $lang['LINK_INCOME'] = 'Profit';
 $lang['LINK_DEFENSE'] = 'Aparare';
 $lang['LINK_ENERGY'] = 'Energie';
 $lang['LINK_BUY'] = 'Cumpara';
 $lang['LINK_BUY_AGAIN'] = 'Cumpara din nou';
 $lang['LINK_SELL'] = 'Vinde';
 $lang['LINK_SELL_AGAIN'] = 'Vinde din nou';

 /* Bank / Exchange / Casino */
 $lang['LINK_BANK'] = 'banca';
 $lang['LINK_STOCKEXCHANGE'] = 'Stock-Exchange';
 $lang['LINK_CASINO'] = 'Casino';

 $lang['LINK_DEPOSIT'] = 'Depune';
 $lang['LINK_WITHDRAW'] = 'Retrage';
 $lang['LINK_BALANCE'] = 'Balanta';

 /* Alliance */
 $lang['LINK_INVITE'] = 'Invita';
 $lang['LINK_PENDING'] = 'Invitati';
 $lang['LINK_APPROVED'] = 'Acceptati';
 $lang['LINK_COMMENT'] = 'Mesaje';
 $lang['LINK_BEST_PLAYER'] = 'cei mai buni jucatori';
 $lang['LINK_BEST_COUNTRY'] = 'cele mai bune tari';
 $lang['LINK_DROP'] = 'arunca';
 $lang['LINK_ACCEPT'] = 'accepta';
 $lang['LINK_REJECT'] = 'refuza';
 $lang['LINK_SEND'] = 'trimite';
 $lang['LINK_RESET'] = 'reseteaza';

 /* Forum */
 $lang['LINK_FORUM'] = 'Forum';
 $lang['LINK_POLLS'] = 'Polls';
 $lang['LINK_CHATROOM'] = 'Cheat';
 $lang['LINK_SEARCH'] = 'Cauta';

 /* Help */
 $lang['LINK_GENERAL'] = 'instructiuni';
 $lang['LINK_NOTES'] = 'noutati';
 $lang['LINK_RANKS'] = 'loc';
 $lang['LINK_AWARDS'] = 'premii';
 $lang['LINK_LEVELS'] = 'levele';
 $lang['LINK_STATS'] = 'statistica';
 $lang['LINK_DONATE'] = 'donare';
 $lang['LINK_ABOUT'] = 'despre';

 $lang['LINK_DISABLED'] = 'dezactivat';

 /*
 ** ------------------
 ** GENERAL 
 ** ------------------
 */

 $lang['SYSTEM_HACK_DETECTED'] = 'nu folositi refresh,inapoi sau butonul inainte';

 $lang['AGO_DAY'] = ' zi'; 
 $lang['AGO_DAYS'] = ' zile';
 $lang['AGO_HOUR'] = ' ora';
 $lang['AGO_HOURS'] = ' ore';
 $lang['AGO_MIN'] = ' minut';
 $lang['AGO_MINS'] = 'minute';
 $lang['AGO_SEC'] = ' secunda';
 $lang['AGO_SECS'] = ' secunde';

 $lang['COPYRIGHT'] = 'Copyright © 2008-2013 - toate drepturile rezervate - <a target="new" href="http://www.plaatsoft.nl">PlaatSoft</a>';

 $lang['STATUS_CASH'] = 'bani';
 $lang['STATUS_EXP'] = 'Experienta.';
 $lang['STATUS_LEVEL'] = 'nivel';
 $lang['STATUS_HEALTH'] = 'viata';
 $lang['STATUS_ENERGY'] = 'energie';
 $lang['STATUS_AMMO'] = 'munitie';
 $lang['STATUS_ALLIANCE_SIZE'] = 'marimea aliantei';

 $lang['BOX_INFO'] = 'INFOrmatii';
 $lang['BOX_WARN'] = 'atentionari';
 $lang['BOX_ERROR'] = 'eroare';

 $lang['GENERAL_NEXT_LEVEL'] = 'minunat ai trecut nivelul\'ai primit %s puncte de aptitudini %s dollars. viata ta,energia si munitia au revenit.';
 $lang['GENERAL_BATTLE_LEVEL'] = 'minunat ai castigat %s lupte si primesti %s puncte suplimentare si %s dollars.';
 $lang['GENERAL_BOUNTY_LEVEL'] = 'minunat! ai pus % pe capul lui si primesti %s puncte de aptitudine si %s dollars.';
 $lang['GENERAL_REBEL_LEVEL'] = 'minunat!ai inceput %s rascoale si primesti %s puncte de aptitudine si %s dollars.';
 $lang['GENERAL_BATTLE_AWARD_WON'] = 'lupta castigata';
 $lang['GENERAL_BOUNTY_AWARD_WON'] = 'recompensa pusa';
 $lang['GENERAL_REBEL_AWARD_WON'] = 'rascoale incepute';
 $lang['GENERAL_UNLOCK'] = 'disponibil la nivelul %s';
 $lang['GENERAL_NEW_FEATURES'] = 'urmatoarele facilitati au fost deblocate';
 $lang['GENERAL_RECEIVED_AWARD'] = 'primesti premiul:';

 $lang['GENERAL_ATTACK'] = 'atac';
 $lang['GENERAL_DEFENSE'] = 'aparare';
 $lang['GENERAL_INCOME'] = 'profit';
 $lang['GENERAL_ENERGY'] = 'energie';
 $lang['GENERAL_EXPERIENCE'] = 'experienta';
 $lang['GENERAL_DOLLAR'] = 'dollar';
 $lang['GENERAL_ALLIANCE_SIZE'] = 'marimea aliantei';
 $lang['GENERAL_EXPERIENCE_POINTS'] = 'puncte de experienta';
 $lang['GENERAL_UPKEEP'] = 'costul pe ora';
 $lang['GENERAL_BANK'] = 'banca';
 $lang['GENERAL_DEPLOYED'] = 'cumparate';

 $lang['GENERAL_PLAYER'] = 'jucator';
 $lang['GENERAL_LEVEL'] = 'nivel';
 $lang['GENERAL_ALLIANCE'] = 'alianta';
 $lang['GENERAL_WON'] = 'catigate';
 $lang['GENERAL_LOST'] = 'pierdute';
 $lang['GENERAL_AMOUNT'] = 'Amount';
 $lang['GENERAL_DATE'] = 'data';
 $lang['GENERAL_TRANSACTION'] = 'tranzactii';
 $lang['GENERAL_BALANCE'] = 'balanta';
 $lang['GENERAL_APPROVED'] = 'aprobate';
 $lang['GENERAL_EMAIL'] = 'Email';
 $lang['GENERAL_TOP'] = 'Top';
 $lang['GENERAL_EXP'] = 'experienta';
 $lang['GENERAL_COUNTRY'] = 'tari';
 $lang['GENERAL_PLAYERS'] = 'jucatori';
 $lang['GENERAL_WONS'] = 'castigate';
 $lang['GENERAL_LOSTS'] = 'pierdute';
 $lang['GENERAL_NO'] = 'nu';
 $lang['GENERAL_YES'] = 'da';
 $lang['GENERAL_AGO'] = 'acum';
 $lang['GENERAL_MESSAGE'] = 'mesaje';
 $lang['GENERAL_ACTION'] = 'Actione';
 $lang['GENERAL_NUMBER'] = 'Nr.';
 $lang['GENERAL_DISCOUNT'] = 'reducere cladiri';
 $lang['GENERAL_REQUESTS'] = 'cerinte';
 $lang['GENERAL_EP'] = 'puncte aptitudine';
 $lang['GENERAL_AWARD'] = 'premiu';
 $lang['GENERAL_LANGUAGE'] = 'limba';
 $lang['GENERAL_RANKING'] = 'loc';

 $lang['GENERAL_NEW_UNIT'] = 'unitate noua';
 $lang['GENERAL_NEW_BUILDING'] = 'cladire noua';
 $lang['GENERAL_NEW_MISSION'] = 'misiune noua';
 $lang['GENERAL_GAIN'] = 'castig';

 $lang['GENERAL_BOUNTY'] = 'Bounty';
 $lang['GENERAL_INTELLIGENCE'] = 'inteligenta';
 $lang['GENERAL_SPIES'] = 'spion';
 $lang['GENERAL_MAINTENANCE'] = 'intretinere cladire';

 $lang['GENERAL_CNTRY'] = 'tara';
 $lang['GENERAL_TOPICS'] = 'topic'; 
 $lang['GENERAL_FORUM'] = 'Forum';
 $lang['GENERAL_MESSAGES'] = 'mesaj';
 $lang['GENERAL_LAST_MESSAGE'] = 'ultimul mesaj';
 $lang['GENERAL_FORUM_MODERATED'] = '(Moderat de %s)';
 $lang['GENERAL_NOT_MODERATED'] = '(Not Moderated)';

 $lang['GENERAL_BY'] = 'acum';
 $lang['GENERAL_TOPIC'] = 'Topic';
 $lang['GENERAL_LOCKED'] = 'blocat';
 $lang['GENERAL_WORLDMAP'] = 'harta lumii';
 $lang['GENERAL_PLAATSOFT'] = 'PlaatSoft';
 $lang['GENERAL_CONQUER'] = 'cucerire';

 $lang['GENERAL_ST'] = '%sst';
 $lang['GENERAL_ND'] = '%snd';
 $lang['GENERAL_TH'] = '%sth';

 $lang['GENERAL_CONTINENT'] = 'Continent';
 $lang['GENERAL_CONQUERED'] = 'cucerit';

 $lang['GENERAL_IDLE'] = 'repaus';
 $lang['GENERAL_ACTIVE'] = 'Activ';
 $lang['GENERAL_INACTIVE'] = 'Inactiv';

 $lang['GENERAL_PLANET'] = 'Planeta';
 $lang['GENERAL_PLANET_0'] = 'pamant';
 $lang['GENERAL_PLANET_1'] = 'luna';
 $lang['GENERAL_PLANET_2'] = 'marte';
 $lang['GENERAL_PLANET_3'] = 'asteroid';
 $lang['GENERAL_PLANET_4'] = 'soare';

 /*
 ** ------------------
 ** TIP
 ** ------------------
 */

 $lang['TIP_GENERAL'] = 'TIP';
 $lang['TIP_0'] = 'joaca misunea de antrenament ca sa castigi experienta pentru a trece la nivelul urmator'; 
 $lang['TIP_1'] = 'cumpara cateva trupe si incepe lupta de antrenament pentru a castiga puncte de experienta';
 $lang['TIP_2'] = 'schimbarea iti aduce puncte de aptitudine (Home -> Skills)ca sa iti imbunatatesti aptitudinile de soldat';
 $lang['TIP_3'] = 'introduce adresa de mail ca sa primesti mesaje de la alianta si notificari';
 $lang['TIP_4'] = 'cumpara cateva cladiri care iti aduc bani ca sa generezi'; 
 $lang['TIP_5'] ='cumpara cladiri defensive ca sa iti imbunatatesti apararea'; 
 $lang['TIP_6'] = 'fa-ti aliante cu ceilalti jucatori ca sa iti imbunatatesti atacul si apararea';
 $lang['TIP_7'] = 'depoziteaza bani in Banca Nationala ca sa ii tii in siguranta de ceilalti jucatori'; 
 $lang['TIP_8'] = 'colecteaza puncte de experienta suplimentare votand'; 
 $lang['TIP_9'] = 'pune sume de bani pe capul celorlalti jucatori ca sa primesti recompense';
 $lang['TIP_10'] = 'viziteaza cazinoul ca sa joci la roata norocului pentru a castiga si mai multi bani';
 $lang['TIP_11'] = 'cumpara cladiri pentru energie pentru a regenera energia mai repede';
 $lang['TIP_12'] = 'cumpara soldati inteligenti ca sa spionezi ceilalti jucatori si pentru a porni rascoala pe continentul lor'; 
 $lang['TIP_13'] = 'depoziteaza bani in banca Transquera ca sa primesti profit in fiecare zi';
 $lang['TIP_14'] = 'viziteaza forumul.noi idei in joc sunt binevenite';
 $lang['TIP_15'] = 'verifica sectiunea de ajutor pentru mai multe informatii';
 $lang['TIP_16'] = 'cumpara/vinde ca sa faci mai mult profit(Money -> StockExchange)';
 $lang['TIP_17'] = 'depoziteaza bani banca SwissCore ca sa primesti profit zilnic ';
 $lang['TIP_18'] = 'completeaza toate misiunile de pe continent pentru a primi puncte de experienta suplimentare';
 $lang['TIP_19'] = 'repara armata (acasa -> regenereaza) ca sa previ pierderea unitatilor';
 $lang['TIP_20'] = 'viziteaza cazinoul pentru a juca la sloturi pentru a castiga bani'; 
 $lang['TIP_21'] = 'repara cladirile (acasa -> regenereaza) ca sa previ pierderea cladirilor';
 $lang['TIP_22'] = 'continua sa joci si devino cel mai bun jucator al tarii tale';

 $lang['TIP_90'] = 'doar 10 nivele ramase pana sa iti poti infiinta propria ta colonie pe luna';
 $lang['TIP_91'] = 'doar 9 nivele ramase pana sa iti poti infiinta propria ta colonie pe luna';
 $lang['TIP_92'] = 'doar 8 nivele ramase pana sa iti poti infiinta propria ta colonie pe luna';
 $lang['TIP_93'] = 'doar 7 nivele ramase pana sa iti poti infiinta propria ta colonie pe luna';
 $lang['TIP_94'] = 'doar 6 nivele ramase pana sa iti poti infiinta propria ta colonie pe luna';
 $lang['TIP_95'] = 'doar 5 nivele ramase pana sa iti poti infiinta propria ta colonie pe luna';
 $lang['TIP_96'] = 'doar 4 nivele ramase pana sa iti poti infiinta propria ta colonie pe luna';
 $lang['TIP_97'] = 'doar 3 nivele ramase pana sa iti poti infiinta propria ta colonie pe luna';
 $lang['TIP_98'] = 'doar 2 nivele ramase pana sa iti poti infiinta propria ta colonie pe luna';
 $lang['TIP_99'] = 'doar 1 nivel ramas pana sa iti poti infiinta propria ta colonie pe luna';
 $lang['TIP_100'] = 'creaza-ti propria colonie pe luna';

 $lang['TIP_140'] = 'doar 10 nivele ramase pana sa iti poti infiinta propria ta colonie pe marte';
 $lang['TIP_141'] = 'doar 9 nivele ramase pana sa iti poti infiinta propria ta colonie pe marte';
 $lang['TIP_142'] = 'doar 8 nivele ramase pana sa iti poti infiinta propria ta colonie pe marte';
 $lang['TIP_143'] = 'doar 7 nivele ramase pana sa iti poti infiinta propria ta colonie pe marte';
 $lang['TIP_144'] = 'doar 6 nivele ramase pana sa iti poti infiinta propria ta colonie pe marte';
 $lang['TIP_145'] = 'doar 5 nivele ramase pana sa iti poti infiinta propria ta colonie pe marte';
 $lang['TIP_146'] = 'doar 4 nivele ramase pana sa iti poti infiinta propria ta colonie pe marte';
 $lang['TIP_147'] = 'doar 3 nivele ramase pana sa iti poti infiinta propria ta colonie pe marte';
 $lang['TIP_148'] = 'doar 2 nivele ramase pana sa iti poti infiinta propria ta colonie pe marte';
 $lang['TIP_149'] = 'doar 1 nivel ramas pana sa iti poti infiinta propria ta colonie pe marte';
 $lang['TIP_150'] = 'creaza-ti propria colonie pe marte!';

 $lang['TIP_190'] = 'doar 10 nivele ramase pana sa iti poti infiinta propria ta colonie pe asteroid';
 $lang['TIP_191'] = 'doar 9 nivele ramase pana sa iti poti infiinta propria ta colonie pe asteroid';
 $lang['TIP_192'] = 'doar 8 nivele ramase pana sa iti poti infiinta propria ta colonie pe asteroid';
 $lang['TIP_193'] = 'doar 7 nivele ramase pana sa iti poti infiinta propria ta colonie pe asteroid';
 $lang['TIP_194'] = 'doar 6 nivele ramase pana sa iti poti infiinta propria ta colonie pe asteroid';
 $lang['TIP_195'] = 'doar 5 nivele ramase pana sa iti poti infiinta propria ta colonie pe asteroid';
 $lang['TIP_196'] = 'doar 4 nivele ramase pana sa iti poti infiinta propria ta colonie pe asteroid';
 $lang['TIP_197'] = 'doar 3 nivele ramase pana sa iti poti infiinta propria ta colonie pe asteroid';
 $lang['TIP_198'] = 'doar 2 nivele ramase pana sa iti poti infiinta propria ta colonie pe asteroid';
 $lang['TIP_199'] = 'doar 1 nivel ramas pana sa iti poti infiinta propria ta colonie pe asteroid';
 $lang['TIP_200'] = 'creaza-ti propria colonie pe asteroid';

 /*
 ** ------------------
 ** LOGIN PAGE
 ** ------------------
 */

 $lang['LOGIN_MEMBER_TITLE'] = 'inregistrare membru';
 $lang['LOGIN_REGISTER_TITLE'] = 'inregistrare gratuita';
 $lang['LOGIN_RECOVER_TITLE'] = 'recuperare parola';
 $lang['LOGIN_MANUAL_TITLE'] = 'instructiuni';

 $lang['LOGIN_PLAYERS'] = 'jucatori';
 $lang['LOGIN_REQUESTS'] = 'cerinte';
 $lang['LOGIN_COUNTRIES'] = 'tari';
 $lang['LOGIN_ONLINE'] = 'jucatori on-line';

 $lang['LOGIN_PASSWORD'] = 'parola';
 $lang['LOGIN_USERNAME'] = 'Username';
 $lang['LOGIN_EMAIL'] = 'Email';
 $lang['LOGIN_NICKNAME'] = 'Nickname';

 $lang['LOGIN_MAINTENANCE_TITLE'] = 'mentenanta server';
 $lang['LOGIN_MAINTENANCE'] = ';in acest moment are loc o mentenanta a serverului.va rugam sa reveniti in 30 minute.multumim';

 $lang['LOGIN_LOGOUT'] = 'te-ai delogat!'; 
 $lang['LOGIN_FAILED'] = 'username si/sau parola gresite';
 $lang['LOGIN_REGISTER_OK'] = 'contul a fost creat!';
 $lang['LOGIN_PASSWORD_TO_SHORT'] = 'parola trebuie sa aibe cel putin 6 caractere';
 $lang['LOGIN_USERNAME_TO_SHORT'] = 'Username-ul trebuie sa aiba cel putin 4 caractere';
 $lang['LOGIN_USERNAME_EXIST'] = 'Username %s deja exista!';
 $lang['LOGIN_EMAIL_EXIST'] = 'Email deja inregistrat!';
 $lang['LOGIN_EMAIL_INVALID'] = 'Email-ul este invalid! (invalid format)';
 $lang['LOGIN_NICKNAME_EXIST'] = 'Nickname %s deja folosit!';
 $lang['LOGIN_NICKNAME_NEEDED'] = 'Nickname trebuie introdus!';
 $lang['LOGIN_NEW_PASSWORD_SEND'] = 'noua parola a fost trimisa la adresa de mail!';
 $lang['LOGIN_EMAIL_UNKNOWN'] = 'e-mail necunoscut!';
 $lang['LOGIN_BEST_VIEWED'] = 'WarQuest este optimizat pentru urmatoarele sisteme mobile:"Apple iOS/iPad, Nokia Symbian, 
 BlackBerry OS, Android OS"si pentru browserele de internet:"Internet Explorer, Mozilla Firefox, Apple Safari, Opera, Google Chrome".
 Acest joc este optimizat pentru browserele setate la 500px';

 $lang['LOGIN_NEW_CLIENT_TITLE'] = 'un nou client WarQuest este disponibil!';
 $lang['LOGIN_NEW_CLIENT'] = 'folosesti un client WarQuest invechit. visiteaza www.plaatsoft.nl pentru a descarca noua versiune.';

 $lang['LOGIN_PASSWORD_RESET_NOTE'] = 'daca ai uitat parola introdu adresa de mail si iti vom trimite o noua parola pe adresa de email.';

 /*
 ** ------------------
 ** HOME - OVERVIEW
 ** ------------------
 */

 $lang['HOME_TITLE'] = 'Acasa';

 $lang['HOME_FLASH_NEWS_TITLE'] = 'Noutati';

 $lang['HOME_LASTEST_FORUM_POST'] = 'Ultimele postari pe forum';

 $lang['HOME_INTRO_PLAYERS'] = 'in acest moment %s jucatori din %s tari sunt activi';
 $lang['HOME_INTRO_FIGHTS'] = '%s lupte au avut loc ';
 $lang['HOME_INTRO_REQUESTS'] = '%s server requests were handled. ';

 $lang['HOME_INTRO_TITLE'] = 'Introducere';
 $lang['HOME_INTRO_MISSIONS'] = 'incepe jocul %s ';
 $lang['HOME_INTRO_BATTLES'] = 'si lupte %s. ';
 $lang['HOME_INTRO_UNITS'] = ' cand castigi bani si experienta poti cumpara mai multe %s ';
 $lang['HOME_INTRO_BUILDINGS'] = ' si %s pentru a deveni mai puternic. ';
 $lang['HOME_INTRO_ENEMY'] = ' in orice moment alti jucatori te pot ataca asa ca ingrijeste-te de aparare.';

 $lang['HOME_NEW_ANDROID_VERSION'] = 'o noua versiune a aplicatiei v%s este disponibila pe piata android .<br/>Please upgrade!';
 $lang['HOME_NEW_WINDOWS_VERSION'] = 'un nou client WarQuest este disponibil!';
 $lang['HOME_CLICK_HERE'] = 'aici';
 $lang['HOME_CLICK_TEXT'] = 'Click %s pentru a incepe downloadul.';
 $lang['HOME_EMAIL_MISSING'] = 'te rugam intro adresa de mail ca sa primesti mesaje de la ceilalti jucatori si pentru a-ti recupera parola.';
 $lang['HOME_DAILY_BONUS'] = 'ai gasit %s dollar la o locatie inamica!';

 $lang['HOME_WELCOME'] = 'Bine ai venit';
 $lang['HOME_LAST_LOGIN'] = 'Ultima vizita a fost acum <b>%s</b>.';
 $lang['HOME_AWARDS'] = 'premii';
 $lang['HOME_BATTLE_AWARDS_TEXT'] = 'ai castiga urmatorul premiu de lupta:';
 $lang['HOME_BOUNTY_AWARDS_TEXT'] = 'ai castiga urmatorul premiu de vanatoare:';
 $lang['HOME_REBEL_AWARDS_TEXT'] = 'ai castiga urmatorul premiu de rascoala:';
 $lang['HOME_OVERVIEW_TITLE']= 'privire generala';
 $lang['HOME_MAP_TITLE'] = 'Continent cucerit';
 $lang['HOME_MAP_NOTE'] = ' fiecare continent contine 3 regiuni care pot fi cucerite prin misiuni.';

 $lang['HOME_TRAVEL_TO'] = 'calatoreste pe';

 $lang['HOME_INTRO_PLACE1'] = 'esti pe locul <b>%s</b> general '; 
 $lang['HOME_INTRO_PLACE2'] = 'si locul <b>%s</b> din <b>%s</b> .'; 
 $lang['HOME_PLAYERS_ONLINE'] = 'in ultimele 24hs %s jucatori au fost on-line.';

 $lang['HOME_HOLIDAY'] = 'vacanta';
 $lang['HOME_HOLIDAY_PERIOD_ACTIVE'] = 'periaoda de vacanta activa pentru %s. Misiunile,luptele, unitatile, cladirile si banii sunt blocate in aceasta perioada!';

 /*
 ** ------------------
 ** HOME - PROFILE
 ** ------------------
 */

 $lang['PLAYER_TITLE'] = 'JUCATOR';
 $lang['PLAYER_WIN_LOST_RATE'] = 'procent Castiguri/pierderi';
 $lang['PLAYER_BUILDINGS'] = 'Cladiri';
 $lang['PLAYER_CASH_FLOW'] = 'Bani';
 $lang['PLAYER_ALLIANCE_SIZE'] = 'Marimea aliantei';
 $lang['PLAYER_EXP_POINTS'] = 'Puncte experienta';
 $lang['PLAYER_SERVER_REQUEST'] = 'Servere';
 $lang['PLAYER_MISSION_COMPLETED'] = 'Misiune completa';
 $lang['PLAYER_DEFENSE_STRENGTH'] = 'Taria apararii';
 $lang['PLAYER_ATTACK_STRENGTH'] = 'Taria atacului';
 $lang['PLAYER_FIGHTS_LOST'] = 'lupte pierdute';
 $lang['PLAYER_FIGHTS_WON'] = 'lupte castigate';
 $lang['PLAYER_BUILDING_INCOME'] = 'profit';
 $lang['PLAYER_CONTINENT_INCOME'] = 'Continent income';
 $lang['PLAYER_BOUNTY_SET'] = 'vanatoare pusa';
 $lang['PLAYER_REBELLION_RISE'] = 'rascoala inceputa';
 $lang['PLAYER_UPKEEP'] = 'costul unitatilor pe ora';
 $lang['PLAYER_NETTO_INCOME'] = 'profit net';
 $lang['PLAYER_STATISTICS'] = 'Statistici'; 
 $lang['PLAYER_DISCOUNT_MAINTENANCE'] = 'reducere & Mentenanta';
 $lang['PLAYER_NAME'] = 'Nume'; 
 $lang['PLAYER_ID'] = 'Id';
 $lang['PLAYER_RANK'] = 'Loc'; 
 $lang['PLAYER_OVERVIEW'] = 'Profil'; 
 $lang['PLAYER_DISCOUNT_RATE'] = 'Reducere cladire';
 $lang['PLAYER_MAINTENANCE_RATE'] = 'mentenanta unitatilor';
 $lang['PLAYER_LAST_LOGIN'] = 'ultima data activ (acum)';
 $lang['PLAYER_CREATED'] = 'Creat (acum)';
 $lang['PLAYER_CASINO_PLAYED'] = 'jucat la cazino';
 $lang['PLAYER_ADS_SHOWED'] = 'Ads aratate';
 $lang['PLAYER_TOTAL_HOURLY_INCOME'] = 'profit total pe ora';

 $lang['PLAYER_MONEY_STATUS'] = 'Current assets';
 $lang['PLAYER_CASH_MONEY'] = 'Bani';
 $lang['PLAYER_BANK'] = 'Banca';

 $lang['PLAYER_PLATFORM_BROWSER'] = 'Platforma & Browser';
 $lang['PLAYER_BROWSER'] = 'Browser';
 $lang['PLAYER_BROWSER_VERSION'] = 'Versiune';
 $lang['PLAYER_PLATFORM'] = 'Platforma';

 $lang['PLAYER_LAST_TWEET'] = 'Last Tweet';

 $lang['PLAYER_ATTACK_FORCE'] = 'Overview (%s Attack %s)';
 $lang['PLAYER_DEFENSE_FORCE'] = 'Overview (%s aparare %s)';
 $lang['PLAYER_ATTACK_TEXT'] = '%s ai <b>%s</b> aliati si poti comanda maxim <b>%s</b> unitati. atacul %s are urmatoaarele unitati:';
 $lang['PLAYER_DEFENSE_TEXT'] = '%s ai <b>%s</b> aliati si poti comnda maxim <b>%s</b> unitati. apararea %s are urmatoaarele unitati:';
 $lang['PLAYER_UNIT'] = 'Unitati';
 $lang['PLAYER_AMOUNT'] = 'Amount';
 $lang['PLAYER_STRENGTH'] = 'tarie';
 $lang['PLAYER_ATTACK_SKILLS'] = 'aptitudini de atac';
 $lang['PLAYER_DEFENSE_SKILLS'] = 'aptitudini de aparare';
 $lang['PLAYER_SUB_TOTAL'] = 'Sub total';
 $lang['PLAYER_TOTAL'] = 'Total';
 $lang['PLAYER_FORCE'] = 'Atac & aparare tarie'; 
 $lang['PLAYER_DEPLOYED'] = 'Deployed';

 $lang['PLAYER_BUILDING'] = 'cladire';
 $lang['PLAYER_INCOME'] = 'profit';
 $lang['PLAYER_COST'] = 'Cost';
 $lang['PLAYER_BUILDING_OVERVIEW'] = 'profitul cladirii';
 $lang['PLAYER_BUILDING_TEXT'] = 'acum, jucatorul %s are %s cladiri pentru profit:';
 $lang['PLAYER_UPKEEP_COST'] = 'costuri pe ora';
 $lang['PLAYER_UPKEEP_TEXT'] = 'acum,jucatorul %s are %s unitati';
 $lang['PLAYER_CONTINENT_OVERVIEW'] = 'Profitul acestui continent';
 $lang['PLAYER_CONTINENT_TEXT'] = 'jucatorul %s a cucerit continentul %s';

 $lang['PLAYER_DISCOUNT_OVERVIEW'] = 'reducere cladiri';
 $lang['PLAYER_BUILDING_TEXT'] = 'acum, jucatorul %s are %s reducere pentru cladiri:';

 $lang['PLAYER_MAINTENANCE_OVERVIEW'] = 'mentenanta cladirilor';
 $lang['PLAYER_MAINTENANCE_TEXT'] = 'acum, jucatorul %s are %s cladiri de mentenanta:';

 $lang['PLAYER_SPY_1'] = 'intel';
 $lang['PLAYER_SPY_2'] = 'exploratori';
 $lang['PLAYER_SPY_3'] = 'exploratori';
 $lang['PLAYER_SPY_4'] = 'exploratori';
 $lang['PLAYER_ESPIONAGE_UNLOCK1'] = 'deblocat cand puterea %s este %s% mai mare decat a oponentului.';
 $lang['PLAYER_ESPIONAGE_UNLOCK2'] = 'delocat cand %s puterea ta este egaka sau mai mare decat a oponentului.';

 /*
 ** ------------------
 ** HOME - NEWS
 ** ------------------
 */

 $lang['HOME_BATTLE_TITLE'] = 'Noutati';
 $lang['HOME_BATTLE_ATTACK_BY'] = 'Ai fost atacat de %s din %s.';
 $lang['HOME_BATTLE_YOU_WON'] = 'Ai <b>CASTIGAT</b>. ';
 $lang['HOME_BATTLE_YOU_LOST'] = 'AI <b>PIERDUT</b>. ';
 $lang['HOME_BATTLE_YOU_EXP'] = 'ai castigat %s experienta ';
 $lang['HOME_BATTLE_TOOK_DAMAGE'] = 'ai produs %s daune.';
 $lang['HOME_BATTLE_TAKING_DAMAGE'] = 'ai primit %s daune.';
 $lang['HOME_BATTLE_YOU_MONEY'] = 'Pierzand %s dolari ';
 $lang['HOME_BATTLE_NO_NEWS'] = 'Nici un raport al bataliilor disponibil in acest moment!'; 

 $lang['HOME_BOUNTY_NEWS'] = '%s a pus %s dolari pe capul tau. daca vei fi invins vei pierde %s experienta.';

 /*
 ** ------------------
 ** HOME - MESSAGE
 ** ------------------
 */

 $lang['HOME_MESSAGES_TITLE']= 'Mesage';
 $lang['HOME_MESSAGE_DELETED'] = 'Mesaj sters!';
 $lang['HOME_NO_MESSAGES'] = 'nu sunt mesaje de la alti jucatori in acet moment!'; 

 /*
 ** ------------------
 ** HOME - SKILLS
 ** ------------------
 */

 $lang['PLAYER_SKILL_SUBTITLE1'] = 'Pncte aptitudine';
 $lang['PLAYER_SKILL_SUBTITLE2'] = 'Puncte aptitudine [%s disponibile]';
 $lang['PLAYER_SKILL_NOTE'] = 'NOTA:foloeste punctele de aptitudine ca sa cresti atacul aparearea viata energia si munitia.';
 $lang['PLAYER_SKILLS'] = 'Aptitudini'; 
 $lang['PLAYER_MAX'] = 'Current'; 
 $lang['PLAYER_ATTACK'] = 'ATAC';
 $lang['PLAYER_DEFENSE'] = 'APARARE';
 $lang['PLAYER_HEALTH'] = 'VIATA'; 
 $lang['PLAYER_ENERGY'] = 'ENERGIE'; 
 $lang['PLAYER_AMMO'] = 'MUNITIE'; 

 $lang['PLAYER_ATTACK_TIP'] = 'cresteti atacul pentru a face mai multe pagube si pentru a castiga mai multe batalii.Te costa 1 punct de aptitudine ca sa iti maresti atacul cu %s. descreste atacul cu %s ca sa optii un punct de aptitudine in schimb.';
 $lang['PLAYER_DEFENSE_TIP'] = 'cresteti apararea ca sa rezisti impotriva mai multor atacuri.Te costa 1 punct de aptitudine ca sa iti cresti apararea cu %s. Descreste apararea cu %s ca sa optii un punct de aptitudine.';
 $lang['PLAYER_HEALTH_TIP'] = 'Cresteti viata maxima ca sa supravietuiesti mai multor batalii. Te costa 1 puncte de aptitudine ca sa iti cresti viata maxima cu 10. Descreste-ti viata cu 20 pentru a primii in schimb un punct de aptitudine.';
 $lang['PLAYER_ENERGY_TIP'] = 'Cresteti energia maxima pentru a juca mai multe misiuni. Te costa 1 puncte de aptitudine ca sa iti cresti energia maxima cu 10. Descreste-ti energia cu 20 pentru a primii in schimb un punct de aptitudine.';
 $lang['PLAYER_AMMO_TIP'] = 'Cresteti munitia maxima pentru a lupta mai mult. Te costa 2 puncte de aptitudine ca sa iti cresti munitia cu 1. Descreste-ti munitia cu 1 pentru a primii in schimb un punct de aptitudine.';

 $lang['PLAYER_SKILL_ACCEPTED1'] = '%s aptitudine marita.';
 $lang['PLAYER_SKILL_REJECTED1'] = 'Iti trebuie %s puncte de aptitudine(s) ca sa iti maresti aceasta calitate.';
 $lang['PLAYER_SKILL_ACCEPTED2'] = '%s aptitudine scazuta.';
 $lang['PLAYER_SKILL_REJECTED2'] = '%s trebuie sa ai nivelul minim.';

 /*
 ** ------------------
 ** HOME - TRADE
 ** ------------------
 */

 $lang['HOME_TRADE_TITLE1'] = 'Puncte de schimb';
 $lang['HOME_TRADE_TITLE2'] = 'Puncte de schimb [%s disponibile]';
 $lang['HOME_TRADE_NOTE'] = 'Nota: I-ati Puncte de schimb(vezi Ajutor - Pagina de Donatii) pentru a le pitea schimba in puncte de aptitudine,bani sau pot fi folosite ca sa iti imbunatatesti timpul de regenerare a vietii energiei sau munitiei.';

 $lang['HOME_TRADE_CONDITION'] = 'Current';
 $lang['HOME_TRADE_MINIMAL'] = 'Minim';

 $lang['HOME_TRADE1'] = 'Timpul pentru viata';
 $lang['HOME_TRADE1_NOTE'] = 'descreste-ti timpul pentru viata pentru ca aceasta sa se regenereze mai repede. Te costa %s ca sa iti descresti timpul cu 5 secunde.';

 $lang['HOME_TRADE2'] = 'Timpul pentru energie';
 $lang['HOME_TRADE2_NOTE'] = 'descreste-ti timpul pentru energie pentru ca aceasta sa se regenereze mai repede. Te costa %s ca sa iti descresti timpul cu 5 secunde.';

 $lang['HOME_TRADE3'] = 'Timpul pentru munitie';
 $lang['HOME_TRADE3_NOTE'] = 'descreste-ti timpul pentru munitie pentru ca aceasta sa se regenereze mai repede. Te costa %s ca sa iti descresti timpul cu 5 secunde.';

 $lang['HOME_TRADE4'] = 'BANI';
 $lang['HOME_TRADE4_NOTE'] = 'Obtine bani pentru a-ti putea cumpara armata,costrui cladiri,etc ..Te costa %s ca sa iti cresti banii cu %s dollar.';

 $lang['HOME_TRADE5'] = 'Puncte de aptitudine';
 $lang['HOME_TRADE5_NOTE'] = 'i=ati puncte de aptitudine pentru a mari atacul ,apararea viata energia sau munitia. te costa %s pentru a primi 1 puncte de aptitudine';

 $lang['HOME_TRADE_SKILL_POINTS'] = 'punct(e) de aptitudine ';
 $lang['HOME_TRADE_IN'] = 'SCHIMBA';
 $lang['HOME_MAX_REACHED'] = 'Maxim atins';

 $lang['HOME_TRADE_HEALTH_TIMER_TO_LARGE'] = 'timpul pentru viata a ajuns la minim.';
 $lang['HOME_TRADE_ENERGY_TIMER_TO_LARGE'] = 'timpul pentru energie a ajuns la minim.';
 $lang['HOME_TRADE_AMMO_TIMER_TO_LARGE'] = 'timpul pentru munitie a ajuns la minim.';

 /*
 ** ------------------
 ** HOME - RESTORE
 ** ------------------
 */

 $lang['PLAYER_RESTORE_TITLE'] = 'Recuperare&Reparatie';
 $lang['PLAYER_RESTORE_SUBTITLE1'] = 'Recuperare';
 $lang['PLAYER_RESTORE_SUBTITLE2'] = 'Reparatie';
 $lang['PLAYER_RESTORE_UNLOCKED'] = 'Recuperarea & Reparatia vor fi deblocate la nivelul %s.';
 $lang['PLAYER_RESTORE_PRICE'] = 'Pretul recuperarii';
 $lang['PLAYER_RESTORE_PRICE_PER_DAY'] = 'Pretul recuperarii pe zi';
 $lang['PLAYER_REPAIR_PRICE'] = 'Pretul reparatiei';
 $lang['PLAYER_RESTORED_FAILED'] = 'nu ai %s dolari pentru a executa aceasta actiune.';

 $lang['PLAYER_HEALTH_TITLE'] = 'Recuperare viata';
 $lang['PLAYER_HEALTH_NOTE'] = 'Plateste spitalul pentru a-ti recupera viata complet.Viata se poate recupera si singura cu timpul.Recuperarea poate fi folosita doar odata la 5 minuteViata se poate recupera si singura cu timpul.'; 
 $lang['PLAYER_HEALTH_CONDITION'] = 'Starea Vietii';
 $lang['PLAYER_HEALTH_RESTORED'] = 'Viata recuperata pentru %s dolari.';
 $lang['PLAYER_HEALTH_CONFIRM'] = 'Chiar vrei sa iti recuperezi viata?';

 $lang['PLAYER_ENERGY_TITLE'] = 'Recuperare energie';
 $lang['PLAYER_ENERGY_NOTE'] = 'Plateste compania petroliera ca sa iti recuperezi energia.Energia poate fi regenerata doar 1 data la 24h.Energia se poate regenera cu trecerea timpului'; 
 $lang['PLAYER_ENERGY_CONDITION'] = 'Starea Energiei';
 $lang['PLAYER_ENERGY_RESTORED'] = 'Energia regenerata pentru %s dolari.';
 $lang['PLAYER_ENERGY_CONFIRM'] = 'Çhiar vrei sa iti regenerezi Energia?';

 $lang['PLAYER_AMMO_TITLE'] = 'Regenerare munitie';
 $lang['PLAYER_AMMO_NOTE'] = 'Plateste fabrica de arme ca sa iti regenereze munitia complet.Recuperarea poate fi folosita doar 1 data la 24h.Munitia se poate regenera cu trecerea timpului.'; 
 $lang['PLAYER_AMMO_CONDITION'] = 'Starea Munitiei';
 $lang['PLAYER_AMMO_RESTORED'] = 'Munitia regenerata pentru %s dolari.';
 $lang['PLAYER_AMMO_CONFIRM'] = 'Chiar vrei sa iti recuperezi munitia?';

 $lang['PLAYER_CEASE_FIRE_TITLE'] = 'Perioada de Relax';
 $lang['PLAYER_CEASE_FIRE_NOTE'] = 'Plateste bani ca sa activezi perioada de relax.In aceasta periaoda alti jucatori nu te pot ataca,dar nici tu nu poti ataca alti jucatori.'; 
 $lang['PLAYER_CEASE_FIRE_ACTIVATED'] = 'Perioada de relax activata pentru %s dolari.';
 $lang['PLAYER_CEASE_FIRE_CONFIRM'] = 'Chiar vrei sa activezi Perioada de Relax?';
 $lang['PLAYER_HOLIDAY_TITLE'] = 'Perioada Sarbatorilor';
 $lang['PLAYER_HOLIDAY_NOTE'] = 'Stai linistit pe timpul sarbatorilor. pe timpul acestei perioade contul tau este inghetat:Misiunile, Bataliile, Armata si Cladirile sunt blocate iar celilalti jucatori nu te pot ataca.'; 
 $lang['PLAYER_HOLIDAY_ACTIVATED'] = 'Perioada sarbatorilor activata pentru %s dolari.';
 $lang['PLAYER_HOLIDAY_CONFIRM'] = 'Chiar vrei sa activezi Perioada de Sarbabori?';

 $lang['PLAYER_UNITS_TITLE'] = 'Repara armata';
 $lang['PLAYER_UNITS_NOTE'] = 'Repara armata.Daca unittile tale ajung pe 0% viata atunci unele unitati pot fi distruse iar celelalte unitati vor fi reparate automat.'; 
 $lang['PLAYER_UNITS_CONDITION'] = 'Starea Armatelor(SA)';
 $lang['PLAYER_UNITS_REPAIRED'] = 'Armatele tale au fost reparate pentru %s dolari.';
 $lang['PLAYER_UNITS_CONFIRM'] = 'Chiar vrei sa iti repari armata?';

 $lang['PLAYER_BUILDINGS_TITLE'] = 'Repara Cladirile';
 $lang['PLAYER_BUILDINGS_NOTE'] = 'Repara cladirile bazei tale. Daca cladirile tale ajung cu viata la 0% unele cladiri vor fi distruse iar celelalte cor fi reparate automat.'; 
 $lang['PLAYER_BUILDINGS_CONDITION'] = 'Starea Cladirilor (SC)';
 $lang['PLAYER_BUILDINGS_REPAIRED'] = 'Cladirile tale au fost reparate pentru %s dolari.';
 $lang['PLAYER_BUILDINGS_CONFIRM'] = 'Chiar vreisa iti repari cladirile?';

 $lang['PLAYER_REBELLION_TITLE'] = 'Restaureaza pacea';
 $lang['PLAYER_REBELLION_NOTE'] = 'Plateste inteligenta ca sa inceteze revoltele din regiunile cucerite de tine.Daca starea revoltei ajunge la 100% unele regiuni vor fi pierdute si trebuie recucerite.'; 
 $lang['PLAYER_REBELLION_CONDITION'] = 'Starea Revoltelor(SR)';
 $lang['PLAYER_REBELLION_RESTORED'] = 'termina revolta pentru %s dolari.';
 $lang['PLAYER_REBELLION_CONFIRM'] = 'Chiar vrei sa restaurezi pacea?';

 /*
 ** ------------------
 ** HOME - SETTINGS
 ** ------------------
 */

 $lang['SETTING_TITLE'] = 'Setari';
 $lang['SETTING_GENERAL1'] = 'Setari generale 1';
 $lang['SETTING_GENERAL2'] = 'Setari generale 2';

 $lang['SETTING_NICKNAME'] = 'WarQuest nume';
 $lang['SETTING_TWITTER'] = 'Twitter account';
 $lang['SETTING_LANGUAGE'] = 'Limba';
 $lang['SETTING_BACKGROUND'] = "Fundal";
 $lang['SETTING_SOUND'] = 'Sunet activat(Experimental)';
 $lang['SETTING_BOUNTY'] = 'Activat cand se pune recompensa pe capul tau.';
 $lang['SETTING_RESTORE'] = 'Activat regenerare & reparatie confirmare.';
 $lang['SETTING_CONDITION'] = 'Activat Unitati/Cladiri/Revolte starea lor in fereastra pop-up.';
 $lang['SETTING_FORUM_POST'] = 'Activat ultimele postari pe forum pe pagina principala.';
 $lang['SETTING_SORT1'] = 'Activat noile mesaje in partea de sus a forumului.';
 $lang['SETTING_SORT2'] = 'Activat vechile lupte la inceput.';
 $lang['SETTING_NO_BOT_NEWS'] = 'Dezactivat Raportul bataliilor si notificarile cand esti atacat.';
 $lang['SETTING_ALLIES_IN_BATTLE_LIST'] = 'Activat aliatii sa fie vazuti pe campul de lupta si la recompense.';

 $lang['PLAYER_LANG_ENGLISH'] = 'Engleza';
 $lang['PLAYER_LANG_DUTCH'] = 'Daneza';
 $lang['PLAYER_LANG_GERMAN'] = 'Germana';
 $lang['PLAYER_LANG_ITALIAN'] = 'Italiana';

 $lang['BACKGROUND_0'] = 'Black';
 $lang['BACKGROUND_1'] = 'Army Green';
 $lang['BACKGROUND_2'] = 'Red Aurora';
 $lang['BACKGROUND_3'] = 'Gray Stones';
 $lang['BACKGROUND_4'] = 'Pink Circles';
 $lang['BACKGROUND_5'] = 'Blue Silk';
 $lang['BACKGROUND_6'] = 'Brown';
 $lang['BACKGROUND_7'] = 'Pirate';
 $lang['BACKGROUND_8'] = 'Modern';
 $lang['BACKGROUND_9'] = 'Classic';
 $lang['BACKGROUND_10'] = 'Chocolate';
 $lang['BACKGROUND_11'] = 'Christmas';
 $lang['BACKGROUND_12'] = 'Fireworks';

 $lang['PLAYER_GENERAL_CHANGED'] = 'Setarile generale schimbate!';
 $lang['NICKNAME_EXIST'] = 'Nickname-ul este deja luat!';
 $lang['NICKNAME_TO_SHORT'] = 'Nickname-ul trebuie sa iaba minim 4 caractere!';
 $lang['NICKNAME_NO_SPACE'] = 'Fara spatiu la nickname!';

 $lang['PLAYER_CHANGE_EMAIL'] = 'Setari de email';
 $lang['PLAYER_NEW_EMAIL'] = 'Adresa de mail';
 $lang['PLAYER_NOTIFICATION_ALLIANCE'] = 'Notificari despre alianta pe mail';
 $lang['PLAYER_NOTIFICATION_COMMENT'] = 'Mesaje de notificare pe mail';
 $lang['PLAYER_EMAIL_CHANGED'] = 'Setarile de mail schimbate';
 $lang['PLAYER_EMAIL_EXIST'] = 'Adresa de mail deja inregistrata!';
 $lang['PLAYER_EMAIL_INVALID'] = 'Adresa de mail este invalida(format necunoscut)!';

 $lang['PLAYER_LOGIN_SETTINGS'] = 'Setari de logare';
 $lang['PLAYER_USERNAME'] = 'Username';
 $lang['PLAYER_USERNAME_TO_SHORT'] = 'Username !';
 $lang['PLAYER_USERNAME_ALREADY_EXIST'] = 'Username-ul exista deja!';
 $lang['PLAYER_USERNAME_CHANGED'] = 'Username-ul este schimbat. nu uita sa-l schimbi si in aplicatia mobila si in clienbtul Windows,altfel logarea automata nu va mai fi posibila!';
 $lang['PLAYER_CURRENT_PASSWORD'] = 'Parola curenta'; 
 $lang['PLAYER_NEW_PASSWORD'] = 'Noua parola';
 $lang['PLAYER_PASSWORD_CHANGED'] = 'Parola este schimbata.nu uita sa o schimbi si in aplicatia mobila si in clentul windows altfel logarea automata nu va mai fi posibila!';
 $lang['PLAYER_PASSWORD_NO_MATCH'] = 'parola curenta nu se potriveste!';
 $lang['PLAYER_PASSWORD_TO_SHORT'] = 'noua parola trebuie sa aiba cel putin 6 caractere!';
 $lang['PLAYER_LOGIN_NOTE'] = 'ATENTIUNE:Loghinul automat merge doar daca ai acelasi username si parola si in aplicatia mobila si in clentul windows!'; 

 $lang['SETTING_ACCOUNT_RESET_TITLE'] = 'cont resetat';
 $lang['SETTING_YES'] = 'Da';
 $lang['SETTING_SURE'] = 'cont resetat! Esti sigur?';
 $lang['SETTING_ACCOUNT_RESET'] = 'Activezi resetarea contului? ';
 $lang['SETTING_NO_REVERSE'] = '(actiunea de resetare a contului nu este reversibila!)';
 $lang['SETTING_ACCOUNT_RESET_NOTE'] = 'WARNING:Cand contul tau este resetat toatul etse resetat la 0 inclusiv unitati cladiri etc';
 $lang['SETTING_ACCOUNT_RESETTED'] = 'contul jucatorului %s este resetat!';

 /*
 ** ------------------
 ** MISSION DATA
 ** ------------------
 */

 /* Earth Missions */
 $lang['MISSION_GROUP_0'] = 'Training';
 $lang['MISSION_GROUP_1'] = 'Europe';
 $lang['MISSION_GROUP_2'] = 'N-America';
 $lang['MISSION_GROUP_3'] = 'S-America';
 $lang['MISSION_GROUP_4'] = 'Africa';
 $lang['MISSION_GROUP_5'] = 'N-Asia';
 $lang['MISSION_GROUP_6'] = 'S-Asia';
 $lang['MISSION_GROUP_7'] = 'E-Asia';
 $lang['MISSION_GROUP_8'] = 'Oceania';
 $lang['MISSION_GROUP_9'] = 'Mideast';

 /* Moon Missions */
 $lang['MISSION_GROUP_10'] = 'Alpha ';
 $lang['MISSION_GROUP_11'] = 'Beta';
 $lang['MISSION_GROUP_12'] = 'Charlie';
 $lang['MISSION_GROUP_13'] = 'Delta';
 $lang['MISSION_GROUP_14'] = 'Echo';
 $lang['MISSION_GROUP_15'] = 'Foxtrot';
 $lang['MISSION_GROUP_16'] = 'Golf';
 $lang['MISSION_GROUP_17'] = 'Hotel';
 $lang['MISSION_GROUP_18'] = 'India';

 /* Mars Missions */
 $lang['MISSION_GROUP_20'] = 'Alpaca';
 $lang['MISSION_GROUP_21'] = 'Bison';
 $lang['MISSION_GROUP_22'] = 'Coyote';
 $lang['MISSION_GROUP_23'] = 'Dolphin';
 $lang['MISSION_GROUP_24'] = 'Emu';
 $lang['MISSION_GROUP_25'] = 'Fox';
 $lang['MISSION_GROUP_26'] = 'Giraffe';
 $lang['MISSION_GROUP_27'] = 'Heron';
 $lang['MISSION_GROUP_28'] = 'Iguana';

 /* Asteroid Missions */
 $lang['MISSION_GROUP_30'] = 'Alfred';
 $lang['MISSION_GROUP_31'] = 'Benjamin';
 $lang['MISSION_GROUP_32'] = 'Charles';
 $lang['MISSION_GROUP_33'] = 'David';
 $lang['MISSION_GROUP_34'] = 'Edward';
 $lang['MISSION_GROUP_35'] = 'Frederick';
 $lang['MISSION_GROUP_36'] = 'George';
 $lang['MISSION_GROUP_37'] = 'Harry';
 $lang['MISSION_GROUP_38'] = 'Isaac';

 /* Earth */
 $lang['MISSION_0'] = 'Training mission';
 $lang['MISSION_1'] = 'Great Britain Region';
 $lang['MISSION_2'] = 'Benelux';
 $lang['MISSION_3'] = 'France Region ';
 $lang['MISSION_4'] = 'Central Europe';
 $lang['MISSION_5'] = 'Scandinavia';
 $lang['MISSION_6'] = 'East Europe';
 $lang['MISSION_7'] = 'Spain Region';
 $lang['MISSION_8'] = 'South Europe';

 $lang['MISSION_10'] = 'Greenland';
 $lang['MISSION_11'] = 'Canada';
 $lang['MISSION_12'] = 'United States';
 $lang['MISSION_13'] = 'Mexico';
 $lang['MISSION_14'] = 'Guatemala Region';
 $lang['MISSION_15'] = 'Nicaragua Region';
 $lang['MISSION_16'] = 'Cuba Region';
 $lang['MISSION_17'] = 'Caribbean Region';

 $lang['MISSION_20'] = 'Middle America';
 $lang['MISSION_21'] = 'Ecuador Region';
 $lang['MISSION_22'] = 'Bolivia Region';
 $lang['MISSION_23'] = 'Paraguay Region';
 $lang['MISSION_24'] = 'Chile Region';
 $lang['MISSION_25'] = 'Argentina Region';
 $lang['MISSION_26'] = 'Uruguay Region';
 $lang['MISSION_27'] = 'Brazil Region';

 $lang['MISSION_30'] = 'Algeria Region';
 $lang['MISSION_31'] = 'Egypt Region';
 $lang['MISSION_32'] = 'West Africa Region';
 $lang['MISSION_33'] = 'Central Africa Region';
 $lang['MISSION_34'] = 'East Africa Region';
 $lang['MISSION_35'] = 'Mozambique Region';
 $lang['MISSION_36'] = 'Zimbabwe Region';
 $lang['MISSION_37'] = 'South Africa Region';

 $lang['MISSION_40'] = 'Russia Region';
 $lang['MISSION_41'] = 'Mongolia Region';
 $lang['MISSION_42'] = 'Kazakhstan Region';
 $lang['MISSION_43'] = 'Uzbekistan Region';
 $lang['MISSION_44'] = 'Tajikistan Region';
 $lang['MISSION_45'] = 'Turkmenistan Region';
 $lang['MISSION_46'] = 'Georgia Region';
 $lang['MISSION_47'] = 'Armenia Region';

 $lang['MISSION_50'] = 'Iran';
 $lang['MISSION_51'] = 'Afghanistan';
 $lang['MISSION_52'] = 'Pakistan';
 $lang['MISSION_53'] = 'India';
 $lang['MISSION_54'] = 'Nepal';
 $lang['MISSION_55'] = 'Bangladesh Region';
 $lang['MISSION_56'] = 'Thailand Region';
 $lang['MISSION_57'] = 'Laos Region';

 $lang['MISSION_60'] = 'China';
 $lang['MISSION_61'] = 'North Korea';
 $lang['MISSION_62'] = 'South Korea';
 $lang['MISSION_63'] = 'Japan';
 $lang['MISSION_64'] = 'Taiwan';
 $lang['MISSION_65'] = 'Cambodia Region';
 $lang['MISSION_66'] = 'Vietnam Region';
 $lang['MISSION_67'] = 'Malaysia';

 $lang['MISSION_70'] = 'West Indonesia';
 $lang['MISSION_71'] = 'East Indonesia';
 $lang['MISSION_72'] = 'Philippines Region';
 $lang['MISSION_73'] = 'Papua New Guinea';
 $lang['MISSION_74'] = 'Timor';
 $lang['MISSION_75'] = 'North Australia';
 $lang['MISSION_76'] = 'South Australia';
 $lang['MISSION_77'] = 'New Zealand';

 $lang['MISSION_80'] = 'Syria';
 $lang['MISSION_81'] = 'Iraq';
 $lang['MISSION_82'] = 'Saudi Arabia';
 $lang['MISSION_83'] = 'Kuwait';
 $lang['MISSION_84'] = 'Yemen Region';
 $lang['MISSION_85'] = 'Oman Region ';
 $lang['MISSION_86'] = 'Jordan';
 $lang['MISSION_87'] = 'Israel';

 /* Moon */
 $lang['MISSION_100'] = 'Crater Endymion';
 $lang['MISSION_101'] = 'Crater Franklin';
 $lang['MISSION_102'] = 'Sinus Honoris';
 $lang['MISSION_103'] = 'Mons Fidei';
 $lang['MISSION_104'] = 'Crater Blanc';
 $lang['MISSION_105'] = 'Crater Fesenkov';
 $lang['MISSION_106'] = 'Montes Temporis';
 $lang['MISSION_107'] = 'Crater Darwin';

 $lang['MISSION_110'] = 'Crater Agnes';
 $lang['MISSION_111'] = 'Mons Andre';
 $lang['MISSION_112'] = 'Vallis Ardeshir';
 $lang['MISSION_113'] = 'Crater Aristoteles';
 $lang['MISSION_114'] = 'Mare Blanc';
 $lang['MISSION_115'] = 'Mons Bradley';
 $lang['MISSION_116'] = 'Vallis Delisle';
 $lang['MISSION_117'] = 'Sinus Dieter';

 $lang['MISSION_120'] = 'Mons Dilip';
 $lang['MISSION_121'] = 'Mons Esam';
 $lang['MISSION_122'] = 'Crater Albategnius';
 $lang['MISSION_123'] = 'Mons Gruithuisen Delta';
 $lang['MISSION_124'] = 'Mare Gruithuisen Gamma';
 $lang['MISSION_125'] = 'Crater Hansteen';
 $lang['MISSION_126'] = 'Vallis Herodotus';
 $lang['MISSION_127'] = 'Mons Huygens';

 $lang['MISSION_130'] = 'Sinus La Hire';
 $lang['MISSION_131'] = 'Mons Maraldi';
 $lang['MISSION_132'] = 'Mons Moro';
 $lang['MISSION_133'] = 'Crater Aristarchus';
 $lang['MISSION_134'] = 'Mons Pico';
 $lang['MISSION_135'] = 'Vallis Piton';
 $lang['MISSION_136'] = 'Sinus Rumker';
 $lang['MISSION_137'] = 'Mons Usov';

 $lang['MISSION_140'] = 'Mons Vinogradov';
 $lang['MISSION_141'] = 'Mons Vitruvius';
 $lang['MISSION_142'] = 'Mons Wolff';
 $lang['MISSION_143'] = 'Montes Agricola';
 $lang['MISSION_144'] = 'Montes Alpes';
 $lang['MISSION_145'] = 'Crater Apenninus';
 $lang['MISSION_146'] = 'Montes Archimedes';
 $lang['MISSION_147'] = 'Montes Carpatus';

 $lang['MISSION_150'] = 'Montes Caucasus';
 $lang['MISSION_151'] = 'Mare Cordillera';
 $lang['MISSION_152'] = 'Montes Haemus';
 $lang['MISSION_153'] = 'Crater Harbinger';
 $lang['MISSION_154'] = 'Sinus Pyrenaeus';
 $lang['MISSION_155'] = 'Montes Riphaeus';
 $lang['MISSION_156'] = 'Montes Rook';
 $lang['MISSION_157'] = 'Mare Secchi';

 $lang['MISSION_160'] = 'Montes Spitzbergen';
 $lang['MISSION_161'] = 'Mare Taurus';
 $lang['MISSION_162'] = 'Sinus Teneriffe';
 $lang['MISSION_163'] = 'Montes Harbinger';
 $lang['MISSION_164'] = 'Vallis Rheita';
 $lang['MISSION_165'] = 'Vallis Baade';
 $lang['MISSION_166'] = 'Crater Bohr';
 $lang['MISSION_167'] = 'Vallis Palitzsch';

 $lang['MISSION_170'] = 'Crater Fecunditatis';
 $lang['MISSION_171'] = 'Mare Australe';
 $lang['MISSION_172'] = 'Montes Orientale';
 $lang['MISSION_173'] = 'Sinus Cognitum';
 $lang['MISSION_174'] = 'Mare Crisium';
 $lang['MISSION_175'] = 'Mons Spumans';
 $lang['MISSION_176'] = 'Montes Tranquillitatis';
 $lang['MISSION_177'] = 'Mare Vaporum';

 $lang['MISSION_180'] = 'Crater Aestatis';
 $lang['MISSION_181'] = 'Lacus Bonitatis';
 $lang['MISSION_182'] = 'Montes Felicitatis';
 $lang['MISSION_183'] = 'Sinus Luxuriae';
 $lang['MISSION_184'] = 'Lacus Oblivionis';
 $lang['MISSION_185'] = 'Mons Solitudinis';
 $lang['MISSION_186'] = 'Montes Temporis';
 $lang['MISSION_187'] = 'Crater Timoris';

 /* Mars */
 $lang['MISSION_200'] = 'Crater Al-Qahira';
 $lang['MISSION_201'] = 'Sinus Ares';
 $lang['MISSION_202'] = 'Vallis Auqakuh';
 $lang['MISSION_203'] = 'Crater Bahram';
 $lang['MISSION_204'] = 'Mare Harmakhis';
 $lang['MISSION_205'] = 'Mons Her Desher';
 $lang['MISSION_206'] = 'Sinus Hrad';
 $lang['MISSION_207'] = 'Vallis Huo Hsing';

 $lang['MISSION_210'] = 'Mons Kasei';
 $lang['MISSION_211'] = 'Mare Labou';
 $lang['MISSION_212'] = 'Vallis Maadim';
 $lang['MISSION_213'] = 'Crater Maja';
 $lang['MISSION_214'] = 'Sinus Mamers';
 $lang['MISSION_215'] = 'Vallis Mangala';
 $lang['MISSION_216'] = 'Crater Marte';
 $lang['MISSION_217'] = 'Mare Mawrth';

 $lang['MISSION_220'] = 'Crater Nirgal';
 $lang['MISSION_221'] = 'Vallis Shalbatana';
 $lang['MISSION_222'] = 'Crater Simud';
 $lang['MISSION_223'] = 'Sinus Tiu';
 $lang['MISSION_224'] = 'Vallis Aloysius';
 $lang['MISSION_225'] = 'Crater Ambrosius';
 $lang['MISSION_226'] = 'Mare Barnabas';
 $lang['MISSION_227'] = 'Mare Constantia';

 $lang['MISSION_230'] = 'Vallis Edmondus';
 $lang['MISSION_231'] = 'Mare Eustachius';
 $lang['MISSION_232'] = 'Crater Georgius';
 $lang['MISSION_233'] = 'Sinus Griselda';
 $lang['MISSION_234'] = 'Vallis Gualterius';
 $lang['MISSION_235'] = 'Crater Homfridus';
 $lang['MISSION_236'] = 'Mare Henricus';
 $lang['MISSION_237'] = 'Crater Guglielmus';

 $lang['MISSION_240'] = 'Mare Janetta';
 $lang['MISSION_241'] = 'Vallis Jerominus';
 $lang['MISSION_242'] = 'Crater Josephus';
 $lang['MISSION_243'] = 'Mare Leonardus';
 $lang['MISSION_244'] = 'Sinus Mauritius';
 $lang['MISSION_245'] = 'Crater Nicholaus';
 $lang['MISSION_246'] = 'Vallis Laurentius';
 $lang['MISSION_247'] = 'Mons Octavius';

 $lang['MISSION_250'] = 'Crater Misericordia';
 $lang['MISSION_251'] = 'Vallis Petronella';
 $lang['MISSION_252'] = 'Sinus Sylvanus';
 $lang['MISSION_253'] = 'Crater Reginaldus';
 $lang['MISSION_254'] = 'Vallis Adeipho';
 $lang['MISSION_255'] = 'Sinus Randulphus';
 $lang['MISSION_256'] = 'Crater Xpofer';
 $lang['MISSION_257'] = 'Mare Aegidius';

 $lang['MISSION_260'] = 'Sinus Aeneas';
 $lang['MISSION_261'] = 'Crater Philipus';
 $lang['MISSION_262'] = 'Sinus Beniaminus';
 $lang['MISSION_263'] = 'Vallis Rosamundi';
 $lang['MISSION_264'] = 'Mons Peregrinus';
 $lang['MISSION_265'] = 'Mare Xtianus';
 $lang['MISSION_266'] = 'Vallis Crispianus';
 $lang['MISSION_267'] = 'Crater Clementia';

 $lang['MISSION_270'] = 'Vallis Elizabeta';
 $lang['MISSION_271'] = 'Crater Xtopher';
 $lang['MISSION_272'] = 'Mare Placentia';
 $lang['MISSION_273'] = 'Sinus Gaufridus';
 $lang['MISSION_274'] = 'Crater Stephanus';
 $lang['MISSION_275'] = 'Vallis Xpianus ';
 $lang['MISSION_276'] = 'Mare Girardus';
 $lang['MISSION_277'] = 'Crater Radulphus';

 $lang['MISSION_280'] = 'Crater Xtopherus';
 $lang['MISSION_281'] = 'Vallis Terentius';
 $lang['MISSION_282'] = 'Mons Eamnonn';
 $lang['MISSION_283'] = 'Crater Kadisha';
 $lang['MISSION_284'] = 'Mare Kachine';
 $lang['MISSION_285'] = 'Vallis Oddvar';
 $lang['MISSION_286'] = 'Sinus Radborne';
 $lang['MISSION_287'] = 'Crater Ebenezer';

 /* Asteroid */
 $lang['MISSION_300'] = 'Crater Albococcinea';
 $lang['MISSION_301'] = 'Sinus argentea';
 $lang['MISSION_302'] = 'Vallis Atrococcinea';
 $lang['MISSION_303'] = 'Crater Colorans';
 $lang['MISSION_304'] = 'Mare Cardinalis';
 $lang['MISSION_305'] = 'Mons Brunnea';
 $lang['MISSION_306'] = 'Sinus Chlorantha';
 $lang['MISSION_307'] = 'Vallis Erythrocarpa';

 $lang['MISSION_310'] = 'Mons Ferruginea';
 $lang['MISSION_311'] = 'Mare Colorans';
 $lang['MISSION_312'] = 'Vallis Aurea';
 $lang['MISSION_313'] = 'Crater Atrovirens';
 $lang['MISSION_314'] = 'Sinus lutescens';
 $lang['MISSION_315'] = 'Vallis Maculata';
 $lang['MISSION_316'] = 'Crater Nigrescens';
 $lang['MISSION_317'] = 'Mare Punicea';

 $lang['MISSION_320'] = 'Crater Rosea';
 $lang['MISSION_321'] = 'Vallis Rubiginosa';
 $lang['MISSION_322'] = 'Crater Tinctoria';
 $lang['MISSION_323'] = 'Sinus Sulphurea';
 $lang['MISSION_324'] = 'Vallis Sempervirens';
 $lang['MISSION_325'] = 'Crater Rubicunda';
 $lang['MISSION_326'] = 'Mare Variegata';
 $lang['MISSION_327'] = 'Mare Versicolor';

 $lang['MISSION_330'] = 'Vallis Vinosa';
 $lang['MISSION_331'] = 'Mare Viridescens';
 $lang['MISSION_332'] = 'Crater Citrodora';
 $lang['MISSION_333'] = 'Sinus Foetidissima';
 $lang['MISSION_334'] = 'Vallis Gravaeolens';
 $lang['MISSION_335'] = 'Crater Odorata';
 $lang['MISSION_336'] = 'Mare Suaveolens';
 $lang['MISSION_337'] = 'Crater Ursina';

 $lang['MISSION_340'] = 'Mare Amabile';
 $lang['MISSION_341'] = 'Vallis Praecox ';
 $lang['MISSION_342'] = 'Crater Bella';
 $lang['MISSION_343'] = 'Mare Amoena';
 $lang['MISSION_344'] = 'Sinus Gracilis';
 $lang['MISSION_345'] = 'Crater Formosa';
 $lang['MISSION_346'] = 'Vallis Fragilis';
 $lang['MISSION_347'] = 'Mons Foeniculaceus';

 $lang['MISSION_350'] = 'Crater Blanda';
 $lang['MISSION_351'] = 'Vallis Elegantissima';
 $lang['MISSION_352'] = 'Sinus Imperialis';
 $lang['MISSION_353'] = 'Crater Splendens';
 $lang['MISSION_354'] = 'Vallis Superba';
 $lang['MISSION_355'] = 'Sinus Magnifica';
 $lang['MISSION_356'] = 'Crater Campestris';
 $lang['MISSION_357'] = 'Mare Collina';

 $lang['MISSION_360'] = 'Sinus Insignis';
 $lang['MISSION_361'] = 'Crater Peregrina';
 $lang['MISSION_362'] = 'Sinus Mutabilis';
 $lang['MISSION_363'] = 'Vallis Spectabilis';
 $lang['MISSION_364'] = 'Mons Thermalis';
 $lang['MISSION_365'] = 'Mare Gracilis';
 $lang['MISSION_366'] = 'Vallis Sinensis';
 $lang['MISSION_367'] = 'Crater Pratensis';

 $lang['MISSION_370'] = 'Vallis Mirabilis';
 $lang['MISSION_371'] = 'Crater Umbrosa ';
 $lang['MISSION_372'] = 'Mare Paradoxas';
 $lang['MISSION_373'] = 'Sinus Pulchella';
 $lang['MISSION_374'] = 'Crater Floribunda';
 $lang['MISSION_375'] = 'Vallis Microphylla';
 $lang['MISSION_376'] = 'Mare Parviflora';
 $lang['MISSION_377'] = 'Crater Venusta';

 $lang['MISSION_380'] = 'Crater Monstrosus';
 $lang['MISSION_381'] = 'Vallis Septentrionalis';
 $lang['MISSION_382'] = 'Mons Occidentalis';
 $lang['MISSION_383'] = 'Crater Pulcherrima';
 $lang['MISSION_384'] = 'Mare Spectabilis';
 $lang['MISSION_385'] = 'Vallis Regia';
 $lang['MISSION_386'] = 'Sinus Macrantha';
 $lang['MISSION_387'] = 'Crater Caespitosa';

 /* Soare */
 $lang['MISSION_400'] = 'Crater Albococcinea';
 $lang['MISSION_401'] = 'Sinus argentea';
 $lang['MISSION_402'] = 'Vallis Atrococcinea';
 $lang['MISSION_403'] = 'Crater Colorans';
 $lang['MISSION_404'] = 'Mare Cardinalis';
 $lang['MISSION_405'] = 'Mons Brunnea';
 $lang['MISSION_406'] = 'Sinus Chlorantha';
 $lang['MISSION_407'] = 'Vallis Erythrocarpa';

 $lang['MISSION_410'] = 'Mons Ferruginea';
 $lang['MISSION_411'] = 'Mare Colorans';
 $lang['MISSION_412'] = 'Vallis Aurea';
 $lang['MISSION_413'] = 'Crater Atrovirens';
 $lang['MISSION_414'] = 'Sinus lutescens';
 $lang['MISSION_415'] = 'Vallis Maculata';
 $lang['MISSION_416'] = 'Crater Nigrescens';
 $lang['MISSION_417'] = 'Mare Punicea';

 $lang['MISSION_420'] = 'Crater Rosea';
 $lang['MISSION_421'] = 'Vallis Rubiginosa';
 $lang['MISSION_422'] = 'Crater Tinctoria';
 $lang['MISSION_423'] = 'Sinus Sulphurea';
 $lang['MISSION_424'] = 'Vallis Sempervirens';
 $lang['MISSION_425'] = 'Crater Rubicunda';
 $lang['MISSION_426'] = 'Mare Variegata';
 $lang['MISSION_427'] = 'Mare Versicolor';

 $lang['MISSION_430'] = 'Vallis Vinosa';
 $lang['MISSION_431'] = 'Mare Viridescens';
 $lang['MISSION_432'] = 'Crater Citrodora';
 $lang['MISSION_433'] = 'Sinus Foetidissima';
 $lang['MISSION_434'] = 'Vallis Gravaeolens';
 $lang['MISSION_435'] = 'Crater Odorata';
 $lang['MISSION_436'] = 'Mare Suaveolens';
 $lang['MISSION_437'] = 'Crater Ursina';

 $lang['MISSION_440'] = 'Mare Amabile';
 $lang['MISSION_441'] = 'Vallis Praecox ';
 $lang['MISSION_442'] = 'Crater Bella';
 $lang['MISSION_443'] = 'Mare Amoena';
 $lang['MISSION_444'] = 'Sinus Gracilis';
 $lang['MISSION_445'] = 'Crater Formosa';
 $lang['MISSION_446'] = 'Vallis Fragilis';
 $lang['MISSION_447'] = 'Mons Foeniculaceus';

 $lang['MISSION_450'] = 'Crater Blanda';
 $lang['MISSION_451'] = 'Vallis Elegantissima';
 $lang['MISSION_452'] = 'Sinus Imperialis';
 $lang['MISSION_453'] = 'Crater Splendens';
 $lang['MISSION_454'] = 'Vallis Superba';
 $lang['MISSION_455'] = 'Sinus Magnifica';
 $lang['MISSION_456'] = 'Crater Campestris';
 $lang['MISSION_457'] = 'Mare Collina';

 $lang['MISSION_460'] = 'Sinus Insignis';
 $lang['MISSION_461'] = 'Crater Peregrina';
 $lang['MISSION_462'] = 'Sinus Mutabilis';
 $lang['MISSION_463'] = 'Vallis Spectabilis';
 $lang['MISSION_464'] = 'Mons Thermalis';
 $lang['MISSION_465'] = 'Mare Gracilis';
 $lang['MISSION_466'] = 'Vallis Sinensis';
 $lang['MISSION_467'] = 'Crater Pratensis';

 $lang['MISSION_470'] = 'Vallis Mirabilis';
 $lang['MISSION_471'] = 'Crater Umbrosa ';
 $lang['MISSION_472'] = 'Mare Paradoxas';
 $lang['MISSION_473'] = 'Sinus Pulchella';
 $lang['MISSION_474'] = 'Crater Floribunda';
 $lang['MISSION_475'] = 'Vallis Microphylla';
 $lang['MISSION_476'] = 'Mare Parviflora';
 $lang['MISSION_477'] = 'Crater Venusta';

 $lang['MISSION_480'] = 'Crater Monstrosus';
 $lang['MISSION_481'] = 'Vallis Septentrionalis';
 $lang['MISSION_482'] = 'Mons Occidentalis';
 $lang['MISSION_483'] = 'Crater Pulcherrima';
 $lang['MISSION_484'] = 'Mare Spectabilis';
 $lang['MISSION_485'] = 'Vallis Regia';
 $lang['MISSION_486'] = 'Sinus Macrantha';
 $lang['MISSION_487'] = 'Crater Caespitosa';

 /*
 ** ------------------
 ** MISSION PAGE
 ** ------------------
 */

 $lang['MISSION_TITLE'] = 'MISIUNI';

 $lang['MISSION_NOTE'] = 'Nota: joaca misiunile pentru a castiga bani si experienta necesare avansari in nivele.Cand o misiune este completata 100% vei castiga bani dublu.Daca completezi un continentul %s 100% profitul tau va creste cu %s dolari.';

 $lang['MISSION_ALLIANCE_SIZE'] = 'marimea aliantei';
 $lang['MISSION_GAIN'] = 'Castig';
 $lang['MISSION_PART'] = 'Parte';
 $lang['MISSION_REQUIRED'] = 'Necesar';
 $lang['MISSION_UNLOCK'] = 'Deblocabil la nivelul %s';
 $lang['MISSION_CHANCE_LOOT'] = 'Chance of loot';
 $lang['MISSION_YOU_USED'] = 'Ai utilizat';
 $lang['MISSION_YOU_GAIN'] = 'Ai castigat';
 $lang['MISSION_DOLLAR_AND'] = ' dolari si ';
 $lang['MISSION_ABORTED'] = 'Misiune abandonata!';
 $lang['MISSION_NO_ENERGY'] = 'nu ai suficienta energie pentru a completa misiunea.Asteapta cateva minute pentru a ti se incarca energia.';
 $lang['MISSION_LOW_ALLIANCE'] = ' marimea aliantei tale este prea mica pentru a juca aceasta misiune.';
 $lang['MISSION_MISSING_UNITS'] = ' nu ai armata corespunzatoare pentru a inchei aceasta misiune.';
 $lang['MISSION_MISSING_UNITS_PRICE'] = 'Pretul total pentru a cumpara unitatile este de %s dolari. costul pe ora va creste cu %s dolari.';
 $lang['MISSION_UNITS_LOST'] = 'pe timpul acestei misiuni ai pierdut urmatoarele unitati: ';
 $lang['MISSION_LOOT_WON'] = 'ai castigat urmatoarele';
 $lang['MISSION_UNLOCKED'] = 'acum continua cu lupta de antrenament.';
 $lang['MISSION_CONTINTENT_READY1'] = 'Magnific! ai completat partea %s din %s din continentul %s!';
 $lang['MISSION_CONTINTENT_READY2'] = 'Ai primit %s puncte de aptitudine. ';
 $lang['MISSION_CONTINTENT_READY3'] = 'ai completat toate partile. Continua cu urmatorul continent!';
 $lang['MISSION_CONTINTENT_READY4'] = ' continua cu partea %s de pe acest continent!';
 $lang['MISSION_COMPLETE_TEXT'] = 'ai cucerit urmatoarele continente pana acum!';
 $lang['MISSION_REBEL'] = 'Revolta';
 $lang['MISSION_COMPLETE_PLANET_0'] = 'Excellent! Ai completat toate misiunile de pe Pamant. primesti 100 milioane dolari bonus.';
 $lang['MISSION_COMPLETE_PLANET_1'] = 'Excellent! Ai completat toate misiunile de pe Luna. primesti 500 milioane dolari bonus.';
 $lang['MISSION_COMPLETE_PLANET_2'] = 'Excellent! Ai completat toate misiunile de pe Marte. Ai primit 999 billione dolari bonus.';
 $lang['MISSION_COMPLETE_PLANET_3'] = 'Excellent! Ai completat toate misiunile de pe Asteroid.Primesti 50 puncte de schimb bonus.';

 $lang['MISSION_NO_MISSIONS'] = 'Nici o misiune disponibila!';

/*
** ------------------
** BATTLE PAGE
** ------------------
*/

$lang['BATTLE_TITLE'] = 'Lupta';
$lang['BATTLE_GENERAL_TITLE'] = 'Lupta';
$lang['BATTLE_BOUNTY_TITLE'] = 'Pune Recompensa';

$lang['BATTLE_LOST'] = 'Your %s attacked %s. You lost the battle, taking %s damage, while dealing %s to %s.';
$lang['BATTLE_WON'] = 'Your %s attacked %s. You won the battle, taking %s damage while dealing %s to %s. You took %s dollars and gain %s experience points.';
$lang['BATTLE_DEFENDER_HEALTH_LOW'] = '%s s-a predat temporar deoarece viata este prea mica!';
$lang['BATTLE_ATTACKER_HEALTH_LOW'] = 'Viata ta este prea mica pentru lupta!. Viziteaza spitalul pentru recuperare instant sau asteapta cateva minute pentru vindecare automata.';
$lang['BATTLE_AMMO_LOW'] = 'Nu mai ai munitie! Asteapta cateva minute sa ti se incarce munitia sau foloseste punctel de aptitudine pentru a-i inbunatatii munitia.';
$lang['BATTLE_UNITS_LOST'] = 'pe timpul luptei ai pierdut urmatoarele unitati:';
$lang['BATTLE_BUILDINGS_LOST'] = 'Pe timpul luptei ai pierdut urmatoarele cladiri:';
$lang['BATTLE_DEFENSE_FORCE'] = '%s %s Aparare %s (%s puterea apararii):'; 
$lang['BATTLE_DEFENSE_BASE'] = '%s Baza de aparare:'; 
$lang['BATTLE_ATTACK_FORCE'] = 'Your %s attack %s (%s attack strength)';
$lang['BATTLE_MORE'] = 'mai mult';
$lang['BATTLE_NO_PLAYER_AVAILABLE'] = 'In acest moment nici un jucator nu este disponibil pentru lupta.';
$lang['BATTLE_UNLOCKED'] = 'Lupta este deblocata la nivelul 1.<br/>Completeaza misiunea de antrenament pentru inceput.';
$lang['BATTLE_BOUNTY_UNLOCKED'] = 'Vanatoarea de recompense este disponibila la nivelul %s.';
$lang['BATTLE_ALLY_NO_ATTACK'] = '<b>%s</b> iti este aliat. Nu iti poti ataca aliatii.';
$lang['BATTLE_SURRENDER'] = 'S-a predat temporar';

$lang['BATTLE_NOTE1'] = 'Nota:Lupta impotriva altor jucatori pentru a castiga bani si experienta pentru a trece la nivelul urmator.';
$lang['BATTLE_NOTE2'] = 'Nota: vaneaza alti jucatori ca sa castigi recompensa pusa pe capul lor si castiga experienta pentru a trece nivelul.';

$lang['BATTLE_FORCE_TYPE'] = 'Forta:';
$lang['BATTLE_ENEMIES'] = 'Inamici';
$lang['BATTLE_BOUNTY'] = 'Recompense puse';
$lang['BATTLE_NO_BOUNTY_PLAYERS'] = 'in acest moment nici un jucator cu recompensa pusa nu este disponibil.';
$lang['BATTLE_BOUNTY_BONUS'] = 'Ai primit recompensa de  %s dolari.'; 
$lang['BATTLE_HOSPITAL_BONUS'] = '%s s-a predat temporar.Primesti  %s dolari bonus!'; 
$lang['BATTLE_BOUNTY_LOST'] = 'Ai fost atacat de  %s of %s.Ai pierdut. Pierzi %s dolari, primind %s daune si pierzand %s puncte de experienta.';
$lang['BATTLE_BOUNTY_CONFIRM'] =' pui o recompensa de %s dolari pe capul lui ?';

$lang['BATTLE_CEASE_FIRE_PERIOD'] = 'Perioada de relaxare este activa! Luptele nu sunt posibile. %s';
$lang['BATTLE_AND'] = 'si';
$lang['BATTLE_REBEL_UPDATE1'] = 'treaba buna, ai inceput revolta pentru %s in %s region(s). De acum ii poti vedea situatia.';
$lang['BATTLE_REBEL_UPDATE2'] = 'treaba buna, ai crescut sansa de revolta cu %s lui %s%.';
$lang['BATTLE_REBEL_UPDATE3'] = 'Pacat, nici o regiune disponibila pentru revolta!';

$lang['BATTLE_NO_BOUNTY_MONEY'] = 'nu ai  %s dolari ca sa pui o recompensa pe capul lui  %s.';
$lang['BATTLE_BOUNTY_SET'] = 'Ai pus %s dolari pe capul lui %s si ai primit un punct de experienta. cand %s va fi invins, va pierde  %s puncte de experienta.'; 

$lang['BATTLE_MOON_UNLOCKED'] = 'Bataliile pe luna sunt disponibile de la nivelul 100.';
$lang['BATTLE_MARS_UNLOCKED'] = 'Bataliile pe marte sunt disponibile de la nivelul 150.';
$lang['BATTLE_ASTERIOD_UNLOCKED'] = 'Bataliile pe asteroid sunt disponibile de la nivelul 200.';

$lang['BATTLE_RANGE'] = 'Jucatorii de la lvl %s pana la lvl %s sunt in raza ta de lupta.';

$lang['BATTLE_COMING_SOON'] = 'In curand';

$lang['BATTLE_SUN_STORY'] = 'Bataliile pe Soare au loc de peste 5 ani. 
Oamenii au inceput sa exploreze soarele pentru suprematie. Odata cu invadarea soarelui au descoperit o rasa de extraterestrii
 care sunt mai insetati de razboi si mult mai puternici.De acum depinde doar de lorzii WarQuest  
( jucatori de nivel 249 sau mai mare ) sa reziste invaziei in sistemul nostru solar .deci,toti warlorzii 
formati o UNINE si adunati-va fortele pentru a incepe razboiu impotriva necunoscutilor si puternicilor extraterestrii !';

/*
** ------------------
** UNIT DATA
** ------------------
*/

/* Earth */
$lang['UNIT_GROUP_0']  = 'Armata';
$lang['UNIT_GROUP_2']  = 'Cavalerie';
$lang['UNIT_GROUP_3']  = 'Nave';
$lang['UNIT_GROUP_4']  = 'Avioane';
$lang['UNIT_GROUP_5']  = 'Cetateni';
$lang['UNIT_GROUP_6']  = 'Inteligenta';

/* Moon */
$lang['UNIT_GROUP_7']  = 'Luptatori';
$lang['UNIT_GROUP_8']  = 'Drone';
$lang['UNIT_GROUP_9']  = 'Nave Spatiale';
$lang['UNIT_GROUP_10'] = 'Cetateni';
$lang['UNIT_GROUP_11'] = 'Army';
$lang['UNIT_GROUP_12'] = 'Exploratori';

/* Mars */
$lang['UNIT_GROUP_13']  = 'Drone';
$lang['UNIT_GROUP_14']  = 'Warriors';
$lang['UNIT_GROUP_15']  = 'Nave Spatiale';
$lang['UNIT_GROUP_16']  = 'Exploratori';
$lang['UNIT_GROUP_17'] 	= 'Cetateni';
$lang['UNIT_GROUP_18'] 	= 'Army';

/* Asteroid */
$lang['UNIT_GROUP_19']  = 'Drone';
$lang['UNIT_GROUP_20']  = 'Warriors';
$lang['UNIT_GROUP_21']  = 'Nave Spatiale';
$lang['UNIT_GROUP_22']  = 'Exploratori';
$lang['UNIT_GROUP_23'] 	= 'Cetateni';
$lang['UNIT_GROUP_24'] 	= 'Army';


/* Calvary (Earth) - Group 2 */
$lang['UNIT_1'] = 'Minigunner';
$lang['UNIT_2'] = 'Recruit';
$lang['UNIT_3'] = 'Marines';
$lang['UNIT_4'] = 'Paratrooper';
$lang['UNIT_5'] = 'Medic';
$lang['UNIT_6'] = 'Grenadier';
$lang['UNIT_7'] = 'Military police';
$lang['UNIT_8'] = 'Navy Seal';
$lang['UNIT_9'] = 'Machine Gunner';
$lang['UNIT_10'] = 'Rocketlaunchers';
$lang['UNIT_11'] = 'Captain';
$lang['UNIT_12'] = 'Commando';
$lang['UNIT_13'] = 'UAV Squad';
$lang['UNIT_14'] = 'XM-25 Gunner';
$lang['UNIT_15'] = 'Tank Demolisher';
$lang['UNIT_16'] = 'Navy Seal';
$lang['UNIT_17'] = 'FELIN Combat Infantry';
$lang['UNIT_18'] = 'Heavy Assault Squad';
$lang['UNIT_19'] = 'Force Warrior Squad';
$lang['UNIT_20'] = 'Machine Gun Squad';
$lang['UNIT_21'] = 'Sniper Team';
$lang['UNIT_22'] = 'Grenade Squad';
$lang['UNIT_23'] = 'Rail Gun Troopers';
$lang['UNIT_24'] = 'Mobile Marines';
$lang['UNIT_101'] = 'Military Car';
$lang['UNIT_102'] = 'Humvee';
$lang['UNIT_103'] = 'Truck';
$lang['UNIT_104'] = 'Light Artillery';
$lang['UNIT_105'] = 'Calvary Carrier';
$lang['UNIT_106'] = 'MGM-51 Shillelagh';
$lang['UNIT_107'] = 'Calvary Transporter';
$lang['UNIT_108'] = 'Assault Vehicle';
$lang['UNIT_109'] = 'SSM Launcher';
$lang['UNIT_110'] = 'Light Hovercraft';
$lang['UNIT_111'] = 'M1 Abrams Tank';
$lang['UNIT_112'] = 'Calvary Vehicle';
$lang['UNIT_113'] = 'Anti-ambush Vehicle';
$lang['UNIT_114'] = 'Heavy Tank';
$lang['UNIT_115'] = 'Leopard 1A1';
$lang['UNIT_116'] = 'HG-544 Vehicle';
$lang['UNIT_117'] = 'Tracked Carrier';
$lang['UNIT_118'] = 'Combat Vehicle';
$lang['UNIT_119'] = 'Hellfire Tank';
$lang['UNIT_120'] = 'Battle Tank';
$lang['UNIT_121'] = 'Mounted Combat System';
$lang['UNIT_122'] = 'Self Propelled Artillery';
$lang['UNIT_123'] = 'Chaparral Tank';
$lang['UNIT_124'] = 'M198 Howitzer';
$lang['UNIT_125'] = 'Heavy Artillery';
$lang['UNIT_126'] = 'Missile Launcher';
$lang['UNIT_127'] = 'Mobile Anti Aircraft';

/* Navy (Earth) - Group 3 */
$lang['UNIT_201'] = 'Rubber boat';
$lang['UNIT_202'] = 'Transport';
$lang['UNIT_203'] = 'Frigate';
$lang['UNIT_204'] = 'Naval Tanker';
$lang['UNIT_205'] = 'Naval Destroyer';
$lang['UNIT_206'] = 'M80 Stiletto';
$lang['UNIT_207'] = 'Submarine';
$lang['UNIT_208'] = 'Helicopter Carrier';
$lang['UNIT_209'] = 'Battleship';
$lang['UNIT_210'] = 'Houbei Missile ship';
$lang['UNIT_211'] = 'Horizon Frigate';
$lang['UNIT_212'] = 'Type 13 Frigate';
$lang['UNIT_213'] = 'Destroyer';
$lang['UNIT_214'] = 'Scorpene Submarine';
$lang['UNIT_215'] = 'DDG 1000 Destroyer';
$lang['UNIT_216'] = 'Elite Dreadnought';
$lang['UNIT_217'] = 'SPY-1D Destroyer';
$lang['UNIT_218'] = 'Sea Fighter';
$lang['UNIT_219'] = 'HSV-2 Swift';
$lang['UNIT_220'] = 'Missile Cruiser';
$lang['UNIT_221'] = 'UXV Combatant';
$lang['UNIT_222'] = 'Anti Submarine Ship';
$lang['UNIT_223'] = 'Kanimbla AT ship';
$lang['UNIT_224'] = 'Aircraft Carrier';
$lang['UNIT_225'] = 'Landing Platform Dock';
$lang['UNIT_226'] = 'Type 23 Frigate';
$lang['UNIT_227'] = 'Ohio Submarine';
$lang['UNIT_228'] = 'Nuclear Cruiser';

/* Airforce (Earth) - Group 4 */
$lang['UNIT_301'] = 'Cessna 172';
$lang['UNIT_302'] = 'C-17 Cargo plane';
$lang['UNIT_303'] = 'V-22A Osprey Gunship';
$lang['UNIT_304'] = 'AV-8B Harrier Jet';
$lang['UNIT_305'] = 'Comanche Helicopter';
$lang['UNIT_306'] = 'Havoc Helicopter';
$lang['UNIT_307'] = 'Saab JA37 Viggen';
$lang['UNIT_308'] = 'SR-71 Blackbird';
$lang['UNIT_309'] = 'Apache Helicopter';
$lang['UNIT_310'] = 'B-2 Spirit Bomber';
$lang['UNIT_311'] = 'F-18 Super Hornet';
$lang['UNIT_313'] = 'F-15 Silent Eagle';
$lang['UNIT_314'] = 'B-1 Lancer';
$lang['UNIT_316'] = 'F3 Interceptor';
$lang['UNIT_318'] = 'F-16 Falcon';
$lang['UNIT_319'] = 'PAK-FA Fighter';
$lang['UNIT_320'] = 'F-117 Nighthawk';
$lang['UNIT_321'] = 'Boeing NGB Bomber';
$lang['UNIT_322'] = 'F-14 Tomcat';
$lang['UNIT_323'] = 'F-35 Lightning II';
$lang['UNIT_324'] = 'B-52 Stratofortress';
$lang['UNIT_325'] = 'F-22 Raptor';
$lang['UNIT_326'] = 'Trident II Missile';

/* Citizens (Earth) - Group 5 */
$lang['UNIT_401'] = 'Construction Engineer';
$lang['UNIT_402'] = 'Mechanic Engineer';
$lang['UNIT_403'] = 'Lab Engineer';
$lang['UNIT_404'] = 'Manager';
$lang['UNIT_405'] = 'Doctor';
$lang['UNIT_406'] = 'Cook';
$lang['UNIT_407'] = 'Security Guard';

/* Intel (Earth) - Group 6 */
$lang['UNIT_501'] = 'Surveillance Camera';
$lang['UNIT_502'] = 'Marine Intelligence';
$lang['UNIT_503'] = 'Mini Air Drone';
$lang['UNIT_504'] = 'G343 Spy Robot';
$lang['UNIT_505'] = 'Intelligence A3 Crusader';
$lang['UNIT_506'] = 'Spy Fishing Ship';
$lang['UNIT_507'] = 'Hawk Eye';
$lang['UNIT_508'] = 'UK-80 AWACS';
$lang['UNIT_509'] = 'AS-102 Stealth Ship';
$lang['UNIT_510'] = 'US-101 Predator';
$lang['UNIT_511'] = 'Heron Drone';
$lang['UNIT_512'] = 'HG101 Satellite';


/* Warriors (Moon) - Group 7 */
$lang['UNIT_700'] = 'Ahiga I';
$lang['UNIT_701'] = 'Aindrias II';
$lang['UNIT_702'] = 'Aloisius III';
$lang['UNIT_703'] = 'Aloysius IV';
$lang['UNIT_704'] = 'Alvar V';
$lang['UNIT_705'] = 'Aindrias VI';
$lang['UNIT_706'] = 'Cadomedo VII';
$lang['UNIT_707'] = 'Catigernus VIII';
$lang['UNIT_708'] = 'Catutigernos IX';
$lang['UNIT_709'] = 'Cedric X';
$lang['UNIT_710'] = 'Cheveyo XI';

/* Drones (Moon) - Group 8 */
$lang['UNIT_800'] = 'Basic Rover I';
$lang['UNIT_801'] = 'Lunar Transporter II';
$lang['UNIT_802'] = 'Moon Explorer III';
$lang['UNIT_803'] = 'Moon Havostar IV';
$lang['UNIT_804'] = 'Mobile Lab V';
$lang['UNIT_805'] = 'Transporter VI';
$lang['UNIT_805'] = 'Space Crane VII';
$lang['UNIT_806'] = 'Moon Buggy VIII';
$lang['UNIT_807'] = 'Fuel Transporter IX';
$lang['UNIT_808'] = 'Fuel Explorer X';
$lang['UNIT_809'] = 'Moon Explorer XI';
$lang['UNIT_810'] = 'Transporter XII';

/* Spacecrafts (Moon) - Group 9 */
$lang['UNIT_900'] = 'Moon Cruiser';
$lang['UNIT_901'] = 'Millennium Falcon';
$lang['UNIT_902'] = 'Ebon Hawk';
$lang['UNIT_903'] = 'Transport Robot';
$lang['UNIT_904'] = 'Slave I';
$lang['UNIT_905'] = 'Assault ship';
$lang['UNIT_906'] = 'Corellian corvette';
$lang['UNIT_907'] = 'War Hawk Shadow';
$lang['UNIT_908'] = 'Solar Spacecraft';
$lang['UNIT_909'] = 'Royal starship';
$lang['UNIT_910'] = 'Theta-Class Shuttle';
$lang['UNIT_911'] = 'Trade Cruiser';
$lang['UNIT_912'] = 'Sith Infiltrator';
$lang['UNIT_913'] = 'Imperial landing craft';
$lang['UNIT_914'] = 'Star Skiff II';
$lang['UNIT_915'] = 'Star Destroyer';
$lang['UNIT_916'] = 'Flag Ship';

/* Citizens (Moon) - Group 10 */
$lang['UNIT_1000'] = 'Astronaut';
$lang['UNIT_1001'] = 'Female';
$lang['UNIT_1002'] = 'Male';

/* Explorers (Moon) - Group 12 */
$lang['UNIT_1200'] = 'Explorer Satellite';
$lang['UNIT_1201'] = 'Explorer Ship';
$lang['UNIT_1202'] = 'Short Range Radar';
$lang['UNIT_1203'] = 'Deepspace Explorer';
$lang['UNIT_1204'] = 'Planet Explorer';
$lang['UNIT_1205'] = 'Space Elevator';
$lang['UNIT_1206'] = 'Astronaut Explorer';
$lang['UNIT_1207'] = 'Long Range Rader';
$lang['UNIT_1208'] = 'Deepspace Relay Station';
$lang['UNIT_1209'] = 'Lightspeed Explorer';
$lang['UNIT_1210'] = 'Planet Destroyer';
$lang['UNIT_1211'] = 'Galaxy Explorer';


/* Drones (Mars) - Group 13 */
$lang['UNIT_1300'] = 'Loyce I';
$lang['UNIT_1301'] = 'Labhaoise II';
$lang['UNIT_1302'] = 'Kondo III';
$lang['UNIT_1303'] = 'Kiaskari VI';
$lang['UNIT_1304'] = 'Khalon V';
$lang['UNIT_1305'] = 'Hida VI';
$lang['UNIT_1306'] = 'Irapeke VII';
$lang['UNIT_1307'] = 'Heriberto VIII';
$lang['UNIT_1308'] = 'Kerbasi IX';
$lang['UNIT_1309'] = 'Karna X';

/* Warriors (Mars) - Group 14 */
$lang['UNIT_1400'] = 'Gervaso I';
$lang['UNIT_1401'] = 'Galtero II';
$lang['UNIT_1402'] = 'Gunther III';
$lang['UNIT_1403'] = 'Donnachadh VI';
$lang['UNIT_1404'] = 'Duncan V';
$lang['UNIT_1405'] = 'Eskiminzin VI';
$lang['UNIT_1406'] = 'Fenyang VII';
$lang['UNIT_1407'] = 'Finnegan VIII';
$lang['UNIT_1408'] = 'Clodovea IX';
$lang['UNIT_1409'] = 'Eferhilda X';

/* Spacecrafts (Mars) - Group 15 */
$lang['UNIT_1500'] = 'Mars Cruiser I';
$lang['UNIT_1501'] = 'Cocon II';
$lang['UNIT_1502'] = 'Hawk Eye III';
$lang['UNIT_1503'] = 'Ariane IV';
$lang['UNIT_1504'] = 'Gyro V';
$lang['UNIT_1505'] = 'Miner VI';
$lang['UNIT_1506'] = 'Jannus VII';
$lang['UNIT_1507'] = 'Tango VIII';
$lang['UNIT_1508'] = 'Rader IX';
$lang['UNIT_1509'] = 'Eloy  X';

/* Explorers (Mars) - Group 16 */
$lang['UNIT_1600'] = 'Cadabyr I';
$lang['UNIT_1601'] = 'Chadwick II';
$lang['UNIT_1602'] = 'Calhoun III';
$lang['UNIT_1603'] = 'Cheveyo IV';
$lang['UNIT_1604'] = 'Clancy V';
$lang['UNIT_1605'] = 'Clodovea VI';
$lang['UNIT_1606'] = 'Cochise VII';
$lang['UNIT_1607'] = 'Czarine VIII';
$lang['UNIT_1608'] = 'Caddawyc IX';
$lang['UNIT_1609'] = 'Chlodwig X';

/* Citizens (Mars) - Group 17 */
$lang['UNIT_1700'] = 'Astronaut';
$lang['UNIT_1701'] = 'Female';
$lang['UNIT_1702'] = 'Male';


/* Warriors (Asteroid) - Group 19 */
$lang['UNIT_1900'] = 'Swify I';
$lang['UNIT_1901'] = 'Euhm II';
$lang['UNIT_1902'] = 'Mirageman III';
$lang['UNIT_1903'] = 'Vereldor IV';
$lang['UNIT_1904'] = 'Maelsius V';
$lang['UNIT_1905'] = 'Suldan VI';
$lang['UNIT_1906'] = 'Jonesy VII';
$lang['UNIT_1907'] = 'Pendejo VIII';
$lang['UNIT_1908'] = 'Vorpal IX';
$lang['UNIT_1909'] = 'Iyona X';

/* Warriors (Asteroid) - Group 20 */
$lang['UNIT_2000'] = 'Grandmaster I';
$lang['UNIT_2001'] = 'Courage II';
$lang['UNIT_2002'] = 'Hero III';
$lang['UNIT_2003'] = 'Pious IV';
$lang['UNIT_2004'] = 'Stalwart V';
$lang['UNIT_2005'] = 'Bombadil VI';
$lang['UNIT_2006'] = 'Happyelf VII';
$lang['UNIT_2007'] = 'Rainbow VIII';
$lang['UNIT_2008'] = 'MerryLad IX';
$lang['UNIT_2009'] = 'Drenar X';

/* Spacecrafts (Asteroid) - Group 21 */
$lang['UNIT_2100'] = 'Halvilion I';
$lang['UNIT_2101'] = 'Menelaus II';
$lang['UNIT_2102'] = 'Ultimatum III';
$lang['UNIT_2103'] = 'Erudur IV';
$lang['UNIT_2104'] = 'Banbelion V';
$lang['UNIT_2105'] = 'Nimtharadon VI';
$lang['UNIT_2106'] = 'Voronthil VII';
$lang['UNIT_2107'] = 'Anion VIII';
$lang['UNIT_2108'] = 'Partharaon IX';
$lang['UNIT_2109'] = 'Erudil X';

/* Explorers (Asteroid) - Group 22 */
$lang['UNIT_2200'] = 'Girlyman I';
$lang['UNIT_2201'] = 'Wuss II';
$lang['UNIT_2202'] = 'Sissy III';
$lang['UNIT_2203'] = 'Tauren IV';
$lang['UNIT_2204'] = 'Hykon V';
$lang['UNIT_2205'] = 'Talenx VI';
$lang['UNIT_2206'] = 'DDazra VII';
$lang['UNIT_2207'] = 'Hexa VIII';
$lang['UNIT_2208'] = 'Marest IX';
$lang['UNIT_2209'] = 'Rawrgrable X';

/* Citizens (Asteroid) - Group 23 */
$lang['UNIT_2300'] = 'Astronaut';
$lang['UNIT_2301'] = 'Female';
$lang['UNIT_2302'] = 'Male';

/*
** ------------------
** UNIT PAGE
** ------------------
*/

$lang['UNIT_TITLE'] = 'UNITS';

$lang['UNIT_NOTE_1'] = 'Nota: Cumpara soldati pentru a putea efectua misiunea.';
$lang['UNIT_NOTE_2'] = 'Nota: Cumpara cavalerie pentru a-ti imbunatatii puterea cavaleriei. Lupta castga sau fura bani de la adversari.';
$lang['UNIT_NOTE_3'] = 'Note: Cumpara nave pentru a-ti imbunatatii puterea navala. Lupta castga sau fura bani de la adversari.';
$lang['UNIT_NOTE_4'] = 'Note: Cumpara avioane pentru a-ti imbunatatii puterea aeriana. Lupta castiga sau fura bani de la adversari.';
$lang['UNIT_NOTE_6'] = 'Note: Cumpara forte inteligente pentru a-ti imbunatatii puterea diplomatica. lupta, castiga ca sa incepi revolta in regiunile inamice de pe pamant si fura bani de la inamici  \'s Trasquera or SwissCore bank account.';

$lang['UNIT_NOTE_8'] = 'Note: Cumpara drone lunare pentru a-ti imbunatati forta dronelor. Lupta, casiga si fura bani de la inamici \'s cash account.';
$lang['UNIT_NOTE_7'] = 'Note: Cumpara wariori lunari pentru a-ti imbunatati forta wariorilor. Lupta, casiga si fura bani de la inamici \'s cash account.';
$lang['UNIT_NOTE_9'] = 'Note: Cumpara nave spatiale lunare pentru a-ti imbunatati forta aeriana. Lupta, casiga si fura bani de la inamici \'s cash account.';
$lang['UNIT_NOTE_12'] = 'Note: Cumpara exploratori lunari pentru a-ti imbunatati forta de explorare. lupta, castiga ca sa incepi revolta in regiunile inamice de pe luna si fura bani de la inamici  \'s Trasquera or SwissCore bank account.';

$lang['UNIT_NOTE_13'] = 'Note: Cumpara drone martiene pentru a-ti imbunatati forta dronelor. Lupta, casiga si fura bani de la inamici \'s cash account.';
$lang['UNIT_NOTE_14'] = 'Note: Cumpara wariori martieni pentru a-ti imbunatati forta wariorilor. Lupta, casiga si fura bani de la inamici \'s cash account.';;
$lang['UNIT_NOTE_15'] = 'Note: Cumpara nave spatiale martiene pentru a-ti imbunatati forta aeriana. Lupta, casiga si fura bani de la inamici \'s cash account.';
$lang['UNIT_NOTE_16'] = 'Note: Cumpara exploratori martieni pentru a-ti imbunatati forta de explorare. lupta, castiga ca sa incepi revolta in regiunile inamice de pe marte si fura bani de la inamici  \'s Trasquera or SwissCore bank account.';


$lang['UNIT_NOTE_19'] = 'Note: Cumpara drone asteroide pentru a-ti imbunatati forta dronelor. Lupta, casiga si fura bani de la inamici \'s cash account.';
$lang['UNIT_NOTE_20'] = 'Note: Cumpara wariori asteroizi pentru a-ti imbunatati forta wariorilor. Lupta, casiga si fura bani de la inamici \'s cash account.';
$lang['UNIT_NOTE_21'] = 'Note: Cumpara nave spatiale asteroide pentru a-ti imbunatati forta aeriana. Lupta, casiga si fura bani de la inamici \'s cash account.';
$lang['UNIT_NOTE_22'] = 'Note: Cumpara exploratori asteroizi pentru a-ti imbunatati forta de explorare. Batlle, win to start rebellions on Asteroid and steal some money from your opponent\'s Trasquera or SwissCore bank account.';

$lang['UNIT_NOTE_25'] = 'Note: Cumpara drone solare pentru a-ti imbunatati forta dronelor.';
$lang['UNIT_NOTE_26'] = 'Note: Cumpara wariori solari pentru a-ti imbunatati forta wariorilor.';
$lang['UNIT_NOTE_27'] = 'Note: Cumpara nave spatiale solare pentru a-ti imbunatati forta aeriana.';
$lang['UNIT_NOTE_28'] = 'Note: Cumpara exploratori solari pentru a-ti imbunatati forta de explorare.';

$lang['UNIT_DISBAND'] = 'ai vandut %s %s pentru %s. inca %s disponibili.';
$lang['UNIT_DISBAND_FAILED'] = 'nu ai %s %s. inca %s disponibil.';

$lang['UNIT_DEPLOY'] = 'You deploy %s %s for %s. acum %s deployed.';
$lang['UNIT_NO_UPKEEP'] = 'insuficient profit pentru a cumpara %s %s.';
$lang['UNIT_NO_FUNDS'] = 'insuficienti bani pentru a cumpara %s %s pentru %s.';
$lang['UNIT_MAX'] = 'Nu mai mult de %s %s(s) permisi!';

$lang['UNITS_NO_UNITS'] = 'nici o unitate disponibila!';

/*
** ------------------
** BUILDING DATA
** ------------------
*/

/* Earth Buildings */
$lang['BUILDING_GROUP_1']  = 'Profit';
$lang['BUILDING_GROUP_2']  = 'Aparare';
$lang['BUILDING_GROUP_3']  = 'Energie';
$lang['BUILDING_GROUP_4']  = 'Discont';
$lang['BUILDING_GROUP_5']  = 'Mentenanta';

/* Moon Buildings */
$lang['BUILDING_GROUP_6']  = 'Profit';
$lang['BUILDING_GROUP_7']  = 'Aparare';
$lang['BUILDING_GROUP_8']  = 'Energie';
$lang['BUILDING_GROUP_9']  = 'Discont';
$lang['BUILDING_GROUP_10'] = 'Mentenanta';

/* Mars Buildings */
$lang['BUILDING_GROUP_11'] = 'Profit';
$lang['BUILDING_GROUP_12'] = 'Aparare';
$lang['BUILDING_GROUP_13'] = 'Energy';
$lang['BUILDING_GROUP_14'] = 'Discont';
$lang['BUILDING_GROUP_15'] = 'Mentenanta';

/* Asteroid Buildings */
$lang['BUILDING_GROUP_16'] = 'Profit';
$lang['BUILDING_GROUP_17'] = 'Aparare';
$lang['BUILDING_GROUP_18'] = 'Energie';
$lang['BUILDING_GROUP_19'] = 'Discont';
$lang['BUILDING_GROUP_20'] = 'Mentenanta';



/* Income (Earth) - Group 1 */
$lang['BUILDING_1']  = 'Supply Depot';
$lang['BUILDING_3']  = 'Refinery';
$lang['BUILDING_6']  = 'Weapons Factory';
$lang['BUILDING_8']  = 'Communications Center';
$lang['BUILDING_24'] = 'Bio Science Factory';
$lang['BUILDING_12'] = 'Oil Rig';
$lang['BUILDING_14'] = 'Military Research Lab';
$lang['BUILDING_16'] = 'Nuclear Testing Facility';
$lang['BUILDING_25'] = 'Water Treatment Facility';
$lang['BUILDING_17'] = 'Solar Satellite Network';

/* Defence (Earth) - Group 2 */
$lang['BUILDING_2']  = 'Bunker';
$lang['BUILDING_21'] = 'Sea minefield';
$lang['BUILDING_5']  = 'Guard tower';
$lang['BUILDING_51'] = 'Embassy';
$lang['BUILDING_7']  = 'Short range launcher';
$lang['BUILDING_22'] = 'Torpedo launcher';
$lang['BUILDING_9']  = 'Long range launcher';
$lang['BUILDING_11'] = 'Land minefield';
$lang['BUILDING_52'] = 'Intel command center';
$lang['BUILDING_20'] = 'Airfield';
$lang['BUILDING_23'] = 'Submarine factory';
$lang['BUILDING_15'] = 'Magnetic cannon';
$lang['BUILDING_53'] = 'Drone control center';
$lang['BUILDING_54'] = 'Cyberspace warfare';

/* Energy (Earth) - Group 3 */
$lang['BUILDING_4']  = 'Solar power unit';
$lang['BUILDING_10'] = 'Mobile generator';
$lang['BUILDING_13'] = 'Gas power facility';
$lang['BUILDING_18'] = 'Eolic power farm';
$lang['BUILDING_19'] = 'Oil extractors';
$lang['BUILDING_26'] = 'Solar power facility';
$lang['BUILDING_27'] = 'Offshore eolic power farm';
$lang['BUILDING_28'] = 'Geothermal energy facility';
$lang['BUILDING_35'] = 'Hydro power dam';
$lang['BUILDING_39'] = 'Nuclear power facility';

/* Discount (Earth) - Group 4 */
$lang['BUILDING_29'] = 'Army field mess';
$lang['BUILDING_40'] = 'Military supply depot';
$lang['BUILDING_37'] = 'Mobile hospital';
$lang['BUILDING_38'] = 'Command center';
$lang['BUILDING_30'] = 'Military bootcamp';
$lang['BUILDING_31'] = 'Military academy';
$lang['BUILDING_32'] = 'Recreation facility';
$lang['BUILDING_33'] = 'Military Statue';
$lang['BUILDING_34'] = 'Military headquarters';
$lang['BUILDING_36'] = 'President\'s office';

/* Maintenance (Earth) - Group 5 */
$lang['BUILDING_41'] = 'Road maintenance';
$lang['BUILDING_42'] = 'Bridge maintenance';
$lang['BUILDING_43'] = 'Transport vehicle garage';
$lang['BUILDING_44'] = 'Helicopter hangar';
$lang['BUILDING_45'] = 'Vehicle garage';
$lang['BUILDING_46'] = 'Navy ship dock';
$lang['BUILDING_47'] = 'Building maintenance';
$lang['BUILDING_48'] = 'Submarine dock';
$lang['BUILDING_49'] = 'Power facility maintenance';
$lang['BUILDING_50'] = 'Airplane hangar';

/* Income (Moon) - Group 6 */
$lang['BUILDING_600'] = 'General base';
$lang['BUILDING_601'] = 'Explore & Research center';
$lang['BUILDING_602'] = 'Personel quarters';
$lang['BUILDING_603'] = 'Oxygen factory';
$lang['BUILDING_604'] = 'Water factory';
$lang['BUILDING_605'] = 'Communication center';
$lang['BUILDING_606'] = 'Greenhouse';
$lang['BUILDING_607'] = 'Construction factory';
$lang['BUILDING_608'] = 'Metal extraction center';
$lang['BUILDING_609'] = 'Spacecraft launch center';
$lang['BUILDING_610'] = 'Lunar hospital';
$lang['BUILDING_611'] = 'Terraforming centre';

/* Defence (Moon) - Group 7 */
$lang['BUILDING_700'] = 'Defence research center';
$lang['BUILDING_701'] = 'Drone factory';
$lang['BUILDING_702'] = 'Short range missile';
$lang['BUILDING_703'] = 'Warrior factory';
$lang['BUILDING_704'] = 'Allarm system';
$lang['BUILDING_705'] = 'Long range laser';
$lang['BUILDING_706'] = 'Spacecraft factory';
$lang['BUILDING_707'] = 'Energy shield';
$lang['BUILDING_708'] = 'Nuclear missile launcher';
$lang['BUILDING_709'] = 'Tasers weapon factory';
$lang['BUILDING_710'] = 'Photonic weapon factory';
$lang['BUILDING_711'] = 'Mobile android defender';
$lang['BUILDING_712'] = 'Colony defence shield';
$lang['BUILDING_713'] = 'Underground factory';
$lang['BUILDING_714'] = 'Spacecraft launcher';

/* Energy (Moon) - Group 8 */
$lang['BUILDING_800'] = 'Gas research center';
$lang['BUILDING_801'] = 'Petroleum research center';
$lang['BUILDING_802'] = 'Gas extractors';
$lang['BUILDING_803'] = 'Petroleum extractors';
$lang['BUILDING_804'] = 'Solar power facility';
$lang['BUILDING_805'] = 'Gas power facility';
$lang['BUILDING_806'] = 'Mini orbit solar facility';
$lang['BUILDING_807'] = 'Nuclear power facility';
$lang['BUILDING_808'] = 'Large orbit solar facility';
$lang['BUILDING_809'] = 'Mini space colony';
$lang['BUILDING_810'] = 'Solar grid system';
$lang['BUILDING_811'] = 'Large space colony';

/* Discount (Moon) - Group 9 */
$lang['BUILDING_900'] = 'Skyscraper';
$lang['BUILDING_901'] = 'Bridge';
$lang['BUILDING_902'] = 'Village';
$lang['BUILDING_903'] = 'Headquarters';
$lang['BUILDING_904'] = 'Volcano base';
$lang['BUILDING_905'] = 'City';
$lang['BUILDING_906'] = 'Bootcamp';
$lang['BUILDING_907'] = 'Missile launchers';
$lang['BUILDING_908'] = 'President\'s Office';
$lang['BUILDING_909'] = 'Military academy';
$lang['BUILDING_910'] = 'Recreation facility';
$lang['BUILDING_911'] = 'Command center';

/* Maintenance (Moon) - Group 10 */
$lang['BUILDING_1000'] = 'Architect design center';
$lang['BUILDING_1001'] = 'Drone repair center';
$lang['BUILDING_1002'] = 'Missile repair center';
$lang['BUILDING_1003'] = 'Explore repair center';
$lang['BUILDING_1004'] = 'Vehicle repair center';
$lang['BUILDING_1005'] = 'Warrior repair center';
$lang['BUILDING_1006'] = 'Infra repair center';
$lang['BUILDING_1007'] = 'Unit repair center';
$lang['BUILDING_1008'] = 'Power repair center';
$lang['BUILDING_1009'] = 'Robot repair center';

/* Income (Mars) - Group 11 */
$lang['BUILDING_1100'] = 'General base';
$lang['BUILDING_1101'] = 'Research center';
$lang['BUILDING_1102'] = 'Oxygen factory';
$lang['BUILDING_1103'] = 'Personel quarters';
$lang['BUILDING_1104'] = 'Water factory';
$lang['BUILDING_1105'] = 'Metal extration center';
$lang['BUILDING_1106'] = 'Communication center';
$lang['BUILDING_1107'] = 'Converance center';
$lang['BUILDING_1108'] = 'Greenhouse';
$lang['BUILDING_1109'] = 'Hotel';

/* Defense (Mars) - Group 12 */
$lang['BUILDING_1200'] = 'Research center';
$lang['BUILDING_1201'] = 'Weapon factory';
$lang['BUILDING_1202'] = 'Short range missile';
$lang['BUILDING_1203'] = 'Warrior factory';
$lang['BUILDING_1204'] = 'Allarm system';
$lang['BUILDING_1205'] = 'Spacecraft factory';
$lang['BUILDING_1206'] = 'Long range launcher';
$lang['BUILDING_1207'] = 'Explorer factory';
$lang['BUILDING_1208'] = 'Drone factory';
$lang['BUILDING_1209'] = 'Warrior factory';
$lang['BUILDING_1210'] = 'Alien Detect unit';

/* Energy (Mars) - Group 13 */
$lang['BUILDING_1300'] = 'Energy research center';
$lang['BUILDING_1301'] = 'Gas power facility';
$lang['BUILDING_1302'] = 'Petroleum research center';
$lang['BUILDING_1303'] = 'Petroleum extractors';
$lang['BUILDING_1304'] = 'Solar power facility';
$lang['BUILDING_1305'] = 'Gas extractors';
$lang['BUILDING_1306'] = 'Mining center';
$lang['BUILDING_1307'] = 'Nuclear power facility';
$lang['BUILDING_1308'] = 'Large orbit solar facility';
$lang['BUILDING_1309'] = 'Large mars colony';

/* Discount (Mars) - Group 14 */
$lang['BUILDING_1400'] = 'Training center';
$lang['BUILDING_1401'] = 'Terraforming center';
$lang['BUILDING_1402'] = 'Village';
$lang['BUILDING_1403'] = 'Headquarters';
$lang['BUILDING_1404'] = 'Supply depot';
$lang['BUILDING_1405'] = 'Construction unit';
$lang['BUILDING_1406'] = 'Bootcamp';
$lang['BUILDING_1407'] = 'President\'s office';
$lang['BUILDING_1408'] = 'Command center';

/* Maintenance (Mars) - Group 15 */
$lang['BUILDING_1500'] = 'Architect design center';
$lang['BUILDING_1501'] = 'Drone repair center';
$lang['BUILDING_1502'] = 'Missile repair center';
$lang['BUILDING_1503'] = 'Explore repair center';
$lang['BUILDING_1504'] = 'Vehicle repair center';
$lang['BUILDING_1505'] = 'Warrior repair center';
$lang['BUILDING_1506'] = 'Infra repair center';
$lang['BUILDING_1507'] = 'Unit repair center';
$lang['BUILDING_1508'] = 'Power repair center';
$lang['BUILDING_1509'] = 'Robot repair center';

/* Income (Asteroid) - Group 16 */
$lang['BUILDING_1600'] = 'General base';
$lang['BUILDING_1601'] = 'Research center';
$lang['BUILDING_1602'] = 'Oxygen factory';
$lang['BUILDING_1603'] = 'Personel quarters';
$lang['BUILDING_1604'] = 'Water factory';
$lang['BUILDING_1605'] = 'Metal extration center';
$lang['BUILDING_1606'] = 'Communication center';
$lang['BUILDING_1607'] = 'Converance center';
$lang['BUILDING_1608'] = 'Greenhouse';
$lang['BUILDING_1609'] = 'Hotel';

/* Defense (Asteroid) - Group 17 */
$lang['BUILDING_1700'] = 'Research center';
$lang['BUILDING_1701'] = 'Weapon factory';
$lang['BUILDING_1702'] = 'Short range missile';
$lang['BUILDING_1703'] = 'Warrior factory';
$lang['BUILDING_1704'] = 'Allarm system';
$lang['BUILDING_1705'] = 'Spacecraft factory';
$lang['BUILDING_1706'] = 'Long range launcher';
$lang['BUILDING_1707'] = 'Explorer factory';
$lang['BUILDING_1708'] = 'Drone factory';
$lang['BUILDING_1709'] = 'Warrior factory';

/* Energy (Asteroid) - Group 18 */
$lang['BUILDING_1800'] = 'Energy research center';
$lang['BUILDING_1801'] = 'Gas power facility';
$lang['BUILDING_1802'] = 'Petroleum research center';
$lang['BUILDING_1803'] = 'Petroleum extractors';
$lang['BUILDING_1804'] = 'Solar power facility';
$lang['BUILDING_1805'] = 'Gas extractors';
$lang['BUILDING_1806'] = 'Mining center';
$lang['BUILDING_1807'] = 'Nuclear power facility';
$lang['BUILDING_1808'] = 'Large orbit solar facility';
$lang['BUILDING_1809'] = 'Large mars colony';

/* Discount (Asteroid) - Group 19 */
$lang['BUILDING_1900'] = 'Training center';
$lang['BUILDING_1901'] = 'Terraforming center';
$lang['BUILDING_1902'] = 'Military personel quarters';
$lang['BUILDING_1903'] = 'Military headquarters';
$lang['BUILDING_1904'] = 'Supply depot';
$lang['BUILDING_1905'] = 'Construction company';
$lang['BUILDING_1906'] = 'Bootcamp';
$lang['BUILDING_1907'] = 'President\'s office';
$lang['BUILDING_1908'] = 'Village';
$lang['BUILDING_1909'] = 'Recreation facility';

/* Maintenance (Asteroid) - Group 20 */
$lang['BUILDING_2000'] = 'Architect design center';
$lang['BUILDING_2001'] = 'Drone repair center';
$lang['BUILDING_2002'] = 'Missile repair center';
$lang['BUILDING_2003'] = 'Explore repair center';
$lang['BUILDING_2004'] = 'Vehicle repair center';
$lang['BUILDING_2005'] = 'Warrior repair center';
$lang['BUILDING_2006'] = 'Infra repair center';
$lang['BUILDING_2007'] = 'Unit repair center';
$lang['BUILDING_2008'] = 'Power repair center';
$lang['BUILDING_2009'] = 'Robot repair center';


/*
** ------------------
** BUILDING PAGE
** ------------------
*/

$lang['BUILDING_TITLE'] = 'BUILDINGS';
$lang['BUILDING_NOTE1'] = 'Nota: cladirile de profit ofera unb profit mai mare. Fiecare cladire contiune cetateni care for creste costurile pe ora.';
$lang['BUILDING_NOTE2'] = 'Nota: cladirile de aparare ofera o protectie mai mare impotriva atacurilor. Fiecare cladire contiune cetateni care for creste costurile pe ora.';
$lang['BUILDING_NOTE3'] = 'Nota: cladirile de energie ofera recuperea mai rapida a energiei. Fiecare cladire contiune cetateni care for creste costurile pe ora.';
$lang['BUILDING_NOTE4'] = 'Nota: Reducerea costului cladirilor ofera reducere la  achizitoinarea cladirilor. Fiecare cladire contiune cetateni care for creste costurile pe ora.';
$lang['BUILDING_NOTE5'] = 'Nota: Mentenanta cladirilor permite repararea mai rapida a unitatilor astfel vei pierde mai putine unitati in timpul bataliilor. Fiecare cladire contiune cetateni care for creste costurile pe ora.';

$lang['BUILDING_NOTE6'] = 'Nota: cladirile de profit ofera unb profit mai mare pentru baza ta de pe luna.';
$lang['BUILDING_NOTE7'] = 'Nota: cladirile de aparare ofera o protectie mai mare in timpul bataliilor de pe luna.';
$lang['BUILDING_NOTE8'] = 'Nota: cladirile de energie ofera recuperea mai rapida a energiei de pe luna.';
$lang['BUILDING_NOTE9'] = 'Nota: Reducerea costului cladirilor ofera reducere la  achizitoinarea cladirilor de pe luna.';
$lang['BUILDING_NOTE10'] = 'Nota: Mentenanta cladirilor permite repararea mai rapida a unitatilor astfel vei pierde mai putine unitati in timpul bataliilor de pe luna.';

$lang['BUILDING_NOTE11'] = 'Nota: cladirile de profit ofera unb profit mai mare pentru baza ta de pe marte.';
$lang['BUILDING_NOTE12'] = 'Nota: cladirile de aparare ofera o protectie mai mare in timpul bataliilor de pe marte.';
$lang['BUILDING_NOTE13'] = 'Nota: cladirile de energie ofera recuperea mai rapida a energiei de pe marte.';
$lang['BUILDING_NOTE14'] = 'Nota: Reducerea costului cladirilor ofera reducere la  achizitoinarea cladirilor de pe marte.';
$lang['BUILDING_NOTE15'] = 'Nota: Mentenanta cladirilor permite repararea mai rapida a unitatilor astfel vei pierde mai putine unitati in timpul bataliilor de pe marte.';

$lang['BUILDING_NOTE16'] = 'Nota: cladirile de profit ofera unb profit mai mare pentru baza ta de pe asteroid.';
$lang['BUILDING_NOTE17'] = 'Nota: cladirile de aparare ofera o protectie mai mare in timpul bataliilor de pe asteroid.';
$lang['BUILDING_NOTE18'] = 'Nota: cladirile de energie ofera recuperea mai rapida a energiei de pe asteroid.';
$lang['BUILDING_NOTE19'] = 'Nota: Reducerea costului cladirilor ofera reducere la  achizitoinarea cladirilor de pe asteroid.';
$lang['BUILDING_NOTE20'] = 'Nota: Mentenanta cladirilor permite repararea mai rapida a unitatilor astfel vei pierde mai putine unitati in timpul bataliilor de pe asteroid.';

$lang['BUILDING_NOTE21'] = 'Nota: cladirile de profit ofera unb profit mai mare pentru baza ta de pe soare.';
$lang['BUILDING_NOTE22'] = 'Nota: cladirile de aparare ofera o protectie mai mare in timpul bataliilor de pe soare.';
$lang['BUILDING_NOTE23'] = 'Nota: cladirile de energie ofera recuperea mai rapida a energiei de pe soare.';
$lang['BUILDING_NOTE24'] = 'Nota: Reducerea costului cladirilor ofera reducere la  achizitoinarea cladirilor de pe soare.';
$lang['BUILDING_NOTE25'] = 'Nota: Mentenanta cladirilor permite repararea mai rapida a unitatilor astfel vei pierde mai putine unitati in timpul bataliilor de pe soare.';

$lang['BUILDING_SELL'] = 'Ai vandut %s %s pentru %s. ai inca %s disponibile.';
$lang['BUILDING_LOW_UPKEEP'] = 'Nu ai suficient profit pentru a vinde %s %s pentru %s.';
$lang['BUILDING_NOT_OWNED'] = 'nu ai %s %s.';

$lang['BUILDING_BUY'] = 'Ai cumparat %s %s pentru %s. ai %s cumparate.';
$lang['BUILDING_MAX'] = 'nu mai mult de %s %s(s) permise!';
$lang['BUILDING_NO_FUNDS'] = 'nu ai suficieni bani pentru a cumpara %s %s pentru %s.'; 
$lang['BUILDING_LOW_UPKEEP2'] = 'nu ai suficient profit pentru a cumpara  %s %s pentru %s.';

$lang['BUILDING_UPKEEP'] = 'Cost pe ora';
$lang['BUILDING_PRICE'] = 'Pret';
$lang['BUILDING_DEPLOYED'] = 'Deployed';
$lang['BUILDING_GAIN'] = 'Castig';
$lang['BUILDING_ENERGY'] = 'Energie';
$lang['BUILDING_INCOME'] = 'Profit';
$lang['BUILDING_REQUIRED'] = 'Necesar';

$lang['BUILDINGS_NO_BUILDINGS'] = 'Nici o cladire disponibila!';

/*
** ------------------
** MONEY - BANKS 
** ------------------
*/

$lang['MONEY_TITLE'] = 'Bani';

$lang['BANK_GROUP_1'] = 'National';
$lang['BANK_GROUP_2'] = 'Trasquera';
$lang['BANK_GROUP_3'] = 'SwissCore';

$lang['BANK_TITLE'] = 'BANKS';
$lang['BANK_NOTE'] = 'Note: Ai %s% taxa pentru orice depozit . banca plateste %s% dobanda in fiecare zi. ';
$lang['BANK_WARNING'] = 'ATENTIUNE: Inteligentii sau Exploratorii de la alti jucatori pot fura bani din aceasta banca.';

$lang['BANK_TRANSACTION_TYPE_0'] = 'Ai retras';
$lang['BANK_TRANSACTION_TYPE_1'] = 'Ai depozitat';
$lang['BANK_TRANSACTION_TYPE_2'] = 'Taxa bancii';
$lang['BANK_TRANSACTION_TYPE_3'] = 'Restore bill';		
$lang['BANK_TRANSACTION_TYPE_4'] = 'Dobanda';	
$lang['BANK_TRANSACTION_TYPE_5'] = 'Spionul a furat';
$lang['BANK_TRANSACTION_TYPE_6'] = 'Bonus ';

$lang['BANK_TRANSACTION_LOG'] = 'Transactie istoric';

$lang['BANK_WITHDRAW']= 'Ai retras %s dolari din banca';
$lang['BANK_WITHDRAW_FAILED'] = '%s dolari nu sunt disponibil in banca!';

$lang['BANK_DEPOSIT'] = 'depus %s dolari in banca.';
$lang['BANK_DEPOSIT_FAILED'] = 'Nu ai %s dolari.';

/*
** ------------------
** MONEY - STOCK EXCHANGES
** ------------------
*/

$lang['STOCK_GROUP_1'] = 'Nasdaq';
$lang['STOCK_GROUP_2'] = 'DowJones';
$lang['STOCK_GROUP_3'] = 'AEX';
$lang['STOCK_GROUP_4'] = 'Personal';

$lang['STOCK_TITLE'] = 'STOCK EXCHANGES';
$lang['STOCK_BROKER_ERROR'] = ' conexiunea la Broker esuata. Schimbul nu este posibil in acest moment. te rugam incearca mai tarziu.';
$lang['STOCK_BUY'] = 'Ai cumparat %s %s pentru %s dolari. acum ai  %s.';
$lang['STOCK_NO_MONEY'] = ' Nu ai suficienti bani pentru a cumpara %s %s pentru %s dolari.';
$lang['STOCK_PRICE'] = 'Pretul actiunii %s [%s]';
$lang['STOCK_PROFIT'] = 'Profitul actiunii %s [%s]';
$lang['STOCK_NOT_OWNED'] = 'nu ai  %s %s actiuni.';
$lang['STOCK_SELL'] = 'Ai vandut %s %s actiuni pentru %s dolari. Ai platit %s dolari taxa tranzactiei. Mai ai inca %s.';
$lang['STOCK_NOTE'] = 'Nota: POti cumpara sau vinde actiuni pentru a face profit. Pretul actiunii se reactualizeaza in timp real de la Yahoo. Este o taxa de  %s% pentru fiecare tranzactie.';
$lang['STOCK_PRICE_TO_LOW'] = 'pretul actiunii prea mic. Schimb blocat!';

$lang['STOCK_SYMBOL'] = 'Simbolul actiunii'; 
$lang['STOCK_SYMBOL_INFO'] = 'Nota: Intra la Yahoo financiar pentru a customiza aceasta lista.'; 

$lang['STOCK_ADD'] = 'Adauga actiune';
$lang['STOCK_SYMBOL_ADDED'] = 'ai adaugat (%s) la lista ta personala de actiuni.';
$lang['STOCK_NO_SYMBOLS' ] = 'nu ai adaugat nici o actiune inca!';
$lang['STOCK_SYMBOL_NOT_FOUND'] = 'simbolul actiunii (%s)nu exista!';
$lang['STOCK_SYMBOL_AVAILABLE'] = 'simbolul actiunii (%s) dexa existent in list personala.';

$lang['STOCK_REMOVE'] = 'elimina actiuni';
$lang['STOCK_SYMBOL_REMOVED'] = 'Simbolul actiunii eliminat!';

$lang['GENERAL_STOCKS'] = 'Actiune';

/*
** ------------------
** MONEY - CASINO
** ------------------
*/

$lang['CASINO_TITLE'] = 'CASINO';

$lang['CASINO_1'] = 'Roata Norocului';
$lang['CASINO_2'] = 'Slot-Machine';

$lang['CASINO_MONEY'] = 'Bani';
$lang['CASINO_NUMBER'] = 'Numar norocos';
$lang['CASINO_BET'] = 'Miza';
$lang['CASINO_PLAY'] = 'Joaca';
$lang['CASINO_ROLL'] = 'Invarte';

$lang['CASINO_NO_BET'] = 'Introdu miza!';
$lang['CASINO_NO_LUCKY_NUMBER'] = 'introdu numarul norocos!';
$lang['CASINO_BET_TO_LARGE'] = 'Miza prea mare! miza maxima este %s dolari.'; 
$lang['CASINO_NO_MONEY'] = 'Nu ai suficienti bani!'; 

$lang['CASINO_WIN'] = 'numarul castigator este %s. ai castigat %s  dolari.';
$lang['CASINO_LOST'] = 'numarul castigator este %s. ai pierdut %s dolari.';

$lang['CASINO_NOTE1'] = 'Nota: INtrodu miza si numarul norocos si apasa joaca. daca esti norocos o sa castigi de 10 ori miza ta.';
$lang['CASINO_NOTE2'] = 'Nota: INtrodu miza si apasa joaca. poate vbei catiga miza ta.';

$lang['CASINO_UNLOCK'] = '%s este deblocat la nivelul %s';

$lang['CASINO_SLOTMACHINE_WIN'] = 'Ai castigat de %s ori miza ta. Ai castigat %s dolari.';
$lang['CASINO_SLOTMACHINE_LOST'] = 'Ai pierdut %s dolari.';
$lang['CASINO_SLOTMACHINE_HELP'] = 'urmatoarea combinatie la sloturi castiga';

/*
** ------------------
** ALIANTA
** ------------------
*/

$lang['ALLIANCE_TITLE'] = 'ALIANTA';

$lang['ALLIANCE_PENDING_TITLE1'] = 'Invitaii';
$lang['ALLIANCE_PENDING_TITLE2'] = 'invitatii [%s acceptati - %s invitati ]';

$lang['ALLIANCE_ACCEPT_TITLE1'] = 'Accepted';
$lang['ALLIANCE_ACCEPT_TITLE2'] = 'Accepted [%s acceptati - %s invitati]';

$lang['ALLIANCE_INVITE_TITLE1'] = 'Invitati';
$lang['ALLIANCE_INVITE_TITLE2'] = 'Invitati [%s acceptati - %s invitati]';

$lang['ALLIANCE_NO_PENDING'] = 'nici o alianta in asteptare!'; 
$lang['ALLIANCE_INVITATION'] = 'invitatia de alianta a fost trimisa lui %s!'; 
$lang['ALLIANCE_REJECT'] = 'Respinge pe %s ca aliat!';
$lang['ALLIANCE_DROP'] = 'arunca pe %s ca aliat!';
$lang['ALLIANCE_ACCEPT'] = 'Accepta pe %s ca aliat!';
$lang['ALLIANCE_ALLY'] = 'Aliat';
$lang['ALLIANCE_MAXIMUM'] = 'numarul maxim de aliati %s a fost atins.asteapta sa treci nivelul.'; 
$lang['ALLIANCE_LOCKED'] = 'invitatiile de alianter deblocate la nivelul 1';
$lang['ALLIANCE_NOTE'] = 'Nota:  Cu fiecare alianta aprobata poti comanda cu 6 unitati mai mult pe timpul bataliilor. Tine minte ca nu poti ataca aliatii.';

$lang['ALLIANCE_INVITE_FRIENDS'] = 'Invita un prieten prin email';
$lang['ALLIANCE_INVITE_NOTE'] = 'Nota: Invita un jucator pentru alianta. Daca celalalt jucator accepta sau respinge alianta vei fi informat prin email(optiune in setari). numarul maxim de acceptati + invitati pentru acest nivel este %s.';
$lang['ALLIANCE_EMAIL_INVALID']= 'Adresa de email nu este valida!';
$lang['ALLIANCE_ALREADY_INVITED'] = 'adresa de mail deja invitata!';
$lang['ALLIANCE_INVITE_SENT'] = 'invitatia pe email a fost facuta.';

$lang['ALLIANCE_COMMENT_TITLE'] = 'Mesaj';
$lang['ALLIANCE_COMMENT_TEXT1'] = 'Creaza mesaj (max. 400 caractere) pentru toti jucatorii';
$lang['ALLIANCE_COMMENT_TEXT2'] = 'Creaza mesaj (max. 400 caractere) pentru %s';
$lang['ALLIANCE_PLAYER_NEWS'] = 'Mesaj';
$lang['ALLIANCE_COMMENT_ALL'] = 'Mesajul este memorat si disponibil pentru restul jucatorilor.';
$lang['ALLIANCE_COMMENT_PLAYER'] = 'mesajul este trimis lui %s';

$lang['LEADERBORD_BEST_PLAYER'] = 'Clasament (Cei mai buni jucatori)';
$lang['LEADERBORD_BEST_PLAYER_NOTE'] = 'Nota: In clasamentul celor mai buni jucatori sunt doar oameni. robotii WarQuest  (cyberspace) nu sunt disponibili!';

$lang['LEADERBORD_BEST_COUNTRY'] = 'Clasament (Cele mai bune tari)';
$lang['LEADERBORD_BEST_COUNTRY_NOTE'] = 'Note: Leaderboard shows the best real countries.';

$lang['LEADERBORD_PLAYER_COUNTRY'] = 'Clasament (Cei mai buni jucatori din  %s)';
$lang['LEADERBORD_PLAYER_COUNTRY_NOTE'] = 'Nota: Clasamentul arata cei mai buni jucatori din tara selectata.';

/*
** ------------------
** FORUMUL 
** ------------------
*/

$lang['FORUM_TITLE'] = 'FORUM'; 
$lang['FORUM_TITLE2'] = 'Forum';
$lang['FORUM_NOTE'] = 'Nota: Selecteaza un forum ca sa vezi toate postarile. I\'ve seen some people cursing or use other bad words in the forums. I doesn\'t want that kind of language on here! Thanks. And remember, no bad words! ';

$lang['FORUM_1'] = 'Anunturi'; 
$lang['FORUM_NOTE_1'] = 'Anunturi generale';
$lang['FORUM_2'] = 'Rapoarte de Bug'; 
$lang['FORUM_NOTE_2'] = 'ce merge rau in noul up-date?';
$lang['FORUM_3'] = 'Feature Requests'; 
$lang['FORUM_NOTE_3'] = 'Ce  vreti in noul up-date?';
$lang['FORUM_4'] = 'Help'; 
$lang['FORUM_NOTE_4'] = 'ce nu este clar in  WarQuest?';
$lang['FORUM_5'] = 'Altele'; 
$lang['FORUM_NOTE_5'] = 'Oricare alte discutii?';
$lang['FORUM_6'] = 'Comunitatea tarilor'; 
$lang['FORUM_NOTE_6'] = 'discutii in limba locala?';

$lang['FORUM_SEARCH_TOKEN'] = 'Cautarea trebuie sa aiba cel putin 3 caractere.';

$lang['TOPIC_TITLE'] = 'Topic'; 
$lang['TOPIC_CREATED_INPUT'] = 'Creaza un nou topic (max. 80 caractere)';
$lang['TOPIC_CREATED'] = 'Topic creat';
$lang['TOPIC_UPDATED'] = 'Topic relansat';
$lang['TOPIC_DELETED'] = 'Topic sters';
$lang['TOPIC_NO_TOPICS'] = 'in acest moment nici un topic deschis.';
$lang['TOPIC_NOTE'] = 'Nota: alege un topic pentru a citi/scrie sau creaza unul nou.'; 
$lang['TOPIC_CREATED_BY'] = '(Creat de %s)';

/*
** ------------------
** FORUM - POLL
** ------------------
*/

$lang['POLL_TITLE'] = 'Polls';
$lang['POLL_RESULT_TITLE'] = 'Poll Rezultate';
$lang['POLL_TEASER_TITLE'] = 'New Poll';
$lang['POLL_RESULTS'] = 'Rezultat';
$lang['POLL_ClOSED'] = '(Poll inchis)';
$lang['POLL_VOTE_ADD'] = 'Multumim pentru votul tau! Ai primit 10 puncte de experienta ca recompensa.';
$lang['POLL_VOTE_REMOVE'] = 'Votul tau este anulat!';
$lang['POLL_VOTE'] = 'Vot';
$lang['POLL_VOTES'] = 'Voturi';
$lang['POLL_CANCEL'] = 'Anulare';
$lang['POLL_SUMMARY'] = 'Total Votanti: %s';
$lang['POLL_WARNING'] = 'selectati una dintre voturile posibile!';

/*
** ------------------
** FORUM - CHAT
** ------------------
*/

$lang['CHATROOM_TITLE'] = 'Chatroom';
$lang['CHATROOM_NOTE'] = 'Note: Incepe conversatia cu unul dintre jucatorii on-line!';
$lang['CHATROOM_LAST_ACTIVE'] = 'ultima data activ';
$lang['CHATROOM_CHAT'] = 'Chat';
$lang['CHAT_NOTE'] = 'Nota: scrrie un mesaj pentru a incepe cheat-ul!';

$lang['CHAT_TITLE'] = 'Chat';

/*
** ------------------
** AJUTOR - INSTRUCTIUNI
** ------------------
*/

$lang['HELP_TITLE'] = 'AJUTOR';

$lang['HELP_GENERAL_SUBTITLE'] = 'Instructiuni';

$lang['HELP_INTRO_TITLE'] = 'Introductiuni';
$lang['HELP_INTRO'] =	'WarQuest este un joc Multiplayer Online gratis care sugereaza o zona de razboi cu mi de jucatori reali. WarQuest te duce in anul 2020.
 Lumea este in razboi. Obiectivul jocului este sa iti aperi tara si sa cuceresti alte tari.
 Cumpara arme si armata ,joaca misiuni,lupte,fa-ti aliati si devino cel mai bun jucator din tara ta.';

$lang['HELP_EXP_TITLE'] = 'Experienta / Nivel';
$lang['HELP_EXP'] = ' joaca misiuni si du lupte pentru a castiga experienta. cand colectezi suficienta experienta vei putea treci la nivelul urmator.
 Cand un nivel este complet energia viata si munitia vor reveni la maxim.';

$lang['HELP_HEALTH_TITLE'] = 'Viata';
$lang['HELP_HEALTH'] = 'Viata ta va scadea cu fiecare batalie dar va reveni automat cu trecerea timpului. 
 poti vizita spitalul (ACASA -> Restaureaza) si plati pentru o recuperare rapida.';

$lang['HELP_ENERGY_TITLE'] = 'Energie'; 
$lang['HELP_ENERGY'] = ' energia ta va scadea cu fiecare misiune jucata dar va reveni automat cu trecerea timpului. Cumparand cladiri de energie va reveni mai repede cu recerea  timpului. 
O poti incarca totusi la maxim in acelasi fel ca si viata.';

$lang['HELP_AMMO_TITLE'] = 'Munitie'; 
$lang['HELP_AMMO'] =	'Fiecare batalie te costa 1 munitie. munitia este regenerata cu trecerea timpului. O poti incarca totusi la maxim in acelasi fel ca si viata.';

$lang['HELP_MISSION_TITLE'] = 'Misiuni';
$lang['HELP_MISSION'] = 'Joaca misiuni pentru acastiga bani si experienta necesara treceri nivelului. 
daca o misiune este 100% completata vei primi dublu de bani. daca un continent este cucerit vei primi un profit bonus.<br/><br/>

Urmatorul bonus estre este oferit cand fiecare planeta este cucerita:<br/>
PAMANT: 100 Million dollari<br/>
LUNA: 500 Millioane dollari<br/>
MARTE: 999 Billioane dollari<br/>
ASTEROID: 50 puncte de schimb';

$lang['HELP_BATTLE_TITLE'] = 'LUPTA';
$lang['HELP_BATTLE'] =	'lupta impotriva altor jucatori pentru a castiga bani si experienta necesare treceri nivelului.
 In timpul bataliilor armata ta si cladirile pot fi deteriorate sau chiar pierdute.';

$lang['HELP_UNITS_TITLE'] = 'Unitati';
$lang['HELP_UNITS'] =  'In timpul atacului cele mai bune unitati sunt selectate automat. marimea armatei tale depinde de marimea aliantei. Primesti la inceput 6 unitati
si un aliat. Fiecare aliat iti aduce 6 unitati in plus. iti poti achizitiona mai multe unitati dar numai de 6 ori numarul aliantei tale vor participa.';

$lang['HELP_BUILDINGS_TITLE'] = 'Cladiri';
$lang['HELP_BUILDINGS'] = 'In timpul jocului cladirile pot aduce profit, o aparare mai mare, energie mai rapida, 
discont si o mentenata mai mare. Fiecare cladire cumparata va creste pretul urmatoarei cladiri. Fiecare cladire contine cetateni care vor creste cheltuielile.';

$lang['HELP_BANKS_TITLE'] = 'Banca';
$lang['HELP_BANKS'] = 'Fiecare banca are o taxa pentru depozit. Banii depusi in banca National sunt in siguranta fata de atacurile celorlalti jucatori dar plateste
o dobanda destul de mica. Banii depusi in banca Trasquera sau SwissCore au o dobanda mai mare dar pot fi furati de inteligenti sau de exploratorii celorlalti jucatori.';

$lang['HELP_ALLIANCE_TITLE'] = 'Alianta'; 
$lang['HELP_ALLIANCE'] = 'Fiecare alianta aprobata iti creste armata cu 6 unitati. Cresteti alianta ca sa devi mai puternic!
 Tine minte totusi ca nu poti ataca aliati.';

$lang['HELP_SKILL_POINTS_TITLE'] = 'puncte de aptitudine';
$lang['HELP_SKILL_POINTS'] = 'Punctele de aptitudine pot fi primite in timpul jocului. foloseste punctele de aptitudine ca sa iti maresti atacul,apararea,
viata,energia sau munitia.Munitia costa 2 puncte de  aptitudine,iar celelalte doar 1. poti de altfel sa schimbi la un procent de 2:1 cresterea unei aptitudini.';

$lang['HELP_TRADE_POINTS_TITLE'] = 'Puncte de Schimb';
$lang['HELP_TRADE_POINTS']  = 'Punctele de schimb pot fi procurate prin donare de dolari reali. Vezi Ajutor -> Donare. 
Punctele de schimb pot fi schimbate in puncte de aptitudini, bani sau pot fi utiizate pentru a scadea timpul de reincarcare a vietii energiei sau munitiei.';

$lang['HELP_TACTICS_TITLE'] = 'Tactici';
$lang['HELP_TACTICS'] = 'Un lucru important este ca unitatile cu care joci in misiuni pot fi pierdute in timpul luptei. 
 This is important to consider as the cost of replacing some of the higher priced 
units used in a mission may exceed the money earned from the mission itself. In general, if your goal 
is to maximize money from missions, then focus on the Money / Energy value of the mission. 
If your goal is to maximize experience points, then focus on the Exp / Energy value of the 
missions.<br/><br/>

Odata cu cresterea in nivel jocul creste automat raza la care pot fi vazuti oponentii. 
 Pentru asta trebuie sa faci tot posibilul sa iti cresti alianta si sa incerci sa o ti la maxim.<br/><br/>

Cladirile de aparare sunt ideale pentru ca ele cresc valoarea apararii tale ori de cate ori esti atacat. 
Este recomandant sa va procurati cat de multe puteti pentru a nu va mai face grija ca veti fi atacati de boti si veti pierde banii.<br/><br/>

In WarQuest, apararea face ca uni oponenti sa fie foarte foarte greu de infrant. 
este recomandat de asemeni sa folositi si unele puncte de aptitudini pentru aparare,dar cele mai multe trebuie folosite pentru atac pentru ca la aparare se
mai poate compensa cu,cladirile de aparare .<br/><br/>

Cand va hotarati sa cumparati armata sa fiti foarte atent la costul pe ora al fiecarei unitate, atacul si
apararea acestora. Daca castigi cele mai multe lupte cu armata pe care o ai trebuie sa faci tot posibilul sa nu mai cumperi alte unitati si sa iti 
reorientezi banii catre alte cladiri.';

$lang['HELP_GRAVATAR_TITLE'] = 'avatar';
$lang['HELP_GRAVATAR'] = 'WarQuest suporta avatar (www.gravatar.com) serviciul de imagine. avatarul este o 
imagine care te insoteste alaturi de nik-ul tau.';

$lang['HELP_BOUNTY_TITLE'] = 'Vaneaza recompense';
$lang['HELP_BOUNTY'] = 'poti sa pui recompense pe capul oponentilor. Recompensa este influentata de nivelul oponentului. Dupa ce ai pus o recompensa
ceilalti jucatori il pot ataca pe cel pe capul caruia a pus recompensa (Lupta -> Vaneazarecompense).
Daca oponentul este infrant va pierde puncte de experienta iar recompensa este transferaata catre invingator.';

$lang['HELP_UNITS_CONDITION_TITLE'] = 'Starea Unitatilr (SU)';
$lang['HELP_UNITS_CONDITION'] = 'Aceasta valoare iti arata starea unitatilor tale. 
daca aceasta valoare ajunge la 0% vei pierde cateva unitati. Pentru a preveni pierderea:
(ACASA -> Restaureaza).'; 

$lang['HELP_BUILDINGS_CONDITION_TITLE'] = 'Starea cladirilor (SC)';
$lang['HELP_BUILDINGS_CONDITION'] = 'Aceasta valoare iti arata starea cladirilor din baza ta.
 daca aceasta valoare ajunge la 0% vei pierde cateva cladiri. Pentru a prezveni pierderea cladirilor: 
 (Acasa -> Restaureaza).'; 

$lang['HELP_FORUM_TITLE'] = 'Forum';
$lang['HELP_FORUM'] = 'Pentru a te informa sau pentru a vorbi pe cheat cu alti jucatori viziteaza forumul.';

$lang['HELP_WORLDMAP_TITLE'] = 'Harta';
$lang['HELP_WORLDMAP'] = 'Fiecare planeta (Pamant / Luna / Marte) contine o harta cu 72 de regiuni care pot fi cucerite 
 jucand misiuni. Regiunile au urmatoarele culori: <br/>
- "Verde" Regione 0% cucerita<br/>
- "Galben" Regione 33% cucerita.<br/>
- "Purple" Regione 66% cucerita.<br/>
- "Portocaliu" Regione 100% cucerita.<br/>
- "Rosu" Revolta in regione. Regiunea trebuie recucerita.';

$lang['HELP_SHORTCUTS_TITLE'] = 'Scurtaturile meniului';
$lang['HELP_SHORTCUTS'] = 'Urmatoarele scurtaturi disponibile sunt::<br/>
- Click "Bani" Pentru a merge la cei mai buni jucatori.<br/>
- Click "Exp." Pentru a merge la cele mai bune tari.<br/>
- Click "Level" to go to the poll page.<br/>
- Click "Viata" Pentru a merge la pagina de vindecare.<br/>
- Click "Energie" Pentru a merge la pagina de profil.<br/>
- Click "Munitie" Pentru a merge la pagini de aptitudini.';

$lang['HELP_ATTACK_FORCE_TITLE'] = 'Forta atacului';
$lang['HELP_ATTACK_FORCE'] = 'Inainte de lupta poti alege una dintre urmatoarele forte de atac:<br/><br/>
Pamant<br/>
- "Army" cele mai bune unitati de pe pamant.<br/>
- "Calverie" doar cavaleria.<br/>
- "Nave" Only fortele navale.<br/>
- "Avioane" Only fortele aeriene.<br/>
- "Inteligenti" doar fortele inteligente.<br/><br/>
LUNA<br/>
- "Army" cele mai bune unitati de pe luna.<br/>
- "Drones" Doar drone.<br/>
- "Warriors" Doar warrior.<br/>
- "Nave spatiale" Doar nave spatiale moon units.<br/>
- "Exploratori " Doar exploratori.<br/><br/>
MARTE<br/>
- "Army" cele mai bune unitati de pe marte.<br/>
- "Drone" doar drone.<br/>
- "Warriors" doar warrior .<br/>
- "Spacecrafts " doar nave spatiale mars units.<br/>
- "Explorers " doar exploratori.<br/><br/>
ASTEROID<br/>
- "Army" cele mai bune unitati de pe asteroid.<br/>
- "Drones" doar drone s.<br/>
- "Warriors" doar warrior .<br/>
- "Spacecrafts " doar nave spatiale.<br/>
- "Explorers " doar exploratori.
';

$lang['HELP_REBELLION_CONDITION_TITLE'] = 'Starea rascoalei (SR)';
$lang['HELP_REBELLION_CONDITION'] = 'Aceasta valoare iti arata starea de rascoala. Rascoala poate fin inceputa de inteligentii
sau exploratorii celorlalti jucatori.daca valoarea ajunge la 100% unele dintre regiunile cucerite de tine vor fi in rascoala.
pentru a impiedica acest lucru viziteaza (ACASA -> Restaureaza) pentru a pune capat rascoalei. Fiecare pierdere o unei regiuni va influenta profitul.
Restaureaza controlul regiunilor prin recastigarea acestora.';

/*
** ------------------
** HELP - RELEASE NOTES
** ------------------
*/

$lang['HELP_NOTES_SUBTITLE1'] = 'Release Notes';
$lang['HELP_NOTES_SUBTITLE2'] = 'Release Notes (English only)';

/*
** ------------------
** HELP - RANCURI
** ------------------
*/

$lang['HELP_RANKS_SUBTITLE'] = 'Rancuri';
$lang['HELP_RANKS'] = 'Urmatoarele grade sunt disponibile:';

/*
** ------------------
** HELP - PREMII
** ------------------
*/

$lang['HELP_AWARDS_SUBTITLE'] = 'Premii';
$lang['HELP_BATTLE_AWARDS'] = 'Umatorul premiu de victorie poate fi castigat:';
$lang['HELP_BOUNTY_AWARDS'] = 'Umatorul premiu pentru punere de recompense poate fi castigat:';
$lang['HELP_REBEL_AWARDS'] = 'Umatorul premiu pentru inceperea rascoalei poate fi castigat:';


/*
** ------------------
** HELP - Nivele
** ------------------
*/

$lang['HELP_LEVEL_SUBTITLE'] = 'Nivele';
$lang['HELP_LEVEL'] = 'Urmatorul nivel este disponibil:';
$lang['HELP_LEVEL_UNIT_LOST'] = 'Unitate(i) pierduta';
$lang['HELP_LEVEL_EXPERIENCE'] = 'Experienta';
$lang['HELP_LEVEL_FEATURES'] = 'Urmatoarea schema deblocata';

/*
** ------------------
** HELP - STATS
** ------------------
*/

$lang['HELP_STATS_TITLE'] = 'Statistica';
$lang['HELP_STATS_NOTE'] = 'Nota: Pe aceasta pagina WarQuest Statisticile sunt live.';
$lang['HELP_STATS_PLAYERS'] = 'Jucatori noi (ultimele 14 zile)';
$lang['HELP_STATS_ONLINE'] = 'Players online (ultimele 14 zile)';
$lang['HELP_STATS_FIGHTS'] = 'Player fights (ultimele 14 zile)';
$lang['HELP_STATS_MISSIONS'] = 'Missions played (ultimele 14 zile)';
$lang['HELP_STATS_CASINO'] = 'Casino games played (ultimele 14 zile)';
$lang['HELP_STATS_ADS'] = 'Ads showed (ultimele 14 zile)';
$lang['HELP_STATS_REQUESTS'] = 'Server requests (ultimele 14 zile)';

/*
** ------------------
** HELP - DONATii
** ------------------
*/

$lang['HELP_DONATE_TITLE1'] = 'Doneaza';
$lang['HELP_DONATE_TITLE2'] = 'Doneaza (English only)';

$lang['HELP_SUBTITLE_DONATE1'] = 'General';
$lang['HELP_DONATE1'] = 'WarQuest poate fi jucat de placere gratis, dar daca vrei sa iti arati recunostinta pentru acest joc,
pentru autor pentru resursele folosite pentru timpul pierdut dealungul anilor o poti face printr-o donatie cat de mica.';

$lang['HELP_SUBTITLE_DONATE3'] = 'PayPal';
$lang['HELP_DONATE3'] = 'Pentru a face o donatie on-line folosind cardul ,sau contul de PayPal apasa aici si intro valoarea
cu care vrei sa contribui. Tranzactia va fi procesata de PayPal un nume de incredere in tranzactiile on-line.Mi de multumiri pentru suport.';

/*
** ------------------
** HELP - Despre
** ------------------
*/

$lang['HELP_ABOUT_SUBTITLE'] = 'despre';
$lang['HELP_BACKGROUND_TITLE'] = 'Background';
$lang['HELP_BACKGROUND'] = 'WarQuest este creat de <a target="new" href="http://www.plaatsoft.nl">PlaatSoft</a>. Original game idea is based on some other games available in the Apple appstore. The main reason to recreate this kind of game is to create a better game play and user interface which can be controlled on the following devices: smart phones (Apple, Android, Nokia and BlackBerry), tablets(Samsung and Apple), Game consoles (Nintendo) and all kinds of notebooks (Intel / AMD base).';
$lang['HELP_CREDITS_TITLE'] = 'Credite';
$lang['HELP_BROWSERS_TITLE'] = 'Browsere suportate'; 
$lang['HELP_HARDWARE_TITLE'] = 'Hardware suportate'; 
$lang['HELP_DISCLAIMER_TITLE'] = 'Disclaimer'; 
$lang['HELP_DISCLAIMER'] = 'Programul este distribuit fara nici un fel de garantie de nici un fel, INCLUzand designe-ul, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.<br/>';

$lang['HELP_CREDITS_TITLE'] = 'Credits';
$lang['HELP_CREDITS'] = 'Mi de multumiri oamenilor si organizatiilor care au ajutat la crearea acestui joc.';
$lang['HELP_CREDITS_ARCHITECT'] = 'Architect';
$lang['HELP_CREDITS_DEVELOPERS'] = 'Developer';
$lang['HELP_CREDITS_GRAPHICS'] = 'Graphica & Informatie';
$lang['HELP_CREDITS_TRANSLATORS'] = 'Translatori';
$lang['HELP_CREDITS_TESTERS'] = 'Testeri';
$lang['HELP_CREDITS_OTHER'] = 'altii';
$lang['HELP_CREDITS_OTHER_NOTE'] = 'Si desigur tuturor jucatorilor WarQuest care au trimis feedback-uri pentru a imbunatatii jocul . Distractie placuta';

/*
** ------------------
** RANK DATA
** ------------------
*/

$lang['RANK_1'] = "SGV";
$lang['RANK_2'] = "SGV CLASA 1";
$lang['RANK_3'] = "Specialist";
$lang['RANK_4'] = "Caporal";
$lang['RANK_5'] = "Sergent";
$lang['RANK_6'] = " Sergent minor";
$lang['RANK_7'] = "Sergeant clasa 1";
$lang['RANK_8'] = "Master Sergeant";
$lang['RANK_9'] = "First Sergeant";
$lang['RANK_10'] = "Sergent Major";
$lang['RANK_11'] = "Command Sergeant Major";
$lang['RANK_12'] = "Sergent Major of the Army";
$lang['RANK_13'] = "SubLocotenent";
$lang['RANK_14'] = "Locotenent";
$lang['RANK_15'] = "Capitan";
$lang['RANK_16'] = "Major";
$lang['RANK_17'] = "Locotenent colonel";
$lang['RANK_18'] = "Colonel";
$lang['RANK_19'] = "Brigadier General";
$lang['RANK_20'] = "Major General";
$lang['RANK_21'] = "Locotenent General";
$lang['RANK_22'] = "General";
$lang['RANK_23'] = "General of the Army";

/*
** ------------------
** COUNTRY NAMES
** ------------------
*/

$landcode = array();

$landcode['ad'] = "Andorra";
$landcode['ae'] = "Arab Emirates";
$landcode['af'] = "Afghanistan";
$landcode['ag'] = "Antigua and Barbuda";
$landcode['ai'] = "Anguilla";
$landcode['al'] = "Albania";
$landcode['am'] = "Armenia";
$landcode['an'] = "Netherlands Antilles";
$landcode['ao'] = "Angola";
$landcode['aq'] = "Antarctica";
$landcode['ar'] = "Argentina";
$landcode['as'] = "American Samoa";
$landcode['at'] = "Austria";
$landcode['au'] = "Australia";
$landcode['aw'] = "Aruba";
$landcode['ax'] = "Aland Islands";
$landcode['az'] = "Azerbaijan";
		
$landcode['ba'] = "Bosnia and Herzegovina";
$landcode['bb'] = "Barbados";
$landcode['bd'] = "Bangladesh";
$landcode['be'] = "Belgium";
$landcode['bf'] = "Burkina Faso";
$landcode['bg'] = "Bulgaria";
$landcode['bh'] = "Bahrain";
$landcode['bi'] = "Burundi";
$landcode['bj'] = "Benin";
$landcode['bm'] = "Bermuda";
$landcode['bn'] = "Brunei Darussalam";	
$landcode['bl'] = "Saint Barthelemy";
$landcode['bn'] = "Brunei";
$landcode['bo'] = "Bolivia";
$landcode['br'] = "Brazil";
$landcode['bs'] = "Bahamas";
$landcode['bt'] = "Bhutan";
$landcode['bv'] = "Bouvet island";
$landcode['bw'] = "Botswana";
$landcode['by'] = "Belarus";
$landcode['bz'] = "Belize";
	
$landcode['ca'] = "Canada";
$landcode['cc'] = "Cocos Islands";
$landcode['cf'] = "Central African Republic";
$landcode['cg'] = "Congo";
$landcode['ch'] = "Switzerland";
$landcode['ci'] = "Cote d lvoire";
$landcode['ck'] = "Cook Islands";
$landcode['cl'] = "Chili";
$landcode['cm'] = "Cameroon";
$landcode['cn'] = "China";
$landcode['co'] = "Columbia";
$landcode['cr'] = "Costa Rica";
$landcode['cs'] = "Serbia en Montenegro";
$landcode['cu'] = "Cuba";
$landcode['cv'] = "Cape Verde";
$landcode['cx'] = "Christmas Island";
$landcode['cy'] = "Cyprus";
$landcode['cz'] = "Czech Republic";
	
$landcode['de'] = "Germany";
$landcode['dj'] = "Djibouti";
$landcode['dk'] = "Denmark";
$landcode['dm'] = "Dominica";
$landcode['do'] = "Dominican Republic";
$landcode['dz'] = "Algeria";
	
$landcode['ec'] = "Ecuador";
$landcode['ee'] = "Estonia";
$landcode['eg'] = "Egypt";
$landcode['eh'] = "Western Sahara";
$landcode['er'] = "Eritrea";
$landcode['es'] = "Spain";
$landcode['et'] = "Ethiopia";
$landcode['eu'] = "Cyberspace";
	
$landcode['fi'] = "Finland";
$landcode['fj'] = "Fiji";
$landcode['fk'] = "Falkland Islands";
$landcode['fm'] = "Micronesia";
$landcode['fo'] = "Faroe Islands";
$landcode['fr'] = "France";
	
$landcode['ga'] = "Gabon";
$landcode['gb'] = "United Kingdom";
$landcode['gd'] = "Grenada";
$landcode['ge'] = "Georgia";
$landcode['gf'] = "French Guiana";
$landcode['gh'] = "Ghana";
$landcode['gi'] = "Gibraltar";
$landcode['gl'] = "Greenland";
$landcode['gm'] = "Gambia";
$landcode['gn'] = "Guinea";
$landcode['gp'] = "Guadeloupe";
$landcode['gq'] = "Equatorial Guinea";
$landcode['gr'] = "Greece";
$landcode['gs'] = "Zuid-Georgia";
$landcode['gt'] = "Guatemala";
$landcode['gu'] = "Guam";
$landcode['gw'] = "Guinee-Bissau";
$landcode['gy'] = "Guyana";
	
$landcode['hk'] = "Hong Kong";
$landcode['hm'] = "Heard- en McDonald Islands";
$landcode['hn'] = "Honduras";
$landcode['hr'] = "Kroatia";
$landcode['ht'] = "Haiti";
$landcode['hu'] = "Hungary";
	
$landcode['id'] = "Indonesia";
$landcode['ie'] = "Ireland";
$landcode['il'] = "Israel";
$landcode['in'] = "India";
$landcode['im'] = "Isle of Man";
$landcode['io'] = "BI Ocean Territory";
$landcode['iq'] = "Iraq";
$landcode['ir'] = "Iran";
$landcode['is'] = "Iceland";
$landcode['it'] = "Italy";
	
$landcode['jm'] = "Jamaica";
$landcode['jo'] = "Jordan";
$landcode['jp'] = "Japan";
	
$landcode['ke'] = "Kenya";
$landcode['kg'] = "Kyrgyzstan";
$landcode['kh'] = "Cambodia";
$landcode['ki'] = "Kiribati";
$landcode['km'] = "Comores";
$landcode['kn'] = "Saint Kitts en Nevis";
$landcode['kp'] = "North Korea";
$landcode['kr'] = "South Korea";
$landcode['kw'] = "Kuwait";
$landcode['ky'] = "Cayman Islands";
$landcode['kz'] = "Kazachstan";
	
$landcode['la'] = "Laos";
$landcode['lb'] = "Lebanon";
$landcode['lc'] = "Saint Lucia";
$landcode['li'] = "Liechtenstein";
$landcode['lk'] = "Sri Lanka";
$landcode['lr'] = "Liberia";
$landcode['ls'] = "Lesotho";
$landcode['lt'] = "Lithuania";
$landcode['lu'] = "Luxembourg";
$landcode['lv'] = "Latvia";
$landcode['ly'] = "Libyan";
	
$landcode['ma'] = "Morocco";
$landcode['mc'] = "Monaco";
$landcode['md'] = "Moldova";
$landcode['mg'] = "Madagascar";
$landcode['mh'] = "Marshall Islands";
$landcode['mk'] = "Macedonia";
$landcode['ml'] = "Mali";
$landcode['mm'] = "Myanmar";
$landcode['mn'] = "Mongolia";
$landcode['mo'] = "Macao";
$landcode['mp'] = "Northern Mariana Islands";
$landcode['mq'] = "Martinique";
$landcode['mr'] = "Mauritania";
$landcode['ms'] = "Montserrat";
$landcode['mt'] = "Malta";
$landcode['mu'] = "Mauritius";
$landcode['mv'] = "Maldives";
$landcode['mw'] = "Malawi";
$landcode['mx'] = "Mexico";
$landcode['my'] = "Malaysia";
$landcode['mz'] = "Mozambique";
	
$landcode['na'] = "Namibia";
$landcode['nc'] = "New Caledonia";
$landcode['ne'] = "Niger";
$landcode['nf'] = "Norfolk Islands";
$landcode['ng'] = "Niger";
$landcode['ni'] = "Nicaragua";
$landcode['nl'] = "Netherlands";
$landcode['no'] = "Norway";
$landcode['np'] = "Nepal";
$landcode['nr'] = "Nauru";
$landcode['nu'] = "Niue";
$landcode['nz'] = "New Zealand";
	
$landcode['om'] = "Oman";
	
$landcode['pa'] = "Panama";
$landcode['pe'] = "Peru";
$landcode['pf'] = "French Polynesia";
$landcode['pg'] = "Papua New Guinea";
$landcode['ph'] = "Philippines";
$landcode['pk'] = "Pakistan";
$landcode['pl'] = "Poland";
$landcode['pm'] = "Saint Pierre and Miquelon";
$landcode['pn'] = "Pitcairn";
$landcode['pr'] = "Puerto Rico";
$landcode['ps'] = "Palestinian";
$landcode['pt'] = "Portugal";
$landcode['pw'] = "Palau";
$landcode['py'] = "Paraguay";
	
$landcode['qa'] = "Qatar";
	
$landcode['re'] = "Reunion";
$landcode['ro'] = "Romania";
$landcode['ru'] = "Russian Federation";
$landcode['rs'] = "Serbia";
$landcode['rw'] = "Rwanda";
	
$landcode['sa'] = "Saudi Arabia";
$landcode['sb'] = "Solomon Islands";
$landcode['sc'] = "Seychelles";
$landcode['sd'] = "Sudan";
$landcode['se'] = "Sweden";
$landcode['sg'] = "Singapore";
$landcode['sh'] = "Saint-Helena";
$landcode['si'] = "Slovenia";
$landcode['sj'] = "Svalbard and Jan Mayen";
$landcode['sk'] = "Slovakia";
$landcode['sl'] = "Sierra Leone";
$landcode['sm'] = "San Marino";
$landcode['sn'] = "Senegal";
$landcode['so'] = "Somalia";
$landcode['sr'] = "Suriname";
$landcode['st'] = "Sao Tome en Principe";
$landcode['sv'] = "El Salvador";
$landcode['sy'] = "Syria";
$landcode['sz'] = "Swaziland";
	
$landcode['tc'] = "Turks and Caicos Islands";
$landcode['td'] = "Chad";
$landcode['tg'] = "Togo";
$landcode['th'] = "Thailand";
$landcode['tj'] = "Tajikistan";
$landcode['tk'] = "Tokelau";
$landcode['tl'] = "Timor";
$landcode['tm'] = "Turkmenistan";
$landcode['tn'] = "Tunisia";
$landcode['to'] = "Tonga";
$landcode['tr'] = "Turkey";
$landcode['tt'] = "Trinidad and Tobago";
$landcode['tv'] = "Tuvalu";
$landcode['tw'] = "Taiwan";
$landcode['tz'] = "Tanzania";
	
$landcode['ua'] = "Ukraine";
$landcode['ug'] = "Uganda";
$landcode['um'] = "United States Minor Outlying Islands";
$landcode['us'] = "United States";
$landcode['uy'] = "Uruguay";	
$landcode['uz'] = "Uzbekistan";
	
$landcode['va'] = "Vatican City";
$landcode['vc'] = "Saint Vincent and the Grenadines";
$landcode['ve'] = "Venezuela";
$landcode['vg'] = "Virgin Islands; British";
$landcode['vi'] = "Virgin islands; US";
$landcode['vn'] = "Vietnam";
$landcode['vu'] = "Vanuatu";
	
$landcode['wf'] = "Wallis and Futuna";
$landcode['ws'] = "Samoa";
	
$landcode['ye'] = "Yemen";
$landcode['yt'] = "Mayotte";
	
$landcode['za'] = "South Africa";
$landcode['zm'] = "Zambia";
$landcode['zw'] = "Zimbabwe";
	
?>