package nl.warquest.database;
// Generated 17-mrt-2014 21:30:25 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ClanMission generated by hbm2java
 */
@Entity
@Table(name="clan_mission"
    ,catalog="warquest"
)
public class ClanMission  implements java.io.Serializable {


     private ClanMissionId id;
     private int progress;

    public ClanMission() {
    }

    public ClanMission(ClanMissionId id, int progress) {
       this.id = id;
       this.progress = progress;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="cid", column=@Column(name="cid", nullable=false) ), 
        @AttributeOverride(name="mid", column=@Column(name="mid", nullable=false) ) } )
    public ClanMissionId getId() {
        return this.id;
    }
    
    public void setId(ClanMissionId id) {
        this.id = id;
    }
    
    @Column(name="progress", nullable=false)
    public int getProgress() {
        return this.progress;
    }
    
    public void setProgress(int progress) {
        this.progress = progress;
    }




}


