package nl.warquest.database;
// Generated 17-mrt-2014 21:30:25 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lottery generated by hbm2java
 */
@Entity
@Table(name="lottery"
    ,catalog="warquest"
)
public class Lottery  implements java.io.Serializable {


     private Integer lotteryId;
     private Date expireDate;
     private int bet;
     private long money;
     private long gold;
     private int uid;
     private int uidAmount;
     private int bid;
     private int bidAmount;
     private int done;

    public Lottery() {
    }

    public Lottery(Date expireDate, int bet, long money, long gold, int uid, int uidAmount, int bid, int bidAmount, int done) {
       this.expireDate = expireDate;
       this.bet = bet;
       this.money = money;
       this.gold = gold;
       this.uid = uid;
       this.uidAmount = uidAmount;
       this.bid = bid;
       this.bidAmount = bidAmount;
       this.done = done;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="lottery_id", nullable=false)
    public Integer getLotteryId() {
        return this.lotteryId;
    }
    
    public void setLotteryId(Integer lotteryId) {
        this.lotteryId = lotteryId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expire_date", nullable=false, length=19)
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
    
    @Column(name="bet", nullable=false)
    public int getBet() {
        return this.bet;
    }
    
    public void setBet(int bet) {
        this.bet = bet;
    }
    
    @Column(name="money", nullable=false)
    public long getMoney() {
        return this.money;
    }
    
    public void setMoney(long money) {
        this.money = money;
    }
    
    @Column(name="gold", nullable=false)
    public long getGold() {
        return this.gold;
    }
    
    public void setGold(long gold) {
        this.gold = gold;
    }
    
    @Column(name="uid", nullable=false)
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }
    
    @Column(name="uid_amount", nullable=false)
    public int getUidAmount() {
        return this.uidAmount;
    }
    
    public void setUidAmount(int uidAmount) {
        this.uidAmount = uidAmount;
    }
    
    @Column(name="bid", nullable=false)
    public int getBid() {
        return this.bid;
    }
    
    public void setBid(int bid) {
        this.bid = bid;
    }
    
    @Column(name="bid_amount", nullable=false)
    public int getBidAmount() {
        return this.bidAmount;
    }
    
    public void setBidAmount(int bidAmount) {
        this.bidAmount = bidAmount;
    }
    
    @Column(name="done", nullable=false)
    public int getDone() {
        return this.done;
    }
    
    public void setDone(int done) {
        this.done = done;
    }




}


