package nl.warquest.database;
// Generated 17-mrt-2014 21:30:25 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name="stock"
    ,catalog="warquest"
)
public class Stock  implements java.io.Serializable {


     private Integer sid;
     private String symbol;
     private int gsid;
     private int pid;

    public Stock() {
    }

    public Stock(String symbol, int gsid, int pid) {
       this.symbol = symbol;
       this.gsid = gsid;
       this.pid = pid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="sid", nullable=false)
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    
    @Column(name="symbol", nullable=false, length=10)
    public String getSymbol() {
        return this.symbol;
    }
    
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }
    
    @Column(name="gsid", nullable=false)
    public int getGsid() {
        return this.gsid;
    }
    
    public void setGsid(int gsid) {
        this.gsid = gsid;
    }
    
    @Column(name="pid", nullable=false)
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }




}


